- service/service.go
- service/service_test.go
- testbed/testbed/otelcol_runner.go
SignalTestComplete shouldn't be in the public API and Application should provide a Shutdown method instead. This change is fixing the public API, behavior of Shutdown will be fixed in the future.
Fixes #2260.
> Rename SignalTestComplete to Shutdown

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
- exporter/prometheusremotewriteexporter/testutil_test.go
Currently, there is no limit on the size of the remote_write export request to a Cortex instance. This could create problems if one Prometheus scrape produces an extreme amount of timeseries metrics. 
This PR creates a batch of concurrent requests where the max size of a request is 3MB and the max number of timeseries per request is 40,000.
A future PR will tackle making the max size of each request configurable.
**Testing:** 
* Unit tests were fixed
* Performance tests were done with 15000 Prometheus metrics (around 100k timeseries) per scrape. The first and last metric of each Prometheus metric type were all found.
> Add batched exports to the Prometheus Remote Write Exporter 

- exporter/prometheusremotewriteexporter/config_test.go
- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/factory.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/testutil_test.go
A few changes:
- Removal of arbitrary whitespace
- Fixing the package godoc
- Use of canonical variable names such as req/resp
And more. Can't break any APIs right now otherwise would rename PrwExporter to Exporter.
> Fix a few readability issues on the prometheusremotewriteexporter

- .github/workflows/contrib-tests.yml
As part of [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/1234), this pull request migrates the contrib_test workflow that was contained in the config.yml file to GitHub Actions.
I suggest having CircleCI and GitHub Actions jobs run in parallel while the migration is in progress. In the last migration Pull Request, we will remove the existing CircleCI workflows.
A series of other PRs authored by @AzfaarQureshi and myself will be filed concurrently with this one migrating the build_and_test workflow in small chunks on the collector main repo and then on the collector-contrib repo.
cc- @alolita @AzfaarQureshi
> Migrate CircleCI contrib-test workflow to GitHub Actions

- processor/memorylimiter/README.md
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
- testbed/tests/trace_test.go
Contributes to https://github.com/open-telemetry/opentelemetry-collector/issues/1121
**Description**
Memory limiter processor previously had only one limit. When exceeding
this limit it was previously continuously calling GC. This resulted in
huge CPU consumption if the check interval was small and this was
forcing to use large check intervals. This in turn was resulting in
lethargic response to growing memory usage and the memory limiter was
not very effective in situations when memory usage were growing rapidly
(e.g. when there was a big spike or when the backend was down).
I changed the logic of memory limiter to be based on 2 thresholds:
soft and hard. While below soft threshold the memory limiter is fully disabled.
Between soft and hard limiter the limiter begins dropping incoming …
> Introduce soft and hard limits for memory limiter

- examples/k8s/otel-config.yaml
- Update Kubernetes config file for Agent and Collector to remove usage of the `queued_retry` processor.
The `queued_retry` processor is deprecated and each exporter adds support for this using the `exporterhelper`.
**Testing:** 
- Run `kubectl -f apply examples/k8s/otel-config.yml` and manually verify the setup works.
> [examples] Remove queued_retry processor from Kubernetes example

- cmd/otelcol/main_windows.go
- docs/troubleshooting.md
Adding a feature - adds a check for NO_WINDOWS_SERVICE environment variable on Windows to allow forcing interactive mode instead of running as a service.
This is required for using the collector in Windows Docker containers, as at least some of the Windows base images do not support services (fails with "The service process could not connect to the service controller"). Environment variable is used instead of automatic detection of Docker as it is uncertain if images that support services are possible and/or desired.
Running collector in Windows Docker containers is required to perform containerized integration tests of agents on Windows.
> Environment variable NO_WINDOWS_SERVICE to force interactive mode on Windows

- .github/workflows/build-and-test.yml
- .github/workflows/check-links.yaml
- .github/workflows/check-links/README.md
- .github/workflows/check-links/check-links.sh
- .github/workflows/check-links/config.json
- .github/workflows/check-links/markdown-link-check
As part of https://github.com/open-telemetry/opentelemetry-collector/issues/1234, this pull request migrates the windows-test, setup-environment, lint, and cross-compile workflow that was contained in the config.yml file to GitHub Actions. The remaining CI jobs will be migrated in PR 2/3 and the publish jobs will be migrated in 3/3
We suggest having CircleCI and GitHub Action jobs run in parallel for a few weeks. After the GitHub Actions jobs are running fine for a week or so and then remove the CircleCI workflows from config.yml
cc- @alolita, @shovnik
> Migrate CircleCI build-and-test workflow to GitHub Actions (1/3)

- examples/k8s/otel-config.yaml
**Description:** Change `endpoing` to `endpoint` in `examples/k8s/otel-config.yaml`
> Fix typo in examples/k8s/otel-config.yaml

- .github/workflows/build-and-test.yml
Related to [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/1234) and PR #2298 . This PR adds caching to the setup-environment job to make its runtime a little faster. 
cc- @alolita, @shovnik
> Adding caching to GHA setup-environment job

- .github/workflows/build-and-test.yml
- testbed/testbed/receivers.go
- testbed/tests/e2e_test.go
- testbed/tests/log_test.go
- testbed/tests/metric_test.go
As part of [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/1234), this pull request migrates the loadtest, correctness and build-package jobs to GitHub Actions. `windows-msi` and the publish jobs will be migrated in PR 3/3
We suggest having CircleCI and GitHub Action jobs run in parallel for a few weeks. After the GitHub Actions jobs are running fine for a week or so and then remove the CircleCI workflows from config.yml
cc- @alolita, @shovnik
> Migrate CircleCI workflows to GitHub Actions (2/3)

- .github/workflows/build-and-test.yml
Related to [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/1234) and PR #2298, this PR is caching make tools and changing all the upload/download actions to `@v1 ` for stability
> GitHub Actions Cache build-tools and change all upload/download actions to @v1

- receiver/fluentforwardreceiver/conversion.go
- receiver/fluentforwardreceiver/conversion_test.go
- receiver/fluentforwardreceiver/receiver_test.go
- Sometimes strings are received as []uint8
- fluentd uses "message", fluent-bit uses "log" for the log message
> [receiver/fluentforward] Fix string conversions

- .github/workflows/build-and-test.yml
- .github/workflows/scripts/set_release_tag.sh
- .github/workflows/scripts/setup_load_tests.sh
- .github/workflows/scripts/verify-dist-files-exist.sh
As part of [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/1234), this pull request does some naming changes and refactoring on the already migrated build_and_test workflows jobs in preparation for migrating the remaining `windows-msi`, `publish-dev` and `publish-stable` jobs in the following [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/2299)
This PR must be reviewed and merged before merging the final [migration PR](https://github.com/open-telemetry/opentelemetry-collector/pull/2299). The purpose of this PR is to remove changes to existing jobs from the final migration PR.
- All step names are consistent across jobs (descriptive and capitalized except articles/prepositions)
- Bash logic that is complex or to be reused in the new jobs was …
> Refactor build_and_tests GHA workflow before for migrating publish jobs

- .github/workflows/build-and-test.yml
- internal/buildscripts/packaging/msi/make.ps1
As part of [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/1234), this pull request completes the migration to GitHub Actions for the core repo by migrating the remaining `windows-msi` and publish jobs to GHA. The `publish-check` job was intentionally omitted as it seems to only print a success or fail message of the binaries and distributions were successfully created, but does not actually accomplish any task. Let me know if it served an important purpose I might have missed.
When merging this PR, once the repository is ready to move publishing from CircleCI to GHA, a maintainer will need to add the DOCKER_USERNAME and DOCKER_PASSWORD secrets for the opentelemetry docker account to allow pushing to docker. In addition a token with all access writes will need to …
> Migrate CircleCI workflows to GitHub Actions (3/3)

- .github/workflows/build-and-test.yml
This refactor [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/2313) I authored accidentally introduced an error into the build-and-test workflow which prevents the load-tests job from running altogether and fails every run of the build-and-test workflow. This one line fix should resolve the issue and allow the build-and-test workflow to pass once again.
**Link to tracking Issue:** #1234 
**Testing:** Workflow was run locally and it now runs load tests as intended.
cc- @AzfaarQureshi
> Fix build-and-test GitHub Actions workflows

- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_metadata.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others_linux.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
Add disk/weighted_io_time metric (Linux only)
> Add disk/weighted_io_time metric (Linux only)

- extension/pprofextension/pprofextension.go
Flush out the write buffer to the output profile file during the graceful shutdown. Ignore the Close error, trying to flush is the best we can do but is not worth to halt the shutdown if Close fails.
> Flush out to the profile file before graceful shutdown

- .github/workflows/codeql-analysis.yml
Follow up to issue https://github.com/open-telemetry/oteps/issues/144
[CodeQL](https://github.com/github/codeql-action) is GitHub's static analysis engine which scans repos for security vulnerabilities. As the project grows and we near GA it might be useful to have a workflow which checks for security vulnerabilities with every PR so we can ensure every incremental change is following best development practices. Also passing basic security checks will also make sure that there aren't any glaring issues for our users.
* This PR adds [CodeQL](https://github.com/github/codeql-action) security checks to the repo
* After every run the workflow uploads the results to GitHub. Details on the run and security alerts will show up in the `security` tab of this repo.
**Workflow Triggers**
* daily …
> [1/2] Add Security workflows: CodeQL scan workflow

- translator/trace/zipkin/zipkinv2_to_traces.go
- translator/trace/zipkin/zipkinv2_to_traces_test.go
This PR addresses https://github.com/open-telemetry/opentelemetry-collector/issues/2214 and, by extension, https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1644. ZipkinV2 internal translation was not taking into account the `error` tag. As mentioned in this Specification PR https://github.com/open-telemetry/opentelemetry-specification/pull/1257, and confirmed by @owais , any presence of the [`error` tag should be used to indicate a span status of `Error`](https://github.com/open-telemetry/opentelemetry-specification/pull/1257/files#diff-c50b2cac17490acd52955c504c267e15e9b8f1bfd51f15e02369cb1c83071e13R149) and is also [overriding on any other tag that denotes status for zipkin](https://github.com/open-telemetry/opentelemetry-specification/pull/1257/ …
> fix zipkinv2 translation error tag handling

- exporter/opencensusexporter/config.go
- exporter/opencensusexporter/config_test.go
- exporter/opencensusexporter/factory.go
- exporter/opencensusexporter/opencensus.go
- exporter/opencensusexporter/testdata/config.yaml
> Add queue-retry for opencensus exporter

- consumer/pdata/trace_test.go
- consumer/pdata/traceid.go
**Description:**  Add the new method that equals to calling !data.TraceID(t).IsValid() for
the internal data.TraceID.
**Link to tracking Issue:** #2014
> Add pdata TraceID.IsEmpty() method

- internal/buildscripts/packaging/fpm/common.sh
The build deb package job is a little flaky due to the following err:
```
Installing otel-collector_0.17.0-post_amd64.deb ...
Error response from daemon: Error processing tar file(exit status 1): lchown /tmp/otel-collector_0.17.0-post_amd64.deb: no such file or directory
Error: Process completed with exit code 1.
```
I suspect the problem is in line 43 of common.sh where `dpkg -i` is called before the `docker cp` is complete. Adding a sleep and another instruction between the two steps seemed to fix the flakiness on my fork
> GitHub Actions - fixing flaky build package job

- consumer/consumer.go
- consumer/pdata/metric.go
- Fix comments introduced in #1720 that kept the old name (MetricsData) instead of the new one (Metrics)
**Testing:** n/a this is a docs change
**Documentation:** Updated strings that used the old name.
> [consumer] Fix comments referencing MetricsData

- examples/demo/app/main.go
Pusher was missing in the metric controller creation. Due to this no metrics
were exported at all.
Added pusher similar to this example: https://github.com/open-telemetry/opentelemetry-go/blob/c066f15ed74fec52c4755014bfcf2bdfb8e0e661/example/otel-collector/main.go#L81
Tested with Collector and verified that now metrics are exported.
Also renamed "pusher" to "cont" since it is not a Pusher but a Controller.
> Fix broken metrics exporting in the example

- Makefile
`v0.18.0-16-g4721f834` - the current head of my current branch is based on v0.18.0, but since it has a few commits on top of that, describe has added the number of additional commits ("16") and an abbreviated object name for the commit itself ("4721f834") at the end.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2382
> Determine the version using git describe

- internal/version/version.go
- service/service.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/2382
> Add uptime to the servicez debug page

- exporter/jaegerexporter/exporter.go
- exporter/jaegerexporter/exporter_test.go
- exporter/jaegerexporter/metrics.go
- exporter/jaegerexporter/metrics_test.go
- service/telemetry.go
Adds a connection state reporter to the Jaeger exporter sending state changes to the log and as a metric.
**Link to tracking Issue:** Closes #1861, as it's the best we can do at this exporter level. On a more general level, the collector could provide more verbose info about the underlying gRPC connections. See #2237 for more information.
**Testing:** unit and manual tests.
**Documentation:** None.
Here are the complete logs for an OpenTelemetry Collector that got started without a Jaeger backend available. Note that the config.yaml contains two exporters, one (`jaeger`) with the `insecure: true` option, and a second one (`jaeger/2`) without this option. A Jaeger all-in-one is then started, without TLS support. This ends with the first exporter eventually transitioning …
> Improve connection state logging for Jaeger exporter

- cmd/pdatagen/internal/base_slices.go
This was not a problem in the generated code because slice of values is used only with `AnyValue` for the moment.
> Fix slice of values generated code

- internal/processor/filterset/config.go
- internal/processor/filterset/strict/strictfilterset.go
- internal/processor/filterset/strict/strictfilterset_test.go
> Avoid returning always nil error in strict filterset

- consumer/pdata/common.go
- consumer/pdata/common_test.go
Adding support for array type for `AttributeValue` equal. This is according to the spec - https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md
**Testing:**
Added test for array of scalar types
> Add equal for AttributeValue arrays type

- testbed/testbed/data_providers.go
- testbed/tests/testdata/k8s-metrics.json
- testbed/tests/trace_test.go
FileDataProvider in an implementation of the DataProvider for use in end-to-end tests.
The data to send is loaded from a file. The file should contain one JSON-encoded
Export*ServiceRequest Protobuf message. The file can be recorded using the "file"
exporter.
FileDataProvider is useful for implementing end-to-end tests that use realistic data.
As an example I also added TestMetricsFromFile which uses testdata/k8s-metrics.json
real world data that I recorded using k8scluster receiver running on my local
Kubernetes cluster.
> Add FileDataProvider to the testbed

- processor/batchprocessor/splittraces.go
While working on #2422, @bogdandrutu suggested I make this performance enhancement to metrics so I figure it should be applied here as well.
> Avoid extra allocations in splittraces

- processor/batchprocessor/README.md
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/splitmetrics.go
- processor/batchprocessor/splitmetrics_test.go
During #2220 @arminru discovered that the max batch size was only applied to spans. This applies the same logic to metrics.
> Support max batch size for metrics

- testbed/testbed/child_process.go
When the process is terminated its CPU time calculation could be incorrect since 
gopsutil sometimes returns CPU times that are lower than previously returned times.
This was resulting in negative CPU time delta, which was then converted to uint32
percent resulting in overflowing of the negative number into large positive number
and very large incorrect CPU percentages shown.
This changes fixes the problem by ensuring the calculated CPU time delta is never
negative.
> Show correct CPU usage when the process is terminated early

- CONTRIBUTING.md
**Description:** Repository named `opentelemetry-collector` but CONTRIBUTING guide refers to it as `opentelemetry-service`
**Documentation:** links with `opentelemetry-service` have been changed to `opentelemetry-collector`
> Contibuting: rename opentelemetry-service to opentelemetry-collector

- config/configcheck/configcheck.go
- consumer/consumererror/combineerrors.go
- consumer/consumererror/combineerrors_test.go
- exporter/kafkaexporter/jaeger_marshaller.go
- exporter/prometheusremotewriteexporter/exporter.go
- processor/cloningfanoutconnector.go
- processor/fanoutconnector.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/scraperhelper/errors.go
- receiver/scraperhelper/scrapercontroller.go
- receiver/scraperhelper/scrapercontroller_test.go
- service/builder/exporters_builder.go
- service/builder/extensions_builder.go
- service/builder/pipelines_builder.go
- service/builder/receivers_builder.go
- service/defaultcomponents/defaults.go
- service/service.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2472
> Move CombineErrors to consumererror package

- exporter/otlpexporter/otlp.go
I was troubleshooting an issue where un-retryable exports were being retried. #2455 fixes the root cause and this PR improves error messages from the OTLP exporter. The exporter returns the same permanent error instance for each export which masks the underlying error and makes failures hard to debug. This PR preserves the original error by wrapping it in a permament error and returning it.
Previously all log message looked as follows:
```
failed to push metrics data via OTLP exporter: Permanent error: fatal error sending to server
```
Now they preserve the original error message:
```
failed to push metrics data via OTLP exporter: Permanent error: rpc error: code = InvalidArgument desc = [otlp: empty data point]
```
> Preserve original error messages in OTLP exporter

- docs/security.md
Capture relevant security information and considerations.
Attempts to address:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2230
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2231
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2232
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2233
> Add an initial security document

- docs/security.md
Fixed typo in security documentation. 
N/A
**Testing:**
N/A
N/A
> Fixed typo in security documentation

- receiver/prometheusreceiver/DESIGN.md
Signed-off-by: albertteoh <albert.teoh@logz.io>
Fix some minor typos and grammatical issues from the prometheus receiver's DESIGN.md doc.
> Fix minor typos and grammatical issues in prometheus design doc

- receiver/zipkinreceiver/trace_receiver.go
The problem mentioned in the comment was with the thrift version, now fixed.
> Remove copied code in zipkin receiver, use the source

- .github/workflows/build-and-test.yml
> Use cached tools instead of uploading to the artifacts for the tools

- exporter/otlphttpexporter/README.md
- exporter/otlphttpexporter/config.go
- exporter/otlphttpexporter/config_test.go
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
- exporter/otlphttpexporter/testdata/config.yaml
- internal/middleware/compression.go
- internal/middleware/compression_test.go
- testbed/testbed/receivers.go
- testbed/tests/trace_test.go
The default value of "compression" option is empty and results in no compression,
which is the same as the old behavior. You can also specify "compression: gzip"
which will result in gzip encoding of outgoing http requests.
> Add "compression" option to otlphttp exporter

- translator/trace/zipkin/consumerdata.go
- translator/trace/zipkin/zipkinv1_thrift_to_protospan.go
- translator/trace/zipkin/zipkinv1_to_protospan.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
> Change zipkin translator to not use consumerdata

- config/confighttp/README.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- receiver/otlpreceiver/README.md
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/testdata/config.yaml
Fixes #1383 by exposing ability to set CORS Allowed Headers
**Link to tracking Issue:** #1383 
**Testing:** Config unit tests updated, manual tests performed with requests sent from browser via OpenTelemetry-JS to another domain (where the collector was residing)
**Documentation:** Description of the newly added option added
> Add cors_allowed_headers option to confighttp

- component/componenttest/example_factories.go
- component/receiver.go
- consumer/pdata/trace.go
- exporter/README.md
- exporter/exporterhelper/tracehelper_test.go
- obsreport/obsreport_receiver.go
- processor/README.md
- processor/cloningfanoutconnector.go
- processor/fanoutconnector.go
- processor/probabilisticsamplerprocessor/probabilisticsampler_test.go
- receiver/prometheusreceiver/internal/transaction.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/2482
> Update docs and code comments to not refer to old consumerdata

- CHANGELOG.md
- cmd/pdatagen/internal/trace_structs.go
- consumer/pdata/generated_trace.go
- consumer/pdata/generated_trace_test.go
- consumer/pdata/trace.go
- consumer/pdata/trace_test.go
- receiver/otlpreceiver/trace/otlp.go
- receiver/otlpreceiver/trace/otlp_test.go
Updates #2488
The previous logic was to ignore deprecated if received non unset for new status code,
but if downstream a service is not upgraded it should see the deprecated status set correctly.
This change is to be consistent with `SetCode`.
> Remove accessors for deprecated status code, fix receiver logic

- component/component.go
Clarifies that components should not accept anymore data on shutdown 
Ping @bogdandrutu 
Closes #2481
> docs(component): improves the documentation

- cmd/schemagen/go.sum
- exporter/kafkaexporter/README.md
- exporter/kafkaexporter/authentication.go
- exporter/kafkaexporter/authentication_test.go
- exporter/kafkaexporter/scram_client.go
- go.mod
- go.sum
This PR adds SASL/SCRAM authentication to kafka receiver and exporter.
#2252
**Testing:** 
Unit Tests 
Added to Readme
> Add SASL/SCRAM authentication mechanism on kafka receiver and exporter

- testbed/tests/trace_test.go
The test is very close to the limit (e.g. 149MB) or exceeds it and fails.
Bumping the limits to make sure it succeeds.
> Increase memory limit for TestTraceNoBackend10kSPS

- .github/workflows/build-and-test.yml
- Makefile
- Makefile.Common
> Improve caching for go actions, add go build cache

- CONTRIBUTING.md
Description:
Added step to add new components to the OpenTelemetry.io registry
Same commit to contrib: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2465
N/A
Testing:
N/A
Documentation:
N/A
Signed-off-by: Granville Schmidt 1246157+gramidt@users.noreply.github.com
> Added step to add new components to the OpenTelemetry.io registry

- CHANGELOG.md
- consumer/consumerdata/consumerdata.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/2482
> Remove consumerdata.TraceData

- internal/goldendataset/metric_gen.go
- internal/goldendataset/metric_gen_test.go
- internal/goldendataset/pict_metric_gen.go
- processor/filterprocessor/expr_test.go
- processor/filterprocessor/filter_processor_test.go
- testbed/correctness/metrics/metric_diff_test.go
> Fix comments and func names in goldendataset metrics

- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
Ensure that the receiver finishes all ongoing requests, and does not accept any new request after shutdown is finished.
> Fix OTLP receiver Shutdown() bug

- CHANGELOG.md
- internal/goldendataset/span_generator.go
- translator/conventions/opencensus.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/oc_testdata_test.go
- translator/internaldata/oc_to_resource.go
- translator/internaldata/oc_to_traces.go
- translator/internaldata/resource_to_oc.go
- translator/internaldata/resource_to_oc_test.go
- translator/internaldata/traces_to_oc.go
- translator/trace/zipkin/zipkinv2_to_traces.go
> Replace custom opencensus sematic conventions with otel semantic conventions

- receiver/prometheusreceiver/README.md
I've helped at least 4 people at this point whose problems using the prometheus receiver came down to using $ characters without escaping them.  Its a common enough problem, i'd like to add warnings to more places.  The Readme seems like a good place to start
Issues:
https://github.com/open-telemetry/opentelemetry-collector/issues/557 added docs to opentelemetry.io, but not in the repo.  https://github.com/open-telemetry/opentelemetry-collector/issues/1077#issuecomment-638801113 is an example of someone confused about this as well.
> Add note about escaping $ in prometheus config

- component/componenttest/shutdown_verifier.go
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
I added a Shutdown() test that does basic verification of the behavior of the
Shutdown() function. More verifications can be added later.
The test revealed a bug in batchprocessor Shutdown() function which would
not wait until all pending data was drained.
> Fix Shutdown behavior for batchprocessor

- internal/goldendataset/traces_generator.go
- internal/goldendataset/traces_generator_test.go
- testbed/correctness/traces/correctness_test.go
- testbed/testbed/data_providers.go
- testbed/testbed/data_providers_test.go
- translator/internaldata/resource_to_oc_test.go
- translator/internaldata/traces_to_oc_test.go
- translator/trace/jaeger/traces_to_jaegerproto_test.go
- translator/trace/zipkin/traces_to_zipkinv2_test.go
> Change goldendataset trace to return pdata

- CHANGELOG.md
- exporter/prometheusexporter/prometheus_test.go
- processor/filterprocessor/filter_processor_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/metrics_receiver_test.go
- translator/internaldata/consumerdata.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/oc_testdata_test.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_metrics_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2482
> Move MetricsData to internaldata

- .gitignore
.devcontainer is used by VS Code to develop from docker images.
> Add .devcontainer dir to .gitignore

- cmd/issuegenerator/go.mod
- cmd/issuegenerator/go.sum
- cmd/schemagen/go.sum
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
- go.mod
- go.sum
Dependabot does not update deps which are pinned (specific commit), or don't have go mod.
> Update deps which dependabot cannot update

- translator/conventions/trace_exporters.go
- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerproto_to_traces_test.go
- translator/trace/jaeger/traces_to_jaegerproto.go
- translator/trace/protospan_translation.go
- translator/trace/zipkin/traces_to_zipkinv2.go
- translator/trace/zipkin/zipkinv2_to_traces.go
> Add semantic conventions for instrumentation library, switch to use this new one

- exporter/loggingexporter/logging_exporter.go
When span was containing several events, only the first one was printed out by the logging exporter. After checking the code it, turned out that handling the case with no attributes returns from the iteration loop altogether, which is wrong. The same bug was introduced for span links.
**Testing:** Just manual tests performed for Span Events
> loggingexporter: fix handling the loop for empty attributes

- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
Add printing map to logging exporter.
Currently maps are printed as `<Unknown OpenTelemetry attribute value type MAP>`. An idea of the PR is to put it in more usable form. Nested maps are stringified jsons
Example output:
```
Some text: {
-> foo: STRING(test)
-> zoo: MAP({"bar":13})
}
````
**Testing:**
unit tests
> loggingexporter: add support for AttributeMap

- docs/troubleshooting.md
I was, somewhat meta, troubleshooting to ensure the agent was starting correctly, so I ran the sample cURL:
```
> curl -X POST localhost:9411/api/v2/spans -H'Content-Type: application/json' -d '[ { "traceId": "5982fe77008310cc80f1da5e10147519", "parentId": "90394f6bcffb5d13", "id": "67fae42571535f60", "kind": "SERVER", "name": "/m/n/2.6.1", "timestamp": 1516781775726000, "duration": 26000, "localEndpoint": { "serviceName": "api" }, "remoteEndpoint": { "serviceName": "apip" }, "tags": { "data.http_response_code": "201", } } ]'
invalid character '}' looking for beginning of object key string
>
```
I spotted a trailing comma after the response code. Removing it solved the issue:
```
> curl -X POST localhost:9411/api/v2/spans -H'Content-Type: application/json' -d '[ { …
```
> Fix sample JSON in cURL request in troubleshooting.md

- config/configgrpc/README.md
Closes #2508 by clarifying how the PerRPCAuth option differs from an `authorization` header sent when a connection is first established.
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Clarify the difference between auth header and per-RPC auth

- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
- exporter/prometheusremotewriteexporter/testutil_test.go
fixes  #2608
~Ensure that the metric name is greater than the length of the
counter suffix ("_total") before checking if it contains the counter
suffix to prevent crashes for short (smaller or eq to the length of the
suffix) metric names.~
~The edge case where the metric name is "_total" is not handled (considered
not to have the suffix), but should not occur IRL.~
edit: Use `strings.hasSuffix()` to check if metric name has the counter suffix ("_total")
Also fix the spelling of "delimiter".
warning: this is one of my first PRs in Go 😅
> [prometheusremotewrite] fix: counter name check 

- consumer/consumertest/sink.go
- consumer/consumertest/sink_test.go
- internal/internalconsumertest/err_or_sink_consumer.go
- receiver/opencensusreceiver/opencensus_test.go
- receiver/otlpreceiver/otlp_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2477
> Remove SetConsumerError from sink test helpers

- service/builder/exporters_builder.go
- service/builder/exporters_builder_test.go
- service/builder/extensions_builder.go
- service/builder/pipelines_builder.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
- service/service.go
> Simplify builders for components, remove unnecessary builders

- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/tracehelper.go
- exporter/prometheusexporter/prometheus.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
since obsreport is the package name
fixes #2642
> Rename `ExporterObsReport` to `Exporter`

- obsreport/obsreport.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_test.go
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
since obsreport is the package name.
Fixes #2639
> Rename `ProcessorObsReport` to `Processor`

- CHANGELOG.md
- consumer/fanoutconsumer/cloningconsumer.go
- consumer/fanoutconsumer/cloningconsumer_test.go
- consumer/fanoutconsumer/consumer.go
- consumer/fanoutconsumer/consumer_test.go
- service/internal/builder/pipelines_builder.go
- service/internal/builder/receivers_builder.go
> Move fanout consumers to fanoutconsumer package

- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/tracehelper.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
> Remove obsreport.ExporterContext, always add exporter name as a tag to the metrics

- exporter/exporterhelper/common.go
- exporter/exporterhelper/factory_test.go
- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/logshelper_test.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/jaegerexporter/exporter.go
- exporter/kafkaexporter/kafka_exporter.go
- exporter/kafkaexporter/kafka_exporter_test.go
- exporter/loggingexporter/logging_exporter.go
- exporter/opencensusexporter/opencensus.go
- exporter/otlpexporter/otlp.go
- exporter/otlphttpexporter/otlp.go
- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/zipkinexporter/zipkin.go
Even in code for metrics we did not have a consistent implementation,
also most important thing was not used anymore in observability helper.
> Remove the number of items from returned values in Push funcs

- receiver/kafkareceiver/factory_test.go
- receiver/kafkareceiver/kafka_receiver_test.go
- receiver/kafkareceiver/otlp_unmarshaller.go
- receiver/kafkareceiver/otlp_unmarshaller_test.go
- receiver/kafkareceiver/unmarshaller.go
> Change Kafka receiver to not use internal data

- receiver/zipkinreceiver/proto_parse_test.go
> Change Zipkin receiver to not use internal data

- README.md
@james-bebbington is currently working on something else and cannot allocate time to the Collector. 
James, thanks for you work on the Collector, you are welcome back anytime in the future.
> Removing james-bebbington as an approver

- consumer/pdata/log.go
- consumer/pdata/log_test.go
- exporter/fileexporter/file_exporter.go
- exporter/fileexporter/file_exporter_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- internal/otlp_wrapper.go
- internal/testdata/log.go
- internal/testdata/log_test.go
- receiver/otlpreceiver/logs/otlp.go
- receiver/otlpreceiver/logs/otlp_test.go
- testbed/testbed/data_providers.go
Tested in contrib and was able to access InternalWrapper.Orig,
with this change this is no longer possible.
Also removes one extra allocation for the request object when 
using otlp receiver/exporter since we keep the initial pointer around.
> Use otlp request in wrapper, hide members in the wrapper

- consumer/pdata/metric.go
- consumer/pdata/metric_test.go
- consumer/simple/metrics_test.go
- exporter/fileexporter/file_exporter.go
- exporter/fileexporter/file_exporter_test.go
- exporter/kafkaexporter/otlp_marshaller_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- internal/otlp_wrapper.go
- internal/testdata/metric.go
- internal/testdata/metric_test.go
- receiver/otlpreceiver/metrics/otlp.go
- receiver/otlpreceiver/metrics/otlp_test.go
- testbed/testbed/data_providers.go
- testbed/tests/resource_processor_test.go
> Add MetricsWrapper to dissallow access to internal representation

- consumer/pdata/trace.go
- consumer/pdata/trace_test.go
- exporter/fileexporter/file_exporter.go
- exporter/fileexporter/file_exporter_test.go
- exporter/kafkaexporter/otlp_marshaller_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- internal/goldendataset/traces_generator.go
- internal/otlp_wrapper.go
- internal/testdata/trace.go
- internal/testdata/trace_test.go
- receiver/kafkareceiver/otlp_unmarshaller.go
- receiver/kafkareceiver/otlp_unmarshaller_test.go
- receiver/otlpreceiver/marshal_jsonpb_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/otlpreceiver/trace/otlp.go
- receiver/otlpreceiver/trace/otlp_test.go
- testbed/testbed/data_providers.go
- testbed/testbed/validator.go
- translator/internaldata/resource_to_oc_test.go
> Add TracesWrapper to dissallow access to internal representation

- consumer/pdata/log.go
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
> Rename pdata.Logs.SizeBytes to Size, consistent with metrics/traces

- exporter/prometheusexporter/collector.go
- exporter/prometheusexporter/collector_test.go
This fixes #2700
This fix allows the prometheus exporter to work with standard labels that follow the naming convention of using periods instead of underscores.
https://github.com/open-telemetry/opentelemetry-collector/issues/2700
**Testing:**
I will add tests in a second commit
No additional documentation added, is it worth mentioning?
> Sanitize prometheus labels

- config/configtls/README.md
Fixing example configuration bug. The `client_ca_file` option was under the wrong section.
**Testing:**
Ran locally. This config worked, previous did not.
> Fix client_ca_file config section

- receiver/prometheusreceiver/metrics_receiver.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Fix the issue #2533 which the prometheus `receiver` and `exporter` names are not correctly propagated via the context.
**Link to tracking Issue:** #2533
Only tested manually with the config below:
```
receivers:
otlp:
protocols:
http:
prometheus:
config:
scrape_configs:
- job_name: "otel-collector"
scrape_interval: 5s
static_configs:
- targets: ["localhost:8888"]
processors:
batch:
extensions:
health_check: {}
exporters:
prometheusremotewrite:
endpoint: "http://localhost:9090/api/v1/write"
insecure: true
external_labels:
server: otel
prometheus:
endpoint: "0.0.0.0:8081"
namespace: test-space
const_labels:
label1: value1
send_timestamps: true …
```
> Propogate name and transport for prometheus receiver and exporter

- consumer/pdata/log.go
- consumer/pdata/metric.go
- consumer/pdata/metric_test.go
- consumer/pdata/trace.go
- consumer/pdata/trace_test.go
- exporter/exporterhelper/queued_retry_test.go
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
> Rename pdata Size to OtlpProtoSize, fix some other comments

- component/component.go
This clarifies the phases of the lifecycle of Component.
> Clarify Component lifecycle

- service/defaultcomponents/default_exporters_test.go
- service/defaultcomponents/default_extensions_test.go
- service/defaultcomponents/default_processors_test.go
- service/defaultcomponents/default_receivers_test.go
Add lifetime tests to remaining default components in line with https://github.com/open-telemetry/opentelemetry-collector/pull/2679. This allows changing the components without restarting the process.
Description:
Separate the default components test per type of component and also allow to run the test for a single component. Some receivers are not being tested for lifecycle in this PR:
- Zipkin and OTLP receiver (I will have PRs to fix these soon)
- Kafka receiver: requires access to the internals of the receiver to perform a successful Start call
- OpenCensus: can't be properly stopped due to usage CMux (the CMux listener Accept calls block forever)
> Add lifecycle tests to all default components 

- examples/demo/app/Dockerfile
- examples/demo/app/main.go
- examples/demo/docker-compose.yaml
**Description:** Updated the demo metrics generator application to build a container image rather than using `go run main.go` inside a `go:1.12` image.  Also updated the metrics generator application to use a `go:1.14` image as Go 1.12 is no longer supported.
**Testing:** Application was started with `docker-compose up -d` and metrics were observed via the Prometheus container.
> Update demo app to build image

- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
- service/defaultcomponents/default_receivers_test.go
To allow the OTLP receiver to be created while one instance is already running. This allows changing the components without restarting the process. See related #2741
Move the registration of the receiver servers to when the receiver is started. Also check in the goroutines serving requests if the errors are not the ones expected when shutting down the receiver (avoid useless calls to ReportFatalError).
**Tests:**
Added tests to the otlp package to check for the issues being fixed.
> Allow multiple OTLP to be created

- service/defaultcomponents/default_extensions_test.go
Fixes #2738 by selecting available endpoints and ports for the default extensions tests.
> Make default extensions test more resilient

- receiver/opencensusreceiver/opencensus.go
- receiver/otlpreceiver/otlp.go
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
- service/defaultcomponents/default_receivers_test.go
Zipkin shutdown method was returning before its server goroutine was completed and not checking for the expected `http.ErrServerClosed`. This PR ensures shutdown only returns after the goroutine completes, no errors are reported when the server is closed. Opportunistic fix: remove an improper call to `ReportFatalError` for a synchronous error when the port is already in use.
**Testing:**
Enabled lifecycle test for Zipkin receiver.
> Ensure Zipkin shutdown correctness

- consumer/pdata/common.go
- consumer/pdata/log.go
- consumer/pdata/metric.go
- consumer/pdata/trace.go
This is not the case right now (we are not using type aliasing, but type definition), but to avoid any possible future mistakes better to define the enums as `int32`. Also fixes other places where we define enums as int and change them to `int32` for consistency.
> Avoid exposing internal types via type aliasing

- service/internal/builder/exporters_builder.go
- service/internal/builder/extensions_builder.go
- service/internal/builder/host_wrapper.go
- service/internal/builder/host_wrapper_test.go
- service/internal/builder/pipelines_builder.go
- service/internal/builder/receivers_builder.go
Improve the log msg for ReportFatalError. The message now includes the component information added by the builder to any ReportFatalError. The error message is also logged before calling the app.ReportFatalError this way all components reporting errors are recorded even if the app doesn't pick that notification. The log inside the app is kept so it is clear which one triggered the shutdown.
Processors are not wrapped with a "built" structure but are also, typically, do not report fatal errors.
**Testing:**
- Manually verified the message by forcing component errors.
> Add a host wrapper  to improve ReportFatalError msg

- exporter/exporterhelper/factory.go
> Use Traces instead of Trace in exporterhelper

- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/tracehelper.go
- exporter/prometheusexporter/prometheus.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
> configure obsReport.NewExporter with struct

- processor/batchprocessor/README.md
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/splitlogs.go
- processor/batchprocessor/splitlogs_test.go
Similar to https://github.com/open-telemetry/opentelemetry-collector/pull/2422, this adds support for `send_batch_max_size` to batch processor for logs.  Meaning this parameter is now supported for traces, metrics and logs (previously only traces and metrics were supported).
> Support max batch size for logs

- service/defaultcomponents/default_extensions_test.go
Missed use of custom config on the extension tests.
> Fix extension tests

- config/internal/configsource/component.go
Add a watcher to the retrieved values plus renamed Apply to Retrieve.
> Add watcher to values retrieved via config sources

- CHANGELOG.md
- extension/healthcheckextension/README.md
- extension/healthcheckextension/config.go
- extension/healthcheckextension/config_test.go
- extension/healthcheckextension/factory.go
- extension/healthcheckextension/factory_test.go
- extension/healthcheckextension/healthcheckextension.go
- extension/healthcheckextension/healthcheckextension_test.go
- extension/healthcheckextension/testdata/config.yaml
- service/application_test.go
- service/defaultcomponents/default_extensions_test.go
Change health check extension's config to use `Endpoint` instead of `Port`, fix tests according to the changes.
**Link to tracking Issue:** #2764
> Use Endpoint for health check extention

- .github/workflows/check-links.yaml
fix check links when no markdown file changed still failed
resolved #2814
> upgrade check links used node tls version (14)

- CHANGELOG.md
- config/configparser/config.go
- config/parser.go
- receiver/hostmetricsreceiver/factory.go
- receiver/jaegerreceiver/factory.go
- receiver/otlpreceiver/factory.go
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/factory.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2735
> Change CustomUnmarshaler implementations to use config.Parser, prove the interface

- receiver/jaegerreceiver/trace_receiver.go
Escape the error message sent to clients, containing user-provided input.
Theoretically, this could allow an attacker to perform a reflected cross-site scripting attack. In my view, this would be hardly exploitable, as the Jaeger Receiver has Jaeger Client as the only clients, and browsers would have to be tricked into making requests directly to it with the bad payload. On the way out, the browser would interpret the Jaeger Receiver as a single domain, as each protocol is on its own port. No session data, or any other type of senstive information, would be available for the attacker to extract.
In any case, this here fixes the theoretical case, especially to prevent this from being used in a composite attack in a scenario that I can't think of...
> Escape user input used in output

- internal/buildscripts/packaging/fpm/common.sh
- internal/buildscripts/packaging/fpm/deb/build.sh
- internal/buildscripts/packaging/fpm/otel-collector.conf
- internal/buildscripts/packaging/fpm/otel-collector.service
- internal/buildscripts/packaging/fpm/rpm/build.sh
Include a systemd environment file in the deb/rpm packages for the `otel-collector` service that allows the user to configure the otelcol startup options and add custom environment variables when running the collector as a service.  Default otelcol option is `--config=/etc/otel-collector/config.yaml`.
#2255 
**Testing:**
Tested locally and in CI.
https://github.com/open-telemetry/opentelemetry.io/pull/500
> Add systemd environment file for deb/rpm packages

- config/internal/configsource/component.go
Small refinements to the configsource interface:
- Changing Retrieved to interface;
- Separating the watching capability in a separate interface: WatchableRetrieved;
- Adding a specific error to signal that the watched value was updated;
> Refine configsource interface

- extension/healthcheckextension/README.md
- extension/healthcheckextension/config.go
- extension/healthcheckextension/factory.go
This commits brings back default configuration of the health_check extension to make sure it works in k8s-like environments without extra configuration as it was before the latest change https://github.com/open-telemetry/opentelemetry-collector/pull/2782.
Resolves: https://github.com/open-telemetry/opentelemetry-collector/issues/2827
> Change health_check default endpoint to 0.0.0.0:13133

- CHANGELOG.md
- extension/pprofextension/config.go
- extension/pprofextension/config_test.go
- extension/pprofextension/factory.go
- extension/pprofextension/factory_test.go
- extension/pprofextension/pprofextension.go
- extension/pprofextension/pprofextension_test.go
- extension/zpagesextension/config.go
- extension/zpagesextension/config_test.go
- extension/zpagesextension/factory.go
- extension/zpagesextension/factory_test.go
- extension/zpagesextension/zpagesextension.go
- extension/zpagesextension/zpagesextension_test.go
- service/defaultcomponents/default_extensions_test.go
Change `pprof` and `zpages` extensions' configs to use `confignet.TCPAddr` instead of `Endpoint` string.
**Link to tracking Issue:** #2764
> Use confignet.TCPAddr in extentions

- CHANGELOG.md
- config/configparser/config.go
> Update LoadReceiver signature to remove unused params

- exporter/prometheusexporter/accumulator.go
- exporter/prometheusexporter/accumulator_test.go
Ensure consistency, data points coming in the same batch are either all dropped or all exported.
> Ensure same time is used for updated time, and for expiration test

- component/componenttest/nop_receiver.go
- component/componenttest/nop_receiver_test.go
- config/config.go
- config/config_test.go
- config/receiver.go
- internal/testcomponents/example_receiver.go
- receiver/hostmetricsreceiver/config.go
- receiver/jaegerreceiver/config.go
- receiver/kafkareceiver/config.go
- receiver/opencensusreceiver/config.go
- receiver/otlpreceiver/config.go
- receiver/prometheusreceiver/config.go
- receiver/prometheusreceiver/factory.go
- receiver/prometheusreceiver/factory_test.go
- receiver/receiverhelper/factory_test.go
- receiver/zipkinreceiver/config.go
- service/internal/builder/factories_test.go
- service/internal/builder/receivers_builder_test.go
The goal is to add `Validate()` interface in `config.Receiver|Exporter|Processor|Extension` so we can force each component to add validation logic on component level configuration. Only have the changes for `config.Receiver` in this PR.
Added `CustomConfigOptions` interface in `config.Receiver`.  And `CustomConfigOptions` interface has embedded `CustomConfigValidator` interface so it can force each receiver component to implement `Validate()` for Config validation check. Also, `CustomConfigOptions` interface can be extended to add more CustomConfig options.
**The reason why we should have `Validate()` for each component.**
Currently, since we don't have a unified fashion for components to `validate` the configuration. The component contributors write the config validate …
> Add validate interface in configmodels to force each component do configuration validation

- component/componenttest/nop_receiver.go
- config/config.go
- config/config_test.go
- config/receiver.go
- receiver/hostmetricsreceiver/config.go
- receiver/jaegerreceiver/config.go
- receiver/kafkareceiver/config.go
- receiver/opencensusreceiver/config.go
- receiver/otlpreceiver/config.go
- receiver/prometheusreceiver/config.go
- receiver/receiverhelper/factory_test.go
- receiver/zipkinreceiver/config.go
- service/internal/builder/factories_test.go
- service/internal/builder/receivers_builder_test.go
> Refactor ConfigValidator

- service/internal/builder/builder.go
- service/internal/builder/exporters_builder.go
- service/internal/builder/extensions_builder.go
- service/internal/builder/pipelines_builder.go
- service/internal/builder/receivers_builder.go
> Tune logs (zap) fields for each component, remove duplicate type already in name

- component/componenttest/nop_receiver.go
- component/componenttest/nop_receiver_test.go
- config/receiver.go
- internal/testcomponents/example_receiver.go
- receiver/receiverhelper/factory_test.go
- service/internal/builder/factories_test.go
- service/internal/builder/receivers_builder_test.go
> Implement Validate() in ReceiverSettings, easy transition

- cmd/otelcol/Dockerfile
- examples/demo/app/Dockerfile
**Description:** This change sets a custom user to the container image, under an ID that yields an unprivileged user.
> Set unprivileged user to container image

- .golangci.yml
> Enable golint comments check

- exporter/prometheusremotewriteexporter/exporter.go
Fixes a leak in HTTP responses after sending protobuf payloads
to Amazon's endpoints. This change ensures that connections
can be successfully reused, otherwise without invoking .Close()
they won't easily be reused.
Discovered while investigating for anything that could be averse
to scalability of the exporter.
Fixes #2874
/cc @Aneurysm9 @rakyll @alolita
> exporter/prometheusremotewriterexporter: close HTTP response body

- Makefile
`make run` is a useful command, but there is no way to pass extra command arguments. This commit adds a way to do that with RUN_ARGS env variable
> Add an option to pass command arguments with `make run`

- testbed/correctness/traces/correctness_test.go
- testbed/testbed/data_providers.go
- testbed/testbed/validator.go
Added a TODO to fix the span links attributes and tracestate propagation when Jaeger is used.
> Change testbed validator to use pdata

- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
This commit adds observability to queue_retry exporter helper. It adds the first metric "queue_length" that indicates current size of the queue per exporter. The metrics is updated every second.
This is the first commit to address the issue https://github.com/open-telemetry/opentelemetry-collector/issues/2434
> Report metric about current size of the exporter retry queue

- component/componenttest/nop_processor.go
- component/processor.go
- component/processor_test.go
- processor/processorhelper/factory.go
The reason to do this is to allow us to add factory methods for new signals in the future without breaking implementations.
> Allow adding new signals in ProcessorFactory by forcing everyone to embed BaseProcessorFactory

- config/internal/configsource/manager.go
- config/internal/configsource/manager_test.go
- config/internal/configsource/testdata/arrays_and_maps.yaml
- config/internal/configsource/testdata/arrays_and_maps_expected.yaml
- config/internal/configsource/testdata/params_handling.yaml
- config/internal/configsource/testdata/params_handling_expected.yaml
Adds a config source manager that wraps the interaction with config sources. This should be the part visible outside the configuration-related implementation, ie.: for the code setting up the service and watching for updates.
The syntax for config source references is provisional.
> Add a config source manager

- exporter/kafkaexporter/README.md
- exporter/kafkaexporter/jaeger_marshaller.go
- exporter/kafkaexporter/jaeger_marshaller_test.go
- exporter/kafkaexporter/kafka_exporter.go
- exporter/kafkaexporter/marshaller.go
**Description:** exporter/kafkaexporter: key jaeger spans by traceid, emulating jaeger-collector behavior. This allows for "grouping by traceid" for kafka consumers. For reference: [jaeger kafka producer](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/kafka/writer.go#L87).
**Testing:** Updated tests, inspected resulting messages produced into kafka to match up with the expectation.
**Documentation:** Updated kafkaexporter documentation to reflect behavior
> otelcol/exporter/kafka: key jaeger messages on traceid

- receiver/prometheusreceiver/internal/metricfamily.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
Fixing a bug - PrometheusReceiver ignores Summary and Histogram Metrics that do not have _sum counter. #2661
Modified the condition in `toDistributionTimeSeries` and `toSummaryTimeSeries` functions to ignore the `hasSum` check.
https://github.com/open-telemetry/opentelemetry-collector/issues/2661
**Testing:** 
Updated Unit test cases, and also tested with live application using DropWizard metrics framework.
None.
> Treating Summary and Histogram metric with out "_sum" counter as valid metric.

- CONTRIBUTING.md
As part of #2430, this PR adds guidelines for component developers on how to appropriately make their components observable.
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Add guidelines for observability in the components

- config/internal/configsource/manager.go
- config/internal/configsource/manager_test.go
- config/internal/configsource/testdata/envvar_cfgsrc_mix.yaml
- config/internal/configsource/testdata/envvar_cfgsrc_mix_expected.yaml
Adding support to existing env var syntax per https://github.com/open-telemetry/opentelemetry-collector/pull/2857#issuecomment-815078669
> Config Source Manager: support current env var syntax

- CHANGELOG.md
- config/config.go
- config/config_test.go
- config/exporter.go
- config/extension.go
- config/processor.go
- exporter/fileexporter/config.go
- exporter/jaegerexporter/config.go
- exporter/kafkaexporter/config.go
- exporter/loggingexporter/config.go
- exporter/opencensusexporter/config.go
- exporter/otlpexporter/config.go
- exporter/otlphttpexporter/config.go
- exporter/prometheusexporter/config.go
- exporter/prometheusremotewriteexporter/config.go
- exporter/zipkinexporter/config.go
- extension/healthcheckextension/config.go
- extension/pprofextension/config.go
- extension/zpagesextension/config.go
- processor/attributesprocessor/config.go
- processor/batchprocessor/config.go
- processor/filterprocessor/config.go
- processor/memorylimiter/config.go
- processor/probabilisticsamplerprocessor/config.go
- processor/resourceprocessor/config.go
- processor/spanprocessor/config.go
Extend previous PR - https://github.com/open-telemetry/opentelemetry-collector/pull/2856. Add `validatable` interface to `config.processor | extension | exporter`. And add the config validation in `config.Validate()`
**Next** 
Implement the empty `Validate()` func in component `Config`. For at least the core component we want to release stable.
https://github.com/open-telemetry/opentelemetry-collector/issues/2541
> add `validatable` interface to all the component config

- config/configparser/config.go
- service/application.go
- service/application_test.go
- service/internal/builder/builder.go
- service/parserprovider/default.go
- service/parserprovider/default_test.go
- service/parserprovider/file.go
- service/parserprovider/flags.go
- service/parserprovider/inmemory.go
- service/parserprovider/provider.go
- service/parserprovider/setflag.go
- service/parserprovider/setflag_test.go
- service/parserprovider/testdata/otelcol-config.yaml
- testbed/testbed/otelcol_runner.go
- testbed/testbed/otelcol_runner_test.go
> Extract ConfigFactory in a ParserProvider interface

- .github/workflows/codeql-analysis.yml
> Enable codeql for every PR

- exporter/prometheusexporter/accumulator.go
- exporter/prometheusexporter/collector.go
- exporter/prometheusexporter/collector_test.go
- exporter/prometheusexporter/end_to_end_test.go
Allows Summary metrics to be exported to Prometheus.
To walk through this feature, I created an adaptation of a Brian Brazil
tutorial for DropWizard, to create a Java server at
https://github.com/odeke-em/bugs/tree/master/opentelemetry-collector/2661
and it uses DropWizard, and exports out JVM statistics with Prometheus where the
*gc_collection_seconds are of the summary kind when scraped by visiting
http://localhost:1234/metrics which produced
```
jvm_gc_collection_seconds_count{gc="G1 Young Generation",} 4.0
jvm_gc_collection_seconds_sum{gc="G1 Young Generation",} 0.026
jvm_gc_collection_seconds_count{gc="G1 Old Generation",} 0.0
```
and then roundtripped the collector to scrape those metrics and then
export them to Prometheus
VS
making Prometheus directly scrape that endpoint and then …
> exporter/prometheusexporter: support Summary

- CHANGELOG.md
- config/parser.go
- service/parserprovider/setflag.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/2651
> Remove config.NewViper, users should use config.NewParser

- testbed/tests/trace_test.go
We are running close to limit and sometimes fail on CI: https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/6439/workflows/c4539858-c8fe-4ece-8684-01ca3dcbc13b/jobs/74316
> Bump TestTraceNoBackend10kSPS CPI limits

- CHANGELOG.md
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/opencensusreceiver/octrace/observability_test.go
- receiver/opencensusreceiver/octrace/opencensus_test.go
- receiver/otlpreceiver/logs/otlp_test.go
- receiver/otlpreceiver/metrics/otlp_test.go
- receiver/otlpreceiver/trace/otlp_test.go
- testutil/testutil.go
> Remove testutil.HostPortFromAddr, no need to provide this helper

- component/componenthelper/component.go
- exporter/exporterhelper/common.go
- processor/processorhelper/processor.go
- receiver/scraperhelper/scraper.go
> Follow golang pattern and name public function types with Func suffix

- CHANGELOG.md
- exporter/opencensusexporter/opencensus_test.go
- exporter/otlpexporter/otlp_test.go
- receiver/jaegerreceiver/jaeger_agent_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/opencensusreceiver/octrace/opencensus_test.go
- testutil/testutil.go
> Remove testutil.WaitFor, use testify helper if needed

- CHANGELOG.md
- receiver/jaegerreceiver/jaeger_agent_test.go
- testbed/testbed/test_case.go
- testutil/testutil.go
- testutil/testutil_test.go
> Remove testutil.WaitForPort, users can use testify.Eventually

- receiver/hostmetricsreceiver/config.go
- receiver/hostmetricsreceiver/config_test.go
- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/otlpreceiver/config.go
- receiver/otlpreceiver/config_test.go
- receiver/prometheusreceiver/config.go
- Move some errors happening during unmarshaling to the new `Validate` method.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/pull/2867#discussion_r606354281
To be tracked on #2819
> Move some unmarshaling errors to the Validate method

- CHANGELOG.md
- component/componenttest/shutdown_verifier.go
- component/processor.go
- consumer/fanoutconsumer/cloningconsumer_test.go
- consumer/fanoutconsumer/consumer_test.go
- processor/attributesprocessor/attributes_trace.go
- processor/attributesprocessor/factory.go
- processor/attributesprocessor/factory_test.go
- processor/batchprocessor/factory.go
- processor/memorylimiter/factory.go
- processor/memorylimiter/memorylimiter_test.go
- processor/probabilisticsamplerprocessor/factory.go
- processor/probabilisticsamplerprocessor/factory_test.go
- processor/probabilisticsamplerprocessor/probabilisticsampler.go
- processor/probabilisticsamplerprocessor/probabilisticsampler_test.go
- processor/processorhelper/factory.go
- processor/processorhelper/factory_test.go
- processor/processorhelper/processor.go
- processor/processorhelper/processor_test.go
- processor/resourceprocessor/factory.go
- processor/spanprocessor/factory.go
- processor/spanprocessor/factory_test.go
- processor/spanprocessor/span_test.go
> Fix all TraceProcessor usages, use TracesProcessor

- consumer/consumertest/err.go
- consumer/consumertest/err_test.go
- consumer/consumertest/nop.go
- consumer/consumertest/nop_test.go
> Remove already deprecated test funcs New*Nop and New*Err

- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
Ensures that before a prompb.WriteRequest is created, that the
TimeSeries contained have their Sample values sorted chronologically
by Prometheus to avoid out of order errors reported by Prometheus
barfing.
Thanks to @rakyll for a reproducer and for diagnosing the problem, which
helped distill the issue from a very complex setup that required super
expensive Kubernetes clusters with many replicas, but essentially the problem
became more apparently when the number of TimeSeries grew.
It is important to note that the presence of such a bug signifies that
with a large number of replicas are being scraped from, this stalls
scraping and takes a long time which means that targets scraped in a
round-robin fashion experience staleness when many. This might be even
more reasons for setups to adopt …
> exporter/prometheusremotewriter: sort Sample by Timestamp to avoid out of order errors

- CHANGELOG.md
- consumer/pdata/common.go
- consumer/pdata/common_test.go
- consumer/simple/metrics_test.go
- exporter/opencensusexporter/opencensus_test.go
- processor/resourceprocessor/resource_processor.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process.go
- testbed/testbed/data_providers.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_resource.go
- translator/internaldata/oc_to_traces.go
- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerthrift_to_traces.go
- translator/trace/zipkin/zipkinv2_to_traces.go
- translator/trace/zipkin/zipkinv2_to_traces_test.go
> Replace InitEmptyWithCapacity with EnsureCapacity and Clear

- config/experimental/configsource/component.go
- config/internal/configsource/manager.go
- config/internal/configsource/manager_test.go
Make configsource component public as an experimental component.
> Make configsource component visible

- processor/README.md
k8s_tagger relies on the `context.Context` object to find the pod IP of the incoming telemetry. This context gets lost when batch processor is hit. Adding recommendation here even though k8s_tagger is a contrib to because this is where ordering recommendations are made and it's a common processor.
> Update processor recommendation for k8s_tagger

- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/metrics_receiver_test.go
In Prometheus, `job` and `instance` are the two auto generated labels, however they are both dropped by prometheus receiver. Although these information is still available in `service.name` and `host`:`port`, it breaks the data contract for most Prometheus users (who use `job` and `instance` to consume metrics in their own system).
This PR adds `job` and `instance` as well-known labels in prometheus receiver to fix the issue.
https://github.com/open-telemetry/opentelemetry-collector/issues/575
https://github.com/open-telemetry/opentelemetry-collector/issues/2499
https://github.com/open-telemetry/opentelemetry-collector/issues/2363
https://github.com/open-telemetry/wg-prometheus/issues/7
> Add job and instance as well-known labels in prometheus receiver

- service/application.go
- service/application_test.go
- service/parserprovider/provider.go
Add interfaces to ParserProvider so it can handle configurations that trigger reload. Intended to be used with config sources.
Missing: a test to cover the update configuration on appplication_test.go
> Adding Watchable and Closeable to ParserProvider interface

- receiver/kafkareceiver/kafka_receiver.go
Fix datarace between kafkareceiver and batchprocessor, more description see issue #2956 
kafkareceiver should not use `traces` varible  after invoke `nextConsumer.ConsumeTraces` because  `traces` object will be operated in batchprocessor in another goroutine.
```
==================
WARNING: DATA RACE
Write at 0x00c0001108d0 by goroutine 115:
go.opentelemetry.io/collector/consumer/pdata.ResourceSpansSlice.MoveAndAppendTo()
/Users/jimmiehan/github.com/hanjm/opentelemetry-collector/consumer/pdata/generated_trace.go:75 +0x237
go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).add()
/Users/jimmiehan/github.com/hanjm/opentelemetry-collector/processor/batchprocessor/batch_processor.go:269 +0xe5
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProce …
```
> Fix data race between kafkareceiver and batchprocessor (#2956)

- exporter/kafkaexporter/config_test.go
- receiver/kafkareceiver/factory.go
- receiver/kafkareceiver/factory_test.go
- receiver/kafkareceiver/kafka_receiver_test.go
Fix some typo in kafkareceiver and kafkaexporter package
> Fix some typo in kafkareceiver and kafkaexporter package

- exporter/prometheusremotewriteexporter/README.md
- exporter/prometheusremotewriteexporter/factory.go
Prometheus remote write (PWR) exporter is supporting queued retry
out of the box, but due to the strict requirements of PWR, the queue
causes "out of order sample" errors. The queue won't be suitable
for Prometheus unless it has a way to shard the data by timeseries.
This is not going to break the existing users because if they have
this feature enabled, they already can't use the PRW exporter correctly.
Fixes #2949.
> Remove queue from the Prometheus remote write

- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
dpgSignature is invoked very often, which leads to high CPU usage when
collecting Prometheus metrics.
Benchmark results on my machine show 3x less CPU and almost 4x less
memory used. Since I'm also changing the format of returned values
(dropping superfluous characters), it will reduce overall memory usage
of the receiver, because they are used as map keys.
Benchmark result before this change:
Benchmark_dpgSignature-6   	 1284531	       969.6 ns/op	     120 B/op	       7 allocs/op
Benchmark result after this change:
Benchmark_dpgSignature-6   	 3515179	       313.9 ns/op	      32 B/op	       2 allocs/op
**Testing:** Added benchmark and updated unit tests.
> Optimize dpgSignature function in Prometheus receiver

- receiver/jaegerreceiver/trace_receiver.go
The Jaeger agent reports ErrServerClosed when shutting down the service. This error is expected and should not be reported.
> Jaeger agent should not report ErrServerClosed

- receiver/kafkareceiver/factory.go
- receiver/kafkareceiver/factory_test.go
- receiver/kafkareceiver/jaeger_unmarshaller.go
- receiver/kafkareceiver/jaeger_unmarshaller_test.go
- receiver/kafkareceiver/kafka_receiver.go
- receiver/kafkareceiver/kafka_receiver_test.go
- receiver/kafkareceiver/otlp_unmarshaller.go
- receiver/kafkareceiver/otlp_unmarshaller_test.go
- receiver/kafkareceiver/unmarshaller.go
- receiver/kafkareceiver/unmarshaller_test.go
- receiver/kafkareceiver/zipkin_unmarshaller.go
- receiver/kafkareceiver/zipkin_unmarshaller_test.go
Renamed methods/objects used by Traces to include "Traces" in Kafka receiver.
Fixed https://github.com/open-telemetry/opentelemetry-collector/pull/2944#discussion_r615000738
> Rename traces methods/objects to include Traces in Kafka receiver

- cmd/pdatagen/internal/base_slices.go
- consumer/pdata/common.go
- consumer/pdata/generated_common_test.go
- consumer/pdata/generated_log_test.go
- consumer/pdata/generated_metrics_test.go
- consumer/pdata/generated_trace_test.go
> Remove deprecated NewAttributeValue, update pdatagen to avoid using it

- CHANGELOG.md
- receiver/zipkinreceiver/trace_receiver_test.go
- translator/trace/zipkin/testdata/zipkin_v2_notimestamp.json
- translator/trace/zipkin/traces_to_zipkinv2.go
- translator/trace/zipkin/traces_to_zipkinv2_test.go
- translator/trace/zipkin/zipkinv2_to_traces.go
- translator/trace/zipkin/zipkinv2_to_traces_test.go
Fixing a bug - As outlined in the submitted issue, otel-collector previously fixed an issue with zipkin json_v1 formatted spans not containing a startTimestamp. This fixes the same case for zipkin json_v2 format.
https://github.com/open-telemetry/opentelemetry-collector/issues/2506
**Testing:**
added a unit test around the new method, similar to the one already in place for zipkin json_v1 handling.
added changelog entry only, as this is a bug fix.
> Handle missing starttime case for zipkin json v2 format spans (#2506)

- exporter/kafkaexporter/factory.go
- exporter/kafkaexporter/factory_test.go
- receiver/kafkareceiver/factory.go
- receiver/kafkareceiver/factory_test.go
- Change method signatures as recommended in #2967 (Closes #2967)
> Change With*Unmarshallers signatures

- exporter/prometheusremotewriteexporter/factory.go
This is a follow up to #2951.
When we disable the queue completely, it causes the export to happen
not in a consumer goroutine. Enable the queue internally that export
gets its own goroutine not to block the entire collector pipeline.
> Enable the queue for the Prometheus Remote Write Exporter internally

- receiver/prometheusreceiver/internal/metricsbuilder.go
Remove the intermediate return variable and make use of the multiple values in case.
> Fix the readability of isUsefulLabel

- receiver/jaegerreceiver/trace_receiver.go
The test hitting #2975 runs Start and Shutdown in close succession and in this case Shutdown was setting the field `collectorServer` to nil before the goroutine launched on Start actually accessed the field. Fixed the issue by adding a `sync.WaitGroup` to ensure that Shutdown actually waits for all launched goroutines to exit (also improved error handling for the server goroutines). Removed setting the fields to nil on Shutdown since that is not necessary.
Fixes #2975
> Wait jaeger receiver server goroutines exit on shutdown

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
This is a follow up to #2897. Even though the instance and job labels are scraped, we were not using them during the export. This change makes sure that the remote write exporter is labelling the outgoing samples with "job" and "instance". 
Fixes #575
Fixes #2499
Fixes #2363
Fixes open-telemetry/wg-prometheus#37
Fixes open-telemetry/wg-prometheus#39
Passing compliance tests:
$ go test --tags=compliance -run "TestRemoteWrite/otelcollector/Job.+" -v ./
=== RUN TestRemoteWrite
=== RUN TestRemoteWrite/otelcollector
=== RUN TestRemoteWrite/otelcollector/JobLabel
=== PAUSE TestRemoteWrite/otelcollector/JobLabel
=== CONT TestRemoteWrite/otelcollector/JobLabel
--- PASS: TestRemoteWrite (10.02s)
--- PASS: TestRemoteWrite/otelcollector (0.00s)
--- PASS: TestRemoteWrite/otelcollector/JobLabel …
> Don't drop instance and job labels in the Prometheus Remote Write Exporter

- exporter/loggingexporter/known_sync_error.go
- exporter/loggingexporter/known_sync_error_windows.go
- exporter/loggingexporter/logging_exporter.go
Similar to what happens in Linux and macOS the logger.Sync call on loggingexporter also returns an error that should be ignored on Windows.
> Logging exporter ignore invalid handle on close

- service/application_test.go
- service/internal/builder/host_wrapper.go
This is an "emergency" fix until a better mechanism to allow the addition of zpages by the service (and others) is prepared.
> Fix service zpages

- .circleci/config.yml
- Makefile
This strips off absolute paths referring to GOPATH, modules and the
project from the build taking us a step closer to reproducible builds.
This has an effect on debugging when developing locally as full paths will not be present in the stack traces anymore but it should should be pretty easy to figure out.
Before:
```
2021/04/24 02:49:56 manual panic
panic: manual panic
goroutine 1 [running]:
log.Panicf(0x3a21de8, 0xc, 0x0, 0x0, 0x0)
/usr/local/go/src/log/log.go:361 +0xc5
go.opentelemetry.io/collector/receiver/otlpreceiver.newOtlpReceiver(0xc0007a3ad0, 0xc000802840, 0xc0007a3ad0, 0x5247cc0, 0xc00018f600)
/Users/olone/Projects/opentelemetry/opentelemetry-collector/receiver/otlpreceiver/otlp.go:75 +0x96
go.opentelemetry.io/collector/receiver/otlpreceiver.createReceiver(0x3f …
```
> Add -trimpath to go build args.

- Makefile
- internal/collector/telemetry/telemetry.go
- internal/version/version.go
- service/logger.go
* For logger profile use flag "log-profile"
* For telemetry address this is not a breaking change
> Remove BuildInfo used only in two places

- cmd/otelcol/main.go
- component/application_info.go
- service/application.go
- testbed/testbed/otelcol_runner.go
> Remove ApplicationStartInfo.LongName, the usage as long help was wrong anyway

- .circleci/config.yml
- .github/workflows/build-and-test.yml
- .github/workflows/contrib-tests.yml
- CONTRIBUTING.md
- cmd/checkdoc/go.mod
- cmd/issuegenerator/go.mod
- cmd/mdatagen/go.mod
- examples/demo/app/go.mod
- go.mod
- internal/tools/go.mod
Updated CI and makefile to use Go 1.16.
In 1.16, `go install` accepts versions so the tools trick to pin tool versions is not required anymore.
> Upgrade to Go1.16

- .circleci/config.yml
I am disabling until an audit is done and we are certain there
is nothing wrong with it.
We should decide how we prevent this from happening in the future.
> Disable codecov until the script is audited

- testbed/testbed/validator.go
**Description:** Print more human readable 10 base integers instead of hexes when comparing testbed results.
Instead of
```
validator.go:42:
Error Trace:    validator.go:42
test_case.go:277
scenarios.go:190
log_test.go:159
Error:          Not equal:
expected: 0x222e0
actual  : 0x210e8
Test:           TestLog10kDPS/syslog-udp
Messages:       Received and sent counters do not match.
```
print the following (more readable) output:
```
validator.go:42:
Error Trace:    validator.go:42
test_case.go:277
scenarios.go:190
log_test.go:159
Error:          Not equal:
expected: 140000
actual  : 135400
Test:           TestLog10kDPS/syslog-udp
Messages:       Received and sent counters do not match.
```
> testbed: Compare ints in 10 base not in hex

- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
* The reordering could happen if during processing of an item other items were added to the newItems channel. This is fixed by avoiding to re-add the left items to the channel.
* The logic of spliting was wrong by forcing sendBatchSize instead of sendBatchMaxSize when split was called.
* Fix logic if a very large message is received > 2x sendBatchMaxSize to call export multiple times instead of once and reset the timer.
> Fix batchprocessor to avoid reordering and send max size

- receiver/prometheusreceiver/internal/ocastore.go
> Avoid using componenterror.ErrAlreadyStopped when not in components

- receiver/jaegerreceiver/trace_receiver.go
No other component implement this, and we should trust the service that it does the right thing.
> Remove premature protection for Start/Stop in jaeger receiver

- testbed/tests/trace_test.go
We are running very close to limit (e.g. 66MB in this run https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/6834/workflows/146b061a-c3dc-4601-ac43-4a31c201c064/jobs/78320) and sometime exceed it and fail the build.
Bumping slightly to avoid failures. The limit is still low enough to ensure memory limiter work (the max is lower than the min without limiter).
> Bump memory limit for TestTraceNoBackend10kSPS/MemoryLimit

- CONTRIBUTING.md
With modules, GOPATH is  not commonly used by Go developers anymore. Switch to the non-GOPATH instructions.
> Don't require GOPATH for development

- extension/ballastextension/README.md
The current example is a disabled case, give a non-zero size to enable the memory ballast in the example.
> Fix the memory blast example

- exporter/prometheusremotewriteexporter/README.md
- exporter/prometheusremotewriteexporter/config.go
- exporter/prometheusremotewriteexporter/config_test.go
- exporter/prometheusremotewriteexporter/factory.go
- exporter/prometheusremotewriteexporter/testdata/config.yaml
Add `exporterhelper.ResourceToTelemetrySettings` support in `prometheusremotewriteexporter` config. It will allow both `prometheusremotewriteexporter` and `ampprometheusremotewriteexporter` be able to convert Resource attributes to Metric Labels for Prometheus metrics. 
```
prometheusremotewrite:
resource_to_telemetry_conversion:
enabled: true
```
https://github.com/aws-observability/aws-otel-collector/issues/472
**Testing:** 
`make all`
> Add resource_to_telemetry_conversion config in prometheusremotewriteexp

- consumer/consumererror/permanent.go
- consumer/consumererror/permanent_test.go
- consumer/consumererror/signalerrors.go
- consumer/consumererror/signalerrors_test.go
**Description:** Fixing a bug - Add Unwrap method to consumer errors permanent, Traces, Logs and Metrics. Functions Is and As in standard package errors use Unwrap to retrieve wrapped errors.
**Testing:** Created error type testErrorType. Wrapped testErrorType values with the consumer errors. Used function errors.As to retrieve wrapped testErrorType values. Added tests:
- TestPermanent_Unwrap
- TestTraces_Unwrap
- TestLogs_Unwrap
- TestMetrics_Unwrap
> Add Unwrap methods to consumer errors

- CHANGELOG.md
- cmd/otelcol/main.go
- component/build_info.go
- service/application.go
- testbed/testbed/otelcol_runner.go
- Renamed ExeName to Command
- Added Description to store the full name of the collector
> Renamed ExeName to Command, added Description in start info

- service/application_test.go
The test TestApplication_StartAsGoRoutine is setting the metric level to none but there is no way to reset the flag to its default. This breaks the tests if one tries to run the tests multiple times in the same `go test` command. Since the setting was not required by tests opting to remove it.
> Remove test step that can't be cleaned-up

- component/component.go
- component/exporter.go
- component/receiver.go
1. Move the component lifecycle to interface godoc so the godoc can render it
2. Avoid using below/above, godoc already groups things correctly.
3. Avoid giving references to what functions/methods implement what. Instead, mention what they do.
4. Fix inconsistencies in new lines for long lines.
Related to #3049.
> Fix godoc wording and inconsistencies

- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
- internal/otlptext/databuffer.go
- internal/otlptext/databuffer_test.go
- internal/otlptext/logs.go
- internal/otlptext/logs_test.go
- internal/otlptext/metrics.go
- internal/otlptext/metrics_test.go
- internal/otlptext/traces.go
- internal/otlptext/traces_test.go
The plan is to eventually use this as an unmarshaller (#3044) but for now make
it accessible from `internal/otlptext`.
> Extract OTLP text logging from logging exporter

- internal/otlptext/databuffer.go
Results in timestamps like `2021-05-04 03:39:45.663583 +0000 UTC` instead of `123456789`
> Format timestamps as strings instead of int in otlptext output

- receiver/jaegerreceiver/trace_receiver.go
Remove locking from start and stop functions - jaeger receiver
https://github.com/open-telemetry/opentelemetry-collector/issues/3041
> remove locking from jaeger receiver start and stop processes

- testbed/tests/e2e_test.go
We are running close to the limit and sometimes fail on CI: https://github.com/open-telemetry/opentelemetry-collector/pull/3073/checks?check_run_id=2494206292
This should avoid spurious failures.
> Increase TestIdleMode memory limit

- processor/batchprocessor/splitmetrics.go
- processor/batchprocessor/splitmetrics_test.go
Benchmarks Before:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkSplitMetrics
BenchmarkSplitMetrics-16    	    6660	    170653 ns/op	  182889 B/op	    3309 allocs/op
PASS
Process finished with the exit code 0
```
Benchmarks After:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkSplitMetrics
BenchmarkSplitMetrics-16    	    7858	    134259 ns/op	  141881 B/op	    2596 allocs/op
PASS
Process finished with the exit code 0
```
Benchmarks Reference Clone:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz …
```
> Fix batch processor metrics reorder, improve performance

- internal/testdata/trace.go
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/splitmetrics.go
- processor/batchprocessor/splittraces.go
- processor/batchprocessor/splittraces_test.go
Benchmarks Before:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkSplitTraces
BenchmarkSplitTraces-16    	    8277	    135600 ns/op	  222440 B/op	    1725 allocs/op
PASS
```
Benchmarks After:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkSplitTraces
BenchmarkSplitTraces-16    	    9896	    108060 ns/op	  172409 B/op	    1372 allocs/op
PASS
```
Benchmarks Reference Clone:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkCloneSpans
BenchmarkCloneSpans-16    	   12393	     97528 ns/op	  167896 B/op …
```
> Fix batch processor traces reorder, improve performance

- CHANGELOG.md
- translator/trace/zipkin/grpc_http_mapper.go
- translator/trace/zipkin/grpc_http_mapper_test.go
- translator/trace/zipkin/status_code.go
- translator/trace/zipkin/zipkinv1_thrift_to_protospan_test.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
> Remove OpenCensus status constants and transformation

- CHANGELOG.md
- internal/occonventions/opencensus.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/oc_testdata_test.go
- translator/internaldata/oc_to_resource.go
- translator/internaldata/oc_to_resource_test.go
- translator/internaldata/oc_to_traces.go
- translator/internaldata/oc_to_traces_test.go
- translator/internaldata/resource_to_oc.go
- translator/internaldata/resource_to_oc_test.go
- translator/internaldata/traces_to_oc.go
- translator/internaldata/traces_to_oc_test.go
- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/zipkin/zipkinv2_to_traces.go
> Remove OpenCensus conventions, should not be used

- README.md
Not clear to everyone due to the vanity import path.
> Give a link to the Go package site

- processor/batchprocessor/README.md
- processor/batchprocessor/config.go
- processor/batchprocessor/config_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/3119
> Validate that batch config max size is greater than send size

- receiver/prometheusreceiver/metrics_receiver_test.go
This change was a part of #2964 but it's closed now. Having typed
arguments make it easier to massage the arguments before comparing.
Contributing this change for future maintainers.
> Minor change to doCompare

- exporter/exporterhelper/common.go
- extension/authoidcextension/README.md
While working on another PR noticed some typos in our documentation
1. oidcextension module's README sample example missed a key configuration 
2. exporterhelper module had a minor typo in one of its doc strings 
**Testing:** - Fixed comments
> [MINOR] Fixed documentation in exporterHelper module and OIDCExtension README

- exporter/jaegerexporter/exporter_test.go
The args is autogenerated by table-driven test generator tools but it's arbitrary.
> Minor improvement to remove arbitary args from the Jaeger tests

- exporter/otlpexporter/otlp.go
- exporter/otlphttpexporter/otlp.go
In Go, we tend to not to name concrete types with prefixes like *Imp or *Impl like in Java. Renaming exporterImp to exporter to keep it simple.
> Remove Java-like concrete type naming

- translator/internaldata/oc_to_traces.go
> Mark internaldata traces translation as deprecated for external usage

- .golangci.yml
- internal/processor/filterlog/filterlog.go
- internal/processor/filterspan/filterspan.go
- receiver/jaegerreceiver/trace_receiver.go
- service/application.go
- testbed/testbed/receivers.go
Switch `golint` linter to `revive`. `golint` has been deprecated (see golang/go#38968). `golangci-lint` recommends `revive` as a replacement.
> Switch to `revive` from `golint`

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
- exporter/prometheusremotewriteexporter/testutil_test.go
Remove internal protos usage in Prometheusremotewrite exporter, closes #3108
> Remove internal protos usage in Prometheusremotewrite exporter

- receiver/prometheusreceiver/internal/ocastore.go
- receiver/prometheusreceiver/internal/ocastore_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/internal/transaction_test.go
- receiver/prometheusreceiver/metrics_receiver.go
- receiver/prometheusreceiver/metrics_reciever_external_labels_test.go
Add external labels to every scraped sample in the Prometheus receiver if user has external labels configured.
Fixes #2904.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/3016.
> Honor Prometheus external labels

- internal/sharedcomponent/sharedcomponent.go
- internal/sharedcomponent/sharedcomponent_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/factory_test.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
Use the new code in OTLP receiver.
> Add an internal sharedcomponent to be shared by receivers with shared resources

- exporter/prometheusremotewriteexporter/README.md
- exporter/prometheusremotewriteexporter/config.go
- exporter/prometheusremotewriteexporter/config_test.go
- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/factory.go
- exporter/prometheusremotewriteexporter/testdata/config.yaml
A follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/2974.
> Allow users to configure the Prometheus remote write queue

- exporter/prometheusremotewriteexporter/config.go
- exporter/prometheusremotewriteexporter/exporter_test.go
The Prometheus Remote Write (PRW) exporter is not using the retried queue. After this change, collector will error if the configuration has sending_queue from the PRW exporter.
Note: This is a breaking change and we might want to keep it not to break the existing collector configs.
> Remove QueueSettings from the Prometheus remote write exporter

- .github/workflows/docs-update.yml
- website_docs/_index.md
- website_docs/configuration.md
- website_docs/getting-started.md
Per open-telemetry/opentelemetry.io#472, we're mirroring the docs content on the website to each SIG. When a release occurs and these docs are updated, please make an issue or PR mirroring them to their appropriate location in the website repo (https://github.com/open-telemetry/opentelemetry.io/tree/main/content/en/docs/collector).
> Add opentelemetry.io docs

- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- internal/pdatagrpc/logs.go
- internal/pdatagrpc/metrics.go
- internal/pdatagrpc/traces.go
This is needed because if we split pdata, we will nolonger be able to depend on the InternalRep or generated proto classes (raw, grpc).
The pdatagrcp will eventually be public once we stabilize the API.
The API in the pdatagrcp package is inspired from the grpc generated classes and redirects all calls to the generated classes. Some simple renames:
* TraceService[Client|Server] -> Traces[Client|Server]
* MetricsService[Client|Server] -> Metrics[Client|Server]
* LogsService[Client|Server] -> Logs[Client|Server]
Other changes:
* Replace usages of grpc generated classes in otlpexporter to excercise this new package.
* Left some TODOs for the moment until this package is used more to determine the right API.
Updates …
> Add initial implementation of pdatagrcp

- .circleci/config.yml
- .github/workflows/scripts/setup_load_tests.sh
This PR contains the same fix to unblock community PRs as the following contrib PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3423
> Update CI jobs to not require contexts for PR builds

- testbed/tests/e2e_test.go
This change improves the failure message for the TestBallastMemory. While this won't solve the problem, it will help understand if we are barely above the limit, or if the test went considerably above the max.
> Improve test failure logging for TestBallastMemory

- service/application_windows.go
Fixing a bug - As reported in #2756 Windows service events only contain the zap entry message and none of the fields.  These changes create a dedicated `zapcore.Core` to wrap the service logger's Core and use a production console encoder to encode the full entry, including its fields and stack if provided.
https://github.com/open-telemetry/opentelemetry-collector/issues/2756
**Testing:**
Tested manually with windows service.  ~~Currently examining unit test in addition to existing service test.~~
edit: I don't believe there's a clean* way to mock `eventlog.Log` sending in a unit test since* no interfaces are used and it resolves to a syscall: https://github.com/golang/sys/blob/94ec62e081691fed0145b707594111cee9cb360a/windows/zsyscall_windows.go …
> Use dedicated zapcore.Core for Windows service

- .circleci/config.yml
See https://circleci.com/docs/2.0/configuration-reference/#available-machine-images for the end of life of ubuntu-16-04
> Upgrade build package machine

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/factory.go
See https://github.com/golang/go/wiki/CodeReviewComments#initialisms.
> Fix the abbreviation initialism

- internal/model/decoder.go
- internal/model/decoder_test.go
- internal/model/encoder.go
- internal/model/encoder_test.go
- internal/model/mocks_test.go
This provides the high level wrappers around encoding pdata to bytes and
decoding bytes to pdata.
Just adds pdata.Traces for now. Would like to find a way to do code generation
since they're virtually identical for each telemetry type.
> High level encode/decode APIs

- internal/model/marshaler.go
- internal/model/marshaler_test.go
- internal/model/unmarshal.go
- internal/model/unmarshal_test.go
> Rename high-level interfaces to Marshaler/Unmarshaler

- exporter/fileexporter/file_exporter_test.go
- testutil/testutil.go
This ticket is currently for Phase2-GA-Roadmap
**Description:** Add Error Writer to be used in file exporter tests where limited writer was being used. Then remove limited writer from 
**Link to tracking Issue:** #3225 
**Testing:** Ran all file export tests in Intellij go test configuration. Run all unit test using make command.
> Add errWriter for fileexporter tests and remove testutils.LimitedWriter #3225

- testbed/tests/e2e_test.go
This PR adds a 10% margin of error to the TestBallastMemory, so that it won't fail if the memory usage is above the max, but not at unreasonable levels.
Closes #3233
> Add margin of error for TestBallastMemory

- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/factory_test.go
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
Description:
Updated oltphttpexporter for upcoming client auth extension changes
#3287
Testing:
Unit tests
Documentation:
Unit tests
> Refactor otlphttp exporter for upcoming API chnages

- exporter/zipkinexporter/factory.go
- exporter/zipkinexporter/zipkin.go
- exporter/zipkinexporter/zipkin_test.go
Description:
Updated Zipkin exporter for upcoming client auth extension changes
#3287
Testing:
Unit tests
Documentation:
Unit tests
> Refactored zipkin exporter for the upcoming ToClient confighttp API changes. 

- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/factory.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- exporter/otlpexporter/testdata/config.yaml
Description:
Updated oltpexporter for upcoming client auth extension changes
#3287
Testing:
Unit tests
Documentation:
Unit tests
> Refactor otlp exporter to upcoming auth changes

- extension/zpagesextension/README.md
Fix typo in zpagesextension's README.md
The very same as #3152 as @will-sargent-eero had some problems with the CLA.
> Remove typo in zpagesextension's README.

- config/config.go
- config/configauth/configauth.go
- config/configcheck/configcheck.go
- config/configgrpc/configgrpc.go
- config/configgrpc/gzip.go
- config/confighttp/confighttp.go
- config/configloader/config.go
- config/confignet/confignet.go
- config/configtelemetry/configtelemetry.go
- config/configtest/configtest.go
- config/configtls/configtls.go
- config/exporter.go
- config/extension.go
- config/internal/configsource/manager.go
- config/parser.go
- config/processor.go
- config/receiver.go
This PR is one of the three PRs working to review and improve the Config package. Changes were made to update the documentation of type and func declarations in the configuration package and all of its sub-packages, with a focus on ensuring that the documentation follows the [best practices](https://blog.golang.org/godoc) recommended by Go, and that there is no grammar mistakes.
Addresses part of #3051
> Edit Type/Function Documentation in the Config Package

- exporter/prometheusexporter/accumulator.go
I have met same problem like these issues  #3118,#3161, and I debug found here:
Same metric with different order lablemap will get a different key in accumulator's map. And same metric will be in the Map with different key, when accumulator is collecting, only the first one will be exported to prometheus. Some key will never be exported because of prometheus will only get the first one. I found sort it before generate the key, there will only one metric in accumulator's map, and every metric will be exported.
> fix bug  issue#3118 and issue#3161

- config/config.go
- config/configauth/doc.go
- config/configcheck/configcheck.go
- config/configcheck/doc.go
- config/configgrpc/configgrpc.go
- config/configgrpc/doc.go
- config/confighttp/doc.go
- config/configloader/config.go
- config/configloader/doc.go
- config/confignet/doc.go
- config/configtelemetry/doc.go
- config/configtest/doc.go
- config/configtls/doc.go
- config/doc.go
- config/experimental/configsource/component.go
- config/experimental/configsource/doc.go
- config/internal/configsource/doc.go
This PR is one of the three PRs aiming to address the issue: Reviewing and Improving config package.
Changes were made to first create an overview for any missing sub-packages, and secondly, to move the existing documentations into a separate `doc.go` to maintain consistency with the other modules.
Addresses part of #3051
> Add doc.go files to the Config package

- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/traces_test.go
- internal/obsreportconfig/obsmetrics/obs_exporter.go
- internal/obsreportconfig/obsmetrics/obs_processor.go
- internal/obsreportconfig/obsmetrics/obs_receiver.go
- internal/obsreportconfig/obsmetrics/obs_scraper.go
- internal/obsreportconfig/obsmetrics/obsmetrics.go
- internal/obsreportconfig/obsreportconfig.go
- internal/obsreportconfig/obsreportconfig_test.go
- obsreport/obsreport.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_scraper.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- processor/batchprocessor/metrics.go
- processor/processorhelper/processor.go
- service/telemetry.go
Hide OpenCensus references from public APIs in `obsreport` and `obsreporttest` packages, there are 3 public APIs in `obsreport` are using OpenCensus View.
**Changes**
1. Moved `obsreport.Configure()` and `AllViews()` into internal folder `obsreportconfig` and made `AllViews` private, only keep the necessary telemetry APIs in `obsreport`. It helps to separate obsreport telemetry setup and collector telemetry reporting. Also, it hides the unnecessary public APIs.
2. Moved the OpenCensus metrics(`stats`) defines for each components into internal folder `obsreportconfig/obsmetrics` 
**TODO**
1. Remove `obsreport.ProcessorMetricViews`from the package and update it's consumer
2. update `contrib` package for above changes.
**Checklist,**
obsreport
* `func Configure(level …
> Avoid exposing OpenCensus reference in public APIs

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/factory.go
- exporter/prometheusremotewriteexporter/factory_test.go
Description:
Updated PrometheusRemoteWriteExporter for upcoming client auth extension changes. Moved httpClient creation to Start method of the component. This ensures the call to ToClient() method gets access to host object which is required in the next version of ToClient() apis. 
#3287 #3282
Testing:
Unit tests
Documentation:
Unit tests
> Refactored PromRemoteWriteExporter to create client in Start to accomodate future update to ToClient() apis 

- obsreport/obsreport_receiver.go
**Description:** Removed the deprecated funcs for the obsreceiver after making changes to the collector-contrib repo
**Link to tracking Issue:** [Issue #2649](https://github.com/open-telemetry/opentelemetry-collector/issues/2649)
> Remove deprecated funcs inside the obsreceiver

- internal/otlp/decoder.go
- internal/otlp/encoder.go
- internal/otlp/from_translator.go
- internal/otlp/to_translator.go
> Add otlpjson as a serializer implementation

- obsreport/obsreport_processor.go
- obsreport/obsreport_test.go
- processor/batchprocessor/metrics.go
> Remove obsreport.ProcessorMetricViews, use BuildProcessorCustomMetricName where needed

- exporter/jaegerexporter/exporter.go
- exporter/jaegerexporter/exporter_test.go
Description:
Updated JaegerExporter for upcoming client auth extension changes
#3287 #3282
Testing:
Unit tests
Documentation:
Unit tests
> Refactored Jaeger exporter to move connection into start for upcoming Auth changes.

- obsreport/doc.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/kafkareceiver/kafka_receiver.go
- receiver/opencensusreceiver/ocmetrics/opencensus.go
- receiver/opencensusreceiver/octrace/opencensus.go
- receiver/otlpreceiver/logs/otlp.go
- receiver/otlpreceiver/metrics/otlp.go
- receiver/otlpreceiver/trace/otlp.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/scraperhelper/scrapercontroller.go
- receiver/zipkinreceiver/trace_receiver.go
> Remove Receive from obsreport.Receiver funcs

- extension/oidcauthextension/README.md
- extension/oidcauthextension/config.go
- extension/oidcauthextension/extension.go
- extension/oidcauthextension/extension_test.go
- extension/oidcauthextension/factory.go
- extension/oidcauthextension/factory_test.go
- extension/oidcauthextension/oidc_server_test.go
- service/defaultcomponents/defaults.go
This PR renames the OIDC Auth Extension to oidcauthextension, following the naming pattern agreed as part of #3128
> Rename OIDC auth extension

- exporter/exporterhelper/logs.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/traces.go
- exporter/prometheusexporter/prometheus.go
- obsreport/doc.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
> Remove Export from obsreport.Exporter funcs

- exporter/README.md
- receiver/README.md
Fixing a minor bug in the README: The log receivers were not sorted alphabetically, fixed it.
> correct minor typo

- CHANGELOG.md
- component/componenttest/nop_extension.go
- component/componenttest/nop_extension_test.go
- component/extension.go
- config/configcheck/configcheck_test.go
- extension/ballastextension/factory.go
- extension/ballastextension/factory_test.go
- extension/extensionhelper/factory.go
- extension/extensionhelper/factory_test.go
- extension/healthcheckextension/factory.go
- extension/healthcheckextension/factory_test.go
- extension/oidcauthextension/factory.go
- extension/oidcauthextension/factory_test.go
- extension/pprofextension/factory.go
- extension/pprofextension/factory_test.go
- extension/zpagesextension/factory.go
- extension/zpagesextension/factory_test.go
- internal/testcomponents/example_extension.go
- service/defaultcomponents/default_extensions_test.go
- service/internal/builder/extensions_builder.go
- service/internal/builder/extensions_builder_test.go
- service/internal/builder/factories_test.go
Continuation work from #2991
Fixes #2650
Replace ExtensionCreateParams with ExtensionCreateSettings.
Replace all dependencies in Extensions.
Signed-off-by: Patryk Matyjasek <pmatyjasek@sumologic.com>
#2650 
**Testing:** 
Update unit tests
In code comments
> Standarize Settings, Params and Parameters in Extensions

- obsreport/obsreport_receiver.go
> Hide unnecessary public struct in obsreport

- testbed/tests/trace_test.go
Closes #2911 by increasing the max allowed RAM usage for the 10k SPS load test. The other limits seem to still be within boundaries.
> Increase max RAM for load test

- config/configloader/testdata/empty-all-sections.yaml
per https://github.com/open-telemetry/opentelemetry-collector/pull/3337#discussion_r643949551 these changes fix a typo that leads to a test failure when using koanf, whose UnmarshalExact method is functional for maps with nil values.
> Fix pipelines typo in config loader test config

- receiver/prometheusreceiver/internal/prom_to_otlp.go
- receiver/prometheusreceiver/internal/prom_to_otlp_test.go
Starts the progressive effort to convert directly from
Prometheus->OTLPPdata
directly instead of
Prometheus->OpenCensusProto->OTLPPdata
by adding a converter for node+resource -> pdata.Resource.
Updates #3137
> receiver/prometheus/internal: add createNodeAndResourcePdata for Prometheus->OTLP Pdata

- Makefile
If there are core dependency changes that affect the contrib go module state the `check-contrib` make target will fail.  These changes run `make gotidy` in the contrib project before running the tests (per https://github.com/open-telemetry/opentelemetry-collector/pull/3337/files#r647145882)
> Run make gotidy for check-contrib

- consumer/pdata/logs_test.go
- consumer/pdata/metrics_test.go
- consumer/pdata/traces_test.go
> Remove usages of InternalRep when possible in pdata tests

- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
- internal/otlptext/databuffer.go
- internal/otlptext/logs.go
- internal/otlptext/logs_test.go
- internal/otlptext/metrics.go
- internal/otlptext/metrics_test.go
- internal/otlptext/traces.go
- internal/otlptext/traces_test.go
> Convert otlptext to implement Marshaler interfaces

- testbed/tests/resource_processor_test.go
Remove also the Nil vs Empty tests since in pdata they are equivalent.
> Remove usage of internal protos in testbed.TestMetricResourceProcessor

- internal/otlp/marshaler.go
- internal/otlp/pb_decoder.go
- internal/otlp/pb_encoder.go
- internal/otlp/pb_test.go
- internal/otlp/unmarshaler.go
> Add encoder/decoder and marshaler/unmarshaler for OTLP protobuf

- exporter/prometheusremotewriteexporter/factory.go
The default retry settings are far off from the Prometheus
Server's behavior. Retry more aggressively to avoid excessive
in-memory buffering.
Fixes open-telemetry/wg-prometheus#54 because the test
times out before the retry is sent.
> Adjust default retry settings for the PRW Exporter

- testbed/testbed/data_providers.go
- testbed/tests/metric_test.go
- testbed/tests/trace_test.go
Alternative to https://github.com/open-telemetry/opentelemetry-collector/pull/3388
> Update FileDataProvider to use the new model.Unmarshaler, avoid InternalRep usage

- service/application.go
**Description:** Uses the cmd's context rather than background. By default, `cobra.Command` will use `context.Background()` if the context is unset, but propagating the context can be useful for people using the app's command directly and calling `ExecuteContext`.
The collector uses `Execute`, which does not set a context in the cmd, so there is no change in the application's behaviour.
> Use cmd's context instead of background

- internal/otlp/json_decoder.go
- internal/otlp/json_encoder.go
- internal/otlp/json_test.go
> Add tests for OTLP JSON encode/decode

- receiver/otlpreceiver/otlp_test.go
> Remove unnecessary proto marshaler tests, avoid using InternalRep in otlprecv

- CHANGELOG.md
- config/configcheck/configcheck.go
- config/configloader/config.go
- config/configloader/config_test.go
- config/configparser/parser.go
- config/internal/configsource/manager.go
- exporter/prometheusremotewriteexporter/config_test.go
- go.mod
- go.sum
- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/otlpreceiver/config.go
- receiver/otlpreceiver/config_test.go
- service/parserprovider/setflag.go
Fixing a bug/adding a feature - These changes resolve https://github.com/open-telemetry/opentelemetry-collector/issues/2594 by replacing internal Viper usage with [Koanf](https://github.com/knadh/koanf) (which appears to be largely created due to this exact issue) and direct mapstructure usage.  The net result of these changes is* that all existing config parser usage is still supported, but config cases are respected/preserved, which is extremely helpful for dynamic and arbitrary map values for case sensitive use cases.
I opted not to add a transitional approach or parser setting to better manage the resulting complexity and since none of the contrib tests seem to be affected (apart from case sensitivity and a new dependency requirement).**
Since Koanf+mapstructure usage …
> Replace Viper with Koanf

- internal/otlp/pb_decoder.go
- internal/pdatagrpc/traces.go
- receiver/otlpreceiver/internal/logs/otlp.go
- receiver/otlpreceiver/internal/logs/otlp_test.go
- receiver/otlpreceiver/internal/metrics/otlp.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
- receiver/otlpreceiver/internal/trace/otlp.go
- receiver/otlpreceiver/internal/trace/otlp_test.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlphttp.go
> Change oltpreceiver to use the new unmarshaler, avoid grpc-gateway dependency

- exporter/otlpexporter/otlp_test.go
- internal/pdatagrpc/logs.go
- internal/pdatagrpc/metrics.go
- internal/pdatagrpc/traces.go
- receiver/otlpreceiver/internal/logs/otlp.go
- receiver/otlpreceiver/internal/logs/otlp_test.go
- receiver/otlpreceiver/internal/metrics/otlp.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
- receiver/otlpreceiver/internal/trace/otlp.go
- receiver/otlpreceiver/internal/trace/otlp_test.go
> Add grpc response struct for all signals instead of returning interface

- receiver/kafkareceiver/kafka_receiver_test.go
- receiver/otlpreceiver/otlp_test.go
> Remove usage of ToOtlpProtoBytes, will be removed after Marshaler is released

- receiver/scrapererror/partialscrapeerror.go
- receiver/scrapererror/partialscrapeerror_test.go
Go development practices favors returning concrete types over interfaces, so the users don't have to force cast the return value to the concrete type and the APIs self document the returned error type.
> Return concrete error type

- CHANGELOG.md
- receiver/prometheusreceiver/config.go
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/factory.go
- receiver/prometheusreceiver/testdata/invalid-config-prometheus-relabel.yaml
Don't allow changing the metric name using prometheus metric_relabel_configs.  This doesn't currently work (https://github.com/open-telemetry/opentelemetry-collector/issues/2297), and can't easily be made to work (https://github.com/prometheus/prometheus/issues/8893).  Until we can make it work correctly, we should fail loudly.
Issue: https://github.com/open-telemetry/opentelemetry-collector/issues/2297
**Testing:**
Unit tests added
> Disallow renaming metrics using the prometheus receiver

- receiver/kafkareceiver/factory.go
- receiver/kafkareceiver/factory_test.go
- receiver/kafkareceiver/kafka_receiver.go
- receiver/kafkareceiver/kafka_receiver_test.go
- receiver/kafkareceiver/pdata_unmarshaler.go
- receiver/kafkareceiver/pdata_unmarshaler_test.go
- receiver/kafkareceiver/unmarshaler.go
- receiver/kafkareceiver/unmarshaler_test.go
Currently _kafkareceiver_ doesn't support metrics type. This PR adds metrics support to it (almost a direct copy/substitute from traces/logs implementation).
**Testing:**
- `go test ./...`: under kafkareceiver folder, all pass
- `make test`: some cases failed locally but should be unrelated
- manual test with this configs (another collector configured with _hostmetrics_ receiver and _kafka_ exporter):
```yaml
receivers:
otlp:
protocols:
grpc:
http:
kafka/a:
protocol_version: "2.0.0"
topic: asdf_traces
kafka/b:
protocol_version: "2.0.0"
topic: asdf_metrics
processors:
batch:
exporters:
logging:
logLevel: debug
service:
pipelines:
traces:
receivers: [kafka/a]
exporters: [logging]
metrics:
receivers: [kafka/b]
exporters: [logging]
```
**Caveats:**
If same config is used …
> add metrics to kafkareceiver

- receiver/prometheusreceiver/internal/staleness_store.go
- receiver/prometheusreceiver/internal/staleness_store_test.go
Implements a simple store that will be used to record stale metrics;
those that are NOT present in the current scrape, but were in the prior
scrape. This logic will then be attached to our receiver logic
to then complete the mechanism and then issue stale markers.
Updates #3413
Updates #2961
> receiver/prometheus: add store to track stale metrics

- processor/attributesprocessor/testdata/config.yaml
Update attributes in the `config.yaml` of attributes processor. So the regex value is consistent with the comment above it, as suggested in the issue.
#2843
> Update the example config of attributes processor

- receiver/zipkinreceiver/trace_receiver.go
The lock wasn't called from more than one location.
Relates #3041
> [receiver/zipkin] Remove unused locking

- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_darwin.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_fallback.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_linux.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_unix.go
- receiver/hostmetricsreceiver/internal/testutils.go
The `processes` scraper in `hostmetricsreceiver` did not use boot startTime, unlike the rest of the scrapers.
While I'd consider this a bug, could be considered a minor feature request.   Specifically, the [OTLP spec](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L117) strongly recommends start timestamps for points with Aggregation Temporarily.   This is *not* required due to compatibility with non-OTel metric format, but we should have a really good reason not to provide a valid timestamp.
I just found this yesterday, can open a bug for this PR if needed.
Here's what I did:
- Wire boot timestamp through to processes scraper (matches all other host metrics receivers).
- Add a more verbose output on timestmap …
> Fix missing startTimestamp for processes scraper.

- config/configgrpc/README.md
**Description:** This change is in line with the recent updates for the `per_rpc_auth` feature as mentioned [here](https://github.com/open-telemetry/opentelemetry-collector/issues/3472)
**Link to tracking Issue:** #3472 
**Documentation:** Updates to change the way `per_rpc_auth` should be used.
> Update gRPC Configuration Settings README.md

- exporter/fileexporter/file_exporter.go
- exporter/fileexporter/file_exporter_test.go
- exporter/kafkaexporter/pdata_marshaler.go
- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
- exporter/otlphttpexporter/otlp.go
- internal/otlp/pb_test.go
- internal/otlptext/logs.go
- internal/otlptext/logs_test.go
- internal/otlptext/metrics.go
- internal/otlptext/metrics_test.go
- internal/otlptext/traces.go
- internal/otlptext/traces_test.go
- model/pdata/logs.go
- model/pdata/logs_test.go
- model/pdata/metrics.go
- model/pdata/metrics_test.go
- model/pdata/traces.go
- model/pdata/traces_test.go
- receiver/kafkareceiver/kafka_receiver_test.go
- receiver/kafkareceiver/pdata_unmarshaler.go
- receiver/otlpreceiver/otlp_test.go
- receiver/otlpreceiver/otlphttp.go
- receiver/zipkinreceiver/trace_receiver.go
- testbed/testbed/data_providers.go
> Change Marshaler/Unmarshaler to be consistent with other interfaces

- CHANGELOG.md
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/pagingscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/factory.go
- receiver/scraperhelper/scraper.go
- receiver/scraperhelper/scrapercontroller.go
- receiver/scraperhelper/scrapercontroller_test.go
This removes the MetricsScraper and ResourceMetricsScraper interfaces in favor
of a single Scraper interface that scrapes and returns pdata.Metrics. There
were already helper wrappers that allow users to return MetricSlices and
ResourceMetricSlices. These helpers package those results into pdata.Metrics
for the base interface.
Resolves #3085: This also removes the multiMetricScraper which wrapped multiple
scrapers to appear as a single scraper but then functions like scraper.ID()
would be empty. This was evident when trying to log errors and you couldn't
figure out what scraper made the error because it was wrapped in the
multiscraper.
> scraperhelper: use common scraping interface

- translator/trace/zipkinv1/json.go
- translator/trace/zipkinv1/json_test.go
- translator/trace/zipkinv1/thrift.go
- translator/trace/zipkinv1/thrift_test.go
- translator/trace/zipkinv1/to_translator.go
> zipkinv1 implement directly Unmarshaler interface

- exporter/zipkinexporter/zipkin.go
- receiver/kafkareceiver/zipkin_unmarshaler_test.go
- receiver/zipkinreceiver/trace_receiver_test.go
- translator/trace/zipkinv2/from_translator.go
- translator/trace/zipkinv2/from_translator_test.go
- translator/trace/zipkinv2/json.go
- translator/trace/zipkinv2/json_test.go
- translator/trace/zipkinv2/protobuf.go
- translator/trace/zipkinv2/protobuf_test.go
- translator/trace/zipkinv2/to_translator.go
Keep the To/From translator, but update them to accept/return zipkin model.
> zipkinv2 implement directly Marshaler/Unmarshaler interface

- receiver/otlpreceiver/internal/logs/otlp.go
- receiver/otlpreceiver/internal/logs/otlp_test.go
- receiver/otlpreceiver/internal/metrics/otlp.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
- receiver/otlpreceiver/internal/trace/otlp.go
- receiver/otlpreceiver/internal/trace/otlp_test.go
> Small nits in otlp/receiver

- model/otlp/pb_test.go
- model/pdata/logs.go
- model/pdata/logs_test.go
- model/pdata/metrics.go
- model/pdata/metrics_test.go
- model/pdata/traces.go
- model/pdata/traces_test.go
> Remove to from proto in pdata, can use OTLP marshaler/unmarshaler

- receiver/scraperhelper/scraper.go
- receiver/scraperhelper/scrapercontroller_test.go
On error pdata.Metrics may not be initialized so guard against it. Update test
to return uninitialized object on error.
> scraperhelper: fix case when returned pdata is empty

- extension/ballastextension/README.md
- extension/ballastextension/config.go
- extension/ballastextension/config_test.go
- extension/ballastextension/factory.go
- extension/ballastextension/memory_ballast.go
- extension/ballastextension/memory_ballast_test.go
- extension/ballastextension/testdata/config_invalid.yaml
- internal/cgroups/cgroups.go
- internal/iruntime/mem_info.go
- internal/iruntime/mem_info_test.go
- internal/iruntime/total_memory_linux.go
- internal/iruntime/total_memory_other_test.go
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
**Descritpion:** 
Enhance the current ballast extension which is to set memory ballast for the collector process.  And we'll remove `--mem-ballast-size-mib` support from command line later.
**The changes,**
Added new configuration `size_in_percentage` which can dynamically set ballast size based on the total memory of the running environments. (hosts, Docker, K8s, etc)
**Sample Config,**
```yaml
extensions:
memory_ballast:
size_in_percentage: 20
```
**How ballast size is calculated by percentage setup**
When `size_in_percentage` is enabled with the value(1-100), the `ballast_size` will be calculated by 
`size_in_percentage * totalMemory`. The `totalMemory` will be calculated for hosts and containers(in docker, k8s, etc) by the following steps,
1. Look up Memory Cgroup subsystem where the …
> Support setting ballast size in percentage of total Mem in ballast extension

- receiver/otlpreceiver/otlp_test.go
> Replace usage of internal/data in otlpreceiver tests with a small hack, will fix later

- receiver/prometheusreceiver/internal/metrics_adjuster.go
- receiver/prometheusreceiver/internal/metrics_adjuster_test.go
**Description:** Fixes bounds check and nil pointer dereferences that may occur when adjusting histogram and summary metric points.
**Link to tracking Issue:** #3058
> receiver/prometheus: avoid nil pointer deref when adjusting metric points

- service/collector.go
This is follow up to #2277. The internal channel must have been renamed too.
> Rename the shutdown channel

- .golangci.yml
- cmd/pdatagen/internal/base_fields.go
- cmd/pdatagen/internal/metrics_structs.go
- model/internal/data/protogen/common/v1/common.pb.go
- model/internal/data/protogen/logs/v1/logs.pb.go
- model/internal/data/protogen/metrics/v1/metrics.pb.go
- model/internal/data/protogen/trace/v1/trace.pb.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
- model/pdata/metrics.go
- model/pdata/metrics_test.go
Updating OTLP to version 0.8.0. Here is a checklist of the progress so far:
> update OTLP to v0.8.0

- exporter/exporterhelper/factory_test.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
- exporter/fileexporter/factory.go
- exporter/jaegerexporter/exporter.go
- exporter/jaegerexporter/exporter_test.go
- exporter/jaegerexporter/factory.go
- exporter/kafkaexporter/factory.go
- exporter/loggingexporter/factory.go
- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
- exporter/opencensusexporter/factory.go
- exporter/otlpexporter/factory.go
- exporter/otlphttpexporter/factory.go
- exporter/prometheusexporter/factory.go
- exporter/prometheusremotewriteexporter/factory.go
- exporter/zipkinexporter/factory.go
In a future PR ExporterCreateSettings will carry Tracer and Meter for custom tracing/metrics.
> Change exporterhelper to accept ExporterCreateSettings instead of just logger

- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
- receiver/prometheusreceiver/internal/ocastore.go
- receiver/prometheusreceiver/internal/staleness_end_to_end_test.go
- receiver/prometheusreceiver/internal/staleness_store.go
- receiver/prometheusreceiver/internal/staleness_store_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/internal/transaction_test.go
- receiver/prometheusreceiver/metrics_receiver.go
- receiver/prometheusreceiver/metrics_receiver_test.go
Adds the staleness store to the metricsBuilder and transaction to track when metrics
disappear between scrapes.
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/3414
Fixes #3413
Fixes #2961
> receiver/prometheus: glue and complete staleness marking for disappearing metrics

- internal/goldendataset/testdata/pict_input_metrics.txt
I used the following command to regenerate pict pairs and found that the data didn't match what was currently there, looking at the input data, it looks like`DoubleHistogram` should have been renamed along w/ the generated data.
```
pict ./testdata/pict_input_metrics.txt > testdata/generated_pict_pairs_metrics.txt
```
I don't have a good sense for how to get `pict` generation as part of the build. The hard problem seems to be getting a binary for it built. I just ran the command I installed w/ brew on my machine.
> fix DoubleHistogram in pict input data

- component/componenttest/nop_exporter.go
- component/componenttest/nop_extension.go
- component/componenttest/nop_processor.go
- component/componenttest/nop_receiver.go
- component/exporter.go
- component/extension.go
- component/processor.go
- component/receiver.go
- service/internal/builder/exporters_builder.go
- service/internal/builder/exporters_builder_test.go
- service/internal/builder/extensions_builder.go
- service/internal/builder/extensions_builder_test.go
- service/internal/builder/pipelines_builder.go
- service/internal/builder/pipelines_builder_test.go
- service/internal/builder/receivers_builder.go
- service/internal/builder/receivers_builder_test.go
- service/service.go
Followup PR will use the passed tracer to construct obsreport.
> Pass a TracerProvider via construct settings to all the components

- docs/metric-metadata.yaml
Noticed there was a mention of `doiuble histogram` left in the documentation, this change fixes that.
> fix mention of double histogram in documentation

- config/configtls/README.md
- config/configtls/configtls.go
- config/configtls/configtls_test.go
Users want to be to choose the min and max versions they want to allow. Introduce two new settings to make the version range configurable.
Fixes #3396.
> Allow users to set min and max TLS versions

- receiver/prometheusreceiver/config.go
- receiver/prometheusreceiver/factory.go
Validate against nil configuration and configuration with no scrape_configs.
Fixes #2705.
> Validate the Prometheus configuration

- service/collector.go
Currently, the behavior allows collector to be shutdown and restarted by Run. But we shouldn't promise this behavior given it may complicate the Collector implementation over time even though it doesn't present a significant advantage to the alternative: reconstructing a collector and running it. We can always flex this behavior if Shutdown -> Run -> Shutdown becomes a critical to support.
> Document that (*Collector).Run shouldn't be called after shutdown

- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
**Description:** attempts to ensure that the prometheus receiver correctly ingests counter metrics, regardless whether the producing system includes a `_total` suffix on the counter metric name.
**Fixes:** #3557
> receiver/prometheus: add `_total` to list of trimmable metric name suffixes

- exporter/exporterhelper/doc.go
- exporter/fileexporter/doc.go
- exporter/kafkaexporter/doc.go
- exporter/loggingexporter/doc.go
- exporter/opencensusexporter/doc.go
- exporter/otlpexporter/doc.go
- exporter/otlphttpexporter/doc.go
- exporter/prometheusexporter/doc.go
- exporter/prometheusremotewriteexporter/doc.go
- exporter/prometheusremotewriteexporter/exporter.go
- exporter/zipkinexporter/doc.go
Some exporters have package godocs and some doesn't. It gives an impression that the package with godocs are not mature. I'll follow up with godoc additions to receivers and processors.
> Add missing package docs to exporters

- service/collector.go
- service/settings.go
service.Collector is handling the signal management and implementing a graceful shutdown. This is a problem for collectors that want to wire their own signal handling in cases they want to add custom logic and/or have resources other than the service.Collector to shutdown. Moving the graceful shutdown out of the service package to let the main programs do the wiring themselves.
Fixes #3490
> Make graceful shutdown optional

- processor/attributesprocessor/attributes_log.go
- processor/attributesprocessor/attributes_trace.go
- processor/attributesprocessor/factory.go
- processor/filterprocessor/factory.go
- processor/filterprocessor/filter_processor.go
- processor/memorylimiter/factory.go
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
- processor/probabilisticsamplerprocessor/probabilisticsampler.go
- processor/processorhelper/logs.go
- processor/processorhelper/logs_test.go
- processor/processorhelper/metrics.go
- processor/processorhelper/metrics_test.go
- processor/processorhelper/traces.go
- processor/processorhelper/traces_test.go
- processor/resourceprocessor/factory.go
- processor/resourceprocessor/resource_processor.go
- processor/spanprocessor/factory.go
- processor/spanprocessor/span.go
> Use Func pattern in processorhelper, consistent with others

- config/configauth/mock_serverauth.go
- config/configauth/mock_serverauth_test.go
- config/configauth/serverauth.go
- config/configauth/serverauth_test.go
- extension/oidcauthextension/extension.go
- extension/oidcauthextension/extension_test.go
This PR is split from #3552 and contains only the first commits from that, as discussed during today's SIG Collector call. 
﻿Signed-off-by: Juraci Paixão Kröhling juraci@kroehling.de
> Prepare auth API to return a context

- model/pdata/common.go
- model/pdata/common_test.go
The implementation AttributeValue.Equals() was incomplete, because it didn't handle values that were of map (kvlist) type. This PR handles that case.
Possibly #2488.
**Testing:**
Added to the existing unit test.
> Implement Equal() for map-valued AttributeValues

- model/internal/otlp_wrapper.go
- model/internal/otlp_wrappers_test.go
- model/otlp/pb_unmarshaler.go
Deprecating IntHistogram. As per https://github.com/open-telemetry/opentelemetry-proto/blob/f3b0ee0861d304f8f3126686ba9b01c106069cb0/opentelemetry/proto/metrics/v1/metrics.proto#L170, the OTLP receiver will translate `IntHistogram` into `Histogram`. Would love any pointers on how to improve the tests here, are there are utilities I've not used in the collector codebase to make the test less manual?
**Link to tracking Issue:** Part of #3534 
**Testing:** Added a test to ensure both `Histogram` and `IntHistogram` are valid `Histogram` after translation.
> translate IntHistogram to Histogram in otlp_wrappers

- extension/ballastextension/memory_ballast.go
- processor/memorylimiter/README.md
- processor/memorylimiter/config.go
- processor/memorylimiter/factory.go
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
- service/defaultcomponents/default_extensions_test.go
- service/defaultcomponents/defaults.go
1. enable `ballastextension` component 
2. Make memory limiter uses the ballast size value from ballast extension if it is enabled.
https://github.com/open-telemetry/opentelemetry-collector/issues/2516
**Testing:** 
make all
> Add validation on ballast size between memorylimiter and ballastextension

- model/internal/otlp_wrapper.go
- model/internal/otlp_wrappers_test.go
Deprecating IntGauge As per https://github.com/open-telemetry/opentelemetry-proto/blob/f3b0ee0861d304f8f3126686ba9b01c106069cb0/opentelemetry/proto/metrics/v1/metrics.proto#L156, the OTLP receiver will translate `IntGauge` into `Gauge`. 
**Link to tracking Issue:** Part of #3534 
**Testing:** Added a test to ensure both `Gauge` and `IntGauge` are valid `Gauge` after translation.
This change is built on top of #3613, will rebase once merged.
> translate IntGauge to Gauge in otlp_wrappers

- internal/goldendataset/resource_generator.go
- testbed/tests/e2e_test.go
- testbed/tests/scenarios.go
- testbed/tests/testdata/ballast_extension.yaml
- testbed/tests/trace_test.go
* Replace `mem-ballast-size-mib` by `ballast extension` in testbed
#2516
> Replace mem-ballast-size-mib by ballast extension in testbed

- CHANGELOG.md
- cmd/pdatagen/internal/base_slices.go
- model/pdata/generated_common.go
- model/pdata/generated_log.go
- model/pdata/generated_metrics.go
- model/pdata/generated_trace.go
**Description:** Use of `Resize()` has been eliminated both in core and contrib.  This PR removes the method entirely from the pdata slice APIs.
**Link to tracking Issue:** #2488
> Remove deprecated pdata slice resize API

- extension/ballastextension/memory_ballast.go
- processor/memorylimiter/factory.go
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
* Remove the global ballast size variable in ballast extension
* Access Ballast extension in Memory Limiter processor via Host.GetExtensions 
#2516
> Access Ballast extension in Memory Limiter via Host.GetExtensions

- service/collector.go
**Description**
Fix bug: The collector hangs when reloading the service fails. This change will cause the collector fail with a fatal error if it can't be reloaded.
**Example**
* Load the collector with a valid config
* Config changed to an invalid config
* Reload the collector using parseprovider.Watchable
* [Current behaviour] Collector hangs in a stopped state
* [New behaviour] Collector exits with fatal error
**Testing**
Manually tested only
> Handle errors when reloading service

- exporter/prometheusremotewriteexporter/wal.go
- exporter/prometheusremotewriteexporter/wal_test.go
- go.mod
- go.sum
Split off from PR #3017, as requested to firstly add the implementation
unwired to the exporter itself to help the reviewers easily understand
Uses an off the shelf WAL implementation to add capabilities
to the Prometheus remote exporter using github.com/tidwall/wal.
By default the WAL will be on and to configure the WAL location,
please use this prometheusremotewrite exporter YAML configuration:
```yaml
exporters:
prometheusremotewrite:
endpoint: "http://some.url:9411/api/prom/push"
wal:
directory: ./waldir/wal_directory
truncate_frequency: 200s
cache_size: 300
```
whose fields are quite similar to Prometheus' WAL fields per
https://docs.google.com/document/d/1cCcoFgjDFwU2n823tKuMvrIhzHty4UDyn0IcfUHiyyI/edit#heading=h.mlf37ibqjgov
We are using an off-the-shelf WAL because:
By the time …
> exporter/prometheusremotewrite: add a WAL implementation without wiring up

- receiver/prometheusreceiver/internal/otlp_metricfamily.go
- receiver/prometheusreceiver/internal/otlp_metricfamily_test.go
Implements metricGroupPdata toDistributionPoint and added unit tests
as well as equivalence tests to ensure the migration will render
the same results.
Updates #3137
Updates PR #3427
> receiver/prometheus: add metricGroup.toDistributionPoint pdata conversion

- receiver/prometheusreceiver/internal/otlp_metricfamily.go
- receiver/prometheusreceiver/internal/otlp_metricfamily_test.go
Implements metricGroupPdata toSummaryPoint and added unit tests
as well as equivalence tests to ensure the migration will render
the same results.
Updates #3137
Depends on PR #3667
Updates PR #3427
> receiver/prometheus: add metricGroup.toSummaryPoint pdata conversion

- model/pdata/common.go
- model/pdata/common_test.go
Fix a bug - Getting the bool value of a non-bool attribute returns false; therefore, equality of a false bool attribute and any non-bool attribute returned true. To fix this issue, the equality of attributes should assert the two attributes share a type.
**Testing:**
The respective unit test was updated to ensure this edge case was hit.
> fix bool attribute equality

- website_docs/getting-started.md
Hi team,
I’m a developer at HashiCorp and I’ve been exploring what it would mean to integrate OpenTelemetry into a system like Nomad. As a first step I ported the “Getting Started” demo and sample files so they be deployed as Nomad jobs.
I don’t know if this is the type of contribution that is expected given the work towards the 1.0 GA, so feel free to close it. 
Also let me know if there are more meaningful contributions that I can make, and that are also more aligned with the roadmap, around integrating OpenTelemetry with Nomad. I would love to help 🙂 
Thank you.
Port examples and demo to Nomad job files.
Add "Getting Started" instructions for Nomad on how to run the collector as an agent or gateway, and the full demo.
> Add Nomad examples on "Getting Started"

- receiver/prometheusreceiver/internal/metricfamily.go
- receiver/prometheusreceiver/internal/otlp_metricfamily.go
- receiver/prometheusreceiver/internal/otlp_metricfamily_test.go
Implements metricGroupPdata toNumberDataPoint and added unit tests
as well as equivalence tests to ensure the migration will render
the same results.
Updates #3137
Depends on PR #3668
Updates PR #3427
> receiver/prometheus: add metricGroup.toNumberDataPoint pdata conversion

- service/internal/builder/exporters_builder.go
- service/internal/builder/exporters_builder_test.go
- service/internal/builder/extensions_builder.go
- service/internal/builder/extensions_builder_test.go
- service/internal/builder/pipelines_builder.go
- service/internal/builder/receivers_builder.go
This PR tries to limit the usage of `config.Component.Id()` to see if this functionality is really needed
> Small cleanups in service/builder

- cmd/pdatagen/internal/base_fields.go
- cmd/pdatagen/internal/metrics_structs.go
- internal/testdata/metric.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
- model/pdata/metrics.go
- receiver/prometheusreceiver/internal/otlp_metricfamily_test.go
- testbed/correctness/metrics/metric_diff.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/oc_to_metrics.go
**Description:** Updates Exemplar to use oneOfPrimitiveValue, this means we'll be able to move away from IntDataPoint in the next change.
**Link to tracking Issue:** Part fo #3534
> update Exemplar to use oneOfPrimitiveValue

- CHANGELOG.md
- service/collector.go
- service/internal/builder/builder.go
- service/internal/telemetry/process_telemetry.go
- service/internal/telemetry/process_telemetry_test.go
* Disable `mem-ballast-size-mib` command line option for setting memory ballast
#2516
> Disable `mem-ballast-size-mib` from command line option

- cmd/pdatagen/internal/base_structs.go
- cmd/pdatagen/internal/metrics_structs.go
- model/pdata/generated_common.go
- model/pdata/generated_log.go
- model/pdata/generated_metrics.go
- model/pdata/generated_resource.go
- model/pdata/generated_trace.go
**Description:** In preparation to remove `IntSum`/`IntGauge`/`IntDataPoint`, marking them as deprecated
> mark IntGauge/IntSum/IntDataPoint as deprecated

- processor/batchprocessor/splitmetrics.go
**Description:** Removing handling for IntGauge and IntSum from the batch processor. Updated `initGaugeIntMetric` and `initSumIntMetric` as part of this change to get the tests to pass. 
**Link to tracking Issue:** #3534
> Remove IntGauge/IntSum from batchprocessor

- receiver/prometheusreceiver/internal/otlp_metricfamily.go
- receiver/prometheusreceiver/internal/otlp_metricsbuilder_test.go
> Convert prometheusreceiver to new Number metrics

- internal/goldendataset/metrics_gen.go
- internal/goldendataset/metrics_gen_test.go
- internal/goldendataset/pict_metrics_gen.go
- internal/goldendataset/pict_metrics_gen_test.go
- internal/processor/filterexpr/matcher.go
- internal/processor/filterexpr/matcher_test.go
- processor/filterprocessor/expr_test.go
- testbed/correctness/metrics/metric_diff.go
- testbed/correctness/metrics/metric_diff_test.go
- testbed/tests/resource_processor_test.go
> Convert testbed to new Number metrics

- extension/zpagesextension/zpagesextension.go
- extension/zpagesextension/zpagesextension_test.go
- go.mod
- go.sum
- service/collector.go
- service/collector_test.go
- service/internal/otel_trace_sampler.go
- service/service.go
- service/settings.go
- service/zpages.go
> Enabel tracez z-pages from otel-go, disable opencensus

- model/pdata/metrics.go
- receiver/prometheusreceiver/internal/otlp_metricfamily_test.go
**Description:** Removing `SetValue` and `Value` functions for `NumberDataPoint` and `Exemplar`. These have been replaced by `SetDoubleVal` and `DoubleVal` and updated in the contrib repo as well.
> remove SetValue/Value func for NumberDataPoint/Exemplar

- cmd/pdatagen/internal/metrics_structs.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
- model/pdata/metrics.go
**Description:** Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/3730, removing `IntGauge` and `IntSum`.
**Link to tracking Issue:** Part of #3534 
Will rebase once #3730 is merged.
> Remove IntGauge/IntSum

- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
Fixes #3734 by using chained interceptors for the gRPC servers. The tests making use of ToServerOptions were also changed to call grpc.NewServer with the obtained options, ensuring that they are valid.
The test TestGrpcServerAuthSettings now calling grpc.NewServer, executed against the configgrpc without the chained interceptors confirms the bug:
```
$ go test ./config/configgrpc/
--- FAIL: TestGrpcServerAuthSettings (0.00s)
panic: The unary server interceptor was already set and may not be reset. [recovered]
panic: The unary server interceptor was already set and may not be reset.
goroutine 23 [running]:
testing.tRunner.func1.2(0xa6c2a0, 0xc0b8a0)
/home/jpkroehling/bin/go/src/testing/testing.go:1144 +0x332 …
```
> Use chained interceptors in the gRPC server

- receiver/prometheusreceiver/internal/metricfamily.go
- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
- receiver/prometheusreceiver/internal/otlp_metricfamily.go
- receiver/prometheusreceiver/internal/otlp_metricfamily_test.go
- receiver/prometheusreceiver/internal/transaction.go
With this change, we now infer the actual interval startTime
for cumulative types from the original starttime interval reinforcing
what the OpenTelemetry Proto recommendations say in
https://github.com/open-telemetry/opentelemetry-proto/blob/bc8ee79d8e01faf3310af2987268e94285f354da/opentelemetry/proto/metrics/v1/metrics.proto#L132-L140
Fixes #3691
> receiver/prometheus: use actual interval startTimeMs for cumulative types

- exporter/exporterhelper/resource_to_label_test.go
- exporter/otlpexporter/otlp_test.go
- exporter/otlphttpexporter/otlp_test.go
- exporter/prometheusexporter/prometheus_test.go
- internal/testdata/metric.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
**Description:** This change removes temporary test functions that were added as part of the transition to OTLP v0.8.0, they are no longer needed.
> remove no longer needed test functions

- .golangci.yml
**Description:** Re-enable static checks which were disabled at the beginning of the OTLP v0.8.0 work.
> re-enable static checks

- receiver/prometheusreceiver/internal/otlp_metricfamily.go
- receiver/prometheusreceiver/internal/otlp_metricsbuilder.go
This change wires together the logic to convert
the pdata converters into a method ToMetricPdata
that appends converted metrics. The next change or two,
will then hook everything up directly and will
allow us to delete all the prior code!!
Updates #3137
Updates PR #3674
Requires PR #3694
Updates #3691
> receiver/prometheus: add ToMetricPdata method

- extension/storage/Makefile
- extension/storage/README.md
- extension/storage/doc.go
- extension/storage/nop_client.go
- extension/storage/storage.go
**Description:** As discussed during the SIG, we want to move storage extension to core, starting with the interface (this PR) so persistent buffer implementation (https://github.com/open-telemetry/opentelemetry-collector/issues/2285) could use it
**Link to tracking Issue:** #3424 
**Testing:** Just the interface, no tests
**Documentation:** README.md with API
cc @djaglowski @tigrannajaryan
> Copy contrib's storage interface to core

- cmd/pdatagen/internal/common_structs.go
- cmd/pdatagen/internal/log_structs.go
- cmd/pdatagen/internal/metrics_structs.go
- cmd/pdatagen/internal/trace_structs.go
- model/pdata/generated_log.go
- model/pdata/generated_log_test.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
- model/pdata/generated_trace.go
- model/pdata/generated_trace_test.go
**Description:** Adding SchemaUrl field to:
- `ResourceLogs`
- `ResourceMetrics`
- `ResourceSpans`
- `InstrumentationLibraryLogs`
- `InstrumentationLibraryMetrics`
- `InstrumentationLibrarySpans`
**Link to tracking Issue:** Part of #3535 
Followup to https://github.com/open-telemetry/opentelemetry-collector/pull/3756
> adding SchemaUrl field

- cmd/pdatagen/internal/metrics_structs.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
**Description:** This is the first PR to convert Labels to Attributes, it's adding the attributes field to NumberDataPoint, HistogramDataPoint, SummaryDataPoint.
**Link to tracking Issue:** Part of #3535 
Built on top of https://github.com/open-telemetry/opentelemetry-collector/pull/3759
>  adding Attributes to NumberDataPoint, HistogramDataPoint, SummaryDataPoint

- config/config.go
- config/configloader/config.go
- internal/testcomponents/example_exporter.go
- receiver/hostmetricsreceiver/config.go
- receiver/jaegerreceiver/config.go
- receiver/otlpreceiver/config.go
- receiver/prometheusreceiver/config.go
> Rename CustomUnmarshable to Unmarshallable, typo in the initial name

- config/experimental/configsource/component.go
- config/internal/configsource/manager.go
- config/internal/configsource/manager_test.go
> Make configsource Watchable an optional interface

- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/obsreport_test.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
- exporter/prometheusexporter/factory.go
- exporter/prometheusexporter/factory_test.go
- exporter/prometheusexporter/prometheus.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
- service/collector.go
- service/collector_test.go
- service/settings.go
- testbed/testbed/senders.go
> Change obsreport exporter to accept ExporterCreateSettings

- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/resource_to_label.go
- exporter/exporterhelper/resource_to_label_test.go
- exporter/prometheusexporter/accumulator.go
- exporter/prometheusexporter/accumulator_test.go
- exporter/prometheusexporter/collector.go
- exporter/prometheusexporter/collector_test.go
- exporter/prometheusexporter/prometheus_test.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
- exporter/prometheusremotewriteexporter/testutil_test.go
- internal/testdata/common.go
- internal/testdata/metric.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_metrics_test.go
**Description:** Started moving code from labels to attributes. I initially started with the ocinternal and then ended up having to make a few more changes in order to get all the tests passing. If this change is too big to be reviewed I'm happy to refactor.
**Link to tracking Issue:** Part of #3535 
**Testing:** Updated all the existing tests
Followup to https://github.com/open-telemetry/opentelemetry-collector/pull/3761
> update oc internal, prometheus exporters to use attributes 

- config/configparser/parser.go
- config/configparser/parser_test.go
- config/configparser/testdata/basic_types.yaml
- config/configparser/testdata/embedded_keys.yaml
> Fix Parser.ToStringMap to split the loaded keys by delim

- exporter/prometheusexporter/accumulator.go
- exporter/prometheusexporter/collector.go
- exporter/prometheusremotewriteexporter/helper.go
- translator/internaldata/metrics_to_oc.go
This fixes the calls to `StringVal` that were left as TODOs during the transition from labels to attributes. It addresses the core repo's task list items in https://github.com/open-telemetry/opentelemetry-collector/issues/3815
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/3815
Followup to #3820
> replace StringVal with AttributeValueToString

- model/otlp/pb_marshaler.go
- model/otlp/pb_test.go
- model/pdata/common.go
- model/pdata/logs.go
- model/pdata/metrics.go
- model/pdata/metrics_test.go
- model/pdata/traces.go
- model/pdata/traces_test.go
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
**Description:** remove OtlpProtoSize in favor of Sizer interface.
This change adds a `Sizer` interface + an implementation for `pb_marshaler` as per the discussion in #3531. This allows us to remove `OtlpProtoSize()` from traces/metrics/logs and will allow different marshalers to implement `Size()` themselves.
**Link to tracking Issue:** Fixes #3531
**Testing:** Moved size tests for traces/metrics/logs to `pb_marshaler` and converted `batch_processor_test` to use the *Sizers from `pb_marshaler`
> all: remove OtlpProtoSize in favor of Sizer interface

- model/go.mod
- model/go.sum
> Bump google.golang.org/grpc from 1.39.0 to 1.40.0 in /model

- go.mod
- go.sum
Fix wmi error on contrib tests by requiring the latest version. 
This error was probably introduced by #3802.
This uncovers a different, unrelated error:
```
go test -race -timeout 30s ./...
/home/circleci/go/pkg/mod/github.com/influxdata/influxdb-observability/common@v0.2.4/metrics_sort.go:20:35: m.Gauge().DataPoints().At(l).LabelsMap undefined (type pdata.NumberDataPoint has no field or method LabelsMap)
/home/circleci/go/pkg/mod/github.com/influxdata/influxdb-observability/common@v0.2.4/metrics_sort.go:24:33: m.Sum().DataPoints().At(l).LabelsMap undefined (type pdata.NumberDataPoint has no field or method LabelsMap)
/home/circleci/go/pkg/mod/github.com/influxdata/influxdb-observability/common@v0.2.4/metrics_sort.go:29:39: m.Histogram().DataPoints().At(l).LabelsMap …
```
> Fix wmi error on contrib-tests

- config/experimental/configsource/component.go
- config/internal/configsource/manager.go
- config/internal/configsource/manager_test.go
This PR makes the ConfigSource equivalent with the Session, and
relies on the fact that when created ConfigSource does what
NewSession was doing.
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/3792
> Remove unnecessary Session, one per ConfigSource anyway

- receiver/prometheusreceiver/README.md
- receiver/prometheusreceiver/config.go
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/testdata/invalid-config-prometheus-unsupported-features.yaml
With this change, we reject advanced Prometheus features that the
collector won't support. This way users will be cognizant of what isn't
supported. This way, anyone who adds this configuration to their
Prometheus receiver section
```yaml
receivers:
prometheus:
buffer_period: 234
buffer_count: 45
use_start_time_metric: true
start_time_metric_regex: '^(.+_)*process_start_time_seconds$'
config:
scrape_configs:
- job_name: 'demo'
scrape_interval: 5s
remote_write:
- url: "https://example.org/write"
remote_read:
- url: "https://example.org/read"
rule_files: ["a", "b"]
alerting:
alert_relabel_configs:
- separator: ","
target_label: "fix"
- separator: "|"
target_label: "gotham"
alertmanagers:
- scheme: "http"
path_prefix: "/prefix1"
timeout: 1s
```
will be shown what we don't support these …
> receiver/prometheus: make Config.Validate reject unsupported Prometheus advanced features

- CHANGELOG.md
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/zipkinreceiver/trace_receiver_test.go
- translator/conventions/v1.5.0/nonstandard.go
- translator/internaldata/oc_to_traces.go
- translator/internaldata/traces_to_oc.go
- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerproto_to_traces_test.go
- translator/trace/jaeger/jaegerthrift_to_traces_test.go
- translator/trace/jaeger/traces_to_jaegerproto.go
- translator/trace/jaeger/traces_to_jaegerproto_test.go
- translator/trace/protospan_translation.go
- translator/trace/zipkinv1/json_test.go
- translator/trace/zipkinv1/status_code.go
- translator/trace/zipkinv1/thrift_test.go
- translator/trace/zipkinv2/from_translator.go
- translator/trace/zipkinv2/from_translator_test.go
- translator/trace/zipkinv2/to_translator.go
Deprecate the old values and replace with the new value defined by the specification.
This may be a breaking change for backends that expect this value.
See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md
> Change semantic conventions for status (code, msg) as per specifications

- service/parserprovider/provider.go
- service/settings.go
Watching is a loaded term and gives an impression that it's a mechanism that could be used to continuously report new configuration changes. We could have called this interface a Waiter, but it's too late to make changes, hence adding some comments to clarify it's not used for continuous config updates.
> Clarify that Watchable is not used for continuous watching

- exporter/kafkaexporter/config.go
- exporter/kafkaexporter/config_test.go
- exporter/kafkaexporter/factory.go
- exporter/kafkaexporter/kafka_exporter.go
- exporter/kafkaexporter/testdata/config.yaml
A new `kafkaexporter` setting `max_message_bytes` has been added, under `producer` section.
https://github.com/open-telemetry/opentelemetry-collector/issues/3579
**Testing:**
A test was added to validate that configuration is parsed correctly.
Tested for messages bigger than default allowed.
> Adding max_message_bytes for producer configuration to kafkaexporter

- exporter/exporterhelper/internal/bounded_queue.go
- exporter/exporterhelper/internal/bounded_queue_test.go
- go.mod
- go.sum
This functionality is not used and brings unnecessary dependencies, we will use Otel anyway.
> Remove export metrics logic from copied BoundedQueue

- internal/testdata/common.go
- internal/testdata/metric.go
- model/pdata/common.go
- model/pdata/common_test.go
- model/pdata/metrics_test.go
As per issue #3926, adding `NewAttributeMapFromMap` for consistency. As part of this also deprecating the existing `InitFromMap` will will be removed once the contrib repo is updated.
**Link to tracking Issue:** part of #3926 
**Testing:** Updated existing tests
> add NewAttributeMapFromMap, mark InitFromMap deprecated

- model/pdata/timestamp.go
**Description:** Removes the pdata.TimestampFromTime function in preparation for pdata release candidate.
Fixes #3925
> Remove deprecated pdata.TimestampFromTime.

- service/telemetry.go
**Description:** only initialize internal telemetry once.
This change updates the init() method for `colTelemetry` (which is a singleton) to run at most once. This allows multiple collector instances to be run in the same process.
**Link to tracking Issue:** open-telemetry/wg-prometheus/issues/34
**Testing:** Manually tested and was able to create multiple collectors in the same process, while previously, it would error out with:
```
Error: failed to initialize telemetry: processor/batch/batch_send_size: cannot register view "processor/batch/batch_send_size"; a different view with the same name is already registered                        
processor/batch/batch_send_size_bytes: cannot register view "processor/batch/batch_send_size_bytes"; a different view with the same name is already …
```
> service: only initialize telemetry once to prevent errors in multiple instances

- CHANGELOG.md
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/otlp.go
Remove the legacy gRPC port `55680` in OTLP receiver
**Note** - will remove the legacy http port `55681` in a separate PR once we're ready.
**Link**
https://github.com/open-telemetry/opentelemetry-collector/issues/3368
> Remove the legacy gRPC port 55680 in OTLP receiver

- model/pdata/common.go
- model/pdata/common_test.go
**Description:** Takes the second alternative outlined in #3930.  Renames the `NULL` attribute value to `EMPTY` to maintain parity with other collection types that use `AppendEmpty()`.  Added `SetMapVal()` and `SetArrayVal()` to the `AttributeValue` type to simplify converting the entry to those types.  We can later add typed `Append*` methods on the `AnyValueArray` type if this indirection proves too cumbersome.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/3930
> model/pdata: Change AttributeValue NULL->EMPTY

- component/telemetry.go
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/otlp.go
Pass in `ReceiverCreateSettings` to confighttp/configgrpc to support configuring TracerProvider and in the near future MeterProvider.
**Link to tracking Issue:** Fix https://github.com/open-telemetry/opentelemetry-collector/issues/3931
> use ReceiverCreateSettings to configure TracerProvider

- .circleci/config.yml
- .github/workflows/build-and-test.yml
- Makefile
- Makefile.Common
- exporter/exporterhelper/README.md
- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/consumers_queue.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/persistent_queue.go
- exporter/exporterhelper/persistent_queue_test.go
- exporter/exporterhelper/persistent_storage.go
- exporter/exporterhelper/persistent_storage_batch.go
- exporter/exporterhelper/persistent_storage_batch_test.go
- exporter/exporterhelper/persistent_storage_test.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_experimental.go
- exporter/exporterhelper/queued_retry_inmemory.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/queued_retry_v1.go
- exporter/exporterhelper/queued_retry_v2.go
- exporter/exporterhelper/traces.go
Persistent queue implementation within queued_retry, aimed at being compatible with Jager's [BoundedQueue](https://github.com/jaegertracing/jaeger/blob/master/pkg/queue/bounded_queue.go) interface (providing a simple replacement) and backed by [file storage extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage) for storing WAL.
Currently, to run the persistent queue, OpenTelemetry Collector Contrib with `enable_unstable` build tag is required.
**Link to tracking Issue:** #2285 
[Design doc](https://docs.google.com/document/d/1Y4vNthCGdYI61ezeAzL5dXWgiZ73y9eSjIDitk3zXsU/edit#)
**Testing:** Unit Tests and manual testing, more to come
**Documentation:** README.md updated, including an example
> Persistent storage in queued_retry, backed by file storage extension

- service/service.go
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/3957
> Cleanup service, combine small functions to better read the overall flow

- model/semconv/v1.5.0/nonstandard.go
This PR removes the `AttributeHTTPStatusText` const from `/model/semconv/v1.5.0/nonstandard.go`.
This PR, along with PR [5182](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5182) in the collector-contrib repository, address issue #3999
> Remove AttributeHTTPStatusText const from nonstandard.go

- service/collector.go
- service/collector_test.go
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/3957
Need these cleanups to allow separation between flags parsing and usage, this will happen in a separate PR.
> Cleanup collector, remove duplicate fields with settings, restructure code

- CHANGELOG.md
This PR adds a changelog entry for the changes made in #4015 and [contrib/5182](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5182).
#3999, addressed by the PRs mentioned above
One line addition to `CHANGELOG.md`.
> Add changelog entry for removing AttributeHTTPStatusText

- CHANGELOG.md
- model/semconv/v1.5.0/nonstandard.go
Removes `AttributeMessageType` from `/model/semconv/v1.5.0/nonstandard.go`
This PR and PR in [contrib/5186](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5186) addresses #3998  in the collector repository.
> fix: remove AttributeMessageType

- component/componenttest/nop_host.go
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/otlp.go
- receiver/otlpreceiver/otlp.go
Follow up to https://github.com/open-telemetry/opentelemetry-collector/issues/4012, this changes the method signature for `ToServerOption` and `ToDialOption` to receive a `component.Host` which contains the extensions previously passed in.
**Link to tracking Issue:** Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4012
> use component.Host rather than map of extensions in ToServer

- VERSIONING.md
**Description:** Clarifies use of semantic import versioning for semconv packages.  This means that new packages with new import paths may be incompatible with prior packages and may require transition effort.  Prior packages will not go away and should be available for concurrent use.
**Link to tracking Issue:** Fixes #4000
> Add note to versioning doc describing use of spec version in semconv import paths

- config/config.go
- config/config_test.go
- config/configunmarshaler/defaultunmarshaler.go
- config/configunmarshaler/defaultunmarshaler_test.go
- config/configunmarshaler/testdata/invalid-logs-level.yaml
- config/configunmarshaler/testdata/valid-config.yaml
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/3957
Next PRs will use this configuration and it will deprecate/remove the flags.
> Add configuration to setup collector logs via config file.

- config/experimental/configsource/component.go
- config/internal/configsource/manager.go
- config/internal/configsource/manager_test.go
> Remove RetrieveEnd from ConfigSource, proved not used in splunk implementations

- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- model/otlpgrpc/logs.go
- model/otlpgrpc/metrics.go
- model/otlpgrpc/traces.go
- receiver/otlpreceiver/internal/logs/otlp.go
- receiver/otlpreceiver/internal/logs/otlp_test.go
- receiver/otlpreceiver/internal/metrics/otlp.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
- receiver/otlpreceiver/internal/trace/otlp.go
- receiver/otlpreceiver/internal/trace/otlp_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/otlpreceiver/otlphttp.go
> Add a notion of Request to otlp to decouple data from protocol specific metadata

- cmd/pdatagen/internal/metrics_structs.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
Currently `otlpmetrics.Exemplar` (protogen/metrics/v1/metrics.pb.go) has a `TraceId` field and a `SpanId` field, but `pdata.Exemplar` does not provide any function to query/modify these values. This PR expose that by simply adding fields declaration to `cmd/pdatagen/internal/metrics_structs.go`
**Testing:**
- `go test ./...`-ed inside cmd/pdata/internal
> pdata.Exemplar: add function to get/set traceID and spanID

- exporter/exporterhelper/README.md
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_experimental.go
- exporter/exporterhelper/queued_retry_inmemory.go
Description:
This addresses one of the items raised in #4025 (remove the config for persistent queue from stable build).
To implement this, QueueSettings was duplicated. One struct has additional persistent-storage related config. Unfortunately, I couldn't find a more elegant solution while keeping the ability to reuse `exporterhelper.WithQueue`. Perhaps there's a better way to handle that which would not include too much boilerplate?
Link to tracking Issue: #4025
Testing: Unit tests updated
Documentation: README.md updated to make it clear that persistent storage related config requires `enable_unstable` flag
> Use separate config struct for persistent storage

- CHANGELOG.md
- config/configauth/README.md
- config/configgrpc/README.md
- config/configgrpc/configgrpc.go
- config/confighttp/README.md
- config/confighttp/confighttp.go
- config/configtls/README.md
- exporter/otlpexporter/testdata/config.yaml
- exporter/otlphttpexporter/testdata/config.yaml
- receiver/otlpreceiver/config.md
- receiver/otlpreceiver/testdata/config.yaml
Remove the squash for `configtls.TLSClientSetting` in `confighttp` and `cnofiggrpc` per discussion - https://github.com/open-telemetry/opentelemetry-collector/issues/4028
**TODO:** Fix `contrib` tests for the breaking changes
https://github.com/open-telemetry/opentelemetry-collector/issues/4028
> Remove squash on `configtls.TLSClientSetting` in confighttp & cnofiggrpc

- service/internal/builder/exporters_builder.go
- service/internal/builder/pipelines_builder.go
- service/parserprovider/file.go
> Correctly wraps errors instead of wrapping error strings

- CHANGELOG.md
- cmd/otelcol/main.go
- service/collector.go
- service/collector_test.go
- service/collector_windows.go
- service/command.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/3957
> Split Collector from the cobra.Command.

- consumer/consumererror/combine.go
- consumer/consumererror/combine_test.go
This change preserves the original errors used in `consumererrors.Combine` which enables using go 1.13+ errors package to assert the error types.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/4056
**Testing:** 
Added further unit tests to the existing test suite for it.
> Improving usability of combined errors throughout the collector

- service/parserprovider/default.go
- service/parserprovider/merge.go
- service/parserprovider/merge_test.go
- service/parserprovider/setflag.go
- service/parserprovider/setflag_test.go
Fixes a bug where the provider passed to SetFlag provider was not closed.
Followup will add support to merge multiple whatchable providers.
> Add a new type of provider that can merge multiple config providers

- exporter/otlphttpexporter/otlp.go
- model/otlpgrpc/logs.go
- model/otlpgrpc/metrics.go
- model/otlpgrpc/traces.go
- receiver/otlpreceiver/encoder.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlphttp.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/4052
> Add Marshal/MarshalJSON to Request/Response otlpgrpc messages

- receiver/otlpreceiver/otlp_test.go
When the limit is set to 50MB I get this:
```
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (79500054 vs. 52428800)
```
> Add test to prove setting max_recv_msg_size_mib works as expected

- config/configtelemetry/configtelemetry.go
- go.mod
- go.sum
- service/telemetry.go
**Description:** add support for exporting internal metrics via OpenTelemetry library.
This change adds a new flag `--metrics-backend` which can be set to `opentelemetry` to use the [OpenTelemetry Prometheus exporter](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/prometheus) for internal metrics instead of the current OpenCensus implementation. The flag defaults to `opencensus`, preserving the current functionality. There will be follow up PRs that actually set up the existing internal metrics to be exported via the OpenTelemetry library (currently, the exporter will start but will not expose any metrics).
**Link to tracking Issue:** Updates #816 
**Testing:** Added unit tests for the new flag and manually tested to make sure the current internal metrics are still …
> add support for exporting internal metrics via OpenTelemetry library.

- service/collector.go
- service/parserprovider/default.go
- service/parserprovider/default_test.go
> Rename parserprovider.Default to parserprovider.NewDefaultMapProvider

- consumer/consumererror/signalerrors.go
- consumer/consumererror/signalerrors_test.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/traces.go
> Deprecate consumererror.As[Traces|Metrics|Logs], use standard errors.As

- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/producer_consumer_queue.go
- exporter/exporterhelper/persistent_queue.go
- exporter/exporterhelper/persistent_queue_test.go
- exporter/exporterhelper/queued_retry_experimental.go
- exporter/exporterhelper/queued_retry_inmemory.go
This addresses one of the items raised in #4025 (move persistent_queue to internal). The overall refactor is broken into three parts:
* **Part 1**: extracting ProducerConsumerQueue interface out of BoundedQueue (so it could be later used for both memory-based and disk-based queues, preparing ground for Part 2) 👈    (this PR)
* **Part 2**: actual moving Persistent Queue into exporthelper/internal (this also requires exporting `internal.RequestUnmarshaller` and `internal.PersistentRequest`) [(link to draft PR)](https://github.com/open-telemetry/opentelemetry-collector/pull/4116)
* **Part 3**: including metrics on number of batches handled through persistent queue [(link to draft PR)](https://github.com/open-telemetry/opentelemetry-collector/pull/4117)
Link to tracking Issue: #4025
Testing: …
> Move Persistent Queue to exporthelper/internal [Part 1/3]

- examples/k8s/otel-config.yaml
**Description:** Finish removal of health_check extension from k8s example, will lead to confusing output otherwise.
**Link to tracking Issue:** The removal was started in #3903
**Testing:** kubectl reports the pod as ready which it did not before.
> Finish removal of health_check extension from k8s example configuration

- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp_test.go
- exporter/otlphttpexporter/config_test.go
- exporter/otlphttpexporter/factory_test.go
Change TLSClient config to pointer type in `confighttp` and `configgrpc` config
**Related Issue**
https://github.com/open-telemetry/opentelemetry-collector/issues/4028
https://github.com/open-telemetry/opentelemetry-collector/pull/4063#discussion_r711974463
> Change TLSClient config to pointer type

- config/configtest/configtest.go
- config/internal/configsource/manager.go
- consumer/consumererror/combine.go
- go.mod
- receiver/scrapererror/scrapeerror.go
- receiver/scrapererror/scrapeerror_test.go
- receiver/scraperhelper/scrapercontroller.go
- receiver/scraperhelper/scrapercontroller_test.go
- service/collector.go
- service/configcheck.go
- service/defaultcomponents/defaults.go
- service/internal/builder/exporters_builder.go
- service/internal/builder/extensions_builder.go
- service/internal/builder/pipelines_builder.go
- service/internal/builder/receivers_builder.go
- service/internal/fanoutconsumer/logs.go
- service/internal/fanoutconsumer/metrics.go
- service/internal/fanoutconsumer/traces.go
- service/parserprovider/merge.go
- service/service.go
The functionality was added before the support for errors.Is/As was added to golang,
right now this is no longer needed and generic packages like go.uber.org/multierr are more user friendly.
> Deprecate consumererror.Combine, use go.uber.org/multierr

- CHANGELOG.md
- consumer/consumererror/combine_test.go
- consumer/consumererror/permanent.go
- consumer/consumererror/permanent_test.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlphttpexporter/otlp.go
This also will allow us to expose the "permanent" type in the future if needed.
> Rename consumererror.Permanent to consumererror.NewPermanent, consistency

- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/obsreport_test.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/traces_test.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/obsreporttest_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/scraperhelper/scrapercontroller_test.go
Continuing the work in https://github.com/open-telemetry/opentelemetry-collector/issues/4038, this change returns the `TelemetrySettings` from `SetupRecordedMetricsTest` and uses it for components that support `TelemetrySettings`. Once this other [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/3982) is in, we can update the remaining tests to also use these settings
**Link to tracking Issue:** Part of #4038 
Built on top of https://github.com/open-telemetry/opentelemetry-collector/pull/4080
> SetupRecordedMetricsTest returns TelemetrySettings

- obsreport/obsreport_processor.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- processor/memorylimiterprocessor/factory.go
- processor/memorylimiterprocessor/memorylimiter.go
- processor/memorylimiterprocessor/memorylimiter_test.go
**Link to tracking Issue:** #3922
> obsreport: wire up ProcessorCreateSettings for processors using obsreport

- config/configtelemetry/configtelemetry.go
- service/telemetry.go
Added a version tag to the collector's own telemetry metrics because today when looking at those metrics there is no way to know the collector's version, this can also help to know what collector versions are running out there.
I based the "flag" to control this on [PR 3816](https://github.com/open-telemetry/opentelemetry-collector/pull/3816)
> Add version to the internal telemetry metrics

- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/obsreport_test.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/traces_test.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/obsreporttest_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/scraperhelper/scrapercontroller_test.go
Updating a test method and struct:
* `SetupRecordedMetricsTest` -> `SetupTelemetry`
* `TestTelemetrySettings` -> `TestTelemetry`
Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/4093#discussion_r718770901
> rename SetupRecordedMetricsTest -> SetupTelemetry

- extension/ballastextension/README.md
- go.mod
- go.sum
- internal/iruntime/mem_info.go
- service/internal/telemetry/process_telemetry.go
Use version 3 of gopsutil library instead of version 2.
**Link to tracking Issue:** relates to shirou/gopsutil#1078
> Use gopsutil/v3

- component/receiver.go
This is important to make sure failed Consume*() calls are correctly handled
by Receivers and that the Receives in turn correctly respond back to the senders
from which they received data.
We may need to audit all receivers to make sure they work according to these
requirements.
> Clarify how Receivers must handle errors returned by Consume*() functions

- cmd/builder/README.md
Updates the README file for the Collector Builder tool with instructions that will work "out of the box" following the merge into this repo.
**Testing:**
These changes are reproducible for me at a local command line (that's a lot of words for "wfm")
**Thoughts:**
The name `builder` is very generic. The old name `opentelemetry-collector-builder` was more descriptive.
> Update Builder README with new module paths

- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/traces_test.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/obsreporttest_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/scraperhelper/scrapercontroller_test.go
The following change updates various obsreporttest methods to support TestTelemetry:
* CheckExporterMetrics, CheckExporterTraces, CheckExporterLogs
* CheckProcessorTraces, CheckProcessorMetrics, CheckProcessorLogs
* CheckReceiverLogs, CheckReceiverTraces, CheckReceiverMetrics
* CheckScraperMetrics
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4038
This is built on top of https://github.com/open-telemetry/opentelemetry-collector/pull/4281
> Update Check* functions to support TestTelemetry

- component/processor_test.go
Embed `nil` `ProcessorFactory` into `TestProcessorFactory`. This works since there are no calls to the embedded factory on the test.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/pull/4175#discussion_r740650033
> [component] Embed nil ProcessorFactory

- processor/batchprocessor/batch_processor_test.go
The batch size was 100 and the number of datapoints being generated was also 100 so at times, the batch processor would be sending the data before the timeout was reached, which is what this particular test is trying to test. To fix this, I'm increasing the batch send size to 101.
**Link to tracking Issue:** Fixes #4322
> [test] fixing flaky TestBatchMetricsProcessor_Timeout

- CHANGELOG.md
- component/component.go
- component/componenttest/nop_exporter.go
- component/componenttest/nop_extension.go
- component/componenttest/nop_receiver.go
- component/exporter.go
- component/exporter_test.go
- component/extension.go
- component/receiver.go
- component/receiver_test.go
- exporter/exporterhelper/factory.go
- extension/extensionhelper/factory.go
- receiver/receiverhelper/factory.go
- service/configcheck_test.go
Make `component.Factory` embed `internalinterface.InternalInterface`, so that the component factories must be implemented using the helpers.
This also includes extensions (which are not part of the focus of #3921, since extensions don't have per-signal methods), but I think for consistency it's better to add them (moving the internalinterface dependency to individual interfaces wouldn't be a breaking change if we find this is too restrictive).
This is a follow up to #4175.
**Link to tracking Issue:** fixes #3921
> Make `component.Factory` inherit `internalinterface.InternalInterface`

- cmd/builder/cmd/root.go
- cmd/builder/internal/builder/config.go
* Avoid using global viper;
* Print the command name as well when printing version, update command name to reflect new binary name.
* Remove unnecessary empty line.
> Small nits in the builder

- CHANGELOG.md
- config/config.go
- config/configunmarshaler/defaultunmarshaler.go
- config/exporter.go
- config/extension.go
- config/processor.go
- config/receiver.go
> Remove config.[Receivers|Exporters|Processors|Extensions], use map directly

- cmd/builder/cmd/root.go
Adding a feature: stop build if config file in `--config` is set but not exist
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/4308
> stop build if config file not exist

- cmd/builder/internal/root.go
- cmd/builder/main.go
> Move builder/cmd/root to internal, no need to be public

- CHANGELOG.md
- consumer/consumererror/signalerrors.go
> Remove deprecated funcs consumererror.As[Traces|Metrics|Logs]

- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/main.go
- cmd/builder/internal/root.go
- cmd/builder/internal/scaffold/main.go
> Consistent config member name with configuration keys

- CHANGELOG.md
- processor/memorylimiterprocessor/README.md
- processor/memorylimiterprocessor/config.go
- processor/memorylimiterprocessor/config_test.go
- processor/memorylimiterprocessor/factory_test.go
- processor/memorylimiterprocessor/testdata/config.yaml
> memorylimiterprocessor: Remove deprecated config (already no-op) ballast_size_mib

- .github/workflows/builder-release.yaml
- cmd/builder/.goreleaser.yml
- docs/release.md
This PR migrates the release workflow for the builder. 
__ATTENTION__: Before merging, ensure that the secret `GORELEASER_KEY` is set for this project. If you do not know what the value should be, ask me.
Closes #4314 
> Release workflow for the builder

- model/internal/data/traceid.go
Fixing a bug - Correct TraceID error log
from
`var errInvalidTraceIDSize = errors.New("invalid length for SpanID")`
to
`var errInvalidTraceIDSize = errors.New("invalid length for TraceID")`
> correct traceid error log

- cmd/builder/.goreleaser.yml
**Description:** Fixing a ldflags bug in the builder. Currently it does not get to replace either version or date.
**Testing:**
Before:
```
goreleaser release --snapshot --rm-dist
./dist/opentelemetry-collector_darwin_amd64/opentelemetry-collector version
2021-11-08T14:41:22.701-0600	INFO	internal/root.go:100	OpenTelemetry Collector distribution builder	{"version": "dev", "date": "unknown"}
2021-11-08T14:41:22.702-0600	INFO	internal/root.go:120	Using config file	{"path": "/Users/isantos/.otelcol-builder.yaml"}
builder version dev
```
After:
```
./dist/opentelemetry-collector_darwin_amd64/opentelemetry-collector version
2021-11-08T14:46:36.713-0600	INFO	internal/root.go:100	OpenTelemetry Collector distribution builder	{"version": "v0.39.0-next", "date": "2021-11-08T20:46:26Z"} …
```
> fix(builder): fixes ldflags module path for version and date in builder goreleaser

- receiver/otlpreceiver/otlp_test.go
The `createSingleSpanTrace` makes a single testdata.GenerateTracesOneSpan() call, no point in having a separate function for this.
> [test] cleanup in otlp_test

- examples/k8s/otel-config.yaml
Description:
The k8s example [here](https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/main/examples/k8s/otel-config.yaml) has old otel collector image which does not had the new tls config implementation so replacing with new one and command line flag --mem-ballast-size-mib has been deprecated so removed that flag as well.
[4247](https://github.com/open-telemetry/opentelemetry-collector/issues/4247)
Testing:
I performed following steps in minikube k8s
$ kubectl apply -f otel-config.yaml
$ kubectl get pod
and checked all pod were up and there were no TLS error
Documentation:
Once it gets merged I will update the docs.
> OTLP-4278 Update Kubernetes example to latest version

- processor/batchprocessor/splitmetrics.go
- processor/batchprocessor/splitmetrics_test.go
Fix a regression in which metric batches do not have aggregation temporality and IsMonotonic set for cumulative metrics.  The issue was introduced in #3573, where we changed to having to copy each field from the old metric to the new one.  These fields were missed, and thus get their default value when new batches of metrics were created.
I looked at the implementation of [CopyTo](https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/pdata/generated_metrics.go#L716) that is used for copying metrics elsewhere to make sure I fix all issues of this type.  For Sum, we are missing AggregationTemporality and IsMonotonic.  We were also missing [AggregationTemporality](https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/pdata/generated_met …
> Copy AggregationTemporality and IsMonotonic to new metric batches

- CHANGELOG.md
- processor/batchprocessor/splitmetrics_test.go
This makes sure we have full test coverage for all data types in the batch processor, and adds a changelog entry for the fix in #4389, as requested by reviewers.
> Unit test and changelog follow up to batch processor descriptor fix

- exporter/loggingexporter/config.go
- exporter/loggingexporter/config_test.go
- exporter/loggingexporter/factory.go
- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
* Use zapcore.Level in config to avoid manual parsing.
* Use logger.Core to determine if debug is enabled.
> Small nits in logging exporter

- model/internal/cmd/pdatagen/internal/base_structs.go
- model/pdata/generated_common.go
- model/pdata/generated_log.go
- model/pdata/generated_metrics.go
- model/pdata/generated_resource.go
- model/pdata/generated_trace.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/4254 
Try to remove the confusion that the pdata.Metrics cannot be constructed.
> Improve message for New funcs in pdata

- config/configmapprovider/default_test.go
- config/configmapprovider/expand.go
- config/configmapprovider/expand_test.go
- config/configmapprovider/file.go
- config/configmapprovider/inmemory.go
- config/configmapprovider/merge.go
- config/configmapprovider/merge_test.go
- config/configmapprovider/properties.go
- config/configmapprovider/properties_test.go
- config/configmapprovider/provider.go
- config/configmapprovider/simple.go
- config/configtest/configtest.go
- service/collector.go
- service/config_watcher.go
- service/config_watcher_test.go
This uses a callback instead of a blocking WaitForUpdate function
to notify about config changes.
This simplifies the usage of the Provider, especially when watching
for changes is required.
A follow up PR will add watching capabilities to existing Provider
implementations.
> Refactor configmapprovider.Provider and Retrieved interfaces

- cmd/builder/README.md
**Description:** Go1.17 requires [`suffix like @latest or @v1.2.3`][go_1_17_notes] to be used with `go install` which is missing in builder's README.
[go_1_17_notes]: https://golang.org/doc/go1.17#go-get
> builder: fix installation instructions in readme

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/config_test.go
- cmd/builder/internal/builder/main_test.go
- go.mod
- versions.yaml
> Prepare core release v0.39.0

- .github/workflows/builder-release.yaml
The release of the collector builder for 0.39.0 failed due to:
```
⨯ release failed after 10.40s error=failed to get module path: chdir cmd/builder: no such file or directory: 
```
https://github.com/open-telemetry/opentelemetry-collector/runs/4195118833?check_suite_focus=true
Running it locally from the root of the repository did work:
```
$ goreleaser release -f ./cmd/builder/.goreleaser.yml
• running goreleaser v0.184.0-pro
• licensed to juraci.kroehling@grafana.com
• releasing...     
• loading config file       file=./cmd/builder/.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...               commit=57ecd4ff8dc5a37c6f353c7d6f72f49e5dec18c2 latest tag=cmd/builder/v0.39.0
• parsing tag      
• running before hooks
• running hook …
```
> Remove workdir from builder release workflow, restrict to builder tags

- CHANGELOG.md
- model/pdata/common.go
- model/pdata/common_test.go
> Remove deprecated func in pdata

- model/pdata/common.go
- model/pdata/common_test.go
Unfortunately during the code review of the https://github.com/open-telemetry/opentelemetry-collector/pull/3980 I missed this because was kind of "hiden" in a PR that was supposed to just do a rename of NULL -> Empty.
This is yet another example why collector maintainers MUST always ask for small focused PRs and never allow other different changes.
The reason to not allow this is because user need to either "CopyTo" or "MoveTo", right now the way how Set was implemented would share the same memory and is not thread safe since changes in the copied value will be reflected in the destination.
> Remove Set[Map|Slice]Val. They were added in a PR focused on other change

- .github/workflows/changelog.yml
This check ensures the label "skip changelog" has been applied or that the changelog has been updated. This follows the same pattern as the opentelemetry-go and opentelemetry-python SIGs.
> add changelog step in cicd

- client/client.go
- client/client_test.go
- client/doc_test.go
Includes documentation and how it's expected to be used by
both providers and consumers.
Fixes #4058
> Rename client.Client to client.Info

- docs/release.md
- internal/buildscripts/builder-config.yaml
> Include local builder config to release procedure

- CHANGELOG.md
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/factory.go
- exporter/otlpexporter/otlp.go
Adding the ability to pass TelemetrySettings to ToDialOptions to configure underlying instrumentation library.
Fixes #4424
> `configgrpc`: Update `ToDialOptions` with settings

- .golangci.yml
Removed unused `.golangci.yml` rules, they were used when many components lived here.
> [golangci-lint] Remove unused exclude rules

- CHANGELOG.md
- model/semconv/v1.7.0/resource.go
- model/semconv/v1.7.0/trace.go
- model/semconv/v1.8.0/resource.go
- model/semconv/v1.8.0/trace.go
A couple of versions of the spec have been released since semconv was last generated, this brings the collector up to date.
> `semconv`: adding semconv 1.7.0 and 1.8.0

- client/client.go
- client/doc_test.go
> Add AuthData to client.Info

- CHANGELOG.md
- service/collector.go
- service/collector_test.go
- service/collector_windows.go
Currently, the state channel allows only 4 states to be stored at a given time. This is with the assumption that the configuration can't be reloaded dynamically. To be able to support the same we need to be able to not block if there are state changes that are periodically happening. ~This PR makes the state channel inserts non blocking.~
This PR ensures that state change information propagation is not blocking by removing the channel and replacing it with an atomic variable.
> Make state information propogation non blocking on the collector

- .golangci.yml
- config/configgrpc/configgrpc_test.go
- config/configmap.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage_test.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/obsreport_test.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/traces_test.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
- processor/batchprocessor/batch_processor_test.go
- processor/memorylimiterprocessor/memorylimiter_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/scraperhelper/scrapercontroller_test.go
Enable `errcheck` and fix linter errors.
**Link to tracking Issue:** Updates #2789
> Enable `errcheck` linter

- config/configauth/README.md
Fixing a bug - Current documentation in configauth module's README misses client side authenticators documentation. 
This PR adds client authenticators details and link existing client authenticators.
> [Documentation] fixes for configauth module's README

- config/configmapprovider/expand_test.go
This PR solves linting error after #4450  was merged. 
I found a solution at [expoter/otlpexporter/otlp_test.go](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/otlp_test.go#L210-L212)
#4470
> fix: lint error not having a return value of `exp.Shutdown`

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- go.mod
- internal/buildscripts/builder-config.yaml
- versions.yaml
> Prepare v0.40.0

- .github/workflows/builder-release.yaml
- cmd/builder/.goreleaser.yml
- docs/release.md
> Small adjustments to the release config and docs

- exporter/README.md
Fix exporter readme
Removed reference to fileexporter, since that is in contrib
> Remove fileexporter from exporter docs (moved to contrib)

- CHANGELOG.md
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_batch.go
- exporter/exporterhelper/internal/persistent_storage_test.go
This fixes a bug with handling corrupted data by persistent buffer. In principle, when corrupted data is encountered, it should be handled gracefully. This fix makes sure this happens for several scenarios. Also, the change adds several test cases
The original bug was found by @pmalek-sumo and was expressed by following:
```
2021-11-24T11:53:33.753Z    info    internal/persistent_storage.go:309    Fetching items left for dispatch by consumers    {"kind": "exporter", "name": "otlphttp/containers", "queueName": "otlphttp/containers-logs", "numberOfItems": 2}
panic: interface conversion: interface is nil, not internal.PersistentRequest
goroutine 1 [running]:
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*batchStruct).getRequestResult(0xc001653038, …
```
> Handle corrupted persistent storage data gracefully

- internal/otlptext/logs.go
- internal/otlptext/metrics.go
- internal/otlptext/traces.go
This enables printing SchemaURL in logging exporter.
> Include SchemaURL in OTLP text

- CHANGELOG.md
- config/configmap.go
- config/configmap_test.go
- config/configmapprovider/default_test.go
- config/configmapprovider/expand_test.go
- config/configmapprovider/file.go
- config/configmapprovider/inmemory.go
- config/configtest/configtest.go
- config/configunmarshaler/defaultunmarshaler_test.go
- config/internal/configsource/manager.go
- config/internal/configsource/manager_test.go
The benefit of this is that we remove from the public API the assumption that configuration needs to be yaml.
> Remove NewConfigMapFrom[File|Buffer], add testonly version

- docs/release.md
This works around a problem with pushing all the tags at once, which doesn't trigger the github actions.
Fixes #4485
> `docs`: update release documentation to use push-tag

- CHANGELOG.md
- config/configtls/README.md
- config/configtls/configtls.go
Addresses ﻿CWE-327 by setting the minimum TLS version to 1.2. Lower versions can still be set for backwards compatibility with older network appliances, although I don't think any of them are that old to still not have 1.2 available.
> configtls: TLS 1.2 is the new default min version

- CHANGELOG.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- receiver/otlpreceiver/otlp.go
Closes #4512 by adding the component.Host parameter to the confighttp.ToServer function, in preparation for the changes related to configauth. This also changes the order of arguments, to make it consistent with configgrpc.
> `confighttp`: add component.Host parameter to ToServer

- config/confighttp/README.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
Add more config parameters to HTTPClientSettings to be used by multiple http-based exporters
**Description:** Added  3 more config parameters MaxIdleConns, MaxIdleConnsPerHost and IdleConnTimeout in HTTPClientSettings
**Link to tracking Issue:**  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5432#discussion_r716774048
**Testing:** All test cases are passing
> Add more config parameters to HTTPClientSettings to be used by multiple http-based exporters

- receiver/otlpreceiver/otlp.go
Default OTLP HTTP endpoint 0.0.0.0:4318 enables legacy endpoint as well. It makes the migration painless, so we need to encourage users to update their configuration. This change adds a warning message in case if user has the legacy endpoint configured explicitly.
> Add a warning message for legacy OTLP HTTP endpoint usage

- CHANGELOG.md
- config/confighttp/README.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- receiver/otlpreceiver/README.md
- receiver/otlpreceiver/config.md
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/testdata/config.yaml
**Description:** Add support for sending `Access-Control-Max-Age` along with CORS preflight responses.
I have OpenTelemetry Collector deployed, with an OLTP HTTP endpoint configured to accept traces directly from browser clients. I noticed there was no `Access-Control-Max-Age` sent in CORS preflight responses from the collector, meaning the browser needs to send a new preflight request every time the client submits traces to the collector.
**Testing:** I found existing CORS tests, and updated them to exercise the new `cors_max_age` property and check for a `Access-Control-Max-Age` response header.
**Documentation:** I found documentation for the existing CORS receiver properties and added entries for the new `cors_max_age` property.
> Support CORS Max-Age on OTLP/HTTP receiver

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- go.mod
- internal/buildscripts/builder-config.yaml
- versions.yaml
Closes #4524
The current state of the collector seems to be compatible with contrib: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6642
> Prepare v0.41.0

- CHANGELOG.md
- config/configauth/mock_serverauth.go
- config/configauth/serverauth.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
Fixes #4440 by specifying the interface for HTTP auth and implementing it for the OTLP receiver.
> `configauth`: add ServerAuthenticator interfaces for HTTP receivers

- internal/middleware/wrappedstream.go
> Credit grpc-ecosystem/go-grpc-middleware for WrappedServerStream

- config/configtelemetry/configtelemetry.go
- internal/obsreportconfig/obsreportconfig.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_scraper.go
- obsreport/obsreport_test.go
In order to allow for more tests to run concurrently without triggering
the race detector, Level needs to be guarded by some atomic method.
This change makes access to the collector's Level managable via sync
method which may lead to eventual consistent.
[#4543](https://github.com/open-telemetry/opentelemetry-collector/pull/4542#:~:text=I%20had%20raised-,%234543,-to%20help%20track)
**Testing:** 
Nothing at the moment, not exactly sure how best to effectively change made.
> Making access atomic to the collector's level

- .github/workflows/changelog.yml
This reverts commit 5405247048e4e22416d14236ad7be006f4e609a6.
The problem is happening because there's a mismatch between references: previously, the changelog was obtaining the latest commit from `github.base_ref`, which is typically `main`. The referenced commit uses the GitHub Action, which will get the latest commit from the PR itself. Running a diff between the PR against itself yields no results at all:
```console
$ git fetch origin jpkrohling/issue4556 --depth=1
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From github.com:jpkrohling/opentelemetry-collector
* branch              jpkrohling/issue4556 -> FETCH_HEAD
$ git diff --name-only FETCH_HEAD
$
```
Whereas running the same command using `main` in the FETCH_HEAD yields
```console
$ git fetch origin main --depth=1 …
```
> Revert "Use action/checkout fetch-depth instead of manually fetch (#4535)"

- CHANGELOG.md
- config/configmapprovider/merge.go
- config/configmapprovider/merge_test.go
- config/configmapprovider/simple.go
> Fix merge config map provider to close the watchers

- .github/workflows/stale-pr.yaml
To prevent PRs from closing while many maintainers/approvers are away.
> bump staleness to 14 days

- config/configmapprovider/provider.go
- config/configmapprovider/retrieved.go
> config provider: remove the need to call the onChange with close error

- CHANGELOG.md
- service/collector.go
- service/collector_test.go
- service/collector_windows.go
- service/command.go
- service/command_test.go
- service/config_provider.go
- service/config_provider_test.go
- service/settings.go
This change was added new too long ago, but we got clear feedback that it is
unclear how the separation work and how to replace one component or the other.
> Revert separate settings for map provider and unmarshaler

- service/internal/telemetrylogs/logger.go
This was triggered by the Prometheus Staleness tests. Setting the core logger to a NopLogger can cause `NewIncreaseLevelCore` to cause the following error:
"invalid increase level, as level \"fatal\" is allowed by increased level, but not by existing core"
The change in this PR fixes that to ensure the logger is never nil.
> fix nil error introduced in SetColGRPCLogger

- CHANGELOG.md
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/testdata/config.yaml
- use `middleware.CompressionType` instead of grpc's own constants.
- Not to use a map to validate compression keys.
- added tests for each compression methods.
- throw an error for zlib and deflate, which only be supported in confighttp
#4623
> Refactor configgrpc for compression methods

- CHANGELOG.md
- service/config_provider.go
- service/config_provider_test.go
This is to allow backwards compatible "converters" to be implemented and still benefit of the default ConfigProvider implementation, as well as helping previous implementations which had a custom "config.MapProvider" to still use that + the new service.NewDefaultConfigProvider.
> Add an option to allow config.Map conversion in the service.ConfigProvider

- config/configgrpc/configgrpc_test.go
- config/confighttp/confighttp_test.go
- config/configunmarshaler/defaultunmarshaler_test.go
- exporter/loggingexporter/config_test.go
- exporter/otlpexporter/config_test.go
- exporter/otlphttpexporter/config_test.go
- extension/ballastextension/config_test.go
- extension/zpagesextension/config_test.go
- processor/batchprocessor/config_test.go
- processor/memorylimiterprocessor/config_test.go
- receiver/otlpreceiver/config_test.go
- service/service_test.go
**Description:**  
Replace all `path.Join(".",` with `filepath.Join(`
as mentioned [#6459](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6459#discussion_r759550623) in opentelemetry-collector-contrib folder, core also need to be have similar.
#4633
> Otel-4633 Replace path.Join method with filepath.Join method

- config/configgrpc/README.md
- config/configgrpc/configgrpc_benchmark_test.go
Per request in PR #4632, splitting out the addition of compression benchmarks from the change in the default OTLP grpc compression algo. 
Related to Issue #4587.
> Add OTLP grpc compression benchmarks

- service/config_provider.go
- service/config_provider_test.go
- service/internal/configprovider/default.go
- service/internal/configprovider/expand.go
- service/internal/configprovider/expand_test.go
- service/servicetest/configprovider.go
> Transform expand provider to converter

- README.md
Owais is currently not able to allocate much time to the Collector.
Thank you for your contributions, Owais. I hope to see you back when you have more time!
> Remove Owais Lone from the approvers' list

- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage_test.go
This addresses #4563
I was not able to replicate the original issue (I did run the tests in a loop for some time and looked through the code). Perhaps the timeout was too short and the tests suite failed when it was running on an instance that had high resource usage. I made some small improvements to the test (increased the timeout, reduced test logging output)
> Improve persistent storage tests

- CHANGELOG.md
- cmd/builder/internal/command.go
- cmd/otelcorecol/builder-config.yaml
> [Builder]: Enable unmarshal exact to help finding hard to find typos

- internal/otlptext/databuffer.go
- internal/testdata/metric.go
Add support for printing OTLP exponential histograms
Fixes #4641 
**Testing:**
I ran `go test -v` with a modified test to verify that the printed format (which the test does not actually validate for any data point) is correct. 
The math equations used here are copied from https://github.com/open-telemetry/opentelemetry-go/pull/2393 where they have been extensively tested.
> Add otlptext support for exponential histogram

- service/internal/telemetrylogs/logger.go
This simplifies the logic in SetColGRPCLogger.
Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/4598#discussion_r773358541
> refactor: don't bother checking the level

- CHANGELOG.md
- config/configmapprovider/env.go
- config/configmapprovider/file.go
- config/configmapprovider/properties.go
- config/configmapprovider/provider.go
- service/config_provider_test.go
> Define a type for onChange func instead of func pointer

- CHANGELOG.md
- service/internal/configprovider/expand.go
- service/internal/configprovider/expand_test.go
Using Koanf fixed the issue with AllKeys that did not correctly flatten the input map.
> Remove expand cases that cannot happen with config.Map

- config/configmapprovider/env_test.go
- config/internal/configsource/manager_test.go
> Small cleanup in tests, use t.Setenv instead of os, avoids manual cleanup

- CHANGELOG.md
- config/configtest/configtest.go
- config/configunmarshaler/defaultunmarshaler_test.go
- service/internal/configprovider/expand_test.go
- service/servicetest/configprovider.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/4605
Fix bunch of places in tests where we had duplicate code to avoid circular dependencies.
> Remove deprecated configtest.LoadConfig

- cmd/builder/README.md
Per [this Slack thread](https://cloud-native.slack.com/archives/CJFCJHG4Q/p1641843690036300?thread_ts=1641835604.031700&cid=CJFCJHG4Q), the builder was recently updated not to include any components by default.
This PR updates the README's TL;DR example to explicitly include the required core collector modules (OTLP receiver, batch processor, and logging exporter). Without them, the collector you build following those instructions fails to run.
**Link to tracking issue:**
n/a (I just went ahead and opened this PR)
**Testing:**
To reproduce the failure:
- Clone open-telemetry/opentelemetry-collector at https://github.com/open-telemetry/opentelemetry-collector/commit/bed95f1d1c648a8c538ec2698b9f60a2d913ba3b
- Navigate into cmd/builder
- Follow TL;DR instructions, creating …
> Update builder README instructions to include required modules

- CHANGELOG.md
- config/configmapprovider/env.go
- config/configmapprovider/env_test.go
- config/configmapprovider/file.go
- config/configmapprovider/file_test.go
- config/configmapprovider/properties.go
- config/configmapprovider/properties_test.go
- config/configmapprovider/provider.go
- config/configtest/configtest.go
- service/config_provider.go
- service/config_provider_test.go
This is a preliminary change in order to support single/multiple local/remote config sources.
This PR changes the Provider to accept an URI as the resource identifier.
1. The current way is still fully supported and will continue to be supported, but there are more ways to specify the file:
Command line(currently supported): `./otelcol --config=local.yaml`
Command line(currently supported): `./otelcol --config=/path/to/local.yaml`
Command line(new support): `./otelcol --config=file:/path/to/local.yaml`
> Change configmapprovider.Provider to accept an location for retrieve

- CHANGELOG.md
- config/configmapprovider/properties.go
- config/configmapprovider/properties_test.go
- service/config_provider.go
Resolves TODOs left in https://github.com/open-telemetry/opentelemetry-collector/pull/4657
> Change Properties Provider to be a converter, does not match the Provider interface

- CHANGELOG.md
- config/configmap.go
- config/configmapprovider/properties.go
- service/config_provider.go
- service/config_provider_test.go
- service/internal/configprovider/expand.go
The drop of the Config prefix from the func name was forced by go lint, which does not like to repeat the package name as the prefix for types.
> Move service.ConfigMapConverterFunc to config.MapConverterFunc

- .github/workflows/build-and-test.yml
Currently, the key used for cache is based on all hash go.mod and go.sum files. However, go.sum is enough unique to become a hash key for the cache. As a result, it would decrease the time to hash the files and execute the workflow more faster.
N/A
We can test it on the ```buid-and-test``` workflow which will be tested with a Pull Request.
N/A
> Change key cache to use hash go sum only

- CHANGELOG.md
- service/collector_windows.go
Fixes #4685. When `With` is called, clone the original encoder instead of creating a new one. Fields were being dropped because fields are apart of the encoder and each new call to `With` was creating a new encoder.
**Link to tracking issue:**
https://github.com/open-telemetry/opentelemetry-collector/issues/4685
**Testing:**
Tested manually with a windows service.
> Correctly clone windows logging encoder

- CONTRIBUTING.md
The guidelines are necessary to explain how we want to generally approach external process execution. This was recently brought up in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6512
If we accept these guidelines the following should happen:
- The prometheusexecreceiver should be modified to allow only a hard-coded list of exporters.
- The fluentbitextension should be either removed or significantly
limited in terms of what locations and what executable file names it can allow.
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6512
will be rejected, possibly substituted by a plugin system that @zenmoto
referred to in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6512#issuecomment-996922645
if we find useful to have …
> Add external process execution guidelines

- processor/memorylimiterprocessor/README.md
> Remove warning about already removed config value

- CHANGELOG.md
- config/configtelemetry/configtelemetry.go
- config/configunmarshaler/defaultunmarshaler.go
- service/collector_test.go
- service/flags.go
* Usages of `--metrics-level={VALUE}` can be replaced by `--set=service.telemetry.metrics.level={VALUE}`;
* Usages of `--metrics-addr={VALUE}` can be replaced by `--set=service.telemetry.metrics.address={VALUE}`;
> Remove deprecate flags --metrics-level and --metrics-addr

- config/configunmarshaler/defaultunmarshaler.go
- config/configunmarshaler/defaultunmarshaler_test.go
Better error message when config is invalid
This is a replacement for PR https://github.com/open-telemetry/opentelemetry-collector/pull/4517 which seems to be going nowhere.
**Testing:**
I added a simple test for code coverage.  I mostly tested manually with 
```
receivers:
otlp:
protocols:
http:
exporters:
pineapple:
logLevel: debug
service:
pipelines:
traces:
receivers: [otlp]
exporters: [pineapple]
```
which causes the output to become `collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown exporters type "pineapple" for "pineapple" (valid values: [otlp otlphttp logging])`.  (The valid values the new part of the `error`)
cc …
> Include valid factories in error when unknown type in config

- CHANGELOG.md
- config/confighttp/confighttp.go
- receiver/otlpreceiver/config.md
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
Add a max_recv_size option to otlpreceiver's http endpoint.
When not specified it is the default zero value 0, in which case will not introduce the size limit.
**Link to tracking Issue:** #4669
**Testing:**
- a new `TestHTTPMaxRecvSize` test is added in **otlp_test.go** (this uses the existing global json data to test)
- also manually tested
screenshot of a packet capture session for **x-protobuf** content-type
setting `max_recv_size` to 74 for a size 75 message:
update README for otlpreceiver and CHANGELOG
> Add `max_request_body_size` to confighttp.HTTPServerSettings

- CHANGELOG.md
- config/configtelemetry/configtelemetry.go
After the `--metrics-level` flag was removed, this is no longer needed.
> Deprecate configtelemetry.Level.Set()

- CHANGELOG.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/otlp.go
1. Made changes to pass telemetry settings to configHttp Toclient to configure the instrumentation library
2. Instrumented the otlphttp exporter using otel instrumentation library to enable observability.
Fixes: #4449
> configHttp: Ability to pass telemetry settings to http instrument library that instruments the otlphttp exporter

- receiver/otlpreceiver/otlp_test.go
This is a follow-up of https://github.com/open-telemetry/opentelemetry-collector/pull/4677#discussion_r786990737.
These two cases are almost the same so I made a function to avoid duplicate code.
**Testing:** `go test ./...`
> split otlpreceiver's TestMaxRequestBodySize into 2 parts (success & failure)

- CONTRIBUTING.md
To help settle the naming inconsistency across the project, I had drafted up what I had seen as the approach taken for golang projects and have updated the contribution guide.
https://github.com/open-telemetry/opentelemetry-collector/issues/4471
**Testing:**
No testing added though it would nice to see if there was an automated way of validating this across the project.
NA
> Formalise Method Naming Convention

- CHANGELOG.md
- cmd/builder/.goreleaser.yml
drop some platforms for the builder release.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4655
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/4655
**Testing:** Ran goreleaser and check the outputs
This is the new list of arches/platforms:
- Linux arm64
- Linux amd64
- Darwin arm64
- Darwin amd64
- Windows amd64
> Remove support to some arches and platforms from `ocb` (opentelemetry-collector-builder)

- CHANGELOG.md
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
This was changed 1y ago, and it is probably safe to remove it now.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1968
> Remove deprecated legacy path support for otlp http receiver

- CHANGELOG.md
- service/config_provider.go
Split from https://github.com/open-telemetry/opentelemetry-collector/pull/4727
> Copy slice argument, disallow changes from caller to the input slice

- config/configmapprovider/properties.go
- internal/testcomponents/example_exporter.go
> Remove references to viper in comments

- CHANGELOG.md
- service/config_provider.go
- service/config_provider_test.go
The current --config flag breaks backwards compatibility for Windows users as a common path is to use is C: as is used in the collector-contrib MSI for example.
**Link to tracking Issue:** #4725
**Testing:** Added unit test, confirmed with command line manual test.
> ensure windows file path is respected

- CHANGELOG.md
- service/collector_test.go
- service/config_provider.go
- service/flags.go
Restriction (compatible with `--set`): Per flag entry can be defined only one location, to define multiple locations use multiple flag entries (which will be merged in the given order):
```bash
./otelcol --cofig=file:/path/to/first/file --config=file:/path/to/second/file
```
Fixes: https://github.com/open-telemetry/opentelemetry-collector/issues/2701
> Enable end users to provide multiple files for config location

- service/config_provider_test.go
Still unclear how this didn't fail CI before 🤔 
The call in the test was still passing in a `string` instead of `[]string`
> fix call to NewDefaultConfigProvider

- CHANGELOG.md
- config/configmapprovider/expand.go
- config/configmapprovider/expand_test.go
- config/configmapprovider/testdata/expand-with-all-env.yaml
- config/configmapprovider/testdata/expand-with-no-env.yaml
- config/configmapprovider/testdata/expand-with-partial-env.yaml
The use and expansion of environment variables is supported in the Collector configuration. For example:
```
processors:
attributes/example:
actions:
- key: "${DB_KEY}"
action: "${OPERATION}"
```
> expandStringValues function support to map[string]interface{}

- component/componenttest/nop_exporter.go
- component/componenttest/nop_extension.go
- component/componenttest/nop_processor.go
- component/componenttest/nop_receiver.go
- exporter/exporterhelper/common.go
- processor/processorhelper/logs.go
- processor/processorhelper/metrics.go
- processor/processorhelper/processor.go
- processor/processorhelper/traces.go
- receiver/scraperhelper/scraper.go
Try to understand if the Component helper is necessary, or only having the helper funcs is enough.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/4681
> Use directly the consumer helper funcs in the other helpers packages.

- CHANGELOG.md
- client/client.go
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- config/confighttp/clientinfohandler.go
- config/confighttp/confighttp_test.go
**Description:** Add Host property for Metadata
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/4722
> Add Host property for Metadata

- CHANGELOG.md
> Fix changelog entry for #4736

- model/internal/cmd/pdatagen/internal/base_fields.go
`manualSetter` field of `primitiveTypedField` struct is not being used anymore and can be removed along with its template.
> [pdatagen] Remove unused primitiveTypedField.manualSetter field

- CHANGELOG.md
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
This change adds a fallback handler to handle responses to invalid requests for logs, metrics and traces.
Given the following requests, the following responses are returned:
```
POST http://localhost:4318/v1/(logs|metrics|traces)
Content-Type: 
HTTP/1.1 415 Unsupported Media Type
Content-Type: text/plain
Date: Thu, 27 Jan 2022 03:44:19 GMT
Content-Length: 57
Content-Type: text/plain; charset=utf-8
Connection: close
415 unsupported media type, supported: [application/json]
```
```
PATCH http://localhost:4318/v1/(logs|metrics|traces)
Content-Type: application/json
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain
Date: Thu, 27 Jan 2022 04:13:01 GMT
Content-Length: 46
Content-Type: text/plain; charset=utf-8
Connection: close
405 method not allowed, supported: [GET, …
```
> Handle unsupported requests

- model/internal/cmd/pdatagen/internal/base_fields.go
The env var `structOriginFullName` is not used in `accessorsMessageValueTemplate`, removing the redundant switch case.
> [pdatagen] Remove redundant switch case in messageValueField.generateAccessors

- config/confighttp/README.md
Update confighttp readme to reflect correct placement of the cors and endpoint configuration
The example provided in confighttp resulted in configuration errors. The example has now been updated to reflect the documentation provided at [otlpreceiver / confighttp / HTTPServerSettings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/config.md#confighttp-HTTPServerSettings)
> Update confighttp readme

- .github/workflows/builder-integration-test.yaml
- cmd/builder/test/core.builder.yaml
- cmd/builder/test/replaces.builder.yaml
This PR bumps the integration tests to use the latest released version of the collector when building a distribution. It also enables a daily build running the integration tests, as well as their manual execution.
> Update builder integration tests, enable daily/manual builds

- model/internal/cmd/pdatagen/internal/metrics_structs.go
Follow up nit from https://github.com/open-telemetry/opentelemetry-collector/pull/4784
> [pdatage] Update numeric value struct names

- CONTRIBUTING.md
As a result of the discussion involving #4672, we agreed during the SIG Collector meeting that we'd start recommending and enforcing breaking changes to be performed in two steps.
> Add guidelines for breaking changes

- model/internal/cmd/pdatagen/internal/base_fields.go
- model/internal/cmd/pdatagen/internal/metrics_structs.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
- model/pdata/metrics.go
- model/pdata/metrics_test.go
Define new pdatagen field `oneOfField` to represent `oneof` proto field. Migrate hardcoded Metric Data related functions and pdatagen numberField to use the new pdatagen field.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/4704
> [pdatagen] Generate oneOf field

- model/internal/cmd/pdatagen/internal/base_structs.go
- model/pdata/generated_common.go
- model/pdata/generated_log.go
- model/pdata/generated_metrics.go
- model/pdata/generated_resource.go
- model/pdata/generated_trace.go
The field is not being used anymore.
The build will be fixed once https://github.com/open-telemetry/opentelemetry-collector/pull/4791 is merged
> [pdatagen] Remove deprecated field from messageValueStruct

- model/internal/cmd/pdatagen/internal/base_fields.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
- model/pdata/metrics.go
- model/pdata/metrics_test.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/4782
> [pdatagen] Generate Metric type accessors

- internal/otlptext/logs.go
- internal/otlptext/traces.go
I believe same line from metrics is copied but text is not changed.
> Fix typo in OTLP text

- cmd/builder/internal/builder/config.go
- cmd/builder/test/core.builder.yaml
- cmd/builder/test/replaces.builder.yaml
**Description:** bump otel version to 0.44.0
This is to prevent:
```
2022-02-11T14:53:02.762+0100    INFO    builder/main.go:52      You're building a distribution with non-aligned version of the builder. Compilation may fail due to API changes. Please upgrade your builder or API     {"builder-version": "0.43.0"}
```
**Testing:** Ran `go test -count 1 ./...` in `./cmd/builder` dir
> builder: bump otelColVersion version to 0.44.0

- CHANGELOG.md
- internal/otlptext/databuffer.go
- model/internal/cmd/pdatagen/internal/base_fields.go
- model/internal/cmd/pdatagen/internal/metrics_structs.go
- model/pdata/generated_metrics.go
- model/pdata/generated_metrics_test.go
- model/pdata/metrics.go
- model/pdata/metrics_test.go
Add new `NumberDataPoint.ValueType()` and `Exemplar.ValueType()` instead. Do not use `accessorType` in the pdatagen, always rely on proto field type for consistency.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/4781
> [pdata] Rename `NumberDataPoint/Exemplar.Type` methods to `ValueType`

- CHANGELOG.md
- extension/zpagesextension/README.md
- service/internal/zpages/templates.go
- service/internal/zpages/templates/features_table.html
- service/internal/zpages/templates_test.go
- service/zpages.go
> [extension/zpages] Add feature gate summary page

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- docs/release.md
- go.mod
- versions.yaml
Contrib PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7937
Closes #4871
> Prepare v0.45.0

- CHANGELOG.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
If authenticator is configured it will deny CORS requests which do not carry auth. This change reorders auth and CORS middlewares so CORS takes precedence.
**Testing:**
There is a test which ensures that auth will be skipped for CORS requests.
> [confighttp] Allow CORS requests with configured auth

- config/configmap_test.go
Follow-up after https://github.com/open-telemetry/opentelemetry-collector/pull/4249, I was not able to finish that, and want to see if somebody else can continue. Added tests (which are always good to validate the current behavior), but left few TODOs about things to investigate.
> Add tests for expandNilStructPointersFunc, left TODO to investigate

- Makefile
- docs/release.md
This PR improves the release docs by:
- removing outdated steps or information
- replacing ambiguous terms by more explicit references. For instance, `origin` and `upstream` were replaced by the GitHub references (namespace/repo-name)
- adding a table at the end of the document with the release history for the past few releases and the future schedule
- reordering some steps, like the ones about determining the version number and checking the state of the main branches
> Improve release doc

- CHANGELOG.md
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
Fixes: https://github.com/open-telemetry/opentelemetry-collector/issues/4565
> Remove support for legacy otlp/http port

- CHANGELOG.md
- processor/memorylimiterprocessor/factory.go
- processor/memorylimiterprocessor/factory_test.go
- processor/memorylimiterprocessor/memorylimiter.go
- processor/memorylimiterprocessor/memorylimiter_test.go
Signed-off-by: Dani Louca <dlouca@splunk.com>
This change https://github.com/open-telemetry/opentelemetry-collector/commit/062e64f1d7466400cbc5b0bd727ec94175a0e0de caused the memory limiter to "only" start the `checkMemLimits` routine for the ml instance used by the traces processor . 
In other words, metrics and logs processor will NOT [drop/refuse](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/memorylimiter.go#L206) data and will pass them down to the next consumer regardless of the current memory pressure as their instance of ml->forcingDrop will not be set.
The simplest solution, is to call start for each processor (metrics, logs, traces) , but this will not be efficient as we'll be running 3 instances of …
> [processor/memorylimiter] Only drops traces, not logs or metrics

- docs/release.md
> Assign release managers to future releases

- CONTRIBUTING.md
Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/4903#issuecomment-1049671154.
Moves 'Exceptions' subsection to its own section and rewords to apply more generally to all rules and procedures that may be set in this repository.
The intent is to formalize how to deal with exceptions to existing rules.
The specific motivation was to address how should we determine exceptions to the Go version support policy if e.g. a new version has a feature that is deemed particularly useful or necessary, but it can apply to any other rule we come up with.
> Reword exceptions section to be more general

- CHANGELOG.md
- model/internal/pdata/common.go
- model/internal/pdata/common_test.go
- model/internal/pdata/metrics_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4756 by adding RemoveIf for AttributeMap.  The implementation (and TODO) are based on the RemoveIf for AttributeValueSlice: https://github.com/open-telemetry/opentelemetry-collector/blob/model/v0.43.1/model/pdata/generated_common.go#L181
**Testing:**
Unit tests added.
Benchmark added to compare performance of Remove to RemoveIf when deleting a large number of elements.
```
$ go test -bench=.
goos: linux
goarch: amd64
pkg: go.opentelemetry.io/collector/model/pdata
cpu: Intel(R) Xeon(R) CPU @ 2.20GHz
...
BenchmarkAttributeMap_Remove-16                                  	   94230	     12897 ns/op
BenchmarkAttributeMap_RemoveIf-16                                	  374329	      3345 ns/op
...
```
> Add RemoveIf to attribute map, and rename Delete to Remove

- CHANGELOG.md
- service/internal/builder/pipelines_builder.go
> Add `pipeline` key with pipeline identifier to processor loggers

- CHANGELOG.md
- model/internal/otlp_wrapper.go
- model/internal/pdata/logs.go
- model/internal/pdata/logs_test.go
- model/internal/pdata/metrics.go
- model/internal/pdata/metrics_test.go
- model/internal/pdata/otlp_wrapper.go
- model/internal/pdata/traces.go
- model/internal/pdata/traces_test.go
- model/otlp/json_marshaler.go
- model/otlp/json_unmarshaler.go
- model/otlp/pb_marshaler.go
- model/otlp/pb_unmarshaler.go
- model/otlpgrpc/logs.go
- model/otlpgrpc/metrics.go
- model/otlpgrpc/traces.go
- model/pdata/logs_alias.go
- model/pdata/metrics_alias.go
- model/pdata/traces_alias.go
This PR tries to respect the rules 100%, but the need to keep the deprecated public funcs is unclear since they should not/ cannot be used externally.
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/4706
Issue will be fixed when removing the deprecated funcs.
> pdata: deprecate funcs working with InternalRep

- CHANGELOG.md
- model/internal/cmd/pdatagen/internal/resource_structs.go
- model/internal/pdata/generated_resource.go
- model/internal/pdata/generated_resource_test.go
**Description:** Added missing droppedAttributesCount
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/4788
**Testing:** No new tests where added, few test were autogenerated.
**Documentation:** No new documentation were added
> add droppedAttributesCount to resource_struct

- CHANGELOG.md
- config/configauth/default_clientauthenticator.go
- config/configauth/default_clientauthenticator_test.go
Similar to #4558, this allows client authenticators to be created without having to implement all the functions from the ClientAuthenticator interface.
This is non-breaking change.
Fixes #4557
> Implement default client authenticators

- CHANGELOG.md
- service/collector.go
- service/collector_test.go
Fixes: #4826
If the `Run` exited due to an error during startup the state would stay as `Starting` changed this to be set to `Closed` when any startup error occurs.
There might need to be a larger discussion on if `Closed` is the correct state or if we should introduce a `Failed` or `Error` state that would be more appropriate here.?
**Link to tracking Issue:** #4826
**Testing:** Added unit tests to valid state change
> State set to closing when Collector Run encounters startup failure

- CHANGELOG.md
Move all the deprecation entries from "Breaking Changes" to its own section as discussed https://github.com/open-telemetry/opentelemetry-collector/pull/4978#discussion_r825459643
> [CHANGELOG] Move all deprecation entries to "Deprecations" section

- CHANGELOG.md
- config/configmapprovider/yaml.go
- config/configmapprovider/yaml_test.go
- service/config_provider.go
> Add a new yaml provider, allows providing yaml bytes

- docs/ga-roadmap.md
The GA Roadmap to be updated. Just removing the passed dates to avoid confusion for now.
> Remove passed dates from GA roadmap

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- go.mod
- go.sum
- versions.yaml
- Update CHANGELOG.md and versions.yaml
- Prepare collector-base for version v0.47.0 (made by running `make multimod-prerelease` and cherry-picking from `prerelease_collector-base_v0.47.0` branch)
- Update Collector version in cmd/builder/internal/builder/config.go
- Update Collector version on cmd/otelcorecol/builder-config.yaml
- Update Collector version on cmd/otelcorecol files (not listed on release playbook)
**Link to tracking Issue:** Closes #5007
**Testing:** Verified in open-telemetry/opentelemetry-collector-contrib#8494
> Prepare v0.47.0 release

- .github/workflows/build-and-test.yml
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5032.
In order to merge this PR, an admin for the repo will need to change the branch protection rules for `main` to require the `build-and-test / unittest (1.18)` and `build-and-test / unittest (1.17)`  checks instead of the `unittest` check.
I don't think this needs a changelog entry.
> Run unit tests on go 1.18 in addition to 1.17

- README.md
- docs/release.md
> Add definition for release manager

- CHANGELOG.md
- model/internal/cmd/pdatagen/internal/base_fields.go
- model/internal/cmd/pdatagen/internal/log_structs.go
- model/internal/pdata/generated_log.go
> Deprecate LogRecord.Name(), it was deprecated in the data model

- CHANGELOG.md
- cmd/builder/internal/builder/templates/main_windows.go.tmpl
- cmd/otelcorecol/main_windows.go
- service/collector_windows.go
- service/collector_windows_test.go
Currently the WindowsService type in the service package is unnecessary public, and always used as a svc.Handler.
Avoid exposing this public type by returning an `svc.Handler` instead.
> Deprecate NewWindowsService, add NewSvcHandler

- CHANGELOG.md
- service/collector_windows.go
- service/command.go
- service/featuregate/flags.go
- service/flags.go
Distributions that build without the builder will need to declare it as they do for "config" and "set".
> Deprecate global flag in featuregates

- config/mapprovider.go
- config/mapprovider/envmapprovider/mapprovider.go
- config/mapprovider/filemapprovider/mapprovider.go
- config/mapprovider/yamlmapprovider/mapprovider.go
The parameter `location` used in the [`Retrieve`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configmapprovider/provider.go#L57) function of the `Provider` interface does not clearly define what it is.
This PR changes it to `uri` as it more clearly defines its value, which is a [data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme).
Closes #5002.
Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>
> Change parameter 'location' to a more relevant name

- model/otlpgrpc/logs_test.go
- model/otlpgrpc/metrics_test.go
- model/otlpgrpc/traces_test.go
This happened because the upgrade to otlp 0.15.0 is not fully implemented to deal with backwards compatibility.
> Fix JSON serialization tests

- docs/troubleshooting.md
Adjusted the highlighting on a few code blocks in the documentation. Some were identified as JSON and were difficult to read on GitHub. 
Blocks for log output are now highlighted as plain, preformatted text. Blocks showing terminal prompts are now identified as shell sessions, though their appearance did not change.
> Highlight documentation code blocks accurately

- CHANGELOG.md
- model/semconv/v1.5.0/schema.go
- model/semconv/v1.6.1/schema.go
This change fixes the sem conv SchemaURL values, as reported in https://github.com/open-telemetry/opentelemetry-collector/pull/5090#discussion_r835926493
> Fix Semantic Convention Schema URL definition for 1.5.0 and 1.6.1

- CHANGELOG.md
- model/semconv/v1.7.0/nonstandard.go
- model/semconv/v1.7.0/schema.go
- model/semconv/v1.8.0/nonstandard.go
- model/semconv/v1.8.0/schema.go
Some files that are supposed to be created manually were missed in semconv v1.7.0 and v1.8.0
> [model/semconv] Add missing files for semconv v1.7.0 and v1.8.0

- model/semconv/semconv_test.go
This tests validates that all files needed for the new model/semconv release are created .
> Add a test to validate presence of all semconv files

- internal/tools/go.mod
- internal/tools/go.sum
> Fix checksum mismatch in github.com/blizzy78/varnamelen

- model/internal/cmd/pdatagen/internal/base_fields.go
- model/internal/pdata/generated_metrics.go
- model/internal/pdata/metrics_test.go
A bug was caught in the prometheus tests in the contrib repository where a histogram datapoint that contained a nil sum was copied into a new datapoint, resulting in the sum being initialized to 0.
Added a test to validate the issue is fixed. I will add another issue to add this test to the generated tests for future use.
> fix bug with nil Sum

- CHANGELOG.md
I also fixed some PR numbers in existing entries.
Contributes to https://github.com/open-telemetry/opentelemetry-collector/issues/5120
> Update CHANGELOG for 0.48.0 release

- CHANGELOG.md
- model/otlpgrpc/logs.go
- model/otlpgrpc/logs_test.go
- model/otlpgrpc/metrics.go
- model/otlpgrpc/metrics_test.go
- model/otlpgrpc/traces.go
- model/otlpgrpc/traces_test.go
Because, most likely for the moment only otlp exporter/receiver is using this package, we can remove this after just one version, no third-party deps.
> Remove deprecated funcs from otlpgrpc

- CHANGELOG.md
- service/collector.go
- service/telemetry.go
This PR also removes the set of the global MeterProvider, similarly with #5138.
> Setup the correct meter provider if telemetry.useOtelForInternalMetrics featuregate enabled

- .github/workflows/build-and-test.yml
Add support to CI to build collector for architectures: Linux 386 and ARM64, and Windows 386. The binaries for these architectures are released  in [collector releases](https://github.com/open-telemetry/opentelemetry-collector-releases/releases). This GitHub Actions job will help to see if any issues are introduced to cross binary builds when a commit is pushed.
Fix #5031 
Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>
> [ci] Cross build for  architectures

- CHANGELOG.md
- model/internal/pdata/common.go
- model/internal/pdata/common_test.go
`return` statements were missed in the Value.asRaw function for Slice and Map elements.
> [pdata] Fix Value.asRaw to correctly return Slice and Map elements

- CHANGELOG.md
- model/internal/pdata/common.go
This change also improves `Slice.asRaw()` method. Now it returns raw presentation of Slice and Map elements instead of `"<invalid array value>"` string.
> [pdata] Use Value.asRaw in Map.AsRaw and Slice.asRaw methods

- CHANGELOG.md
- model/internal/otlp/logs.go
- model/internal/otlp/metrics.go
- model/internal/otlp/traces.go
- model/otlp/json_unmarshaler.go
- model/otlpgrpc/logs.go
- model/otlpgrpc/logs_test.go
- model/otlpgrpc/metrics.go
- model/otlpgrpc/metrics_test.go
- model/otlpgrpc/traces.go
- model/otlpgrpc/traces_test.go
The functions were added in the the latest release. They are intended for the internal use only and shouldn't be exported.
This change is applied without backward compatibility because the functions accept an argument of internal type and cannot be used outside of `collector/model`. If we keep backward compatibility here, we would also have to export these functions additionally in the new structure defined in https://github.com/open-telemetry/opentelemetry-collector/pull/5087.
Closes: https://github.com/open-telemetry/opentelemetry-collector/issues/5163
> Make InstrumentationLibrary<signal>ToScope functions unexported

- CHANGELOG.md
- internal/otlptext/logs.go
LogRecord.Name has been deprecated, but there is still a reference to it in the logging exporter. This change removes the name from the logging exporter output.
> Remove deprecated log name from text marshaler

- CHANGELOG.md
- service/collector_test.go
- service/collector_windows.go
- service/command.go
- service/config_provider.go
- service/config_provider_test.go
This is a fork of https://github.com/open-telemetry/opentelemetry-collector/pull/4762
Also, deprecates `service.MustNewConfigProvider` and `service.MustNewDefaultConfigProvider`in favor of `service.NewConfigProvider`.
> Add a NewConfigProvider that uses options for settings, and does input validation

- .github/workflows/check-links.yaml
Reverted github-action-markdown-link-check action in the check-links workflow to version 1.0.13 due to [issues with version 1.0.14 ](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/127)
Fixes #5118 
**Testing:**
Reverted version, updated release.md in a test branch, and triggered the action.  [Passing results here.](https://github.com/TylerHelmuth/opentelemetry-collector/runs/5979608772?check_suite_focus=true)
> reverted link check action to 1.0.13

- pdata/internal/logs.go
- pdata/internal/metrics.go
- pdata/internal/traces.go
- pdata/plog/alias.go
- pdata/plog/encoding.go
- pdata/pmetric/alias.go
- pdata/pmetric/encoding.go
- pdata/ptrace/alias.go
- pdata/ptrace/encoding.go
> Remove unnecessary aliases for Marshaler/Unmarshaler/Sizer in pdata

- CHANGELOG.md
- pdata/plog/plogotlp/logs.go
- pdata/plog/plogotlp/logs_test.go
- pdata/pmetric/pmetricotlp/metrics.go
- pdata/pmetric/pmetricotlp/metrics_test.go
- pdata/ptrace/ptraceotlp/traces.go
- pdata/ptrace/ptraceotlp/traces_test.go
The codepath through the OTLP receiver for gRPC was not translating the `InstrumentationLibrary*` to `Scope*`.
Fixes #5188
> [receiver/otlp] fix otlp <0.15.0 receiver bug

- .github/workflows/check-links.yaml
- CONTRIBUTING.md
See https://github.com/open-telemetry/opentelemetry-collector/runs/5999091156?check_suite_focus=true
> Fix check links errors, use latest version of the tool

- .golangci.yml
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/otlpexporter/otlp_test.go
- internal/obsreportconfig/obsreportconfig.go
- processor/memorylimiterprocessor/memorylimiter.go
- processor/memorylimiterprocessor/memorylimiter_test.go
- service/collector.go
- Add depguard to enforce usage of `go.uber.org/atomic`
- Use `go.uber.org/atomic` everywhere (WIP, still need to fix some tests)
**Link to tracking Issue:** Fixes #5200
> Use `go.uber.org/atomic` everywhere

- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- processor/memorylimiterprocessor/memorylimiter.go
- processor/memorylimiterprocessor/memorylimiter_test.go
> Use atomic.Bool when int was used as a bool variable

- component/receiver.go
The documentation used `======` incorrectly to mark headings. According to godocs:
> A title is a line that is separated from its following line by an empty line, begins with a capital letter and doesn't end with punctuation.
> [docs] fix headings in godoc

- pdata/internal/cmd/pdatagen/internal/base_slices.go
- pdata/internal/cmd/pdatagen/internal/base_structs.go
- pdata/internal/cmd/pdatagen/internal/files.go
- pdata/internal/cmd/pdatagen/main.go
- pdata/internal/common.go
- pdata/internal/logs.go
- pdata/internal/metrics.go
- pdata/internal/spanid.go
- pdata/internal/traceid.go
- pdata/internal/traces.go
- pdata/pcommon/alias.go
- pdata/pcommon/generated_common_alias.go
- pdata/pcommon/generated_resource_alias.go
- pdata/pcommon/spanid_alias.go
- pdata/pcommon/timestamp_alias.go
- pdata/pcommon/traceid_alias.go
- pdata/plog/alias.go
- pdata/plog/generated_alias.go
- pdata/pmetric/alias.go
- pdata/pmetric/generated_alias.go
- pdata/ptrace/alias.go
- pdata/ptrace/generated_alias.go
- Use copy of the godoc comments from pdata/internal instead of mentioning aliases in pdata/p<signal> public API docs.
- Update godoc strings in both pdata/p<signal> and pdata/internal to keep them consistent.
> Update pdata godoc strings

- config/mapconverter/expandmapconverter/expand_test.go
This was possible after the split of individual providers in their own package.
> Remove duplicate code between configtest and expand_test

- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/testdata/config.yaml
Add two test cases for edge cases in writing the OTLP receiver YAML:
- A protocol key is explicitly set as `null`.
- A protocol key is explicitly set to an empty object, `{}`.
In both cases the protocol will be enabled.
These test cases would usually not be set by end-users but they can happen if there is some processing of YAML (e.g. by something like Helm). I think it's important to have them here to avoid regressions if we ever change the underlying code for configuration loading
> [receiver/otlp] Add tests for YAML edge cases

- CHANGELOG.md
- exporter/otlpexporter/otlp.go
- exporter/otlphttpexporter/otlp.go
- pdata/plog/plogotlp/logs.go
- pdata/plog/plogotlp/logs_test.go
- pdata/pmetric/pmetricotlp/metrics.go
- pdata/pmetric/pmetricotlp/metrics_test.go
- pdata/ptrace/ptraceotlp/traces.go
- pdata/ptrace/ptraceotlp/traces_test.go
- receiver/otlpreceiver/internal/logs/otlp_test.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
- receiver/otlpreceiver/internal/trace/otlp_test.go
- receiver/otlpreceiver/otlp_test.go
- `plogotlp.Request.SetLogs` func is deprecated in favor of `plogotlp.NewRequestFromLogs`
- `pmetricotlp.Request.SetMetrics` func is deprecated in favor of `pmetricotlp.NewRequestFromMetrics`
- `ptraceotlp.Request.SetTraces` func is deprecated in favor of `ptraceotlp.NewRequestFromTraces`
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/5230
> [pdata] Replace `Request.Set<Signals>` with NewRequestFrom<Signals>

- CHANGELOG.md
- internal/otlptext/databuffer.go
- model/pdata/metrics_alias.go
- pdata/internal/cmd/pdatagen/internal/metrics_structs.go
- pdata/internal/generated_pmetric.go
- pdata/internal/generated_pmetric_test.go
- pdata/internal/metrics.go
- pdata/internal/metrics_test.go
- pdata/pmetric/alias.go
Split `pmetric.MetricValueType` into `NumberDataPointValueType` and `ExemplarValueType`
1. `pmetric.NumberDataPoint.ValueType()` now returns a `NumberDataPointValueType` that can be `NumberDataPointValueTypeInt` or `NumberDataPointValueTypeDouble`.
2. `pmetric.Exemplar.ValueType()` now returns a `ExemplarValueType` that can be `ExemplarValueInt` or `ExemplarValueDouble`.
(1) use case is most commonly being used. Thats why we keep backward compatibility for it. We don't keep backward compatibility for (2) it to avoid mixing the split types.
Closes: https://github.com/open-telemetry/opentelemetry-collector/issues/4819
Replaces https://github.com/open-telemetry/opentelemetry-collector/pull/5227
> [pdata] Split `pmetric.MetricValueType` into more specific types

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/base_fields.go
- pdata/internal/cmd/pdatagen/internal/log_structs.go
- pdata/internal/generated_plog.go
The field is going to be removed but the setter is still not deprecated
> Deprecate `plog.LogRecord.SetName()` function

- service/config_provider.go
- service/config_provider_test.go
Deprecated `ConfigProviderSettings.Unmarshaler` is still being used in `service.NewConfigProvider` causing nil pointer exception it's not provided.
> Fix nil pointer exception in service.NewConfigProvider

- config/configgrpc/configgrpc.go
- config/confighttp/confighttp.go
- processor/batchprocessor/config.go
`omitempty` has effect only if the config is used as a source to encode/decode from, but the config is always the destination in our case, so it has no effect.
> Remove usage of unnecessary omitempty

- CHANGELOG.md
- service/collector.go
Resolves #5242
Reduced the logging level when the collector exits due to a context cancel. When the collector is exited with a canceled context it would print an error with a stack trace. This lead to confusing logs when the collector correctly shut down due to a context that was closed by signal intercepts.
~~Kept the context error log if the error is `context.DeadlineExceeded` as it's much more likely if the collector exceeded some deadline the user should be notified of such.~~
**Link to tracking Issue:** #5242 
**Testing:** Tested locally with signal intercepts. Current unit tests are valid.
> Reduced logging level for collector shutdown due to context cancel

- exporter/exporterhelper/README.md
The `resource_to_telemetry_conversion` setting was listed in the readme, but it doesn't correspond to a setting for this exporter. It looks like individual exporters in the contrib repo have it.
The readme also had a dangling link for more settings. I've removed the link altogether since, as far as I can tell, there are no longer any settings not listed in the readme. Please kindly verify that this is true.
> cleanup exporterhelper readme

- service/collector.go
- service/settings.go
Calling SetLoggerV2 isn't thread safe and should only be called `before any grpc functions`. See more details: https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/settable#pkg-overview
This hacky workaround checks if the collector's logger has been set, if so, don't bother updating the grpc logger. Looking for alternative implementations here.
> [bugfix] temporary fix around grpclogger

- service/collector_test.go
- service/host.go
- service/service.go
- service/service_test.go
- service/telemetry.go
- service/zpages.go
Moves `service` functionality related to `component.Host` and `zpages` into a new `serviceHost` struct. This is an internal refactor only, with the goal of more easily visualizing what it would take to eventually expose the `service` struct.
**Link to tracking Issue:** I opened this because of the discussion in #5149. I want to do internal refactors to move towards eventually exposing `service`. Even if we don't end up going in that route, I think this is an improvement of the code and should be merged regardless.
**Testing:** Amended unit tests
**Documentation:** n/a, internal refactor only
> [service] Split `component.Host` functionality into separate `serviceHost` struct

- CONTRIBUTING.md
Signed-off-by: Kevin Earls <kearls@redhat.com>
This PR fixes #5314 by correcting CONTRIBUTING.md to use the correct CI platform and build targets.
**Link to tracking Issue:** #5314
> Update CONTRIBUTING.md to reference the correct CI platform

- README.md
The circleci badge is no longer relevant, removing it. Updating the github action badge icon as well and adding go report card badge.
> [docs] clean up badges

- cmd/otelcorecol/go.mod
- cmd/otelcorecol/go.sum
- go.mod
- go.sum
Bump github.com/klauspost/compress from 1.15.1 to 1.15.3
Bump github.com/shirou/gopsutil/v3 from 3.22.3 to 3.22.4
> [chore] bump dependencies

- .github/workflows/build-and-test.yml
go mod cache already got invalidated when tools changed
> Merge cache for go mod and tools.

- .github/workflows/build-and-test-windows.yaml
See https://github.com/actions/cache/blob/main/examples.md#go---modules
> Fix windows go cache path, per GA examples

- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/contrib-tests.yml
> setup-go github action does all the env setup

- CHANGELOG.md
- pdata/plog/plogotlp/logs.go
- pdata/pmetric/alias.go
- pdata/pmetric/pmetricotlp/metrics.go
- pdata/ptrace/ptraceotlp/traces.go
> Remove deprecated pdata funcs/structs from v0.50.0

- config/configtelemetry/configtelemetry.go
- config/configtelemetry/configtelemetry_test.go
> configtelemetry: remove unnecessary private func, add unittests for public funcs

- CHANGELOG.md
- service/featuregate/gates.go
> Remove derecated featuregate funcs/structs from v0.50.0

- docs/processing.md
This PR continues to mature the processing.md doc. 
- Updates the metric's virtual field to be in alignment with recent discussions/PRs.  
- Introduces the start of expected function syntax.
> [Telemetry Query Language] Iterate on processing doc

- .github/workflows/api-compatibility.yml
- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
This change does not affect the collector consumed as a library, or other third party distributions unless they are using the builder.
> Update CI targets to use go 1.18 when possible

- README.md
This moves the stability level documentation from the contrib repo to the core repo.
> [docs] add stability documentation

- exporter/otlpexporter/README.md
Adds the status header for the OTLP exporter.
> [docs] add status information for OTLP exporter

- CHANGELOG.md
- component/component.go
- component/componenterror/errors.go
- component/componenttest/shutdown_verifier.go
- component/exporter.go
- component/processor.go
- component/receiver.go
- processor/processorhelper/logs.go
- processor/processorhelper/logs_test.go
- processor/processorhelper/metrics.go
- processor/processorhelper/metrics_test.go
- processor/processorhelper/traces.go
- processor/processorhelper/traces_test.go
- receiver/otlpreceiver/otlp.go
- receiver/scraperhelper/scrapercontroller.go
- receiver/scraperhelper/scrapercontroller_test.go
- service/internal/builder/exporters_builder.go
- service/internal/builder/receivers_builder.go
> Deprecate componenterror package, move to component

- processor/memorylimiterprocessor/README.md
> [docs] add status for memorylimiter

- config/README.md
> Update config/README.md with more details about configURI

- CHANGELOG.md
- pdata/internal/common.go
- pdata/internal/common_test.go
- pdata/pcommon/alias.go
Deprecate `pcommon.Value.NewValueBytes` in favor of `Value.NewValueMBytes` in preparation of migration to the new immutable slices.
This constructor was missed in https://github.com/open-telemetry/opentelemetry-collector/pull/5344. We will still stick to the schedule defined in https://github.com/open-telemetry/opentelemetry-collector/issues/5263. The deprecated function will be just replaced without removal in 0.53.0.
> [pdata] Rename `Value.NewValueBytes ` to `Value.NewValueBytes`

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/metrics_structs.go
- pdata/internal/generated_pmetric.go
- pdata/internal/generated_pmetric_test.go
> [otlp] add optional min/max fields to histograms

- docs/processing.md
Updates function names/parameters in doc to match function naming standards.
> [Telemetry Query Language] Updating doc to match naming standards

- CHANGELOG.md
- config/README.md
- config/configmap.go
- config/mapconverter.go
- config/mapconverter/expandmapconverter/expand.go
- config/mapconverter/expandmapconverter/expand_test.go
- config/mapconverter/overwritepropertiesmapconverter/properties.go
- config/mapconverter/overwritepropertiesmapconverter/properties_test.go
- service/collector_test.go
- service/collector_windows.go
- service/command.go
- service/config_provider.go
- service/mapresolver.go
- service/mapresolver_test.go
The main reason to do this, is because if in the future we want to extend the capabilities of the "MapConverter" we don't have any way to do that. By using an interface we can define "optional" interfaces that some converters may implement to enable future improvements.
> BreakingChange: Change to use interface instead of func for MapConverter

- .github/workflows/build-and-test-windows.yaml
- Makefile
- Makefile.Common
- cmd/builder/internal/builder/config_test.go
- cmd/builder/internal/builder/main_test.go
Enable running unit test on Windows for all modules and fix those that are failing except for one issue reported separately:
https://github.com/open-telemetry/opentelemetry-collector/issues/5403
> Run Windows unit tests for all modules and fix them
