service/collector_test.go

Small nit in collector tests, same config already available in testdata

---

config/configmap_test.go
config/configmapprovider/default_test.go
config/configtest/configtest_test.go
config/configtls/configtls_test.go
exporter/otlpexporter/factory_test.go
exporter/otlpexporter/otlp_test.go
exporter/otlphttpexporter/factory_test.go
service/collector_test.go
service/collector_windows_test.go
service/internal/builder/pipelines_builder_test.go
service/internal/builder/receivers_builder_test.go

Use path join instead on unix style paths in tests for testdata files

---

.github/workflows/changelog.yml

Use action/checkout fetch-depth instead of manually fetch

---

CHANGELOG.md
CONTRIBUTING.md

In order to help making sub packages across the repo more consistent,
the contribution guide is being updated to reflect that.
Looking to expand contributions to make consistent approaches to working on the collector and the contrib.
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6209

An initial draft of updating recomendations

---

service/collector.go
service/internal/telemetrylogs/logger.go
service/internal/telemetrylogs/logger_test.go

Remove unnecessary interface, simplify grpc logger

---

service/collector.go
service/config_watcher.go
service/config_watcher_test.go
service/service.go

Small nits in service package

---

CHANGELOG.md
config/configmapprovider/expand.go
config/configmapprovider/expand_test.go
config/configmapprovider/mock_test.go

Fix expand map provider to call close on the base provider.

---

config/configmapprovider/merge_test.go

Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/4571

Remove error test map provider from merge tests, use the mock

---

config/configmapprovider/env.go
config/configmapprovider/env_test.go
config/configmapprovider/testdata/invalid-yaml.yaml

Add env config map provider, read from environment variable

---

config/configmapprovider/merge.go

Remove resolved TODO from the merge config map provider

---

Makefile
internal/buildscripts/builder-config.yaml

Fix local otelcol core build for testing

---

service/collector.go
service/config_provider.go
service/config_provider_test.go

Expose a new public interface service.ConfigProvider

---

service/collector_test.go
service/collector_windows.go
service/command.go
service/config_provider.go
service/config_provider_test.go
service/internal/configprovider/default.go
service/internal/configprovider/default_test.go
service/internal/configprovider/testdata/default-config.yaml

Add new default service config provider, remove map default provider

---

CHANGELOG.md
config/config_test.go
config/service.go

Add `custom` log encoding setting
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/4532

Add "custom" option for log encoding

---

service/internal/builder/receivers_builder.go

Avoid using config.ID() when possible, understand if can be removed

---

cmd/builder/internal/builder/templates/main_windows.go.tmpl
cmd/otelcorecol/main_windows.go

Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/4593

[Builder]: Small code structure nits in main_windows

---

config/confighttp/confighttp_test.go

Improves test coverage - Adds a test over the default HTTP interceptor to cover when server authentication fails.
**Link to tracking Issue:** [4555](https://github.com/open-telemetry/opentelemetry-collector/issues/4555)

Add test coverage over failing authentication in default HTTP interceptor

---

config/configmapprovider/retrieved_test.go

Remove unnecessary import comment from test file

---

CHANGELOG.md
config/configmap.go
config/configmapprovider/properties.go
config/configmapprovider/properties_test.go
service/config_provider.go
service/config_provider_test.go
service/internal/configprovider/expand.go
service/internal/configprovider/expand_test.go

Add context to config.MapConverterFunc

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go

[Builder] Remove deprecated config option module::core

---

processor/memorylimiterprocessor/config.go
processor/memorylimiterprocessor/memorylimiter.go

Fix error message in memorylimiter processor related to ballast extension

---

component/componenthelper/component.go

Add default implementation to the Start/Stop funcs instead of the users of them

---

CHANGELOG.md

Remove duplicate enhancements entry in unreleased

---

README.md

**Description:** Adding documentation for the configuration on the README.md
**Link to tracking Issue:** #4611

Otel-4611 Adding configuration docs in README.md

---

config/config.go
config/service.go

nit: remove internal empty funcs

---

config/configmapprovider/provider.go

add scheme length requirement in the documentation

---

CHANGELOG.md

Cleaning up the changelog with formatting fixes.

formatting fixes

---

CHANGELOG.md
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
go.mod
versions.yaml

This release includes a fix for a regression in the 0.43.0 release.

prepare v0.43.1 release

---

service/config_provider.go

Fix small typo in service.NewConfigProvider comments

---

CONTRIBUTING.md

Had added an incomplete example to this and removing it from the contribution guide.

Remove incomplete example used here

---

CHANGELOG.md

Add changelog entry for 4734, fix section for 4735

---

config/configmap_test.go
config/configmapprovider/env_test.go
config/configmapprovider/expand_test.go
config/configmapprovider/file.go
config/configtls/configtls_test.go
config/internal/configsource/manager_test.go
exporter/otlpexporter/factory_test.go
exporter/otlpexporter/otlp_test.go
exporter/otlphttpexporter/factory_test.go
internal/cgroups/cgroups.go
service/collector_test.go
service/collector_windows_test.go
service/config_provider_test.go
service/internal/builder/exporters_builder_test.go
service/internal/builder/pipelines_builder_test.go
service/internal/builder/receivers_builder_test.go
service/servicetest/configprovider_test.go

Replace usage of path.Join with filepath.Join, better windows support

---

model/internal/cmd/pdatagen/internal/metrics_structs.go
model/pdata/generated_metrics.go

Remove mentions of "double" from numeric value structs

[pdata] Update Metric Sum and Gauge structs comments

---

docs/roadmap.md

Make some roadmap items as done. Maybe this roadmap doc needs a deeper revamp?

Mark some roadmap items as done

---

model/internal/cmd/pdatagen/internal/metrics_structs.go

https://github.com/open-telemetry/opentelemetry-collector/pull/4773 wasn't rebased before merge. It broke the build

Fix build broken due to merge conflict

---

.github/workflows/changelog.yml

**Description:** What is stated in the title
**Link to tracking Issue:** #4603

don't run changelog check if pr comes from dependabot

---

component/componenttest/nop_component.go
component/componenttest/nop_exporter.go
component/componenttest/nop_extension.go
component/componenttest/nop_processor.go
component/componenttest/nop_receiver.go

Small improvements in componenttest

---

CHANGELOG.md
service/defaultcomponents/defaults.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/3927

Deprecate service/defaultcomponents go package

---

CHANGELOG.md
config/configtelemetry/configtelemetry.go
config/configtelemetry/configtelemetry_test.go

Remove deprecated funcs in configtelemetry

---

model/pdata/metrics_test.go

Adding a test to ensure OTLP translation worked as expected for Exponential Histograms. This type was not covered previously.

adding missing expo histo test

---

CHANGELOG.md

Add changelog after PR 4799

---

docs/monitoring.md

**Link to tracking Issue:** Fixes #4815

Remove reference to 'new-metrics' flag in docs

---

CONTRIBUTING.md
config/configmapprovider/provider.go
config/configmapprovider/retrieved.go
model/pdata/logs.go
service/config_provider.go
service/defaultcomponents/defaults.go

And update existing deprecation notices appropriately.

Update Contributing guideline to include version in deprecation notice

---

README.md

Mark more parts as stable

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
go.mod
go.sum

Bump github.com/shirou/gopsutil/v3 from 3.21.12 to 3.22.1

---

internal/testdata/log.go
internal/testdata/metric.go
internal/testdata/trace.go

Remove unused code from internal/testdata

---

.github/workflows/build-and-test.yml

nit: fix small comment inconsistency in genotelcorecol check

---

README.md

Update status to be reported by GA not by circle CI

---

internal/testutil/testutil.go
internal/testutil/testutil_test.go

Fix small nits in testutil, handle errors, initialize slices

---

CHANGELOG.md
component/componenttest/nop_extension.go
component/extension.go
config/configunmarshaler/defaultunmarshaler.go
extension/ballastextension/factory.go
extension/extensionhelper/factory.go
extension/zpagesextension/factory.go
internal/testcomponents/example_extension.go
service/command_test.go
service/internal/extensions/extensions_test.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/4681

Move everything from extensionhelper to component.

---

cmd/otelcorecol/go.sum
go.mod
go.sum

make gotidy

---

.github/workflows/build-and-test.yml
Makefile
Makefile.Common

Separate goporto in a step that checks for changes, since the command change the code.

Create a new github job, extract all non lint checks

---

component/factories_test.go

Add tests for component.Factories constructor helpers

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
go.mod
go.sum

Upgrade to github.com/klauspost/compress v1.14.4

---

README.md

Document Go language version support policy. Should have 'Skip Changelog'.
**Link to tracking Issue:** Fixes #4841

[README] Add section about Go compatibility

---

CHANGELOG.md
model/pdata/logs.go

Remove deprecated funcs in pdata

---

component/componenthelper/component.go
extension/extensionhelper/factory.go

Fix deprecation notice version for extensionheleper and componenhelper

---

README.md

I am sorry if I missed anyone, feel free to ping this PR or open a new PR if you remember others.

Try to add all previous triagers/approvers/maintainers as emeritus

---

model/pdata/logs_test.go
model/pdata/metrics_test.go
model/pdata/traces_test.go

Fix small nits in pdata tests, add missing compatibility tests

---

model/pdata/logs.go
model/pdata/logs_test.go
model/pdata/metrics.go
model/pdata/metrics_test.go
model/pdata/traces.go
model/pdata/traces_test.go

Add MoveTo all the top pdata structs, consistency with other generated structs

---

service/collector.go
service/collector_test.go

Nicer log messages if state is logged.

Implement Stringer for service.State

---

service/collector.go
service/collector_test.go

* Change state to be a int32 and use atomic ops accordingly.
* Change test that should expect certain state to check for that instead of using Eventually.

Small improvements in collector tests, and atomic usage

---

model/pdata/traceid_alias.go

nit: fix small comment in pdata

---

service/featuregate/flags_test.go

[service/featuregate] Add test for multiple namespaced gates with `+` in flags

---

.github/ISSUE_TEMPLATE/release.md

This new template can be used when creating a new release.
Fixes #4883

[release process] add release template

---

component/componenttest/nop_exporter.go
component/componenttest/nop_extension.go
component/componenttest/nop_host.go
component/componenttest/nop_processor.go
component/componenttest/nop_receiver.go
service/service_test.go

Fixing a bug: Refactor some new factory func under component/componenttest.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4906

Refactor some new factory func under component/componenttest

---

config/configmapprovider/properties.go

Fix nit in convertor commnent

---

docs/troubleshooting.md

Update troubleshooting to use correct command line option to change metrics address. This is the same PR as https://github.com/open-telemetry/opentelemetry-collector/pull/4923/files

[docs] Update troubleshooting arguments

---

model/pdata/common_alias.go

The collector version appeared to be outdated by the time https://github.com/open-telemetry/opentelemetry-collector/pull/4978 got merged
Submitted another PR from https://github.com/open-telemetry/opentelemetry-collector/pull/5021 to re-trigger CI

[pdata] Update deprecation comments

---

service/command.go

Fix comment for service.NewCommand

---

config/configmapprovider/provider.go

Fix small nit in configmap provider interface comment

---

docs/release.md

Followup after https://github.com/open-telemetry/opentelemetry-collector/pull/5015

Add release step to update examples/k8s/otel-config.yaml

---

model/otlpgrpc/logs.go
model/otlpgrpc/metrics.go
model/otlpgrpc/traces.go

Simplify UnmarshalJSON implementation

---

model/otlpgrpc/logs_test.go
model/otlpgrpc/metrics_test.go
model/otlpgrpc/traces_test.go

Add unittests for grpc otlp client/server

---

model/otlpgrpc/logs.go
model/otlpgrpc/metrics.go
model/otlpgrpc/traces.go

Simplify UnmarshalProto funcs in otlpgrpc

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
go.mod
go.sum
versions.yaml

Need to wait for https://github.com/open-telemetry/opentelemetry-collector/pull/5127 before merging this.
Contributes to https://github.com/open-telemetry/opentelemetry-collector/issues/5120

Prerelease collector base v0.48.0

---

cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml

Contributes to https://github.com/open-telemetry/opentelemetry-collector/issues/5120
Merge after https://github.com/open-telemetry/opentelemetry-collector/pull/5128

Update builder version number to 0.48.0

---

docs/release.md

Updated instructions and the schedule.

Update release.md after 0.48.0 release

---

config/configgrpc/configgrpc.go

This is a consistency PR, since the default propagators are always the global once. We can remove from other places or add everywhere.

Add otel propagators to the grpc client options

---

config/config.go

nit: fix some comments in config

---

.github/dependabot.yml
Makefile

The project does not have any docker file anymore https://github.com/open-telemetry/opentelemetry-collector/network/updates/333762109

Remove dependabot config to upgrade docker

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
config/configmap.go

Small nits in config.Map, avoid unnecessary deps

---

service/collector_test.go
service/collector_windows.go
service/command.go
service/config_provider.go
service/config_provider_test.go

Followup after #4936, remove some duplicate code

---

pdata/plog/plogotlp/logs.go
pdata/pmetric/pmetricotlp/metrics.go
pdata/ptrace/ptraceotlp/traces.go

Small nits in struct comments in otlp package

---

exporter/exporterhelper/internal/bounded_memory_queue.go

* Capacity is immutable, so access no longer atomic.
* The items channel is immutable, so no reason to use pointer.

Small nits in bounded memory, unnecessary atomics and pointers

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
model/go.mod
versions.yaml

Closes https://github.com/open-telemetry/opentelemetry-collector/issues/5205

Prepare 0.49.0 release

---

CHANGELOG.md

Fix small nit in CHANGELOG entry

---

config/mapprovider.go

Add version to the deprecated message

---

service/internal/extensions/extensions.go

Fix typo in extensions.go

---

service/collector_test.go

Refactor collector tests, improve names, localize functionality tests

---

internal/testutil/testutil.go
internal/testutil/testutil_test.go

Remove GetAvailablePort, change GetAvailableLocalAddress to handle windows reserved ports

---

exporter/exporterhelper/queued_retry.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5260

Try to clarify the suggestion in the export failures when retry_on_failure is disabled

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
model/go.mod
versions.yaml

fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5277

[chore] prepare v0.50.0 release

---

docs/release.md

Note i've swapped jpkrohling for the 0.52.0 release as he's out for a few months.

[docs] update to release documentation

---

service/mapresolver.go
service/mapresolver_test.go

Address feedback about existing code from 5248

---

config/configtls/README.md

As mentioned in the subject. README of configtls is missing `relaod_interval` configuration - added the option

Added missing documentation for "reload_interval" configuration in configtls module.

---

CHANGELOG.md
pdata/internal/common.go
pdata/internal/common_test.go

Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/5310

[pdata] Make Slice.AsRaw() method exported

---

.github/workflows/build-and-test.yml

Fix go cache path per Github Action example, fix build for different go versions

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
go.sum
versions.yaml

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5338

Prerelease collector v0.51.0

---

Makefile

Run make gotidy after multimod prerelease

---

Makefile
versions.yaml

Rename collector-base to collector-core in multimod versions

---

.golangci.yml
Makefile.Common

Enable unused linter, add allow-parrallel-runs as config

---

config/README.md

For @tigrannajaryan since he asked to have all the explanations from different config related PRs in one document for devs to understand, but I promise that I will not update this doc, since I know that will get outdated sooner or later.

Add high level design of the config package and config resolving

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
go.mod
go.sum
internal/tools/go.sum
pdata/go.mod
pdata/go.sum

Bump all deps, Monday, May, 16th

---

CHANGELOG.md
config/mapprovider.go

Remove access to deprecated members of the config.Retrieved struct

---

docs/release.md

Update docs/release to not manually change file, but re-run the builder

---

receiver/otlpreceiver/README.md

[docs] add status header for OTLP receiver

---

pdata/ptrace/json.go
pdata/ptrace/json_test.go

Remove test only code that marshalls json using jsonpb

---

processor/batchprocessor/README.md

[docs] add status for batch processor

---

exporter/loggingexporter/README.md

[docs] add status for logging exporter

---

VERSIONING.md

Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/5358

Define stability guarantees for v1 API

---

component/componenterror/errors.go

Fix deprecated message, missing version

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
internal/tools/go.sum
versions.yaml

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5416

[chore] prepare v0.52.0 release

---

extension/ballastextension/README.md
extension/zpagesextension/README.md

Fixes #5375
Fixes #5429
Fixes #5428

[docs] add status header for ballast/zpages

---

exporter/otlpexporter/factory.go
exporter/otlpexporter/otlp.go

Nit: small nit fix in otlpexporter, no functionality change

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
go.mod
go.sum
pdata/go.mod
pdata/go.sum

Bump dependencies to latest

---

component/build_info.go

nit: fix comments in BuildInfo struct

---

service/telemetry.go

Fix merge race condition between PRs

---

config/moved_configmap.go

Fix typo in deprecation message for config.WithRetrievedClose

---

confmap/provider/envprovider/provider.go
confmap/provider/envprovider/provider_test.go
confmap/provider/fileprovider/provider.go
confmap/provider/fileprovider/provider_test.go
confmap/provider/fileprovider/testdata/invalid-yaml.yaml
confmap/provider/internal/provider.go
confmap/provider/internal/provider_test.go
confmap/provider/yamlprovider/provider.go
confmap/provider/yamlprovider/provider_test.go

Also small rename of the provider files from mapprovider -> provider.

Avoid duplicate code, add internal.NewRetrievedFromYAML

---

confmap/README.md

Remove false statement from confmap/README.md, the Resolver is public now

---

CHANGELOG.md
service/telemetry.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5404

Remove AddCollectorVersionTag, enabled for long time already

---

component/componenttest/testdata/invalid_go.txt
component/componenttest/testdata/valid_go.txt

Remove unused go template files in testdata

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
go.sum
versions.yaml

[chore] prepare v0.53.0 release

---

docs/release.md

**Description:**  Update release schedule by moving myself to the bottom of the list.

[docs/release] Update release schedule

---

service/config_test.go

Move config tests to service to avoid using deprecated config types

---

service/host.go
service/internal/builder/exporters_builder.go
service/internal/builder/exporters_builder_test.go
service/internal/builder/pipelines_builder.go
service/internal/builder/pipelines_builder_test.go
service/internal/builder/receivers_builder_test.go
service/internal/components/constants.go
service/service.go

Cleanup exporters builder, avoid exposing private members

---

config/common.go

Fix some comment typos.

---

.github/workflows/create-dependabot-pr.yml
.github/workflows/scripts/dependabot-pr.sh

This PR is the core repo version of https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/eac0998a9d39121e3647180059acf2dd02dd3f77
This pr adds a workflow to replace the manual work required to commit all the dependabot PRs. The workflow:
- checks out the code
- runs .github/workflows/scripts/dependabot-pr.sh which looks for all dependabot PRs and applies the dependency update
- runs tidy/builds the collector
- commits a change and creates a PR

[chore] add gh action to consolidate dependabot PR

---

docs/processing.md

This PR adds to the telemetry query language the concept of Constructor functions.
Related to PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10487

[Telemetry Query Language] Added Constructor definition

---

.golangci.yml

Enable tenv linter, ensure env vars are cleaned up

---

service/collector_test.go
service/command_test.go

Cleanup NewCommand and Collector tests 

---

exporter/otlpexporter/otlp.go

Pass context to grpc.Dial, so service can control deadline, cancel

---

config/configgrpc/configgrpc.go
config/configgrpc/wrappedstream.go
config/configgrpc/wrappedstream_test.go

Move internal/midleware to config/configgrpc, only usage

---

service/service.go

nit: simplify TraceProvider initialization in one step

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
go.sum
versions.yaml

**Description:** Changes to prepare for the `v0.54.0` release.

Release Prep v0.54.0

---

service/host.go
service/internal/extensions/extensions.go
service/service.go
service/zpages.go

Rename BuiltExtensions to Extensions, consistency with Pipelines

---

component/exporter.go
component/processor.go
component/receiver.go

Change type of factory options to be an internal interface. The goal is to be able to introduce options that apply to multiple factories, as in
```go
type ComponentFactoryOption interface {
ReceiverFactoryOption
ProcessorFactoryOption
ExporterFactoryOption
}
```
Since the type is private I think this is not a breaking change and does not warrant a changelog.
**Link to tracking Issue:** Motivated by https://github.com/open-telemetry/opentelemetry-collector/pull/5580#discussion_r907226442

[component] Change type of factory options to use internal interface

---

service/internal/extensions/extensions.go
service/internal/extensions/extensions_test.go
service/service.go

Change extensions.Build to accept settings, allow extensibility

---

service/internal/pipelines/pipelines.go
service/internal/pipelines/pipelines_test.go
service/service.go

Change pipelines.Build to accept settings, allow extensibility

---

.github/workflows/build-and-test.yml
.github/workflows/scripts/verify-dist-files-exist.sh
CHANGELOG.md
cmd/builder/.goreleaser.yml

Hi there,
I've successfully built and tested  the opentelemetry-collector on power VM. 
* adding code changes to enable CICD to generate linux binaries for PPC64le arch.
please review and merge. and suggest any changes if required.

adding support for ppc64le arch

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
versions.yaml

Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/5716

[chore] Prepare collector core release v0.56.0

---

service/extensions/config.go
service/extensions/extensions.go
service/extensions/extensions_test.go
service/host.go
service/service.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5564

Move extensions for internal to public package

---

.github/workflows/scripts/dependabot-pr.sh

* No reason to "build" the collector, instead we need to make sure we generate the collector automatic files to be up to date.
* No reason not to skip any other file.

Update dependabot pr GH action to generate otelcorecol and include all files

---

.github/workflows/scripts/dependabot-pr.sh

Signed-off-by: Bogdan Drutu <@users.noreply.github.com>

Dependabot PR, do not ignore root module in core

---

CHANGELOG.md
service/config.go
service/config_test.go
service/telemetry.go

Remove deprecated funcs/types from service related to Config

---

CHANGELOG.md
component/componenttest/nop_exporter.go
component/componenttest/nop_processor.go
component/componenttest/nop_receiver.go
component/exporter.go
component/exporter_test.go
component/processor.go
component/processor_test.go
component/receiver.go
component/receiver_test.go
exporter/loggingexporter/factory.go
exporter/otlpexporter/factory.go
exporter/otlphttpexporter/factory.go
internal/testcomponents/example_exporter.go
internal/testcomponents/example_processor.go
internal/testcomponents/example_receiver.go
processor/batchprocessor/factory.go
processor/memorylimiterprocessor/factory.go
receiver/otlpreceiver/factory.go
service/internal/pipelines/pipelines_test.go

Replace deprecate With[Traces|Metrics|Logs][Receiver|Processor|Exporter] with the new definition

---

pdata/internal/cmd/pdatagen/internal/base_fields.go

Remove unused code in pdata generator

---

.github/workflows/changelog.yml
.github/workflows/contrib-tests.yml

Add a new label Skip Contrib Tests that skips contrib tests requirement

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
versions.yaml

- Update changelog
- prepare release 0.57.0
Closes #5771

[chore] prepare release 0.57.0

---

CHANGELOG.md
component/exporter.go
component/processor.go
component/receiver.go

Remove deprecated component stability helpers

---

CHANGELOG.md
cmd/builder/go.mod
cmd/builder/internal/builder/config.go
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
internal/tools/go.mod
pdata/go.mod
semconv/go.mod
versions.yaml

Cherry Pick https://github.com/open-telemetry/opentelemetry-collector/pull/5808

Prepare for v0.57.2 (#5808)

---

internal/obsreportconfig/obsreportconfig.go
internal/obsreportconfig/obsreportconfig_test.go

Small nit in internal/obsreportconfig

---

exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/traces_test.go
internal/obsreportconfig/obsreportconfig.go
obsreport/obsreport_exporter.go
obsreport/obsreport_receiver.go
obsreport/obsreport_scraper.go
receiver/otlpreceiver/otlp_test.go

Remove global metrics level, use level passed in create settings

---

CHANGELOG.md

nit: add PR number to the changelog entry

---

exporter/exporterhelper/internal/bounded_memory_queue.go
exporter/exporterhelper/internal/persistent_queue.go
exporter/exporterhelper/internal/persistent_storage.go
exporter/exporterhelper/internal/producer_consumer_queue.go

Remove unnecessary code from persistent queue implementation

---

exporter/exporterhelper/queued_retry.go

Remove unnecessary slice for only one attribute value

---

exporter/exporterhelper/internal/bounded_memory_queue.go
exporter/exporterhelper/internal/bounded_memory_queue_test.go
exporter/exporterhelper/queued_retry.go

exporterhelper: bounded memory queue, remove unused onDropItem func

---

exporter/exporterhelper/common.go
exporter/exporterhelper/internal/persistent_queue.go
exporter/exporterhelper/internal/persistent_storage.go
exporter/exporterhelper/internal/persistent_storage_batch.go
exporter/exporterhelper/internal/persistent_storage_test.go
exporter/exporterhelper/internal/request.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/queued_retry.go
exporter/exporterhelper/queued_retry_test.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/traces_test.go

Unify exporterhelper.request and internal.PersistentRequest

---

exporter/exporterhelper/internal/bounded_memory_queue.go
exporter/exporterhelper/internal/bounded_memory_queue_test.go
exporter/exporterhelper/internal/persistent_queue.go
exporter/exporterhelper/internal/persistent_queue_test.go
exporter/exporterhelper/internal/producer_consumer_queue.go
exporter/exporterhelper/queued_retry.go

Use internal.Request in the ProducerConsumerQueue, avoid casting

---

confmap/confmaptest/configtest_test.go
confmap/resolver_test.go

Fix build because of a race condition between merged PRs

---

receiver/otlpreceiver/internal/logs/otlp_test.go
receiver/otlpreceiver/internal/metrics/otlp_test.go
receiver/otlpreceiver/internal/trace/otlp_test.go
receiver/otlpreceiver/otlp_test.go

[chore] otlpreceiver check errors in tests

---

processor/memorylimiterprocessor/factory.go

Use the config pointer as the key for the memorylimiter instances instead of the ID

---

confmap/confmaptest/configtest.go

[chore] fix wrong usage of yaml.v2 instead of yaml.v3

---

CHANGELOG.md

Update changelog for the relase v0.58.0

---

exporter/otlpexporter/otlp_test.go

See https://github.com/open-telemetry/opentelemetry-collector/runs/7841516008?check_suite_focus=true

Fix race condition in otlpexporter tests

---

pdata/internal/cmd/pdatagen/internal/base_fields.go
pdata/internal/generated_common.go
pdata/internal/generated_plog.go
pdata/internal/generated_pmetric.go
pdata/internal/generated_ptrace.go
pdata/internal/generated_resource.go

Remove unnecessary pointer dereference in pdata

---

service/collector.go
service/service.go

Move log statements to service when possible and cleaner

---

CHANGELOG.md
processor/memorylimiterprocessor/factory.go
processor/memorylimiterprocessor/memorylimiter_test.go
processor/processorhelper/logs.go
processor/processorhelper/logs_test.go
processor/processorhelper/metrics.go
processor/processorhelper/metrics_test.go
processor/processorhelper/traces.go
processor/processorhelper/traces_test.go

Deprecate New*ProcessorWithCreateSettings, update New*Processor to the new API

---

pdata/internal/json/common.go

[chore]: remove unnecessary return true

---

CHANGELOG.md
pdata/internal/metrics.go

Remove deprecated funcs from pdata module.

---

pdata/ptrace/json.go
pdata/ptrace/json_test.go

Use common json parsing code for attributes

---

component/extension.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/traces.go
processor/processorhelper/logs.go
processor/processorhelper/metrics.go
processor/processorhelper/traces.go

Bogdan was back in time for 1 week :)

Fix deprecation version in deprecation message

---

CHANGELOG.md
pdata/internal/json/scope.go
pdata/internal/json/scope_test.go
pdata/pmetric/json.go
pdata/ptrace/json.go
pdata/ptrace/json_test.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5312 

Fix reading scope attributes for trace JSON, remove duplicate code

---

docs/release.md

[chore] update release table

---

service/internal/configunmarshaler/defaultunmarshaler.go

[chore] remove unnecessary nolint statement

---

pdata/ptrace/json_test.go

[chore] fix build due to race in merge PRs

---

service/config_test.go

[chore] use proper velidate error instead of a hacky way

---

pdata/pcommon/common_test.go

- Remove duplicate tests
- Remove Attribute part from Map and Slice
- Remove benchmark tests
- Make sure consistent naming for helpers
- Fix some typos

[chore] Cleanup pdata/internal/common_tests.go

---

CHANGELOG.md
pdata/internal/json/attribute.go
pdata/internal/json/number.go
pdata/internal/json/number_test.go
pdata/pmetric/json.go

To fix tests in contrib https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/8007302828?check_suite_focus=true 

Fix json parsing for float64

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
go.mod
go.sum

Upgrade zap and opencensus-prometheus

---

CHANGELOG.md
component/extension.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/traces.go
processor/processorhelper/logs.go
processor/processorhelper/metrics.go
processor/processorhelper/traces.go

Remove deprecated components helpers funcs

---

CHANGELOG.md
exporter/loggingexporter/internal/otlptext/logs.go
pdata/internal/cmd/pdatagen/internal/log_structs.go
pdata/plog/generated_logs.go
pdata/plog/generated_logs_test.go
pdata/plog/logs.go

Remove deprecated funcs and enum values from plog

---

CHANGELOG.md
pdata/internal/cmd/pdatagen/internal/metrics_structs.go
pdata/pmetric/generated_metrics.go
pdata/pmetric/generated_metrics_test.go
pdata/pmetric/metric_data_point_flags.go
pdata/pmetric/metric_data_point_flags_test.go
pdata/pmetric/metrics.go
pdata/pmetric/metrics_test.go

Remove deprecated funcs for pmetric

---

CHANGELOG.md
pdata/internal/json/resource.go
pdata/internal/json/resource_test.go
pdata/pmetric/json.go
pdata/ptrace/json.go

Remove duplicate code in Traces and Metrics JSON unmarshaler

Remove duplicate code in Traces and Metrics JSON unmarshaler

---

pdata/pmetric/json_test.go
pdata/ptrace/json_test.go

Remove duplicate tests, already covered in internal/json/resource_test

---

CHANGELOG.md
pdata/internal/json/attribute.go
pdata/internal/json/attribute_test.go
pdata/plog/json.go

Correctly skip unkown value types

---

pdata/plog/json.go
pdata/pmetric/json.go
pdata/ptrace/json.go

[chore] remove unnecessary private funcs

---

pdata/internal/cmd/pdatagen/internal/common_structs.go
pdata/internal/data/bytesid.go
pdata/internal/data/spanid.go
pdata/internal/data/spanid_test.go
pdata/internal/data/traceid.go
pdata/internal/data/traceid_test.go
pdata/internal/generated_wrapper_logs.go
pdata/internal/generated_wrapper_metrics.go
pdata/internal/generated_wrapper_traces.go
pdata/plog/generated_logs_test.go
pdata/pmetric/generated_metrics_test.go
pdata/ptrace/generated_traces_test.go

[chore] remove unnecessary ctor func, clarify errors

---

confmap/confmap.go

This is a quick fix to unblock https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/8276682484?check_suite_focus=true
I believe the issue still needs more attention.
@djaglowski @bogdandrutu PTAL

Fix failing unmarshalerHookFunc

---

service/README.md

**Description:** Updates `README.md` in service directory to include newly added `http` provider.

[chore] Update service readme with HTTP provider

---

pdata/pcommon/common.go

[chore] Remove dulicate code between New[Map|Slice]FromRaw and FromRaw.

---

pdata/pcommon/common.go
pdata/pcommon/common_test.go

[chore] avoid unnecessary copy when doing fromraw

---

cmd/builder/go.mod
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go

builder: move config module validation during Validate

---

CHANGELOG.md
exporter/exporterhelper/internal/persistent_queue_test.go
internal/testdata/common.go
internal/testdata/log.go
pdata/pcommon/common.go

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/5998

[pdata] Deprecate Map.Insert* methods

---

.github/workflows/contrib-tests.yml
Makefile

Make sure contrib is fully restored locally but ignore it in CI

[Makefile] Clean up check-contrib target

---

CHANGELOG.md
exporter/loggingexporter/internal/otlptext/databuffer.go
pdata/internal/cmd/pdatagen/internal/common_structs.go
pdata/internal/cmd/pdatagen/internal/trace_structs.go
pdata/internal/generated_wrapper_traces.go
pdata/internal/wrapper_common.go
pdata/pcommon/trace_state.go
pdata/pcommon/trace_state_test.go
pdata/ptrace/generated_traces.go
pdata/ptrace/generated_traces_test.go
pdata/ptrace/json_test.go
pdata/ptrace/traces.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6022
Main motivation is that we may want to allow mutating (adding an entry to the state).

Replace immutable TraceState with a mutable struct

---

pdata/pcommon/common.go
pdata/pcommon/common_test.go

[chore] Remove unnecessary private func in pcommon.Value

---

service/featuregate/flags.go

[chore] Remove unnecessary private func in featuregate

---

CHANGELOG.md
pdata/pcommon/common.go
pdata/pcommon/common_test.go

Remove deprecated funcs from pcommon.[Map|Value|Slice]

---

CHANGELOG.md
pdata/pmetric/metrics.go

Delete deprecated Metric.SetDataType

---

CHANGELOG.md
pdata/pmetric/metric_data_point_flags.go
pdata/pmetric/metrics.go

Delete deprecated metrics immutable flags APIs

---

docs/release.md

Update release rotation
**Link to tracking Issue:** Fixes #6067

[docs] Update release rotation

---

CHANGELOG.md

Remove duplicate entry in CHANGELOG

---

.github/workflows/scripts/dependabot-pr.sh

[chore] Fix small nits in dependabot-pr.sh

---

pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
pdata/pcommon/generated_primitive_slice.go

Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6106

[pdata] Add more documentation to primitive slice methods

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/builder/internal/config/default.yaml
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
versions.yaml

Prepare collector-core for version v0.61.0

[chore] prepare release 0.61.0

---

CHANGELOG.md
semconv/template.j2
semconv/v1.10.0/generated_resource.go
semconv/v1.10.0/generated_trace.go
semconv/v1.10.0/nonstandard.go
semconv/v1.10.0/schema.go
semconv/v1.11.0/generated_resource.go
semconv/v1.11.0/generated_trace.go
semconv/v1.11.0/nonstandard.go
semconv/v1.11.0/schema.go
semconv/v1.12.0/generated_resource.go
semconv/v1.12.0/generated_trace.go
semconv/v1.12.0/nonstandard.go
semconv/v1.12.0/schema.go
semconv/v1.13.0/generated_resource.go
semconv/v1.13.0/generated_trace.go
semconv/v1.13.0/nonstandard.go
semconv/v1.13.0/schema.go

Generate semantic conventions for spec v1.10-1.13

---

pdata/pmetric/metric_data_point_flags.go

[chore] remove outdated comment about MetricDataPointFlags

---

confmap/README.md
confmap/resolver.go
confmap/resolver_test.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5706

Disallow dollar sign in opaque value, allow recursive expansion to be implemented in the future

---

CHANGELOG.md
cmd/builder/internal/builder/config.go
cmd/builder/internal/config/default.yaml
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
examples/k8s/otel-config.yaml
go.mod
versions.yaml

- prepare release 0.62.0
- Prepare collector-core for version v0.62.0
- add multimod changes

[chore] prepare release v0.62.0

---

pdata/internal/cmd/pdatagen/internal/base_slices.go
pdata/internal/cmd/pdatagen/internal/base_structs.go
pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
pdata/pcommon/common.go
pdata/pcommon/generated_common.go
pdata/pcommon/generated_primitive_slice.go
pdata/pcommon/generated_resource.go
pdata/pcommon/trace_state.go
pdata/plog/generated_logs.go
pdata/plog/logs.go
pdata/pmetric/generated_metrics.go
pdata/pmetric/metrics.go
pdata/ptrace/generated_traces.go
pdata/ptrace/traces.go

Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6286

[pdata] Clarify CopyTo and MoveTo behavior in godoc.

---

Makefile

Add `.yaml` to changelog files.
**Link to tracking Issue:** Fixes #6332

[Makefile] Add `.yaml` to changelog filename for `chlog-new`

---

proto_patch.sed

All these types were renamed/removed

[chore] remove outdated proto patches

---

docs/design.md

Started looking at various documents under the `docs` directory that are somewhat outdatted. This PR updates the design document.

[docs] update design.md doc

---

.chloggen/deprecateallconfig.yaml
component/config.go
config/moved_config.go
exporter/exporterhelper/internal/persistent_queue_test.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/queued_retry_test.go
exporter/exporterhelper/traces.go
obsreport/obsreport_exporter.go
obsreport/obsreport_receiver.go
obsreport/obsreport_scraper.go
service/config.go
service/internal/pipelines/pipelines.go
service/internal/pipelines/pipelines_test.go
service/service_test.go

No deprecation, they were added in this cycle. Deprecated old formats are in config package.

Change component.DataType enum value names to be consistent with other in the repo

---

confmap/resolver.go
featuregate/gates.go
featuregate/gates_test.go
internal/obsreportconfig/obsreportconfig.go

No deprecation, they were added in this cycle.

Change featuregate.Stage enum value names to be consistent with other in the repo

---

.chloggen/featuregatestage.yaml
featuregate/gates.go
featuregate/gates_test.go
featuregate/stage.go
featuregate/stage_test.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6490

Capitalize featuregate.Stage string values, remove Stage prefix

---

.chloggen/split-components.yaml

[chore] fix typo in changelog

---

Makefile

Corresponds to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16328

[chore] Add 'goporto' and 'multimod-verify' to default make target

---

docs/release.md

This specifically calls out the correct way to merge the pull request.
cc @bogdandrutu as the other recent patch releaser

[docs] add documentation around patch release

---

cmd/otelcorecol/go.mod
component/go.mod
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/ballastextension/go.mod
extension/zpagesextension/go.mod
go.mod
processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/otlpreceiver/go.mod

[chore] update featuregate dep

---

Makefile

[chore] missed adding consumer to contrib makefile targets

---

cmd/builder/internal/builder/config.go
cmd/builder/internal/config/default.yaml
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
component/go.mod
consumer/go.mod
examples/k8s/otel-config.yaml
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/ballastextension/go.mod
extension/zpagesextension/go.mod
go.mod
processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/otlpreceiver/go.mod
versions.yaml

[chore] prepare release 0.65.0

---

.chloggen/rm-deprecated.yaml
featuregate/gate.go

[featuregate] remove deprecated func

---

CONTRIBUTING.md

See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9888

Document organization of Makefile, Makefile.Common

---

service/pipelines_test.go

Fix some pipeline tests and validate error messages

---

processor/batchprocessor/metrics.go

[chore] fix typo in comment

---

.chloggen/fixotlptransport.yaml
connector/forwardconnector/forward.go
internal/sharedcomponent/sharedcomponent.go
internal/sharedcomponent/sharedcomponent_test.go
receiver/otlpreceiver/factory.go
receiver/otlpreceiver/internal/logs/otlp.go
receiver/otlpreceiver/internal/logs/otlp_test.go
receiver/otlpreceiver/internal/metrics/otlp.go
receiver/otlpreceiver/internal/metrics/otlp_test.go
receiver/otlpreceiver/internal/trace/otlp.go
receiver/otlpreceiver/internal/trace/otlp_test.go
receiver/otlpreceiver/otlp.go
receiver/otlpreceiver/otlp_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6695

Fix otlpreceiver transport metrics attribute

---

.chloggen/fix4030.yaml
config/configgrpc/configgrpc.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4030

Fix todo to add MeterProvider to grpc instrumentation

---

otelcol/internal/configunmarshaler/configs_test.go
otelcol/unmarshaler.go
otelcol/unmarshaler_test.go

Subset of #6700 
This adds an unmarshaler to `otelcol/internal/configunmarshaler`.

[chore] Add connectors to configunmarshaler test

---

.chloggen/revert-6693-main.yaml

_Please delete paragraphs that you did not …

Add chloggen

---

.chloggen/deprecate-value-equal.yaml
pdata/pcommon/common.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6811

[pdata] Deprecate pcommon.Value.Equal method

---

service/internal/components/loggers.go

Add connector logger

---

docs/release.md

Fix instructions for updating contrib repo in release docs

---

docs/security-best-practices.md

Update security guidelines around 0.0.0.0.  As k8s situations are more nuanced I'll update the helm chart specifically to address this security guideline.
https://github.com/open-telemetry/opentelemetry-collector/issues/6938

Update security recommendation

---

.chloggen/otlpthttp-retry.yaml
exporter/otlphttpexporter/otlp.go

#6845
Update retry based on spec change
**Link to tracking Issue:** <Issue number if applicable> 
#6845 
**Documentation:** < Describe the documentation added.> 

[exporter/otlphttp] Retry only on status code 429/502/503/504

---

connector/connector.go
connector/connector_test.go

Parameterize connector data type errors

---

.chloggen/add-debug-option-to builder.yaml
cmd/builder/README.md
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go
cmd/builder/internal/builder/main.go
cmd/builder/internal/builder/main_test.go
cmd/builder/internal/command.go
cmd/builder/internal/command_test.go

**Description:** add option to enable remote debug
**Link to tracking Issue:** Closes https://github.com/open-telemetry/opentelemetry-collector/issues/6149
**Testing:** Tested with delve
**Documentation:** Documentation updated

add remote debug option for otel-collector to builder

---

.github/workflows/api-compatibility.yml
.github/workflows/build-and-test.yml
CONTRIBUTING.md
Makefile
Makefile.Common
internal/buildscripts/compare-apidiff.sh
internal/buildscripts/gen-apidiff.sh

Looking to reduce contribution toil and reducing onboarding efforts, this removes any additional once of steps that could cause issues with tooling versioning mismatches.
N/A

[chore] Simplify contribution / Usage

---

internal/buildscripts/compare-apidiff.sh
internal/buildscripts/gen-apidiff.sh

Use git rev-parse instead.
Fixes #6977

[chore] remove need for realpath

---

cmd/builder/internal/builder/config.go
cmd/builder/internal/config/default.yaml
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
component/go.mod
confmap/go.mod
connector/forwardconnector/go.mod
consumer/go.mod
examples/k8s/otel-config.yaml
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/ballastextension/go.mod
extension/zpagesextension/go.mod
go.mod
processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/otlpreceiver/go.mod
versions.yaml

Run
```
make prepare-release PREVIOUS_VERSION=0.69.1 RELEASE_CANDIDATE=0.70.0 MODSET=beta
```
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/7000

[chore] Prepare release 0.70.0

---

otelcol/config_test.go

See https://github.com/open-telemetry/opentelemetry-collector/pull/7001#discussion_r1085710724

Merge otelcol test config structs

---

.chloggen/fix_receiverLoggerDataTypeKey.yaml
service/internal/components/loggers.go

Fix incorrect key used for receiver logger datatype attribute

---

internal/tools/go.mod
internal/tools/go.sum
internal/tools/tools.go

[chore] remove ghr

---

.github/workflows/scripts/release-prepare-release.sh

[chore] update release script to fail on error

---

docs/release.md

@bogdandrutu if you're ok with it, I'd like to do the next release to ensure the changes to the release process I've made work.

[chore] update release schedule

---

.github/workflows/scripts/dependabot-pr.sh
.github/workflows/scripts/set_release_tag.sh
.github/workflows/scripts/verify-dist-files-exist.sh
.github/workflows/shellcheck.yml
cmd/builder/test/test.sh
internal/buildscripts/compare-apidiff.sh
internal/buildscripts/gen-apidiff.sh

Adding shellcheck GitHub Actions workflow.
Fixing issues detected by shellcheck.
**Link to tracking Issue:** #6864

Add shellcheck GitHub Actions workflow

---

service/graph.go

Follows #7045 with implementation of `pipelinesGraph.GetExporters`

Add graph-based GetExporters

---

pdata/internal/cmd/pdatagen/internal/base_slices.go
pdata/plog/generated_logrecordslice_test.go
pdata/plog/generated_resourcelogsslice_test.go
pdata/plog/generated_scopelogsslice_test.go
pdata/pmetric/generated_exemplarslice_test.go
pdata/pmetric/generated_exponentialhistogramdatapointslice_test.go
pdata/pmetric/generated_histogramdatapointslice_test.go
pdata/pmetric/generated_metricslice_test.go
pdata/pmetric/generated_numberdatapointslice_test.go
pdata/pmetric/generated_resourcemetricsslice_test.go
pdata/pmetric/generated_scopemetricsslice_test.go
pdata/pmetric/generated_summarydatapointslice_test.go
pdata/pmetric/generated_summarydatapointvalueatquantileslice_test.go
pdata/ptrace/generated_resourcespansslice_test.go
pdata/ptrace/generated_scopespansslice_test.go
pdata/ptrace/generated_spaneventslice_test.go
pdata/ptrace/generated_spanlinkslice_test.go
pdata/ptrace/generated_spanslice_test.go

The loop was never executed before

[chore] [pdata] Fix the generated tests for slices

---

service/graph.go
service/pipelines.go
service/service_test.go
service/zpages.go

Add graph-based implemenation of HandleZPages

---

.github/workflows/scripts/release-prepare-release.sh

Fixes the issue identified in the comment: https://github.com/open-telemetry/opentelemetry-collector/pull/7139#discussion_r1097740190

[chore] fix chlog-update format

---

.chloggen/addvisit.yaml
featuregate/registry.go
featuregate/registry_test.go
service/zpages.go

Not breaking change, not released yet.
For details see https://pkg.go.dev/flag#VisitAll and https://pkg.go.dev/flag#Visit

Fix API to be compatible with flagset, missed the comment initially

---

.chloggen/removeoldclosers.yaml
confmap/resolver.go
confmap/resolver_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/7215

confmap: clear list of old closers

---

.chloggen/service-graph-stable.yaml
service/service.go

Set service.graph feature gate to stable

---

service/graph.go
service/graph_test.go

See https://github.com/open-telemetry/opentelemetry-collector/pull/7045#discussion_r1094843917

Improve error message when cycle is detected in component graph

---

cmd/otelcorecol/go.mod
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
go.mod
processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/go.mod
receiver/go.sum
receiver/otlpreceiver/go.mod

This will make updating contrib easier

[chore] update receiver dep to main

---

.github/workflows/create-dependabot-pr.yml

This is now consistent w/ the contrib repo

[chore] rename dependabot pr action for consistency

---

cmd/otelcorecol/go.mod
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
go.mod
processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/go.mod
receiver/otlpreceiver/go.mod

Make update to contrib easier.

[chore] update exporter module to main

---

.github/dependabot.yml
Makefile

To avoid upgrading dependencies on the release day

[chore] Move dependabot PRs to Wednesday

---

exporter/exporterhelper/internal/bounded_memory_queue.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/7355

[chore] fix boundedMemoryQueue comments about implementation details

---

config/confighttp/compression_test.go
config/confighttp/confighttp_test.go
confmap/confmap_test.go
confmap/confmaptest/configtest_test.go
confmap/provider/internal/configurablehttpprovider/provider_test.go
connector/forwardconnector/forward.go
exporter/exporterhelper/internal/persistent_storage_test.go
extension/auth/authtest/mock_clientauth.go
extension/auth/authtest/mock_clientauth_test.go
extension/zpagesextension/zpagesextension_test.go
pdata/internal/cmd/pdatagen/internal/base_fields.go
service/internal/components/host_wrapper_test.go
service/telemetry/otel_trace_sampler.go
service/zpages.go

To address lint issues raised by https://github.com/open-telemetry/opentelemetry-collector/pull/7413

[chore] rename unused parameters

---

service/internal/proctelemetry/process_telemetry.go

To address lint issues raised in https://github.com/open-telemetry/opentelemetry-collector/pull/7413

[chore] remove redundant if

---

featuregate/README.md

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/7044

[docs] document feature gate removal

---

.github/workflows/milestone-add-to-pr.yml

This updates:
- the milestone to match "next release"
- the token to use otel bot's token
- context.issue.number

[chore] update milestone gh action

---

.chloggen/msg_fix-provide-type-error.yaml
confmap/provider.go

Updating the error message to be more informative to users on what the expected outcome is.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/7399
**Testing:**
NA
NA

[Provider] Include user friendly error

---

.chloggen/reload-clientca-on-file-change.yaml
cmd/otelcorecol/go.mod
config/configgrpc/configgrpc_test.go
config/confighttp/confighttp_test.go
config/configtls/clientcasfilereloader.go
config/configtls/clientcasfilereloader_test.go
config/configtls/configtls.go
config/configtls/configtls_test.go
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
go.mod
receiver/otlpreceiver/go.mod

**Description:** Reload client CAs in server TLS settings when file has been modified
**Link to tracking Issue:** #6524
**Testing:** manual only
**Documentation:** none

Reload client CAs in server TLS settings on file change

---

.chloggen/deprecateremoval.yaml
.chloggen/featuregatetasks.yaml
.chloggen/tofromversion.yaml
confmap/resolver.go
featuregate/README.md
featuregate/flag_test.go
featuregate/gate.go
featuregate/gate_test.go
featuregate/registry.go
featuregate/registry_test.go
featuregate/stage.go
service/internal/zpages/templates.go
service/internal/zpages/templates/features_table.html
service/zpages.go

Fixes 2 out of the 3 tasks in https://github.com/open-telemetry/opentelemetry-collector/issues/7043

featuregate: Add deprecated Stage and to/from versions

---

docs/release.md

Update release schedule after v0.75.0

Update release schedule

---

README.md

[chore] add atoulme as triager

---

CHANGELOG.md
cmd/builder/go.mod
cmd/builder/internal/builder/config.go
cmd/builder/test/core.builder.yaml
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go
component/go.mod
confmap/go.mod
connector/forwardconnector/go.mod
consumer/go.mod
examples/k8s/otel-config.yaml
exporter/go.mod
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/ballastextension/go.mod
extension/zpagesextension/go.mod
featuregate/go.mod
go.mod
pdata/go.mod
processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/go.mod
receiver/otlpreceiver/go.mod
semconv/go.mod
versions.yaml

Update main with changes from v0.76.1

---

.github/workflows/prepare-release.yml
docs/release.md

Based on the feedback from the latest release, touched up the releasing doc with some quick wins.

[chore] Touchup release doc

---

processor/batchprocessor/README.md

This PR is created to update the example referred in the ReadME
current example will lead to following error :

[chore]Update example in ReadMe - batch processor

---

.github/workflows/builder-release.yaml

[chore] add step to create a release for v* tag

---

.github/workflows/scripts/release-create-tracking-issue.sh
.github/workflows/scripts/release-prepare-release.sh

Update release scripts to not include unreleased version in the release titles

[chore] Do not include unreleased versions in the release titles

---

config/configtls/README.md
exporter/exporterhelper/README.md

**Description:** Document the format used for durations
**Link to tracking Issue:** #7619

document duration format

---

README.md

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/7778

Propose @astencel-sumo as triager

---

extension/experimental/storage/doc.go

Fix incorrect godoc for storage module.

[doc] update documentation

---

exporter/otlpexporter/README.md
exporter/otlphttpexporter/README.md

Follows https://github.com/open-telemetry/opentelemetry-specification/pull/3454

[chore] Update OTLP spec URL

---

otelcol/command.go
otelcol/command_components.go

minor refactor to the components sub command.

[chore] command name didn't reflect the subcmd

---

connector/README.md

See https://github.com/open-telemetry/opentelemetry.io/issues/2725#issuecomment-1558694501

[chore] Clarify description of connectors

---

.github/workflows/builder-integration-test.yaml
Makefile
Makefile.Common
cmd/builder/test/test.sh
internal/tools/go.mod
internal/tools/tools.go

This is needed to run the builder tests. Also added a makefile target to build the integration test more easily

[chore] install tool envsubst

---

cmd/otelcorecol/go.mod
exporter/go.mod
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/ballastextension/go.mod
extension/zpagesextension/go.mod
go.mod
processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/go.mod
receiver/otlpreceiver/go.mod

This will make updating core easier. Otherwise we'd need replace statements all over the place.

[chore] bump extension/processor pkgs to main

---

cmd/otelcorecol/go.mod
connector/forwardconnector/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
go.mod
receiver/otlpreceiver/go.mod

Makes update in contrib easier.

[chore] bump new modules to main

---

cmd/otelcorecol/go.mod
component/go.mod
config/configauth/go.mod
config/configgrpc/go.mod
config/confighttp/go.mod
config/configtls/go.mod
connector/forwardconnector/go.mod
connector/go.mod
exporter/go.mod
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/auth/go.mod
extension/ballastextension/go.mod
extension/go.mod
extension/zpagesextension/go.mod
go.mod
processor/batchprocessor/go.mod
processor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/go.mod
receiver/otlpreceiver/go.mod

[chore] update new modules to main

---

service/internal/graph/graph_test.go

found some double commented out statements

[chore] clean up comments

---

connector/forwardconnector/go.mod
connector/go.mod
receiver/otlpreceiver/go.mod

tidy is currently failing on main

[chore] fix main

---

docs/release.md

Swaps release managers for v0.81.0 and v0.82.0

Swap release managers for v0.81.0 and v0.82.0

---

Makefile
pdata/internal/data/protogen/common/v1/common.pb.go
pdata/internal/data/protogen/metrics/v1/metrics.pb.go

There are no changes from the previous release candidate, just a version update.

[chore] update OTLP to v1.0.0

---

service/telemetry/generated_config.go

Update jsonschema library w/ the latest code from opentelemetry-configuration

[chore] make genjsonschema

---

.chloggen/codeboten_update-jsonschema-0001b0391785d880ce052f4c6fd85c5a4e0474fa.yaml
service/telemetry/config.go
service/telemetry/generated_config.go

- `make genjsonschema`
- remove duplicate type

[chore] update jsonschema

---

service/telemetry/config.go

[chore] clean up debug statement

---

docs/troubleshooting.md

Updated Grafana dashboard link. Old dashboard was not updated for 3+years. I linked "my" dashboard, which is published also in the [repo](https://github.com/monitoringartist/opentelemetry-collector-monitoring), so users may contribute and improve it easily.
Dashboard has structure - horizontal by receivers/processors/exporters, vertical by traces/metrics/logs + process metrics. It is trying to be generic, no distro/component specific.

Update troubleshooting.md - Grafana dashboard link

---

.github/workflows/prepare-release.yml
docs/release.md

Based on a my experience releasing v0.83.0, I believe the following clarifications would help reduce potential errors in future releases.

[chore] Release docs clarification

---

exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/request.go
exporter/exporterhelper/traces.go

To be able to change it if necessary while it's in development phase

[chore] [exporterhelper] Add an experimental notice to the new API

---

exporter/exporterhelper/internal/mock_storage.go
exporter/exporterhelper/internal/persistent_queue_test.go
exporter/exporterhelper/internal/persistent_storage_batch_test.go
exporter/exporterhelper/internal/persistent_storage_test.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/queued_retry_test.go
exporter/exporterhelper/traces_test.go

[chore] [exporterhelper] Cleanup mock storage test helpers

---

docs/release.md

Fixing couple of typos along the way

[chore] update release doc

---

exporter/exporterhelper/queued_retry_test.go

The exporter doesn't use the jaeger queue library anymore. So the TODO can be resolved. We also need to change the mock request from transient error to permanent error to make sure that the first request is kept in the retry loop while the second one is in the queue

[chore] [exporterhelper] Enable TestQueuedRetry_StopWhileWaiting test

---

cmd/otelcorecol/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/zpagesextension/go.mod
go.mod
otelcol/go.mod
receiver/otlpreceiver/go.mod

This will facilitate updating the core module from contrib

[chore] update otelcol/service deps

---

obsreport/obsreport_exporter.go
obsreport/obsreport_processor.go
obsreport/obsreport_receiver.go
obsreport/obsreport_scraper.go
obsreport/obsreporttest/obsreporttest.go

Incorrectly labelled it as 0.85.0 before.

[chore] fix deprecation version

---

.chloggen/codeboten_deprecate-obsreporttest.yaml
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/obsexporter_test.go
exporter/exporterhelper/obsreport_test.go
exporter/exporterhelper/queue_sender_test.go
exporter/exporterhelper/traces_test.go
exporter/exportertest/nop_exporter.go
obsreport/obsreporttest/obsreporttest.go
obsreport/obsreporttest/obsreporttest_test.go
processor/processorhelper/obsreport_test.go
processor/processortest/nop_processor.go
receiver/receiverhelper/obsreport_test.go
receiver/receivertest/nop_receiver.go
receiver/scraperhelper/obsreport_test.go
receiver/scraperhelper/scrapercontroller_test.go

follow up on #8501. As per the suggestion, the code in NewCreateSettings is pretty small and not needed as a separate function.

remove NewCreateSettings funcs

---

Makefile

This is revert-ing the revert of https://github.com/open-telemetry/opentelemetry-collector/pull/8024. This also inverses the return of `check-changes` to match the original behaviour.
Fixes #8149

[chore] use multimod diff

---

pdata/internal/cmd/pdatagen/internal/base_fields.go
pdata/internal/cmd/pdatagen/internal/base_structs.go
pdata/internal/cmd/pdatagen/internal/pmetric_package.go
pdata/pmetric/generated_exponentialhistogramdatapoint.go
pdata/pmetric/generated_exponentialhistogramdatapoint_test.go
pdata/pmetric/generated_histogramdatapoint.go
pdata/pmetric/generated_histogramdatapoint_test.go

Simplify internal pdatagen structures by removing redundant interface usages and struct fields. 
No functional changes.

[chore] [pdata] Simplify internal pdatagen structs and interfaces

---

docs/release.md

- Fix step 8
- Rotate the schedule. I added a week to the winter holiday rotation and set it on Jan 8th instead of Jan 1st :)

[chore] Update the release doc

---

docs/platform-support.md

[docs/platform-support] Add owners for linux/arm

---

docs/release.md

Adjusts the release schedule to account for Kubecon.  I also adjusted the following dates, but let me know if you'd rather go right from a 2023-11-13 release to a 2023-11-20 release (1 week between releases).

[chore] Adjust release dates

---

README.md

[chore] Propose @songy23 as triager

---

exporter/exporterhelper/internal/bounded_memory_queue_test.go

Remove helper function, used by one test.

[chore] simplify test code

---

README.md

Fix the denial that @codeboten lives in.

Update @codeboten affiliation to reality

---

confmap/provider/internal/configurablehttpprovider/testdata/otel-config.yaml
examples/local/otel-config.yaml

[chore] [examples/local] fix memory_limiter description

---

exporter/exporterhelper/internal/bounded_memory_queue_test.go
exporter/exporterhelper/internal/consumers.go
exporter/exporterhelper/internal/persistent_queue_test.go
exporter/exporterhelper/queue_sender.go

Addressing https://github.com/open-telemetry/opentelemetry-collector/pull/8898#discussion_r1393471604

[chore] [exporterhelper] Make QueueConsumer control queue start/shutdown

---

exporter/exporterhelper/retry_sender.go

Revert an accidental change in https://github.com/open-telemetry/opentelemetry-collector/pull/8867/files#diff-4dfc275bb0788b5ee1310c9f3d6aed3d5c7e514e28be5b87802907d3ed5e0c4dR179

[chore] [exporterhelper] Revert accidental log message change

---

exporter/exporterhelper/internal/persistent_queue.go
exporter/exporterhelper/internal/persistent_storage.go
exporter/exporterhelper/internal/persistent_storage_test.go

Part of https://github.com/open-telemetry/opentelemetry-collector/pull/8923 split

[chore] Rename persistentContiguousStorage to persistentQueue

---

internal/tools/go.mod
internal/tools/go.sum

[chore] downgrade golangci-lint

---

exporter/exporterhelper/internal/persistent_queue_test.go

Update test names after removing the persistentStorage

[chore] [exporterhelper] Update persistent queue test names

---

exporter/exporterhelper/internal/bounded_memory_queue_test.go

The same tests as TestZeroSizeNoConsumers

[chore] [exporterhelper] Remove duplicate test TestZeroSize

---

exporter/exporterhelper/internal/persistent_queue_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/8958

[chore] Fix flaky test TestPersistentQueue_FullCapacity

---

exporter/exporterhelper/queue_sender_test.go

Update the test validating failed re-enqueue to ensure that the request is sent through the queue sender, not the retry sender. It'll unblock removing the dependency on the retry sender for the re-enqueue as done in https://github.com/open-telemetry/opentelemetry-collector/pull/8942

[chore] [exporterhelper] Update test validating failed re-enqueue

---

exporter/exporterhelper/queue_sender.go

Not being used after the recent changes

[chore] [exporterhelper] Remove redundant queueSender field

---

docs/platform-support.md

Add @atoulme as owner for linux/arm64 platform.
Fixes #9010

[chore] add @atoulme as owner for linux/arm64

---

docs/scraping-receivers.md

**Description:** Fix a broken link in scrapping receivers documentation.

Fix broken link to metadata schema

---

Makefile
Makefile.Common

It's not need after https://github.com/open-telemetry/opentelemetry-collector/pull/8024

[chore] Remove unused yq tool

---

Makefile.Common
internal/tools/jsonschema_patch.sed

Should've been removed as part of https://github.com/open-telemetry/opentelemetry-collector/pull/8620

[chore] Remove jsonschema artifacts

---

internal/tools/go.mod
internal/tools/go.sum
internal/tools/tools.go

This should've been included in https://github.com/open-telemetry/opentelemetry-collector/pull/9073

[chore] Remove yq package from internal/tools

---

processor/memorylimiterprocessor/config.go
processor/memorylimiterprocessor/config_test.go
processor/memorylimiterprocessor/memorylimiter.go

Addressing https://github.com/open-telemetry/opentelemetry-collector/pull/9059#discussion_r1424349622

[chore] [processor/memory_limiter] Move config errors to config.go

---

docs/platform-support.md

[chore][platform-support.md] Add owner for windows/386

---

consumer/consumer.go
consumer/doc.go
consumer/metrics.go

[chore] some doc changes to consumer package

---

consumer/consumer.go

A small fix to the doc string of a function to clarify what it returns.

[chore] small doc fix

---

exporter/exporterhelper/internal/bounded_memory_queue.go
exporter/exporterhelper/internal/bounded_memory_queue_test.go
exporter/exporterhelper/internal/persistent_queue.go
exporter/exporterhelper/internal/persistent_queue_test.go
exporter/exporterhelper/queue_sender.go

Address https://github.com/open-telemetry/opentelemetry-collector/pull/8853#discussion_r1438362242

[chore] [exporterhelper] Move queue creation parameters to structs

---

Makefile

[chore] make sure all contrib tests run

---

.github/workflows/contrib-tests.yml
Makefile

This speeds up replacements and make build logs easier to parse.

[chore] simplify replacements with one mod edit call instead of many

---

processor/README.md

Updated documentation
- Update recommended processors
- Update ordering processors
For recommended processors, either the log signal could be added or documentation could be made signal agnostic - opted for the latter.

Update processor README

---

README.md

[chore] add @TylerHelmuth as triager

---

.chloggen/remove_rpcz.yaml
extension/zpagesextension/README.md
service/service_test.go

Remove mention of rpcz from tests and README.
Fixes #9328

[extension/zpages] remove mention of rpcz

---

docs/platform-support.md

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/9351

docs: add @astencel-sumo as platform owner for `linux/386`

---

.chloggen/confignet-remove-deprecated-functions.yaml
config/confignet/confignet.go

Remove deprecated functions from confignet.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9105

[confignet] Remove deprecated functions

---

.chloggen/httpserversettings_httpserverconfig-otlpreceiver.yaml

add missing changelog for HTTPServerSettings->HTTPServerConfig for otlpreceiver Config
https://github.com/open-telemetry/opentelemetry-collector/pull/9405#discussion_r1470269634

[chore] add missing changelog for HTTPServerSettings->HTTPServerConfig for otlpreceiver Config

---

config/configtelemetry/configtelemetry.go
config/configtelemetry/configtelemetry_test.go

move implementation checks to test files
#9431

[configtelemetry] move implementation checks to test files

---

.chloggen/add_generated_tests_check_config.yaml
cmd/mdatagen/templates/component_test.go.tmpl

Add a generated test that checks the config struct using `componenttest.CheckConfigStruct`.

[mdatagen] add generated test to check config struct

---

.chloggen/mx-psi_deprecate-configgrpc.yaml
config/configgrpc/configgrpc.go

[config/configrpc] Deprecate SanitizedEndpoint, ToListener and ToListenerContext

---

receiver/receivertest/contract_checker.go

[chore] fix var naming

---

.chloggen/remove_ServerConfig_ToListener.yaml
config/configgrpc/configgrpc.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/9481

[configgrpc] Remove deprecated ServerConfig.ToListener

---

config/configgrpc/configgrpc_test.go

Update usage of removed `confignet` API

[chore] Fix the build

---

cmd/builder/internal/builder/config.go

Fix #9626 by aligning the ocb version with Collector's.

[chore] Fix version in ocb

---

docs/troubleshooting.md

Fix highlighting for traces config in https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#traces

[chore] troubleshootings docs fix  yaml code highlighting

---

.github/workflows/prepare-release.yml

fixes the intendation issue at: https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/prepare-release.yml
Refer - https://github.com/open-telemetry/opentelemetry-collector/pull/9409#issuecomment-1972971296

[chore] fixes intendation issues in yaml file

---

.chloggen/issue-9475-configtls-validate.yaml
config/configtls/configtls.go
config/configtls/configtls_test.go
exporter/otlpexporter/config_test.go
exporter/otlpexporter/testdata/invalid_configs.yaml

Add `Validate()` method to `TLSSetting` and validate tls `min_version` and `max_version`.
#9475

[config/configtls] Validate MinVersion and MaxVersion

---

.github/ISSUE_TEMPLATE/feature_request.md

The descriptions for each header in the feature request template for this repository are useful to the person filing a request, but serve no purpose to the issue reader. These can be commented out to in the displayed markdown to save the user from having to delete each one (or if not deleted, save the reader from having to parse through extra information).

[chore][Feature Request Template] Comment out header descriptions

---

CONTRIBUTING.md

As of the referenced issue, this project's minimum supported version is 1.21. Documentation should accurately reflect this.
https://github.com/open-telemetry/opentelemetry-collector/pull/9533

[CONTRIBUTING.md] Update golang version

---

CHANGELOG-API.md
CHANGELOG.md

Move API changes to the CHANGELOG-API.md and remove redundant entries

[chore] Cleanup the v1.4.0/v0.97.0 changelog

---

config/internal/warning.go
internal/localhostgate/featuregate.go
internal/localhostgate/featuregate_test.go

[chore] Do not log warning when feature gate is enabled

---

component/doc.go

Add connector as a type of component.

[chore] update the comment of the component package

---

config/configgrpc/go.mod
connector/go.mod
consumer/go.mod
exporter/go.mod
exporter/otlpexporter/go.mod
go.mod
internal/e2e/go.mod
otelcol/go.mod
processor/batchprocessor/go.mod
processor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/otlpreceiver/go.mod
service/go.mod

This will make updating contrib easier.

[chore] update pdata/testdata dep

---

README.md
docs/release.md

:tada: fixes #9946, fixes #9949, fixes #9953

Promote @atoulme, @TylerHelmuth and @songy23 to approvers

---

README.md

[chore] Remove dead link

---

.chloggen/mdatagen-filter.yaml

s/metadatagen/mdatagen/
Missed during review

[chore] Fix component name in changelog

---

cmd/mdatagen/go.mod

Makes updating contrib easier.

[chore] update filter dep

---

README.md
docs/platform-support.md

I have changed my GitHub username following https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username.

[chore] change @astencel-sumo to @andrzej-stencel

---

.chloggen/4274-allow-dns-as-scheme-for-endpoint.yaml
exporter/otlpexporter/config.go
exporter/otlpexporter/config_test.go

[exporter/otlp] Allow DNS scheme to be used in endpoint

---

cmd/builder/internal/builder/main_test.go

This is necessary when testing the builder with unreleased versions of Collector modules.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10014

[chore][cmd/builder] Include replaces in builder versioning tests

---

component/componenttest/otelprometheuschecker.go
otelcol/collector.go
receiver/otlpreceiver/otlp_test.go
receiver/receivertest/contract_checker.go

fix function names in comment
Fixes #

chore: fix function names in comment

---

.github/workflows/build-and-test.yml

We do the same for the contrib repo.
cc @atoulme

[chore] only run unit tests for actuated on a single version

---

cmd/builder/internal/builder/config.go

Revert changes to backwards compatibility

---

renovate.json

should not have included `https`

[chore] fix package prefix

---

README.md
docs/release.md

I have been unable to provide this position the bandwidth that it deserves and it is time to formalize recognition of that fact.

Move Aneurysm9 to emeritus status

---

.chloggen/confighttp-remove-deprecated-funcs.yaml
config/confighttp/confighttp.go

Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9807

[confighttp] Remove deprecated functions

---

README.md

We upgraded the proto version, so we need to upgrade it in the readme as well.
* https://github.com/open-telemetry/opentelemetry-collector/pull/10109#pullrequestreview-2058708683
* https://github.com/open-telemetry/opentelemetry-collector/pull/10155

Upgrade the used otlp version in readme

---

cmd/mdatagen/internal/samplereceiver/documentation.md

documentation needed to be regenerated

[chore] make gogenerate

---

cmd/mdatagen/README.md

Fixed the deadlink in mdatagen that would cause existing functionality to not work as expected.
Fixes #10071

[chore]: fix the dead link in mdatagen

---

CHANGELOG-API.md

Follow up to #9516 and https://github.com/open-telemetry/opentelemetry-collector/pull/10173#discussion_r1606677594

[chore] Amend changelog for ResolverSettings

---

service/service_test.go

This will allow enabling of goleak checks for the package.

[chore] fix leak in test

---

confmap/expand_test.go

Add a new test scenarios to confmap expand tests
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/10182#discussion_r1617668532

[confmap] Add new tests

---

CHANGELOG-API.md
CHANGELOG.md

Changelog update v1.9.0/v0.102.0

---

exporter/exporterhelper/obsexporter.go
processor/processorhelper/obsreport.go
receiver/receiverhelper/obsreport.go
receiver/scraperhelper/obsreport.go

These were declared and not used anywhere. Removing them.

[chore] removing unused loggers

---

README.md
docs/release.md

Fixes #10371 :tada: 
cc @open-telemetry/collector-approvers

[chore] Promote @evan-bradley to approver role

---

confmap/README.md
docs/troubleshooting.md

Adds troubleshooting section explaining how our configuration handles configuration like `processors:`.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9931

[confmap] Write up note about null maps

---

CONTRIBUTING.md

[chore] Document how component developers can add metrics to their code

---

exporter/loggingexporter/README.md

Fix formatting in loggingexporter README. loggingexporter is deprecated.

[chore] Fix formatting in loggingexporter README

---

.github/workflows/build-and-test.yml
.github/workflows/tidy-dependencies.yml
cmd/otelcorecol/go.mod
pdata/pprofile/go.mod

Removed the toolchain directive in pprof/go.mod as it's unnecessary

[chore] bump go 1.21.12

---

.github/workflows/check-goreleaser.yaml
.github/workflows/generate-semantic-conventions-pr.yaml

This addresses security concerns around permissions for workflows.

[chore] update global permissions on workflows

---

internal/featuregates/featuregates.go

This will be released in v0.105

[chore] fix register from version for gate

---

.github/workflows/build-and-test-arm.yml

Use the arm64 machines provisioned by https://github.com/open-telemetry/community/issues/2156
Fixes #10606

[chore] reenable arm testing

---

.github/workflows/build-and-test-arm.yml
docs/platform-support.md

Also updated the platform support doc.

[chore] update arm workflow to run both macos and linux

---

.chloggen/document_fields.yaml
component/status.go

Document status enums and New constructors
Fixes #9822

[component] Document status enums and New constructors

---

.chloggen/experimental_include_metadata.yaml

Addressing https://github.com/open-telemetry/opentelemetry-collector/pull/10685#discussion_r1688408298

[chore] fix changelog, drop user changelog mention

---

docs/release.md

Rotate the schedule to the next release.

[chore] Update release.md

---

docs/ga-roadmap.md

On the GA roadmap, we defined what modules are in scope, but we did not explicitly define how to determine the scope within these modules.
This PR adds some wording to define what the scope *within* modules is. These are roughly the criteria I have personally been using.

[chore] Define scope for 1.0 changes

---

cmd/mdatagen/go.mod
config/configgrpc/go.mod
config/confighttp/go.mod
connector/forwardconnector/go.mod
connector/go.mod
exporter/go.mod
exporter/nopexporter/go.mod
go.mod
processor/batchprocessor/go.mod
processor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/go.mod
receiver/nopreceiver/go.mod
receiver/otlpreceiver/go.mod
service/go.mod

this will make updating contrib much easier

[chore] update to main

---

cmd/otelcorecol/go.mod
exporter/debugexporter/go.mod
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/zpagesextension/go.mod
internal/e2e/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
receiver/otlpreceiver/go.mod
service/go.mod

Otherwise contrib continues to be mad about ambiguious packages

[chore] update indirect as well

---

.chloggen/mx-psi_fix-106-issue.yaml
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
extension/zpagesextension/zpagesextension_test.go
receiver/otlpreceiver/config_test.go
receiver/otlpreceiver/go.mod

[configauth] Use correct mapstructure tag in confighttp Auth section

---

CONTRIBUTING.md

Minor spelling and grammar clarification suggestions for the contribution guide. Added a link where relevant, as well

minor grammar and spelling improvements to CONTRIBUTING.md

---

service/extensions/extensions_test.go

This addresses a TODO in the extension test code.

[chore] update test to use slices.Reverse

---

extension/ballastextension/factory.go

I know this is a deprecated extension, but I stumbled on this comment and thought it didn't look right. :smile: 
Fixes #

ballastextension: fix comment typo

---

connector/README.md

corrects the description by replacing words in readme

fix replace words in doc

---

.chloggen/codeboten_mark-meter-deprecated.yaml
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/main_test.go
cmd/mdatagen/templates/telemetry.go.tmpl
cmd/mdatagen/templates/telemetry_test.go.tmpl
exporter/exporterhelper/internal/metadata/generated_telemetry.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/processorhelper/internal/metadata/generated_telemetry.go
receiver/receiverhelper/internal/metadata/generated_telemetry.go
receiver/scraperhelper/internal/metadata/generated_telemetry.go
service/internal/metadata/generated_telemetry.go

This is split from https://github.com/open-telemetry/opentelemetry-collector/pull/10912

[mdatagen] mark Meter as deprecated

---

CHANGELOG.md

Follow up to discussion in https://github.com/open-telemetry/opentelemetry-collector/pull/9759#discussion_r1725261693
@songy23 PTAL

[chore] add a changelog entry to highlight changes in #9759

---

.chloggen/confmap-remove-strictlytyped-feature-gate.yaml
internal/globalgates/globalgates.go

Remove stable confmap.strictlyTypedInput gate

[confmap] Remove stable confmap.strictlyTypedInput gate

---

.chloggen/remove-opencensus-bridge-gate.yaml
internal/globalgates/globalgates.go

Removes stable `service.disableOpenCensusBridge` gate.

[service] Remove stable service.disableOpenCensusBridge gate

---

cmd/mdatagen/loader.go

origin from https://github.com/open-telemetry/opentelemetry-collector/pull/10942#discussion_r1744374717
Fixes #

[chore] update comment for mdatagen loader

---

config/confighttp/README.md
receiver/otlpreceiver/config.md

Fix documentation for max_request_body_size 
Fixes #11066

Fix documentation for max_request_body_size

---

internal/iruntime/total_memory_other_test.go

testifylint wants to change the assertion and make sure it compiles。
Fixes #11164

[Chore] assert.Positive comply with testifylint

---

internal/e2e/status_test.go

Related to https://github.com/open-telemetry/opentelemetry-collector/issues/10927

[chore] Skip flaky test

---

receiver/otlpreceiver/README.md

Small formatting fix (add missing backquote) in README of otlpreceiver.

[chore] otlpreceiver: README: markdown formatting fix

---

Makefile

Replace filter to see if that fixes contrib tests

---

.chloggen/receivertest-remove-deprecations.yaml
receiver/receivertest/nop_receiver.go

[receivertest] Remove deprecated function

---

internal/memorylimiter/iruntime/total_memory_linux.go

Fix lint errors on linux

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
internal/e2e/go.mod
internal/e2e/go.sum
otelcol/go.mod
otelcol/go.sum
otelcol/otelcoltest/go.mod
otelcol/otelcoltest/go.sum
service/go.mod
service/go.sum

This update will be done separately as it includes breaking changes

[chore] set config to 0.10.0

---

processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
receiver/go.mod
receiver/nopreceiver/go.mod
receiver/otlpreceiver/go.mod

The current version cannot be resolved by modules outside core.

[chore] Use externally-resolvable version of consumererror

---

cmd/otelcorecol/go.mod
exporter/exporterhelper/exporterhelperprofiles/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
internal/e2e/go.mod

Pin other unreleased module versions, after running into the same issue as in https://github.com/open-telemetry/opentelemetry-collector/pull/11497.

[chore] Pin unreleased modules to commit version

---

docs/coding-guidelines.md
docs/component-stability.md

Works towards #11553. Unifies information about component stability in a single document.
Fixes #11571

[chore][docs] Move configuration changes guidelines to component stability doc

---

.github/ISSUE_TEMPLATE/vote.md

Adds issue template for making votes.
Fixes #11552

[chore] Add issue template for RFC votes

---

cmd/builder/test/core.builder.yaml

Add replace statement for `consumer/consumererror/consumererrorprofiles`

[chore] add the missing replace in core.builder.yaml

---

.chloggen/confignet-readme.yaml
config/confignet/README.md

Updates  dialer timeout section documentation in confignet README 
Fixes #11685

fix confignet README (dialer timeout)

---

README.md

Update the meeting times so they are in PT.

[chore] Update meeting times

---

README.md

Promote @jade-guiton-dd  to triager on behalf of @open-telemetry/collector-maintainers.
- PRs reviewed: https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+reviewed-by%3Ajade-guiton-dd+
- PRs authored: https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Ajade-guiton-dd+
- Issues commented: https://github.com/open-telemetry/opentelemetry-collector/issues?q=is%3Aissue+commenter%3Ajade-guiton-dd+
- Commits: https://github.com/open-telemetry/opentelemetry-collector/commits?author=jade-guiton-dd
cc @open-telemetry/collector-triagers

[chore] Add @jade-guiton-dd as a triager

---

docs/security-best-practices.md
receiver/otlpreceiver/README.md

Follows #11235, relates to #8510

[chore] Remove references to component.UseLocalHostAsDefaultHost

---

docs/release.md

This change is paired with https://github.com/open-telemetry/opentelemetry-collector-releases/pull/769

[chore] update release instructions to update the -releases changelog

---

exporter/internal/queue/default_batcher_test.go

[chore] Skip TestDefaultBatcher_Split_TimeoutDisabled on Windows

---

docs/release.md

[chore] Mention filing a thread in #otel-collector-dev during releases

---

docs/release.md

Adds post-release steps including release retro and schedule updating.
Fixes #11858

[chore] Add post-release steps

---

.github/CODEOWNERS

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/11840

[chore] Add open-telemetry/collector-approvers to all lines in CODEOWNERS

---

consumer/consumerprofiles/profiles.go

Follow-up to https://github.com/open-telemetry/opentelemetry-collector/pull/11779

[chore] Update deprecation comments in consumerprofiles module

---

docs/component-stability.md

Documents relationship between component stability and versioning.
Fixes #11851

[chore] [docs/component-stability.md] Document relationship between versioning and stability

---

docs/release.md

Mention release blockers should be addressed before the release.

[chore][release.md] mention release blockers

---

.github/workflows/milestone-add-to-pr.yml

This updates the pr update workflow to only the permissions needed.

[chore] restrict permissions on workflow

---

.github/workflows/check-merge-freeze.yml

This workflow only needs read access.

[chore] update permissions to read only

---

.github/workflows/api-compatibility.yml
.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test-windows.yaml
.github/workflows/build-and-test.yml
.github/workflows/builder-integration-test.yaml
.github/workflows/changelog.yml
.github/workflows/check-links.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/contrib-tests.yml
.github/workflows/generate-semantic-conventions-pr.yaml
.github/workflows/perf.yml
.github/workflows/shellcheck.yml
.github/workflows/stale-pr.yaml
.github/workflows/tidy-dependencies.yml

shorten
```
permissions:
contents: all
```
to
```
permissions: read-all
```

[chore] minor cleanup in workflows

---

.github/workflows/build-and-test-windows.yaml

[chore] add testing for windows 2025

---

.github/workflows/check-merge-freeze.yml

debug freeze check job

---

.github/workflows/check-merge-freeze.yml

This reverts commit 794d850595fd5326f5781b4b2b7495169b4256aa.

Revert "debug freeze check job (#12047)"

---

.github/workflows/check-merge-freeze.yml

Fix freeze check job

---

.github/workflows/changelog.yml

Fix an issue that `changelog` action will fail if there are no links detected: https://github.com/open-telemetry/opentelemetry-collector/actions/runs/12667603014/job/35301289365
Adding `failIfEmpty: false` to the action according to the doc: https://github.com/lycheeverse/lychee-action/blob/master/README.md#passing-arguments
n/a
n/a
n/a

[chore] Fix link checker to allow empty links

---

extension/zpagesextension/README.md

See https://github.com/open-telemetry/opentelemetry-collector/pull/11964#discussion_r1920925215

[chore] fix typo exporter->extension

---

docs/release.md

The job to run make opdate-otel is finally working

[chore] Update release doc to mention the new update-otel job

---

.chloggen/remove-deprecated-checkscrapermetrics.yaml
component/componenttest/obsreporttest.go
component/componenttest/otelchecker.go

Remove deprecated CheckScraperMetrics functions
Relevant to #12105 
n/a
n/a

Remove deprecated CheckScraperMetric functions

---

cmd/mdatagen/internal/loader_test.go
cmd/mdatagen/internal/samplereceiver/documentation.md
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/internal/samplereceiver/metrics_test.go
cmd/mdatagen/internal/templates/telemetry.go.tmpl
exporter/exporterhelper/internal/metadata/generated_telemetry.go

Fix several issues on optional metrics:
1. Add missing stability
2. Fix description and function in generated file
n/a
n/a
n/a

[chore] Fix optional metrics

---

exporter/exporterhelper/internal/queue_sender.go
exporter/exporterqueue/async_queue.go
exporter/exporterqueue/bounded_memory_queue_test.go
exporter/exporterqueue/persistent_queue_test.go
exporter/exporterqueue/queue.go

This PR will allow future PR that implements sync/disabled queue to propagate cancellation.

[chore] Move the logic to not propagate context propagation to async queue only

---

.chloggen/fix-blocking-queue.yaml
exporter/exporterqueue/async_queue.go
exporter/exporterqueue/async_queue_test.go
exporter/exporterqueue/memory_queue.go
exporter/exporterqueue/memory_queue_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12282

Fix async queue to propagate cancellation all they way to the queue

---

cmd/otelcorecol/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
receiver/otlpreceiver/go.mod
service/go.mod

This PR is to unblock `make update-otel` in contrib repo
cc @evan-bradley @mx-psi 
Relevant #12226 
n/a
n/a

[chore] Update latest version of `confmap/xconfmap`

---

cmd/mdatagen/internal/command.go

[chore] mdatagen fix to not create empty metadata/metadatatest dirs

---

.chloggen/codeboten_update-otlp-logs.yaml
receiver/otlpreceiver/README.md
receiver/otlpreceiver/internal/metadata/generated_status.go
receiver/otlpreceiver/metadata.yaml

This has been at least in beta for quite some time.
Fixes #11099

[receiver/otlp] update stability for logs

---

CHANGELOG.md

[service] update changelog to identify a breaking change

---

exporter/exporterhelper/internal/base_exporter_test.go
exporter/exporterhelper/internal/batch_sender_test.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/test_util.go

Followup is to make `setFeatureGateForTest` part of featuregatetest package.

[chore] Simplify setFeatureGateForTest definition and usage

---

cmd/otelcorecol/go.mod
internal/e2e/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
processor/memorylimiterprocessor/go.mod
receiver/otlpreceiver/go.mod
service/go.mod

Follow up to #12334 to do step 5 of https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/coding-guidelines.md#module-organization

[chore] Use pseudoversion for internal/telemetry

---

docs/observability.md
docs/platform-support.md

[docs] Fix links `syslist.go`

---

connector/xconnector/metadata.yaml
exporter/exporterhelper/xexporterhelper/metadata.yaml
exporter/xexporter/metadata.yaml
processor/processorhelper/logs_test.go
processor/xprocessor/metadata.yaml
receiver/xreceiver/metadata.yaml

Some of the metadata.yaml files contain invalid class field, this PR fixes them.

[chore] fix the class field of metadata.yaml files

---

cmd/otelcorecol/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/zpagesextension/go.mod
internal/e2e/go.mod
receiver/otlpreceiver/go.mod
service/go.mod

This is to fix this error on update-otel: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/13332696174/job/37240482863

[chore] Bump pseudoversion on root module

---

.github/workflows/ping-codeowners-prs.yml

Reduce the scope of permissions given to the github token.

[chore] update permissions for ping-codeowners-prs workflow

---

.github/workflows/ping-codeowners-issues.yml

Reduce the scope of permissions given to the github token

[chore] update permissions for ping-codeowners-issues workflow

---

.github/workflows/add-labels.yml

Reduce the scope of permissions given to the github token

[chore] update permissions for add-labels workflow

---

.github/workflows/add-codeowners-to-pr.yml

Reduce the scope of permissions given to the github token

[chore] update permissions for add-codeowners-to-pr workflow

---

README.md

Promote @sincejune to triager on behalf of @open-telemetry/collector-maintainers.
PRs reviewed: https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+reviewed-by%3Asincejune+
PRs authored: https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Asincejune+
Issues commented: https://github.com/open-telemetry/opentelemetry-collector/issues?q=is%3Aissue+commenter%3Asincejune+
Commits: https://github.com/open-telemetry/opentelemetry-collector/commits?author=sincejune

[chore] Promote Chao Weng to triager

---

cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/samplescraper/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/templates/metrics.go.tmpl

[mdatagen] Use ScopeName variable instead of actual value
n/a
n/a
n/a

[chore] [mdatagen] Use ScopeName variable instead of actual value

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/other.yaml
extension/xextension/storage/metadata.yaml

- add new metadata.yaml file to `extension/xextension/storage` and add @swiatekm as codeowner there
- remove @swiatekm from metadata.yaml file at `extension/xextension`
- regenerate codeowners
Fixes #12382

[chore] fix the metadata of extension/xextension/storage

---

confmap/provider/envprovider/provider.go

The existing link 404s, this updates it to the correct URL.

[chore][envprovider] Fix OTel doc link

---

cmd/otelcorecol/go.mod
internal/e2e/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
service/go.mod

pin service/hostcapabilities to existing pseudoversion prior to publishing v0.121.0
Fixes #12462
none, gomod version updated only
none, no change to API or user

[chore] update service/hostcapabilities to pseudoversion

---

cmd/otelcorecol/go.mod
config/configauth/go.mod
config/configgrpc/go.mod
config/confighttp/go.mod
config/confighttp/xconfighttp/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/auth/authtest/go.mod
extension/auth/go.mod
extension/extensionauth/extensionauthtest/go.mod
extension/zpagesextension/go.mod
internal/e2e/go.mod
receiver/otlpreceiver/go.mod
service/go.mod

pins newly created modules to existing version
Fixes #12520, relates to #12462
existing testing framework
none, no api or user-facing changes

[chore] pin extensionauth and extensionauthtest to published version

---

.chloggen/fix-12298.yaml
cmd/mdatagen/internal/templates/component_test.go.tmpl
cmd/mdatagen/internal/templates/telemetrytest.go.tmpl
cmd/mdatagen/internal/templates/telemetrytest_test.go.tmpl

Fixes #12298
Inspired by https://github.com/open-telemetry/opentelemetry-collector/pull/12477, but looks like that PR is hard to pass queue merge.

[cmd/mdatagen] fix #12298 unit tests failures

---

exporter/exporterhelper/logs_batch.go

**Before:**
```
BenchmarkSplittingBasedOnItemCountManyLogsSlightlyAboveLimit
BenchmarkSplittingBasedOnItemCountManyLogsSlightlyAboveLimit-12    	      50	  23387806 ns/op	43531234 B/op	  700471 allocs/op
BenchmarkSplittingBasedOnByteSizeManyLogsSlightlyAboveLimit
BenchmarkSplittingBasedOnByteSizeManyLogsSlightlyAboveLimit-12    	      30	  38350051 ns/op	43616507 B/op	  702427 allocs/op
```
**After:**
```
BenchmarkSplittingBasedOnItemCountManyLogsSlightlyAboveLimit
BenchmarkSplittingBasedOnItemCountManyLogsSlightlyAboveLimit-12    	      51	  23075717 ns/op	43531254 B/op	  700472 allocs/op
BenchmarkSplittingBasedOnByteSizeManyLogsSlightlyAboveLimit
BenchmarkSplittingBasedOnByteSizeManyLogsSlightlyAboveLimit-12    	      36	  32852065 ns/op	43601205 B/op	  702094 allocs/op
```

[chore] Improve logs bytes batch

---

exporter/exporterhelper/internal/sizer/logs_sizer.go
exporter/exporterhelper/internal/sizer/logs_sizer_test.go
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go

Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/12546

[chore] Fix correct counting the cached size and capacity left

---

cmd/otelcorecol/go.mod
internal/e2e/go.mod
receiver/otlpreceiver/go.mod
scraper/scraperhelper/go.mod

This will make updating contrib easier.

[chore] update receiverhelper to main

---

exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queue_sender_test.go

Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/12689

[chore] Extract the QueueBatch logic from the old QueueSender

---

exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queuebatch/config.go
exporter/exporterhelper/internal/queuebatch/default_batcher.go
exporter/exporterhelper/internal/queuebatch/default_batcher_test.go
exporter/exporterhelper/internal/queuebatch/queue_batch.go

This functionality is not yet exposed to the users, in next PRs will be.

[chore] Add ability to configure sizer for default batcher

---

cmd/mdatagen/go.mod
cmd/otelcorecol/go.mod
exporter/debugexporter/go.mod
exporter/exporterhelper/xexporterhelper/go.mod
exporter/exportertest/go.mod
exporter/go.mod
exporter/nopexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
exporter/xexporter/go.mod
internal/e2e/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
processor/batchprocessor/go.mod
processor/memorylimiterprocessor/go.mod
processor/processorhelper/go.mod
processor/processorhelper/xprocessorhelper/go.mod
processor/processortest/go.mod
processor/xprocessor/go.mod
service/go.mod

Fixes open-telemetry/opentelemetry-collector-contrib#38850

[chore] Bump pseudoversions for processor and exporter modules

---

exporter/exporterhelper/internal/base_exporter.go

No changelog needed since it's not released yet

[chore] Mark the new batcher config as mutating as well

---

confmap/confmap_test.go
confmap/internal/e2e/fuzz_test.go
confmap/internal/e2e/types_test.go
confmap/resolver_test.go

A simple refactoring to unexport structs used in testing.

[chore] unexport test structs

---

exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/xexporterhelper/profiles.go
exporter/exporterhelper/xexporterhelper/profiles_test.go

[chore] Deprecate NewProfilesRequestExporter

---

cmd/builder/README.md

Fix https://github.com/open-telemetry/opentelemetry-collector-releases/issues/911
Fixes documentation issue where ocb does not respect a default config file (needs to be specified via `--config`
Fixes [#911](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/911)
None, doc only
README.md

[chore] [cmd/builder] update README.md

---

cmd/mdatagen/internal/command_test.go
cmd/mdatagen/internal/templates/metrics.go.tmpl
cmd/mdatagen/internal/templates/telemetry.go.tmpl
cmd/mdatagen/internal/templates/telemetrytest.go.tmpl
cmd/mdatagen/internal/templates/telemetrytest_test.go.tmpl

fix imports conditions and indentation

[chore][mdatagen] fix imports conditions and indentation

---

config/confighttp/client_middleware_test.go
extension/extensionmiddleware/extensionmiddlewaretest/nop.go
extension/extensionmiddleware/extensionmiddlewaretest/nop_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/pull/12845#discussion_r2051079454

[chore] extensionmiddlewaretest HTTPClientFunc renamed RoundTripperFunc

---

exporter/exporterhelper/README.md

Fix typos in the exporter/exporterhelper README

---

.chloggen/fix_generated_logs_import.yaml
cmd/mdatagen/internal/templates/logs_test.go.tmpl

Adds the missing dependencies into the auto generated files.
Fixes # https://github.com/open-telemetry/opentelemetry-collector/issues/12907

fix: add missing imports

---

.chloggen/tpm-test-darwin.yaml
config/configtls/tpm_test.go

Do not run TPM test macos/darwin

---

docs/release.md

Updates release guidelines to reflect #12837

[chore] Specify that the merge freeze also applies to update-otel

---

.chloggen/metadata-events-func.yaml
cmd/mdatagen/internal/loader_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_config.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_logs.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_logs_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/testdata/config.yaml
cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/internal/templates/config.go.tmpl
cmd/mdatagen/internal/templates/logs.go.tmpl
cmd/mdatagen/internal/templates/logs_test.go.tmpl
cmd/mdatagen/internal/templates/testdata/config.yaml.tmpl
receiver/nopreceiver/internal/metadata/generated_logs.go
receiver/otlpreceiver/internal/metadata/generated_logs.go

Add functions for processing structured events
Part of #12571 
Added
Added

[mdatagen] Add functions for processing structured events

---

exporter/exporterhelper/internal/queuebatch/memory_queue_test.go

Fixes http://github.com/open-telemetry/opentelemetry-collector/issues/13004

[chore] Fix BenchmarkMemoryQueueWaitForResult test

---

docs/component-stability.md

This updates the stability requirements to require certain benchmarking, testing and documentation to ensure scalability, resiliency and performance expectations are documented at a minimum level.
To operationalize this, I will work on:
- Adding automated context propagation tests for components for which it is easy to do so (connectors and processors)
- Adding a new section to the table with a link to the latest benchmarking results.
Fixes #11866
Fixes #11868
Fixes #11593

[chore] Document scalability, performance and resiliency requirements for stable components

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
extension/memorylimiterextension/go.mod
extension/memorylimiterextension/go.sum
internal/e2e/go.mod
internal/e2e/go.sum
internal/memorylimiter/go.mod
internal/memorylimiter/go.sum
otelcol/go.mod
otelcol/go.sum
otelcol/otelcoltest/go.mod
otelcol/otelcoltest/go.sum
processor/memorylimiterprocessor/go.mod
processor/memorylimiterprocessor/go.sum
service/go.mod
service/go.sum

To fix the build on darwin
The same as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40011

[chore] Update github.com/ebitengine/purego to v0.8.3

---

.github/workflows/utils/cspell.json

to resolve https://github.com/open-telemetry/opentelemetry-collector/actions/runs/14986150747/job/42100355298?pr=13026

[chore] Add tlsconfig to the spell check allowlist

---

.chloggen/mdatagen-events-doc.yaml
cmd/mdatagen/internal/command.go
cmd/mdatagen/internal/command_test.go
cmd/mdatagen/internal/samplereceiver/documentation.md
cmd/mdatagen/internal/templates/documentation.md.tmpl
cmd/mdatagen/internal/testdata/events/basic_event.yaml

Add events in generated documentation
Part of #12571 
n/a
Added

[mdatagen] Add events in generated documentation

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
extension/memorylimiterextension/go.mod
extension/memorylimiterextension/go.sum
internal/e2e/go.mod
internal/e2e/go.sum
internal/memorylimiter/go.mod
internal/memorylimiter/go.sum
otelcol/go.mod
otelcol/go.sum
otelcol/otelcoltest/go.mod
otelcol/otelcoltest/go.sum
processor/memorylimiterprocessor/go.mod
processor/memorylimiterprocessor/go.sum
service/go.mod
service/go.sum

include latest updates to purego that fix MacOS go test -race failure in various packages
Fixes #13021
`make all`
none, no change to users or API

[chore] pin github.com/ebitengine/purego to @a52bc8357ac9

---

cmd/mdatagen/internal/loader_test.go
cmd/mdatagen/internal/sampleconnector/documentation.md
cmd/mdatagen/internal/sampleconnector/metadata.yaml
cmd/mdatagen/internal/samplereceiver/documentation.md
cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/internal/samplescraper/documentation.md
cmd/mdatagen/internal/samplescraper/metadata.yaml

Remove duplicated "will be"s.
n/a
n/a
n/a

[chore] Remove duplicated 'will be's

---

cmd/otelcorecol/go.mod
internal/e2e/go.mod
receiver/otlpreceiver/go.mod

Uses valid pseudoversion so that contrib update-otel works

[chore] Use pseudoversions for configoptional

---

.github/workflows/api-compatibility.yml
.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test-windows.yaml
.github/workflows/build-and-test.yml
.github/workflows/builder-integration-test.yaml
.github/workflows/changelog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/contrib-tests.yml
.github/workflows/perf.yml
.github/workflows/prepare-release.yml
.github/workflows/release-branch.yml
.github/workflows/tidy-dependencies.yml

Allows us to move the other deps forward

[chore] revert change to go version

---

config/configoptional/optional.go

Use flavor instead of `hasValue` and `notNone`
Updates #13181 using https://github.com/open-telemetry/opentelemetry-collector/pull/13168#discussion_r2137494222

[chore][configoptional] Use flavor for indicating internal state

---

pdata/internal/cmd/pdatagen/internal/base_fields.go
pdata/internal/cmd/pdatagen/internal/base_slices.go
pdata/internal/cmd/pdatagen/internal/base_structs.go
pdata/internal/cmd/pdatagen/internal/templates.go

Reduce code duplication and move all string generation to templates.

[chore] [pdatagen] Simplify and consolidate generation of small parts

---

cmd/mdatagen/internal/loader_test.go
cmd/mdatagen/internal/metadata_test.go
confmap/confmap_test.go

Renovate/go GitHub.com go viper mapstructure v2 vulnerability

---

cmd/mdatagen/internal/loader_test.go
cmd/mdatagen/internal/metadata_test.go
confmap/confmap_test.go
confmap/internal/e2e/types_test.go
internal/memorylimiter/config_test.go
otelcol/internal/configunmarshaler/configs_test.go
otelcol/unmarshaler_test.go

Fix tests caused by error message changes

---

README.md
docs/release.md

Thanks for all your work @dmathieu!

promote dmathieu to approver

---

.chloggen/enable-sizer.yaml
exporter/exporterhelper/internal/queuebatch/config.go
exporter/exporterhelper/internal/queuebatch/config_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12881

[exporterhelper] Enable items and bytes sizers for persistent queue

---

docs/release.md

Discussed in stability working group.
I will be on vacation the week I was scheduled.

Swap 7/14 and 7/28 releases with mx-psi

---

exporter/exporterhelper/internal/queue/obs_queue.go
exporter/exporterhelper/internal/queue/obs_queue_test.go
exporter/exporterhelper/internal/queue/queue.go
exporter/exporterhelper/internal/queuebatch/disabled_batcher_test.go
exporter/exporterhelper/internal/queuebatch/queue_batch.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/13077

[chore] Move obs_queue to the internal/queue package

---

.chloggen/support-batch-sizer.yaml
exporter/exporterhelper/internal/queuebatch/batcher.go
exporter/exporterhelper/internal/queuebatch/config.go
exporter/exporterhelper/internal/queuebatch/config_test.go
exporter/exporterhelper/internal/queuebatch/multi_batcher.go
exporter/exporterhelper/internal/queuebatch/multi_batcher_test.go
exporter/exporterhelper/internal/queuebatch/partition_batcher.go
exporter/exporterhelper/internal/queuebatch/partition_batcher_test.go
exporter/exporterhelper/internal/queuebatch/queue_batch.go
exporter/exporterhelper/internal/queuebatch/queue_batch_test.go
exporter/go.mod
exporter/otlpexporter/config_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/13313

Add suppport to configure a different Sizer for the batcher than the queue

---

exporter/exporterhelper/README.md

Follow-up for https://github.com/open-telemetry/opentelemetry-collector/pull/13362

[chore] Add docs for `sending_queue::batch::sizer` option

---

.github/workflows/spell-check.yaml
.github/workflows/utils/cspell.json

fixes #13394
Verified in https://github.com/cuichenli/opentelemetry-collector/actions/runs/16309020726/job/46060816564

[chore] add cspell check file pattern for .chloggen 

---

Makefile

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/12747
No changelog because this is not the rule used for official binaries, but only for local tests.
Fixes #

[chore] build otelcorecol with grpcnotrace to remove one usage of text/templates

---

.chloggen/mx-psi_bump-prometheus-0.59.1.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
internal/e2e/go.mod
internal/e2e/go.sum
otelcol/go.mod
otelcol/go.sum
otelcol/otelcoltest/go.mod
otelcol/otelcoltest/go.sum
service/go.mod
service/go.sum

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/13381
Relates to https://github.com/open-telemetry/opentelemetry-go/issues/7039

[service] Bump otel-go Prometheus module to v0.59.1

---

pdata/internal/json/iterator_test.go
pdata/internal/json/stream.go
pdata/internal/json/stream_test.go

No changelog because this bug was not released.

[chore] Ensure that Inf is converted as Infinity

---

.github/workflows/builder-snapshot.yaml

Bumps goreleaser version
I am not sure how, but Fixes #13497

[chore][builder-snapshot.yaml] Bump goreleaser version

---

.golangci.yml

Enables and fixes [asasalint](https://golangci-lint.run/usage/linters/#asasalint) linter

[chore]: enable asasalint linter

---

.golangci.yml

Enables and fixes [decorder](https://golangci-lint.run/usage/linters/#decorder) linter

[chore]: enable decorder linter

---

.chloggen/move_snappy_compression_beta.yaml
config/confighttp/compression.go
config/confighttp/compression_test.go

Move the feature gate `confighttp.framedSnappy` to beta.

[confighttp] Move `confighttp.framedSnappy` feature gate to beta.

---

extension/README.md

Update supported service extensions in extension/README.md

---

service/telemetry/config_test.go
service/telemetry/metrics_test.go
service/telemetry/testdata/config_invalid_metrics_empty_readers.yaml
service/telemetry/testdata/config_invalid_metrics_views_feature_gate.yaml
service/telemetry/testdata/config_invalid_metrics_views_level.yaml
service/telemetry/testdata/config_invalid_unknown_field.yaml
service/telemetry/testdata/config_logs.yaml
service/telemetry/testdata/config_metrics_empty_readers.yaml
service/telemetry/tracer_test.go

Improve coverage of config validation, TracerProvider creation, and trace context propagator configuration.
Simplify some other tests.
N/A
N/A
N/A

[chore] service/telemetry: improve test coverage

---

internal/memorylimiter/memorylimiter.go

[chore] fix a few comments

---

component/componenttest/nop_host.go

Update godoc comments on nopHost.
Good to do before https://github.com/open-telemetry/opentelemetry-collector/issues/13490.

[chore][componenttest] Update nophost godoc

---

config/configgrpc/configgrpc.go
config/configgrpc/configgrpc_test.go

Changes receiver variable names to be abbreviations for the current struct names.

[chore][configgrpc] Fix receiver variable names

---

.github/actionlint.yaml

Reverts open-telemetry/opentelemetry-collector#13658
See #13659 - the PR was not actually exercising the action.

Revert "[chore] remove all ignore statements for actionlint"

---

pdata/internal/wrapper_value.go
pdata/internal/wrapper_value_test.go
pdata/pcommon/map.go
pdata/pcommon/value.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/13631

[chore] Add manual AnyValue unmarshal to allow using memory pools

---

exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/queuebatch/queue_batch.go

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/13631

[chore] Fix ReferenceCounter setting passing to the queue

---

service/extensions/extensions.go
service/internal/graph/graph_test.go
service/internal/graph/lifecycle_test.go
service/internal/status/nop.go
service/internal/status/nop_test.go

This is just moving an internal package around, as a side effect of #13573

[chore] refactor statustest, fold into status

---

.github/ISSUE_TEMPLATE/feature_request.yaml

[chore] Fix issue template

---

exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/base_exporter_test.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/queuebatch/queue_batch.go
exporter/exporterhelper/internal/queuebatch/queue_batch_test.go
exporter/exporterhelper/queue_batch.go

This will help avoiding mistakes like https://github.com/open-telemetry/opentelemetry-collector/pull/13699

[chore] Remove internal duplicate definition of QueueBatchSettings

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
internal/e2e/go.mod
internal/e2e/go.sum
internal/e2e/metric_stability_test.go
otelcol/go.mod
otelcol/go.sum
otelcol/otelcoltest/go.mod
otelcol/otelcoltest/go.sum
service/go.mod
service/go.sum
service/service_test.go
service/telemetry/otelconftelemetry/metrics_test.go

Reverts open-telemetry/opentelemetry-collector#13750
See discussion at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42513#issuecomment-3258074082 for context

Revert "Update module github.com/prometheus/common to v0.66.0"

---

.chloggen/mx-psi_stabilize-exporter.yaml
versions.yaml

Stabilizes module `exporter`.
Follows #13729
Fixes #12978

[exporter] Stabilize module exporter

---

.chloggen/profiles-otlp-1-8-0.yaml
internal/cmd/pdatagen/internal/pdata/pprofile_package.go
pdata/internal/generated_wrapper_location.go
pdata/internal/generated_wrapper_location_test.go
pdata/internal/generated_wrapper_stack.go
pdata/internal/generated_wrapper_stack_test.go

Fix `protoID`s that were changed with breaking changes of the Profiling protocol and were missed in the initial change #13758.

fix pprofile protoIDs

---

.chloggen/mx-psi_mark-configauth-as-1.0.yaml
versions.yaml

Marks `configauth` module as 1.0
Fixes #9476

[configauth] Mark module as 1.0
