open-telemetry/opentelemetry-collector

- docs/release.md
> Update release schedule

- docs/processing.md
Removes the python-like syntax examples.  Changes language to be clear functions only work one one signal at a time.
Related to #5395
> [Telemetry Query Language] Updated function signal expectations

- CHANGELOG.md
- config/moved_service.go
- service/collector_test.go
- service/telemetry.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/5398
This adds a sub-section in the `service.telemetry` config section where any Resource attributes can be specified. All specified attributes will included as own metrics labels.
If `service.instance.id` is not specified it will be auto-generated. Previously `service.instance.id` was always auto-generated, so the default of the new behavior matches the old behavior.
For example we can have the following in the config:
```yaml
service:
telemetry:
resource:
service.instance.id: 01G3EN4NW306AFVGQT5ZYC0GEK
service.namespace: onlineshop
deployment.environment: production
```
> Allow specifying Collector's own Resource in the config

- CHANGELOG.md
- component/extension.go
This resolved the issue#5437, and better align with the names of following types from package **component** : 
ExporterCreateDefaultConfigFunc
ProcessorCreateDefaultConfigFunc
ReceiverCreateDefaultConfigFunc
ExtensionDefaultConfigFunc
> ExtensionDefaultConfigFunc should be ExtensionCreateDefaultConfigFunc

- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/producer_consumer_queue.go
> [exporterhelper] Remove unused function from the internal interface ProducerConsumerQueue

- CHANGELOG.md
- confmap/README.md
- confmap/confmap_test.go
- confmap/resolver.go
- confmap/resolver_test.go
- service/config_provider.go
The reason to do this is to allow alternative implementation of the service.ConfigProvider to re-use the resolver logic,
also to create an independent "confmap.Conf" resolver for other services/binaries to use.
> Move service.mapResolver to confmap.Resolver

- processor/batchprocessor/batch_processor.go
Split from https://github.com/open-telemetry/opentelemetry-collector/pull/5461 
> Remove unused func from internal interface batch

- CHANGELOG.md
- config/moved_configmap.go
- confmap/confmap_test.go
- confmap/provider.go
- confmap/provider/envprovider/provider.go
- confmap/provider/internal/provider.go
- confmap/provider_test.go
- confmap/resolver_test.go
It is ok to change NewRetrievedFromMap to NewRetrieved since it was just moved, not yet released. This is a step towards supporting providing any value type.
> Replace NewRetrievedFromMap with NewRetrieved

- .github/workflows/build-and-test.yml
- CHANGELOG.md
Added linux arm to "cross-build-collector" matrix in `build-ant-test.yml` action for CI.
This will allow adding release for armv7 to dockerhub so the collector can run on raspberry pi.
This architecture is already tested [in contrib CI](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6297dffe6a7728d33715e8189bbc75e82a48ddc4/.github/workflows/build-and-test.yml#L288).
See full discussion [here](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/105). Thank you @mx-psi for the help with this :)
**Testing:**
This PR invokes more tests in CI
> Add linux-arm architecture to cross build tests in CI

- confmap/confmap_test.go
- confmap/resolver_test.go
> Fix small nits in confmap tests

- examples/local/otel-config.yaml
Fix the format error of configuration file in local examples, the right format can be saw in https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md.
> fix format error of config file for otel local example

- service/host.go
- service/internal/extensions/extensions.go
- service/internal/extensions/extensions_test.go
- service/service.go
This PR also remove the use of the deprecated `config.Config` in the extension builder package.
> Cleanup extension builder, avoid exposing private members

- service/README.md
This explains only how to provide the configuration via the `--config` file, after #4742 will update the embedded values option.
> Add readme about how to provide configuration to the collector

- internal/testcomponents/example_receiver.go
- receiver/otlpreceiver/factory.go
> fix some typos in comments

- service/collector_windows.go
- service/collector_windows_test.go
- service/command.go
- service/flags.go
Because we are not cleaning up the os.Args the NewCommand tests which are also parsing the flags (via os.Args) set the config flag even if that was not expected.
> Fix collector tests on windows. The locations gets set in a different test.

- CHANGELOG.md
- service/service.go
Fixing a bug - Removes a repeated call to shut down extensions introduced in 1aa0e5ab3667721f282b557346779cb4ebec4903
> Ensure extensions are only shut down once

- internal/testcomponents/example_exporter.go
- internal/testcomponents/example_exporter_test.go
- internal/testcomponents/example_factories.go
- internal/testcomponents/example_processor.go
- internal/testcomponents/example_processor_test.go
- internal/testcomponents/example_receiver.go
- service/internal/builder/exporters_builder_test.go
- service/internal/builder/pipelines_builder_test.go
- service/internal/builder/receivers_builder_test.go
* Expose example processor to allow start/shutdown tests.
> Cleanup internal/testcomponents

- service/host.go
- service/internal/extensions/extensions.go
- service/internal/extensions/extensions_test.go
- service/service.go
- service/zpages.go
> Move zpages logic for extension into the extension builder

- README.md
As per the discussion at SIG meeting on June 15th, adding a definition for unmaintained components.
> [docs] add definition for unmaintained

- internal/testutil/testutil.go
> testutil: Exclude port ranges for both TCP and UDP

- service/host.go
- service/internal/pipelines/pipelines.go
- service/service.go
- service/zpages.go
> Extract builder for pipelines components into one struct

- README.md
Thanks for your contributions @alolita @punya @flands!
Please provide feedback here if you have bandwidth to continue triaging for the collector/collector-contrib repositories.
> [docs] move current triagers to emeritus

- service/internal/builder/capabilities.go
- service/internal/builder/capabilities_test.go
- service/internal/builder/pipelines_builder.go
> pipeline/builder: add tests for capabilities wrappers

- service/flags.go
> chore: remove double space

- docs/release.md
**Description:** [link](https://docs.github.com/en/github/authenticating-to-github/signing-commits) is being redirected to [new-link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)
**Documentation:** updated the link so automated testing will not fail for deadlinks.
> fixed link in release.md being redirected

- CHANGELOG.md
- config/configtls/README.md
- config/configtls/configtls.go
- config/configtls/configtls_test.go
**Description:** Fixing a bug, default TLS version and description does not match
**Link to tracking Issue:** #5430
> Fixing incorrect default TLS min and TLS max versions

- CHANGELOG.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/otlphttpexporter/otlp.go
Fix #5061
change httpconfig.HTTPClientSettings.ToClient to use component.Host as input parameters
#5061
> change HTTPClientSettings.ToClient to use component.Host as input 

- CHANGELOG.md
- service/collector.go
- service/collector_test.go
- service/config_test.go
- service/service.go
- service/service_test.go
- service/settings.go
- service/telemetry.go
The problem was that the MetricProvider is initialized into the "service.telemetry.MetricProvider" after components were created, so all components will get a no-op implementation even if the feature gate is enabled. This change was not a trivial change because the process telemetry initialization requires the ballast size, which is available after the extensions are initialized, because of that I split the initialization of the MetricProvider/oc.Registry from the initialization of the process telemetry.
> Fix initialization of the MetricProvider

- service/collector.go
- service/config_provider.go
- service/internal/pipelines/pipelines.go
> fix simple typos

- CHANGELOG.md
- component/component.go
- component/componenttest/nop_exporter.go
- component/componenttest/nop_processor.go
- component/componenttest/nop_receiver.go
- component/exporter.go
- component/exporter_test.go
- component/processor.go
- component/processor_test.go
- component/receiver.go
- component/receiver_test.go
- exporter/loggingexporter/factory.go
- exporter/otlpexporter/factory.go
- exporter/otlphttpexporter/factory.go
- internal/testcomponents/example_exporter.go
- internal/testcomponents/example_processor.go
- internal/testcomponents/example_receiver.go
- processor/batchprocessor/factory.go
- processor/memorylimiterprocessor/factory.go
- receiver/otlpreceiver/factory.go
- service/internal/components/constants.go
- service/internal/pipelines/pipelines.go
- service/internal/pipelines/pipelines_test.go
The following allows the setting of a stability level on the factory. This will let us consolidate warnings across all components to notify users of deprecated, unmaintained components.
> add stability level to component factory

- docs/release.md
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11843
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5631
> [chore] update contrib repo changelog procedure

- CHANGELOG.md
- service/internal/pipelines/pipelines.go
- service/internal/pipelines/pipelines_test.go
This is option 1 of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12104
This gives component owners more time to set the stability level of the components.
> Set log level for `undefined` stability level to debug

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- examples/k8s/otel-config.yaml
- versions.yaml
Steps performed:
* Update CHANGELOG.md file and rename the Unreleased section to the new release name. Add a new unreleased section at top. Use commit history feature to get the list of commits since the last release to help understand what should be in the release notes, e.g.: https://github.com/open-telemetry/opentelemetry-collector/compare/v0.44.0...main.
* Use multimod to update the version of the collector package
* Update [versions.yaml](https://github.com/open-telemetry/opentelemetry-collector/blob/main/versions.yaml) and commit it locally
* Run `make multimod-prerelease` (it might fail if you didn't commit the change above)
* Update the collector version in the collector builder to the new release in `./cmd/builder/internal/builder/config.go`.
* Update the collector version in the …
> Prepare v0.55.0 release

- CHANGELOG.md
- service/command.go
- service/featuregate/gates.go
- service/featuregate/gates_test.go
Enhance registry to support failing on unregistered featuregate
fix #5656
> failed on unregistered featuregate

- CHANGELOG.md
- client/client.go
- client/client_test.go
Before this change, users would make references to headers such as "authorization" and "X-CloudFront-Viewer-Latitude", which would potentially fail, as they would be stored in the context as "X-Cloudfront-Viewer-Latitude" or "Authorization".
This PR changes this behavior, to attempt a case insensitive lookup to the backing map in case the key wasn't found under the requested casing. Under the assumption that the lookup key specified by users won't change, on a subsequent lookup, we proactively copy the value to the looked up key, to make the next lookup faster.
Fixes #5610
Fixes open-telemetry/opentelemetry-collector-contrib#8994
> Change metadata lookup to be case insensitive

- component/component.go
- service/internal/components/components.go
- service/internal/components/components_test.go
- service/internal/pipelines/pipelines.go
- service/internal/pipelines/pipelines_test.go
This change will make the func available for extensions as well.
> add LogMessage and move LogStabilityLevel

- CHANGELOG.md
- exporter/loggingexporter/factory.go
- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
**Description:** Make all messages from logging exporter report at info level.
**Link to tracking Issue:**  https://github.com/open-telemetry/opentelemetry-collector/pull/5677#pullrequestreview-1036046290
cc @tigrannajaryan
> [exporter/logging] Decouple `loglevel` field from level of logged messages

- CHANGELOG.md
- pdata/pcommon/alias.go
Exports `internal.NewSliceFromRaw` to make it easier to make a slice from know values.
#5617
**Testing:**
Ran existing tests
> [pdata] export NewSliceFromRaw

- CHANGELOG.md
- exporter/loggingexporter/factory.go
Build the logger on the logging exporter's logger from the one on `TelemetrySettings`, so that the logger honors the configuration settings on `telemetry::logs` and the configuration options on `CollectorSettings.LoggingOptions`.
Depends on #5678
**Link to tracking Issue:** Fixes #5652
**Documentation:** Documented the feature gate.
> [exporter/logging] Build exporter's logger from service's logger

- Makefile
- docs/release.md
make prepare-release does the following:
- checks the local repository is clean
- search/replace PREVIOUS_VERSION with RELEASE_CANDIDATE
- runs make genotelcorecol
- creates a commit on a new branch
- runs make multimod-prerelease
- commits the changes to the branch
- creates a PR
> add prepare-release make target

- .github/workflows/changelog.yml
- .github/workflows/scripts/dependabot-pr.sh
Add a check in the changelog job to skip the job if the title of the PR contains [chore]. This makes it possible for a user who's change doesn't require a changelog entry and doesn't have write access to the repository to skip this check.
For now I've left the check for the "Skip Changelog" label as well, in the future, this should be removed and the label can be removed altogether.
> skip changelog for [chore] prs

- .golangci.yml
Disabling G112 until https://github.com/open-telemetry/opentelemetry-collector/issues/5699 has been addressed.
> [ci] disable G112 to unblock CI

- cmd/otelcorecol/go.mod
- cmd/otelcorecol/go.sum
- go.mod
- go.sum
- pdata/go.mod
- pdata/go.sum
Bump google.golang.org/grpc from 1.47.0 to 1.48.0 in /pdata
Bump google.golang.org/grpc from 1.47.0 to 1.48.0
Bump github.com/klauspost/compress from 1.15.7 to 1.15.8
Bump github.com/prometheus/common from 0.35.0 to 0.37.0
> [chore] dependabot updates Mon Jul 18

- CONTRIBUTING.md
Adds component context including references to more detailed documentation and tutorial.
This PR improves the usability around the process of creating a component for new users.
Partial #5675
> [docs] Add component overview to contributing guide

- CHANGELOG.md
Update Chang log.  Add func `pdata.Remove`, which is the replacement for removed func `pdata.Delete`.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/pull/5307
**Testing:** NA
**Documentation:** NA
> Add replacement for removed func`pdata.Delete` in change log

- CHANGELOG.md
- docs/monitoring.md
- exporter/exporterhelper/obsreport.go
- exporter/exporterhelper/queued_retry_experimental.go
- exporter/exporterhelper/queued_retry_inmemory.go
- exporter/exporterhelper/queued_retry_test.go
Fix #4902, add metric otelcol_exporter_queue_capacity
#4902 
**Testing:** 
> add metrics otelcol_exporter_queue_capacity

- CONTRIBUTING.md
Our commit messages often are quite lacking. A typical approach is writing single line commit
messages and pushing multiple such commits to a PR. When commits are squashed the commit
messages are concatenated, and we end up with useless commit messages.
Here is an example of a commit message body (I am omitting the first line and the commit hash
to avoid blaming anyone in particular - we are all guilty):
```
* add docstring
* fix typo
* fix impi
* apply review feedback
```
This is a useless commit message, in fact, it is worse than an empty one.
I tried to keep the added paragraph in the CONTRIBUTING.md short. If you think more details and
convincing is necessary I can make it more elaborate. Note that the text I added doesn't just
call for good commit messages but has some hints about …
> Add guidelines about commit messages and merging/squashing commits

- Makefile
- Makefile.Common
- cmd/builder/Makefile
- cmd/builder/README.md
- cmd/builder/internal/command.go
- cmd/builder/internal/version.go
Update the builder to consistently use "ocb" in the name of the command,
version and configuration file.
This fixes #5581.
**Testing:** 
Manually looked at version output.
None
> Update the builder to use a consistent binary name.

- CHANGELOG.md
- cmd/builder/internal/command.go
If the builder can't load its build configuration file, it logs an error
and continues. This results in building a collector that is not the one
the user specified. Exit with a fatal error instead.
None.
**Testing:** 
```
$ ./builder
2022-07-22T11:32:21.845+1000	INFO	internal/command.go:85	OpenTelemetry Collector distribution builder	{"version": "dev", "date": "unknown"}
2022-07-22T11:32:21.845+1000	FATAL	internal/command.go:93	failed to load config file	{"config-file": "$HOME/.otelcol-builder.yaml", "error": "open $HOME/.otelcol-builder.yaml: no such file or directory"}
go.opentelemetry.io/collector/cmd/builder/internal.initConfig
/Users/jpeach/upstream/opentelemetry/opentelemetry-collector/cmd/builder/internal/command.go:93 …
```
> Fail when the builder can't load its configuration.

- receiver/otlpreceiver/config.md
Unblocks https://github.com/open-telemetry/opentelemetry-collector/pull/5730
> [chore reformat tables in otlpreceiver/config.md

- CHANGELOG.md
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
Collector currently does retries 402 and 413 error code. 413 is the error code for PAYLOAD TOO LARGE
and 402 is for PAYMENT REQUIRED which a user case of this would be when license token is exhausted.
These error code should be treated as permanent error in the Collector so that they won't get retried.
https://github.com/open-telemetry/opentelemetry-collector/issues/5674
**Testing:** 
oltp_test.go
if we currently document http error code behavior, then treating 402 and 413 as permanent failure can be documented
> Add support to handle 402, 413, 414, 431 http error code as permanent errors in OTLP exporter #5674

- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/changelog.yml
- .github/workflows/check-links.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
Description:
This PR uses [workflow concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) to cancel in-progress builds if a new, higher priority workflow is scheduled. This will happen when new code is pushed to a PR.
Some of our workflows trigger on PR and main, and this setting would affect workflows in both situations. If a set of workflows is running on main and another PR is merged and triggers a new set, the original workflows will be canceled. 
Corresponding PR in Contrib: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12564
> [chore] Set PR workflows concurrency

- .github/workflows/check_links_config.json
Updates markdown-link-check config so that is can correctly check `docs.github.com` urls.  See https://github.com/tcort/markdown-link-check/issues/201 for more details on this workaround.
**Testing:**
ran markdown-link-check locally.
```
markdown-link-check ./docs/release.md -c ./.github/workflows/check_links_config.json   
FILE: ./docs/release.md
[✓] #releasing-opentelemetry-collector
[✓] #releasing-opentelemetry-collector-contrib
[✓] #producing-the-artifacts
[✓] https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
[✓] https://github.com/open-telemetry/opentelemetry-collector
[✓] https://github.com/open-telemetry/opentelemetry-collector-contrib
[✓] https://github.com/open-telemetry/opentelemetry-collector-releases
[✓] …
```
> [chore] Update config for docs.github.com urls

- CHANGELOG.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/otlphttpexporter/otlp.go
> move ToClientWithHost to ToClient

- CHANGELOG.md
- pdata/internal/common.go
- pdata/internal/common_test.go
- pdata/internal/metrics.go
- pdata/pcommon/alias.go
> Remove deprecated funcs from pdata related to mutable slices

- .github/workflows/check-links.yaml
Quick PR to closer align Core's checklink workflow with Contribs.  I am hoping it fixes issues like this: https://github.com/open-telemetry/opentelemetry-collector/runs/7452564621?check_suite_focus=true.
> [chore] Update check-links workflow to match contrib logic

- component/component.go
- component/exporter_test.go
- component/processor_test.go
- component/receiver_test.go
* Make the enum values same type as the enum type
* Use config.DataType everywhere
These are non controversial fixes extracted from https://github.com/open-telemetry/opentelemetry-collector/pull/5762
> Small fixes in the new StabilityLevel feature

- CHANGELOG.md
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/queued_retry_experimental.go
- exporter/exporterhelper/queued_retry_experimental_test.go
- exporter/exporterhelper/queued_retry_inmemory.go
This change is part of an effort to enable the persistent queue by default, without requiring the `enable_unstable` tag. Right now, there are minor inconsistencies between the queue behaviours, and this PR removes them. The intent is for enabling the persistent queue in the build by default to not change any behaviour.
More specifically:
* queue names are now consistent, which required a change to a metric label for the persistent queue
* the in-memory queue has the `requeuing` feature, though it's not enabled
* added some missing tests for persistent queue configuration
This was originally part of #5711, which ended up doing too many things at once.
**Testing:**
Added some tests for parts of the persistent queue that weren't originally …
> [exporterhelper] Make the in-memory and persistent queues more consistent

- pdata/internal/metrics.go
Temporary restore deprecated funcs until https://github.com/influxdata/influxdb-observability/pull/107 is merged, to not block the release.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5770
> Restore deprecated funcs still in use in third-party dependencies

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/metrics_structs.go
- pdata/internal/generated_pmetric.go
- pdata/internal/generated_pmetric_test.go
- pdata/internal/metrics.go
- pdata/internal/metrics_test.go
Deprecates `Flags` and `SetFlags` in favor of `FlagsStruct`
#5443
**Testing:**
Unit tests
> [pdata] Deprecate Flags and SetFlags

- pdata/internal/metrics.go
Reverts open-telemetry/opentelemetry-collector#5786
All third-party code has been updated.
> Revert "Restore deprecated funcs still in use in third-party dependencies"

- .github/workflows/build-and-test.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Makefile.Common
- cmd/builder/go.mod
- cmd/builder/internal/builder/main.go
- cmd/builder/internal/builder/templates/go.mod.tmpl
- cmd/otelcorecol/go.mod
- go.mod
- internal/tools/go.mod
- pdata/go.mod
- semconv/go.mod
Updating to the minimum supported version.
Fixes #5794
> update modules to go 1.18

- CHANGELOG.md
- component/component.go
- component/componenttest/nop_extension.go
- component/exporter.go
- component/exporter_test.go
- component/extension.go
- component/extension_test.go
- component/factories_test.go
- component/processor.go
- component/processor_test.go
- component/receiver.go
- component/receiver_test.go
- extension/ballastextension/factory.go
- extension/zpagesextension/factory.go
- service/extensions/extensions_test.go
- service/internal/pipelines/pipelines.go
* Deprecates current `StabilityLevel(config.DataType)` function from the base `Factory` which is not well suited for Extension. 
* Add new specific for each component `Stability` functions.
> Define a new API for components stability level to match extensions as well

- CHANGELOG.md
- cmd/builder/go.mod
- cmd/builder/internal/builder/config.go
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- examples/k8s/otel-config.yaml
- go.mod
- internal/tools/go.mod
- pdata/go.mod
- semconv/go.mod
- versions.yaml
> [chore] prepare release 0.57.2

- CHANGELOG.md
**Description:** Move Go 1.18 changelog entry to unreleased, since this is not included in the 0.57 release
Follow up to #5795
> Fix changelog related to Go 1.18

- CHANGELOG.md
- exporter/exporterhelper/README.md
- exporter/exporterhelper/queued_retry_experimental.go
- exporter/exporterhelper/queued_retry_experimental_test.go
The persistent queue needs a storage client to run. Currently, this simply takes the one storage extension defined, and errors if there are multiple available. This is both restrictive and arbitrary, and mostly works because it's currently unusual for users to define multiple storage extensions.
This change forces the users to explicitly set the storage extension in queue config if they want to use the persistent queue. This setting doubles as both choosing the storage and enabling the persistent queue - when `storage: nil` (the default), we use the in-memory queue, otherwise, we use the persistent queue with the set storage extension.
This was originally discussed in #5711, and it's part of that change. As it's a breaking change, I'd like to do it before we enable the …
> Require the storage to be explicitly set for persistent queue

- service/flags.go
A small fix to the descriptions of flags. In their descriptions, `config` and `set` flags had examples that used only one dash before the flag instead of two, which was a bit misleading.
> [chore] Add missing dashes to descriptions of flags

- CHANGELOG.md
- confmap/README.md
- confmap/provider.go
- confmap/provider/internal/provider.go
- confmap/provider/internal/provider_test.go
- confmap/resolver.go
- confmap/resolver_test.go
- confmap/testdata/expand-with-all-env-with-source.yaml
- confmap/testdata/expand-with-all-env.yaml
- confmap/testdata/expand-with-no-env.yaml
- confmap/testdata/expand-with-partial-env.yaml
Proposal on how we can extend our current config provider to support expanding (including) config "parts". This will fix https://github.com/open-telemetry/opentelemetry-collector/issues/4231 and will fully implement same capabilities as proposed in https://github.com/open-telemetry/opentelemetry-collector/pull/4468.
This design is based on the https://docs.google.com/document/d/1XlDpS8-a4Ds6uoe6C6WgO8mCpDaQNufcHSEmBpiCdI0/edit format which we already support for the "--config" flag.
Extend the capability of a `confmap.Provider` to return a `Provided` value that can encapsulate a `confmap.Conf` or any partial config value (float64/int64/bool/string/map[string]interface{}/[]interface{} where map values or slice values have the same restrictions). The current design allows `recursive` …
> Add support in the confmap.Resolver to expand embedded config URIs inside configuration

- CHANGELOG.md
- exporter/exporterhelper/common.go
- exporter/exporterhelper/obsreport_test.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/obsreporttest_test.go
- processor/memorylimiterprocessor/memorylimiter.go
- processor/memorylimiterprocessor/memorylimiter_test.go
> Deprecate obsreport.[Processor|Exporter]Settings.Level and use MetricsLevel from CreateSettings

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/common_structs.go
- pdata/internal/generated_common.go
- pdata/internal/generated_common_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5817
> Expose Scope attributes in pdata

- confmap/provider.go
> Use pointer for Retrieved.Close, consistency with all the other funcs

- CHANGELOG.md
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
> Add support to handle 404 and 405 http error code in OTLP exporter #5827

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/metrics_structs.go
- pdata/internal/generated_pmetric.go
- pdata/internal/generated_pmetric_test.go
- pdata/internal/metrics.go
- pdata/internal/metrics_test.go
- pdata/pmetric/alias.go
Deprecates `FlagsStruct` in favor of `Flags`
Related to #5443
**Testing:** 
Unit tests
> [pdata] Deprecate FlagsStruct in favor of Flags

- .github/workflows/create-dependabot-pr.yml
The action used the default go installed in the ubuntu container, that won't work moving forward.
This caused the failure here: https://github.com/open-telemetry/opentelemetry-collector/runs/7728159426?check_suite_focus=true#step:3:463
> [chore] update golang used by dependabot pr

- CHANGELOG.md
This feature is for the moment protected by a private variable that cannot be enabled from outside tests, see https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/resolver.go#L42
When will allow this feature to be enabled, then will add the changelog entry in the right version.
> Remove changelog entry since feature is not yet available, also wrong version 

- CHANGELOG.md
- confmap/provider.go
- confmap/provider/envprovider/provider.go
- confmap/provider/fileprovider/provider.go
- confmap/provider/internal/provider.go
- confmap/provider/yamlprovider/provider.go
- confmap/resolver.go
- confmap/resolver_test.go
This change makes implementations cleaner, since they can return `nil, err` in case of an error instead of a zero initialized Retrieved.
This is a breaking change, but there are very very few implementation of the Provider, so it should be safe to just break it.
> Breaking Change: Change confmap.Provider to return pointer to Retrieved.

- CHANGELOG.md
- confmap/confmaptest/configtest.go
- confmap/confmaptest/configtest_test.go
- confmap/confmaptest/testdata/invalid.yaml
- confmap/provider.go
- confmap/provider/envprovider/provider_test.go
- confmap/provider/fileprovider/provider_test.go
- confmap/provider/yamlprovider/provider_test.go
Currently was documented that the format should be compatible with the URI definition (see https://datatracker.ietf.org/doc/html/rfc3986),
but the scheme name restriction was not copied from the RFC, and no tests to enforce. This PR clearly documents the characters allowed in the scheme name and add confmaptest helper func to test for valid scheme names.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5706
> Enforce scheme name restrictions to all confmap.Provider implementations.

- CHANGELOG.md
- pdata/internal/common.go
The limitation that the pcommon.Slice can have only primitives is indeed in the specs, but cannot be enforced in Equal, it has to be enforced in the constructor if anywhere. Logs need this to support any value, so for the moment remove this artificial limitation from Equal func.
> Remove wrong limitation on pcommon.Value.Equal

- .github/workflows/api-compatibility.yml
- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
- confmap/confmaptest/configtest.go
> Upgrade to go1.19 all workflows except testing on go1.18

- CHANGELOG.md
- pdata/internal/metrics.go
- pdata/internal/metrics_test.go
If offering String() on pdata we should do it from the pdata generator not as ad-hoc for some of the hand written structs.
> Deprecate MetricDataPointFlags.String(), no other pdata has this

- exporter/loggingexporter/internal/otlptext/databuffer.go
- pdata/internal/metrics_test.go
> [chore] rename internal funcs which still refer to double histogram

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/log_structs.go
- pdata/internal/generated_plog.go
- pdata/internal/generated_plog_test.go
- pdata/internal/logs.go
- pdata/internal/logs_test.go
Deprecates LogRecord.Flags() and LogRecord.SetFlags() in favor of LogRecord.FlagsStruct()
> Change LogRecordFlags to use same struct concept as MetricDataPointFlags

- service/collector.go
- service/collector_test.go
- service/collector_windows.go
Avoid using directly the signal channel outside of the test and struct itself.
> Add tests for signal closing shutdown

- CHANGELOG.md
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
- exporter/loggingexporter/factory.go
- exporter/otlpexporter/factory.go
- exporter/otlphttpexporter/factory.go
> Deprecate New*ExporterWithContext, update New*Exporter to the new API

- CHANGELOG.md
- obsreport/obsreport_exporter.go
- obsreport/obsreport_processor.go
> Remove deprecated settings from obsreport

- CHANGELOG.md
- component/component.go
- component/componenttest/nop_extension.go
- component/exporter.go
- component/extension.go
- component/extension_test.go
- component/factories_test.go
- component/processor.go
- component/receiver.go
- extension/ballastextension/factory.go
- extension/zpagesextension/factory.go
- service/extensions/extensions_test.go
> Remove deprecated funcs from component

- CHANGELOG.md
- pdata/internal/json/number.go
- pdata/internal/json/number_test.go
- pdata/pmetric/json.go
- pdata/ptrace/json.go
- pdata/ptrace/json_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5312
Also this improves benchmarks since `ReadAny` was doing an allocation, see:
**Before:**
```
/private/var/folders/5c/5p_3jmvd6qx0rsvmb9j7c_s00000gn/T/GoLand/___BenchmarkJSONUnmarshal_in_go_opentelemetry_io_collector_pdata_ptrace.test -test.v -test.paniconexit0 -test.bench ^\QBenchmarkJSONUnmarshal\E$ -test.run ^$
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/pdata/ptrace
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkJSONUnmarshal
BenchmarkJSONUnmarshal-16    	  334974	      3942 ns/op	    4669 B/op	     231 allocs/op
PASS
```
**After:**
```
/private/var/folders/5c/5p_3jmvd6qx0rsvmb9j7c_s00000gn/T/GoLand/___BenchmarkJSONUnmarshal_in_go_opentelemetry_io_collector_pdata_ptrace.test -test.v …
```
> Fix json trace/metrics unmarshaling for numbers

- CHANGELOG.md
- pdata/pmetric/alias.go
They cannot be removed, unless we apply an exception, since the Deprecation was not correctly marked in golang/godoc because of the missing ":".
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5443
> Deprecate for good the FlagsStruct types

- CHANGELOG.md
- pdata/plog/encoding.go
- pdata/plog/pb.go
- pdata/plog/pb_test.go
- pdata/pmetric/encoding.go
- pdata/pmetric/pb.go
- pdata/pmetric/pb_test.go
- pdata/ptrace/encoding.go
- pdata/ptrace/pb.go
- pdata/ptrace/pb_test.go
Proposing adding a new `MarshalerSizer` interface to `ptrace`, `plog`, and `pmetric` packages and alter `NewProtoMarshaler` to return this interface. This allows easy creation of a `Sizer` implementation. Currently the only way to create a sizer for the `pdata` packages is to call `NewProtoMarshaler` function then cast to a `Sizer`. This is not intuitive from an API standpoint that it should be safe to cast a `Marshaler` as a `Sizer`. 
The `MarshalerSizer` interface is a combination of the `Marshaler` and `Sizer` interfaces.
If this is merged I will create a follow up PR to update the Batch Processor to use this rather than casting from a `Marshaler`.
**Link to tracking Issue:** #5920
**Testing:** Updated tests to use the `MarshalSizer` instead of casting.
> Added MarshalerSizer Interface to facilitate creation of Sizer implementations

- CHANGELOG.md
- pdata/internal/json/enum.go
- pdata/internal/json/enum_test.go
- pdata/pmetric/json.go
- pdata/pmetric/json_test.go
- pdata/ptrace/json.go
- pdata/ptrace/json_test.go
> Remove unnecessary duplicate code and allocations for reading enums in JSON

- CHANGELOG.md
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
**Description:** As a follow up to #5929 removed cast to `Sizer` interface in batch processor as this is no longer required with the new `MarshalerSizer` that is returned from `NewProtoMarshaler`
> [processor/batch] Removed casts to Sizer interface in batch processor

- CHANGELOG.md
- pdata/internal/logs.go
- pdata/internal/logs_test.go
- pdata/internal/metrics.go
- pdata/internal/metrics_test.go
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/telemetryquerylanguage/contexts/tqlmetrics/metrics.go#L614
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/metricstransformprocessor/operation_aggregate_labels.go#L196
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/adapter/frompdataconverter.go#L220
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/alibabacloudlogserviceexporter/logsdata_to_logservice.go#L174
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/tencentcloudlogserviceexporter/logsdata_to_logservice.go#L172
> Add an AsRaw func on the flags, lots of places to encode these flags

- CHANGELOG.md
- cmd/builder/internal/command.go
> Mark custom distribution flags as deprecated

- CHANGELOG.md
- pdata/ptrace/json.go
- pdata/ptrace/json_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5312
> otlpjson/trace: skip unknown fields instead of error

- CHANGELOG.md
- pdata/internal/common.go
The method is inconsistent with other Map methods. It's not very useful and can be easily replaced by `Map.Insert(<key>, NewValueEmpty())`. 
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/5953
> [pdata] Deprecate pcommon.Map.InsertNull method

- exporter/loggingexporter/internal/otlptext/logs.go
> Remove usage of deprecated LogRecord.Flags

- cmd/builder/internal/command.go
This is unnecessary because:
1. It happens before flags are loaded, so will initialize things with default values, which already happens during flags initialization. See flags.StringVar for example.
2. The load using posflag provider, as defined right now (with current flags name) produce this config:
```
k := map[string]interface{} {
"config": ""
"description": "Custom OpenTelemetry Collector distribution"
"go": ""
"module": "go.opentelemetry.io/collector/cmd/builder"
"name": "otelcol-custom otelcol-version:0.58.0"
"output-path": "/var/folders/5c/5p_3jmvd6qx0rsvmb9j7c_s00000gn/T/otelcol-distribution1155391158"
"skip-compilation": false
"version": "1.0.0"
}
```
As you can see, this will whole be ignored, since all the configs (except the config flag) are sub-configs under "dist" anyway. …
> Remove unnecessary posflag provider load

- CHANGELOG.md
- exporter/loggingexporter/internal/otlptext/databuffer.go
Added the Scope attributes to be logged in logging exporter
> [loggingexporter] Add InstrumentationLibararyScope attributes

- exporter/loggingexporter/internal/otlptext/databuffer.go
- exporter/loggingexporter/internal/otlptext/logs.go
- exporter/loggingexporter/internal/otlptext/metrics.go
- exporter/loggingexporter/internal/otlptext/traces.go
While working on #5976, I realized that there are some leftover mentions of `labels` in the logging exporter code, and replaced them with `attributes`.
> [loggingexporter] Rename labels to attributes

- CHANGELOG.md
- config/configtls/README.md
- config/configtls/configtls.go
- config/configtls/configtls_test.go
Use TLS 1.2 by default when min_version is not defined. 
TLS 1.0 and 1.1 are widely deprecated. It does not make sense to offer users with an insecure default.
This PR changes the default TLS min_version for both server and client to 1.2. This is reverting part of a recent change: https://github.com/open-telemetry/opentelemetry-collector/pull/5480
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/5627
**Testing:** Unit tests were modified to account for this case.
**Documentation:** Documentation was updated describing the new default.
> Use TLS 1.2 by default when min_version is not defined

- pdata/pcommon/spanid.go
- pdata/pcommon/spanid_test.go
- pdata/pcommon/traceid.go
- pdata/pcommon/traceid_test.go
The breaking change was added, unintentionally in https://github.com/open-telemetry/opentelemetry-collector/pull/5968 
> Revert breaking change to [Trace|Span]ID.HexString()

- pdata/pmetric/metrics.go
The mistake happened in https://github.com/open-telemetry/opentelemetry-collector/pull/5936
> Add back deprecated funcs/types deleted by mistake.

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/metrics_structs.go
- pdata/internal/generated_wrapper_metrics.go
- pdata/plog/log_record_flags.go
- pdata/pmetric/generated_metrics.go
- pdata/pmetric/generated_metrics_test.go
- pdata/pmetric/metric_data_point_flags.go
- pdata/pmetric/metric_data_point_flags_test.go
- pdata/pmetric/metrics.go
> Change MetricDataPointFlags to the new immutable pattern

- CHANGELOG.md
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_test.go
The client passed into `persistentContiguousStorage` was never closed prior. This would caused the underneath file locked forever and collector failing to restart when settings are updated.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/6003
**Testing:** Added unit test on stop
**Documentation:** None needed as fixing bug
> Close persistent storage client on stop

- CHANGELOG.md
> [chore] remove unnecessary character from changelog

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/main.go
- cmd/builder/internal/command.go
**Description:** Add `skip-get-modules` flag to the builder.
Isolated build environments like [Bazel](https://bazel.build/) or some CIs might not have access to the public internet.
These environments have different ways to inject dependencies, and there is no need to get them directly from the internet during the builder execution time.
~~Also, if we skip compilation (an existing feature) and downloading modules (this feature), there is no need for Go binary anymore.~~ Move to a separate PR.
> Add skip-get-modules flag to support isolated envs

- CHANGELOG.md
- pdata/pcommon/common.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5998
> Deprecate all update funcs, easy to replace with Get and mutate result.

- CHANGELOG.md
- pdata/pcommon/common.go
- pdata/pcommon/common_test.go
Remove deprecated `pcommon.Map` methods: `Update`, `Upsert`, `InsertNull`
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/5974
> [pdata] Remove deprecated pcommon.Map methods

- CHANGELOG.md
- pdata/internal/json/attribute.go
- pdata/internal/json/attribute_test.go
- pdata/plog/json.go
- pdata/plog/json_test.go
Description:
Now Traces And Metrics was converted to  jsoniter`, But Logs still uses `jsonpb`.
Unmarshaler with `jsoniter` will skip unknown fields instead of error
Link to tracking Issue: [https://github.com/open-telemetry/opentelemetry-collector/pull/4986 ]
Testing:
unit test. construct a logs message, fill all the fields, use jsonpb marshal to json bytes, use jsoniter unmarshal to struct, test assert there are equal.
> Implement unmarshal Logs with jsoniter 

- CHANGELOG.md
- pdata/plog/encoding.go
- pdata/plog/pb.go
- pdata/pmetric/encoding.go
- pdata/pmetric/pb.go
- pdata/ptrace/encoding.go
- pdata/ptrace/pb.go
In https://github.com/open-telemetry/opentelemetry-collector/pull/5929, the suggestion to have the combined name as "MarshalerSizer" was wrong.
Even the comment https://github.com/open-telemetry/opentelemetry-collector/pull/5929#discussion_r948230586 was wrong since the link is `WriteSeeker`.
> Fix wrong name suggestion made by bogdandrutu

- CHANGELOG.md
- config/common.go
- config/exporter.go
- config/extension.go
- config/processor.go
- config/receiver.go
- confmap/confmap.go
- receiver/otlpreceiver/config.go
This interface is concerned with unmarshalling a `confmap.Conf`, so is arguably more appropriate
in the `confmap` package. More concretely, moving this is necessary to avoid an import cycle as
would be introduced by #6029.
> Deprecate config.Unmarshallable in favor of confmap.Unmarshallable

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/config_test.go
**Description:** Builder skip Go binary validation if not used
As a follow-up on (#6009), when the builder is used with `-skip-compilation` and `-skip-get-modules` flags, it only generates distribution go codes. So there is no need for Go binary.
Isolated build environments like [Bazel](https://bazel.build/) or some CIs can skip passing Go binary to the builder.
> Builder skip Go binary validation if not used

- CHANGELOG.md
- confmap/confmap.go
- confmap/confmap_test.go
This also moves the Unmarshallable interface from `config` to `confmap` in order to avoid
an import cycle. This makes some sense anyways because the interface is concerned
specifically with unmarshalling a confmap.Conf. The config.Unmarshallable interface
is deprecated and changed to an alias of confmap.Unmarshallable.
Rehash of #4879
> [confmap] Add mapstructure hook function for unmarshalling confmap.Conf

- pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
- pdata/pcommon/generated_primitive_slice.go
Follow-up to item 1 in https://github.com/open-telemetry/opentelemetry-collector/pull/5971
> Copying can be done in-place to save allocations.
> [pdata] Use copy instead of manual copying slices.

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/base_fields.go
- pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
- pdata/pcommon/generated_primitive_slice.go
- pdata/pcommon/generated_primitive_slice_test.go
- pdata/pmetric/generated_metrics.go
Follow-up item 3 to https://github.com/open-telemetry/opentelemetry-collector/pull/5971
> Add CopyTo/MoveTo and remove the copy logic from the parent's CopyTo.
> [pdata] Add CopyTo and MoveTo methods to primitive slices

- CHANGELOG.md
- pdata/pcommon/common.go
- pdata/pcommon/common_test.go
- pdata/pmetric/metrics_test.go
Use `New[Slice|Map]().FromRaw()` instead fo consistency with the interface provided by primitive slices.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/6041
> [pdata] Deprecate New[Slice|Map]FromRaw functions

- CHANGELOG.md
- Makefile
- cmd/builder/Makefile
- cmd/builder/internal/command.go
- cmd/builder/internal/config/default.go
- cmd/builder/internal/config/default.yaml
- cmd/builder/test/default.otel.yaml
- cmd/builder/test/test.sh
Embed the build configuration that is used to build otelcorecol into ocb
so that end users can easily generate a useful collector. This makes the
`--config` flag optional again.
None.
**Testing:**
```
$ make ocb
/Library/Developer/CommandLineTools/usr/bin/make -C cmd/builder config
sed '-e/replaces:/,$d' <../otelcorecol/builder-config.yaml > internal/config/default.yaml
/Library/Developer/CommandLineTools/usr/bin/make -C cmd/builder ocb
GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ../../bin/ocb_darwin_arm64 .
$ ./bin/ocb_darwin_arm64
2022-07-26T16:05:06.722+1000	INFO	internal/command.go:91	OpenTelemetry Collector Builder	{"version": "dev", "date": "unknown"}
2022-07-26T16:05:06.722+1000	INFO	internal/command.go:102	Using default build …
```
> Add a default build configuration to ocb.

- pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
- pdata/pcommon/common.go
- pdata/pcommon/generated_primitive_slice.go
> [chore] primitive slice, avoid allocation if enough space

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/config/default.yaml
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- examples/k8s/otel-config.yaml
- versions.yaml
Prepare 0.60.0 release
**Tests**: I opened open-telemetry/opentelemetry-collector-contrib/pull/14120 for double checking that core will work on contrib
**Link to tracking Issue:** Fixes #6069
> [chore] prepare release 0.60.0

- CHANGELOG.md
- pdata/plog/encoding.go
- pdata/pmetric/encoding.go
- pdata/ptrace/encoding.go
> Delete deprecaed MarshalerSizer interfaces

- CHANGELOG.md
- config/common.go
> Delete deprecated config.Unmarshalable interface

- CHANGELOG.md
- pdata/pcommon/common.go
- pdata/pcommon/common_test.go
These methods would be good to expose given that we have it for several other types. They would be pretty useful to replace custom functions in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/telemetryquerylanguage/contexts/internal/tqlcommon/value.go
> [pdata] Expose pcommon.Value.AsRaw/FromRaw methods

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
- pdata/pcommon/generated_primitive_slice.go
- pdata/pcommon/generated_primitive_slice_test.go
Follow-up PR from https://github.com/open-telemetry/opentelemetry-collector/pull/5971:
> No way of increasing the capacity or length. We can discuss about that API.
Given that we have `SetAt` interface not `Append...`, I think it makes sense to have `SetLen`. But I'm open to other suggestions
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6063
cc @bogdandrutu
> [pdata] Add Append and EnsureCapacity methods to primitive slices

- CHANGELOG.md
- pdata/pmetric/metrics.go
> Deprecate pmetric.OptionalType, unused enum type

- CHANGELOG.md
- pdata/plog/logs.go
> Delete deprecated plog.LogRecord.[Set]FlagStruct funcs

- config/configtls/README.md
- README update to remove an unnecessary link to the same document.
- Minor rephrasing.
> [docs] Remove link to itself

- CHANGELOG.md
- pdata/pcommon/common.go
Appeared that we accidentally broke the deprecation rule in https://github.com/open-telemetry/opentelemetry-collector/pull/6088. This PR unblocks core dependency upgrade in contrib
> [pdata] Restore NewValueBytesEmpty that was removed without deprecation

- CHANGELOG.md
- pdata/pcommon/common.go
> Remove pcommon.Immutable*Slice and related funcs

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/base_fields.go
- pdata/pmetric/generated_metrics.go
> Delete deprecated SetBucketCounts and SetExplicitBounds

- docs/release.md
**Description:**  Update release instructions based on my experience on 0.60.0. In particular:
1. Reword the description of what steps are owned by the release manager based on the new template
2. Explicitly note that you have to commit changes to the changelog before running the pre-release step.
3. Add links to issues I always run into.
> [docs] Update release instructions

- .github/workflows/scripts/dependabot-pr.sh
This fixes issues like https://github.com/open-telemetry/opentelemetry-collector/actions/runs/3079821528 where the PR name is too long, same fix already in contrib.
> Fix github dependabot-pr workflow

- CHANGELOG.md
- exporter/loggingexporter/internal/otlptext/databuffer.go
- internal/testdata/metric.go
- pdata/internal/cmd/pdatagen/internal/base_fields.go
- pdata/internal/cmd/pdatagen/internal/metrics_structs.go
- pdata/pmetric/generated_metrics.go
- pdata/pmetric/generated_metrics_test.go
- pdata/pmetric/metrics.go
- pdata/pmetric/metrics_test.go
- processor/batchprocessor/splitmetrics.go
* Dreprecate old APIs, add new APIs without "Data"
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6081
> Replace MetricDataType with MetricType

- docs/processing.md
This is part of the work to rename TQL to OTTL.
> [docs] rename query language to tranformation language

- CHANGELOG.md
- service/collector.go
- service/collector_test.go
- service/telemetry.go
Changed how the `telemetryInitializer` is created. Previously only a single instance of the `telemetryInitializer` was created for a process. The caused an issue if a `Collector` instance was shutdown and a new one was created the new instance would get the global instance that was shutdown as a result of the first Collector instance being shutdown.
The new logic ensures the feature gate is only registered once but a new `telemetryInitializer` instance is created per instance of the collector.
Tangentially related to #5084. 
In that issue the desired design is:
> I think we are going to the direction to follow the language pattern which is after Shutdown you cannot call Run on the same instance, you have to create a new instance.
I believe …
> Changed how the telemetryInitializer is created

- pdata/pcommon/common.go
To address https://github.com/open-telemetry/opentelemetry-collector/pull/6099#discussion_r980621170
> [pdata] Add comment to to Value.SetStr about its naming.

- cmd/builder/go.mod
- cmd/builder/go.sum
- cmd/builder/internal/builder/config_test.go
- cmd/builder/test/test.sh
Drop the integration tests for the builtin builder configuration. We assume that it is a working config because it is generated from with the source tree and should be covered by collector tests. Add a unit test to ensure some basic sanity for the builtin configuration.
**Link to tracking Issue:** This fixes #6076.
**Testing:** Ran unit an integration tests.
**Documentation:**  N/A
> [chore] Drop builtin builder configuration integration tests.

- CONTRIBUTING.md
> [chore] Add language to CONTRIBUTING re: pre-release spec features

- CHANGELOG.md
- pdata/plog/logs.go
- pdata/plog/logs_test.go
- pdata/pmetric/metrics.go
- pdata/pmetric/metrics_test.go
- pdata/ptrace/traces.go
- pdata/ptrace/traces_test.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6154
> Deprecate pdata Clone methods in favor of CopyTo

- CHANGELOG.md
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/otlp.go
- pdata/plog/plogotlp/logs.go
- pdata/pmetric/pmetricotlp/metrics.go
- pdata/ptrace/ptraceotlp/traces.go
- receiver/otlpreceiver/internal/logs/otlp_test.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
- receiver/otlpreceiver/internal/trace/otlp_test.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6156
> [pdata] Rename Client|Server to GRPC[Client|Server]

- CHANGELOG.md
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/otlp_test.go
- pdata/plog/plogotlp/logs.go
- pdata/plog/plogotlp/logs_test.go
- pdata/pmetric/pmetricotlp/metrics.go
- pdata/pmetric/pmetricotlp/metrics_test.go
- pdata/ptrace/ptraceotlp/traces.go
- pdata/ptrace/ptraceotlp/traces_test.go
- receiver/otlpreceiver/internal/logs/otlp_test.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
- receiver/otlpreceiver/internal/trace/otlp_test.go
- receiver/otlpreceiver/otlp.go
`p[log|trace|metric]otlp` packages don't have grpc part in it anymore, so we need to add GRPC part to the related methods. 
This change should've been landed in https://github.com/open-telemetry/opentelemetry-collector/pull/6165
> [pdata] Rename RegiserServer funcs to RegiserGRPCServer

- CHANGELOG.md
- config/configtelemetry/configtelemetry.go
- config/configtelemetry/configtelemetry_test.go
- config/identifiable.go
- config/identifiable_test.go
- confmap/confmap.go
- confmap/confmap_test.go
- confmap/internal/mapstructure/encoder.go
- confmap/internal/mapstructure/encoder_test.go
Add `Marshal` function to `confmap`. Update types implementing `encoding.TextUnmarshaler` to implement `encoding.TextMarshaler` as well. Add a mapstructure encoder that encodes the config provided using the existing mapstructure tags.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/5418
**Testing:** Added unit test to validate the unmarshal/marshal cycle.
> Add config marshaler.

- CHANGELOG.md
- pdata/pcommon/common.go
- pdata/pcommon/common_test.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6201
Deprecate `pcommon.NewValueString` in favor of `pcommon.NewValueStr` for consistency with `pcommon.ValueTypeStr`
> [pdata] Rename pcommon.NewValueString to pcommon.NewValueStr

- CHANGELOG.md
- service/telemetry.go
- service/telemetry_test.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6136
- The default service.name is set to BuildInfo.Command (equals to "otelcol" for this repo).
- The service.name can be overridden by the end user via telemetry config setting.
> Add service.name resource attribute to the collector's own telemetry

- docs/security.md
Add note about CWE-1327 to the security recommendations.
The intention is to link to this section on a warning when users set `0.0.0.0`-like addresses 
**Link to tracking Issue:** Updates #6151
> [docs/security] Add note about CWE-1327

- config/confighttp/confighttp_test.go
Update some tests to bind to localhost instead of 0.0.0.0
> [chore] update tests to bind to localhost

- service/testdata/otelcol-invalid.yaml
- service/testdata/otelcol-invalidprop.yaml
- service/testdata/otelcol-nop.yaml
- service/testdata/otelcol-validprop.yaml
Additional tests were binding telemetry on 0.0.0.0:8888, this change fixes that to bind to localhost instead.
> [chore] more localhost configuration

- CHANGELOG.md
- service/telemetry.go
**Description:** This wraps `prometheus.Registry` with the `otelcol_` prefix and the `service_` attributes as these are not supported directly by the OpenTelemetry Go Prometheus Exporter.
This ensures that metrics exported by otel-go is consistent with the existing opencensus metrics.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/5882
**Testing:** Manual tested by adding a otel-go metric and testing this.
> Add prometheus metric prefix and constant service attributes to otel-go prometheus exporter

- CHANGELOG.md
- pdata/pmetric/metrics.go
- pdata/pmetric/metrics_test.go
> Change AggregationTemporality.String to simpler, easier to read

- CHANGELOG.md
- exporter/loggingexporter/internal/otlptext/databuffer.go
- exporter/loggingexporter/internal/otlptext/databuffer_test.go
- exporter/loggingexporter/internal/otlptext/logs.go
- exporter/loggingexporter/internal/otlptext/logs_test.go
- exporter/loggingexporter/internal/otlptext/testdata/logs/embedded_maps.out
- exporter/loggingexporter/internal/otlptext/testdata/logs/one_record.out
- exporter/loggingexporter/internal/otlptext/testdata/logs/two_records.out
Remove custom rendering for slice and map values and use Value.AsString() instead
Resolves: https://github.com/open-telemetry/opentelemetry-collector/issues/6243
> [exporter/logging] Apply consistent map value rendering

- CHANGELOG.md
- docs/troubleshooting.md
- exporter/loggingexporter/internal/otlptext/databuffer_test.go
- exporter/loggingexporter/internal/otlptext/testdata/logs/embedded_maps.out
- exporter/loggingexporter/internal/otlptext/testdata/logs/one_record.out
- exporter/loggingexporter/internal/otlptext/testdata/logs/two_records.out
- pdata/pcommon/common.go
- pdata/pcommon/common_test.go
Recently we updated all names related to pdata String value. It makes sense to update string returned by Value.String accordingly to avoid discrepancy with other value types
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6249
> [pdata] Update pcommon.ValueType.String() output

- CHANGELOG.md
- config/common.go
- confmap/confmap.go
- confmap/confmap_test.go
- receiver/otlpreceiver/config.go
- service/internal/configunmarshaler/defaultunmarshaler.go
Officially this can be considered breaking change because of a use in a `var foo func(interface{}) error = conf.Unmarshal`, not in a normal calling usage, but this is an edgecase that we can except and move forward with this.
This will allow to add more options to Marshal/Unmarshal in the future.
> Add options to confmap Marshal/Unmarshal, deprecate UnmarshalExact

- CHANGELOG.md
- service/service.go
- service/service_test.go
Fixing a bug - Fixed issue where the `telemetryInitializer` was not cleaned up if `newService` errors after `telemetryInitializer.init` is called. This would cause subsequent calls to new service to error on `telemetryInitializer.init`.
Fixes: #6238 
**Testing:**
- Added a new unit test that fails without new cleanup logic
- Tested with our OPAMP enabled [agent](https://github.com/observIQ/observiq-otel-collector) and [server](https://github.com/observiq/bindplane-op). On reconfigure our agent runs a new instance of the Collector within the agent process. This was exposing the issue when a bad config is sent.
> Fixed issue where telemetryInitializer is not cleaned up when newService errors

- CHANGELOG.md
- pdata/internal/cmd/pdatagen/internal/metrics_structs.go
- pdata/internal/generated_wrapper_metrics.go
- pdata/pmetric/generated_metrics.go
- pdata/pmetric/generated_metrics_test.go
- pdata/pmetric/metrics.go
Rename `pmetric.[New]?ValueAtQuantile[Slice]?` structs and functions to align them with the underlying protobuf messages. It should have `SummaryDataPoint` prefix as they are defined in the scope of `SummaryDataPoint` protobuf message.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6257
> [pdata] Rename ValueAtQuantile to SummaryDataPointValueAtQuantile

- CHANGELOG.md
- exporter/loggingexporter/internal/otlptext/databuffer.go
- internal/testdata/metric.go
- pdata/internal/cmd/pdatagen/internal/base_fields.go
- pdata/pmetric/generated_metrics.go
- pdata/pmetric/generated_metrics_test.go
- pdata/pmetric/metrics.go
- pdata/pmetric/metrics_test.go
For consistency with `pcommon.ValueType`
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6256
> [pdata] Rename enum zero value constants to have `Empty` suffix

- pdata/internal/cmd/pdatagen/internal/base_fields.go
- pdata/internal/cmd/pdatagen/internal/common_structs.go
- pdata/internal/cmd/pdatagen/internal/log_structs.go
- pdata/internal/cmd/pdatagen/internal/metrics_structs.go
- pdata/internal/cmd/pdatagen/internal/resource_structs.go
- pdata/internal/cmd/pdatagen/internal/trace_structs.go
Given the documented naming recommendations for pdata in https://github.com/open-telemetry/opentelemetry-collector/pull/6255, simplify pdatagen to encourage the same naming between pdata and proto fields.
> [pdata] Simplify pdatagen to rely more on the proto naming dependency

- .chloggen/move-tracing-init.yaml
- service/collector.go
- service/internal/grpclog/logger.go
- service/internal/grpclog/logger_test.go
- service/internal/proctelemetry/process_telemetry.go
- service/internal/proctelemetry/process_telemetry_test.go
- service/service.go
- service/telemetry/otel_trace_sampler.go
- service/telemetry/telemetry.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5564
> Start moving telemetry initialization to service/telemetry

- .chloggen/mx-psi_confmap-provider.yaml
- confmap/resolver.go
- confmap/resolver_test.go
Make `confmap.NewResolver` (and therefore `service.NewConfigProvider`) fail fast if there is an URI with an unsupported scheme.
**Link to tracking Issue:** Fixes #6274
> [confmap] Fail fast on unsupported scheme

- confmap/provider/yamlprovider/provider_test.go
- service/README.md
- service/flags.go
- service/flags_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6294
> [chore] document how set flag works, and current limitations

- .chloggen/enumsasints.yaml
- pdata/plog/json.go
- pdata/pmetric/json.go
- pdata/ptrace/json.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6338
> JSON marshaler emits enums as ints per spec reuqirements.

- pdata/README.md
The documentation is intended to summarize all the naming rules followed in pdata module
> [pdata] Add documentation defining naming conventions

- .chloggen/structs.yaml
- config/configgrpc/configgrpc_benchmark_test.go
- exporter/exporterhelper/internal/persistent_storage_test.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/traces.go
- pdata/plog/json.go
- pdata/plog/json_test.go
- pdata/plog/pb.go
- pdata/plog/pb_test.go
- pdata/pmetric/json.go
- pdata/pmetric/json_test.go
- pdata/pmetric/pb.go
- pdata/pmetric/pb_test.go
- pdata/ptrace/json.go
- pdata/ptrace/json_test.go
- pdata/ptrace/pb.go
- pdata/ptrace/pb_test.go
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
- receiver/otlpreceiver/otlp_test.go
The main motivation is because we want to be able to extend these Marshaler/Unmarshaler implementation with possible options.
Because of that we have 2 options: 1. add Option to each New func, OR 2. expose the structs so that later users can configure different options inside these structs, similar with `jsonpb.Marshaler`.
I implemented the version 2 since it is simpler, and less code, and also common in the industry.
> Deprecate New[JSON|Proto][Marshaler|Unmarshale], expose the structs

- .chloggen/grpcclient.yaml
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/otlp.go
- pdata/plog/plogotlp/grpc.go
- pdata/plog/plogotlp/grpc_test.go
- pdata/pmetric/pmetricotlp/grpc.go
- pdata/pmetric/pmetricotlp/grpc_test.go
- pdata/ptrace/ptraceotlp/grpc.go
- pdata/ptrace/ptraceotlp/grpc_test.go
- receiver/otlpreceiver/internal/logs/otlp_test.go
- receiver/otlpreceiver/internal/metrics/otlp_test.go
- receiver/otlpreceiver/internal/trace/otlp_test.go
- receiver/otlpreceiver/otlp_test.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6350
> Deprecate p[trace|metric|log]otlp.NewClient in favor of p[trace|metric|log]otlp.NewGRPCClient

- .chloggen/generatepartialresponse.yaml
- pdata/internal/cmd/pdatagen/internal/base_structs.go
- pdata/internal/cmd/pdatagen/internal/plogotlp_structs.go
- pdata/internal/cmd/pdatagen/internal/pmetricotlp_structs.go
- pdata/internal/cmd/pdatagen/internal/ptraceotlp_structs.go
- pdata/internal/generated_wrapper_logs_otlp.go
- pdata/internal/generated_wrapper_metrics_otlp.go
- pdata/internal/generated_wrapper_traces_otlp.go
- pdata/plog/plogotlp/generated_logs_otlp.go
- pdata/plog/plogotlp/generated_logs_otlp_test.go
- pdata/plog/plogotlp/response.go
- pdata/pmetric/pmetricotlp/generated_metrics_otlp.go
- pdata/pmetric/pmetricotlp/generated_metrics_otlp_test.go
- pdata/pmetric/pmetricotlp/response.go
- pdata/ptrace/ptraceotlp/generated_traces_otlp.go
- pdata/ptrace/ptraceotlp/generated_traces_otlp_test.go
- pdata/ptrace/ptraceotlp/response.go
Rename `p[trace|metric|log]otlp.Export[Trace|Metrics|Logs]PartialSuccess` to `p[trace|metric|log]otlp.ExportPartialSuccess` for simplicity and consistency with Export[Request|Response]
This doesn't need a deprection because `p[trace|metric|log]otlp.Export[Trace|Metrics|Logs]PartialSuccess` is not released yet.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/6365
> [pdata] Rename p[trace|metric|log]otlp.ExportPartialSuccess

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/config_test.go
- cmd/builder/internal/builder/main_test.go
- cmd/builder/internal/command.go
Signed-off-by: sakshi1215 <sakshi.patle121@gmail.com>
Removing setting path in validate
**Link to tracking Issue:** fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6030
> [chore]: dont set path for go in validate

- service/collector_test.go
**Description:** Integration tests failed because`zpages` failed to start (because the port was not available, see https://github.com/open-telemetry/opentelemetry-collector/issues/6323#issuecomment-1279851766 for more context) which led to leak of `telemetryInitializer` resources.  
**Link to tracking Issue:** #6323
> [test] fix flaky telemetry zpages test

- .chloggen/service-cleanup-on-start-error.yaml
- service/collector.go
- service/service.go
- service/service_test.go
**Description:** Same as #6239. Call `service.Shutdown` if `service.Start` call errors in collector. A failed `service.Start` would leave up the `telemetryInitializer` and the next attempt at starting the collector would cause an error as the `telemetryInitializer` didn't clean up global state.
I'm not sure if this interferes with work on #5564. I moved the `service.telemetryInitializer.Shutdown` into `service.Shutdown`. Currently it the `telemetryInitializer` needs to be shutdown separately from the service. This changes makes it so calling `service.Shutdown` ensures all its state is cleaned up.
Fixes: #6352
> Added cleanup if service errors on Start

- obsreport/obsreport_receiver.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/otelprometheuschecker.go
- obsreport/obsreporttest/otelprometheuschecker_test.go
**Description:**  Adds tests for the OTel Go instrumentation in the `obsreport.Receiver` component helper.
This starts a testing framework for the `obsreport` package to assert metrics when the otel instrumentation featuregate is enabled, it can be used for testing other component helpers from `obsreport` and can be extended for testing gauges and histograms in the future. 
Tests are done by parsing and asserting exported metrics from a prometheus handler.
**Testing:**  Unit tests for the `obsreport.Receiver` component helper.
> Add tests to the obsreport.Receiver component helper when using otel instrumentation

- .chloggen/revertargs.yaml
- service/collector_windows.go
- service/collector_windows_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6433
> Revert how the args are parsed on windows

- docs/roadmap.md
Updating the existing long-term roadmap to reflect the current status of the items on the roadmap. Note this roadmap could probably use a bit of a refresh, will add a discussion topic to the next SIG meet
> [docs] update roadmap document

- .chloggen/providehelpers.yaml
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/otlp.go
- receiver/otlpreceiver/otlp.go
Deprecate old `ToDialOptions` and `ToServerOptions`.
> Provide better helpers for configgrpc, consistent with confighttp

- .chloggen/obsreport_new_methods.yaml
- exporter/exporterhelper/obsreport.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_scraper.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
- processor/memorylimiterprocessor/memorylimiter.go
- processor/memorylimiterprocessor/memorylimiter_test.go
- receiver/otlpreceiver/internal/logs/otlp.go
- receiver/otlpreceiver/internal/metrics/otlp.go
- receiver/otlpreceiver/internal/trace/otlp.go
- receiver/scraperhelper/scrapercontroller.go
**Description:** As the `obsreport.[Receiver|Scraper|Processor|Exporter]` starts to use otel go, we need to return an error if one happens during the creation of otel go metrics. This is the first part for adding `error` as a return of these functions.
**Link to tracking Issue:** #6458
> deprecate `obsreport.New[Receiver|Scraper|Processor|Exporter]` in favor of `obsreport.MustNew*`

- .chloggen/cgroup-subsys-line-parse.yaml
- internal/cgroups/subsys.go
- internal/cgroups/subsys_test.go
**Description:** split line into exactly 3 parts while parsing /proc/{pid}/cgroup.
**Link to tracking Issue:** #6389
**Testing:** None
**Documentation:** None
> cgroups: accurate procfs parsing

- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- go.mod
- receiver/otlpreceiver/go.mod
These were requiring an invalid version of the collector (which was overwritten via replace statements in the module) but causes any modules that include them to require the invalid version of the collector.
> [chore] update go.mod for new modules

- .chloggen/msg_add-issue-link-deprecation.yml
- .chloggen/msg_add-issue-link-feature-gate.yaml
- extension/ballastextension/go.mod
- extension/ballastextension/go.sum
- featuregate/README.md
- featuregate/gates.go
- featuregate/gates_test.go
- internal/obsreportconfig/obsreportconfig.go
- service/internal/zpages/templates.go
- service/internal/zpages/templates/features_table.html
- service/zpages.go
This PR extends the feature gate to add the fields `IssueLinks` and `RemovalVersion` to help provide context to users on:
- Why a feature gate exists?
- What is the associated issue(s)
- When will the feature gate will be removed
https://github.com/open-telemetry/opentelemetry-collector/issues/6167
**Testing:** 
Tests have been updated to include updated to Gate life cycle as per the README
The featureflag README has been updated with an example.
> [featuregates] Add fields for associated Issues and deprecated version

- go.mod
This updates the dependency for the batch processor in go.mod to make updating contrib easier.
The error in contrib:
```
go: downloading go.opentelemetry.io/collector/processor/batchprocessor v0.0.0-00010101000000-000000000000
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureblobreceiver tested by
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureblobreceiver.test imports
go.opentelemetry.io/collector/service/servicetest imports
go.opentelemetry.io/collector/service imports
go.opentelemetry.io/collector/processor/batchprocessor: go.opentelemetry.io/collector/processor/batchprocessor@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
> [chore] update go.mod

- obsreport/obsreporttest/otelprometheuschecker_test.go
- obsreport/obsreporttest/testdata/prometheus_response
**Description:** move tests fixture to file.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/pull/6346/files#r1010963714
> tests: move obsreport tests fixture to file

- .chloggen/valiation-for-empty-metric-address.yaml
- service/config.go
- service/config_test.go
- service/telemetry/config.go
- service/telemetry/config_test.go
> add validation for empty telemetry metric address when level not none

- .chloggen/allowsampling.yaml
- service/config_provider_test.go
- service/telemetry/config.go
- service/telemetry/telemetry.go
- service/unmarshaler.go
- service/unmarshaler_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4554
> Allow to configure sampling config for logs

- featuregate/gates.go
- featuregate/gates_test.go
- service/zpages.go
Because of the conflict between the public member and func name, cannot do the same for ID/Description, will fix in a later version after we remove the public members.
No need for deprecation, they were added in this version.
/cc @mx-psi based on the discussion from https://github.com/open-telemetry/opentelemetry-collector/pull/6447
> Remove get from newly added funcs on Gate that don't conflict

- confmap/resolver.go
Description: 
Made change to correct broken link in comments
fixes #6374
> Fix Reference drive-letter specification link invalid #6374

- .chloggen/confmapmu.yaml
- confmap/resolver.go
This may be a breaking change, but should not be really important...
> Remove unused member from confmap.Resolver

- .chloggen/fixlogging.yaml
- exporter/loggingexporter/internal/otlptext/databuffer.go
- pdata/pcommon/common.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6420
Affected versions:
* v0.62.0
* v0.62.1
* v0.63.0
* v0.64.0
If anyone experience this, simple fix is to remove the logging exporter.
> Fix logging exporter to not mutate the data

- docs/troubleshooting.md
- exporter/loggingexporter/README.md
Signed-off-by: Sakshi Patle <sakshi.patle121@gmail.com>
Changing docs to deprecate loglevel in favour of verbosity
fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6448
Changing docs to deprecate loglevel in favour of verbosity
> [chore]: update docs to reflect verbosity for loggingexporter

- .chloggen/deprecate_hexstring.yaml
- exporter/loggingexporter/internal/otlptext/databuffer.go
- exporter/loggingexporter/internal/otlptext/logs.go
- exporter/loggingexporter/internal/otlptext/traces.go
- exporter/otlphttpexporter/otlp_test.go
- pdata/pcommon/spanid.go
- pdata/pcommon/spanid_test.go
- pdata/pcommon/traceid.go
- pdata/pcommon/traceid_test.go
`[SpanID|TraceID].HexString` methods currently return an empty string for empty SpanID and TraceID instances. This behavior is not defined in the OTel spec and contradicts with w3c recommendations. We don't want to promote a behavior which possibly can be changed in future.
Additionally we introduce `[SpanID|TraceID].String` methods that have the same logic as `HexString` and implement `fmt.Stringer` interface to allow `SpanID` and `TraceID` instances to be used in log statements and avoid unnecessary allocation when log is not emitted. But the `String` method is not encouraged to be used as a replacement for `HexString` because of the concerns described above.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6514
> [pdata] Deprecate HexString func on SpanID and TraceID

- .chloggen/level-update-string.yaml
- config/configtelemetry/configtelemetry.go
- config/configtelemetry/configtelemetry_test.go
- exporter/loggingexporter/config_test.go
- All returned strings are capitalized.
- "" is returned for integers that are out of Level enum range.
- It also affects `Level.MarshalText` output, but it's not a problem because `UnmarshalText` method accepts strings in all cases, e.g. "normal", "Normal" and "NORMAL".
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6490
> [configtelemetry] Update strings returned by `Level.[String|MarshalText]`

- docs/scraping-receivers.md
This document adds some definitions, stability requirements and guidelines on how to update emitted metrics for scraping receivers.
> [docs] Add a doc for scraping receivers

- cmd/otelcorecol/go.mod
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- go.mod
- processor/batchprocessor/go.mod
- processor/memorylimiterprocessor/go.mod
- receiver/otlpreceiver/go.mod
This makes updating otel core possible from contrib without having to write a bunch of replace statements.
> [chore] update component module to v0.0.0

- .chloggen/update-stability-level-string.yaml
- component/component.go
- component/component_test.go
This change updates values returned by `StabilityLevel.String` to be consistent with other enum types:
- All returned strings are capitalized.
- "Undefined" is returned only for `StabilityLevelUndefined`.
- "" is returned for integers that are out of StabilityLevel enum range.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6490
> [component] Update values returned by `StabilityLevel.String` method

- .chloggen/rename-dev-stability-level.yaml
- README.md
- component/component.go
- component/component_test.go
- component/exporter_test.go
- component/extension_test.go
- docs/scraping-receivers.md
- exporter/loggingexporter/README.md
- exporter/loggingexporter/factory.go
- service/extensions/extensions_test.go
- service/internal/components/components.go
- service/internal/components/components_test.go
- service/internal/testcomponents/example_exporter.go
- service/internal/testcomponents/example_processor.go
- service/internal/testcomponents/example_receiver.go
The decision to rename this stability level was made in https://github.com/open-telemetry/opentelemetry-collector/pull/6531#discussion_r1020619947
> [component] Rename "In development" stability level to "Development"

- README.md
@dmitryax has done an enormous amount of work on stabilizing the core APIs. He is the next most active contributor to this repository and I think he will be a great maintainer.
> Make dmitryax a maintainer

- .chloggen/split-consumer.yaml
- cmd/otelcorecol/go.mod
- component/go.mod
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- go.mod
- processor/batchprocessor/go.mod
- processor/memorylimiterprocessor/go.mod
- receiver/otlpreceiver/go.mod
> [chore] update dep to make update-otel easier

- docs/release.md
Update release schedule per internal discussion to happen on Monday instead of Wednesday next week.
The rationale is that we want to have some more distance with Thanksgiving, when many approvers and maintainers will be out of office.
> [release] Update release schedule

- .chloggen/processor-duplication-per-pipeline.yaml
- docs/design.md
- service/config.go
- service/config_test.go
- service/internal/pipelines/pipelines_test.go
- service/internal/pipelines/testdata/pipelines_simple_multi_proc.yaml
There is documentation [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md?plain=1#L125) that explains how a single processor can be specified in multiple pipelines, with the understanding that each pipeline will get its own instance. However, there is nothing specifically stated about the case where a single processor is specified multiple times in a single pipeline.
This PR is as much a question as a proposal. Is there an explicit intention to support this use case, or should we clarify and disallow it?
> [pipelines] Change test to not reuse same processor twice in one pipeline

- .chloggen/remove_units_suffix_otel_go_prometheus_exporter.yaml
- service/telemetry.go
- service/telemetry_test.go
**Description:** Disable the units suffixes added on metrics of otel-go. Type suffixes (`_total`) will still be added but can be trimmed with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16071. 
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16071 is supposed to remove both units and type's suffixes, but otel-go prometheus exporter doesn't expose the unit metadata, so we can't trim these units suffixes. 
This is a breaking change but it restores conformity of the metrics exported by the otel go sdk and opencensus sdk.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/6403
**Testing:** Changed the unit test to add an unit to the created metric, which shouldn't be added as suffix.
> Remove unit suffixes from metrics exported by the otel-go prometheus exporter

- .chloggen/registeroption.yaml
- featuregate/registry.go
This was something the I missed during the previous review.
> Make impossible to implement RegistryOption outside featuregate package

- .chloggen/deprecatevalidate.yaml
- component/config.go
- component/exporter.go
- component/extension.go
- component/processor.go
- component/receiver.go
- config/exporter.go
- config/extension.go
- config/processor.go
- config/receiver.go
- exporter/otlphttpexporter/config_test.go
- receiver/otlpreceiver/config_test.go
- service/config.go
This PR is "split" from https://github.com/open-telemetry/opentelemetry-collector/pull/6544, to avoid breaking changes and go via deprecation.
It is a bit hacky, but better than breaking everyone who uses this interface.
> Deprecate Config.Validate() in favor of component.ValidateConfig

- .github/workflows/check-links.yaml
- .github/workflows/scripts/set_release_tag.sh
- .github/workflows/scripts/verify-dist-files-exist.sh
This PR updates the usage of save-output command in GH actions.
Reference : https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
N/A
ChangeLog is not required
> Update the usage of set-output command in GH actions

- .chloggen/rmvalidate.yaml
- component/config.go
- config/exporter.go
- config/extension.go
- config/processor.go
- config/receiver.go
The reason is to remove the need that every Config includes the "config.*Settings" structs, and remove these structs completely.
One of the functionality they offer right now is that they provide the "default" implementation for `Validate`, and this PR provides a solution to that, by making the `Validate` a proper optional functionality to implement instead of optionally override it.
Alternative is to make mandatory for every `component.*Config` to implement `Validate` and not provide a default in the `config.*Settings`, that also solves the dependency problem (between component and config), but it comes with a small caveat, since if we want to extend the capability to validate sub-configs then for these will be optionally implemented functionality, because of that I believe it is more …
> Remove Validate() from Config interfaces and make it optional interface

- .chloggen/fixconfmap.yaml
- confmap/converter/expandconverter/expand_test.go
- confmap/resolver.go
- confmap/resolver_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6580
> Fix support for concatenating envvars with colon

- README.md
- docs/release.md
I plan to focus on other OpenTelemetry areas, such as OpAMP and Logs and no longer have time to be a Collector maintainer.
It has been a please working with all @open-telemetry/collector-approvers @open-telemetry/collector-contrib-approvers @open-telemetry/collector-maintainers @open-telemetry/collector-contrib-maintainer @open-telemetry/collector-contrib-triagers @open-telemetry/collector-triagers  :-)
> Remove tigrannajaryan as Maintainer

- .chloggen/deepvalidate.yaml
- component/config.go
- component/config_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4584
> Add recursive validation check for configs

- .chloggen/connector-component.yaml
- component/component.go
- config/connector.go
- connector/connector.go
This establishes the new component type without including anything specific about the design of connectors.
Subset of #6372
> Define new component type "connector"

- .chloggen/depunmarshal.yaml
- component/config.go
- component/exporter.go
- component/extension.go
- component/processor.go
- component/receiver.go
- exporter/loggingexporter/config_test.go
- exporter/otlpexporter/config_test.go
- exporter/otlphttpexporter/config_test.go
- extension/ballastextension/config_test.go
- extension/zpagesextension/config_test.go
- processor/batchprocessor/config_test.go
- processor/memorylimiterprocessor/config_test.go
- receiver/otlpreceiver/config_test.go
- service/internal/configunmarshaler/exporters.go
- service/internal/configunmarshaler/extensions.go
- service/internal/configunmarshaler/processors.go
- service/internal/configunmarshaler/receivers.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6578
> Deprecate Unmarshal[*]Config in favor of UnmarshalConfig

- .chloggen/connector-factory.yaml
- component/config.go
- connector/connector.go
- connector/connector_test.go
Follows #6577 
Respects intention of #6552 by defining the factory as part of the `connector` package rather than `component`.
> Add connector factory

- cmd/builder/internal/builder/main_test.go
- cmd/builder/test/core.builder.yaml
- cmd/builder/test/test.sh
- docs/release.md
Most of the credit for this goes to @jpkrohling.
Builder tests were running against a very old version of the builder, rather than current code. The problem with this became apparent when attempting make an additive change to `component.Factories`. ([example failure](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/3447893951/jobs/5754375816#step:4:23))
> Run builder tests with local collector module

- cmd/builder/internal/builder/main.go
Fixes #6591
Fixes #6591
Whereas before an error would look like this:
```
2022-11-22T08:38:42.377-0800    INFO    internal/command.go:125 OpenTelemetry Collector Builder {"version": "dev", "date": "unknown"}
2022-11-22T08:38:42.382-0800    INFO    internal/command.go:158 Using config file       {"path": "./cmd/otelcontribcol/manifest.yaml"}
2022-11-22T08:38:42.383-0800    INFO    builder/config.go:107   Using go        {"go-executable": "/usr/bin/go"}
2022-11-22T08:38:42.394-0800    INFO    builder/main.go:76      Sources created {"path": "./bin"}
2022-11-22T08:38:43.582-0800    INFO    builder/main.go:118     Getting go modules
2022-11-22T08:38:43.750-0800    INFO    builder/main.go:87      Compiling
Error: failed to compile the OpenTelemetry Collector distribution: …
```
> Don't escape go error output in builder

- service/internal/capabilityconsumer/capabilities.go
- service/internal/capabilityconsumer/capabilities_test.go
- service/internal/pipelines/pipelines.go
This is to prepare to move "pipelines" as public, see https://github.com/open-telemetry/opentelemetry-collector/issues/5564
> [chore] Move capabilities consumers in a separate package

- .chloggen/authpanic.yaml
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp.go
Fixing a bug - The OTLP exporter panics when collector tries to shut down the pipelines  as soon as an error happens during start up. 
An error is startup of the exporter will leave exporter with nil connection, followed by shutdown method of exporter invokes calling close on nil connection leading to panic
In the earlier versions since shutdown methods were never called when Start fails, we never observed this behavior.
**Link to tracking Issue:**   https://github.com/open-telemetry/opentelemetry-collector/issues/6619
**Testing:** Manual testing to see collector shuts down gracefully without any panic 
```bash 
2022/11/28 21:50:31 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/11/28 21:50:31 proto: duplicate proto type registered: …
```
> Fix nil panic from otlp exporter

- .chloggen/move-configauth-to-extension-step-1.yaml
- config/configauth/configauth.go
- config/configauth/configauth_test.go
- config/configauth/deprecated.go
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/otlpexporter/config_test.go
- extension/auth/authtest/mock_clientauth.go
- extension/auth/authtest/mock_clientauth_test.go
- extension/auth/clientauth.go
- extension/auth/default_clientauthenticator.go
- extension/auth/default_clientauthenticator_test.go
- extension/auth/default_serverauthenticator.go
- extension/auth/default_serverauthenticator_test.go
- extension/auth/doc.go
- extension/auth/serverauth.go
partly fix #4996
As I commented in https://github.com/open-telemetry/opentelemetry-collector/issues/4996#issuecomment-1296929370
> 1. defines new package `configauth` in the `extensions` directory, but for each exported type (for example `Authentication`), is only the alias of the homonymous one in the `config` directory, for example:
> 
> ```go
> import "go.opentelemetry.io/collector/config/configauth"
> 
> type Authentication = configauth.Authentication
> ```
> 
> 2. change all package or module which imports `config/configauth` to `extension/configauth`, for example configgrpc.go in `config/configgrpc`, change from
> 
> ```go
> import "go.opentelemetry.io/collector/config/configauth"
> ```
> 
> to
> 
> ```go
> import "go.opentelemetry.io/collector/extension/configauth"
> ```
> 
> 3. …
> [extension/authextension] define new authextension package and use new package in collector repo

- docs/release.md
Updating the release version numbers to account for 0.66.0 which was just released.
> [chore] update release schedule

- Makefile
- docs/release.md
Also, only creates tags for the modules not marked as ignored in the version file.
For the moment I cannot find way to push these tags, filed https://github.com/open-telemetry/opentelemetry-go-build-tools/issues/157
> Replace manually adding tags with multimod

- .chloggen/addconfigopaque.yaml
- config/configopaque/opaque.go
- config/configopaque/opaque_test.go
Add a `configopaque.String` type alias. This is the original proposal from #5653. I wanted to try this option out to make sure everyone understands the extent of breaking changes since, as mentioned on https://github.com/open-telemetry/opentelemetry-collector/issues/5653#issuecomment-1208609102, they should be minimal (as they only affect the Go API).
**Link to tracking Issue:** Updates #5653
> Add configopaque package

- cmd/otelcorecol/go.mod
- cmd/otelcorecol/go.sum
- confmap/go.mod
- confmap/go.sum
- extension/ballastextension/go.mod
- extension/ballastextension/go.sum
- go.mod
- go.sum
- processor/memorylimiterprocessor/go.mod
- processor/memorylimiterprocessor/go.sum
I also created a PR on their repo https://github.com/shirou/gopsutil/pull/1386
> Revert github.com/shirou/gopsutil/v3 to previous version, tag removed

- service/internal/configunmarshaler/exporters_test.go
- service/internal/configunmarshaler/extensions_test.go
- service/internal/configunmarshaler/processors_test.go
- service/internal/configunmarshaler/receivers_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6578
> [chore] Remove usage of NopFactories when only one is needed

- .chloggen/move-configauth-to-extension-step-1.yaml
- config/configauth/deprecated.go
- extension/auth/default_clientauthenticator.go
- extension/auth/default_clientauthenticator_test.go
No need to deprecate/break things since these new types were added in this release.
> Prefix auth funcs/types with Client. Add *Func types

- .chloggen/move-configauth-to-extension-step-1.yaml
- config/configauth/deprecated.go
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- extension/auth/default_serverauthenticator.go
- extension/auth/default_serverauthenticator_test.go
- extension/auth/serverauth.go
No need to deprecate/break things since these new types were added in this release.
The reason for Option -> ServerOption is to be consistent with ClientOption.
The reason for AuthenticateFunc -> ServerAuthenticateFunc is because we may have the same Authenticate func on the client in the future and to avoid name conflicts.
> Prefix auth funcs/types with Server to be consistent with Client.

- examples/k8s/otel-config.yaml
While installing otel agent using [Kubernetes](https://opentelemetry.io/docs/collector/getting-started/#kubernetes) instructions. I was hitting `ErrImagePull` for version 0.65.0:
```
→ kubectl get pods
NAME                              READY   STATUS         RESTARTS   AGE
otel-agent-d2t5d                  0/1     ErrImagePull   0          14s
otel-collector-7bf5f66dcf-rc96s   0/1     ErrImagePull   0          14s
```
I tried to find the `0.65.0` tag in [DockerHub](https://hub.docker.com/r/otel/opentelemetry-collector/tags?page=1&name=0.65.0) but seems like it isn't there. Not sure why. Anyways, bumping the image to `0.66.0` solves the issue:
```
→ kubectl get pods
NAME                              READY   STATUS    RESTARTS   AGE
otel-agent-wxnnd                  1/1     Running   0 …
```
> [chore] Bump deployment image to 0.66.0

- service/extensions/extensions_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6578
Factories will need to be moved away from component to not cause circular dependencies, these PRs help with determining where that struct is used.
> [chore] remove usage of component.Factories in service/extiension

- .chloggen/moveext.yaml
- component/factories_test.go
- extension/extension_test.go
- extension/extensiontest/nop_extension_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6578
> [chore] move tests to non deprecated packages, fix chloggen

- service/pipelines.go
- service/pipelines_test.go
- service/service.go
Not a breaking change since the type was added (moved) in this cycle.
> [chore] fix unintended public type settings when moved pipelines

- .chloggen/deprecatecompexp.yaml
- component/componenttest/nop_exporter.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/traces_test.go
- exporter/exportertest/nop_exporter.go
- exporter/exportertest/nop_exporter_test.go
- exporter/loggingexporter/factory_test.go
- exporter/loggingexporter/logging_exporter_test.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp_test.go
- exporter/otlphttpexporter/factory_test.go
- exporter/otlphttpexporter/otlp_test.go
- obsreport/obsreporttest/obsreporttest.go
- otelcol/config_provider_test.go
- service/internal/configunmarshaler/exporters_test.go
- service/pipelines_test.go
This was a miss from https://github.com/open-telemetry/opentelemetry-collector/pull/6672
Skipping changelog since covered in https://github.com/open-telemetry/opentelemetry-collector/blob/main/.chloggen/deprecatecompexp.yaml
> Mark as deprecated componenttest exporter related funcs

- .chloggen/persistentqueuedupdata.yaml
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
Fix a bug that exporter persistent queue is sending duplicate data after restarting. This is due to consumer still processing requests after the persistent storage client has shutdown, resulting successful request not updated in the storage.
https://github.com/open-telemetry/opentelemetry-collector/issues/6692
**Testing:**
- Running existing unit test on close
- added a unit test case to verify storage stopping time is after last item consumed from consumers
Updated changelog
> Persistent queue should stop consumer before stopping storage

- .chloggen/connector-types.yaml
- connector/connector.go
- connector/connector_test.go
Part of #6372, reimplemented within `connectors` package.
Conversation [here](https://github.com/open-telemetry/opentelemetry-collector/pull/6372#discussion_r1011844052) questions whether this is the proper implementation, but I would like to suggest that we use it initially. It's currently localized to the `connectors` package and related functionality will be hidden behind a feature gate. Once the functionality is fully implemented, it will be easier to reconsider alternatives.
> Add connector types

- .chloggen/rmdepbatch.yaml
- component/go.mod
- consumer/go.mod
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- go.mod
- processor/batchprocessor/metrics.go
- processor/batchprocessor/metrics_test.go
- processor/memorylimiterprocessor/go.mod
- receiver/otlpreceiver/go.mod
- service/telemetry.go
Reason is to make sure we don't expose yet a hack pattern to register Otel views until a proper design is in place and to move the OC views registration to the same model as contrib. Also this cleans dependencies between core modules.
> Remove dependency on batchprocessor from service package

- service/collector.go
- service/collector_test.go
- service/service.go
- service/service_test.go
- service/settings.go
This will allow to move deprecated Collector to otelcol.
> [chore] Remove telemetryInitializer from CollectorSettings

- .chloggen/shutdowntel.yaml
- service/collector.go
- service/collector_test.go
- service/service.go
- service/service_test.go
- service/settings.go
- service/telemetry.go
- service/telemetry_test.go
This removes any "private" dependency between Collector and Service and will allow to move collector to otelcol per the deprecation notice.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/5564
> Move shutdown telemetry to Service

- config/configtls/README.md
Fixes a minor spelling mistake.
"certifaces" -> "certificates"
> Fix typo in configtls README.md

- .chloggen/mv-factories-otelcol.yaml
- otelcol/collector.go
- otelcol/collector_test.go
- otelcol/collector_windows_test.go
- otelcol/command_components_test.go
- otelcol/command_test.go
- otelcol/configprovider.go
- otelcol/configprovider_test.go
- otelcol/factories.go
- otelcol/factories_test.go
- otelcol/otelcoltest/config.go
- otelcol/otelcoltest/config_test.go
- otelcol/otelcoltest/nop_factories.go
- otelcol/unmarshaler.go
- otelcol/unmarshaler_test.go
Resolves #6766
`NopFactories` is moved to `otelcoltest`. However, `otelcol` has its own private implementation in order to avoid a dependency cycle.
> Move Factories to otelcol, delete otelcoltest

- receiver/otlpreceiver/README.md
otlpreceiver does not use exporterhelper queue and retry mechanism
Description: Fix misleading README pointing to a piece of code apparently not used in the receiver (the link is for exporters)
Testing: Verified code for trace of exporterhelper. Double checked the config object that doesn't contain anything related to queue or retries
> [receiver/otlpreceiver] Fix README

- .github/workflows/builder-integration-test.yaml
- cmd/builder/test/core.builder.yaml
https://github.com/open-telemetry/opentelemetry-collector/pull/6784 introduced a change to the interface of `sharedcomponent.GetOrAdd`, which affected the builder integration test. 
The integration test is affected because it does not replace every package, but rather only specific packages listed in `cmd/builder/test/core.builder.yaml`.
This PR also enables this integration test for all PRs as well as all merges to `main`. This will prevent similar issues from going unnoticed. Alternately, we could ensure that all local modules are replaced. However, this test takes ~75 seconds to run, which is far from being the bottleneck in our CI process.
The failing test can be reproduced locally by running `(cd ./cmd/builder && ./test/test.sh)`, and can also be see …
> [chore] Fix builder integration test

- exporter/exporterhelper/queued_retry_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6759
The tests helpers for obsreport should be reworked, but this one is a quick fix that should prevent it from panicking.
> [chore] Fix panic in queue_retry tests

- .chloggen/draftbuilder.yaml
- exporter/exporter.go
- exporter/exportertest/nop_exporter.go
- exporter/exportertest/nop_exporter_test.go
- extension/extension.go
- extension/extensiontest/nop_extension.go
- extension/extensiontest/nop_extension_test.go
- otelcol/collector.go
- processor/processor.go
- processor/processortest/nop_processor.go
- processor/processortest/nop_processor_test.go
- receiver/receiver.go
- receiver/receivertest/nop_receiver.go
- receiver/receivertest/nop_receiver_test.go
- service/extensions/extensions.go
- service/extensions/extensions_test.go
- service/host.go
- service/pipelines.go
- service/pipelines_test.go
- service/service.go
- service/service_test.go
- service/zpages.go
The main idea is that we pass a `receiver.Builder` (a combo of configs and factories that can create Receivers to the Service) instead of configs and factories separately. This way we help other distributions to re-implement service/host.
> Add receiver.Builder to help with creating components form a set of configs and factories

- README.md
Migrate to the new endpoint. See https://github.com/badges/shields/issues/8671
> [chore] Update the build status badge

- component/factories.go
Factories was moved from service -> otelcol
> [chore] Factories deprecation comment was incorrect

- .chloggen/mx-psi_configopaque-http.yaml
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/otlphttpexporter/config_test.go
- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/factory_test.go
- exporter/otlphttpexporter/otlp_test.go
Change `Headers` field on HTTP client config to have opaque values and transparent keys.
Depends on #6470
**Link to tracking Issue:** Updates #5653
> [confighttp] Change Headers field type to have opaque values

- cmd/builder/internal/builder/config.go
- cmd/builder/internal/config/default.yaml
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- component/go.mod
- confmap/go.mod
- connector/forwardconnector/go.mod
- consumer/go.mod
- examples/k8s/otel-config.yaml
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- go.mod
- processor/batchprocessor/go.mod
- processor/memorylimiterprocessor/go.mod
- receiver/otlpreceiver/go.mod
- versions.yaml
- prepare release 0.68.0
- Prepare beta for version v0.68.0
- add multimod changes
This corresponds to the last point on step 6 on the release guidelines, by running:
```
make prepare-release PREVIOUS_VERSION=0.67.0 RELEASE_CANDIDATE=0.68.0 MODSET=beta
```
Previous steps are at #6820
**Link to tracking Issue:** Fixes #6821
> [chore] prepare release 0.68.0

- docs/release.md
Update release schedule:
- Move v0.67.0 and v0.68.0 release managers to the bottom of the list
- Move v0.69.0 release date one week later as discussed on the last Collector SIG
- Align the rest of releases to happen a week later (and fix the year on a couple of entries)
Relates to #6818
> [docs] Update release schedule

- exporter/exporterhelper/README.md
The readme mentions resource attributes to metric labels conversion which is not a part of this helper anymore.
> [chore] Update Exporter Helper README.md

- .chloggen/opaque-fixed-length.yaml
- config/configopaque/opaque.go
- config/configopaque/opaque_test.go
Fix secret length disclosure with configopaque String. Use a 8 byte length consistently.
#6868
**Testing:**
Added tests to show how the same string is outputted no matter what length of the secret
> [config/configopaque] fix secret length disclosure with configopaque String

- docs/release.md
Removes the first two points from the bugfix release criteria.
I think the remaining points give a more accurate picture of the decision making process we have taken so far, (e.g for #6420, where the first two points were not fulfilled).
We can revisit this in the future if there are disagreements on when to do a bugfix release
> [docs] Relax bugfix criteria

- .chloggen/connector-factory-map.yaml
- connector/connector.go
- connector/connector_test.go
This adds the `connector.MakeFactoryMap` function, similar to that found in other component type packages.
> Add connector.MakeFactoryMap

- pdata/pcommon/common.go
> [chore] Update pcommon.Map.Equal deprecation doc string

- service/telemetry.go
Create the Prometheus HTTP handler explicitly to better separate responsibilities between OC and OTel instrumentation initializations and prepare for the eventual removal of the OC instrumentation
> [chore] Don't use prom server created by OpenCensus initialization

- config/configopaque/doc.go
- config/configopaque/doc_test.go
- Add a package-level comment for `configopaque` package
- Add examples test to showcase how the configuration struct with field `configopaque.String`,` []configopaque.String` and `map[string]configopaque.String` looks once marshalled.
#6855
Add example test with the expected output.
N/A
> [chore]add package and examples documentation to configopaque package

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/config/default.yaml
- cmd/builder/test/core.builder.yaml
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- component/go.mod
- confmap/go.mod
- connector/forwardconnector/go.mod
- consumer/go.mod
- examples/k8s/otel-config.yaml
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- go.mod
- processor/batchprocessor/go.mod
- processor/memorylimiterprocessor/go.mod
- receiver/otlpreceiver/go.mod
- versions.yaml
This branch started from `origin/main`, merged `origin/release/v0.69.x` into it and resolved merge conflicts.
> Merge `release/v0.69.x` into `main`

- cmd/builder/README.md
There was a build error prior to 0.69.1, update the example accordingly. 
--output-path seems to be deprecated, move it to the config file.  …
> ocb: Update README.md

- cmd/builder/go.mod
- cmd/otelcorecol/go.mod
- component/go.mod
- confmap/go.mod
- connector/forwardconnector/go.mod
- consumer/go.mod
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- featuregate/go.mod
- go.mod
- processor/batchprocessor/go.mod
- processor/memorylimiterprocessor/go.mod
- receiver/otlpreceiver/go.mod
- semconv/go.mod
Ensuring users can't use v0.69.0 since it failed, should use fixed version v0.69.1
https://github.com/open-telemetry/opentelemetry-collector/issues/6908
> [chore] Retract failed release v0.69.0

- service/internal/testcomponents/example_connector.go
- service/internal/testcomponents/example_connector_test.go
- service/internal/testcomponents/example_exporter.go
- service/internal/testcomponents/example_exporter_test.go
- service/internal/testcomponents/example_processor.go
- service/internal/testcomponents/example_receiver.go
- service/internal/testcomponents/example_receiver_test.go
- service/internal/testcomponents/stateful_component.go
- service/pipelines_test.go
This is a small part of #6700. The main idea is to provide a common way to validate components, especially in complex pipelines. Current tests rely on uniform expectations such as all exporters receiving 1 signal. However, testing the connector framework would ideally include expectations on a per-component basis.
This PR adds only the basic start/stop functionality, which itself reduces repetitive code somewhat. In the future, I would like to validating expected signals observed by each component.
> Add testcomponents.StatefulComponent

- cmd/builder/internal/builder/main.go
Signed-off-by: Maureen <amaka013@gmail.com>
**Link to tracking Issue:** Closes https://github.com/open-telemetry/opentelemetry-collector/issues/5781
**Testing:** None
**Documentation:**  None needed
> Add reason for nosec annotation on builder inputs

- .chloggen/connector-config.yaml
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/templates/components.go.tmpl
- cmd/builder/internal/builder/templates/components_test.go.tmpl
- cmd/builder/internal/builder/templates/go.mod.tmpl
- cmd/builder/internal/command.go
- cmd/builder/internal/config/default.yaml
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/components.go
- cmd/otelcorecol/components_test.go
- cmd/otelcorecol/go.mod
- otelcol/factories.go
- otelcol/otelcoltest/nop_factories.go
- otelcol/otelcoltest/nop_factories_test.go
- service/host.go
- service/service.go
- service/service_test.go
> Add support for connector configurations

- .chloggen/otelcol-plan9build.yaml
- exporter/loggingexporter/known_sync_error_plan9.go
Building **otelcorecol** was broken for Plan 9.
```console
$ cd cmd/otelcorecol
$ GOOS=plan9 go build
../../exporter/loggingexporter/known_sync_error.go:29:10: undefined: syscall.ENOTSUP
../../exporter/loggingexporter/known_sync_error.go:31:10: undefined: syscall.ENOTTY
../../exporter/loggingexporter/known_sync_error.go:33:10: undefined: syscall.EBADF
```
**Testing:**
Though I'm not sure yet there are more other issues when otelcorecol is running on Plan 9, at least, this PR is fixed undefined symbol errors and I checked **otelcorecol** shows a help successfully with `-h` option.
> Fix undefined symbol errors on building otelcorecol for Plan 9

- .gitignore
- Makefile
- Makefile.Common
This comes from the spike being done https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17849
The idea is that contributors developer environments match the versions used in the CI to avoid issues with out of date tooling.
N/A
**Testing:** 
Validating that this change works with CI is the test.
These changes are completely transparent to the contributor, so I haven't added any documentation.
> [chore] Updating makefile to use local binaries instead of environment install binaries

- .chloggen/disallowimpl.yaml
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/otlp_test.go
- pdata/plog/plogotlp/grpc.go
- pdata/plog/plogotlp/grpc_test.go
- pdata/pmetric/pmetricotlp/grpc.go
- pdata/pmetric/pmetricotlp/grpc_test.go
- pdata/ptrace/ptraceotlp/grpc.go
- pdata/ptrace/ptraceotlp/grpc_test.go
- receiver/otlpreceiver/internal/logs/otlp.go
- receiver/otlpreceiver/internal/metrics/otlp.go
- receiver/otlpreceiver/internal/trace/otlp.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6966
This pattern is inspired by the gRPC generated code.
> Start enforcing grpc server implementation to embed UnimplementedGRPCServer, dissallow client implementation

- cmd/builder/.goreleaser.yml
- docs/release.md
This removes the need to add the location of the releases repo at the top of the changelog.
> [chore] update release configuration

- .github/workflows/builder-release.yaml
In the last 3 releases, this job has created a release for the cmd/builder/v* tag, which caused an issue in the release process and introduced additional manual steps. An alternative to this would be to create two releases, one for the builder and one for the collector, but that seems overkill at this point.
Fix #6849
> [chore] update release build job to trigger on v* tag push

- .chloggen/case-sensitive-configuration.yaml
- confmap/confmap.go
- exporter/loggingexporter/config_test.go
- exporter/loggingexporter/testdata/config_loglevel_typo.yaml
Signed-off-by: Raphael Silva <rapphil@gmail.com>
**Description:** Fix bug that allowed users to specify invalid configurations that would pass validation but would not work properly or fail silently. E.g.: `loglevel`. If you specify `logLevel`, the validation would pass but the collector logging exporter would not produce logs.
**Testing:** Added unit test before changing the code.
> Fix: Force usage of case-sensitive keys in configurations

- .chloggen/mx-psi_configgrpc-opaque.yaml
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/factory.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
Like #6637, but on `configgrpc`.
**Link to tracking Issue:** Fixes #6852
> [configgrpc] Change Headers field type to have opaque values

- .chloggen/deprecate-map-sort.yaml
- pdata/pcommon/common.go
This method will be removed as it leaks the underlying implementation.
One of the following alternatives should be used instead:
- Map.AsRaw() if you need to compare two maps in tests.
- github.com/open-telemetry/opentelemetry-collector-contrib/pkg/pdatatest module if you use Sort()
to prepare other pdata objects for comparison.
- github.com/open-telemetry/opentelemetry-collector-contrib/pkg/pdatautil module if you use Sort()
to create Map identifiers.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6688
> [pdata] Deprecate pcommon.Map.Sort()

- otelcol/config.go
- otelcol/configprovider.go
- otelcol/unmarshaler.go
Part of #6700 
This PR adds connectors to the `otelcol.Config` and updates associated config provider and unmarshaler.
> Add connectors to otelcol config

- service/graph.go
- service/host.go
- service/pipelines.go
- service/pipelines_test.go
> Extract service.pipelines interface

- cmd/otelcorecol/go.mod
- cmd/otelcorecol/go.sum
- go.mod
- go.sum
- service/nodes.go
Part of #6700
In order to manage components in a directed graph, each node must be associated with a unique identifier (`int64`) in the case of the `gonum` library. This PR defines a simple hashing system for all types of components, as well as a struct type for each component that contains all of the context necessary to reason about the nodes within the graph.
> Add component node types

- otelcol/collector.go
- otelcol/config.go
- otelcol/config_test.go
- otelcol/otelcoltest/config_test.go
- otelcol/otelcoltest/testdata/config.yaml
Part of #6700 
This PR finishes adding connectors to the otelcol config including validation. Validation for connectors is the same as with other components, except two additional checks are included:
1. That each connector is used as an exporter in at least one pipeline, and also as a receiver in at least one pipeline.
2. That each connector ID is distinct from receivers and exporters. (Depends on decision on https://github.com/open-telemetry/opentelemetry-collector/pull/6927#issuecomment-1400791808)
> Add connector validation to otelcol

- .github/workflows/prepare-release.yml
- .github/workflows/scripts/release-check-blockers.sh
- .github/workflows/scripts/release-check-build-status.sh
- .github/workflows/scripts/release-create-tracking-issue.sh
- .github/workflows/scripts/release-prepare-release.sh
- Makefile
- docs/release.md
This PR adds a github action that can be triggered manually to do the following:
- creates tracking issue
- checks for blockers in core
- checks for blockers in contrib
- checks status of build-and-test in core
- checks status of build-and-test in contrib
- runs chlog update
- runs make-prepare for both stable/beta
- creates a PR
See the tracking issue created [here](https://github.com/codeboten/opentelemetry-collector/issues/175)
You can see the PR produced [here](https://github.com/codeboten/opentelemetry-collector/pull/176)
Running the workflow looks like this:
> add github action to automate the release parts of the process

- otelcol/otelcoltest/config_test.go
Very minor test detail missed in previous PR. Part of #6700
> Update otelcoltest to validate num connectors

- .github/workflows/create-dependabot-pr.yml
- .github/workflows/prepare-release.yml
- .github/workflows/scripts/dependabot-pr.sh
- .github/workflows/scripts/release-prepare-release.sh
This works around the limitation that a PR created by an action doesn't trigger workflows automatically by using the opentelemetrybot's token. See https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot
> [chore] use opentelemetrybot

- service/graph.go
- service/graph_test.go
Part of #6700 
This adds graph-based implementations for `StartAll` and `Shutdown` all. It also adds a very lightweight test framework that validates the expected start & stop ordering of generic nodes in the graph.
> Add implementation of pipelineGraph StartAll and ShutdownAll

- cmd/builder/internal/builder/templates/components_test.go.tmpl
- cmd/builder/internal/builder/templates/main.go.tmpl
- cmd/builder/internal/builder/templates/main_windows.go.tmpl
goimport does not merge different blocks, it only splits blocks based on the rules. Because of that we should have only one import group and every repo splits by their rules.
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16828/files#diff-5040246c296b340124c7a2c8a7903ba51ae5fcf34a1d3e353cd2f49ab9bf07e3R14
> Group imports in builder templates

- .github/workflows/scripts/dependabot-pr.sh
This removes the need for the "Skip changelog" label as the title already contains "[chore]".
> [chore] update dependabot pr script

- service/graph_test.go
- service/nodes.go
This interface was part of #6700 but has been refactored out in the latest implementation.
> Remove unnecessary interface in service/nodes.go

- .chloggen/depapply.yaml
- featuregate/registry.go
- featuregate/registry_test.go
- otelcol/command.go
- otelcol/config_test.go
- otelcol/otelcoltest/config_test.go
Trying to keep the API closer to some standard libraries like FlagsSet. If a getter is needed we should name it Lookup.
> Deprecate Apply in favor of Set

- internal/sharedgate/sharedgate.go
- otelcol/config.go
- otelcol/config_test.go
- otelcol/otelcoltest/config_test.go
- service/graph.go
- service/service.go
Part of #6700
The remainder of the connectors implementation is concerned with setting up the component graph and building each node's associated component. I believe the best way to add these capabilities incrementally will be to so in a top-down way. 
- This PR adds the entry point to building the component graph. 
- Next, outline the steps to set up and build the graph.
- Then add nodes, then edges. 
- Finally, build each node's associated component.
#6700 contains extensive testing of the graph as a whole. However, these tests interface primarily with the graph's built components. I'm not seeing a reasonable way to include coverage for a partially built graph, which I expect we would have if we follow the contribution path I've described above. My hope is that we can move forward for …
> Add entry point to build graph-based pipelines

- docs/release.md
Once https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18057 is merged, this PR will update the documentation around releasing contrib.
> [chore] update documentation for releasing contrib

- .chloggen/addvisit.yaml
- featuregate/registry.go
- featuregate/registry_test.go
- service/zpages.go
> Deprecate featuregate.Registry.List in favor of Visit.

- .chloggen/fixgrpc.yaml
- pdata/plog/plogotlp/grpc.go
- pdata/pmetric/pmetricotlp/grpc.go
- pdata/ptrace/ptraceotlp/grpc.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6966
> Add private method to GrpcServer interface, disallow direct implementation

- .chloggen/allow-config-exp-backoff-parameters.yaml
- exporter/exporterhelper/queued_retry.go
- exporter/otlpexporter/cfg-schema.yaml
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/testdata/config.yaml
- exporter/otlphttpexporter/config_test.go
- exporter/otlphttpexporter/testdata/config.yaml
Enhancement - Allow fields from Exponentional Backoff Algorithm, RandomizationFactor and Multiplier, be configured by the user. Defaults values weren't changed.
**Link to tracking Issue:** #6610 
**Testing:** Added the new fields to the testdata/config.yaml files that are parsed by `TestUnmarshalConfig` in "otlphttpexporter/config_test.go" and "otlpexporter/config_test.go"
**Documentation:** Added field's description to cfg-schema.yaml
**Others:** Does you think it requires an addition in the changelog?
> Allow configuration of fields, RandomizationFactor and Multiplier, for `retry_on_failure`

- service/README.md
> Document ability to use config providers inside config

- .chloggen/supportconcat.yaml
- confmap/provider_test.go
- confmap/resolver.go
- confmap/resolver_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6932
> Add support for concatenating multiple embedded uris, or uris with other string parts

- .chloggen/case-sensitive-configuration.yaml
- confmap/confmap.go
- exporter/loggingexporter/config_test.go
- exporter/loggingexporter/testdata/config_loglevel_typo.yaml
This reverts commit 80cabdd33c50eaf386293f90fd8ac57cb3a10dc9.
Closes #7002
> Revert "Revert "Fix: Force usage of case-sensitive keys in configurations (#6876)" (#6988)"

- .chloggen/ldflags.yaml
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/main.go
- cmd/builder/internal/builder/main_test.go
- cmd/builder/internal/command.go
**Description:** Adding a feature - `ldflags` option in builder cmd, to be passed to `go build`
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/6940
**Testing:** manually built a collector with custom components who have build variables.  Passing `ldflags` set the values of these variables.
**Documentation:** I added a description for the `--help` command, but I can add a small explanation to the README if people would prefer.
> add ldflags builder cmd option

- service/pipelines.go
- service/pipelines_test.go
- service/service.go
> Rename pipelineSettings fields with Builder

- connector/forwardconnector/forward.go
There isn't really any reason to use `sharedcomponent` in the forward connector because there is no shared state or interaction between signals.
> Simplify forward connector by removing sharedcomponent

- .chloggen/pdata-deprecate-moveto.yaml
- pdata/plog/logs.go
- pdata/pmetric/metrics.go
- pdata/ptrace/traces.go
The methods don't provide any value and can be replaced with simple assignments.
This also unblocks https://github.com/open-telemetry/opentelemetry-collector/pull/7088
> [pdata] Deprecate [Metrics|Logs|Traces].MoveTo methods

- .chloggen/rmsort.yaml
- pdata/pcommon/map.go
- pdata/pcommon/map_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6688
> Remove deprecated pcommon.Map.Sort

- pdata/internal/cmd/pdatagen/internal/base_slices.go
- pdata/plog/generated_logrecordslice_test.go
- pdata/plog/generated_resourcelogsslice_test.go
- pdata/plog/generated_scopelogsslice_test.go
- pdata/pmetric/generated_exemplarslice_test.go
- pdata/pmetric/generated_exponentialhistogramdatapointslice_test.go
- pdata/pmetric/generated_histogramdatapointslice_test.go
- pdata/pmetric/generated_metricslice_test.go
- pdata/pmetric/generated_numberdatapointslice_test.go
- pdata/pmetric/generated_resourcemetricsslice_test.go
- pdata/pmetric/generated_scopemetricsslice_test.go
- pdata/pmetric/generated_summarydatapointslice_test.go
- pdata/pmetric/generated_summarydatapointvalueatquantileslice_test.go
- pdata/ptrace/generated_resourcespansslice_test.go
- pdata/ptrace/generated_scopespansslice_test.go
- pdata/ptrace/generated_spaneventslice_test.go
- pdata/ptrace/generated_spanlinkslice_test.go
- pdata/ptrace/generated_spanslice_test.go
This brings `slicePtr` and `sliceValue` tests the same view which helps to consolidate them
> [chore] [pdata] Simplify EnsureCapacity tests

- connector/connectortest/connector.go
- connector/connectortest/connector_test.go
- internal/sharedgate/sharedgate.go
Use a different ID than `receivertest` and `exportertest` to avoid ambiguous configuration scenarios. Ambiguous IDs are detected in the `otelcol` package, but lower level packages such as `service` assume that IDs are disambiguated.
To demonstrate this working with the connectors feature gate enabled, I've temporarily updated the gate level to beta. Once tests pass, I will revert the gate level to alpha.
> Disambiguate component ID in 'connectortest' package

- pdata/internal/cmd/pdatagen/internal/base_fields.go
- pdata/internal/cmd/pdatagen/internal/base_structs.go
To reduce repetitive code, the same way as it's done for `baseSlice` structs
> [chore] [pdata] Move generator template fields to dedicated methods

- CONTRIBUTING.md
Under the Naming convention of the CONTRIBUTING.MD I have added the guidelines for getter and setter methods from the [Effective go guidelines](https://go.dev/doc/effective_go#Getters) along with suitable examples.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/7048
> Added guidelines for getter and setter Method.

- .chloggen/connnectors-changelog.yaml
- connector/README.md
- internal/sharedgate/sharedgate.go
This PR is preparation for the v0.71.0 release, which would be the first with a functional implementation of the connectors framework.
- Changes the feature gate from `enableConnectors` to `connectors`, which makes more sense in the long run because the enabled status is independent of the gate's _name_.
- Adds a note to the connectors README about the status of the feature set and how to enable.
- Adds a changelog entry with a basic description of the feature set and a link to the README.
> Update connectors flag and documentation

- .chloggen/enablegraph.yaml
- otelcol/config.go
- otelcol/config_test.go
- otelcol/internal/sharedgate/sharedgate.go
- otelcol/otelcoltest/config_test.go
- service/service.go
- service/service_test.go
Add a separate featuregate to control the new graph base pipelines implementation release. This way we can enable the graph base implementation now, and keep connectors still in alpha (since the validation of the otelcol Config will fail) to limit the number of changes necessary to enable connectors.
> Split graph based pipelines implementation from connectors functionality

- connector/forwardconnector/README.md
The README is updated to the same format as [countconnector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/countconnector/README.md).
> Update forward connector readme

- .chloggen/fix-memory-limiter.yaml
- internal/cgroups/cgroups.go
- internal/cgroups/testdata/proc/cgroups/mountinfo
Fixing Memory limiter bug, when container mount's hosts sys filesystem, cgroups might incorrectly parse current container's memory.
The only way I figure we can fix this is to limit the search to `/sys` ? But I'm not sure if there are kernel's that would mount this in a different place?
**Link to tracking Issue:**  https://github.com/open-telemetry/opentelemetry-collector/issues/6826
and https://github.com/open-telemetry/opentelemetry-helm-charts/issues/543
**Testing:** 
- Added unit tests
-
> [memorylimiter] Fix cgroups parsing

- .github/workflows/scripts/release-prepare-release.sh
The previous change only modified the PR comment, instead of the call to `chlog-update` itself.
> [chore] update chlog update call

- .chloggen/go1-20.yaml
- .github/workflows/build-and-test.yml
- Makefile.Common
- cmd/builder/go.mod
- cmd/builder/internal/builder/main.go
- cmd/builder/internal/builder/templates/go.mod.tmpl
- cmd/otelcorecol/go.mod
- component/go.mod
- confmap/go.mod
- connector/forwardconnector/go.mod
- consumer/go.mod
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- featuregate/go.mod
- go.mod
- internal/tools/go.mod
- pdata/go.mod
- processor/batchprocessor/go.mod
- processor/memorylimiterprocessor/go.mod
- receiver/otlpreceiver/go.mod
- semconv/go.mod
> remove go 1.18 support, bump minimum to go 1.19 and add testing for 1.20

- .chloggen/semconv_v1.17.0.yaml
- Makefile
- semconv/semconv_test.go
- semconv/v1.17.0/generated_event.go
- semconv/v1.17.0/generated_resource.go
- semconv/v1.17.0/generated_trace.go
- semconv/v1.17.0/schema.go
> add semantic conventions for specification v1.17.0

- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage_batch_test.go
- exporter/exporterhelper/internal/persistent_storage_test.go
* Remove unused members
* Fix tests assert vs require, and usage of Eventually when not needed.
> [chore] fix nits in persistent queue implementation

- config/confighttp/compression_test.go
- config/confighttp/confighttp_test.go
- obsreport/obsreporttest/otelprometheuschecker.go
- processor/batchprocessor/metrics_test.go
- service/internal/proctelemetry/process_telemetry_test.go
- service/telemetry_test.go
Use http constants to replace numbers as parameters
_Please delete paragraphs that you did not …
> Use http constants to replace numbers as parameters

- docs/release.md
Updated the release schedule and removed the bit about adding a link to the top of the release notes for the contrib release as this is done automatically now.
> [chore] update release doc

- service/graph.go
- service/pipelines.go
- service/zpages.go
Follows #7201
The service.graph feature gate is now stable, so it cannot be changed. This PR removes the `zpagesPipeline` interface that supported the dual implementations of `service.pipelines`. It does not contain any user facing changes.
> Remove zpagesPipeline interface

- service/graph.go
- service/graph_test.go
- service/host.go
- service/pipelines.go
- service/pipelines_test.go
- service/service.go
- service/service_test.go
Follows #7201 
The `service.graph` feature gate is now stable, so it cannot be changed. This PR removes the code path to the previous implementation of the service pipelines since it is now unused. It does not contain any user facing changes. There will be further code to remove but this PR is limited to these initial steps:
- Remove usage of service.graph feature gate (without removing the feature gate itself)
- Remove service.pipelines interface
> Remove code path to unused service implementation

- obsreport/obsreport_exporter.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_scraper.go
- processor/batchprocessor/metrics.go
- service/internal/proctelemetry/process_telemetry.go
Some changes in the otel go sdk required changes here:
- Dimensionless -> "1"
- Bytes -> "By"
- Unit("s") -> "s"
> update otel go sdk calls

- service/pipelines.go
- service/zpages.go
This is a minor cleanup of the zpages constants in the service package.
- Move zpages constants from pipelines.go into zpages.go
- Use common naming format for all zpages constants
> Consolidate zpages constants

- docs/release.md
Several maintainers will be attending Kubecon the week of 4/17. I'm proposing to shift this release and subsequent released by one week.
> Propose to shift release v0.76.0 and subsequent releases by one week

- .chloggen/featuregateflag.yaml
- featuregate/flag.go
- featuregate/flag_test.go
- featuregate/flags.go
- featuregate/go.mod
- featuregate/go.sum
- featuregate/registry.go
- otelcol/collector_windows.go
- otelcol/command.go
- otelcol/flags.go
- otelcol/flags_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/7042
Uses direct values to/from a given registry. Simplifies usage, defers the "set" logic to the Registry.
> Replace existing featuregate.FlagValue with a direct apply version

- CONTRIBUTING.md
- docs/security-best-practices.md
Fix:https://github.com/open-telemetry/opentelemetry-collector/issues/6854
Added a nudge for [the configopaque package](https://pkg.go.dev/go.opentelemetry.io/collector/config/configopaque)  in the [security recommendations document](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.68.0/docs/security-best-practices.md#configuration) and also in the contributing doc under ["when adding a new component"](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.68.0/CONTRIBUTING.md#when-adding-a-new-component) section.
> Added security recommendation to use configopaque.String for sensitive fields

- CONTRIBUTING.md
Add rules in CONTRIBUTING.md that describe how to name types and functions that apply to a specific signal.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/7050
> [chore] Add naming conventions for signal-specific types

- .chloggen/fix_persistentstorage_deadlock.yaml
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_test.go
Fixing a potential deadlock in persistent queue initialization.
The queue maintains a channel of dummy items whose size should be equal to the queue size at all times. This makes it easier for consumers to wait when the queue is empty. During initialization, we simply add a dummy item to the channel for each queue item.
However, we also attempt to requeue items which were previously dispatched, but not sent, before this step, which actually does add dummy items to the channel as well. As a result, we could have more dummy items in the channel than there are actual items in the storage. This is normally not a big problem, as the queue will quietly discard the extraneous dummy items when it's empty.
It is, however, a problem, if this causes the dummy item channel to go over …
> [exporterhelper] fix deadlock when initializing persistent queue

- .github/workflows/milestone-add-to-pr.yml
Following the conversation in the SIG call on March 22, the github action in this PR will automatically add a merged PR to the first open milestone with `next version` name it finds.
I've tested this code in my fork
> [chore] update merged pull request w/ milestone (#293)

- .github/workflows/milestone-add-to-pr.yml
This solves the permission issue of pull request from remote forks.
> [chore] use pull_request_target in gh action

- .github/workflows/milestone-rotate.yml
This action triggers when a new release is published, updates the next release milestone to the title of the new release and creates a new next release milestone.
> [chore] add milestone rotation gh action

- .chloggen/fix_loggingexporter_exponential_histogram_buckets.yaml
- exporter/loggingexporter/internal/otlptext/databuffer.go
- exporter/loggingexporter/internal/otlptext/testdata/metrics/metrics_with_all_types.out
The interval notation used for displaying bucket boundaries of exponential histograms was incorrect.
Should be:
Negative buckets -> lower bound is inclusive, upper bound exclusive
Positive buckets -> lower bound is exclusive, upper bound inclusive
See: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#exponential-buckets
> The ExponentialHistogram bucket identified by index, a signed integer, represents values in the population that are greater than base\*\*index and less than or equal to base\*\*(index+1).
>
> The positive and negative ranges of the histogram are expressed separately. Negative values are mapped by their absolute value into the negative range using the same scale as the positive range. Note that in the negative …
> [loggingexporter] Fix display of bucket boundaries of exponential histograms

- exporter/loggingexporter/config.go
- exporter/loggingexporter/config_test.go
**Description:** Fixing a bug: Add omitempty to the LogLevel and Verbosity fields so that marshalling them drop deprecated fields
We are importing the logexporter to build our config but leaving the loglevel empty is not removing it from the marshalling since it doesn't have omitempty. Viceversa since the code only allows either LogLevel of Verbosity it makes sense to also omitempty Verbosity as well. 
The default values should handle cases where users don't specify these values. Once LogLevel is fully removed the Verbosity omitempty could be removed if so desired. 
**Testing:** Unit testing added
> [chore] Add omitempty for marshalling of logexporter

- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
Small refactor to how retryable status codes are handled that simplifies the flow a little bit. This shouldn't have any functional impact.
**Testing:**
Added unit tests to cover all retryable codes. Existing tests still pass.
> [chore] Small refactor to OTLP HTTP exporter status code handling

- receiver/doc.go
See discussion here https://github.com/open-telemetry/opentelemetry-collector/pull/7459#discussion_r1156077884
It is expected that the receivers should always retry, not just that they may retry.
> Clarify non-permanent error handling in receiver/doc.go

- .chloggen/logexporter-more-numbers.yaml
- exporter/loggingexporter/logging_exporter.go
Currently, we show the following numbers in non-detailed verbosity:
- log records that are written with confusing label `#logs`
- spans
- metrics which is not consistent with other places (e.g. batch processor) where we count data points instead.
This change adds resource metrics/logs/spans and data point counter with a consistent label naming to non-detailed verbosity output.
> [exporter/logging] Show more counters in not detailed verbosity

- .chloggen/batchprocessor-zeroconfig.yaml
- processor/batchprocessor/README.md
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
- processor/batchprocessor/config.go
- processor/batchprocessor/config_test.go
**Description:** Implement the fixes proposed in #7508. Otherwise, using a `batchprocessor` with `Config{}` passes validation but acts badly at runtime there is both a zero-duration timer and the call to `sendItems` never returns, constantly sending empty batches.
**Link to tracking Issue:** #7508.
**Testing:** Two new tests.
**Documentation:** Updated.
> Batch processor support for split-only configuration

- CONTRIBUTING.md
Updates CONTRIBUTING.md's `New Component` section to reflect most recent new component guidelines. Change made in parallel with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20881.
Related to discussion in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20853
> [chore] Update contributing components guidelines

- exporter/otlpexporter/config.go
OTLP exporter referencing itself as the OpenCensus exporter.
> [chore] fix typo in documentation

- docs/release.md
Adds note about when we will typically make a release for security-related issues. This introduces an informal 30 day SLA ([the tightest TTR SLA for Gitlab](https://about.gitlab.com/handbook/security/threat-management/vulnerability-management/#remediation-slas)) for security-related issues. Since we release every ~14 days, this means we will, in most cases, not make bugfix releases for security related issues. Critical vulnerabilities are added as an exception.
This relates to the discussion around CVE-2023-24534 and CVE-2023-24536.
> Add note about bugfix releases for security-relates issues

- service/telemetry.go
- service/telemetry_test.go
This is moving the code to initialize the prometheus endpoint into a separate func. This will allow us to run it multiple times if a user configures multiple prometheus endpoints via telemetry configuration. This will also allow us to move that code inside a switch to only enable it if users configure prometheus export.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/7533
Skipped the changelog since this is only affecting internals
> move prometheus init code

- exporter/README.md
Leftover from previous change in #5318.
The README misleadingly states that exporters must not modify the export data (or create and work on a copy). However, when the mutation capability is declared, the exporter will already receive a copy of data, and therefore it's not necessary to copy the data again in order to mutate it. I believe this section has been mistakenly left in the README during the work on #5318.
> [docs] Correct the exporter README section on data mutation

- receiver/doc.go
This expands the delivery guarantees introduced for network-based receivers to receivers that use checkpointing.
The purpose of the requirement is the same: to prevent data losses. See previous PR: https://github.com/open-telemetry/opentelemetry-collector/pull/4262
> Clarify checkpointing order for receivers

- .chloggen/connectors-stable.yaml
- otelcol/config_test.go
- otelcol/internal/sharedgate/sharedgate.go
- otelcol/otelcoltest/config_test.go
I believe the connectors codebase has proven to be very stable, as we haven't had to make any changes to support development of individual connectors. If there are no objections, I'd like to mark the gate stable ahead of the next release.
> Mark connectors as stable

- .chloggen/fix-send_failed_requests-counter.yaml
- obsreport/obsreport_exporter.go
- obsreport/obsreporttest/otelprometheuschecker.go
Signed-off-by: guiyong.ou <guiyong.ou@daocloud.io>
fix otelcol_exporter_send_failed_requests count error
fixed #7456
> fix otelcol_exporter_send_failed_requests count error

- Makefile
Otherwise contrib test checks on new releases will fail.
Fixes #7567
> [chore] enable replace for exporter/receiver modules

- CHANGELOG.md
- cmd/builder/go.mod
- cmd/builder/internal/builder/config.go
- cmd/builder/test/core.builder.yaml
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- component/go.mod
- confmap/go.mod
- connector/forwardconnector/go.mod
- consumer/go.mod
- examples/k8s/otel-config.yaml
- exporter/go.mod
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/ballastextension/go.mod
- extension/zpagesextension/go.mod
- featuregate/go.mod
- go.mod
- pdata/go.mod
- processor/batchprocessor/go.mod
- processor/memorylimiterprocessor/go.mod
- receiver/go.mod
- receiver/otlpreceiver/go.mod
- semconv/go.mod
- versions.yaml
Retracts v0.76.0 and v1.0.0-rc10. 
Supersedes https://github.com/open-telemetry/opentelemetry-collector/pull/7573
> Prepare release v0.76.0/v1.0.0-rcv0011

- examples/k8s/otel-config.yaml
Update k8s example to not use 0.0.0.0 on OTLP receiver endpoint 
**Link to tracking Issue:** close <#7572>
> [examples] Update k8s example to not use 0.0.0.0

- .chloggen/featuregate-remove-deprecated-functions.yaml
- featuregate/gate.go
- featuregate/registry.go
Removes deprecated `RemovalVersion` and `WithRegisterRemovalVersion` function.
https://github.com/open-telemetry/opentelemetry-collector/issues/7043
> [featuregate] Removed deprecated functions

- .chloggen/fix_configHTTPAuth.yaml
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
When request signing-based authentication extensions are used it is necessary to ensure that the Auth RoundTripper is the innermost as changes to the request by other RoundTrippers (such as compression or headers) may invalidate the request signature.  This change will ensure that the Auth RoundTripper is invoked after all others and is followed directly by the http.Transport.
> [config/confighttp] Ensure Auth happens after compression

- docs/release.md
More incremental improvements to the release doc.
> [chore] Incremental improvements to the release doc

- .chloggen/exporterhelper_default-queue-size.yaml
- exporter/exporterhelper/README.md
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage_test.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/otlpexporter/cfg-schema.yaml
Reduce the default queue size to 1000. Combined with the defaults on batchprocessor, the current default of 5000 is too much and will lead to an OOMKill in most environments if actually filled.
1000 is probably too high still, but we don't want to make too drastic of a change here at once. See linked issue for specifics.
**Link to tracking Issue:** #7359
**Documentation:** Updated the relevant README
> [exporterhelper]: reduce default queue size to 1000

- cmd/builder/internal/config/default.yaml
**Description:** upgrade core version default to 0.76.1
#7598
https://github.com/open-telemetry/opentelemetry-collector/issues/7598
**Testing:** 
using existing regression testing
none
> upgrade core version default to 0.76.1

- exporter/exporterhelper/obsreport.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_scraper.go
- processor/processorhelper/logs.go
- processor/processorhelper/metrics.go
- processor/processorhelper/traces.go
This removes the remaining references to components living in the `component` module. Fixes #6578
> [chore] clean up old references in docs

- .chloggen/forward-beta.yaml
- connector/forwardconnector/README.md
- connector/forwardconnector/forward.go
This also updates the readme to indicate correctly the distributions that already contain the connector.
> Mark forward connector as beta

- .chloggen/add-deprecated-stage-to-readme.yaml
- featuregate/README.md
- featuregate/flag_test.go
- featuregate/registry.go
- featuregate/registry_test.go
- featuregate/stage_test.go
Updates the new `StageDeprecated` stage to work like `StageStable` but false.  `StageDeprecated` is now no longer changeable and expects a `ToVersion` value to be included when used.  Also fixes a defect where `StageDeprecated` caused an `unknown stage` error on register.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/7043
**Testing:** 
Added tests for `StageDeprecated`
Updated featuregate README to include how `deprecated` is used when a feature is abandoned in `alpha`.
> [featuregate] Fix issue where StageDeprecated cause an error on register

- docs/release.md
Updates based on releasing Contrib and Release repos.
I encountered this error when pushing the tags in Contrib despite previous tags pushing as expected.  
```bash
pushing tag exporter/googlemanagedprometheusexporter/v0.77.0
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 400 bytes | 9.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
remote: fatal error in commit_refs
To https://github.com/open-telemetry/opentelemetry-collector-contrib.git
! [remote rejected]       exporter/googlemanagedprometheusexporter/v0.77.0 -> exporter/googlemanagedprometheusexporter/v0.77.0 (failure)
error: failed to push some refs to 'https://github.com/open-telemetry/opentelemetry-collector-contrib.git'
make: *** [push-tags] Error 1
```
I didn't …
> [chore] Update release docs based on 0.77.0 release

- .chloggen/codeboten_add-featuregate-telemetry.yaml
- internal/obsreportconfig/obsreportconfig.go
- service/service.go
- service/telemetry.go
- service/telemetry/config.go
- service/telemetry_test.go
This adds the feature-gate `telemetry.useOtelWithExtendedConfigurationForInternalTelemetry` to start adding support for additional exporters for the collector's internal telemetry.
This is part of of https://github.com/open-telemetry/opentelemetry-collector/pull/7644
> add feature gate for supporting additional exporters

- .chloggen/fix_persistentstorage_disk-full.yaml
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_test.go
Description:
Make the persistent storage handle not having any available disk space more gracefully. Right now, it may be impossible to actually delete items from the storage in that scenario.
The actual fix is pretty simple, most of the additions in this PR are test code and mocks necessary to even show the problem. The added test does actually fail without the fix.
Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector/issues/7198
Testing:
Added a mock storage with the specific behavior required, and a test that fails without the fix.
> [exporterhelper] Fix persistent storage behaviour with no available space on device

- .chloggen/prepare-featuregate-for-rc.yaml
- versions.yaml
Moves the `featuregate` module to the stable module-set so that in the next release we provide a release candidate.
Closes https://github.com/open-telemetry/opentelemetry-collector/milestone/30
> [featuregate] Move to stable module-set

- Makefile
If a new module is added to a module set or moved from another module set, the release should be required.
> [chore] Update check-changes make target to work with new modules

- .chloggen/fixbatcherror.yaml
- processor/batchprocessor/batch_processor.go
> Fix return error for batch processor when consuming Metrics and Logs

- processor/batchprocessor/batch_processor_test.go
This refactors the batch processor tests to make testing multiple configuration scenarios easier. It adds a testcase for a batch processor w/ metadata keys.
> add benchmark test for multi batch processing

- .chloggen/deprecate-get-exporters.yaml
- component/componenttest/nop_host_test.go
- component/host.go
- service/host.go
- service/internal/graph/graph.go
> Deprecate component.Host.GetExporters

- config/configtls/README.md
**Documentation:** Fix code reference to upstream Go TLS package code line.
The link to upstream Golang crypto/tls code line is wrong, because it was changed since Go release 1.19.
I suggest to use commit reference instead of volatile master branch.
```
https://github.com/golang/go/blob/ed9db1d36ad6ef61095d5941ad9ee6da7ab6d05a/src/crypto/tls/common.go#L700
```
Alternative fix would be to use release branch reference (a bit riskier).
```
https://github.com/golang/go/blob/release-branch.go1.19/src/crypto/tls/common.go#L700
```
Let me know if you prefer this to be referenced using Go release branch so I change the PR.
> [docs] fix code reference in configtls readme

- processor/batchprocessor/README.md
**Description:** This PR improves the description of the `send_batch_size` configuration option in the batch processor. The current documentation may not be 100 percent clear to new users of the processor. This change seeks to add clarification that `send_batch_size` is just a trigger to send and does not enforce limits. 
**Link to tracking Issue:** none, but this caught me off guard a bit. This change would have helped me build a better mental model of the processors capability. 
**Testing:** n/a
**Documentation:** n/a
> [chore][processor/batch] Update description of send_batch_size

- processor/batchprocessor/config.go
`SendBatchSize` godoc was incorrectly saying that a value of 0 implies ignoring the timeout.
> [chore] minor fix in the doc

- .chloggen/add-connectors-to-components-command.yaml
- otelcol/command_components.go
- otelcol/command_components_test.go
- otelcol/configprovider_test.go
- otelcol/factories_test.go
- otelcol/testdata/otelcol-nop.yaml
Add connector components to the output of the `components` command.
**Testing:**
Unit tests
> [otelcol] Add connectors to the components command

- receiver/receivertest/contract_checker.go
- receiver/receivertest/contract_checker_test.go
- Added a CheckConsumeContract() helper func that can be used to test the contract that receivers are expected to maintain for Consume() calls.
- Added an example usage of CheckConsumeContract() helper.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/7478
> Add receiver/consumer contract test helper

- .chloggen/connectors-wrap-mutates.yaml
- service/internal/graph/graph_test.go
- service/internal/graph/nodes.go
- service/internal/testcomponents/example_connector.go
Resolves #7776
The collector copies data whenever handing it to components that may mutate it. The point at which a copy must be made is within a fanout consumer. There are two points at which a fanout consumer may be placed:
1. Immediately after a receiver shared by multiple pipelines
2. Immediately before multiple exporters of a single pipeline
When data is fanned out _to_ a connector (acting as an exporter), we must ensure that the fanout consumer before exporters (point 2 above) is able to take into account whether or not the connector will be handing the data off to a pipeline that will mutate the data.
> Incorporate next consumer's capabilities into connector capabilities

- docs/processing.md
These changes fix a spelling mistake made within `docs/processing.md`.
In `docs/processing.md`, instances of a misspelled word - `tranformation` - has been corrected to `transformation`, [following the Merrier-Webster spelling of the word.](https://www.merriam-webster.com/dictionary/transformation)
> Fix: Correct spelling of transformation in docs/processing.md.

- Makefile
Don't prefix the version number w/ a `v` as the docs already tell the release manager to do so, plus this way it's easier to copy/paste the version from the module set.
> [chore] update check-changes to match the release docs

- .chloggen/add-tls-settings-from-memory.yaml
- config/configgrpc/configgrpc_test.go
- config/confighttp/confighttp_test.go
- config/configtls/README.md
- config/configtls/configtls.go
- config/configtls/configtls_test.go
- receiver/otlpreceiver/otlp_test.go
**Description:** This implements a version of the proposed changes requested in the linked issue.
**Related:** A [PR](https://github.com/prometheus/common/pull/472) accomplishing similar was accepted into Prometheus recently.
**Link to tracking Issue:** #7313
**Testing:** Added tests for a variety of scenarios around filepath vs in memory certs.
**Documentation:** Added new parameters to the README
> Add support to TLSSetting to not only read from file path, but from memory

- .github/workflows/build-and-test.yml
Previously, we [introduced linux/arm to the cross build tests](https://github.com/open-telemetry/opentelemetry-collector/pull/5472) in the CI to add an armv7 release. 
However, without specifying the `GOARM` variable, it falls back to the default value. The default value is not always `7` as it depends on the platform that we are building on. [There are changes to default to GOARM=7 for all non-arm systems in the upcoming golang version](https://go-review.googlesource.com/c/go/+/470695)
We are building on `linux/amd64` machine in github action so `GOARM` defaults to `5` which is different from what we want. 
In this pull request, I added `GOARM` as an environment variable and `goarm` in the arm matrix option so we can explicit set `GOARM=7`. 
**Testing:** 
Able to run …
> [ci] Specify 7 as arm version for arm build in CI

- .chloggen/always_fanout.yaml
- service/internal/graph/nodes.go
This is an implementation of https://github.com/open-telemetry/opentelemetry-collector/pull/7673#issuecomment-1572126437 which resolves some inconsistencies regarding fanout consumers and connectors. It updates the connector code to always pass a fanout consumer to connector factory functions (even if the connector emits to a single pipeline). This will likely pair with the work in #7673 to add helpers to construct connector routers (when needed) for tests.
**Link to tracking Issue:** #7672, #7673
**Testing:**
Unit testing
cc: @bogdandrutu @djaglowski
> Always pass fanout consumers to connector factory functions

- service/service_test.go
There appears to be a flake in waiting for resources being released within tests:
```
service_test.go:345: 
Error Trace:	/home/runner/work/opentelemetry-collector/opentelemetry-collector/service/service_test.go:345
Error:      	Received unexpected error:
Get "http://localhost:8888/metrics": dial tcp [::1]:8888: connect: connection refused
Test:       	TestServiceTelemetryRestart
```
See test run: https://github.com/open-telemetry/opentelemetry-collector/actions/runs/5267677421/jobs/9523273917?pr=7703
NA
**Testing:**
NA
NA
> [service] Ensure test service eventually connects to telemetry port on restart

- .chloggen/codeboten_split-config-mod.yaml
- .github/dependabot.yml
- Makefile
- cmd/builder/test/core.builder.yaml
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- component/go.mod
- config/configcompression/Makefile
- config/configcompression/go.mod
- config/configcompression/go.sum
- connector/forwardconnector/go.mod
- connector/go.mod
- consumer/go.mod
- exporter/go.mod
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- extension/auth/go.mod
- extension/ballastextension/go.mod
- extension/go.mod
- extension/zpagesextension/go.mod
- go.mod
- processor/batchprocessor/go.mod
- processor/go.mod
- processor/memorylimiterprocessor/go.mod
- receiver/go.mod
- receiver/otlpreceiver/go.mod
- versions.yaml
> split config/configcompression into its own module

- .chloggen/msg_introduce-timeout-scrape.yaml
- receiver/scraperhelper/scrapercontroller.go
- receiver/scraperhelper/settings.go
- receiver/scraperhelper/settings_test.go
This introduces a change that each scraper context is cancelled by the next collection period.
NA
**Testing:**
It requires integration tests against both core and contrib.
Add comments to the collection interval to explain usage.
**Alternative**
I had considered adding a new field named `Timeout` which would require to be equal or less than collection interval.
However, since a lot of scrapers already have adopted a timeout fields, I worry about potential conflicts so I opted for this approach.
> [scraper helper] Include support for timeout

- .chloggen/http-server-headers-config.yaml
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
Add `headers` configuration option on HTTPServerSettings. It allows for additional headers to be attached to each HTTP response sent to the client
#7328
**Testing:**
I've added a test case that ensures the code still works with `nil` or an empty map along with one with a set of headers 
I've added comments in the struct, I imagine it will automatically be included in the doc?
> Add headers to HTTPServerSettings

- .chloggen/builder-skip-generate.yaml
- cmd/builder/README.md
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/main.go
- cmd/builder/internal/builder/main_test.go
- cmd/builder/internal/command.go
- cmd/builder/internal/command_test.go
This option makes the builder skip generating sources.
**Link to tracking Issue:** #7541
**Documentation:** as part of the CLI help menu
> [cmd/builder] Add option to skip generating sources

- .chloggen/add-zstd-decompression.yaml
- .chloggen/fix-unsupported-content-encoding-bug.yaml
- config/confighttp/compression.go
- config/confighttp/compression_test.go
- receiver/otlpreceiver/otlp_test.go
This adds ability to decompress zstd-compressed HTTP requests to all receivers that use HTTPServerSettings.
Also added missing error handling for the case when an unsupported compression type was used in the request. Now it correctly returns 400 Bad Request. Also added a unit test to verify this case.
Once this is merged I will submit a PR in contrib repo to add end-to-end tests that use zstd compression in the testbed.
> Add zstd decompression support to HTTPServerSettings

- internal/tools/go.mod
- internal/tools/go.sum
The version that supports -tags is now in the main repo.
> [chore] update go-jsonschema

- .github/workflows/perf.yml
Doing this will require a write token, to be able to update the branch. Will attempt to re-enable this once renovabot permissions are sorted out
> [chore] disable writing benchmark results for now

- .chloggen/otlphttp-partial-success.yaml
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
Handle partial success messages returned from OTLP HTTP backends.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6686
**Testing:**
Unit tests. I was able to manually test partial success messages when submitting metrics to a vendor backend. I'd welcome any additional places to test this.
> Handle partial success responses in the OTLP HTTP exporter

- .chloggen/codeboten_add-option-for-decompressor.yaml
- config/confighttp/compression.go
- config/confighttp/compression_test.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
This provides the ability to add support for compression types which are not supported in core, to be supported by individual components.
This change addresses an issue caused by https://github.com/open-telemetry/opentelemetry-collector/pull/7927, which prevents receivers that use confighttp from adding support for their content-encoding types easily. They still can by implementing an error handler, but that seems messy.
An alternative to this PR is to not return an error for an unsupported encoding type as was the case before https://github.com/open-telemetry/opentelemetry-collector/pull/7927
If the approach is acceptable, I will add the unit tests and changelog
> add support for additional decoders

- pdata/pcommon/map.go
- pdata/pcommon/map_test.go
EnsureCapacity was incorrectly clearing the Map when increasing the capacity. It will now correctly preserve existing elements.
> [pdata] Fix Map.EnsureCapacity bug when the Map is not empty

- CONTRIBUTING.md
adding a linkable title for end-user impacting changes to the contributing guide.
> [chore] add title

- .github/workflows/api-compatibility.yml
- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/changelog.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
- .github/workflows/create-dependabot-pr.yml
- .github/workflows/perf.yml
- .github/workflows/prepare-release.yml
**Description:** Update go minimum version used in workflows to `1.19.11` and `1.20.6` respectively.
> [chore] Update go version used in github workflows

- Makefile
- internal/tools/go.mod
- internal/tools/go.sum
The logic from `check-changes` was moved to multimod diff.
Fixes #8012
> [chore] use multimod diff

- .chloggen/otlphttpexporter-trailing-slash.yaml
- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/factory_test.go
This makes it so we don't put a double slash on the endpoint for otlphttp when it exists.
The spec says that this kind of stuff should be handled w.r.t. the OTEL_EXPORTER_OTLP_ENDPOINT env var and says nothing about programmatic handling of this config. But I still think it's a worthwhile change on a common-ish[1] ergonomic issue.
[1] while the collector isn't the only source of this, at honeycomb we emitted an error related to a misconfigured otlphttp endpoint ~2.5 million times over the past month
fixes https://github.com/open-telemetry/opentelemetry-collector/issues/8084
> Handle trailing slash on endpoint for otlphttp

- .chloggen/msg_cleanup-scraper-helper.yaml
- receiver/scraperhelper/scrapercontroller.go
- receiver/scraperhelper/scrapercontroller_test.go
- receiver/scraperhelper/settings.go
- receiver/scraperhelper/settings_test.go
- Reduce the complexity required in order to override values within components
- Address feedback from https://github.com/open-telemetry/opentelemetry-collector/pull/7703#discussion_r1235257542
N/A
**Testing:** 
Added tests for additional options
Documentation to be added to affected components in contrib
> [scraper helper] improve ease of use of scraper controller settings

- .chloggen/codeboten_update-jsonschema-0001b0391785d880ce052f4c6fd85c5a4e0474fa.yaml
> fix changelog

- .chloggen/codeboten_may-29-otlp-export.yaml
- exporter/otlpexporter/go.mod
- exporter/otlpexporter/go.sum
- exporter/otlphttpexporter/go.mod
- exporter/otlphttpexporter/go.sum
- extension/zpagesextension/go.mod
- extension/zpagesextension/go.sum
- go.mod
- internal/testutil/testutil.go
- service/internal/proctelemetry/config.go
- service/internal/proctelemetry/config_test.go
- service/telemetry.go
- service/telemetry/config.go
- service/telemetry/config_test.go
- service/telemetry_test.go
This enables end users to configure additional prometheus exporters for the collector's telemetry
via the `readers` configuration option. Configuring prometheus through the existing method
of setting the service::metrics::address will continue to work, and only log a warning for users
who have enabled the `telemetry.useOtelWithSDKConfigurationForInternalTelemetry` feature gate.
Linked issue: #7641
This is a follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/7679
> [wip] add ability to configure prometheus export via `readers`

- .github/workflows/build-and-test.yml
This is using the same gh action as in contrib to
address failing coverage upload actions.
Fix https://github.com/open-telemetry/opentelemetry-collector/issues/7131
> [chore] add retry for coverage upload

- .chloggen/codeboten_add-console-exporter.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/go.sum
- go.mod
- go.sum
- service/internal/proctelemetry/config.go
- service/internal/proctelemetry/config_test.go
- service/telemetry/config.go
- service/telemetry/config_test.go
Internal metrics can now be additionally configure to export using the stdout exporter.
Linked issue: https://github.com/open-telemetry/opentelemetry-collector/issues/7641
> add stdout exporter support

- .chloggen/codeboten_add-periodic-internal-timeout.yaml
- service/internal/proctelemetry/config.go
- service/internal/proctelemetry/config_test.go
This adds support for configuring `timeout` and `interval` options for the periodic metric exporter.
Linked issue: #7641
> add support for periodic reader interval/timeout

- .chloggen/codeboten_add-tracer-provider.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/go.sum
- go.mod
- go.sum
- service/internal/proctelemetry/config.go
- service/internal/proctelemetry/config_test.go
- service/service.go
- service/telemetry.go
- service/telemetry/config.go
- service/telemetry/config_test.go
- service/telemetry_test.go
This PR adds support for configuring batch span processor for internal
collector traces. It adds support to export them via the stdout exporter.
Linked issue https://github.com/open-telemetry/opentelemetry-collector/issues/8106
Follows https://github.com/open-telemetry/opentelemetry-collector/pull/8097
> add span processor configuration

- Makefile
This PR reverts #8024, as it introduced a new behavior, causing the release to be blocked.
Apparently, multimod has a return code of 1 when diffs are seen, causing the prepare-release target to break. After this release, we can try to get multimod to behave in the same way as this PR.
> Revert usage of multimod for diff between versions

- .github/workflows/api-compatibility.yml
- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/changelog.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
- .github/workflows/create-dependabot-pr.yml
- .github/workflows/perf.yml
- .github/workflows/prepare-release.yml
To resolve the govulncheck reports:
```
Vulnerability #1: GO-2023-1987
Large RSA keys can cause high CPU usage in crypto/tls
More info: https://pkg.go.dev/vuln/GO-2023-1987
Standard library
Found in: crypto/tls@go1.19.11
Fixed in: crypto/tls@go1.21rc4
Example traces found:
Error:       #1: service/internal/proctelemetry/config.go:299:27: proctelemetry.initOTLPgRPCExporter calls otlpmetricgrpc.New, which eventually calls tls.Conn.Handshake
Error:       #2: service/internal/proctelemetry/config.go:156:39: proctelemetry.InitPrometheusServer calls http.Server.ListenAndServe, which eventually calls tls.Conn.HandshakeContext
Error:       #3: service/service.go:251:36: service.buildResource calls uuid.NewRandom, which eventually calls tls.Conn.Read
Error:       #4: service/config.go:35:13: …
```
> [chore] Upgrade go version in CI

- .chloggen/configwatcher-interface.yaml
- .chloggen/extension-effective-config.yaml
- .chloggen/servicesettings-confmap.yaml
- extension/extension.go
- otelcol/collector.go
- otelcol/collector_test.go
- otelcol/configprovider.go
- otelcol/configprovider_test.go
- service/extensions/extensions.go
- service/extensions/extensions_test.go
- service/service.go
- service/service_test.go
This adds an optional `ConfigWatcher` interface that extensions can implement if they want to be notified of the effective configuration that is used by the Collector.
I don't feel very strongly about any of the decisions I made in this PR, so I am open to input if we would like to take a different approach anywhere. I will leave some comments to explain the decisions I made.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/6596
**Testing:**
I've made minimal unit test changes, but I expect to write more tests once there is consensus on the direction for implementing this functionality. I have done some manual testing to show that an extension can get a YAML representation of the effective config using two YAML input …
> Notify extensions of the Collector's effective configuration

- .github/workflows/build-and-test.yml
To not update required jobs every time a new go version is released.
Needed for https://github.com/open-telemetry/opentelemetry-collector/pull/8208
> [chore] [CI] Add a unittest job without a matrix

- .chloggen/otlp_with_authority.yaml
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
This adds support for configuring `authority` dial option for grpc exporter
> Add support for :authority pseudo-header for grpc client

- Makefile
This is no longer used as the build version information comes from the builder configuration. I've removed the VERSION variable as well, as it's only used in chlog-update and it's passed into the command.
> [chore] remove BUILD_INFO

- .chloggen/exporter-helper-v2.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/constants.go
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_batch.go
- exporter/exporterhelper/internal/persistent_storage_test.go
- exporter/exporterhelper/internal/request.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/request.go
- exporter/exporterhelper/request_test.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
Introduce a new exporter helper that operates over client-provided requests instead of pdata. The helper user now has to provide `Converter` - an interface with a function implementing translation of pdata Metrics/Traces/Logs into a user-defined `Request`. `Request`  is an interface with only one required function `Export`.
It opens a door for moving batching to the exporter, where batches will be built from client data format, instead of pdata. The batches can be properly sized by custom request size, which can be different from OTLP. The same custom request sizing will be applied to the sending queue. It will also improve the performance of the sending queue retries for non-OTLP exporters, they don't need to translate pdata on every retry.
This is an implementation alternative to …
> [exporterhelper] New exporter helper for custom requests

- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
This change adds collector's internal metrics and tracing to the new request-based exporter helpers. Only those metrics and traces are added that are already adopted by the existing exporter helpers for backward compatibility. The new exporter helpers can and should expose more metrics in the future, e.g. for tracking converter errors.
This PR is built on top of https://github.com/open-telemetry/opentelemetry-collector/pull/8178
Only the second commit contains exclusive changes
Tracking Issue: https://github.com/open-telemetry/opentelemetry-collector/issues/8122
> [exporterhelper] Add observability to the new exporter helper

- config/confighttp/confighttp_test.go
To resolve a linter complain after bumping github.com/golangci/golangci-lint: https://github.com/open-telemetry/opentelemetry-collector/actions/runs/5947424448/job/16129479734?pr=8268
```
Error: confighttp_test.go:711:15: G601: Implicit memory aliasing in for loop. (gosec)
CORS:     &tt.CORSSettings,
```
> [chore] [config/confighttp] Remove loop memory aliasing in a test

- .chloggen/exporter-helper-v2.yaml
Cut from https://github.com/open-telemetry/opentelemetry-collector/pull/8248
> [chore] [exporterhelper] Clarify new exposed APIs in the changelog

- .chloggen/handle-http-response-partial-success.yaml
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
Fix the handling of the HTTP response to  ignore responses not encoded as protobuf
Fixes #8263
> [exporter/otlphttpexporter] Partial success HTTP response handling

- .chloggen/codeboten_add-otlp-trace-exporter.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/go.sum
- exporter/otlphttpexporter/go.sum
- go.mod
- go.sum
- service/internal/proctelemetry/config.go
- service/internal/proctelemetry/config_test.go
- service/telemetry/config.go
- service/telemetry/config_test.go
This PR adds support for exporting internal collector traces via the
OTel Go OTLP exporters.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/8106
~Follows https://github.com/open-telemetry/opentelemetry-collector/pull/8117~
> add OTLP export support for internal traces 

- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
> [chore] add error message on parsing bad protobuf response

- exporter/exporterhelper/internal/persistent_storage_test.go
- exporter/exporterhelper/queued_retry_test.go
The method was removed from the Request interface in https://github.com/open-telemetry/opentelemetry-collector/pull/8178, so the implementation on the test structs is not required anymore
> [chore] [exporterhelper] Remove redundant Marshal methods from test structs

- cmd/builder/internal/builder/templates/go.mod.tmpl
Explicitly require `github.com/knadh/koanf/maps` and `github.com/knadh/koanf/providers/confmap` in go.mod to workaround ambiguous imports. Otherwise, the command fails with:
```
Error: failed to update go.mod: exit status 1. Output:
go: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol imports
github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector imports
go.opentelemetry.io/collector/confmap imports
github.com/knadh/koanf/maps: ambiguous import: found package github.com/knadh/koanf/maps in multiple modules:
github.com/knadh/koanf v1.5.0 (/Users/danoshin/go/pkg/mod/github.com/knadh/koanf@v1.5.0/maps)
github.com/knadh/koanf/maps v0.1.1 (/Users/danoshin/go/pkg/mod/github.com/knadh/koanf/maps@v0.1.1)
go: …
```
> [chore] [cmd/builder] Require github.com/knadh/koanf submodules

- CONTRIBUTING.md
> Define guideline for components to deprecate config options

- .github/workflows/scripts/release-create-tracking-issue.sh
Make the filtering for existing issues strict to avoid picking unrelated issues. This happened in during 0.84.0 release
```
+ RELEASE_VERSION=v/v0.84.0
+ '[' '' == '' ']'
+ RELEASE_VERSION=v0.84.0
+ '[' 0.84.0 == '' ']'
++ gh issue list --search 'Release v0.84.0' --json url --jq '.[].url' --repo open-telemetry/opentelemetry-collector
+ EXISTING_ISSUE=https://github.com/open-telemetry/opentelemetry-collector/issues/8063
+ '[' https://github.com/open-telemetry/opentelemetry-collector/issues/8063 '!=' '' ']'
+ echo 'Issue already exists: https://github.com/open-telemetry/opentelemetry-collector/issues/8063'
+ exit 0
Issue already exists: https://github.com/open-telemetry/opentelemetry-collector/issues/8063
```
> [chore] Fix release issue creation script

- docs/release.md
The following changes are applied:
1. Move the contrib draft PR creation to the first step. This is required to be done before the core release, because some changes may be needed in the core codebase to resolve possible core/contrib integration issues which was the case with the 0.84.0 release.
2. Add a missing `v` prefix for OTEL_RC_VERSION env var in step 8.
3. Rotate the schedule
4. Update 0.55.0 version in the examples to 0.85.0. It was inconsistent with using the latest version for the stable module set
5. Mention CHANGELOG-API in step 7
> [chore] Update the release doc

- .chloggen/components-command-with-stability-levels.yaml
- otelcol/command_components.go
- otelcol/command_components_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9518
Example output:
```
buildinfo:
command: otelcorecol
description: Local OpenTelemetry Collector binary, testing only.
version: 0.83.0-dev
receivers:
- name: otlp
stability:
logs: Beta
metrics: Stable
traces: Stable
processors:
- name: memory_limiter
stability:
logs: Beta
metrics: Beta
traces: Beta
- name: batch
stability:
logs: Stable
metrics: Stable
traces: Stable
exporters:
- name: logging
stability:
logs: Development
metrics: Development
traces: Development
- name: otlp
stability:
logs: Beta
metrics: Stable
traces: Stable
- name: otlphttp
stability:
logs: Beta
metrics: Stable
traces: Stable
connectors:
- name: forward
stability:
logs-to-logs: Beta
logs-to-metrics: Undefined
logs-to-traces: Undefined …
```
> Add stability levels to components output

- config/configauth/README.md
- config/configgrpc/README.md
- config/confighttp/README.md
- receiver/otlpreceiver/README.md
Based on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26352, I realized that the confighttp and configgrpc helpers lack links to the configauth package. This PR fixes that and updates the list of known authenticators.
> Improve configauth docs

- .github/workflows/api-compatibility.yml
- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/changelog.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
- .github/workflows/create-dependabot-pr.yml
- .github/workflows/perf.yml
- .github/workflows/prepare-release.yml
- .github/workflows/tidy-dependencies.yml
**Description:** This is a defensive PR to update the minimum go version used in the collectors github actions workflows. The latest go patch version contains fixes for a CVE that could affect a go build tool chain.
> [chore] Update go version used in workflows to ~1.28.8

- .chloggen/disable_keep_alives.yaml
- config/confighttp/README.md
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
Add option to disable HTTP keep-alives which helps in better load balancing in k8s clusters when otlphttp exports are used to send logs to otlp receivers
**Link to tracking Issue:**  #8260
> [confighttp] Add option to disable HTTP keep-alives

- confmap/provider/internal/configurablehttpprovider/testdata/otel-config.yaml
- service/README.md
These should have been updated some time ago when loglevel was replaced by verbosity.
> [chore] update references to loglevel

- processor/batchprocessor/metrics.go
This PR updates the instantation of otel instruments in the batch processor to use multierr instead of returning on the first error it encounters. This aligns w/ other places in the code where we instatiate otel instruments.
> [chore] consistently use multierr in otel instatiation

- .chloggen/exporterhelper-avoid-messages.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/traces.go
Separate all the parts of the baseExporter into an explicit chain of request senders. It makes it easier to follow the data flow and add additional senders. 
This change also removes the baseSettings, because keeping the settings is not needed anymore. All the options update the internal senders in place.
This change also removes confusing error messages like "Exporting failed. Dropping data. Try enabling sending_queue to survive temporary failures" when the Queue is not even available in the exporter (WithQueue option is not applied) which means users don't `sending_queue` config option. Now, such messages are only shown when the sending_queue (or retry_on_failure) is available, but not enabled by the user.
> [exporterhelper] Refactor options and baseExporter

- .chloggen/config-unmarshel-slice-bug.yaml
- confmap/confmap.go
- confmap/confmap_test.go
fix the bug of unmarshalling slice values for package confmap
fix #4001
> [confmap] fix bug of unmarshalling slice values

- .chloggen/s390x-platform-enablement.yaml
- .github/workflows/build-and-test.yml
The `s390x` CPU architecture is the base for IBM zSeries (aka mainframe) systems. It is beneficial for users of this platform to have a supported way to install pre-compiled binaries for the OpenTelemetry collector in a Linux environment. This issue and associated pull requests will enable the building of all relevant binary artifacts for `linux/s390x` as part of the regular CI pipeline.
IBM has performed tests internally to ensure successful build (via cross-compilation) and runtime (on native platform) integrity of the OpenTelemetry collector (core and contrib) via the unit test suites and specific use-cases.
For more information and discussion please refer to the initial feature request issue (open-telemetry/opentelemetry-collector-releases#378).
Resolves: #8213
> Add support for linux/s390x architecture

- config/configtls/clientcasfilereloader_test.go
Data race occurs when the `testLoader.loadClientCAFile()` and `testLoader.returnErrorOnSubsequentCalls()` are called concurrently. 
fix #8395
> [chore] fix race condition in test of configtls

- .chloggen/builder-env.yaml
- cmd/builder/internal/command.go
**Description:** partially fix loading builder config from the env. This moves the env option from unusable (wrong parsing of nested keys), to usable for the `dist.*` settings, but not for any of the components/modules, which will require more complex parsing for arrays.
**Link to tracking Issue:** #8239
**Testing:** try running it locally
> fix builder config from env

- .chloggen/fix-incorrect-use-of-fsnotify.yaml
- config/configtls/clientcasfilereloader.go
**Description:** fix #8438
**Link to tracking Issue:**  #8438
> fix incorrect use of fsnotify in configtls

- .chloggen/codeboten_rm-pipelineconfig.yaml
- service/config.go
This was deprecated a few versions ago
> [service] remove deprecated service.PipelineConfig

- .chloggen/codeboten_obsreport-dep.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/obsexporter.go
- exporter/exporterhelper/obsexporter_test.go
- exporter/exporterhelper/obsreport.go
- exporter/exporterhelper/obsreport_test.go
- obsreport/obsreport_exporter.go
- obsreport/obsreporttest/obsreporttest_test.go
This aligns better with the other new methods in the various helper modules.
> rename exporterhelper obsreport method

- .chloggen/log-featuregates.yaml
- featuregate/registry.go
I found myself troubleshooting an issue with a feature gate not being accepted and found this to be helpful.
Usage:
```
./bin/otelcorecol --feature-gates=fake
Error: invalid argument "fake" for "--feature-gates" flag: no such feature gate "fake". valid gates: [confmap.expandEnabled telemetry.disableHighCardinalityMetrics telemetry.useOtelForInternalMetrics telemetry.useOtelWithSDKConfigurationForInternalTelemetry]
```
> List valid feature gates when failing to load invalid gate

- docs/release.md
Since we now have support tiers defined, we can clarify what platforms allow for a bugfix release
> [docs/release] Specify platform tier for bugfix releases

- pdata/internal/cmd/pdatagen/internal/packages.go
To avoid warnings thrown by `make genpdata`:
```
go run pdata/internal/cmd/pdatagen/main.go
/Library/Developer/CommandLineTools/usr/bin/make fmt
package go.opentelemetry.io/collector/internal/fanoutconsumer
imports go.opentelemetry.io/collector/component
imports go.opentelemetry.io/collector/pdata/pcommon
imports go.opentelemetry.io/collector/pdata/internal
imports go.opentelemetry.io/collector/pdata/internal: import cycle not allowed
package go.opentelemetry.io/collector/internal/fanoutconsumer
imports go.opentelemetry.io/collector/component
imports go.opentelemetry.io/collector/pdata/pcommon
imports go.opentelemetry.io/collector/pdata/internal
imports go.opentelemetry.io/collector/pdata/internal: import cycle not allowed
```
The invalid imports are removed by `go fmt` after that anyway, …
> [chore] [pdata] don't generate a cycle import in the internal package

- docs/troubleshooting.md
Remove bits mentioning configuration on versions v0.42.0 or below and versions v0.35.0 and below.
These versions are more than 2 years old, and users can always switch to the docs when their version was released.
> [docs] Simplify troubleshooting doc

- .chloggen/codeboten_rm-ignore-err.yaml
- exporter/debugexporter/go.mod
- exporter/debugexporter/go.sum
- exporter/exporterhelper/obsexporter.go
- exporter/go.mod
- exporter/loggingexporter/go.mod
- exporter/loggingexporter/go.sum
- exporter/otlpexporter/go.mod
- exporter/otlpexporter/go.sum
- exporter/otlphttpexporter/go.mod
- exporter/otlphttpexporter/go.sum
- processor/batchprocessor/metrics.go
- processor/go.mod
- processor/memorylimiterprocessor/go.mod
- processor/memorylimiterprocessor/go.sum
- processor/processorhelper/obsreport.go
- receiver/go.mod
- receiver/receiverhelper/obsreport.go
- receiver/scraperhelper/obsreport.go
- service/internal/proctelemetry/process_telemetry.go
The workaround had been put in place because of a restriction on `/` characters in the name of the instrument. This is no longer an issue. This PR fixes https://github.com/open-telemetry/opentelemetry-collector/issues/8346
Follows https://github.com/open-telemetry/opentelemetry-collector/pull/8574
> remove workaround to ignore for errors when creating instruments

- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/retry_sender_test.go
Cut from https://github.com/open-telemetry/opentelemetry-collector/pull/8275
> [chore] [exporterhelper] Remove redundant test helper

- .chloggen/codeboten_rm-deprecated68.yaml
- service/extensions/extensions.go
- service/extensions/extensions_test.go
This was deprecated many versions ago, should have been removed but i suspect was missed due to typo.
> [chore] remove code that was deprecated some time ago

- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
**Description:** Validate number of consumers in exporterhelper
This is a very small bug fix that does not even deserve a changelog entry. The collector will not work if a queue with a number of consumers <= 0 is used, so we should fail loudly instead of just hanging not draining the data from the queue.
**Testing:** UTs were added.
> [chore]: Validate number of consumers in exporterhelper

- CHANGELOG-API.md
- CHANGELOG.md
The first iteration doesn't affect the end users. So moving it from user to API changelog
> [chore] Update changelog entry for the recent pdata functionality

- .github/workflows/api-compatibility.yml
- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/changelog.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
- .github/workflows/create-dependabot-pr.yml
- .github/workflows/perf.yml
- .github/workflows/prepare-release.yml
- .github/workflows/tidy-dependencies.yml
This addresses https://pkg.go.dev/vuln/GO-2023-2102
> [chore] bump go versions

- obsreport/obsreporttest/otelprometheuschecker.go
When looking at https://github.com/open-telemetry/opentelemetry-collector/pull/8674, I ran into some changes that were harder than they needed to in the test utility. I'm separating changes to the prometheusChecker into a separate PR to reduce the size of 8674.
> [chore] refactor test code

- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/contrib-tests.yml
Avoid double caching go dependencies, it ends up slowing the build with decompression errors.
> [chore] fix double caching of golang dependencies

- .chloggen/add-is-read-only.yaml
- .chloggen/enable-mutation-assertions.yaml
- internal/fanoutconsumer/logs.go
- internal/fanoutconsumer/logs_test.go
- internal/fanoutconsumer/metrics.go
- internal/fanoutconsumer/metrics_test.go
- internal/fanoutconsumer/traces.go
- internal/fanoutconsumer/traces_test.go
- pdata/plog/logs.go
- pdata/plog/logs_test.go
- pdata/pmetric/metrics.go
- pdata/pmetric/metrics_test.go
- pdata/ptrace/traces.go
- pdata/ptrace/traces_test.go
- service/internal/graph/graph_test.go
This change enables the runtime assertions to catch unintentional pdata mutations in components claiming as non-mutating pdata. Without these assertions, runtime errors may still occur, but thrown by unrelated components, making it very difficult to troubleshoot.
This required introducing extra API to get the pdata mutability state:
- p[metric|trace|log].[Metrics|Traces|Logs].IsReadOnly()
Resolves: https://github.com/open-telemetry/opentelemetry-collector/issues/6794
> [pdata] Enable the pdata mutation safeguards in the fanout consumers

- internal/fanoutconsumer/logs.go
- internal/fanoutconsumer/logs_test.go
- internal/fanoutconsumer/metrics.go
- internal/fanoutconsumer/metrics_test.go
- internal/fanoutconsumer/traces.go
- internal/fanoutconsumer/traces_test.go
A follow-up optimization after merging https://github.com/open-telemetry/opentelemetry-collector/pull/8634.
There is no need to create a fanout consumer for only one read-only consumer. This introduces a behavior that closely resembles its previous state, before the introduction of the readonly/mutable states.
> [fanoutconsumer] [chore] Do not wrap one read-only consumer

- .chloggen/mx-psi_fix-builder.yaml
- cmd/builder/go.mod
- cmd/builder/go.sum
- cmd/builder/internal/builder/config.go
- cmd/builder/internal/builder/config_test.go
- cmd/builder/internal/builder/templates/go.mod.tmpl
- cmd/builder/internal/command.go
- cmd/otelcorecol/go.mod
Adds `go.opentelemetry.io/collector/otelcol` to `go.mod` template for the builder. This fixes #8692.
Since #8443, the `otelcol` folder is its own component. Before this change, `otelcol_version` was enforced by the `collector` module dependency:
https://github.com/open-telemetry/opentelemetry-collector/blob/287b98f6973fd6baa278150b9fca8c83abea0af4/cmd/builder/internal/builder/templates/go.mod.tmpl#L23
After this change, the `go mod tidy` step here:
https://github.com/open-telemetry/opentelemetry-collector/blob/287b98f6973fd6baa278150b9fca8c83abea0af4/cmd/builder/internal/builder/main.go#L115
will add the latest available version for the `otelcol` module since none of the components actually depend on it. For example, with the `v0.86.0` builder config the output is as …
> [cmd/builder] Fix otelcol_version being ignored

- cmd/builder/README.md
Document `go install` limitations on `cmd/builder` README.
**Link to tracking Issue:** Fixes #8691
> [cmd/builder] Specify limitations of `go install` on the README

- .chloggen/codeboten_fix-8673.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/obsexporter.go
- exporter/exporterhelper/obsreport.go
- exporter/exporterhelper/obsreport_test.go
- exporter/exporterhelper/retry_sender_test.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
- internal/obsreportconfig/obsmetrics/obs_exporter.go
- internal/obsreportconfig/obsreportconfig.go
- internal/obsreportconfig/obsreportconfig_test.go
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/otelprometheuschecker.go
These metrics were only exporter either via OC or via the prometheus exporter. Fixes #8673
> [exporterhelper] make enqueue failures available

- .chloggen/fix-nil-storage-panic-on-bad-start.yaml
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
When persistent queue fails to start, for example due to bad permissions, then persistent storage does not get allocated. Thus, ensure stop storage method is only called if actually initialized.
Fixing a bug that resulted in panic when de-referencing nil pointer.  The issue is that in the persistent queue fail to start due to say bad folder permissions, then the `Start` method does not actually set the associated persistent storage, and thus when shutting down it tries to stop the storage and panics.
The traceback appeared as follows:
```
otc-otc-1  | 2023-10-21T05:10:03.187Z   info    extensions/extensions.go:33     Starting extensions...
otc-otc-1  | 2023-10-21T05:10:03.187Z   info    extensions/extensions.go:36     Extension is starting...        {"kind": "extension", …
```
> [fix] [exporterhelper] Fix nil ptr dereference on storage stop

- cmd/builder/README.md
With the collector builder now in the same repo as the collector itself, `/latest` is not a good place to find the latest release of the collector builder. This change provides a link that finds the desired release.
> [cmd/builder] (docs) Fix link to collector builder releases

- .chloggen/codeboten_split-tt-otel-oc.yaml
- exporter/exporterhelper/obsexporter_test.go
- exporter/go.mod
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/otelprometheuschecker.go
- obsreport/obsreporttest/otelprometheuschecker_test.go
- processor/go.mod
- processor/processorhelper/obsreport_test.go
- receiver/go.mod
- receiver/receiverhelper/obsreport_test.go
- receiver/scraperhelper/obsreport_test.go
This change adds a separate prometheus registry for testing the otel vs the oc path through the code. Previous to this change, the otelPrometheusChecker was using the opencensus prometheus exporter which was really confusing and could possibly hide problems.
> [obsreporttest] ensure tests validate either oc or otel

- obsreport/obsreporttest/otelprometheuschecker.go
- processor/batchprocessor/metrics_test.go
did "not" match
@jpkrohling found a few more typos in assertion failures
> [chore] fix test message typo

- .chloggen/codeboten_fix-queue-size-metric.yaml
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/otelprometheuschecker.go
This change ensures the queue_size and queue_capacity metrics are available when using OpenTelemetry for the collector's internal metrics.
Fixes #8682
> [exporterhelper] fix bug with queue size and capacity metrics

- README.md
Pablo has been consistently contributing to the repository for some time now, and I would like to officially nominate him as a maintainer. Thanks @mx-psi for all your work!
> nominate @mx-psi as maintainer

- exporter/exporterhelper/queue_sender_test.go
When sending a retry, make sure to do so inside the run function of the observability sender. Otherwise, tests may produce a negative wait group error when we start to enforce shutdown of the queues.
> [chore] avoid negative waitGroup in test

- .chloggen/fix_logging_without_retry.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/8791.
Logging errors normally happens in the retry exporter helper if retry_on_failure is disabled:
https://github.com/open-telemetry/opentelemetry-collector/blob/66166c4cc371fbe945d7ff19232decd3ee65f76a/exporter/exporterhelper/retry_sender.go#L108-L115
When WithRetry is not specified in the component, no logging happens at all. This change makes the "base" retry sender log errors, so that if a component does not specify WithRetry, it still has errors logged, similar to the behavior with disabled retry.
**Testing:**
Unit tests added
> Log errors even when retry_on_failure is not used

- .chloggen/extension-lifecycle-order.yaml
- docs/service-extensions.md
- extension/extension.go
- service/extensions/extensions.go
- service/extensions/extensions_test.go
- service/extensions/graph.go
- service/extensions/graph_test.go
**Description**:
Enforce order of start and shutdown of extensions according to their internally declared dependencies
**Link to tracking Issue**:
Resolves #8732
**Motivation**:
This is an alternative approach to #8733 which uses declaration order in the config to start extensions. That approach (a) enforces order when it's not always necessary to enforce, and (b) exposes unnecessary complexity to the user by making them responsible for the order.
This PR instead derives the desired order of extensions based on the dependencies they declare by implementing a `DependentExtension` interface. That means that extensions that must depend on others can expose this interface and be guaranteed to start after their dependencies, while other extensions can be started in arbitrary order (same as …
> [service/extensions] extension lifecycle order

- docs/observability.md
This documents how users can enable OTLP export for internal collector telemetry. NOTE: This feature is all still behind feature gates and subject to change
> add docs on how to use feature gates to enable OTLP export

- .gitattributes
Adds `.gitattributes`, same as https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c53db30c19cfbeae138176e8e8ce1912e85ddaed/.gitattributes
> [chore] Add .gitattributes

- exporter/exporterhelper/README.md
Minor clarifications in the README. 
1. The [batch processor's option](https://github.com/open-telemetry/opentelemetry-collector/blob/8bea0d372c9965a99dd88d1f5c4c4b7acee9db40/processor/batchprocessor/config.go#L24) is named `send_batch_size`, not `batch_send_size`.
2. It may be obvious but I didn't instantly realize the sending queue is one or the other (in-memory or persistent). This adds a comment to make it clear.
For reference, I'm adding this as a result of investigation for this issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29006
> [chore][exporter/exporterhelper] Clarifications in README

- connector/forwardconnector/forward.go
- connector/forwardconnector/forward_test.go
`cmd/configschema` currently doesn't work with anonymous config struct. (see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26990#issuecomment-1797797681)
This PR refactors `forwardconnector` to use a defined struct for config.
> [chore] [forwardconnector] use defined struct for config

- .github/workflows/api-compatibility.yml
- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/changelog.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
- .github/workflows/create-dependabot-pr.yml
- .github/workflows/perf.yml
- .github/workflows/prepare-release.yml
- .github/workflows/tidy-dependencies.yml
See https://github.com/open-telemetry/opentelemetry-collector/actions/runs/6807550996/job/18510592678?pr=8830
> Bump golang versions we use to fix vulnerabilities

- exporter/exporterhelper/queue_sender_test.go
Make the imitation of queue overflow more reliable to make the test pass in https://github.com/open-telemetry/opentelemetry-collector/pull/8829
> [chore] [exporterhelper] Ensure TestQueuedRetry_DropOnFull doesn't panic

- exporter/exporterhelper/common.go
- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/mock_storage.go
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_test.go
- exporter/exporterhelper/internal/queue.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/retry_sender.go
- exporter/exporterhelper/retry_sender_test.go
* Rename Stop to Shutdown, add context and return error.
* Fix test nits.
* Return errors from Shutdown instead of log them.
> Rename ProducerConsumerQueue to Queue

- exporter/debugexporter/README.md
This improves the documentation of the `debug` exporter by adding descriptions of the available verbosity levels of the component.
Hopefully this update also brings to light the fact that the verbosity levels need some work. For starters, it makes sense for the `normal` verbosity to have different output from the `basic` verbosity.
> [chore][exporter/debug] add description of verbosity levels

- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/retry_sender.go
- exporter/exporterhelper/retry_sender_test.go
Also, fixes `WithRetry` called with a config that is disabled.
> Avoid nil queue in queue_sender, consolidate implementation

- .chloggen/update-eperimental-request-api.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_test.go
- exporter/exporterhelper/internal/queue.go
- exporter/exporterhelper/internal/request.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/request.go
- exporter/exporterhelper/retry_sender.go
- exporter/exporterhelper/retry_sender_test.go
- exporter/exporterhelper/timeout_sender.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
Pass request+context through the senders pipeline similar to what we do in the collector's pipeline. Use a helper QueueRequest struct for passing requests through queues
This changes also moves the experimental Request interface to a separate package.
> [exporterhelper] Remove redundant request interfaces

- .chloggen/update-eperimental-request-api.yaml
Follow-up to https://github.com/open-telemetry/opentelemetry-collector/pull/8867. Forgot to update the changelog entry after addressing the PR review comments
> [chore] Update a changelog entry

- docs/monitoring.md
Documentation update.
**Link to tracking Issue:** #8835
> Metric is deprecated in v2 kube-state-metrics. Fixes #8835.

- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_test.go
These data are already logger fields, see https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/components/loggers.go#L40
* ID is under `name`
* DataType is under `data_type`
> Do not add Logger field queue name, already configured

- .github/workflows/tidy-dependencies.yml
Switching from forking renovate to renovate, the PRs will now be on a branch in the local repo.
> [chore] update tidy job to use local repo instead of fork

- renovate.json
This configures renovate to use the latest go 1.20 instead of go 1.21
> [chore] configure go version to latest 1.20

- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/consumers.go
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_test.go
- exporter/exporterhelper/internal/queue.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
Move the common workers loop logic from each queue implementation to the sender.
Based on https://github.com/open-telemetry/opentelemetry-collector/pull/8828
> [chore] [exporterhelper] Move workers from queue to queueSender

- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/check-links.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
- .github/workflows/shellcheck.yml
Otherwise, PRs for dependency updates will not re-trigger the CI once gotidy has been run and pushed to the branch.
> [chore] ensure checks run on push to renovatebot branch

- .github/workflows/tidy-dependencies.yml
This is to try and fix the issue where the push from this action doesn't trigger other workflows
> [chore] use PAT on checkout

- .github/workflows/build-and-test-windows.yaml
- .github/workflows/build-and-test.yml
- .github/workflows/builder-integration-test.yaml
- .github/workflows/check-links.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contrib-tests.yml
- .github/workflows/shellcheck.yml
- .github/workflows/tidy-dependencies.yml
- renovate.json
The previous change didn't work because opentelemetrybot doesn't have write permissions to push changes to the renovatebot branch. Reverting to using the standard github token, and testing triggering CI by removing the renovatebot label after the change has been pushed.
> [chore] more tweaking for renovatebot

- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_storage.go
- exporter/exporterhelper/internal/persistent_storage_test.go
Just remove the redundant `persistentQueue` struct as suggested https://github.com/open-telemetry/opentelemetry-collector/pull/8923#issuecomment-1812943071 as step 1
> [chore] [exporterhelper] Remove redundant persistentQueue struct

- .chloggen/expose-zerothreshold.yaml
- pdata/internal/cmd/pdatagen/internal/pmetric_package.go
- pdata/pmetric/generated_exponentialhistogramdatapoint.go
- pdata/pmetric/generated_exponentialhistogramdatapoint_test.go
**Description:** Add ZeroThreshold field to exponentialHistogramDataPoint in pmetric package. It's needed to understand which values fall in the ZeroBucket
Fixes #8802
> Add ZeroThreshold field to exponentialHistogramDataPoint in pmetric package

- .chloggen/dmitryax_use-func-instead-of-converter-interface.yaml
- exporter/exporterhelper/constants.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/request_test.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
As proposed in https://github.com/open-telemetry/opentelemetry-collector/issues/8122#issuecomment-1688794509
If we need backward conversion, we will use an optional argument to the helper function instead of an optional interface.
> [exporterhelper] Replace experimental converter interface with function

- .github/ISSUE_TEMPLATE/stabilization.md
- docs/release.md
This adds a new release template for stabilizing a module.
The intent is to try this out for pdata and featuregate, and iterate on the template over time.
> [docs, .github] Add new issue template for stabilizing a module

- .chloggen/codeboten_prom-without-suffix.yaml
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/otelprometheuschecker.go
- processor/batchprocessor/metrics_test.go
- service/internal/proctelemetry/config.go
- service/internal/proctelemetry/process_telemetry_test.go
- service/telemetry_test.go
This ensures backwards compatibility with the metrics generated via opencensus by default today.
Part of #7454
> [service] remove _total suffix for otel generated metrics

- pdata/plog/json.go
- pdata/pmetric/json.go
- pdata/ptrace/json.go
Explicitly documents that the `JSONMarshaler` and `JSONUnmarshaler` as conforming to the format in the OTLP/JSON specification.
The intent is to be explicit that we follow this spec and that deviations (such as supporting snake case) are bugs that can be removed in a minor version update.
**Link to tracking Issue:** Relates to #6287
> [pdata] Document that Marshalers/Unmarshalers use OTLP/JSON format explicitly

- exporter/exporterhelper/internal/persistent_queue_test.go
Another fix for the flaky test `TestPersistentQueue_FullCapacity`. We need to make sure that the first item is consumed from the queue before proceeding. Otherwise, it can occasionally fail with:
```
--- FAIL: TestPersistentQueue_FullCapacity (0.00s)
persistent_queue_test.go:91:
Error Trace:	/home/runner/work/opentelemetry-collector/opentelemetry-collector/exporter/exporterhelper/internal/persistent_queue_test.go:91
Error:      	Received unexpected error:
sending queue is full
Test:       	TestPersistentQueue_FullCapacity
FAIL
```
> [chore] Fix flaky test TestPersistentQueue_FullCapacity

- .github/ISSUE_TEMPLATE/stabilization.md
- docs/release.md
Clarifies our stance regarding RC releases, inspired by https://github.com/open-telemetry/opentelemetry-collector/pull/8935#discussion_r1397887303. In a nutshell:
- Stabilization criteria have to be met for at least two minor version releases before moving to the stable module.
- We treat these two (or more) minor releases as release candidates and do not release under the `-rc` release family.
- After these releases, we move directly to the `1.x` release family.
**Link to tracking Issue:** Fixes #8063 (together with the upcoming 1.0 release for pdata and featuregate)
cc @braydonk
> Clarify our stance re: release candidates

- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/retry_sender_test.go
Fix flaky TestQueuedRetryPersistentEnabled_shutdown_dataIsRequeued by moving it to persistent queue.
- It makes the test easy to validate given that the size of the persistent queue is always available even if it's closed.
- It brings behavior closer to the name of the test
- It removes the flakiness associated with data race specific to re-enqueuing to the bounded memory queue by shutdown which should be resolved separately once the re-enqueue option is available for the memory queue
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/8124
> [chore] Fix TestQueuedRetryPersistentEnabled_shutdown_dataIsRequeued

- exporter/exporterhelper/queue_sender_test.go
**Description:** fixes a flaky test 
Fixing a bug - TestQueuedRetry_RequeuingEnabled has been failing occasionally. Upon investigation, `be.send` calls the underlying `observabilityConsumerSender.send` which calls `wg.Done()`, so we need to add `wg.Add(1)` before that
**Link to tracking Issue:** #6624
**Testing:** Ran the same test multiple times before/after change: `go test -race -run TestQueuedRetry_RequeuingEnabled -count 1000`
> bug: fix flaky test TestQueuedRetry_RequeuingEnabled

- .chloggen/codeboten_use-namespace.yaml
- service/internal/proctelemetry/config.go
- service/telemetry_test.go
Using this functionality in the otel prom exporter fixes a bug where the target_info was prefixed as otelcol_target_info previously.
> [service] use `WithNamespace` instead of `WrapRegistererWithPrefix`

- .chloggen/fix_persistentstorage_index-updates.yaml
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
Fixing a bug where the in-memory value of the persistent queue's write index would be updated even if writing to the storage failed. This normally wouldn't have any negative effect other than inflating the queue size temporarily, as the read loop would simply skip over the nonexistent record. However, in the case where the storage doesn't have any available space, the in-memory and in-storage write index could become significantly different, at which point a collector restart would leave the queue in an inconsistent state.
Worth noting that the same issue affects reading from the queue, but in that case the writes are very small, and in practice the storage will almost always have enough space to carry them out.
**Link to tracking Issue:** #8115
**Testing:**
The …
> [exporterhelper] Fix invalid write index updates in the persistent queue

- exporter/exporterhelper/common.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/retry_sender.go
Use returned error instead to simplify the senders feedback loop. This change preserves the behavior. Re-enqueueing of the temporary failures depends on the enabled retry sender. This will be changed in the next step when re-queueing becomes a configurable option
> [chore] [exporterhelper] Remove retry sender -> queue sender callback

- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/request.go
- exporter/exporterhelper/retry_sender.go
After https://github.com/open-telemetry/opentelemetry-collector/pull/8985, the whole request is requeued even with the partial request error. This change fixes it and restores the previous behavior. No changelog is needed since the bug is not released yet.
> [chore] [exporterhelper] Fix requeuing of partially failed request

- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
Do not panic on the shutdown of a not-started queue sender
> [chore] [exporterheper] Fix not-started queue sender shutdown

- extension/extension.go
The collector implementation makes a copy of effective configuration before calling `NotifyConfig` so it's safe for the config watcher to save the pointer and use it later. It is resonable to promise this in the API contract.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29277#discussion_r1406522281
**Testing:** No behavior changes.
**Documentation:**  godoc
> [chore][extension] update NotifyConfig contract

- exporter/exporterhelper/queue_sender.go
This should've been part of https://github.com/open-telemetry/opentelemetry-collector/pull/9001. Didn't notice it before
> [chore] [exporterhelper] Remove another redundant field from queueSender

- config/confighttp/README.md
Document `max_request_body_size` setting of `HTTPServerSettings`: https://github.com/open-telemetry/opentelemetry-collector/blob/daef971a0b3087ed76ebe9fd4793877b41b65306/config/confighttp/confighttp.go#L241
> [docs] Document max_request_body_size setting of HTTPServerSettings

- .chloggen/remove_noisy_log.yaml
- exporter/exporterhelper/retry_sender.go
Removes a noisy log statement
Fixes #9017
> Remove noisy log statement

- CHANGELOG.md
- cmd/builder/internal/builder/config.go
- cmd/builder/test/core.builder.yaml
- cmd/otelcorecol/builder-config.yaml
- cmd/otelcorecol/go.mod
- cmd/otelcorecol/main.go
- examples/k8s/otel-config.yaml
- versions.yaml
Started from `origin/main`, merged `origin/release/v0.69.x` into it and resolved merge conflicts.
> Merge release/v0.90.x into main

- .chloggen/codeboten_fix-missing-metrics.yaml
- exporter/exporterhelper/obsexporter.go
This PR ensures that context cancellation in the exporter doesn't interfere with metric aggregation. The OTel SDK currently returns if there's an error in the context used in `Add` (see https://github.com/open-telemetry/opentelemetry-go/blob/6cee2b4a4c76b581115d0d0ca150ad8b2e683db6/sdk/metric/instrument.go#L241-L243). This means that if there's a cancelled context in an export, the metrics are not recorded.
> [exporterhelper] fix missed metric aggregations

- Makefile
- Makefile.Common
- semconv/README.md
Also updating documentation to specify the semantic-conventions repository instead of the spec repo.
> [chore] update gensemconv to use .tools

- Makefile
- Makefile.Common
- internal/tools/semconvkit/main.go
- internal/tools/semconvkit/templates/doc.go.tmpl
- internal/tools/semconvkit/templates/schema.go.tmpl
- internal/tools/tools.go
- semconv/README.md
This code, copied from the opentelemetry-go repo, allows to generate schema.go automatically as well, reducing effort needed to generate semantic convention packages in the future
> [chore] add semconvkit to reduce toil

- .chloggen/connectors-propogate-mutates-data.yaml
- internal/fanoutconsumer/logs.go
- internal/fanoutconsumer/logs_test.go
- internal/fanoutconsumer/metrics.go
- internal/fanoutconsumer/metrics_test.go
- internal/fanoutconsumer/traces.go
- internal/fanoutconsumer/traces_test.go
- service/internal/graph/graph.go
- service/internal/graph/graph_test.go
- service/internal/graph/nodes.go
- service/internal/testcomponents/example_connector.go
This fixes two closely related problems. 
1. While fanoutconsumers do not themselves mutate data, they should expose whether or not they are handing data off to consumers which may do so. Otherwise, the service cannot correctly determine how to fan out after a receiver. e.g. a receiver shared between two pipelines, one of which contains an exporter or connector which mutates data.
2. Connectors can themselves mutate data but we were not taking this into account when building the graph.
> Fix bug where MutatesData would not correctly propogate through connectors

- internal/fanoutconsumer/logs.go
- internal/fanoutconsumer/logs_test.go
- internal/fanoutconsumer/metrics.go
- internal/fanoutconsumer/metrics_test.go
- internal/fanoutconsumer/traces.go
- internal/fanoutconsumer/traces_test.go
- service/internal/graph/graph_test.go
Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/9053.
@dmitryax pointed out [here](https://github.com/open-telemetry/opentelemetry-collector/pull/9053#discussion_r1420871665) that the fanout consumer will pass original data to a non-mutating consumer if any is available. This PR incorporates that point and updates test expectations accordingly.
> Fanout consumer does not need to mutate in some cases

- .github/workflows/generate-semantic-conventions-pr.yaml
This is similar to the workflow used by the jmx gatherer PR in the collector contrib repo.
> [chore] add github action to generate semconv pr

- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/consumers.go
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/queue.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/retry_sender_test.go
This change unblocks adding the `enqueue_on_failure` option to the queue sender by removing the requeue behavior on the shutdown. If we don't remove requeue on shutdown, it's possible to run into a situation described in https://github.com/open-telemetry/opentelemetry-collector/issues/7388. After the recent refactoring, the chance of running into it is pretty small, but it's still possible.
The only reason to requeue on shutdown is to make sure there is no data loss with the persistent queue enabled. The persistent queue captures all the inflight requests in the persistent storage anyway, so there is no reason to requeue an inflight request. The only downside is it potentially can cause sending duplicate data on the collector restart in case of a partially failed request during shutdown. …
> [chore] [exporterhelper] Do not requeue on shutdown

- Makefile
Relax requirements for prepare-release by removing check-changes. Currently, even if it fails, the prepare-release target isn't canceled.
check-changes should be used separately by a release manager
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/9081
> [chore] [makefile] Update check-changes and prepare-release targets

- .chloggen/memory-limiter-update-config-validation-errors.yaml
- processor/memorylimiterprocessor/config.go
- processor/memorylimiterprocessor/config_test.go
- processor/memorylimiterprocessor/factory_test.go
- processor/memorylimiterprocessor/memorylimiter.go
- processor/memorylimiterprocessor/memorylimiter_test.go
- Fix names of the config fields that are validated in the error messages
- Move the validation from start to the initialization phrase
> [processor/memory_limiter] Update config validation

- .chloggen/codeboten_semconv1.22.yaml
- semconv/v1.22.0/doc.go
- semconv/v1.22.0/generated_event.go
- semconv/v1.22.0/generated_resource.go
- semconv/v1.22.0/generated_trace.go
- semconv/v1.22.0/schema.go
Generated with the following:
```
make gensemconv SPECPATH=/tmp/semantic-conventions SPECTAG=v1.22.0
```
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/8686
> [semconv] add 1.22.0 semantic conventions

- .chloggen/codeboten_make-otel-default.yaml
- exporter/exporterhelper/obsexporter_test.go
- exporter/exporterhelper/obsreport_test.go
- exporter/exporterhelper/queue_sender_test.go
- internal/obsreportconfig/obsreportconfig.go
- internal/obsreportconfig/obsreportconfig_test.go
- processor/processorhelper/obsreport_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/receiverhelper/obsreport_test.go
- receiver/scraperhelper/obsreport_test.go
The metrics are now consistent with the metrics produced by OpenCensus. We should move the featuregate forward.
Note that the OpenTelemetry generated metrics includes grpc client/server metrics (for receivers/exporters that use grpc) and `target_info` metrics
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/7454
> make useOtelForInternalMetrics as beta

- exporter/exporterhelper/internal/bounded_memory_queue_test.go
The test checks the behavior that is not available for the user. Zero queue size is not allowed.
With the given input, the test is running in a race condition and fails when `Offer` is called before `Consume`.
```
--- FAIL: TestZeroSizeWithConsumers (0.00s)
bounded_memory_queue_test.go:242:
Error Trace:	/home/runner/work/opentelemetry-collector/opentelemetry-collector/exporter/exporterhelper/internal/bounded_memory_queue_test.go:242
Error:      	Received unexpected error:
sending queue is full
Test:       	TestZeroSizeWithConsumers
FAIL
```
A recent example: https://github.com/open-telemetry/opentelemetry-collector/actions/runs/7187787264/job/19576154676
> [chore] [exporterhelper] Remove redundant flaky test

- cmd/builder/README.md
Deletes a link that does not match any CI status.
> [chore] remove unused CI link

- .github/workflows/api-compatibility.yml
- .github/workflows/check-links.yaml
I seem to recall these were placed here during the initial transition of the repo, they're no longer needed.
This is a follow up to @atoulme's PR which led me to wonder why exemptions were there in the first place 😄
> [chore] remove exemptions for builder

- .chloggen/disable-requeuing.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/consumers.go
- exporter/exporterhelper/internal/err.go
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/queue.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/retry_sender.go
The current re-enqueuing behavior is not obvious and cannot be configured. It takes place only for persistent queue and only if `retry_on_failure::enabled=true` even if `retry_on_failure` is a setting for a different backoff retry strategy. 
This change removes the re-enqueuing behavior in favor of the `retry_on_failure` option. Consider increasing `retry_on_failure::max_elapsed_time` to reduce chances of data loss.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/8382
> [exporterhelper] Do not re-enqueue failed requests

- exporter/exporterhelper/internal/persistent_queue.go
No changelog, bug was not released.
> [chore] Fix storage client leak in persistent queue when shutdown

- exporter/exporterhelper/internal/bounded_memory_queue_test.go
Refactor benchmarks to run as tests as well, remove use of time.Sleep in benchmarks.
> [chore] remove time.Sleep from benchmarks

- .chloggen/confignet-add-dialertimeout.yaml
- config/confignet/README.md
- config/confignet/confignet.go
- config/confignet/confignet_test.go
Adds a new `dialer_timeout` config option to `confignet` to allow configuring the timeout of the connection.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/4331
**Testing:** 
Added new unit tests
Updated readme
> [confignet] Add DialerTimeout config option

- .chloggen/confignet-now-with-ctx.yaml
- config/confignet/confignet.go
- config/confignet/confignet_test.go
Deprecates the `Dial` and `Listen` functions in favor of `DialContext` and `ListenContext`.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/9105
**Testing:** 
Updated unit tests
Added godoc comments
> [confignet] Add new functions that take Context

- cmd/otelcorecol/go.mod
- exporter/debugexporter/go.mod
- exporter/go.mod
- exporter/loggingexporter/go.mod
- exporter/otlpexporter/go.mod
- exporter/otlphttpexporter/go.mod
- go.mod
- internal/e2e/go.mod
This will make updating core from contrib much easier, otherwise we need to add replace statements everywhere in contrib.
> [chore] when adding new module, use the version from main

- internal/sharedcomponent/sharedcomponent.go
- internal/sharedcomponent/sharedcomponent_test.go
- receiver/otlpreceiver/factory.go
Attempt to simplify as much as possible the API exposed by the sharedcomponent package ahead of exposing it as part of a published module.
Relates to #9156 
Changes:
* Remove the map field in the struct, make the struct a map
* Remove the `NewSharedComponents` function, just initialize the map instead.
* Rename GetOrAdd to LoadOrStore
> [chore] polish sharedcomponent API

- .codecov.yml
This is the same rule that was used in contrib, ignores third_party dir under mdatagen.
> [chore] update codecov to ignore third_party

- .golangci.yml
Removes a TODO for the fieldalignment linter, offering a reasoning to keep it disabled moving forward.
Fixes #2789
> [chore] remove fieldalignment linter TODO

- exporter/exporterhelper/internal/bounded_memory_queue.go
- exporter/exporterhelper/internal/bounded_memory_queue_test.go
- exporter/exporterhelper/internal/persistent_queue.go
- exporter/exporterhelper/internal/persistent_queue_test.go
- exporter/exporterhelper/internal/queue_capacity.go
- exporter/exporterhelper/internal/queue_capacity_test.go
- exporter/exporterhelper/queue_sender.go
Introduce an option to limit the queue size by the number of items instead of number of requests. This is preliminary step for having the exporter helper v2 with a batcher sender placed after the queue sender. Otherwise, it'll be hard for the users to estimate the queue size based on the number of requests without batch processor in front of it.
This change doesn't effect the existing functionality and the items based queue limiting cannot be utilized yet.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/8122
Alternative to https://github.com/open-telemetry/opentelemetry-collector/pull/9147
> [chore] [exporterhelper] Items based queue sizing with bounded channel

- .chloggen/make_error_unused_default.yaml
- component/config.go
- confmap/confmap.go
- confmap/confmap_test.go
- exporter/loggingexporter/config.go
- otelcol/internal/configunmarshaler/configs.go
- otelcol/unmarshaler.go
- otelcol/unmarshaler_test.go
- receiver/otlpreceiver/config.go
Make the option `WithErrorUnused` enabled by default when unmarshaling configuration
The option `WithErrorUnused` is now enabled by default, and a new option `WithIgnoreUnused` is introduced to ignore
errors about unused fields.
This relates to #7102 to some extent.
**Testing:**
N/A
N/A
> Make the option `WithErrorUnused` enabled by default when unmarshaling configuration

- .github/pull_request_template.md
Currently when submitting a PR the section descriptions will be shown in the markdown view when they should be hidden. This now follows [contrib's template formatting](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/pull_request_template.md?plain=1).
> [chore] Fix PR template so that comments aren't seen in markdown

- config/configgrpc/go.mod
- config/configgrpc/go.sum
- config/configtls/go.mod
- config/configtls/go.sum
- exporter/debugexporter/go.mod
- exporter/debugexporter/go.sum
- exporter/loggingexporter/go.mod
- exporter/loggingexporter/go.sum
- exporter/otlpexporter/go.mod
- exporter/otlpexporter/go.sum
- exporter/otlphttpexporter/go.mod
- exporter/otlphttpexporter/go.sum
- internal/e2e/go.mod
- internal/e2e/go.sum
- processor/batchprocessor/go.mod
- processor/batchprocessor/go.sum
- processor/memorylimiterprocessor/go.mod
- processor/memorylimiterprocessor/go.sum
- receiver/otlpreceiver/go.mod
- receiver/otlpreceiver/go.sum
Unfortunately as a part of #9173 I committed some `go.mod` and `go.sum` updates incorrectly. I've run `make gotidy` and hopefully cleared those up. 
These goleak dependencies were added for goleak tests that ended up failing, so the tests weren't added as a part of the original PR. This ended up leaving the dependencies incorrectly added.
> [chore] Run make gotidy

- .github/workflows/build-and-test.yml
Every PR should be checked to make sure `make gotidy` can run successfully against its contents. I want to add this because as shown in #9212, I recently broke some dependencies on `main`.
[Logic lifted from contrib.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0c27a3bccfd1b1f7418cc1ac05a535ce29a5a736/.github/workflows/build-and-test.yml#L198-L201)
> [chore][CI/CD] Add make gotidy check in build-and-test.yml

- cmd/mdatagen/loader.go
As described in the [issue opened in the contrib repository](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29923), mdatagen was originally generating tests for byte arrays incorrectly. This tests byte arrays in their proper format.
As [requested](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30106#issuecomment-1879321401), this ports the [contrib fix ](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30106 )into core. 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29923
I added a fake attribute and fake metric …
> [chore][cmd/mdatagen] Properly test bytes attribute type

- exporter/exporterhelper/internal/bounded_memory_queue_test.go
Ensure the queue always has enough capacity to make the benchmark results deterministic. Otherwise, it's unpredictable when the queue starts rejecting the new entries. It depends on how fast it processes them, which can significantly fluctuate.
Also, remove the multiple consumers use cases from benchmarks as redundant. Not sure they provide any value.
> [chore] [exporterhelper] Make memory queue benchmarks deteministic

- .chloggen/statuschange_invalidtransition.yaml
- component/componenttest/nop_telemetry.go
- component/telemetry.go
- internal/sharedcomponent/sharedcomponent.go
- internal/sharedcomponent/sharedcomponent_test.go
- processor/processortest/unhealthy_processor.go
- service/extensions/extensions.go
- service/extensions/extensions_test.go
- service/internal/graph/graph.go
- service/internal/graph/graph_test.go
- service/internal/servicetelemetry/nop_telemetry_settings.go
- service/internal/servicetelemetry/nop_telemetry_settings_test.go
- service/internal/servicetelemetry/telemetry_settings.go
- service/internal/servicetelemetry/telemetry_settings_test.go
- service/internal/status/status.go
- service/internal/status/status_test.go
- service/service.go
> Move error out of `ReportComponentStatus` function signature, use `ReportStatus` instead

- internal/sharedcomponent/sharedcomponent.go
Add just enough code to make sharedcomponent Map thread safe.
Relates to #9156
Follow up to #9157, should be reviewed after it is merged.
> [chore] make sharedcomponent Map threadsafe

- .chloggen/confignet-remove-deprecated-functions.yaml
- config/configgrpc/configgrpc.go
- config/confignet/confignet.go
- config/confignet/confignet_test.go
- extension/zpagesextension/zpagesextension.go
Instead of completely removing `Dial` and `Listen`, renames `DialContext` and `ListenContext` to `Dial` and `Listen` and deprecates `DialContext` and `ListenContext`.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/9105
**Testing:**
Updated tests
> [confignet] Remove deprecated confignet functions

- .chloggen/configopaque_stringer.yaml
Follow up to #9214.
I think marking this as breaking is warranted since we have found 6 instances of breakage in contrib (fixed by open-telemetry/opentelemetry-collector-contrib#30304, open-telemetry/opentelemetry-collector-contrib#30402 and open-telemetry/opentelemetry-collector-contrib#30405).
I am also:
- Adding subtext explicitly stating how to fix this
- Adding this to the user changelog, since it has user-facing implications.
> Mark configopaque change as a breaking change

- .github/ISSUE_TEMPLATE/bug_report.md
The descriptions for each header when reporting bugs is useful for the person filing the bug, but not useful to those reading and reviewing. I think it makes sense for these to be included as comments in the bug report, so they're hidden in the rendered report.
> [chore][bug_report.md] Comment out header descriptions

- .chloggen/exporter-helper-cleanup-error-logs.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/retry_sender.go
- exporter/exporterhelper/retry_sender_test.go
This change makes the logging of the exported error failures cleaner.
1. Ensure an error message is logged every time and only once when data is dropped/rejected due to export failure.
2. Update the wording. Specifically, don't use "dropped" term when an error is reported back to the pipeline. If there is no queue configured, the exporter doesn't drop data by itself but rather rejects it. Keep the "dropped" wording for failures after the enabled queue.
3. Properly report any error reported by a queue. For example, a persistent storage error must be reported as a storage error, not as "queue overflow".
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/9219
> [exporterhelper] Cleanup logging for export failures

- .chloggen/configopaque_stringer.yaml
- config/configopaque/opaque.go
- config/configopaque/opaque_test.go
**Description:** Follow up to #9214.
To make sure the output when using `%#v` is redacted, we must also implement the `fmt.GoStringer` interface.
**Link to tracking Issue:** Relates to #9213
**Testing:**  Adds some tests with YAML and JSON as well as more thorough testing of all `fmt` verbs 
**Documentation:** Clarify that printing this is also redacted.
> [configopaque] Implement fmt.GoStringer interface for String

- docs/release.md
I can't do the v0.95.0 release, so I am swapping it for the v0.96.0 release.
> [docs/release] Swap Juraci and me for release duties

- config/configopaque/doc.go
- config/configopaque/opaque.go
Documents `configopaque` expectations.
The intention is that it is clear that we can add interface implementations after 1.0 if not doing so would leak opaque values.
**Link to tracking Issue:** Fixes #9274
> [chore] Clarify configopaque expectations

- Makefile
This is copied verbatim from the contrib repo.
> [chore] add mdatagen-test makefile target

- CONTRIBUTING.md
Some small updates on the CONTRIBUTING.md doc to keep it updated:
- Remove 'Up for Grabs' label which we have never used
- Update minimum Go version
- Remove outdated comment about OpenTelemetry project status
- Link to dedicated observability doc
> [CONTRIBUTING.md] Proofread the contributing doc

- .chloggen/cipher_suites.yaml
- config/configtls/README.md
- config/configtls/configtls.go
- config/configtls/configtls_test.go
Add `cipher_suites` to configtls:
Users can specify a list of cipher suites to pick from. If left blank, a safe default list is used.
Fixes #8105
**Testing:**
Unit tests
godoc and README
> [configtls] support setting cipher suites

- examples/k8s/otel-config.yaml
The name/value entry had an incorrect indentation that made the documented process fail (Document ref: https://opentelemetry.io/docs/collector/installation/)
the current roadmap and are not aimed at stabilizing and preparing the Collector for the release will
not be accepted.
_Delete the preceding paragraph before submitting._
> Fixed indentation in YAML for deployment at otel-config.yaml

- .chloggen/configopaque-implement-BinaryMarshaler.yaml
- config/configopaque/opaque.go
- config/configopaque/opaque_test.go
Implements the `encoding.BinaryMarshaler` interface for `String`.  This prevents the situation `configopaque` -> `[]byte` -> `string` from leaking the `String` value.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9272
**Testing:** 
Added unit test
> [configopaque] Implement encoding.BinaryMarshaler interface for String

- extension/zpagesextension/zpagesextension.go
Remove use of the deprecated method `ReportFatalError` in favor of using `ReportStatus`.
> [chore][extension/zpages] ReportFatalError -> ReportStatus

- service/internal/resource/config.go
- service/internal/resource/config_test.go
- service/service.go
- service/telemetry.go
- service/telemetry_test.go
A part of #9319 that can be done without waiting for #9131
> [service] Refactor telemetry initialization

- receiver/otlpreceiver/otlp_test.go
This PR removes 3 TODOs and time.Sleep statements as otlp receiver start is now deterministic.
This change is similar to https://github.com/open-telemetry/opentelemetry-collector/pull/9121
For good measure, I ran the tests 10,000 each (each test runs multiple sub-tests) and didn't have any failures.
> [chore] remove waits as start is now deterministic

- otelcol/command_test.go
* Add unit test that illustrates running the command without an external config
* This models how Jaeger all-in-one uses collector because all-in-one can be run without arguments, for maximum user friendliness
> [otelcol] Add unit test for implicit config use case

- docs/platform-support.md
Adds owner for darwin/amd64 platform based on https://github.com/open-telemetry/opentelemetry-collector/issues/8526#issuecomment-1905979165.
**Link to tracking Issue:** Fixes #9114
> [docs] Add owner for darwin/amd64

- .chloggen/codeboten_fix-census-bridge.yaml
- service/internal/proctelemetry/config.go
The periodic metric readers were not connecting to the opencensus bridge prior to this change, meaning anyone trying to emit metrics via the console or OTLP from components that used opencensus were failing to do so.
> [service] fix opencensus bridge in periodic readers

- .chloggen/deprecate_toListener.yaml
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- receiver/otlpreceiver/otlp.go
Introduce `ToListenerContext` and deprecate `ToListener`.
#9389
> [config/configgrpc] introduce toListenerContext, deprecate toListener

- .chloggen/corssettings_corsconfig.yaml
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- receiver/otlpreceiver/config.md
- receiver/otlpreceiver/config_test.go
Deprecate CORSSettings, use CORSConfig instead
#6767
> [config/confighttp] Deprecate CORSSettings, use CORSConfig instead

- .chloggen/httpserversettings_httpserverconfig.yaml
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- receiver/otlpreceiver/config.go
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/factory_test.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
Deprecate HTTPServerSettings, use HTTPServerConfig instead
#6767
> [confighttp] Deprecate HTTPServerSettings, use HTTPServerConfig instead

- .chloggen/httpclientsettings_httpclientconfig-breaking.yaml
- .chloggen/httpclientsettings_httpclientconfig.yaml
- config/confighttp/compression_test.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/otlphttpexporter/config.go
- exporter/otlphttpexporter/config_test.go
- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/factory_test.go
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
- internal/e2e/otlphttp_test.go
Deprecate HTTPClientSettings, use HTTPClientConfig instead
#6767
> [confighttp] Deprecate HTTPClientSettings, use HTTPClientConfig instead

- config/confighttp/clientinfohandler.go
- config/confighttp/clientinfohandler_test.go
move implementation checks to test files
#9431
> [confighttp] move implementation checks to test files

- config/configopaque/opaque.go
- config/configopaque/opaque_test.go
Move implementation checks to test files. Reduces dependencies of the configopaque package.
> [chore][config/configopaque] Move implementation checks to test files

- .github/workflows/contrib-tests.yml
Implements a job matrix for the contrib checks.  If we think it would be worth it, we could add a setup job to download the repo only 1 time.
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30880
> Parallelizing contrib check

- .chloggen/convertersettings.yaml
- .chloggen/providersettings.yaml
- confmap/converter.go
- confmap/converter/expandconverter/expand.go
- confmap/converter/expandconverter/expand_test.go
- confmap/provider.go
- confmap/provider/envprovider/provider.go
- confmap/provider/fileprovider/provider.go
- confmap/provider/httpprovider/provider.go
- confmap/provider/httpsprovider/provider.go
- confmap/provider/internal/configurablehttpprovider/provider.go
- confmap/provider/internal/configurablehttpprovider/provider_test.go
- confmap/provider/yamlprovider/provider.go
- otelcol/collector_test.go
- otelcol/command_test.go
- otelcol/command_validate_test.go
- otelcol/configprovider.go
- otelcol/otelcoltest/config.go
For both #5615 and #9162 we need to be able to log during the confmap resolution.
My proposed solution is to pass a `*zap.Logger` to converters and providers during initialization. These components can then use this to log any warnings they need. This PR does the first step: being able to pass anything to converters and providers during initialization.
The obvious alternative to this is to change the interface of `confmap.Provider` and `confmap.Converter` to pass any warnings in an explicit struct. I think the `*zap.Logger` alternative is more natural for developers of providers and converters: you just use a logger like everywhere else in the Collector.
One problem for the Collector usage of `confmap` is: How does one pass a `*zap.Logger` before knowing how a …
> [confmap] Pass ConverterSettings and ProviderSettings to converters and providers

- CONTRIBUTING.md
Adds expectations for how the repository handle enumerations
Relates to https://github.com/open-telemetry/opentelemetry-collector/issues/9388
> Add enumeration expectations

- .chloggen/configcompression-make-member-func.yaml
- config/configcompression/compressiontype.go
- config/configcompression/compressiontype_test.go
- config/configgrpc/configgrpc.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
Updates `IsCompressed` to be a member function. 
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9434
> [configcompression] make `IsCompressed` a member function

- Makefile
This removes a warning on recent GNU grep versions, but also works on other grep implementations. Contrib already is using the `-E` flag.
> [chore] Use `grep -E` in root Makefile to fix warning

- .chloggen/grpcclientsettings_grpcclientconfig-otlpreceiver.yaml
- .chloggen/grpcclientsettings_grpcclientconfig.yaml
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/config.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/factory.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- internal/e2e/consume_contract_test.go
Deprecate GRPCClientSettings, use ~GRPC~ClientConfig instead
#6767
> [configgrpc] Deprecate GRPCClientSettings, use ClientConfig instead

- .chloggen/httpclientsettings_httpclientconfig-breaking.yaml
- .chloggen/httpclientsettings_httpclientconfig.yaml
- .chloggen/httpserversettings_httpserverconfig-otlpreceiver.yaml
- .chloggen/httpserversettings_httpserverconfig.yaml
- config/confighttp/compression_test.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/otlphttpexporter/config.go
- exporter/otlphttpexporter/config_test.go
- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/factory_test.go
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
- internal/e2e/otlphttp_test.go
- receiver/otlpreceiver/config.go
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/factory_test.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
Following discussion https://github.com/open-telemetry/opentelemetry-collector/pull/9403#discussion_r1471644409
> [chore] Update httpconfig API to not include HTTP prefix

- .chloggen/remove_assert_host.yaml
- cmd/mdatagen/templates/component_test.go.tmpl
Remove use of ReportFatalError in generated tests
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30579
> [mdatagen] Remove use of ReportFatalError in generated tests

- .chloggen/exporter-helper-v2.yaml
- exporter/exporterhelper/common.go
- exporter/exporterhelper/logs.go
- exporter/exporterhelper/logs_test.go
- exporter/exporterhelper/metrics.go
- exporter/exporterhelper/metrics_test.go
- exporter/exporterhelper/queue_sender.go
- exporter/exporterhelper/queue_sender_test.go
- exporter/exporterhelper/request.go
- exporter/exporterhelper/retry_sender.go
- exporter/exporterhelper/retry_sender_test.go
- exporter/exporterhelper/traces.go
- exporter/exporterhelper/traces_test.go
- exporter/exporterqueue/config.go
- exporter/exporterqueue/config_test.go
- exporter/exporterqueue/queue.go
- exporter/internal/queue/bounded_memory_queue.go
- exporter/internal/queue/bounded_memory_queue_test.go
- exporter/internal/queue/consumers.go
- exporter/internal/queue/err.go
- exporter/internal/queue/mock_storage.go
- exporter/internal/queue/package_test.go
- exporter/internal/queue/persistent_queue.go
- exporter/internal/queue/persistent_queue_test.go
- exporter/internal/queue/queue.go
- exporter/internal/queue/queue_capacity.go
- exporter/internal/queue/queue_capacity_test.go
Introduce a way to enable queue in the new exporter helper with a developer interface suggested in https://github.com/open-telemetry/opentelemetry-collector/pull/8248#discussion_r1302102261. 
The new configuration interface for the end users provides a new `queue_size_items` option to limit the queue by a number of spans, log records, or metric data points. The previous way to limit the queue by number of requests is preserved under the same field, `queue_size,` which will later be deprecated through a longer transition process.
Tracking issue: https://github.com/open-telemetry/opentelemetry-collector/issues/8122
> [exporterhelper] Add WithRequestQueue option to the exporter

- receiver/otlpreceiver/otlp.go
Remove use of the deprecated method `ReportFatalError` in favor of using `ReportStatus`.
> [chore][receiver/otlp] ReportFatalError -> ReportStatus

- .github/workflows/build-and-test.yml
> add go 1.22 to tests

- cmd/otelcorecol/go.mod
- cmd/otelcorecol/go.sum
- config/confighttp/go.mod
- config/confighttp/go.sum
- exporter/otlphttpexporter/go.mod
- exporter/otlphttpexporter/go.sum
- internal/e2e/go.mod
- internal/e2e/go.sum
- receiver/otlpreceiver/go.mod
- receiver/otlpreceiver/go.sum
This reverts commit f1a574a84e7f5c74bcd9b9796ef9847b97e2ca10.
Fixes #9519
> Revert "Update module go.opentelemetry.io/contrib/instrumentation/nethttp/otelhttp to v0.48.0 (#9497)"

- .chloggen/check_max_elapsed_time.yaml
- config/configretry/backoff.go
- config/configretry/backoff_test.go
Validate `max_elapsed_time`, ensure it is larger than `max_interval` and `initial_interval` respectively.
> [configretry] validate max_elapsed_time

- exporter/otlpexporter/otlp.go
This comment has a typo and is invalid: we do not start the exporter in this function.
> [chore] remove comment

- exporter/otlpexporter/config.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/factory.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/testdata/invalid_configs.yaml
Use `Config.Validate` to validate the presence of the gRPC endpoint instead of making an assertion at creation time.
> [otlpexporter] Validate the configuration explicitly

- Makefile.Common
This is a QOL improvement. As shown in the testing section, existing `make` commands that rely on tools don't work in sub-packages. The issue was that the path reference for the tools dir was the current directory, instead of the repo's root dir. This updates the path to the tools dir to be from the root path instead of the current directory. 
This now matches [contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2c870cebf0f1a4c02a0fc493db686f6422f8a23a/Makefile.Common#L22).
Before:
```
crobert$ ~/dev/opentelemetry-collector/receiver/otlpreceiver $ make fmt
/bin/bash: /Users/crobert/dev/opentelemetry-collector/receiver/otlpreceiver/internal …
```
> [chore][Makefile.Common] Enable make commands to run on individual packages

- receiver/scrapererror/partialscrapeerror.go
Remove the nil check from `IsPartialScrapeError` as redundant, `errors.As` has the same condition
> [chore] [scrapererror] Remove nil check from IsPartialScrapeError

- exporter/exporterhelper/retry_sender.go
- exporter/internal/experr/err.go
- exporter/internal/experr/err_test.go
- exporter/internal/queue/persistent_queue.go
- exporter/internal/queue/persistent_queue_test.go
The error is created by the retry sender and used by the queue sender. It doesn't belong to queue package
> [chore] [exporterhelper] Move shutdown error from queue package

- receiver/receivertest/contract_checker.go
The `idSet` struct used a mix of pointer and non-pointer receivers on functions, this is now uniformly using non-pointer functions.
> [chore] apply some nits to contract_checker.

- Makefile
Fix a missing backslash, breaking the command, add `configauth` which was missing, and fix the package name `zpagesextension` which has a typo.
> [chore] fix restore-contrib make task

- .chloggen/confighttp-remove-deprecated-items.yaml
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
Removes deprecated items from `confighttp` 
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/6767
> [confighttp] Remove deprecated items

- .chloggen/implement_contract_checker.yaml
- receiver/receivertest/contract_checker.go
- receiver/receivertest/contract_checker_test.go
add support for metrics in contract checker
> [receivertest] add metrics support to contract_checker

- README.md
The OpenSSF badge is a required part of CNCF project graduation. The self reporting has been completed already and this is to demonstrate publicly we have done the required step. 
Relevant issue: https://github.com/open-telemetry/community/issues/1942
> add openssf badge to read me

- CONTRIBUTING.md
Adds new rules for configuration packages and a `NewDefault*` function to enable backwards-compatible use of the configuration.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/9508
> [chore] Add rules for `NewDefault*` pattern

- .chloggen/configretry-validation-fix.yaml
- config/configretry/backoff.go
- config/configretry/backoff_test.go
- exporter/exporterhelper/README.md
[configretry] Allow max_elapsed_time to be set to 0
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/9641
> [configretry] Allow max_elapsed_time to be set to 0

- docs/troubleshooting.md
Add more troubleshooting docs around metric levels and traces.
> [chore] improve troubleshooting docs for collector

- .chloggen/rename_configtls_structs.yaml
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- config/configtls/configtls.go
- config/configtls/configtls_test.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp_test.go
- exporter/otlphttpexporter/config_test.go
- exporter/otlphttpexporter/factory_test.go
- internal/e2e/consume_contract_test.go
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/otlp_test.go
Simply renames a few structs in the `configtls` package for consistence.
`TLSClientSetting` to `ClientConfig`
`TLSServerSetting` to `ServerConfig`
`TLSSetting` to `Config`
Fixes #9474
> [configtls] Rename config structs for consistency

- .chloggen/UseSystemCACerts.yaml
- config/configtls/README.md
- config/configtls/configtls.go
- config/configtls/configtls_test.go
Add `include_system_ca_certs_pool` to configtls, allowing to load system certs and additional custom certs.
Fixes #7774
**Testing:**
UTs
Added to README
> [configtls] add include_system_ca_certs_pool

- docs/design.md
- docs/processing.md
Updates mentions to `spanmetrics` processor and references `spanmetrics` connector instead if applicable.
**Link to tracking Issue:** Relates to open-telemetry/opentelemetry-collector-contrib#29567
> [chore] Remove or update mentions to spanmetrics processor

- .github/workflows/prepare-release.yml
enhance the "Automation - Prepare Release" GitHub Actions workflow by adding version format validation. The workflow now includes a new job, "validate-version," which checks whether the provided version inputs match the expected schema
**Link to tracking Issue:** <Issue number if applicable> #7627
> [chore] validate version format to prepare-release workflow

- .github/workflows/prepare-release.yml
Fixes https://github.com/open-telemetry/opentelemetry-collector/actions/runs/8139621131/workflow
```
The workflow is not valid. .github/workflows/prepare-release.yml (Line: 54, Col: 9): 
Job 'prepare-release' depends on unknown job 'validate-version'.
```
#9409 introduced some errors because the workflow is not tested on PRs, #9668 partly fixed them and I mistakenly believed Github would notify me of further errors in the workflow, the same way it did with this one, but it did not.
> [chore] Fix prepare-release.yml
