CODEOWNERS
/cc @songy23 @SergeyKanzhelev 
for https://github.com/open-telemetry/community/issues/39
=> Add @songy23 as approver

demos/trace/README.md, demos/trace/docker-compose.yaml, demos/trace/oc-agent-config.yaml
Address #24 though you should use
census-instrumentation/opencensus-service for now
=> Make demo work with collector binary

receiver/zipkinreceiver/config.go, receiver/zipkinreceiver/config_test.go, receiver/zipkinreceiver/factory.go, receiver/zipkinreceiver/factory_test.go, receiver/zipkinreceiver/testdata/config.yaml
This is part of remaining migration to new configuration format.
Github issue: https://github.com/open-telemetry/opentelemetry-service/issues/34
Testing done: make
=> Add factory and new-style config for Zipkin receiver

cmd/occollector/app/collector/testdata/otelsvc-config.yaml, internal/collector/processor/queued/config.go, internal/collector/processor/queued/config_test.go, internal/collector/processor/queued/factory.go, internal/collector/processor/queued/factory_test.go, internal/collector/processor/queued/testdata/config.yaml
This is part of remaining migration to new configuration format.
Github issue: https://github.com/open-telemetry/opentelemetry-service/issues/46
Testing done: make
=> Add factory and new-style config for Queued processor

cmd/occollector/app/builder/receivers_builder.go, configv2/example_factories.go, factories/factories.go, factories/factories_test.go, receiver/jaegerreceiver/factory.go, receiver/jaegerreceiver/factory_test.go, receiver/opencensusreceiver/factory.go, receiver/opencensusreceiver/factory_test.go, receiver/prometheusreceiver/factory.go, receiver/prometheusreceiver/factory_test.go, receiver/prometheusreceiver/metrics_receiver.go, receiver/zipkinreceiver/factory.go, receiver/zipkinreceiver/factory_test.go
=> Updates receiver creators to take a zap.Logger parameter.

cmd/occollector/app/builder/exporters_builder.go, configv2/example_factories.go, exporter/opencensusexporter/factory.go, exporter/opencensusexporter/factory_test.go, factories/factories.go, factories/factories_test.go
=> Updates creators for exporters to take logger parameter.

cmd/occollector/app/sender/jaeger_proto_grpc_sender.go, cmd/occollector/app/sender/jaeger_thrift_http_sender.go, cmd/occollector/app/sender/jaeger_thrift_tchannel_sender.go, consumer/consumererror/consumererror.go, consumer/consumererror/consumererror_test.go, exporter/zipkinexporter/zipkin.go, internal/collector/processor/queued/queued_processor.go, internal/collector/processor/queued/queued_processor_test.go
These errors are specific to the consumer interface.
Fixes https://github.com/open-telemetry/opentelemetry-service/issues/107
=> Move errorkind to consumererror

cmd/occollector/app/builder/exporters_builder.go, cmd/occollector/app/builder/receivers_builder.go, configv2/configerror/configerror.go, configv2/configerror/empty_test.go, configv2/example_factories.go, exporter/opencensusexporter/factory.go, exporter/opencensusexporter/factory_test.go, exporter/prometheusexporter/factory.go, exporter/prometheusexporter/factory_test.go, internal/collector/processor/nodebatcher/factory.go, internal/collector/processor/queued/factory.go, processor/addattributesprocessor/factory.go, processor/factory_test.go, receiver/jaegerreceiver/factory.go, receiver/jaegerreceiver/factory_test.go, receiver/prometheusreceiver/factory.go, receiver/prometheusreceiver/factory_test.go, receiver/vmmetricsreceiver/factory.go, receiver/vmmetricsreceiver/factory_test.go, receiver/zipkinreceiver/factory.go, receiver/zipkinreceiver/factory_test.go
Updates https://github.com/open-telemetry/opentelemetry-service/issues/99
=> Move configuration specific errors in configerror

processor/attributekeyprocessor/config.go, processor/attributekeyprocessor/config_test.go, processor/attributekeyprocessor/factory.go, processor/attributekeyprocessor/factory_test.go, processor/attributekeyprocessor/testdata/config.yaml, processor/attributekeyprocessor/testdata/empty.yaml
=> Add factory and config for attributes processor

defaults/defaults_test.go, processor/addattributesprocessor/config_test.go, processor/addattributesprocessor/factory.go, processor/addattributesprocessor/testdata/config.yaml, service/builder/testdata/pipelines_builder.yaml, service/testdata/otelsvc-config.yaml, testbed/tests/testdata/agent-config.yaml
=> Use add-attributes as the name for addattributeprocessor

exporter/opencensusexporter/factory_test.go, service/builder/exporters_builder_test.go
=> Fix two flaky tests with OpenCensus exporter

processor/tracesamplerprocessor/config.go, processor/tracesamplerprocessor/config_test.go, processor/tracesamplerprocessor/factory.go, processor/tracesamplerprocessor/factory_test.go, processor/tracesamplerprocessor/testdata/config.yaml, processor/tracesamplerprocessor/testdata/empty.yaml, processor/tracesamplerprocessor/tracesamplerprocessor.go, processor/tracesamplerprocessor/tracesamplerprocessor_test.go
=> Implement factory and config for sampling processor (head-based)

README.md
=> Fix README - remove broken links and commands

DESIGN.md, Makefile, config/config_test.go, exporter/exporterhelper/common.go, exporter/exporterhelper/tracehelper.go, go.mod, go.sum, internal/tools.go, processor/probabilisticsampler/probabilisticsampler.go, receiver/prometheusreceiver/README.md, receiver/prometheusreceiver/internal/metricsbuilder.go, receiver/prometheusreceiver/internal/ocastore_test.go
Updates #155.
Changes are generated with
$ make misspell-correction
See https://github.com/client9/misspell
=> Add misspell check and fix all typos

receiver/opencensusreceiver/config.go
Fix staticcheck error after last two merges.
=> Fix build: lower casing error message

README.md
* Remove extraneous space in docker command
* Change filename to match sample in /examples/demotrace/
=> Fix and improve sample docker command

Makefile
=> Remove vendor in Makefile

receiver/opencensusreceiver/opencensus_test.go
=> Find available ports instead of hard-coded ones in tests

receiver/jaegerreceiver/trace_receiver.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup: fix typo in error message

examples/demo/README.md, examples/demo/docker-compose.yaml, examples/demo/otel-agent-config.yaml, examples/demo/otel-collector-config.yaml, examples/demo/prometheus.yaml, examples/main.go
=> Add collecting metrics to the examples

service/service.go, service/service_test.go, zpages/zpagesserver.go, zpages/zpagesserver_test.go
=> Move zpages to package zpages instead of internal

processor/attributes/config.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> attributes: fix error in struct definition

examples/demo/otel-agent-config.yaml, exporter/README.md, exporter/loggingexporter/config.go, exporter/loggingexporter/config_test.go, exporter/loggingexporter/factory.go, exporter/loggingexporter/logging_exporter.go, exporter/loggingexporter/testdata/config.yaml
=> Add configuration of log level for logging exporter

exporter/jaeger/jaegerthrifthttpexporter/exporter.go, exporter/loggingexporter/config.go, processor/tailsamplingprocessor/processor.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> Cleanup: fix some typos in code comment

exporter/exporterhelper/common_test.go, exporter/exporterhelper/metricshelper_test.go, exporter/exporterhelper/tracehelper_test.go
=> Use assert pattern in test code of exporterhelper

exporter/exporter.go, exporter/exporterhelper/common.go, exporter/exporterhelper/common_test.go, exporter/exporterhelper/constants.go, exporter/exporterhelper/metricshelper.go, exporter/exporterhelper/metricshelper_test.go, exporter/exporterhelper/tracehelper.go, exporter/exporterhelper/tracehelper_test.go, exporter/exportertest/nop_exporter_test.go, exporter/jaeger/jaegergrpcexporter/exporter.go, exporter/jaeger/jaegergrpcexporter/exporter_test.go, exporter/jaeger/jaegergrpcexporter/factory.go, exporter/jaeger/jaegerthrifthttpexporter/exporter.go, exporter/jaeger/jaegerthrifthttpexporter/exporter_test.go, exporter/jaeger/jaegerthrifthttpexporter/factory.go, exporter/loggingexporter/factory.go, exporter/loggingexporter/logging_exporter.go, exporter/loggingexporter/logging_exporter_test.go, exporter/opencensusexporter/factory.go, observability/observability.go, observability/observability_test.go, receiver/end_to_end_test.go
Updates https://github.com/open-telemetry/opentelemetry-service/issues/265
=> Use full name for the metrics and spans created for observability

processor/spanprocessor/factory.go, processor/spanprocessor/factory_test.go, processor/spanprocessor/span.go, processor/spanprocessor/span_test.go
Original PR got closed - Please refer to #301 for conversation history so far
=> Reopen span Processor logic PR

exporter/prometheusexporter/prometheus.go, exporter/prometheusexporter/prometheus_test.go, exporter/zipkinexporter/zipkin.go, exporter/zipkinexporter/zipkin_test.go, processor/probabilisticsamplerprocessor/probabilisticsampler.go, processor/probabilisticsamplerprocessor/probabilisticsampler_test.go
Fixes https://github.com/open-telemetry/opentelemetry-service/issues/263.
=> Clean up InitFromViper* methods

receiver/prometheusreceiver/factory.go, receiver/prometheusreceiver/metrics_receiver.go, receiver/prometheusreceiver/metrics_receiver_test.go
Follow up of https://github.com/open-telemetry/opentelemetry-service/pull/329.
=> Remove Viper and duplicated config from Prometheus receiver

config/configgrpc/configgrpc.go, config/configgrpc/empty_test.go, exporter/opencensusexporter/config.go, exporter/opencensusexporter/config_test.go, exporter/opencensusexporter/factory.go, exporter/opencensusexporter/factory_test.go, exporter/opencensusexporter/opencensus.go, service/builder/exporters_builder_test.go
=> Add common gRPC configuration settings

examples/demo/README.md, examples/demo/docker-compose.yaml, examples/demo/otel-agent-config.yaml
=> Add back health check in the agent

examples/demo/otel-agent-config.yaml
=> Fix agent configuration in the example

receiver/zipkinreceiver/proto_parse_test.go, receiver/zipkinreceiver/trace_receiver_test.go
=> Use "github.com/stretchr/testify/require" in receiver/zipkinreceiver

processor/queuedprocessor/queued_processor_test.go, processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler_test.go, processor/samplingprocessor/tailsamplingprocessor/idbatcher/id_batcher_test.go, processor/samplingprocessor/tailsamplingprocessor/processor_test.go
=> Use "github.com/stretchr/testify/require" in processor

receiver/opencensusreceiver/opencensus.go
Removes the 1 sec delay on start in favour of `ReportFatalError`
Not sure how to test this, ie how to make one of those calls actually fail in an asynchronous fashion.
closes #171
=> use ReportFatalError from the host interface

translator/conventions/empty_test.go, translator/conventions/opentelemetry.go, translator/conventions/opentelemetry_test.go
=> Define constants for semantic conventions attribute names

translator/trace/grpc_http_mapper.go, translator/trace/grpc_http_mapper_test.go
Fixes code review comment in opentelemetry-collector-contribs project. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41
=> Otel status back to HTTP status mapping function

testbed/Makefile, testbed/testbed/load_generator.go, testbed/testbed/senders.go
This makes it uniform with MetricDataSender which uses MetricsData.
=> Change TraceDataSender interface to use TraceData

CONTRIBUTING.md
The coding guidelines are important for ensuring we create a production
quality Collector. This is the first stab at the guidelines, which can
be improved further over time.
TODO: add link to a more detailed autonomous robustness doc I plan to write.
=> Add coding guidelines

exporter/exportertest/nop_exporter.go, exporter/exportertest/sink_exporter.go, exporter/exportertest/sink_exporter_test.go, exporter/prometheusexporter/prometheus.go, exporter/zipkinexporter/zipkin.go
=> Remove unsed Name() in exporters

CONTRIBUTING.md, docs/roadmap.md, docs/vision.md
It is important to have a document that describes in more detail our vision
and what we want to achieve and help to ensure all contributors work in alignment.
=> Add long-term Roadmap document

exporter/zipkinexporter/config.go, exporter/zipkinexporter/factory.go, exporter/zipkinexporter/testdata/config.yaml, exporter/zipkinexporter/zipkin.go, exporter/zipkinexporter/zipkin_test.go
=> Simplify constructing zipkin exporter

processor/samplingprocessor/tailsamplingprocessor/processor.go, processor/samplingprocessor/tailsamplingprocessor/sampling/always_sample.go, processor/samplingprocessor/tailsamplingprocessor/sampling/numeric_tag_filter.go, processor/samplingprocessor/tailsamplingprocessor/sampling/rate_limiting.go, processor/samplingprocessor/tailsamplingprocessor/sampling/string_tag_filter.go
Signed-off-by: Annanay <annanayagarwal@gmail.com>
=> Add debug logging to tail sampling filters

README.md
Signed-off-by: Annanay <annanayagarwal@gmail.com>
=> Correct README example for tail sampling

README.md
=> Move approver/maintainer list to the repo

pull_request_template.md
Addresses one part of  #350 by adding a pr template. 
The goal of the template is to set expectations around clearly communicating the change made, the testing around it and the supporting documentation.
=> Add pull request proposal

receiver/end_to_end_test.go, receiver/opencensusreceiver/config.go, receiver/opencensusreceiver/config_test.go, receiver/opencensusreceiver/factory.go, receiver/opencensusreceiver/factory_test.go, receiver/opencensusreceiver/opencensus.go, receiver/opencensusreceiver/opencensus_test.go, receiver/opencensusreceiver/testdata/config.yaml, testbed/testbed/receivers.go
This is the same pull request as https://github.com/open-telemetry/opentelemetry-collector/pull/494 just being pushed by a different github account to hopefully resolve CLA issues.
https://github.com/open-telemetry/opentelemetry-collector/issues/501
=> Add support for OpenCensus receiver listening on Unix Domain Socket (#501)

defaults/defaults.go, defaults/defaults_test.go
This change makes span processor part of default build.
=> Enable span processor

.gitignore, pull_request_template.md
- Improve PR template by adding a few line breaks.
- Add ./local/ to .gitignore for convenience, same as the contrib repo.
=> Update PR template and add local/ to .gitignore

README.md
Created from https://github.com/open-telemetry/opentelemetry-collector/pull/555#event-3048110994
Document extending collector.
=> Document extending the collector

extension/README.md
**Documentation:** Refresh to make consistent and add missing documentation
=> Update extensions README.md

processor/README.md
**Documentation:** Refresh to ensure consistency.
=> Update processor README.md

receiver/README.md
**Documentation:** Refresh documentation to make it consistent.
=> Update receiver README.md

exporter/README.md
**Documentation:** Refresh documentation so it is consistent and add missing exporter documentation
=> Update exporter README.md

go.mod, go.sum, receiver/jaegerreceiver/trace_receiver.go, testbed/go.sum
=> Bump Jaeger to 1.17.0

processor/README.md
**Documentation:** Add memory_limiter and resource processor documentation.
@pjanotti  and @dinooliva need your input on this please.
=> Update processors README.md

cmd/otelcol/Dockerfile
Resolves #587
Signed-off-by: Liam White <liam@tetrate.io>
=> add empty /tmp directory to the image

service/builder/pipelines_builder.go
Fixing a bug - Proceed with shutting down remaining processors if one of them fail to shutdown.
**Testing:** None
=> Combine errors and proceed during processors shutdown

translator/internaldata/internal_to_oc_test.go, translator/opencensus/oc_to_internal.go, translator/opencensus/oc_to_internal_test.go
As per comment here:
https://github.com/open-telemetry/opentelemetry-collector/blob/master/internal/data/resource.go#L19
=> Use NewResource instead of manually creating new struct

internal/data/metric.go, internal/data/metric_test.go, internal/data/resource.go
Design decisions:
1. We always need to initialize pimpl when use value structs because all function calls apply to a copy of the struct.
Open Question:
1. How do we signal an optional field with value structs, do we need a "HasFoo" on all the optional members?
=> Add to/from OTLP to internal metric data.

examples/otel-local-config.yaml
**Description:** Provide a local configuration file that enables all receivers and
exports locally via log. Also enables all extensions. This will be used in the documentation to help people get started.
**Testing:** locally
**Documentation:** separate documentation PR will be filed against the website once this is merged.
=> Add local config

translator/metrics/otlp_to_oc.go, translator/trace/otlp_to_oc.go
Followup from https://github.com/open-telemetry/opentelemetry-collector/pull/637
=> Resolve feedback from #637

README.md, docs/monitoring.md
Add a quick blurb about monitoring to the README.md and a monitoring.md
file with some key recommendations to users.
**Documentation:** Update to README.md and the new file.
cc @flands
=> Add Monitoring section and doc

Makefile, testbed/Makefile, testbed/testbed/test_bed.go, testbed/tests/local.yaml
Cross-compiles to more targets than linux/amd64, to improve portability.
Fixes #611
**Testing:**
CI tests added to ensure that everything consistently cross-compiles.
n/a
=> cross-compile linux/arm64, darwin/amd64, windows/amd64

.golangci.yml, translator/trace/zipkin/zipkinv1_to_protospan.go
Interestingly I found a bug in the code by enabling this.
=> Enable all govet analyzers.

examples/demo/.env, examples/demo/README.md, examples/k8s.yaml
**Description:** Update examples to use the latest dev image. These examples currently are linked in the [docs](https://opentelemetry.io/docs/collector/about/), the docs should have examples against stable releases.
/cc @flands @ccaraman
=> Update examples to latest published dev image

README.md, docs/vision.md
This was lost accidentally in https://github.com/open-telemetry/opentelemetry-collector/pull/581
=> Restore Vision document

.circleci/config.yml
To have more reliable CPU usage numbers
=> Use bigger machine for loadtests

component/extension.go, config/configcheck/configcheck_test.go, config/example_factories.go, extension/healthcheckextension/factory.go, extension/healthcheckextension/factory_test.go, extension/pprofextension/factory.go, extension/pprofextension/factory_test.go, extension/zpagesextension/factory.go, extension/zpagesextension/factory_test.go, service/service.go, service/service_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/794
=> Change Extension.Create method to be consistent with the new interfaces.

go.mod, go.sum
```
go get -u google.golang.org/grpc@v1.28.1
go mod tidy
```
=> Update grpc to 1.28.1

internal/data/common.go, internal/data/common_test.go
Caveat: This PR does not fix this when iterating, because we probably going to re-write that part.
=> Fix attributes/string maps to deal with nil values in the original data

processor/attributesprocessor/attribute_hasher.go, processor/attributesprocessor/attributes.go, processor/attributesprocessor/attributes_test.go, processor/attributesprocessor/config.go, processor/attributesprocessor/config_test.go, processor/attributesprocessor/factory.go, processor/attributesprocessor/factory_test.go, service/builder/pipelines_builder_test.go, service/builder/receivers_builder_test.go
Fixes in `service/builder/` are a bit hacky until we change example factories to use the new data-model.
=> Attributesprocessor

obsreport/obsreport_processor.go, obsreport/obsreport_test.go, processor/memorylimiter/memorylimiter.go, processor/queuedprocessor/queued_processor.go
Split from #824 to allow other components to be changed and not blocked by this PR.
=> Change obsreport to use num spans/datapoints instead of data

service/builder/builder.go, service/builder/extensions_builder.go, service/service.go, service/service_test.go
=> Move extension creation into a builder class

receiver/zipkinreceiver/trace_receiver.go, receiver/zipkinreceiver/trace_receiver_test.go
**Description:** While zero IDs are considered by most formats to be an error the Collector should not drop data because of that. This follows the same pattern already adopted for the Jaeger receiver. In order to simplify the code moved the check for nil spans to the location where the function is used so now the translation from Zipkin does not return errors.
=> Zipkin receiver should not error on zero IDs

testbed/testbed/load_generator.go, translator/internaldata/oc_to_traces.go, translator/internaldata/oc_to_traces_test.go
Benchmarks Before:
```
BenchmarkSpansWithAttributesOCToInternal-16    	  398413	      2933 ns/op	    4867 B/op	      15 allocs/op
BenchmarkSpansWithAttributesUnmarshal-16       	   97926	     11981 ns/op	    5018 B/op	     115 allocs/op
```
Benchmarks After:
```
BenchmarkSpansWithAttributesOCToInternal-16    	  467982	      2418 ns/op	    2328 B/op	      30 allocs/op
BenchmarkSpansWithAttributesUnmarshal-16       	   99662	     12013 ns/op	    5018 B/op	     115 allocs/op
```
=> Construct directly the AttributeMap in non-test code.

observability/observability.go
=> Fix exporter dropped spans metric help message

receiver/jaegerreceiver/trace_receiver.go
Split Jaeger's agent transport metric label into two values as the agent runs on two ports and accepts thrift binary and compact https://www.jaegertracing.io/docs/1.17/deployment/#agent.
=> Split Jaeger's agent transport metric label

CONTRIBUTING.md, Makefile
I find this useful when working on the collector :)
=> Add format target to makefile

exporter/jaegerexporter/config_test.go, exporter/jaegerexporter/exporter.go, exporter/jaegerexporter/exporter_test.go, exporter/jaegerexporter/factory.go, exporter/jaegerexporter/factory_test.go, internal/internal.go, receiver/jaegerreceiver/trace_receiver_test.go, testbed/testbed/senders.go, translator/trace/jaeger/jaegerproto_to_traces.go, translator/trace/jaeger/jaegerproto_to_traces_test.go, translator/trace/jaeger/traces_to_jaegerproto.go, translator/trace/jaeger/traces_to_jaegerproto_test.go
Also resolves https://github.com/open-telemetry/opentelemetry-collector/issues/840
=> Switch Jaeger exporter to internal data model

consumer/pdata/common.go, consumer/pdata/common_test.go, consumer/pdata/generated_common.go, consumer/pdata/generated_common_test.go, consumer/pdata/generated_metrics.go, consumer/pdata/generated_metrics_test.go, consumer/pdata/generated_resource.go, consumer/pdata/generated_resource_test.go, consumer/pdata/generated_trace.go, consumer/pdata/generated_trace_test.go, internal/data_generator/internal/base_fields.go, internal/data_generator/internal/base_structs.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/865
=> Add CopyTo function to all the generated structs.

translator/trace/jaeger/jaegerproto_to_traces.go, translator/trace/jaeger/jaegerproto_to_traces_test.go
This additional translation function allows to translate multiple Jaeger proto batches into one internal traces data model. 
Use case example: helps to avoid breaking down multiple Jaeger batches in SAPM receiver before sending to downstream consumers https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/receiver/sapmreceiver/trace_receiver.go#L85
=> Add translation of multiple Jaeger batches to pdata.Traces

translator/trace/jaeger/traces_to_jaegerproto.go, translator/trace/jaeger/traces_to_jaegerproto_test.go
This commit fixes a bug when "service.name" attribute is removed from resource structure during translation to jaeger proto format
=> Fix resource attribute mutation bug

go.mod, go.sum
Upgrading gopsutil to include this fix: https://github.com/shirou/gopsutil/issues/846 (will be needed when getting Windows disk stats)
=> Upgrade gopsutil to 2.20.4

service/defaultcomponents/defaults.go, service/defaultcomponents/defaults_test.go
=> Add resource processor to default components

receiver/hostmetricsreceiver/hostmetrics_receiver.go, receiver/hostmetricsreceiver/internal/scraper.go, receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go, receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper.go, receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_test.go
Rename Scraper.Close -> Scraper.Shutdown
=> Minor: Rename Host Metrics function

receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go
https://github.com/open-telemetry/opentelemetry-collector/issues/932
Minor cleanup: merge two small functions
=> Merge two small functions in host metrics filesystem scraper

examples/k8s.yaml
Replace opencensus receiver/exporter with opentelemetry. Also various
cleanup items:
* Enable memory_limiter processor
* Enable health_check extension
* Remove non-standard/required annotations and env
=> Update k8s demo

.codecov.yml
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/671
=> Enable requirement for 95% per PR coverage, 85% per project (aim to increase later)

ADOPTERS.md
Shopify to approve prior to merge
=> Add Shopify to ADOPTERS

ADOPTERS.md
OMG is using the collector in production 🙌
=> Add OrderMyGear to ADOPTERS

receiver/hostmetricsreceiver/hostmetrics_receiver.go, receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
Added benchmark test for host metrics receiver
=> Added benchmark test for host metrics receiver

ADOPTERS.md
Wait for approval from Wandera before merging
=> Add Wandera to ADOPTERS

ADOPTERS.md
Google Cloud is using OpenTelemetry Collector in production.
=> Add Google Cloud to ADOPTERS

processor/batchprocessor/batch_processor_test.go
**Description:**  The order in which Consume* and Shutdown get handled for batch processor is inconsistent when called back to back. This results in the number of items getting passed through to be inconsistent. To unblock tests and maintain coverage, the tests only check if some data got through and the batching size is 1. 
Issue #1070 has been opened to properly fix the test and ensure the total number of items sent is accounted for after shutdown has been invoked.
**Link to tracking Issue:** Fixes issue #1066 and #1069 
**Testing:** Run each of the test 100 times and no test failures.
=> Unblock prs with modified shutdown test

receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_metadata.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_metadata.go, receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_metadata.go, receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_metadata.go, receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_metadata.go, receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_metadata.go, receiver/hostmetricsreceiver/internal/scraper/virtualmemoryscraper/virtualmemory_metadata.go
Renamed hostmetrics metric metadata files from "constants" to "metadata" and added comments
=> Minor refactoring: changed hostmetrics file names

ADOPTERS.md
Grafana is using the otel collector in its internal tracing pipeline.  
@flands
=> Add Grafana as an Adopter

examples/demo/otel-agent-config.yaml, examples/demo/otel-collector-config.yaml, examples/otel-local-config.yaml, processor/README.md
* Recommend the `batch` processor for metrics
* Explain recommended processors for metrics separate from traces
=> Update documentation and examples for metric processors

.circleci/config.yml, Makefile
**Description:** Publish unit test results to CircleCI. Prep for #1029, with the idea of being able to retrieve test metadata useful for report generation.
Reopening #1131, to try and trigger the CircleCI build.
=> Publish test results

testbed/testbed/validator.go
**Description:** Addressed all TODOs in testbed/testbed/validator.go including validation of span attribute keys and values, span event names, timestamp and attributes, span link spanIds and attributes.
**Testing:** Ran all tracing correctness tests with no panics and no additional failures found in otlp and opencensus receiver and exporter combinations.
=> Added deep validation of span attributes, events and links

processor/README.md
=> Move recommended processors to top of README

Makefile
Looks like someone did the `s/ce/se` wrong :)
=> Fix typo in the ADDLICENSE target name

.circleci/check-links/README.md, .circleci/check-links/check-links.sh, .circleci/check-links/config.json, .circleci/config.yml, docs/migrating-from-opencensus.md, processor/filterprocessor/README.md, processor/samplingprocessor/tailsamplingprocessor/README.md, receiver/README.md, receiver/prometheusreceiver/README.md, receiver/zipkinreceiver/README.md
- Fixes dead links in docs
- Add circleci job to check links in markdown docs
#1155 
Tested the new `check-links` job locally with the `circleci` command line tool. 
Added .circleci/check-links/README.md
=> Fix dead links and add link checker circleci job

exporter/otlpexporter/exporter.go
No behavior changes in this PR just restructure to allow the http support to be added.
=> Refactor otlp export to allow adding a new httpSender

exporter/zipkinexporter/README.md
=> Update Zipkin README

CHANGELOG.md
First draft of changelog. Mainly just copied the commit messages, so the wording and categorization may need to be adjusted by someone more knowledgable.  Also, copied the Traces, Metrics, and Extensions sections from v0.4.0 (not sure what should be added/removed).
=> Update changelog for v0.5.0 beta

exporter/jaegerexporter/README.md, exporter/opencensusexporter/README.md, exporter/otlpexporter/README.md, receiver/jaegerreceiver/README.md, receiver/opencensusreceiver/README.md, receiver/otlpreceiver/README.md
=> Update some receiver/exporter docs

processor/metrics.go, processor/queuedprocessor/factory.go, processor/queuedprocessor/factory_test.go, processor/queuedprocessor/metrics.go, processor/queuedprocessor/queued_processor.go, processor/queuedprocessor/queued_processor_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1181
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/93
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1279
=> Add metrics support for qretry processor

.circleci/config.yml
Reduces time from 9:40mins -> 8:30mins
=> Speedup circleci by not waiting for lint before starting all other jobs

examples/demo/otel-collector-config.yaml, examples/k8s.yaml
Fixing example configs
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/1319
**Documentation:** The documentation for the zipkin exporter is ok.
=> Fixed zipkin config in the example configs

receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_metadata.go, receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper.go, receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_windows.go
Better cross-OS handling of memory states. Also update tests & improve test coverage.
=> Update memory state labels for non-Linux OSs

testbed/testbed/load_generator.go, testbed/tests/scenarios.go
This adds the ability for the load generator to send in parallel to increase
output rate.
=> Add parallelism to load generator

exporter/exporterhelper/common.go, exporter/exporterhelper/common_test.go, exporter/exporterhelper/logshelper.go, exporter/exporterhelper/metricshelper.go, exporter/exporterhelper/tracehelper.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/261
=> ExporterHelper: Add ability to configure start function and remove duplicate code

obsreport/obsreport_receiver.go
=> Remove backslash from godoc

receiver/jaegerreceiver/trace_receiver.go
Propagate the context from agent to the pipeline.
=> Properly handle context in Jaeger agent

.codecov.yml
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/671
=> Update coverage requirement for the project to 90%

receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_linux.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_windows.go
Alternative to https://github.com/open-telemetry/opentelemetry-collector/pull/1373
=> Fix Darwin lint

exporter/zipkinexporter/README.md, receiver/zipkinreceiver/README.md
=> RIP https://zipkin.io/

exporter/fileexporter/file_exporter.go, internal/data/metric.go, internal/goldendataset/resource_generator_test.go, receiver/otlpreceiver/otlp_test.go, testbed/tests/resource_processor_test.go
=> Remove linter ignores where possible

.github/CODEOWNERS, README.md
@flands - Helps the project with triaging issues and PRs
@jrcamp  - Helps the project with triaging issues and PRs - soon to be consider for approver
@rghetia - Thanks a lot for all your contributions, good luck in your new role
@nilebox - This comes with a lot of responsibilities to review PRs, and triage issues and PRs.
=> Update approvers, create triagers.

exporter/exporterhelper/common.go, exporter/exporterhelper/queued_retry.go, exporter/exporterhelper/queued_retry_test.go, exporter/jaegerexporter/README.md, exporter/jaegerexporter/config_test.go, exporter/jaegerexporter/factory.go, exporter/jaegerexporter/testdata/config.yaml, exporter/loggingexporter/logging_exporter.go, exporter/otlpexporter/README.md, exporter/otlpexporter/config_test.go, exporter/otlpexporter/factory.go, exporter/otlpexporter/testdata/config.yaml, testbed/testbed/senders.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1397
=> Use enabled for queue and retry. More human readable

exporter/exportertest/sink_exporter_test.go, receiver/fluentforwardreceiver/conversion.go, receiver/fluentforwardreceiver/conversion_test.go
Also fixed a few issues where errors were disregarded.
=> Increase Test Coverage of fluentforwardreceiver

receiver/jaegerreceiver/factory.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/561
=> Clarify error for Jaeger receiver

exporter/jaegerexporter/README.md, exporter/opencensusexporter/README.md, exporter/otlpexporter/README.md, exporter/zipkinexporter/README.md
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1459
=> Update TLS configuration for http/grpc clients

config/config.go, config/config_test.go, receiver/hostmetricsreceiver/config_test.go, receiver/jaegerreceiver/config_test.go, receiver/otlpreceiver/config_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1459
=> Improve error messages coming from config. Codes are not useful for humans

exporter/fileexporter/config_test.go, exporter/fileexporter/factory.go, exporter/fileexporter/factory_test.go, exporter/fileexporter/file_exporter.go, exporter/fileexporter/file_exporter_test.go, service/defaultcomponents/defaults.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1474
It does not fix the issue because this updates only the interface not the data model.
=> Migrate Fileexporter to the new [Trace/Metrics]Exporter interface

receiver/opencensusreceiver/README.md, receiver/otlpreceiver/README.md
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1494
=> Fix documentation for default max_recv_msg_size_mib

CHANGELOG.md
**Description:** CHANGELOG.md file only
**Link to tracking Issue:** None, I can create one if really needed
**Testing:** None needed
**Documentation:** No change needed
=> Update CHANGELOG to fix typo

component/componenttest/example_factories.go, component/componenttest/example_factories_test.go, service/builder/pipelines_builder_test.go, service/builder/receivers_builder_test.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/1542
=> Migrate componenttest factories to new the interface

translator/conventions/opentelemetry.go
Added in https://github.com/open-telemetry/opentelemetry-specification/pull/799
=> Add semantic attribute for telemetry.auto.version

Makefile
Oneliner to allow overriding the run config via make.
=> Allow overriding local config

cmd/otelcol/main_windows.go, exporter/prometheusremotewriteexporter/exporter.go, exporter/prometheusremotewriteexporter/factory.go, go.mod, go.sum, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go, receiver/zipkinreceiver/trace_receiver.go, service/builder/extensions_builder.go, service/service.go, service/service_test.go, service/service_windows.go, service/telemetry.go, translator/trace/zipkin/zipkinv1_thrift_to_protospan.go, translator/trace/zipkin/zipkinv1_to_protospan.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1600
=> Replace pkg/errors with native Go error wrapping

receiver/jaegerreceiver/trace_receiver_test.go
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/1627
=> Skip test with expired certificates

examples/otel-local-config.yaml
Remove leading 3 spaces from examples/otel-local-config.yaml
=> Format examples/otel-local-config.yaml

config/config.go, config/config_test.go, config/testdata/invalid-exporter-sub-config.yaml, config/testdata/invalid-extension-sub-config.yaml, config/testdata/invalid-pipeline-sub-config.yaml, config/testdata/invalid-processor-sub-config.yaml, config/testdata/invalid-receiver-sub-config.yaml, receiver/hostmetricsreceiver/factory.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1599
=> Identify config error when expected map is other value type

component/extension.go, extension/README.md, extension/extensionhelper/factory.go, extension/healthcheckextension/factory.go, extension/pprofextension/factory.go, extension/zpagesextension/factory.go
Fixing doc inaccuracies - Correct outdated comments and update collector-contrib link in extension readme.
Also provides more informative errors in extension factories.
**Testing:**
No test changes needed
=> Correct extension docs and comments, with error clarification

consumer/pdata/metric_test.go
Split from https://github.com/open-telemetry/opentelemetry-collector/pull/1659
=> Add compatibility test for the new generated protos and structs

translator/internaldata/metrics_to_oc.go, translator/internaldata/metrics_to_oc_test.go, translator/internaldata/oc_testdata_test.go, translator/internaldata/oc_to_metrics.go, translator/internaldata/oc_to_metrics_test.go, translator/internaldata/oc_to_old_metrics.go, translator/internaldata/old_metrics_to_oc.go
=> Add OC to new metrics structure conversion.

exporter/exportertest/sink_exporter.go, exporter/exportertest/sink_exporter_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1657
=> Change sink exporter to use the new metrics internal structs

exporter/loggingexporter/logging_exporter.go, exporter/loggingexporter/logging_exporter_test.go
=> Change logging exporter to use the new metrics internal structs

exporter/exportertest/nop_exporter_test.go, processor/memorylimiter/memorylimiter_test.go, processor/processorhelper/processor_test.go, service/builder/receivers_builder_test.go
=> Change tests to use the new internal metrics structs

testbed/testbed/data_providers.go
=> Change testbed to use the new internal metrics structs

translator/conventions/opentelemetry.go
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/deployment_environment.md
Also sorted everything first (done in separate commit, see last commit for net-new change)
=> add deployment environment semantic convention

exporter/jaegerexporter/README.md, exporter/opencensusexporter/README.md, exporter/otlpexporter/README.md, exporter/prometheusremotewriteexporter/README.md, exporter/zipkinexporter/README.md
=> Update exporter READMEs regarding certificates

translator/internaldata/oc_to_traces.go, translator/internaldata/oc_to_traces_test.go
This reverts commit 7071a9d0c7df555f7de734d376598ec2c2de7f31.
I am reverting the commit since it broke the master build.
=> Revert "Handle translation of OC span.kind attribute for client/server (#1636)"

go.mod, go.sum, testbed/testbed/child_process.go
=> Bump go.uber.org/atomic from 1.6.0 to 1.7.0

cmd/otelcol/config.yaml, examples/otel-local-config.yaml
Add OTLP metrics recevier to configs.
Updates #886
local run
=> Enable OTLP metrics receiver in example and default config

receiver/opencensusreceiver/octrace/observability_test.go
This might help prevent the issue seen in
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/3229/workflows/8455afc6-e388-4c1b-8ec0-025157fac782/jobs/32259/steps.
This might help #1711.
=> OpenCensus Flaky Test Fix

receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows_test.go
=> Running gofmt, produced diff

Makefile, go.mod, internal/tools.go
=> Add goimports to tools, used in fmt makefile

config/config_test.go, config/configtest/configtest.go
=> Use same way to load config in tests as in service

internal/buildscripts/packaging/msi/opentelemetry-collector.wxs
The corresponding change for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1164 but for core, as requested in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1165#pullrequestreview-500955605
=> Allow MSI upgrades.

Makefile
=> Use version released for otel protobuf docker

testbed/testbed/senders.go
Split from https://github.com/open-telemetry/opentelemetry-collector/pull/1924
=> Change testbed senders to call start of the exporters

testbed/correctness/metrics/correctness_test_case.go
=> Wait for 10 seconds for metrics to come, do not block forever

service/internal/resources.go, testbed/testbed/senders.go, testbed/tests/log_test.go
=> Add OTLP logs loadtest, refactor duplicate code in testbed senders

CHANGELOG.md
=> Add changelog entries for already merged PRs

exporter/zipkinexporter/config.go, exporter/zipkinexporter/config_test.go, exporter/zipkinexporter/factory.go, exporter/zipkinexporter/testdata/config.yaml, exporter/zipkinexporter/zipkin.go, exporter/zipkinexporter/zipkin_test.go, testbed/testbed/mock_backend_test.go, testbed/testbed/senders.go
=> Add queue retry to zipkin exporter, and enable them

CHANGELOG.md, service/defaultcomponents/defaults.go, service/defaultcomponents/defaults_test.go, testbed/testbed/receivers.go, testbed/testbed/senders.go, testbed/tests/log_test.go, testbed/tests/metric_test.go, testbed/tests/trace_test.go
=> Add and enable loadtest for OTLP/HTTP

config/confighttp/confighttp.go
=> Small cleanup in confighttp

cmd/pdatagen/internal/base_fields.go, component/componenttest/example_factories_test.go, consumer/pdata/common_test.go, consumer/pdata/generated_log_test.go, consumer/pdata/generated_metrics_test.go, consumer/pdata/generated_trace_test.go, processor/filterprocessor/filter_processor_test.go, processor/memorylimiter/internal/cgroups/cgroups_test.go, processor/resourceprocessor/resource_processor_test.go, receiver/kafkareceiver/kafka_receiver_test.go, service/builder/receivers_builder_test.go, translator/internaldata/oc_to_resource_test.go
=> Use assert.True and assert.False when possible

exporter/otlphttpexporter/otlp.go, exporter/otlphttpexporter/otlp_test.go
This implements the response behavior according to the spec:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md#response-1
=> Add correct handling of server error responses in OTLP/HTTP exporter

exporter/otlpexporter/README.md, exporter/otlphttpexporter/README.md, receiver/otlpreceiver/README.md
Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/1147
=> Add metrics instability notices to OTLP receivers and exporters

consumer/pdata/common.go, consumer/pdata/common_test.go
=> Remove unused public function NewAttributeValueSlice

CHANGELOG.md, component/componenttest/example_factories.go, component/processor.go, component/processor_test.go, processor/attributesprocessor/attributes_trace_test.go, processor/attributesprocessor/factory.go, processor/attributesprocessor/factory_test.go, processor/batchprocessor/batch_processor.go, processor/batchprocessor/factory.go, processor/batchprocessor/factory_test.go, processor/filterprocessor/factory_test.go, processor/memorylimiter/factory.go, processor/memorylimiter/factory_test.go, processor/processorhelper/factory.go, processor/processorhelper/factory_test.go, processor/processorhelper/processor.go, processor/queuedprocessor/factory.go, processor/queuedprocessor/factory_test.go, processor/resourceprocessor/factory.go, processor/resourceprocessor/factory_test.go, processor/resourceprocessor/resource_processor_test.go, processor/samplingprocessor/probabilisticsamplerprocessor/factory.go, processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler.go, processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler_test.go, processor/spanprocessor/factory.go, processor/spanprocessor/factory_test.go, processor/spanprocessor/span_test.go, service/builder/pipelines_builder.go
=> Rename component.TraceProcessor to component.TracesProcessor

CHANGELOG.md, component/componenttest/example_factories.go, component/receiver.go, component/receiver_test.go, exporter/exporterhelper/factory.go, exporter/fileexporter/factory.go, exporter/opencensusexporter/opencensus_test.go, exporter/otlphttpexporter/otlp_test.go, receiver/hostmetricsreceiver/factory_test.go, receiver/jaegerreceiver/factory.go, receiver/jaegerreceiver/factory_test.go, receiver/jaegerreceiver/trace_receiver.go, receiver/jaegerreceiver/trace_receiver_test.go, receiver/kafkareceiver/factory.go, receiver/kafkareceiver/factory_test.go, receiver/opencensusreceiver/factory.go, receiver/opencensusreceiver/factory_test.go, receiver/otlpreceiver/factory.go, receiver/otlpreceiver/factory_test.go, receiver/otlpreceiver/otlp_test.go, receiver/receiverhelper/factory.go, receiver/receiverhelper/factory_test.go, receiver/zipkinreceiver/factory.go, service/builder/receivers_builder.go, testbed/testbed/receivers.go
=> Rename component.TraceReceiver to component.TracesReceiver

internal/processor/filterlog/filterlog_test.go, internal/processor/filtermatcher/.nocover, internal/processor/filtermatcher/filtermatcher_test.go, internal/processor/filterspan/filterspan_test.go
=> Extract common tests for log and span filtering

internal/processor/filterexpr/matcher.go, processor/filterprocessor/expr_test.go
=> Fix usage of removed pdata.StringValue, PR merged after the remove

exporter/prometheusremotewriteexporter/helper.go
Note: When I refer to a "cumulative histogram" I am not reffering to aggregation temporality, I am reffering to a cumulative histogram as defined [here](https://en.wikipedia.org/wiki/Histogram#Cumulative_histogram)
Fixing a bug that does not send histograms to third party Prometheus backends the way they expect it. Prometheus histograms are cumulative, and OTLP histograms are not. Before this PR histogram bucket values were simply copied directly over when converting to Prometheus timeseries, however this PR now adds a rolling cumulative count which gets appended to each timeseries, hence making the histogram cumulative.
According to the [histograms proto definition](https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/metrics/v1/metrics.pr …
=> converted histograms to cumulative in prometheus remote write exporter

exporter/prometheusremotewriteexporter/helper.go
=> Use lowercase variable name, do not empty initialize array

cmd/pdatagen/internal/base_structs.go, consumer/pdata/generated_common.go, consumer/pdata/generated_log.go, consumer/pdata/generated_metrics.go, consumer/pdata/generated_trace.go
=> Simplify MoveAndAppendTo logic in generated slices

.github/dependabot.yml
=> Update dependabot to run daily, add @bogdandrutu as assignee.

exporter/README.md, exporter/fileexporter/README.md, exporter/jaegerexporter/README.md, exporter/loggingexporter/README.md, exporter/opencensusexporter/README.md, exporter/otlpexporter/README.md, exporter/prometheusexporter/README.md, exporter/prometheusremotewriteexporter/README.md, exporter/zipkinexporter/README.md
- Provide getting started information
- Link to duplicated information
- Stop linking to testdata which may or may not be valid
=> Update exporter READMEs

exporter/exportertest/sink_exporter.go, processor/attributesprocessor/attributes_log_test.go, processor/filterprocessor/filter_processor_test.go, receiver/hostmetricsreceiver/factory_test.go, receiver/receiverhelper/scrapercontroller_test.go
=> Remove usage of deprecated exportertest package

.golangci.yml
=> Remove unnecessary linter exclude from golangci

obsreport/obsreport.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1082
=> Remove public func CountMetricPoints, move it to prometheus where is the last usage

README.md
=> fix getting started link in readme

processor/metrics.go
=> Remove unused public func ServiceNameForNode

.github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md, docs/design.md, docs/monitoring.md, docs/roadmap.md, docs/troubleshooting.md, examples/README.md, exporter/exporterhelper/README.md, exporter/prometheusremotewriteexporter/DESIGN.md, extension/README.md, processor/README.md, processor/memorylimiter/README.md, receiver/prometheusreceiver/DESIGN.md
- Remove unnecessary whitespace
- Other minor cleanup
=> Fix README typos

exporter/exporterhelper/metricshelper.go
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com
=> Remove unused public function, usage in contrib will be soon removed

.circleci/config.yml, .golangci.yml, Makefile, cmd/issuegenerator/main.go, cmd/mdatagen/main.go, cmd/mdatagen/main_test.go, config/configauth/oidc_server_test.go, go.sum, internal/processor/filterset/config_test.go, internal/processor/filterset/regexp/config_test.go, processor/processorhelper/attraction_test.go, receiver/jaegerreceiver/jaeger_agent_test.go, receiver/jaegerreceiver/trace_receiver_test.go, translator/trace/zipkin/zipkinv1_to_protospan_test.go
=> Switch to use gosec from golangci lint

exporter/exporterhelper/queued_retry.go
=> Add more trace annotations to the queue-retry logic

exporter/exporterhelper/constants.go, exporter/exporterhelper/logshelper.go, exporter/exporterhelper/logshelper_test.go, exporter/exporterhelper/metricshelper.go, exporter/exporterhelper/metricshelper_test.go, exporter/exporterhelper/tracehelper.go, exporter/exporterhelper/tracehelper_test.go
Signed-off-by: Pavel Kositsyn <kositsyn.pa@phystech.edu>
Fixed panic on nil logger in exporters creation via helper functions
**Link to tracking Issue:** #2086 
**Testing:** added tests for nil logger
=> Add check for nil logger in exporterhelper functions

obsreport/obsreport_processor.go, obsreport/obsreport_test.go, processor/memorylimiter/memorylimiter.go, processor/memorylimiter/memorylimiter_test.go, processor/processorhelper/processor.go, processor/queuedprocessor/queued_processor.go
=> Remove usage and the global funcs in obsreport

receiver/prometheusreceiver/internal/ocastore.go
Otherwise, static analysis tools are not very useful on this package and the interface types are introduced arbitarily not because of need.
=> Remove unnecessary interfaces from the Prometheus receiver

exporter/otlpexporter/README.md
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2170 
=> Fix readme for OTLP exporter

receiver/prometheusreceiver/README.md
We will eventually find a long-term solution to these problems but in the meantime let the users know about the limitations.
=> Add warning about the Prometheus receiver's capabilities

internal/goldendataset/resource_generator.go, receiver/otlpreceiver/otlp_test.go, translator/conventions/opentelemetry.go, translator/internaldata/metrics_to_oc_test.go, translator/internaldata/oc_testdata_test.go, translator/internaldata/oc_to_resource.go, translator/internaldata/resource_to_oc.go, translator/trace/jaeger/jaegerproto_to_traces.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2029
=> Remove usage of deprecated host.hostname

translator/internaldata/resource_to_oc.go
The problem was that there were multiple places (duplicate code) where different parts of
the OC Node struct were initialized, so tests needed to cover all duplicated code. The
current PR removes duplicate code so ensures the coverage is not flaky.
=> Remove flakiness of the code coverage in the resource to OC

consumer/pdata/common.go, consumer/pdata/common_test.go, exporter/opencensusexporter/opencensus_test.go, processor/attributesprocessor/attributes_log_test.go, receiver/kafkareceiver/zipkin_unmarshaller_test.go
=> Fix small nit in InitEmptyWithCap, optimize CopyTo

exporter/exporterhelper/common.go, exporter/exporterhelper/queued_retry.go, processor/processorhelper/processor.go
=> Add more trace annotations, so zpages are more useful to determine failures

CHANGELOG.md, exporter/kafkaexporter/README.md, exporter/kafkaexporter/config.go, exporter/kafkaexporter/factory.go, exporter/kafkaexporter/factory_test.go, exporter/kafkaexporter/jaeger_marshaller.go, exporter/kafkaexporter/jaeger_marshaller_test.go, exporter/kafkaexporter/kafka_exporter.go, exporter/kafkaexporter/kafka_exporter_test.go, exporter/kafkaexporter/marshaller.go, exporter/kafkaexporter/marshaller_test.go, exporter/kafkaexporter/otlp_marshaller.go, exporter/kafkaexporter/otlp_marshaller_test.go
This reverts commit 42a7f662b050138f589e16233e393ab71e051374 because it failed
the build https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/4718/workflows/59a274c1-241d-4928-8411-2c5330c7fc47
=> Revert "Add metrics to Kafka exporter (#1966)"

CHANGELOG.md, exporter/kafkaexporter/README.md, exporter/kafkaexporter/config.go, exporter/kafkaexporter/factory.go, exporter/kafkaexporter/factory_test.go, exporter/kafkaexporter/jaeger_marshaller.go, exporter/kafkaexporter/jaeger_marshaller_test.go, exporter/kafkaexporter/kafka_exporter.go, exporter/kafkaexporter/kafka_exporter_test.go, exporter/kafkaexporter/marshaller.go, exporter/kafkaexporter/marshaller_test.go, exporter/kafkaexporter/otlp_marshaller.go, exporter/kafkaexporter/otlp_marshaller_test.go
Reverts open-telemetry/opentelemetry-collector#2222
=> Revert "Revert "Add metrics to Kafka exporter (#1966)""

exporter/exporterhelper/common.go, exporter/exporterhelper/common_test.go, exporter/exporterhelper/metricshelper_test.go, exporter/exporterhelper/queued_retry.go, exporter/exporterhelper/queued_retry_test.go, exporter/exporterhelper/resource_to_label.go, exporter/jaegerexporter/factory.go, exporter/kafkaexporter/factory.go, exporter/otlpexporter/factory.go, exporter/otlpexporter/factory_test.go, exporter/otlphttpexporter/factory.go, exporter/prometheusremotewriteexporter/config_test.go, exporter/prometheusremotewriteexporter/factory.go, exporter/zipkinexporter/factory.go
=> Improve go readability for default settings func names

cmd/pdatagen/internal/base_fields.go, cmd/pdatagen/internal/base_structs.go, consumer/pdata/generated_common.go, consumer/pdata/generated_common_test.go, consumer/pdata/generated_log.go, consumer/pdata/generated_log_test.go, consumer/pdata/generated_metrics.go, consumer/pdata/generated_metrics_test.go, consumer/pdata/generated_resource.go, consumer/pdata/generated_resource_test.go, consumer/pdata/generated_trace.go, consumer/pdata/generated_trace_test.go, consumer/pdata/trace_test.go
=> Remove deadcode in pdatagen, remove InitEmpty funcs

receiver/kafkareceiver/factory_test.go
This PR changes a variable name that gets flagged by security scanners
resolves issue https://github.com/open-telemetry/opentelemetry-collector/issues/2286
=> changed variable name in kafka receiver

.circleci/config.yml
=> Remove contribtest from circleCI, start using github action

.golangci.yml, cmd/issuegenerator/main.go
=> Disable gosec rule for that particular line

consumer/pdata/spanid.go, consumer/pdata/trace_test.go, translator/internaldata/traces_to_oc.go, translator/trace/jaeger/traces_to_jaegerproto.go, translator/trace/zipkin/traces_to_zipkinv2.go
=> Extend IsEmpty to SpanID, remove usage of IsValid

Makefile
After this PR we will release also utils modules like pdatagen or mdatagen.
=> Use same scripts to add/push/delete tags as in contrib

consumer/pdata/spanid.go, consumer/pdata/traceid.go, internal/data/spanid.go, internal/data/traceid.go, internal/goldendataset/span_generator.go, internal/goldendataset/span_generator_test.go
=> Rename IsValid with IsEmpty for internal data

Makefile
=> Remove what was left from #2337

CHANGELOG.md, processor/resourceprocessor/config.go, processor/resourceprocessor/factory.go, processor/resourceprocessor/factory_test.go
=> Remove deprecated fields from resource processor config

Makefile
=> Remove empty rule from makefile

examples/demo/docker-compose.yaml, examples/demo/otel-agent-config.yaml, examples/demo/otel-collector-config.yaml, examples/local/otel-config.yaml
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2376
=> Update otel demo to use OTLP

cmd/pdatagen/internal/base_slices.go, consumer/pdata/generated_common_test.go, consumer/pdata/generated_log_test.go, consumer/pdata/generated_metrics_test.go, consumer/pdata/generated_trace_test.go
=> Update slice Append tests, improve logic, fix equal order

.github/CODEOWNERS, CONTRIBUTING.md, README.md, consumer/pdata/trace.go, exporter/otlphttpexporter/otlp.go, translator/conventions/aws.go, translator/conventions/opentelemetry.go, translator/internaldata/resource_to_oc.go, translator/trace/grpc_http_mapper.go, translator/trace/protospan_translation.go
=> Update links to main default branch in repos that were converted

.circleci/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .github/workflows/build-and-test.yml, .github/workflows/check-links.yaml, .github/workflows/check-links/check-links.sh, .github/workflows/contrib-tests.yml, README.md, config/configgrpc/README.md, config/confighttp/README.md, config/confignet/README.md, config/configtls/README.md, docs/troubleshooting.md, exporter/jaegerexporter/README.md, exporter/opencensusexporter/README.md, exporter/otlpexporter/README.md, exporter/prometheusremotewriteexporter/README.md, exporter/zipkinexporter/README.md, receiver/hostmetricsreceiver/README.md, receiver/jaegerreceiver/README.md, receiver/opencensusreceiver/README.md, receiver/otlpreceiver/README.md, receiver/zipkinreceiver/README.md, testbed/README.md
=> Update links after master -> main branch change

.circleci/config.yml, .github/workflows/build-and-test.yml
=> Remove lint check from circle CI, require only github actions

exporter/zipkinexporter/README.md
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2332
=> Fix supported pipeline for Zipkin

component/component.go
**Description:** This PR changes component.Shutdown documentation to clarify that buffers need to be cleared and data sent to the next component on shutdown
**Link to tracking Issue:** #2443
Ping @bogdandrutu
=> docs(component): improves the documentation on shutdown

CONTRIBUTING.md, README.md
Move contributing doc within Getting Involved link.
Depends on #2461
=> Add security doc link to README

receiver/jaegerreceiver/README.md
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/2440
=> Fix jaegerreceiver README example

docs/ga-roadmap.md
=> [PROPOSAL] Roadmap to stabilize/GA the Collector and its components

consumer/consumertest/nop.go, consumer/consumertest/sink.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/2477
=> Cleanup comments in componenttest package

.circleci/config.yml
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1234
=> Run windows tests only on github action

.github/workflows/build-and-test.yml, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go
=> Add unittest step to github action

.codecov.yml
Addresses https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2390
=> Update codecov to ignore third_party dir

.github/workflows/build-and-test.yml
=> Fix cache key for go tools, be same as setup task

CHANGELOG.md, consumer/pdata/spanid.go, consumer/pdata/traceid.go
=> Remove deprecated function IsValid from trace/span ID

.github/workflows/build-and-test.yml, Makefile
=> Run build binaries in parallel

cmd/pdatagen/internal/base_fields.go, consumer/pdata/generated_common.go, consumer/pdata/generated_log.go, consumer/pdata/generated_metrics.go, consumer/pdata/generated_resource.go, consumer/pdata/generated_trace.go
=> Remove warning about IsNil, this function no-longer exists

consumer/consumertest/err.go, consumer/consumertest/err_test.go, consumer/consumertest/sink.go, exporter/otlphttpexporter/otlp_test.go, processor/fanoutconnector_test.go, receiver/kafkareceiver/kafka_receiver_test.go, receiver/otlpreceiver/logs/otlp_test.go, receiver/otlpreceiver/metrics/otlp_test.go, receiver/otlpreceiver/trace/otlp_test.go
=> Add new test consumer that returns the given error

testbed/correctness/metrics/metric_diff.go, testbed/correctness/metrics/metric_diff_test.go
=> Remove unused code in correctness metrics

Makefile, Makefile.Common, internal/tools/go.mod, internal/tools/tools.go
=> Avoid running staticchek twice, once in golangci and one directly

CHANGELOG.md, component/componenterror/errors.go
=> Remove deprecated componenterror.CombineErrors

exporter/exporterhelper/common.go, exporter/exporterhelper/common_test.go
=> Small nit fix in exporterhelper, move private var to test

component/componenttest/nop_host.go, component/componenttest/nop_host_test.go, exporter/prometheusexporter/prometheus_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/2540
=> Do not expose NopHost struct

consumer/consumer.go
=> Small nit fix in consumer godoc

testutil/metricstestutil/metricsutil.go, testutil/metricstestutil/metricsutil_test.go
=> Small cleanup in testutil/metrics

component/component.go, component/componenttest/error_waiting_host.go, component/componenttest/nop_host.go, service/builder/exporters_builder.go, service/builder/extensions_builder.go, service/service.go, testbed/testbed/receivers.go, testbed/testbed/senders.go
=> Do not expose entire config in the Host API

.codecov.yml
=> Do not wait for all CI actions to pass before reporting

cmd/schemagen/go.sum, go.mod, go.sum
=> Bump contrib.go.opencensus.io/exporter/prometheus from 0.2.0 to 0.3.0

component/componenttest/example_receiver.go
=> Remove unused code from componenttest

component/component.go, component/host.go
=> Split host definition into its own file

config/configtest/configtest_test.go, config/configtest/testdata/config.yaml
=> Use nop factories in configtest package

config/config_test.go, internal/testcomponents/example_exporter.go, internal/testcomponents/example_exporter_test.go, internal/testcomponents/example_extension.go, internal/testcomponents/example_factories.go, internal/testcomponents/example_processor.go, internal/testcomponents/example_receiver.go, internal/testcomponents/example_receiver_test.go, service/internal/builder/exporters_builder_test.go, service/internal/builder/factories_test.go, service/internal/builder/pipelines_builder_test.go, service/internal/builder/receivers_builder_test.go, service/service_test.go
=> Move example components to internal package

exporter/prometheusremotewriteexporter/DESIGN.md, receiver/prometheusreceiver/DESIGN.md, receiver/prometheusreceiver/README.md
Signed-off-by: yeya24 <yb532204897@gmail.com>
=> Fix some typos

service/service.go
=> Move code in service to follow a consistent structure

.github/dependabot.yml
=> Run make gendependabot

.golangci.yml
=> Fix todo to enable modules-download-mode in golangci

exporter/jaegerexporter/exporter_test.go
=> Change Jaeger exporter to not use internal data

exporter/kafkaexporter/otlp_marshaller.go, exporter/kafkaexporter/otlp_marshaller_test.go
=> Change Kafka exporter to not use internal data

translator/trace/zipkin/attributekeys.go
=> Remove unused zipkin attribute keys

internal/processor/filterconfig/config.go, internal/testdata/common.go, testbed/testbed/receivers.go
=> Remove unused public constants

CONTRIBUTING.md
updated CONTRIBUTING.md to reference the correct golang version needed for local development (1.15 instead of 1.14)
https://github.com/open-telemetry/opentelemetry-collector/issues/2717
=> update CONTRIBUTING.md with correct golang version (#2717)

README.md
=> Remove Nail Islamov from README

translator/conventions/trace.go
=> Remove unspecified semantic convention

consumer/pdata/spanid_test.go, consumer/pdata/trace_test.go, consumer/pdata/traceid_test.go
=> Split trace/span id tests in different files

service/builder.go, service/builder_test.go, service/internal/builder/extensions_builder_test.go, service/internal/builder/factories_test.go, service/service.go, service/service_test.go, service/testdata/otelcol-config-minimal.yaml, service/testdata/otelcol-config.yaml, service/testdata/otelcol-nop.yaml, service/zpages.go
=> Split service builder and zpages from application

receiver/prometheusreceiver/metrics_receiver.go
=> Fix prometheusreceiver context, avoid using start context

obsreport/obsreport_processor.go, obsreport/obsreport_test.go, processor/memorylimiter/memorylimiter.go, processor/memorylimiter/memorylimiter_test.go
=> configure obsReport.NewProcessor with struct

internal/testcomponents/example_exporter.go, internal/testcomponents/example_extension.go, internal/testcomponents/example_factories.go, internal/testcomponents/example_processor.go, internal/testcomponents/example_receiver.go, service/internal/builder/extensions_builder_test.go, service/internal/builder/factories_test.go, service/internal/builder/pipelines_builder_test.go, service/internal/builder/receivers_builder_test.go
=> Remove more usage of example factories, reduce example factories code

service/defaultcomponents/default_exporters_test.go
Disable lifecycle test for logging exporter on darwin until the root cause can be investigated.
=> Disable lifecycle test for logging exporter on darwin

config/configauth/authenticator.go, exporter/fileexporter/file_exporter.go, exporter/prometheusexporter/collector_test.go, exporter/prometheusexporter/prometheus.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go, receiver/kafkareceiver/factory_test.go, receiver/kafkareceiver/kafka_receiver_test.go, receiver/prometheusreceiver/metrics_receiver.go, receiver/zipkinreceiver/trace_receiver.go
=> Make IDE happy, remove unused params or replace with _

service/defaultcomponents/default_exporters_test.go, service/defaultcomponents/default_receivers_test.go
=> Fix typo in PR #2773

CHANGELOG.md
Fixes: https://github.com/open-telemetry/opentelemetry-collector/issues/2783
=> Document that example components were removed, and how to migrate

config/configcheck/configcheck.go
=> Small fixes in configcheck package

CHANGELOG.md
=> Update changelog entries

CHANGELOG.md, cmd/pdatagen/internal/metrics_structs.go, consumer/pdata/generated_metrics.go, consumer/pdata/generated_metrics_test.go, testbed/correctness/metrics/metric_diff.go, translator/internaldata/metrics_to_oc.go, translator/internaldata/oc_to_metrics.go
=> Rename DoubleExemplar to Exemplar, preparation for proto upgdate to v0.8.0

README.md
=> Remove andrewhsu@ from triager role for collector

config/configparser/config.go, config/configparser/config_test.go
=> Avoid using variable name that collides with imported package

go.mod
=> Run make gotidy

service/application.go, service/application_test.go, testutil/testutil.go
This allows the same Application to load config multiple times during a single run. No public way to trigger the configuration reload was added.
**Testing:**
Added tests to validate success and failures on reload of config.
=> Add capability to reload configuration

internal/buildscripts/packaging/fpm/otel-collector.service
Signed-off-by: Conor Evans <coevans@tcd.ie>
=> [FPM Package] fix otel-collector.service description

testbed/testbed/mock_backend.go
=> Remove unused func in testbed.MockBackend

exporter/prometheusremotewriteexporter/exporter_test.go, exporter/zipkinexporter/zipkin_test.go, processor/filterprocessor/config_test.go, service/internal/builder/exporters_builder.go, service/internal/builder/pipelines_builder.go, service/internal/builder/receivers_builder.go, testbed/testbed/receivers.go
=> Avoid using config2 in imports, remove duplicate code in exporter builder

translator/trace/grpc_http_mapper.go, translator/trace/grpc_http_mapper_test.go
=> Remove unused public func HTTPStatusCodeFromOCStatus

config/internal/configsource/manager.go, config/internal/configsource/manager_test.go, config/parser.go, config/parser_test.go, service/application_test.go, service/parserprovider/inmemory.go
=> Limit config.Parser APIs that expose Viper

.golangci.yml
=> Remove usage of deprecated scopelint, replace with exportloopref as suggested

config/config.go
=> Small nits in config.go

exporter/prometheusexporter/collector_test.go
Previously we were plainly comparing slices of proto Quantile values,
but there were flakes due to ordering and some random extra values.
This change just extracts those quantile values into a
map[float64]float64 for direct comparisons.
Fixes #2922
=> exporter/prometheus: replace Quantile proto comparisons by map

CHANGELOG.md
=> Update changelog with already merged PRs

examples/demo/app/go.mod, go.mod
=> Use go 1.15 everywhere in the project

testbed/testbed/senders.go
=> Fix comments in testbed/senders.go

component/receiver.go, component/receiver_test.go, exporter/otlpexporter/otlp_test.go, exporter/otlphttpexporter/otlp_test.go, internal/testcomponents/example_receiver.go, receiver/jaegerreceiver/factory.go, receiver/kafkareceiver/factory.go, receiver/kafkareceiver/factory_test.go, receiver/opencensusreceiver/factory.go, receiver/opencensusreceiver/factory_test.go, receiver/opencensusreceiver/octrace/doc.go, receiver/opencensusreceiver/opencensus.go, receiver/otlpreceiver/factory.go, receiver/otlpreceiver/factory_test.go, receiver/receiverhelper/factory.go, receiver/receiverhelper/factory_test.go, receiver/zipkinreceiver/factory.go, receiver/zipkinreceiver/factory_test.go
=> Fix all TraceReceiver usages, use TracesReceiver

consumer/consumererror/signalerrors.go
=> Small typos in consumererror

cmd/pdatagen/internal/base_fields.go, cmd/pdatagen/internal/trace_structs.go, consumer/pdata/generated_log.go, consumer/pdata/generated_trace.go, consumer/pdata/spanid.go, consumer/pdata/traceid.go, translator/trace/zipkin/zipkinv2_to_traces.go
Ensure we don't leak it by mistake
=> Encapsulate the internal representation of the ids.

receiver/zipkinreceiver/trace_receiver_test.go, testutil/testutil.go
=> Remove testutil.GenerateNormalizedJSON, used only in one test in core and contrib

translator/trace/protospan_translation.go, translator/trace/protospan_translation_test.go, translator/trace/zipkin/zipkinv1_to_protospan.go, translator/trace/zipkin/zipkinv2_to_traces.go
=> Remove unused code and unused arguments from translator package

processor/probabilisticsamplerprocessor/probabilisticsampler_test.go
=> Remove couple of Append usages

receiver/zipkinreceiver/trace_receiver.go
Description:
Ex. Reduce the judgment of zipkin v1 version
=> Zipkin Receiver: Reduce the judgment of zipkin v1 version

cmd/pdatagen/internal/base_slices.go, consumer/pdata/generated_common.go, consumer/pdata/generated_common_test.go, consumer/pdata/generated_log.go, consumer/pdata/generated_log_test.go, consumer/pdata/generated_metrics.go, consumer/pdata/generated_metrics_test.go, consumer/pdata/generated_trace.go, consumer/pdata/generated_trace_test.go
=> Refactor genpdata for slices to avoid duplicate code

processor/probabilisticsamplerprocessor/factory.go, processor/probabilisticsamplerprocessor/probabilisticsampler.go, processor/probabilisticsamplerprocessor/probabilisticsampler_test.go
=> Change ProbabilisticSamplerProcessor to use the processorhelper

exporter/loggingexporter/logging_exporter_test.go, exporter/prometheusexporter/accumulator_test.go
=> Change more Append usage with AppendEmpty when possible

service/logger.go
=> Avoid manual parsing for log level flag, zap already implements flags Var interface

docs/service-extensions.md, processor/spanprocessor/config.go, receiver/opencensusreceiver/testdata/config.yaml, receiver/scraperhelper/scrapercontroller.go
=> Remove references to configmodels

processor/batchprocessor/batch_processor.go, processor/batchprocessor/batch_processor_test.go, processor/batchprocessor/factory.go
=> Small cleanups in batchprocessor

translator/internaldata/resource_to_oc_test.go, translator/trace/jaeger/jaegerproto_to_traces.go
=> Remove some usage of Append where easy to avoid

cmd/otelcol/main.go, component/application_info.go, internal/version/version.go, service/application.go, testbed/testbed/otelcol_runner.go
=> Remove GitHash from application info, no longer useful, version is tag or githash

receiver/kafkareceiver/kafka_receiver_test.go
=> Remove custom waitfor logic, replace with assert.Eventually

receiver/kafkareceiver/kafka_receiver_test.go
=> Fix Kafka receiver flaky tests

receiver/opencensusreceiver/opencensus.go, receiver/opencensusreceiver/opencensus_test.go
=> Avoid returning Already[Started/Stopped] if omitted after

.circleci/config.yml, .github/workflows/build-and-test.yml, Makefile
=> Remove Correctness tests from circleCI, enable on github actions

receiver/jaegerreceiver/trace_receiver.go, receiver/jaegerreceiver/trace_receiver_test.go
=> Try fix TestDefaultReceivers/jaege, graceful shutdown Jaeger receiver

config/configloader/config.go, config/parser.go
=> Remove support for deprecated factory unmarshaler, remove last public Viper API

go.mod, go.sum
=> Remove unnecessary deps, upgrade indirect deps

component/componenthelper/component.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/3048
=> Improve comments and code in componenthelper package

.github/workflows/build-and-test.yml, Makefile, Makefile.Common
=> Remove unused environment variables from Makefile

Makefile
=> Remove GitHash setup from Makefile

.github/workflows/scripts/verify-dist-files-exist.sh, Makefile
Added darwin/arm64 build
https://github.com/open-telemetry/opentelemetry-collector/issues/2172
Tested build generation by running `make binaries-darwin_arm64`
=> Added macos arm64 build

config/config.go
=> Remove unused interface config.NamedEntity

exporter/exporterhelper/logshelper.go, exporter/exporterhelper/logshelper_test.go, exporter/exporterhelper/metricshelper.go, exporter/exporterhelper/metricshelper_test.go, exporter/exporterhelper/tracehelper.go, exporter/exporterhelper/tracehelper_test.go, exporter/prometheusexporter/prometheus.go, obsreport/obsreport_exporter.go, obsreport/obsreport_test.go, obsreport/obsreporttest/obsreporttest.go, obsreport/obsreporttest/obsreporttest_test.go
=> Use config.ComponentID in obsreport exporter settings

README.md
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/3096
=> Add @alolita as Triager for collector

processor/processorhelper/processor.go, processor/processorhelper/processor_test.go
=> Use config.ComponentID in processor helper internal

config/parser.go
=> Small nit fixes in the config.Parser

receiver/jaegerreceiver/README.md
=> Fix port number in jaegerreceiver/README.md

CHANGELOG.md, processor/probabilisticsamplerprocessor/probabilisticsampler_test.go, translator/trace/jaeger/jaegerproto_to_traces.go, translator/trace/jaeger/jaegerproto_to_traces_test.go, translator/trace/jaeger/jaegerthrift_to_traces_test.go, translator/trace/protospan_translation.go, translator/trace/zipkin/status_code.go, translator/trace/zipkin/zipkinv1_thrift_to_protospan_test.go, translator/trace/zipkin/zipkinv1_to_protospan_test.go
=> Remove tracetranslator.TagHTTPStatusCode, use conventions.AttributeHTTPStatusCode

CHANGELOG.md, translator/trace/protospan_translation.go
=> Unexport AttributeArrayToSlice, not used in core or contrib

CONTRIBUTING.md
Update Go version on `CONTRIBUTING.md` to Go 1.16, follow up to #3010.
=> Update Go version

CHANGELOG.md, translator/trace/protospan_translation.go, translator/trace/zipkin/status_code.go, translator/trace/zipkin/traces_to_zipkinv2.go
=> Remove Zipkin specific translation constants, move to internal

Makefile
=> Fix license misspelling

exporter/otlpexporter/otlp.go
=> Avoid one unnecessary allocation in grpc OTLP exporter

extension/zpagesextension/README.md
Added the available routes in the zPages extension README for the users
convenience.
=> Add the available routes to the README of zPages

processor/batchprocessor/splitlogs.go, processor/batchprocessor/splitlogs_test.go
Benchmarks Before:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkSplitLogs
BenchmarkSplitLogs-16    	   16072	     76529 ns/op	  114408 B/op	     669 allocs/op
PASS
```
Benchmarks After:
```
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkSplitLogs
BenchmarkSplitLogs-16    	   21795	     56491 ns/op	   88952 B/op	     556 allocs/op
PASS
```
Benchmarks Reference Clone:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/processor/batchprocessor
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkCloneLogs
BenchmarkCloneLogs-16    	   22305	     52075 ns/op	   85976 B/op	     503 allocs/op
PASS …
```
=> Fix batch processor logs reorder, improve performance

.github/workflows/dependabot.yml
=> Add dependabot tidier to run on each dependabot PR

translator/trace/jaeger/traces_to_jaegerproto_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> Fix small ineffassign issue

component/componenttest/nop_exporter.go, component/componenttest/nop_processor.go, receiver/zipkinreceiver/trace_receiver_test.go
=> Small nit fixes, remove unnecessary mock and overrides

consumer/consumerhelper/common.go, consumer/consumerhelper/common_test.go, consumer/consumerhelper/logs.go, consumer/consumerhelper/logs_test.go, consumer/consumerhelper/metrics.go, consumer/consumerhelper/metrics_test.go, consumer/consumerhelper/traces.go, consumer/consumerhelper/traces_test.go, exporter/exporterhelper/logshelper.go, exporter/exporterhelper/logshelper_test.go, exporter/exporterhelper/metricshelper.go, exporter/exporterhelper/metricshelper_test.go, exporter/exporterhelper/tracehelper.go, exporter/exporterhelper/tracehelper_test.go
=> Add initial implementation of the consumerhelper

processor/filterprocessor/filter_processor_test.go
=> Change filter_processor_test to use pdata

config/configauth/configauth.go, config/configloader/config.go, config/identifiable.go, config/identifiable_test.go, exporter/exporterhelper/logshelper_test.go, exporter/exporterhelper/metricshelper_test.go, exporter/exporterhelper/tracehelper_test.go, processor/filterprocessor/config_test.go
=> Rename config.IDFromString to NewIDFromString, remove MustIDFromString

receiver/hostmetricsreceiver/hostmetrics_receiver_test.go, receiver/prometheusreceiver/internal/metricfamily.go
=> Fix: append result not assigned to the same slice (gocritic)

cmd/issuegenerator/go.sum, obsreport/observability.go
=> Small readability fix in obsreport

exporter/exporterhelper/common.go, exporter/exporterhelper/common_test.go, exporter/exporterhelper/logs.go, exporter/exporterhelper/logs_test.go, exporter/exporterhelper/metrics.go, exporter/exporterhelper/metrics_test.go, exporter/exporterhelper/queued_retry_test.go, exporter/exporterhelper/traces.go, exporter/exporterhelper/traces_test.go
=> Use consumerhelper for exporterhelper, add WithCapabilities

config/internal/configsource/manager_test.go, exporter/jaegerexporter/exporter.go, exporter/jaegerexporter/exporter_test.go, receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_test.go
=> Small style issues in code, unnecessary wrapping

receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_unix.go
=> Fix lint error that breaks the build

receiver/opencensusreceiver/opencensus_test.go
=> Small nits in OpenCensus receiver tests

exporter/fileexporter/file_exporter_test.go
=> Improve filexporter tests

receiver/prometheusreceiver/metrics_reciever_external_labels_test.go
=> Fix Prometheus receiver external label test, PR merged on old base

exporter/exporterhelper/logs_test.go, exporter/exporterhelper/metrics_test.go, exporter/exporterhelper/traces_test.go, exporter/loggingexporter/logging_exporter_test.go, exporter/otlpexporter/otlp_test.go, exporter/prometheusremotewriteexporter/exporter_test.go, internal/otlptext/logs_test.go, internal/otlptext/metrics_test.go, internal/otlptext/traces_test.go, internal/testdata/log.go, internal/testdata/log_test.go, internal/testdata/metric.go, internal/testdata/metric_test.go, internal/testdata/trace.go, internal/testdata/trace_test.go, processor/attributesprocessor/attributes_log_test.go, processor/attributesprocessor/attributes_trace_test.go, processor/batchprocessor/batch_processor_test.go, processor/processorhelper/logs_test.go, processor/processorhelper/metrics_test.go, processor/processorhelper/traces_test.go, processor/spanprocessor/span_test.go, translator/internaldata/oc_to_metrics_test.go, translator/internaldata/oc_to_traces_test.go, translator/trace/jaeger/jaegerproto_to_traces_test.go, translator/trace/jaeger/jaegerthrift_to_traces_test.go, translator/trace/jaeger/traces_to_jaegerproto_test.go, translator/trace/zipkin/traces_to_zipkinv2_test.go, translator/trace/zipkin/zipkinv2_to_traces_test.go
=> Remove testdata GetEmpty for all signals

exporter/jaegerexporter/exporter.go, exporter/kafkaexporter/factory.go, exporter/loggingexporter/logging_exporter.go, exporter/opencensusexporter/factory.go, exporter/otlpexporter/factory.go, exporter/otlphttpexporter/factory.go, exporter/prometheusexporter/factory.go, exporter/prometheusexporter/prometheus.go
=> Set capabilities for all core exporters, remove unnecessary funcs

exporter/exporterhelper/resource_to_label.go, internal/otlptext/databuffer.go, testbed/testbed/validator.go, translator/internaldata/resource_to_oc.go, translator/internaldata/resource_to_oc_test.go, translator/internaldata/traces_to_oc.go, translator/trace/jaeger/traces_to_jaegerproto.go, translator/trace/protospan_translation.go, translator/trace/protospan_translation_test.go, translator/trace/zipkin/traces_to_zipkinv2.go
=> Remove jsonlike argument from AttributeValueToString, always false (contrib as well)

exporter/fileexporter/config.go, exporter/fileexporter/config_test.go, exporter/fileexporter/factory.go, exporter/fileexporter/factory_test.go, exporter/fileexporter/file_exporter.go, exporter/fileexporter/file_exporter_test.go, service/defaultcomponents/default_exporters_test.go
=> Change fileexporter to use the new SharedComponents because of the file

receiver/opencensusreceiver/factory.go, receiver/opencensusreceiver/opencensus.go
=> Use sharedcomponent package helper for OC receiver

translator/trace/protospan_translation.go, translator/trace/zipkin/attributes.go, translator/trace/zipkin/traces_to_zipkinv2.go, translator/trace/zipkin/zipkinv2_to_traces.go
=> Remove public constant TagServiceNameSource, only zipkin needs it

component/host.go
=> Update component.Host comments

internal/model/translator/decoder.go, internal/model/translator/encoder.go
=> Update Encoder/Decoder funcs name to use Encode/Decode

.circleci/config.yml
=> Remove unittest job from circleCI, runs on Github Actions

.circleci/config.yml
=> Revert machine type to ubuntu 16.04 to pass deb package test

config/internal/configsource/manager.go, exporter/otlphttpexporter/README.md, extension/README.md, extension/healthcheckextension/README.md, processor/memorylimiter/internal/cgroups/cgroup.go, processor/memorylimiter/internal/cgroups/cgroup_test.go, processor/memorylimiter/internal/cgroups/cgroups.go, processor/memorylimiter/internal/cgroups/cgroups_test.go, processor/memorylimiter/internal/cgroups/doc.go, processor/memorylimiter/internal/cgroups/errors.go, processor/memorylimiter/internal/cgroups/mountpoint.go, processor/memorylimiter/internal/cgroups/mountpoint_test.go, processor/memorylimiter/internal/cgroups/subsys.go, processor/memorylimiter/internal/cgroups/subsys_test.go, processor/memorylimiter/internal/cgroups/util_test.go
=> Fix duplicate "the" usages

translator/internaldata/metrics_to_oc.go, translator/internaldata/metrics_to_oc_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/3266
=> Fix oc to pdata translation for sum non-monotonic cumulative

testbed/tests/e2e_test.go
=> Fix error in TestBallast <Elements should be the same type>

CHANGELOG.md, config/configgrpc/configgrpc_test.go, testutil/testutil.go
=> Remove unnecessary public func testutil.TempSocketName

internal/otlp/json_decoder.go, internal/otlp/json_encoder.go
=> Rename internal/otlp files, avoid duplicate initialization

internal/model/marshaler.go, internal/model/marshaler_test.go, internal/model/unmarshal.go, internal/model/unmarshal_test.go
=> Change Marshaler/Unmarshaler to be interfaces

.github/CODEOWNERS
=> Add interested folks in Prom to codeowners, so they get notified about reviews in Prom

translator/trace/jaeger/jaegerproto_to_traces_test.go, translator/trace/jaeger/jaegerthrift_to_traces_test.go, translator/trace/jaeger/traces_to_jaegerproto_test.go
=> Rename TraceData to Traces in tests

exporter/jaegerexporter/exporter.go, exporter/kafkaexporter/factory.go, exporter/kafkaexporter/kafka_exporter.go, exporter/kafkaexporter/kafka_exporter_test.go, exporter/loggingexporter/logging_exporter.go, exporter/opencensusexporter/factory.go, exporter/opencensusexporter/opencensus.go, exporter/otlpexporter/factory.go, exporter/otlpexporter/otlp.go, exporter/otlphttpexporter/factory.go, exporter/otlphttpexporter/otlp.go, exporter/zipkinexporter/factory.go, exporter/zipkinexporter/zipkin.go
=> Rename internal funcs push*Data to push*

exporter/opencensusexporter/factory.go, exporter/opencensusexporter/factory_test.go, exporter/opencensusexporter/opencensus.go
Description:
Updated OpenCensus for upcoming client auth extension changes
#3287 #3282
Testing:
Unit tests
Documentation:
Unit tests
cc: @gramidt @bogdandrutu @jpkrohling
=> Refactored OpenCensus exporter to move connection into start for upcoming Auth changes.

website_docs/_index.md, website_docs/getting-started.md
cc @tigrannajaryan, re-created this PR after the rebase gone awry.
=> Sync docs changes between website and repo

internal/model/marshaler.go, internal/model/marshaler_test.go, internal/model/mocks_test.go, internal/model/unmarshal.go, internal/model/unmarshal_test.go
=> Add Marshaler/Unmarshaler interfaces for Logs and Metrics

README.md
=> Add punya as triager

internal/goldendataset/generator_commons.go, internal/goldendataset/pict_tracing_input_defs.go, internal/goldendataset/resource_generator.go, internal/goldendataset/resource_generator_test.go, internal/goldendataset/span_generator.go, internal/goldendataset/span_generator_test.go, internal/goldendataset/testdata/pict_input_spans.txt, internal/goldendataset/testdata/pict_input_traces.txt, internal/goldendataset/traces_generator.go, translator/internaldata/resource_to_oc_test.go
Fixes couple of bugs from PR#3322, see comments in that PR.
=> Fix usage of CopyTo/Append by passing the destination to the function

exporter/fileexporter/file_exporter.go, exporter/fileexporter/file_exporter_test.go, internal/model/unmarshal.go, internal/otlp/from_translator.go, internal/otlp/json_decoder.go, internal/otlp/json_encoder.go, internal/otlp/marshaler.go, internal/otlp/to_translator.go, internal/otlp/unmarshaler.go
=> Convert fileexporter to not depend on InternalRep

testbed/testbed/data_providers.go, testbed/tests/trace_test.go
=> Remove unnecessary public API in testbed

translator/trace/jaeger/constants.go
=> Samll error message fix, remove reference to OC

testbed/testbed/data_providers.go, testbed/testbed/data_providers_test.go, testbed/testbed/load_generator.go
=> Remove batch counter from the testbed DataProvider, not used

testbed/testbed/data_providers.go, testbed/testbed/data_providers_test.go, testbed/testbed/validator.go
=> Hide testbed DataProvider implementation structs

receiver/prometheusreceiver/internal/metricsbuilder.go, receiver/prometheusreceiver/internal/metricsbuilder_test.go
As of Prometheus 2.16.0 (released on 2020-02-13), datapoints with
duplicate label keys MUST be rejected and the Prometheus RemoteWrite
exporter tests were failing, but that was a red herring as the
real issue was really in the receiver.
Fixes https://github.com/open-telemetry/wg-prometheus/issues/44
Fixes #3407
=> receiver/prometheus: reject datapoints with duplicate label keys

.github/workflows/build-and-test.yml, Makefile
=> Avoid compiling in parallel same time without that

config/configgrpc/configgrpc_test.go
=> Remove usage of internal proto in configgrpc tests

exporter/otlphttpexporter/otlp.go
=> Use the new Marshaler in the OTLP HTTP exporter

testbed/testbed/receivers.go, testbed/testbed/senders.go
=> Remove unnecessary public structs from testbed

config/configgrpc/configgrpc_test.go
=> Fix build due to a race condition in merging PRs

internal/model/decoder.go, internal/model/encoder.go, internal/model/from_translator.go, internal/model/marshaler.go, internal/model/to_translator.go, internal/model/unmarshal.go
=> Add comments to translation interfaces, clarify on error return value cannot be used

testbed/correctness/traces/correctness_test.go, testbed/testbed/options.go, testbed/testbed/test_case.go, testbed/tests/e2e_test.go, testbed/tests/metric_test.go, testbed/tests/scenarios.go, testbed/tests/trace_test.go
=> Small cleanups in testbed

consumer/simple/metrics.go, consumer/simple/metrics_test.go
=> Remove unused from consumer/simple

receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go
=> Simplfy process scraper logic

internal/otlptext/logs.go, internal/otlptext/logs_test.go, internal/otlptext/metrics.go, internal/otlptext/metrics_test.go, internal/otlptext/traces.go, internal/otlptext/traces_test.go
=> Small nits in otlptext

config/configgrpc/configgrpc_test.go, exporter/otlpexporter/otlp.go, exporter/otlpexporter/otlp_test.go, model/otlpgrpc/logs.go, model/otlpgrpc/metrics.go, model/otlpgrpc/traces.go, receiver/otlpreceiver/internal/logs/otlp.go, receiver/otlpreceiver/internal/logs/otlp_test.go, receiver/otlpreceiver/internal/metrics/otlp.go, receiver/otlpreceiver/internal/metrics/otlp_test.go, receiver/otlpreceiver/internal/trace/otlp.go, receiver/otlpreceiver/internal/trace/otlp_test.go, receiver/otlpreceiver/otlp.go, receiver/otlpreceiver/otlp_test.go, receiver/otlpreceiver/otlphttp.go
=> Move internal/pdatagrpc to model/otlpgrpc

receiver/jaegerreceiver/trace_receiver.go
=> Create http Server via Config, enable cors and decompression

model/pdata/traces.go, translator/internaldata/oc_to_traces_test.go
=> Remove usage of internal/data in OpenCensus translator

Makefile
=> Update otel/build-protobuf used to build protobufs, no changes

model/pdata/common_test.go
=> Remove usage of deprecated append in pdata/common_test

translator/trace/jaeger/jaegerproto_to_traces.go
=> Remove usage of deprecated append in translator/jaeger

cmd/pdatagen/internal/base_slices.go, model/pdata/generated_common.go, model/pdata/generated_common_test.go, model/pdata/generated_log.go, model/pdata/generated_log_test.go, model/pdata/generated_metrics.go, model/pdata/generated_metrics_test.go, model/pdata/generated_trace.go, model/pdata/generated_trace_test.go, translator/trace/jaeger/jaegerproto_to_traces.go
=> Remove deprecated Append func from generated slices 

translator/trace/zipkinv2/to_translator.go
=> Copy internal data code in zipkinv1, allow pdata to split

obsreport/obsreport_receiver.go, obsreport/obsreport_test.go, obsreport/obsreporttest/obsreporttest_test.go, receiver/jaegerreceiver/trace_receiver.go, receiver/kafkareceiver/kafka_receiver.go, receiver/zipkinreceiver/trace_receiver.go
This is to underdastand if two separate calls are needed.
=> Try to match ReceiverContext with StartOp

obsreport/obsreport_receiver.go, obsreport/obsreport_test.go, receiver/opencensusreceiver/internal/ocmetrics/opencensus.go, receiver/opencensusreceiver/internal/octrace/opencensus.go
=> Move LongLivedCtx as option to constructor settings in obsreport.Receiver

exporter/exporterhelper/metrics.go, exporter/otlpexporter/otlp_test.go, internal/goldendataset/metrics_gen_test.go, model/pdata/metrics.go, model/pdata/metrics_test.go, processor/batchprocessor/batch_processor.go, processor/batchprocessor/splitmetrics.go, processor/memorylimiter/memorylimiter.go, receiver/otlpreceiver/internal/metrics/otlp.go, receiver/prometheusreceiver/internal/transaction.go, receiver/scraperhelper/scrapercontroller.go, receiver/scraperhelper/scrapercontroller_test.go, testbed/testbed/data_providers.go, testbed/testbed/mock_backend.go
=> Refactor MetricAndDataPointCount to DataPointCount

obsreport/obsreport_receiver.go
=> Precalculate span name prefix in obstreport.Receiver, same as Exporter

component/componenttest/shutdown_verifier.go, consumer/consumertest/sink.go, consumer/consumertest/sink_test.go, exporter/otlphttpexporter/otlp_test.go, internal/testdata/trace.go, processor/batchprocessor/batch_processor_test.go, processor/probabilisticsamplerprocessor/probabilisticsampler_test.go, receiver/jaegerreceiver/jaeger_agent_test.go, receiver/otlpreceiver/otlp_test.go, service/internal/fanoutconsumer/cloningconsumer_test.go, service/internal/fanoutconsumer/consumer_test.go, testbed/testbed/mock_backend.go
=> Change SpansCount to SpanCount everywhere

consumer/consumertest/sink.go, consumer/consumertest/sink_test.go, exporter/otlphttpexporter/otlp_test.go, processor/batchprocessor/batch_processor_test.go, service/internal/fanoutconsumer/cloningconsumer_test.go, service/internal/fanoutconsumer/consumer_test.go
=> Change LogRecordsCount to LogRecordCount everywhere

consumer/consumertest/sink.go, consumer/consumertest/sink_test.go, exporter/otlphttpexporter/otlp_test.go, processor/batchprocessor/batch_processor_test.go, receiver/scraperhelper/scrapercontroller_test.go, service/internal/fanoutconsumer/cloningconsumer_test.go, service/internal/fanoutconsumer/consumer_test.go
=> Change MetricsSink to count data points not metrics

receiver/kafkareceiver/kafka_receiver.go
=> Record the correct number of points not metrics in Kafka receiver

obsreport/obsreport_receiver.go, obsreport/obsreport_test.go, obsreport/obsreporttest/obsreporttest_test.go, receiver/jaegerreceiver/trace_receiver.go, receiver/kafkareceiver/kafka_receiver.go, receiver/opencensusreceiver/internal/ocmetrics/opencensus.go, receiver/opencensusreceiver/internal/octrace/opencensus.go, receiver/otlpreceiver/internal/logs/otlp.go, receiver/otlpreceiver/internal/metrics/otlp.go, receiver/otlpreceiver/internal/trace/otlp.go, receiver/prometheusreceiver/metrics_receiver.go, receiver/scraperhelper/scrapercontroller.go, receiver/zipkinreceiver/trace_receiver.go
=> Remove obsreport.ReceiverContext, embed in StartOp*

config/confighttp/confighttp.go, config/confighttp/confighttp_test.go, go.mod, go.sum, receiver/opencensusreceiver/opencensus_test.go
=> Bump github.com/rs/cors from 1.7.0 to 1.8.0

exporter/exporterhelper/queued_retry.go, exporter/exporterhelper/queued_retry_test.go
CC: @alanwest 
Fixing a bug - throttle errors are currently only recognized when they are the outermost error.
This PR ensures that embedded throttle errors are recognized in the retry handler for exporter helpers.
**Testing:**
A test which wraps a throttle error has been added.
=> Use errors.As to identify a throttle error.

service/collector.go, service/collector_test.go, service/settings.go, service/telemetry.go
=> Cleanup to remove the mentions of application

receiver/prometheusreceiver/README.md
Update Prometheus receiver's README to specifically mention Prometheus's scrape_config section.
NA
NA
The change only updates the documentation :)
=> Specifically mention scrape_config section

service/internal/builder/exporters_builder.go, service/internal/builder/extensions_builder.go, service/internal/builder/pipelines_builder.go, service/internal/builder/receivers_builder.go
=> Cleanups in service/internal/builder. Prepare adding Tracer to the Settings

model/pdata/common.go
**Documentation:** Fixes docs.
=> docs: fixes AttributeMap.Range docs.

config/configgrpc/configgrpc.go, config/confighttp/confighttp.go, go.mod, go.sum
=> Enable otel integration for http, enable propagation in grpc

Makefile
=> Update collector model as well in contrib-tests

model/pdata/common.go
* Fix code examples
* Clarify that AttributeValue is actually a mutable cell
#2488
None needed because this only affects docs.
=> Doc improvements

model/internal/otlp_wrapper.go, model/otlp/pb_unmarshaler.go, model/otlpgrpc/traces.go
=> Consolidate where compatibility changes are executed

model/pdata/metrics_test.go
=> Fix tests in pdata after changes in metrics compatibility

exporter/exporterhelper/metrics_test.go, internal/testdata/metric.go, translator/internaldata/metrics_to_oc_test.go, translator/internaldata/oc_testdata_test.go, translator/internaldata/oc_to_metrics_test.go
=> Small cleanups in testdata package, fix names, ensure all types

cmd/pdatagen/internal/metrics_structs.go, exporter/exporterhelper/resource_to_label.go, exporter/prometheusremotewriteexporter/exporter.go, exporter/prometheusremotewriteexporter/helper.go, internal/goldendataset/metrics_gen.go, internal/otlptext/databuffer.go, model/pdata/generated_metrics.go, model/pdata/generated_metrics_test.go, processor/batchprocessor/splitmetrics.go, receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go, receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_linux.go, receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_others.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others_linux.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_linux.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_others.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_windows.go, testbed/correctness/metrics/metric_diff.go, translator/internaldata/metrics_to_oc.go, translator/internaldata/oc_to_metrics.go
Changing references from DoubleDataPoint to NumberDataPoint.
=> Rename DoubleDataPoint to NumberDataPoint

receiver/kafkareceiver/README.md
The receiver supports metrics, traces, and logs via OTLP.
=> [receiver/kafka] Update README

config/exporter.go, config/extension.go, config/processor.go, config/receiver.go
=> Disallow users to implement configs directly, allows us to add more funcs

service/internal/builder/exporters_builder.go, service/internal/builder/exporters_builder_test.go, service/internal/builder/extensions_builder.go, service/internal/builder/pipelines_builder.go, service/internal/builder/pipelines_builder_test.go, service/internal/builder/receivers_builder.go, service/internal/builder/receivers_builder_test.go
=> Use ComponentID as identifier instead of config

extension/zpagesextension/config.go, extension/zpagesextension/factory.go, extension/zpagesextension/zpagesextension.go, extension/zpagesextension/zpagesextension_test.go
=> zpages: Move config validation from factory to Validate

cmd/pdatagen/internal/base_fields.go, model/pdata/generated_metrics.go, model/pdata/metrics.go
**Description:** Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/3699#discussion_r675185393
Will rebase on https://github.com/open-telemetry/opentelemetry-collector/pull/3699 is merged.
=> rename NumberDataPointType to MetricValueType

config/configgrpc/configgrpc.go
=> Remove unused public constant from configgrpc

receiver/opencensusreceiver/opencensus.go
=> Do not report fatal error when cmux.ErrServerClosed

config/configparser/parser.go, exporter/prometheusremotewriteexporter/exporter_test.go, receiver/zipkinreceiver/trace_receiver.go
=> Fix small typos for unmarshalls

exporter/prometheusexporter/accumulator.go, exporter/prometheusexporter/accumulator_test.go, exporter/prometheusexporter/collector.go, exporter/prometheusexporter/collector_test.go, exporter/prometheusexporter/prometheus_test.go
=> Convert prometheus exporter to new Number metrics

exporter/prometheusexporter/collector.go
=> Simple rename of private func in prometheus exporter

exporter/exporterhelper/resource_to_label_test.go, internal/testdata/metric.go, testbed/testbed/data_providers.go, translator/internaldata/metrics_to_oc.go, translator/internaldata/metrics_to_oc_test.go, translator/internaldata/oc_to_metrics.go, translator/internaldata/oc_to_metrics_test.go
=> Convert opencensus and testdata to new Number metrics

receiver/scraperhelper/scrapercontroller_test.go
=> Convert scraperhelper to new Number metrics

exporter/prometheusremotewriteexporter/exporter.go, exporter/prometheusremotewriteexporter/exporter_test.go, exporter/prometheusremotewriteexporter/helper.go, exporter/prometheusremotewriteexporter/testutil_test.go
=> Convert prometheusremotewriteexporter to new Number metrics

model/pdata/metrics_test.go
=> Remove usage of deprecated IntSum/IntGauge in pdata tests

internal/otlptext/databuffer.go
=> Remove usage of deprecated IntSum/IntGauge in otlptext

exporter/exporterhelper/resource_to_label.go, exporter/exporterhelper/resource_to_label_test.go
=> Convert resourcetolabel to new Number metrics

testutil/metricstestutil/metricsutil.go
=> Remove unused public func in metricsutil

model/otlp/pb_test.go, processor/filterprocessor/expr_test.go, processor/filterprocessor/filter_processor_test.go
=> Remove last usages of Int[Gauge|Sum] from tests

model/internal/otlp_wrapper.go, model/internal/otlp_wrappers_test.go
=> Convert temporality and monotonicity for deprecated sums

model/pdata/common.go, processor/processorhelper/attraction.go
**Description:** Fixing a typo in the documentation.
=> fix minor typo in documentation

model/pdata/common.go, model/pdata/common_test.go
**Description:** Adding support for Bytes attribute type.
**Link to tracking Issue:** Part of #3535 
This is built on top of https://github.com/open-telemetry/opentelemetry-collector/pull/3740.
=> adding support for Bytes attribute type 

.github/workflows/api-compatibility.yml
=> Run api compatibility on golang 1.16 

go.mod, go.sum
=> Update zpages to the released version

config/configloader/config.go, go.mod
=> Remove deprecated unmarshaler error, already removed functionality

service/collector.go
=> Small nit in collector implementation

obsreport/obsreport.go, obsreport/obsreport_processor.go
=> Remove unnecessary private function in obsreport

translator/trace/zipkinv2/json.go, translator/trace/zipkinv2/marshaler.go, translator/trace/zipkinv2/protobuf.go
=> Remove duplicate code in zipkinv2 marshaler

.github/workflows/stale-pr.yaml
No easy option to disable issues from stale, but good enough alternative.
Fixes: https://github.com/open-telemetry/opentelemetry-collector/issues/3757
=> Mark issues as stale after 2y and close in 1m

translator/trace/jaeger/jaegerproto_to_traces.go, translator/trace/jaeger/jaegerthrift_to_traces.go
=> Fix small bug in jaeger translation, could generate empty proto spans

service/parserprovider/setflag.go
This PR cuts out a few steps, including copying the map, calling IntfaceKeysToStrings, and merging the map with an empty map.
=> Small nit in setflag ParserProvider

receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/utils.go, receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper.go, receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper.go, receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go, receiver/hostmetricsreceiver/internal/scraper/pagingscraper/paging_scraper_others.go, receiver/hostmetricsreceiver/internal/scraper/pagingscraper/paging_scraper_windows.go, receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_unix.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_linux.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_windows.go, receiver/hostmetricsreceiver/internal/testutils.go
Updating `LabelsMap` to `Attributes` for hostmetrics receiver.
**Link to tracking Issue:** Part of #3535
=> receiver/hostmetrics: update labels to attributes

config/configunmarshaler/defaultunmarshaler.go
When changed to Koanf in https://github.com/open-telemetry/opentelemetry-collector/pull/3337 the Viper
bug (keys with nil values are ignored) that causes the workaround was fixed, so use the unmarshaled values.
=> Remove small hack in the DefaultUnmarshaler caused by viper bug.

receiver/hostmetricsreceiver/config.go, receiver/prometheusreceiver/config.go
=> Use Parser.ToStringMap instead of cast when possible

testbed/testbed/child_process_collector.go
=> Stream otelcol agent output directly to log file

receiver/jaegerreceiver/trace_receiver.go, receiver/otlpreceiver/internal/logs/otlp.go, receiver/otlpreceiver/internal/metrics/otlp.go, receiver/otlpreceiver/internal/trace/otlp.go, receiver/prometheusreceiver/internal/transaction.go
=> Remove unnecessary internal variables in the receivers

exporter/zipkinexporter/zipkin_test.go, receiver/zipkinreceiver/factory.go, receiver/zipkinreceiver/proto_parse_test.go, receiver/zipkinreceiver/trace_receiver.go, receiver/zipkinreceiver/trace_receiver_test.go
=> Avoid using internal zipkinreceiver implementation

testbed/testbed/data_providers.go
=> Update testbed perftest data provider to use attributes

receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/pagingscraper/paging_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_test.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go, receiver/hostmetricsreceiver/internal/testutils.go
=> Update hostmetrics receiver tests to reflect Labels->Attributes change

.github/workflows/codeql-analysis.yml, CHANGELOG.md, go.mod
=> Release v0.33.0, retract v0.32.0

service/collector_test.go
=> Fix skipped test on darwin in collector-test

cmd/mdatagen/metrics.tmpl, receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go
=> Remove FactoriesByName from generated metadata

model/pdata/logs.go, model/pdata/metrics.go, model/pdata/traces.go
=> Nit comments in pdata new Sizer interfaces

translator/trace/jaeger/jaegerproto_to_traces.go, translator/trace/jaeger/jaegerthrift_to_traces.go
=> Fix small nits in jaeger translator

CHANGELOG.md, receiver/prometheusreceiver/internal/otlp_metricfamily_test.go, translator/internaldata/metrics_to_oc.go, translator/trace/protospan_translation.go
=> Remove deprecated funcs from previous release

processor/filterprocessor/config.go, processor/filterprocessor/factory.go, processor/filterprocessor/filter_processor_logs.go, processor/filterprocessor/filter_processor_logs_test.go, processor/filterprocessor/testdata/config_logs.yaml
**Description:** Adding a feature to filter logs based on resource attributes to the filterprocessor
**Testing:** Added Unit tests for sanity checks
=> Add filtering for logs

service/testdata/otelcol-config.yaml
=> Remove usage of components that will be moved to contrib

README.md
=> Add @codeboten as approver, remove @jrcamp

Makefile
=> Fix contrib test action

.github/workflows/api-compatibility.yml, .github/workflows/build-and-test-windows.yaml, .github/workflows/build-and-test.yml, .github/workflows/codeql-analysis.yml, go.mod, go.sum
=> Bump deps that dependabot cannot update

.circleci/config.yml
=> Remove publish step from circleCI, will publish from release repo

CHANGELOG.md, go.mod
=> Release collector v0.34.0

model/pdata/common.go
=> Remove deprecated pdata.AttributeValueToString

internal/otlptext/databuffer.go, internal/otlptext/logs_test.go
**Description:** Adds trace context info to _LogRecord_ log.
=> Add trace context info to LogRecord log

model/pdata/common.go
=> Fix small nit in common pdata

internal/otlptext/databuffer.go, internal/otlptext/logs.go
=> Move logic to write LogRecord, consistent with trace

examples/k8s/otel-config.yaml
Fixing a bug - Fix the conflict caused by the same port name.
=> Fix the conflict caused by the same port name

exporter/exporterhelper/common_test.go, exporter/exporterhelper/logs_test.go, exporter/exporterhelper/metrics_test.go, exporter/exporterhelper/traces_test.go, go.mod, obsreport/obsreport_test.go, receiver/scraperhelper/scrapercontroller_test.go
=> Remove dependency on deprecated go.opentelemetry.io/otel/oteltest 

obsreport/obsreport_scraper.go, obsreport/obsreport_test.go, receiver/scraperhelper/scraper.go
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/3922
=> Remove obsreport.ScraperContext, embed into StartMetricsOp

CHANGELOG.md, go.mod
=> Prepare for v0.35.0 release

model/pdata/common.go
Fixes: https://github.com/open-telemetry/opentelemetry-collector/issues/3993
=> Remove deprecated pdata.AttributeMapToMap

CHANGELOG.md, service/collector.go, service/internal/builder/constants.go
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/3957
=> Remove ballast flag, already no-op

config/experimental/configsource/component.go, service/collector.go, service/collector_test.go, service/parserprovider/default_test.go, service/parserprovider/file.go, service/parserprovider/inmemory.go, service/parserprovider/provider.go, service/parserprovider/setflag.go, service/parserprovider/setflag_test.go
=> Change ParserProvider to become closer to ConfigSource

service/telemetry.go
=> Cleanup service/telemetry, small nits and error improvements.

obsreport/obsreport_exporter.go, obsreport/obsreport_receiver.go
=> Nit: fix some comments in obsreport package

model/otlp/json_test.go
=> Test the public constructor instead of the private one for otlp JSON

CHANGELOG.md
This PR adds a changelog entry for the changes made in #3956 
#3875
=> Add CHANGELOG for #3956, Move ValidateConfig from configcheck to configtest

CHANGELOG.md, go.mod
=> Prepare for v0.36.0 release

model/internal/data/protogen/metrics/v1/metrics.pb.go, model/internal/data/protogen/trace/v1/trace.pb.go
First part of supporting datapoint flags, updating the protos to 0.10.0.
**Link to tracking Issue:** Part of https://github.com/open-telemetry/opentelemetry-collector/issues/3987
=> update opentelemetry-proto to 0.10.0

config/configparser/parser.go, service/parserprovider/setflag.go
=> Replace Parser.MergeStringMap with more generic Parser.Merge

service/collector_test.go
=> Use in-memory provider instead of custom provider

CHANGELOG.md
Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/4064#issuecomment-924530919
=> record memorylimiter name change in changelog

config/configtls/README.md, examples/k8s/otel-config.yaml, exporter/otlpexporter/README.md, exporter/otlphttpexporter/README.md
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4092
=> Fix TLS config in readme

service/collector.go, service/collector_test.go, service/parserprovider/default.go, service/parserprovider/file.go, service/parserprovider/inmemory.go, service/parserprovider/merge.go, service/parserprovider/merge_test.go, service/parserprovider/properties.go, service/parserprovider/properties_test.go, service/parserprovider/provider.go, service/settings.go
=> Rename ParserProvider to MapProvider, preparation to move to config

exporter/exporterhelper/logs_test.go, exporter/exporterhelper/metrics_test.go, exporter/exporterhelper/traces_test.go, obsreport/obsreport_test.go, obsreport/obsreporttest/obsreporttest.go, obsreport/obsreporttest/obsreporttest_test.go, receiver/otlpreceiver/otlp_test.go, receiver/scraperhelper/scrapercontroller_test.go
First part of the work for https://github.com/open-telemetry/opentelemetry-collector/issues/4038, removing the dependency on testing.T from obsreporttest.
**Link to tracking Issue:** Part of https://github.com/open-telemetry/opentelemetry-collector/issues/4038
=> obsreporttest now returns an error

exporter/otlpexporter/README.md, exporter/otlphttpexporter/README.md, receiver/otlpreceiver/README.md
=> Fix warnings about metrics being alpha in OTLP

service/internal/telemetrylogs/logger.go
=> Remove support for logger configuration via flags, flags still kept this version

.github/workflows/build-and-test.yml, Makefile
=> Remove test instalation step, deprecated in golang

service/collector.go, service/collector_test.go, service/service.go, service/service_test.go, service/settings.go
=> Pass TelemetrySettings to Service instead of individual parts

CHANGELOG.md, component/build_info.go, component/componenttest/nop_exporter.go, component/componenttest/nop_extension.go, component/componenttest/nop_processor.go, component/componenttest/nop_receiver.go, service/collector_test.go, service/collector_windows_test.go, service/internal/builder/exporters_builder_test.go, service/internal/builder/extensions_builder_test.go, service/internal/builder/pipelines_builder_test.go, service/internal/builder/receivers_builder_test.go, service/service_test.go
=> Rename DefaultBuildInfo() to NewDefaultBuildInfo()

.github/workflows/build-and-test-windows.yaml, .github/workflows/build-and-test.yml, Makefile, Makefile.Common, internal/tools/go.mod, internal/tools/go.sum, internal/tools/tools.go
=> Cleanup github actions unittests

model/go.mod, model/go.sum
=> Bump google.golang.org/grpc from 1.40.0 to 1.41.0 in /model

cmd/otelcol/main.go, service/collector.go, service/collector_test.go, service/collector_windows.go, service/command.go, service/flags.go, service/parserprovider/default.go, service/parserprovider/default_test.go, service/parserprovider/expand_test.go, service/parserprovider/file.go, service/parserprovider/inmemory.go, service/parserprovider/properties.go, service/parserprovider/properties_test.go
=> Remove dependency between command line flags and providers

config/configtest/configtest.go
Issue caused by https://github.com/open-telemetry/opentelemetry-collector/pull/4098
=> Fix configtest LoadConfig, needs to keep expanding env-var

config/config_test.go, config/configtest/configtest_test.go, config/configunmarshaler/defaultunmarshaler_test.go, config/experimental/config/config.go, config/identifiable.go, exporter/exporterhelper/logs_test.go, exporter/exporterhelper/metrics_test.go, exporter/exporterhelper/traces_test.go, exporter/loggingexporter/config_test.go, exporter/otlpexporter/config_test.go, exporter/otlphttpexporter/config_test.go, extension/ballastextension/config_test.go, extension/zpagesextension/config_test.go, processor/batchprocessor/config_test.go, processor/memorylimiterprocessor/config_test.go, receiver/otlpreceiver/config_test.go, receiver/otlpreceiver/internal/logs/otlp_test.go, receiver/otlpreceiver/internal/metrics/otlp_test.go, receiver/otlpreceiver/internal/trace/otlp_test.go, receiver/otlpreceiver/otlp_test.go, service/internal/builder/pipelines_builder_test.go, service/internal/builder/receivers_builder_test.go
The other methods have been renamed, but this one looks like it was missed.
=> rename NewIDWithName -> NewComponentIDWithName

.codecov.yml
=> Try to update codecov config.

README.md
=> Add more details about collector status

CHANGELOG.md, cmd/pdatagen/internal/metrics_structs.go, model/pdata/generated_metrics.go, model/pdata/generated_metrics_test.go, model/pdata/metrics.go, model/pdata/metrics_test.go
Adding DataPointFlags to NumberDataPoint, HistogramDataPoint, SummaryDataPoint types. This is a follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/4045
**Link to tracking Issue:** Fixes #3987
Will rebase once #4045 is merged.
=> add DataPointFlags to Number/Histogram/Summary datapoints 

config/config.go, config/config_test.go, config/configtest/configtest_test.go, config/configunmarshaler/defaultunmarshaler.go, config/configunmarshaler/defaultunmarshaler_test.go, service/internal/builder/exporters_builder_test.go, service/internal/builder/pipelines_builder_test.go
=> Use ComponentID to identify Pipelines as well

service/internal/builder/exporters_builder.go, service/internal/builder/exporters_builder_test.go, service/internal/builder/pipelines_builder.go, service/internal/builder/pipelines_builder_test.go, service/internal/builder/receivers_builder_test.go
=> Fix small nits in service/internal/builder

cmd/builder/cmd/root.go, cmd/builder/go.mod, cmd/builder/header.txt, cmd/builder/internal/builder/config.go, cmd/builder/internal/builder/config_test.go, cmd/builder/internal/builder/main.go, cmd/builder/internal/scaffold/components.go, cmd/builder/internal/scaffold/gomod.go, cmd/builder/internal/scaffold/main.go, cmd/builder/main.go
=> Update copyright in builder to be consistent with collector

CHANGELOG.md, config/config.go, config/config_test.go, config/configtest/configtest_test.go, config/configunmarshaler/defaultunmarshaler.go, config/configunmarshaler/defaultunmarshaler_test.go, config/service.go, service/internal/builder/exporters_builder.go, service/internal/builder/exporters_builder_test.go, service/internal/builder/pipelines_builder.go, service/internal/builder/pipelines_builder_test.go, service/internal/builder/receivers_builder.go, service/zpages.go
=> Remove config.Pipeline.Name, already in the Piplines map key

processor/batchprocessor/splitlogs.go, processor/batchprocessor/splitmetrics.go, processor/batchprocessor/splitmetrics_test.go, processor/batchprocessor/splittraces.go
=> Fix small nits in the batchprocessor split logic

CHANGELOG.md, config/config_test.go, config/configtest/configtest_test.go, config/configunmarshaler/defaultunmarshaler.go, config/configunmarshaler/defaultunmarshaler_test.go, config/service.go, service/internal/builder/exporters_builder.go, service/internal/builder/exporters_builder_test.go, service/internal/builder/pipelines_builder.go, service/internal/builder/pipelines_builder_test.go, service/internal/builder/receivers_builder.go, service/internal/components/constants.go, service/zpages.go
=> Remove config.Pipeline.InputDataType, already in the Piplines map key

config/config.go, config/exporter.go, config/extension.go, config/processor.go
=> Fix small nits in config

exporter/otlpexporter/otlp.go
=> Remove indirection in otlpexporter, added when thought we can have grpc/http merged

exporter/otlpexporter/otlp.go
=> otlpexporter: simplify shouldRetry logic

extension/ballastextension/README.md
Fix broken link to the blog post
=> Fix broken link

model/pdata/spanid_test.go, model/pdata/timestamp.go, model/pdata/timestamp_test.go, model/pdata/traceid_test.go
=> Add tests for some String funcs in model/pdata

CHANGELOG.md, exporter/otlpexporter/otlp.go
See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc-response
=> Do not retry on codes that will never succeed

component/receiver.go
**Description:** Fixing a small typo :) 
**Documentation:**  NA
=> Fix minor typo

service/zpages.go
=> Remove usage of request Form, we always send params in URL query

config/configunmarshaler/defaultunmarshaler.go, receiver/otlpreceiver/config_test.go
=> Small nits in default config unmarshaler

service/internal/builder/pipelines_builder.go, service/internal/builder/receivers_builder.go
Users of the Pipeline should not know about internal details.
=> Built pipeline ensure correct Capabilities

service/internal/zpages/templates.go
=> Remove debug println from zpages template

cmd/builder/internal/builder/config.go, cmd/builder/internal/builder/config_test.go, cmd/builder/test/nocore.builder.yaml, cmd/builder/test/replaces.builder.yaml
=> Upgrade builder to use collector v0.38.0

service/command_test.go
Adding some basic coverage tests to the service module.
=> add tests in the service module

cmd/builder/internal/builder/config.go, cmd/builder/internal/builder/config_test.go, cmd/builder/internal/builder/main.go, cmd/builder/internal/builder/main_test.go
Adding builder tests for config and main.
**Link to tracking Issue:** Fixes #4318
=> [tests] adding tests for builder

examples/k8s/otel-config.yaml
Update example configuration to reflect current usage of memory ballast
=> Update memory ballast usage

obsreport/obsreporttest/obsreporttest.go, obsreport/obsreporttest/obsreporttest_test.go
=> obsreporttest: Improve tests, check for all possible errors always

service/collector.go, service/collector_test.go, service/config_watcher.go, service/config_watcher_test.go, service/testdata/otelcol-invalid.yaml
* Fix race condition in Collector where multiple goroutines were updating the Collector.service;
* Correctly close the RetrievedWatchable values;
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4236
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/3489
=> Extract configuration wathcing is a separate struct

model/pdata/metrics.go, receiver/scrapererror/doc.go
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>
Fix two golint issues.
=> Fix some golint issues

model/pdata/metrics.go, model/pdata/metrics_test.go
=> Plugin ExponentialHistogram to Metric, add MetricType

internal/testdata/metric.go, processor/batchprocessor/splitmetrics.go, processor/batchprocessor/splitmetrics_test.go
=> Update batch processor to handle ExponentialHistogram

model/pdata/metrics.go, model/pdata/metrics_test.go
=> Improve MetricValueType usage and add String()

cmd/builder/internal/builder/main_test.go
=> [cmd/builder] Assert if config not valid

cmd/builder/internal/command.go, cmd/builder/internal/version.go, cmd/builder/main.go
=> Nit: remove more global state from the Builder

.codecov.yml
=> Update codecov to reflect latest changes

cmd/builder/README.md
Signed-off-by: Fangyi Zhou <me@fangyi.io>
_Please delete paragraphs that you did not use before …
=> cmd/builder: Fix a minor inconsistency in README
