- README.md
- docs/VISION.md
I have been recently thinking about what should be the long-term vision for OpenTelemetry Agent/Collector. I believe it is important to have a clearly articulated set of high-level goals and guiding principles for the product that we work on. I took a first stab at it and would highly appreciate feedback on it and whether you think it is aligned with the goals of the OpenTelemetry community.
This has been already circulated internally at Omnition and also in Gitter channel https://gitter.im/open-telemetry/community
> WIP: Add long-term vision doc and basic info to README

- docs/migrating-from-opencensus.md
Related to issues:
https://github.com/open-telemetry/opentelemetry-service/issues/12
https://github.com/open-telemetry/opentelemetry-service/issues/13
> Add Action Plan for Bootstraping from OpenCensus

- .github/CODEOWNERS
- .github/wip.yml
- CODEOWNERS
- docs/VISION.md
- docs/migrating-from-opencensus.md
After mirror of OC Service repo, re-add new files to get back to
consistent state.
> Re-add CODEOWNERS and docs

- .travis.yml
- CONTRIBUTING.md
- DESIGN.md
- Makefile
- PERFORMANCE.MD
- README.md
This is the highest priority as part of the migration. Future PRs will
handle the complete rename.
> Update initial docs to OpenTelemetry

- Makefile
- cmd/occollector/app/builder/exporters_builder.go
- cmd/occollector/app/builder/pipelines_builder.go
- cmd/occollector/app/builder/receivers_builder.go
- cmd/occollector/app/builder/receivers_builder_test.go
- cmd/occollector/app/builder/testdata/pipelines_builder.yaml
- cmd/occollector/app/collector/collector.go
- internal/configmodels/configmodels.go
- internal/configv2/configv2.go
- internal/configv2/configv2_test.go
- internal/configv2/example_factories.go
- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/opencensusreceiver/config_test.go
- receiver/opencensusreceiver/factory.go
- Build receivers and plug them into pipelines.
- Added tests to verify that single pipeline and multiple pipeline (fan out)
per receiver work correctly.
- Disable -v flag in go test to reduce unnecessary noise in output, we have
too many tests to use -v flag. Errors are still properly printed. This makes
finding the cause of test failures easier.
- Add logging to various application startup steps.
- Changed logging from %q to %s in multiple places to make it more human readable
when output in json format.
Testing done:
1. make && all unit tests pass.
2. make otelsvc and produce otelsvc_linux executable.
3. Manually verify that otelsvc_linux runs and correctly forwards trace data
received via jaeger receiver and exported via opencensus exporter.
This is the first successful run of unified …
> Build receivers based on new configuration

- Makefile
> fix docker otelsvc build.

- receiver/prometheusreceiver/config.go
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/factory.go
- receiver/prometheusreceiver/factory_test.go
- receiver/prometheusreceiver/testdata/config.yaml
This is part of remaining migration to new configuration format.
Github issue: https://github.com/open-telemetry/opentelemetry-service/issues/33
Testing done: make
> Add factory and new-style config for Prometheus receiver

- go.mod
- go.sum
- receiver/vmmetricsreceiver/vm_metrics_collector.go
> add resource to vmreceiver.

- Makefile
- demos/trace/README.md
We only need the unified docker-otelsvc. Having docker-collector in
the makefile is misleading and unnecessary.
Issue: https://github.com/open-telemetry/opentelemetry-service/issues/48
> Remove docker-collector makefile target

- cmd/occollector/app/builder/builder.go
- cmd/occollector/app/collector/collector.go
- cmd/occollector/app/collector/collector_test.go
- cmd/occollector/app/collector/telemetry.go
- go.mod
- go.sum
- internal/collector/telemetry/process_telemetry.go
This change add an optional memory ballast to help with ease GC pressure
in high thoughput scenarios
- Added new CLI flag called `--mem-ballast-size-mib` which represents
the size of memory ballast to use in MiB. Omitting the value or setting
it to zero does not set the ballast.
- Updated process telemetry code to account for the ballast and report
memory usage statistics after subtracting the ballast size. I'm not sure
if this makes sense in every scenario. If not, we can add another flag
to disable the behaviour. Another option is to add one more metric that
just exports the memory ballast size as a static number and then let
metric consumers to adjust the numbers.
https://blog.twitch.tv/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap-26c2462549a2 …
> Introduce optional memory ballast

- cmd/occollector/app/builder/pipelines_builder.go
- cmd/occollector/app/collector/testdata/otelsvc-config.yaml
- internal/collector/processor/nodebatcher/config.go
- internal/collector/processor/nodebatcher/config_test.go
- internal/collector/processor/nodebatcher/factory.go
- internal/collector/processor/nodebatcher/factory_test.go
- internal/collector/processor/nodebatcher/testdata/config.yaml
- internal/collector/processor/queued/factory_test.go
- internal/configmodels/configmodels.go
- internal/configv2/configv2.go
- internal/configv2/configv2_test.go
- internal/configv2/example_factories.go
- internal/factories/factories.go
- internal/factories/factories_test.go
- processor/addattributesprocessor/config_test.go
- processor/addattributesprocessor/factory.go
This is part of remaining migration to new configuration format.
- Added zap.Logger to ProcessorFactory functions because it is
needed by this processor (and can be used if needed in other processors
in the future).
- Added Name/SetName to Processor interface because it is
needed by this processor (this now also makes Processor uniform with
Receiver and Exporter interfaces).
Github issue: https://github.com/open-telemetry/opentelemetry-service/issues/52
Testing done: make
> Add factory and new-style config for Batch processor

- .travis.yml
This change will cache Go mod dependencies on Travis CI and speed up
builds by a couple of minutes
> Cache dependencies on Travis CI

- cmd/occollector/app/collector/collector_test.go
- go.mod
- go.sum
This should make the test work on the following platforms:
- FreeBSD i386/amd64/arm
- Linux i386/amd64/arm
- Windows/amd64
- Darwin i386/amd64
- OpenBSD amd64
> Fixed ballast test cases by using  cross-platform lib

- testbed/testbed/test_bed.go
- testbed/tests/.gitignore
- testbed/tests/local.yaml
Leveraging GOOS to make the tests run seamless in multiple OSes. There will be separate work to establish different baselines for different platforms, this first change is just to make it runs without manual adaptations on multiple OSes.
> Make perf testbed OS agnostic

- testbed/testbed/load_generator.go
- testbed/testbed/mock_backend_test.go
- testbed/testbed/test_case.go
- testbed/tests/perf_test.go
- Introduce TestCase.WaitFor function that waits until specified condition
becomes true.
- Make performance tests faster and reliable by waiting for spans to be received
using WaitFor instead of fixed time period.
- Introduce TestCase.Sleep function to reduce boilerplate in test cases.
> Cleanup E2E tests

- testbed/testbed/child_process.go
- testbed/testbed/test_case.go
There was a data race between GetResourceConsumption and watchResourceConsumption,
one was setting resourceSpec, the other was reading.
Now setting of resourceSpec is done before the resource motoring is started and
both functions only read it so there is no more data race.
Issue: https://github.com/open-telemetry/opentelemetry-service/issues/81
> Fix data race in childProcess

- cmd/occollector/app/builder/exporters_builder.go
- cmd/occollector/app/builder/receivers_builder.go
- configv2/configv2.go
- configv2/example_factories.go
- exporter/opencensusexporter/factory.go
- exporter/opencensusexporter/factory_test.go
- exporter/opencensusexporter/opencensusexporter_test.go
- factories/factories.go
- factories/factories_test.go
- internal/collector/processor/nodebatcher/factory.go
- internal/collector/processor/queued/factory.go
- models/commonerrors.go
- processor/addattributesprocessor/factory.go
- receiver/factories_test.go
- receiver/factory.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/opencensusreceiver/config_test.go
- receiver/opencensusreceiver/factory.go
- receiver/opencensusreceiver/factory_test.go
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/factory.go
- receiver/prometheusreceiver/factory_test.go
- receiver/zipkinreceiver/config_test.go
- receiver/zipkinreceiver/factory.go
- receiver/zipkinreceiver/factory_test.go
This is part 1 of 3 of the refactoring plan to eliminate factories.go
and move the content to corresponding packages (receiver, exporter, processor).
> Move ReceiverFactory to "receiver" package.

- cmd/occollector/app/collector/collector_test.go
Added a Sleep to work around a data race bug in Jaeger
(https://github.com/jaegertracing/jaeger/pull/1625) caused
by stopping immediately after starting.
Without this Sleep we were observing this bug on our side:
https://github.com/open-telemetry/opentelemetry-service/issues/43
The Sleep ensures that Jaeger Start() is fully completed before
we call Jaeger Stop().
TODO: Jaeger bug is already fixed, remove this once we update Jaeger
to latest version.
Testing done: make test
> Add workaround for data race in TestApplication_StartUnified

- exporter/zipkinexporter/zipkin.go
- exporter/zipkinexporter/zipkin_test.go
These 2 functions had error on their return but never returned error. This made confuse on caller sites since it gave the impression that spans could be dropped without proper observability.
> Refactor 2 private functions in zipkin exporters

- receiver/vmmetricsreceiver/factory.go
- receiver/vmmetricsreceiver/factory_test.go
Skip the test if not on linux since currently VM Metrics receiver only supports Linux.
This can be done in other ways (e.g.: rename file, build directive, etc) but I think it is better to keep building it but only skip the failing test on other platforms.
Fixes #104
> Skip TestCreateReceiver for VM Metrics receiver if not on linux

- config/configmodels/configmodels.go
- exporter/zipkinexporter/zipkin_test.go
- observability/observability.go
- observability/observability_test.go
- observability/observabilitytest/observabilitytest.go
- receiver/zipkinreceiver/config_test.go
- receiver/zipkinreceiver/factory.go
- receiver/zipkinreceiver/factory_test.go
- receiver/zipkinreceiver/testdata/config.yaml
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
This change makes the Zipkin receiver respond to received data according to the host ingestion status.
This is part of https://github.com/open-telemetry/opentelemetry-service/issues/76
> Change Zipkin receiver behavior according to host ingestion status

- defaults/defaults.go
- defaults/defaults_test.go
- processor/attributekeyprocessor/config_test.go
- processor/attributekeyprocessor/factory.go
- processor/attributekeyprocessor/factory_test.go
The original PR was made before the change in model of factory registration. This change moves it to the current factory registration.
> Update attributekeyprocessor to current factory registration

- receiver/vmmetricsreceiver/.nocover
- receiver/vmmetricsreceiver/factory.go
- receiver/vmmetricsreceiver/metrics_receiver.go
Receiver will be loaded through config.go instead of viper.
> Clean up stale code in receiver/vmmetrics

- Makefile
Missed the linux path on the copy step
> Fix docker-otelsvc build

- receiver/opencensusreceiver/config.go
- receiver/opencensusreceiver/config_test.go
- receiver/opencensusreceiver/factory.go
- receiver/opencensusreceiver/factory_test.go
- receiver/opencensusreceiver/opencensus.go
- receiver/opencensusreceiver/opencensus_test.go
- receiver/opencensusreceiver/testdata/config.yaml
- testbed/go.sum
- testbed/testbed/mock_backend.go
Add OC receiver config settings in the new format. This brings the settings that were available in the old format to the new config format. No new settings were added or handled at this point.
> Add OC receiver config settings

- receiver/opencensusreceiver/ocmetrics/opencensus.go
When the grpc-gateway was added to this receiver/opencensus
Trace receiver in OpenCensus-Service PR
https://github.com/census-instrumentation/opencensus-service/pull/270,
we recognized that browsers and other sources that send JSON
in one burst won't stream so would encounter an io.EOF.
This PR makes the metrics receiver replicate that behavior.
Fixes #178
> receiver/opencensus/ocmetrics: ignore io.EOF on JSON upload

- examples/demotrace/otel-agent-config.yaml
- testbed/testbed/options.go
- testbed/testbed/test_case.go
- testbed/tests/perf_test.go
- testbed/tests/testdata/add-attributes-config.yaml
- testbed/tests/testdata/agent-config.yaml
The typical usage is expected to have both the batcher and the queued-retry so changing the perf tests to use the queued-retry. The use of the batcher needs a more careful change since it introduces a delay on the arrival of spans that breaks the basic tests.
Also adding a test with addattributesprocessor that requires a different configuration file, the intention here is that adding this processor should not cause major difference between not having it enabled.
> Add queued-retry and add-attributes to perf tests

- Makefile
- go.mod
- go.sum
- internal/tools.go
According to our discussion #153 , I have added the addlicense to make file.
1- It will add license automatically if not found the year "2019" with flag -y and the auther "OpenTelemetry Authors" with flag -c.
2- add license will be part of "make" default goal.
> Check license existence, add license otherwise

- Makefile
The tool was added as a dependency and my local build started failing because of the missing `addlicense` command. This should make it easy to fix for others by running `make install-tools`
> This installs addlicense tool with `make install-tools` command

- Makefile
It needs GO111MODULE env var and the recently added addlicense tool.
/cc @ccaraman
> Fix install-tools target

- service/service.go
Currently if flag "--config" is not specified, an error will be returned saying "Cannot load configuration: must have at least one pipeline", which is a bit confusing.
> Fail fast when config is not set

- exporter/README.md
Remove stale content, put in place a simple skeleton, and put information for the Zipkin exporter.
This is a follow up to a [comment](https://github.com/open-telemetry/opentelemetry-service/pull/207#pullrequestreview-268590954) on PR #207
> Update exporters README

- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/testdata/config.yaml
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
- translator/trace/jaeger/jaegerproto_to_protospan.go
- translator/trace/jaeger/jaegerproto_to_protospan_test.go
- translator/trace/jaeger/status_code.go
Closes #127 by implementing a gRPC receiver based on the protobuf specification from Jaeger's own repository.
> Added Jaeger gRPC receiver

- processor/nodebatcher/node_batcher.go
MD5 is insecure cryptographic hash functions, and are therefore unsuitable for security applications.
> Use sha256 instead of md5 in node batcher processor

- Makefile
- exporter/zipkinexporter/zipkin.go
- go.mod
- go.sum
- internal/tools.go
- receiver/prometheusreceiver/internal/metadata.go
- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
- receiver/prometheusreceiver/internal/ocastore.go
- receiver/prometheusreceiver/internal/ocastore_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/internal/transaction_test.go
- service/builder/builder.go
> Add goimports check and fix import order for all files

- README.md
- docs/observability.md
- docs/vision.md
This is a guidance document that developers can consult with when
working on improving own observability of OpenTelemetry Service.
> Add Observability Vision document

- defaults/defaults.go
- defaults/defaults_test.go
- examples/demotrace/otel-collector-config.yaml
- exporter/README.md
- exporter/zipkinexporter/config.go
- exporter/zipkinexporter/config_test.go
- exporter/zipkinexporter/factory.go
- exporter/zipkinexporter/factory_test.go
- exporter/zipkinexporter/testdata/config.yaml
- exporter/zipkinexporter/zipkin.go
Add the Zipkin exporter configuration factory using the new configuration format. This does not bring many of the settings from the old configuration since they won't be used. In a sub-sequent PR the code of the exporter itself will be changed.
Closes #34
> Add Zipkin exporter factory

- exporter/exporterhelper/constants.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
The paramater was named exportFormat but it actually used as the exporter name.
> Rename exporterhelp parameter

- config/config.go
- config/config_test.go
- config/testdata/missing-enabled-exporters.yaml
Note: From reading the code, there is no expectation on if a processor should be specified. There is a test case to ensure trace pipelines have a processor. 
The config now returns an error if there are no exporters specified or if there are no enabled exporters. 
Update the logic for checking if all receivers are enabled to the ValidateReceiver method just like the logic is added in ValidateExporters.
> Add functionality for ensuring enable exporters

- exporter/exporter.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/exportertest/nop_exporter.go
- exporter/exportertest/nop_exporter_test.go
- exporter/exportertest/sink_exporter.go
- exporter/exportertest/sink_exporter_test.go
- exporter/loggingexporter/factory.go
- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
- receiver/end_to_end_test.go
Continuing the refactor that started from exporterhelper in proper naming the related fileds and methods.
Continuation of #220 (see [comment](https://github.com/open-telemetry/opentelemetry-service/pull/220#discussion_r309932153))
> Refactor (Trace/Metrics)ExportFormat to ExporterName

- config/configmodels/configmodels.go
- exporter/zipkinexporter/zipkin_test.go
- observability/observability.go
- observability/observability_test.go
- observability/observabilitytest/observabilitytest.go
- receiver/README.md
- receiver/opencensusreceiver/config_test.go
- receiver/opencensusreceiver/factory.go
- receiver/opencensusreceiver/testdata/config.yaml
- receiver/receiver.go
- receiver/receivertest/mock_host.go
- receiver/receivertest/mock_host_test.go
- receiver/zipkinreceiver/config_test.go
- receiver/zipkinreceiver/factory.go
- receiver/zipkinreceiver/factory_test.go
- receiver/zipkinreceiver/testdata/config.yaml
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
- service/service.go
- testbed/testbed/mock_backend.go
We paused on #76 until further design conversations, in order to avoid confusion with this incomplete feature let's remove it from the code base.
> Remove memory limiting changes

- defaults/defaults.go
- defaults/defaults_test.go
- internal/collector/sampling/policy.go
- processor/tailsampling/config.go
- processor/tailsampling/config_test.go
- processor/tailsampling/factory_test.go
- processor/tailsampling/processor.go
- processor/tailsampling/processor_test.go
- processor/tailsampling/testdata/tail_sampling_config.yaml
Fixes #146.
~~Note one additional change is now each tail sampling processor can only
accept one policy, because one processor can only have one next
consumer. If users need more than one policies they can define multiple
tail sampling processors in the config.~~
> Finish up configs for tail sampling policies

- service/builder/exporters_builder.go
- service/builder/exporters_builder_test.go
- Exporters not used in any pipeline cause panic during shutting
down.
> Fix nil pointer panic whens stopping exporters

- oterr/constants.go
- processor/addattributesprocessor/addattributesprocessor.go
- processor/addattributesprocessor/factory_test.go
- processor/attributekeyprocessor/attributekeyprocessor.go
- processor/probabilisticsampler/probabilisticsampler.go
- processor/tailsampling/processor.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/opencensusreceiver/ocmetrics/opencensus.go
- receiver/opencensusreceiver/octrace/opencensus.go
- receiver/opencensusreceiver/opencensus.go
- receiver/prometheusreceiver/internal/ocastore.go
- receiver/vmmetricsreceiver/metrics_receiver.go
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
- receiver/zipkinreceiver/zipkinscribereceiver/scribe_receiver.go
- receiver/zipkinreceiver/zipkinscribereceiver/scribe_receiver_test.go
To avoid re-declaring the same error in multiple packages.
> Refactor common errors to oterr/constants.go

- receiver/README.md
- receiver/opencensusreceiver/config.go
- receiver/opencensusreceiver/config_test.go
- receiver/opencensusreceiver/testdata/config.yaml
> Passthrough CORS allowed origins

- receiver/README.md
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/testdata/config.yaml
- receiver/jaegerreceiver/trace_receiver.go
Updates the Jaeger receiver documentation in readme and config.yaml to detail default receiver, configure endpoints and disabling the entire receiver. 
Another round of documentation for Jaeger should be done when https://github.com/open-telemetry/opentelemetry-service/issues/158 is addressed.
> Jaeger Receiver Documentation

- CONTRIBUTING.md
This is an attempt to give better guidance to people trying to participate and contribute to OTelSvc.
The goal is to guide the efforts to issues that we already identified and triaged on the repo.
Side note: there is no clear distinction, at this point between, `help wanted` and `up-for-grabs` labels: `help wanted` is the standard for OC and OTel but `up-for-grabs` is also mentioned for OC and popular in other repos. Perhaps as we triage we could use `help wanted` to "harder" ones and `up-for-grabs` for the more straightforward ones.
> Improve contribution guidance

- docs/design.md
- exporter/zipkinexporter/zipkin_test.go
- processor/fanoutconnector.go
- processor/fanoutconnector_test.go
- service/builder/pipelines_builder.go
- service/builder/receivers_builder.go
This implements https://github.com/open-telemetry/opentelemetry-service/issues/283
> Rename fanoutprocessor to FanOutConnector

- consumer/consumererror/consumererror_test.go
- exporter/exportertest/nop_exporter_test.go
- exporter/exportertest/sink_exporter_test.go
> Use assert/require in test code of exporter

- processor/attributesprocessor/factory_test.go
- achieve 100% coverage for package attributesprocessor
> Add test cases to attributes processor

- exporter/exporterhelper/tracehelper.go
- exporter/zipkinexporter/zipkin.go
- observability/observability.go
- observability/observability_test.go
- observability/observabilitytest/observabilitytest_test.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/opencensusreceiver/octrace/opencensus.go
- receiver/zipkinreceiver/trace_receiver.go
Change all agent tag's TTL to TTLNoPropagation to not propagate them to the next agent/collector/backend.
This PR changes:
1) If the default views are used for receiver/exporter metrics the metric name.
2) The label keys for all the views that are using the receiver/exporter metrics.
> Update observability tags,views,measures names

- exporter/exporterhelper/constants.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/opencensusexporter/opencensus.go
- observability/observability.go
- observability/observability_test.go
- observability/observabilitytest/observabilitytest.go
- observability/observabilitytest/observabilitytest_test.go
By mistake I created this on top of https://github.com/open-telemetry/opentelemetry-service/pull/314. Will wait for that to merge first.
> Add support to record metrics for metricsexporter

- exporter/opencensusexporter/factory.go
- exporter/opencensusexporter/opencensus.go
Refactor OC Exporter creation to expose New(Trace/Metrics)Exporter to be use by forks that extend OC Exporter. 
There is no observable functional changes in this service. 
cc @owais @tigrannajaryan
> Expose public method to create OC Exporter

- receiver/prometheusreceiver/internal/metricfamily.go
- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/metrics_receiver.go
The pr instrument the Prometheus receiver using the observability metrics library. Adding this instrumentation will allow users to monitor service that rely on this receiver.
> Add observability instrumentation for Prometheus receiver

- config/config.go
- config/config_test.go
The current pipeline configuration prevents metric processors from being registered. I need this feature for some work I'm doing so I'd like to enable it.
> Allow metric processors to be specified in pipelines

- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
- observability/observability.go
- observability/observability_test.go
- receiver/prometheusreceiver/metrics_receiver.go
The "Name" property of the config confused me and believed that it is not the full name `type/name` because in documentation we refer to `type` and `name`. Maybe we should have a `Name` and `FullName` (NormalizedName).
> Remove observability special name construction and use the full name

- Makefile
- exporter/exporterhelper/metricshelper.go
- exporter/exportertest/nop_exporter_test.go
- exporter/exportertest/sink_exporter_test.go
- exporter/prometheusexporter/factory.go
- observability/observability_test.go
- observability/observabilitytest/observabilitytest_test.go
- processor/fanoutconnector_test.go
- processor/nodebatcherprocessor/node_batcher_test.go
- processor/probabilisticsamplerprocessor/probabilisticsampler_test.go
- processor/processortest/nop_processor_test.go
- processor/queuedprocessor/factory.go
- receiver/opencensusreceiver/ocmetrics/opencensus.go
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/opencensusreceiver/octrace/observability_test.go
- receiver/opencensusreceiver/octrace/opencensus.go
- receiver/opencensusreceiver/octrace/opencensus_test.go
- receiver/prometheusreceiver/factory_test.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/metrics_receiver_test.go
- receiver/zipkinreceiver/proto_parse_test.go
- translator/trace/jaeger/jaegerproto_to_protospan_test.go
- translator/trace/jaeger/jaegerthrift_to_protospan_test.go
- translator/trace/jaeger/protospan_to_jaegerproto.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
This breaks on incorrect grouping imports and fixes the found ones.
> Make goimports observe local

- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/transaction.go
This change to the Prometheus receiver will prevent unnecessary log messages under normal usage.
> Change log statement in Prometheus receiver from info to debug.

- receiver/prometheusreceiver/internal/transaction.go
This change fixes an issue where the call to the metrics adjuster could result in an empty slice of metrics being passed to ConsumeMetricsData().
> Prometheus Receiver: Ensure that ConsumeMetricsData() is not passed empty metrics

- translator/trace/jaeger/protospan_to_jaegerproto.go
- translator/trace/jaeger/protospan_to_jaegerthrift.go
Jaeger translator was taking address of the loop variable when copying
span tags. This resulted in all destination tags having same values.
This PR fixes the bug and also uses one common code pattern for all
copying code so that copy pasting in future does not introduce similar
bugs.
> Fixed loop variable pointer bug in jaeger translator

- CODEOWNERS
- README.md
- cmd/otelsvc/main.go
- defaults/defaults_test.go
- docs/design.md
- docs/migrating-from-opencensus.md
- docs/observability.md
- docs/performance.md
- docs/service-extensions.md
- docs/vision.md
- examples/demo/README.md
- exporter/README.md
- extension/README.md
- extension/extension.go
- receiver/README.md
- service/service.go
- testbed/README.md
This begins implementation of https://github.com/open-telemetry/opentelemetry-service/issues/352
> Rename OpenTelemetry Service to Collector in docs and comments

- Makefile
- processor/README.md
- processor/fanoutconnector.go
- processor/fanoutconnector_test.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder_test.go
`traceFanOutConnector` and `metricsFanOutConnector` previously simply
passed `TraceData` or `MetricsData` to consumers.
This could cause problems when the data is fed into multiple pipelines
and is concurrently processed and modified by processors.
Fan out connectors now create clones of data before and the clone to
each consumer that is connected (except one - which can use the original).
This is used both for fanout connectors used when the same receiver
feeds data to multiple pipelines (which is somewhat rare use case)
and also when we have multiple exporters connected to the same pipeline
(exporters may modify data).
Fixes issue: https://github.com/open-telemetry/opentelemetry-service/issues/353
> Fix concurrency handling when data is fanned out

- consumer/consumer.go
- processor/attributesprocessor/attributes.go
- processor/cloningfanoutconnector.go
- processor/cloningfanoutconnector_test.go
- processor/fanoutconnector.go
- processor/fanoutconnector_test.go
- processor/nodebatcherprocessor/node_batcher.go
- processor/probabilisticsamplerprocessor/probabilisticsampler.go
- processor/processor.go
- processor/processortest/nop_processor.go
- processor/queuedprocessor/queued_processor.go
- processor/queuedprocessor/queued_processor_test.go
- processor/spanprocessor/span.go
- processor/tailsamplingprocessor/processor.go
- processor/tailsamplingprocessor/processor_test.go
- service/builder/pipelines_builder.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder.go
This is part 1 of the task to introduce capabilities and declare
processor's intent to mutate or not mutate consumed data for the
purpose of optimizing pipeline data ownership.
If a processor declares that they mutate data the pipeline
that the processor is in will use cloning fan out connector.
This is done only if the pipeline shares a receiver with another
pipeline.
This ensures that it is safe for processor modify the data (because
pipelines work concurrently) and avoids cloning for pipelines that
consume data from the same receiver but do not modify it.
For more details see:
https://github.com/open-telemetry/opentelemetry-collector/issues/372
> Add Capabilities to Processor and use for Fanout cloning decision

- exporter/README.md
- processor/README.md
- service/builder/receivers_builder.go
Exporters are not allowed to modify the data they receive.
The README now explicitly mentions this.
Also fixed processors README to avoid mentioning exporters since
the text was incorrect.
> Add data ownership and mutability clarifications

- exporter/jaeger/jaegergrpcexporter/config_test.go
- exporter/jaeger/jaegergrpcexporter/factory_test.go
- exporter/jaeger/jaegerthrifthttpexporter/config_test.go
- exporter/jaeger/jaegerthrifthttpexporter/exporter_test.go
- exporter/jaeger/jaegerthrifthttpexporter/factory_test.go
- exporter/loggingexporter/factory_test.go
- exporter/loggingexporter/logging_exporter_test.go
Some improvements of tests for an issue https://github.com/open-telemetry/opentelemetry-collector/issues/266
> Improved tests for a logging exporter and jaeger exporter

- config/example_factories.go
- exporter/exporter.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/tracehelper.go
- exporter/exportertest/nop_exporter.go
- exporter/exportertest/sink_exporter.go
- exporter/opencensusexporter/opencensus.go
- exporter/prometheusexporter/prometheus.go
- exporter/zipkinexporter/zipkin.go
- service/builder/exporters_builder.go
- service/builder/exporters_builder_test.go
- service/builder/receivers_builder.go
- service/service.go
This is done to have uniformness with Receivers and allow
exporters to communicate with the host (Collector) in the
future.
> Add Start() function to Exporter interface

- processor/processortest/nop_processor.go
- processor/processortest/nop_processor_test.go
- service/builder/exporters_builder.go
- service/builder/exporters_builder_test.go
- service/builder/pipelines_builder.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
- service/builder/testdata/bad_processor_factory.yaml
- service/builder/testdata/bad_receiver_factory.yaml
- service/service.go
- service/service_test.go
The factories can be implemented by 3rd party and this gives a better error message instead of a crash.
Fixes #358
> Handle factories returning nil objects without error

- processor/attributesprocessor/attributes.go
- processor/nodebatcherprocessor/node_batcher.go
- processor/probabilisticsamplerprocessor/probabilisticsampler.go
- processor/processor.go
- processor/processortest/nop_processor.go
- processor/queuedprocessor/queued_processor.go
- processor/spanprocessor/span.go
- processor/tailsamplingprocessor/processor.go
- processor/tailsamplingprocessor/processor_test.go
- service/service.go
Shutdown() method is added so that we can implement proper
pipeline flushing during collector shutdown. This will be done
in a future PR.
> Add Shutdown() function to processors

- receiver/prometheusreceiver/internal/metrics_adjuster.go
- receiver/prometheusreceiver/internal/metrics_adjuster_test.go
- receiver/prometheusreceiver/internal/transaction.go
The Prometheus receiver does not currently account for timeseries dropped by the metrics adjuster, this code change adds support for doing so.
One question is whether timeseries dropped by the metrics adjuster should contribute to overall dropped timeseries or should be removed from received timeseries. I went with the former because, if there were an issue with the metrics adjuster, it would be useful to see the actual number of timeseries received.
> Account for dropped timeseries in the Prometheus metrics adjuster

- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
> fixing TestExportProtocolViolations_nodelessFirstMessage flakyness

- cmd/otelcol/main.go
- config/configcheck/configcheck.go
- config/configcheck/configcheck_test.go
- defaults/defaults.go
- exporter/factory.go
- exporter/jaeger/jaegergrpcexporter/factory_test.go
- exporter/loggingexporter/factory_test.go
- exporter/opencensusexporter/factory_test.go
- exporter/prometheusexporter/factory_test.go
- exporter/zipkinexporter/factory_test.go
- extension/factory.go
- extension/healthcheckextension/factory_test.go
- extension/pprofextension/factory_test.go
- extension/zpagesextension/factory_test.go
- processor/attributesprocessor/factory_test.go
- processor/factory.go
- processor/nodebatcherprocessor/factory_test.go
- processor/probabilisticsamplerprocessor/factory_test.go
- processor/queuedprocessor/factory_test.go
- processor/spanprocessor/factory_test.go
- processor/tailsamplingprocessor/factory_test.go
- receiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/opencensusreceiver/factory_test.go
- receiver/prometheusreceiver/factory_test.go
- receiver/vmmetricsreceiver/factory_test.go
- receiver/zipkinreceiver/factory_test.go
- service/service.go
- service/service_test.go
Adds a validation via reflection that checks if the 'mapstructure' tags are following the desired naming conventions desired for the config file. This becomes a runtime validation so even if not properly tested by some component the inconsistency is captured.
Fixes #359
> Validate configuration object tags

- receiver/prometheusreceiver/config.go
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
- receiver/prometheusreceiver/internal/ocastore.go
- receiver/prometheusreceiver/internal/ocastore_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/internal/transaction_test.go
- receiver/prometheusreceiver/metrics_receiver.go
- receiver/prometheusreceiver/metrics_receiver_test.go
- receiver/prometheusreceiver/testdata/config.yaml
Prometheus clients can optionally export a standard start-time gauge metric, process_start_time_seconds, that greatly simplifies the logic necessary for setting the start timestamp for exported timeseries, which removes the overhead of the metrics adjuster.
This change adds a configuration option to use the start-time metric. If the start-time metric is not found in a scrape, the timeseries for that scrape are dropped.
Note that the start-time timeseries is not exported by the prometheus receiver as a metric (i.e. not passed to ConsumeMetricsData).
> Add support for Prometheus' start time metric

- README.md
Complete update to README. Receivers, processors, exporters and service sections should now reflect current behavior and point to additional documentation. Legacy documentation/configuration has been removed.
> Update README based on latest release

- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/ocastore.go
- receiver/prometheusreceiver/internal/ocastore_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/internal/transaction_test.go
- receiver/prometheusreceiver/metrics_receiver.go
The metrics are recorded based on the Prometheus-define sample timeseries (https://prometheus.io/docs/concepts/jobs_instances/).
> Add http latency metrics to Prometheus receiver

- examples/demo/otel-collector-config.yaml
- exporter/zipkinexporter/config.go
- exporter/zipkinexporter/config_test.go
- exporter/zipkinexporter/factory.go
- exporter/zipkinexporter/testdata/config.yaml
- exporter/zipkinexporter/zipkin.go
- exporter/zipkinexporter/zipkin_test.go
- go.sum
Allows the zipkin exporter to be configured for the proto serialization option.
closes #356
> Adds binary option to the zipkin exporter

- receiver/prometheusreceiver/internal/metrics_adjuster.go
- receiver/prometheusreceiver/internal/metrics_adjuster_test.go
The field "mark" was not fully protected, added proper RLock/RUnlock to protect it. Opportunistically moved one lock from higher level to where it is actually used and also added a sleep looked like was missing from the test.
Fixes #391
/cc @dinooliva
> Fix race on metrics adjuster

- processor/batchprocessor/metrics.go
- processor/metrics.go
- processor/queuedprocessor/factory.go
- processor/queuedprocessor/queued_processor.go
For historical reasons the tag associated to the name of a processor was still named "exporter", changed that to "processor". Added also the name of the queued retry instance to be used as the name of the processor.
> Fix processor metric tag key and add queued retry name

- Makefile
- go.mod
- go.sum
- internal/tools.go
- observability/observability.go
- receiver/opencensusreceiver/factory.go
- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/metrics_receiver.go
- receiver/zipkinreceiver/factory_test.go
- testbed/go.sum
- testbed/testbed/mock_backend_test.go
Similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42/
Add impi to ensure import organization (std, 3rd party and local).
> Add impi to ensure import organization

- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/factory.go
- receiver/prometheusreceiver/testdata/config_env.yaml
The OpenTelemetery Collector currently provides environment variable substitution for config files but this doesn't work for the 'config' portion of the Prometheus receiver where a custom unmarshaler used.
To support our current use-case, we need this feature available for the 'config' portion so we extend the custom unmarshaler to provide it.
> Add environment variable substitution to the Prometheus Receiver config

- processor/resourceprocessor/config.go
- processor/resourceprocessor/config_test.go
- processor/resourceprocessor/doc.go
- processor/resourceprocessor/factory.go
- processor/resourceprocessor/factory_test.go
- processor/resourceprocessor/resource_processor.go
- processor/resourceprocessor/resource_processor_test.go
- processor/resourceprocessor/testdata/config.yaml
Add a resource processor that provides config-based static specification of a resource label that will be added to metrics and trace data.
> Add Resource Processor

- README.md
- go.mod
- go.sum
- internal/testutils/testutils.go
- internal/testutils/testutils_test.go
- receiver/README.md
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/jaeger_agent_test.go
- receiver/jaegerreceiver/testdata/config.yaml
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
- testbed/go.mod
- testbed/testbed/mock_backend.go
Adds the ability to configure the Jaeger Agent protocols independently.  Resolves #157.
Changes: 
- Added documentation about new configuration options
- Added new options to config tests
- Removed `agent *agentapp.Agent` because the agent did not support independently configuring the http server and agent protocols.  
- Added agentProcessors/agentServer to allow for independent configuration of remote sampling proxy as well as agent protocols.
- Added structure to support future addition of jaeger http proxy for remote sampling/baggage.
- Correctly set the `SourceFormat` to jaeger for spans ingested through the agent services.
Tests pass and this has been manually tested in our internal environment.
cc @annanay25
> Add Jaeger Agent Configuration

- processor/samplingprocessor/tailsamplingprocessor/sampling/string_tag_filter.go
Replaced bool with empty struct since bool wasn't leveraged:
```go
if _, ok := saf.values[truncableStr.Value]; ok {
// 
}
```
instead of 
```go
if saf.values[truncableStr.Value] {
//
}
```
Also, empty struct occupies less memory.
> Use empty struct in string-attribute-filter

- .gitignore
- service/builder/receivers_builder.go
fixes #429 
Also modified .gitignore to ignore *.iml files.
> log useful error when receiver creation fails.

- processor/queuedprocessor/factory.go
The logger for the queued retry is not being set making hard to debug issues.
> Set logger for queued_retry

- docs/design.md
- fix double quote in config examples
- remove some trailing white spaces and duplicate word
> Design doc: fix indent in the receivers config example

- testbed/go.mod
- testbed/go.sum
- testbed/testbed/load_generator.go
- testbed/testbed/mock_backend.go
- testbed/testbed/mock_backend_test.go
- testbed/testbed/receivers.go
- testbed/testbed/test_case.go
- testbed/testbed/trace_exporters.go
- testbed/tests/e2e_test.go
- testbed/tests/perf_test.go
1. Extracted TraceExporter and Receiver out of LoadGenerator and MockBackend.
This makes the testbed core protocol-independent and allows to generate
and receive loads using different protocols more easily. Previously it
was pretty much hard-coded to either Jaeger or OC. Now more protocols
can be tested.
For now we have TraceExporter implementation only for OC protocol. Once more
protocol exporters are added to the testbed we can implement matrix testing
of different input/output protocols if needed. Until then all tests use
Collector's OC receiver.
2. Test10kSPS scenario now tests 2 Collector exporters (using 2 Testbed Receivers);
both Jaeger and OC are tested. The test uses dynamic port and generates
config for each protocol sub-test. This is to demonstrate that we are able
to test more …
> Make Testbed more protocol-independent

- docs/design.md
- docs/migrating-from-opencensus.md
- docs/service-extensions.md
The link needs to be updated since the original doc was part of Omnition
GSuite that is now migrated to Splunk GSuite.
> Fix broken link to Configuration spec

- testbed/testbed/test_case.go
- testbed/tests/perf_scenarios.go
- testbed/tests/perf_test.go
When running locally on dev machine it is often useful to have short E2E tests.
This is now possible using TESTBED_DURATION env variable. For example to run E2E
tests so that each takes approximately 1 second do this:
TESTBED_DURATION=1s make run tests
If TESTBED_DURATION is unspecified it defaults to 15 seconds which was the most
common duration in the past.
> Introduce TESTBED_DURATION to control duration of E2E tests

- testbed/testbed/load_generator.go
- testbed/testbed/mock_backend.go
- testbed/testbed/mock_backend_test.go
- testbed/testbed/receivers.go
- testbed/testbed/senders.go
- testbed/testbed/test_case.go
- testbed/tests/e2e_test.go
- testbed/tests/metric_test.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
Exporter and Receiver names were easy to confuse with exporters
and receivers in the actual Collector. This changes helps to make
them distinct.
> Use DataSender and DataReceiver names in TestBed

- testbed/testbed/mock_backend.go
- testbed/testbed/receivers.go
Exporting this is necessary so that we can implement new data
receivers in the contrib repo.
> Export Port field and Mocks to allow creating new data receivers

- testbed/tests/results/BASELINE.md
- testbed/tests/scenarios.go
Batch processor is typical part of any reasonable configuration.
Added it to the configuration of E2E tests so they better reflect
real world usage.
> Add batch processor to E2E tests

- testbed/testbed/mock_backend_test.go
- testbed/testbed/senders.go
- testbed/tests/e2e_test.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
OpenCensus E2E test was previously using JaegerThrift sender.
Now it uses OpenCensus protocol on both ends.
> Add OpenCensus data sender and E2E test

- receiver/README.md
- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/jaeger_agent_test.go
- receiver/jaegerreceiver/testdata/config.yaml
- receiver/jaegerreceiver/trace_receiver.go
This PR takes over from #432 
- Added SamplingManager to the `jReceiver` struct
- Added new parameters to configure remote sampling endpoint (`remote_sampling:fetch_endpoint`)
- Added tests and updated README
/cc @joe-elliott @tigrannajaryan
> Jaeger receiver: Remote sampling support

- testbed/testbed/child_process.go
- testbed/testbed/test_case.go
- testbed/tests/e2e_test.go
- testbed/tests/metric_test.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
- Changed TestCase to use ResourceSpec to specify resource limits.
- Changed Scenario10kItemsPerSecond to accept and use ResourceSpec.
- Removed SetExpectedMaxCPU and SetExpectedMaxRAM functions, using
SetResourceLimits instead. This makes the resource limit specifications
more uniform across the testbed.
- Adjusted resource limits of existing tests to be 1.2x of what they
consume in Travis CI. This gives enough room for measurement instability
in CI and still allows catching big regressions.
> Add ability to specify resource limits in scenarios

- testbed/runtests.sh
- testbed/tests/trace_test.go
The flag is passed to `go test` command. It allows for example to run a
single test if needed. For example to run TestTraceNoBackend10kSPSJaeger
execute this command:
make e2e-test TEST_ARGS="-run TestTraceNoBackend10kSPSJaeger"
> Add TEST_ARGS flag to E2E test execution

- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/exportertest/sink_exporter.go
- receiver/opencensusreceiver/octrace/observability_test.go
Slicing is unnecessary, because slice expressions are equal to itself when evaluated. That's why removed to simplify.
> Unslice to simplify

- extension/pprofextension/config.go
- extension/pprofextension/pprofextension.go
- testbed/tests/scenarios.go
Collector was already able to collect own CPU profiles.
This change enables saving CPU profile to a file after each E2E test.
This helps to analyze performance of the Collector in E2E tests.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/481
> Add CPU profile saving to E2E tests

- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
This allows other to import and extend the zipkin receiver for different
use cases. For example, people can now wrap the server handler and add
HTTP middlewares to it. 
For example this allows people to create wrappers or HTTP middlewares for the server like this: https://github.com/Omnition/omnition-opentelemetry-collector/pull/46
> Zipkin receiver: Allow supplying a custom HTTP server

- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler.go
- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler_test.go
- processor/samplingprocessor/probabilisticsamplerprocessor/testdata/config.yaml
Adds support to OpenTracing "sampling.priority" per semantic conventions at https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table
> Add "sampling.priority" support to probabilistic sampler

- testbed/go.mod
The dependency was referring to non-existing version. This was
building fine in this repo because the dependency is replaced
but was causing problem in other repos which consume the testbed.
> Fix incorrect dependency version in testbed/go.mod

- testbed/go.mod
We previously had a broken dependency that was referring
to non-existing version 0.2.0. This is now causing problems
whenever go attempts to resolve latest version.
Pinning to specific commit should hopefully fix the problem.
> Use specific commit hash in dependency

- examples/k8s.yaml
Resolves #366 by updating configuration to use Otel model and v0.2.0 docker image. 
The docker compose instructions and configs are correct and up to date https://github.com/open-telemetry/opentelemetry-collector/tree/master/examples/demo
> Update k8s config to use opentelemetry docker image and configuration

- receiver/opencensusreceiver/octrace/opencensus.go
- receiver/opencensusreceiver/octrace/options.go
- receiver/opencensusreceiver/opencensus.go
- receiver/opencensusreceiver/opencensus_test.go
Workers were unnecessary complication and did not provide any measurable
performance gains.
In addition they were decoupling receiver from subsequent processors which
makes difficult upcoming implementation of backpressure in the pipeline
(from processors to receivers).
Test results that shows that worker give no performance benefits (any
differences are within the measurement error margin):
Without workers (this commit):
Test                                    |Result|Duration|CPU Avg%|CPU Max%|RAM Avg MiB|RAM Max MiB|Sent Items|Received Items|
----------------------------------------|------|-------:|-------:|-------:|----------:|----------:|---------:|-------------:|
Trace10kSPS/OpenCensus                  |PASS  |     16s|    22.7|    25.9|         37|         45|    149880| …
> Remove workers from OpenCensus receiver implementation

- README.md
- config/config.go
- receiver/README.md
- receiver/factory.go
- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/testdata/bad_empty_config.yaml
- receiver/jaegerreceiver/testdata/bad_no_proto_config.yaml
- receiver/jaegerreceiver/testdata/bad_proto_config.yaml
- receiver/jaegerreceiver/testdata/config.yaml
- receiver/jaegerreceiver/testdata/no_proto_config.yaml
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/prometheusreceiver/factory.go
- service/testdata/otelcol-config.yaml
Fixes #445, #158 
This PR addresses some Jaeger receiver config cleanup as well as makes some breaking changes to the way the config is handled.   See below for details.
**Fixes/Updates**
- Disabled flag is respected per protocol
- Unspecified protocols will no longer be started
- Empty protocol configs can now be specified to start the protocol with defaults. e.g.
```
jaeger:
protocols:
grpc:
```
- Updated readmes
- Naming and behavior of per protocol Addr/Enabled functions in `trace_reciever.go` has been standardized.
- Added thrift tchannel test to meet code coverage
**Breaking Change**
Changed the way an empty `jaeger:` config is handled.  An empty/default config does not start any jaeger protocols.  Previously it started all three collector protocols.  This is a consequence of not …
> Jaeger Receiver Config Fixes

- defaults/defaults.go
- defaults/defaults_test.go
- processor/memorylimiter/config.go
- processor/memorylimiter/config_test.go
- processor/memorylimiter/factory.go
- processor/memorylimiter/factory_test.go
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
- processor/memorylimiter/metrics.go
- processor/memorylimiter/testdata/config.yaml
- processor/processor.go
- testbed/tests/testdata/memory-limiter.yaml
- testbed/tests/trace_test.go
This adds a processor that drops data according to configured memory limits.
The processor is important for high load situations when receiving rate exceeds exporting
rate (and an extreme case of this is when the target of exporting is unavailable).
Typical production run will need to have this processor included in every pipeline
as the first processor (it needs to be the first to be effective).
> Add a memory limiter processor

- processor/README.md
> Processor doc: add description for queued processor

- client/client.go
- client/client_test.go
- go.sum
- receiver/jaegerreceiver/trace_receiver.go
- receiver/opencensusreceiver/octrace/opencensus.go
- receiver/zipkinreceiver/trace_receiver.go
Client package will help identify clients connecting to different
receivers and enable usecases where processors might depend on some
information about the client. For example, a rate-limiting processor
might need some information about clients to figure out when and how to
rate-limit. Also, the upcoming kubernetes processor depends on this as
it needs the IP address of the clients to properly identify resources.
Submitting this as an independent PR as it is generic enough and not
tied to any single processor or usecase.
This PR adds support to the OC, Zipkin and Jaeger GRPC receivers. I'll implement the
same feature for older jaeger receivers in a follow up PR.
> Added client package to help identify RPC/HTTP clients

- testbed/go.mod
Previous version string was invalid and couldn't be used in contrib.
It resulted in the following error:
```
go: github.com/open-telemetry/opentelemetry-collector-contrib/testbed@v0.0.0-20200113165313-aaaf81577e1a requires
github.com/open-telemetry/opentelemetry-collector/testbed@v0.0.0-20200110193345-9f801c5b8d9f requires
github.com/open-telemetry/opentelemetry-collector@v0.2.0-0.20200110151913-9777072f35b3: invalid pseudo-version: version before v0.2.0 would have negative patch number
Add License finished successfully
Fmt finished successfully
go: github.com/open-telemetry/opentelemetry-collector-contrib/testbed@v0.0.0-20200113165313-aaaf81577e1a requires
github.com/open-telemetry/opentelemetry-collector/testbed@v0.0.0-20200110193345-9f801c5b8d9f requires …
```
> Fixed opentelemetry-collector dep version in testbed

- receiver/README.md
- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/testdata/config.yaml
Added propagation code/tests.
Fixes #492 
cc @annanay25
> Propagate Remote Sampling Host port correctly

- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
- service/builder/testdata/unused_receiver.yaml
If a receiver is defined but not used in any pipelines, collector
crashes with nil pointer deference error. This patch fixes the issue.
If a receiver is defined but not added to any pipelines, the collector segfaults with the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x16d1c29]
goroutine 21 [running]:
testing.tRunner.func1(0xc00018c700)
/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x17af7c0, 0x1efc7a0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/open-telemetry/opentelemetry-collector/service/builder.(*builtReceiver).Start(...) …
```
> Fixed a nil pointer deference error with unused receivers

- README.md
- examples/demo/otel-agent-config.yaml
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/testdata/config.yaml
- receiver/jaegerreceiver/trace_receiver_test.go
- testbed/testbed/senders.go
- testbed/tests/testdata/add-attributes-config.yaml
- testbed/tests/testdata/agent-config.yaml
- testbed/tests/testdata/memory-limiter.yaml
We use underscores instead of dashes by convention in all component
configuration. Jaeger receiver used dashes. This commit brings jaeger
receiver in line with the rest of the components.
> Change Jaeger receiver config

- config/example_factories.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/opencensusreceiver/opencensus.go
- receiver/prometheusreceiver/metrics_receiver.go
- receiver/receiver.go
- receiver/vmmetricsreceiver/metrics_receiver.go
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
These methods are not being used, removing them to reduce a bit
boiler-plate code of components.
**Description:** Removing unused method to reduce a little bit boiler-plate code of components.
**Testing:** `make test`
I was tempted to look into removing `TraceReceiver` and `MetricsReceiver` interfaces since they are now just embedding `Receiver` but that will be a larger changing touching many modules. I will look at it separately, this one already reduces a tiny bit the boiler plate code as intended.
> Remove unused MetricsSource() and TraceSource() methods

- translator/conventions/opentelemetry.go
Updated the constants for semantic convention attributes to align with the current version of the specifications. This includes removal of the peer.* attributes.
> Update to latest semantic convention attribute names

- .travis.yml
- Makefile
- go.mod
Go 1.13 has been out for quite a while now and 1.14 beta is out as well.
We've been building core, contrib and some internal collectors with 1.13
for quite some time now and have resolved all issues that came with the
upgrade already. This should be a very safe change.
This will allow us to use leverage new features and fixes shipped by
1.13 such as updates to Go modules, error wrapping, etc.
> Migrate to Go1.13

- receiver/jaegerreceiver/factory_test.go
> Add grpc creations test case to jaeger receiver

- translator/conventions/opentelemetry.go
I missed on attribute `db.url` in my pull request yesterday.
> Add missed semantic convention attribute

- go.mod
- go.sum
- processor/README.md
- processor/attributesprocessor/attributes.go
- processor/attributesprocessor/attributes_test.go
- processor/attributesprocessor/config.go
- processor/attributesprocessor/config_test.go
- processor/attributesprocessor/factory.go
- processor/attributesprocessor/factory_test.go
- processor/attributesprocessor/testdata/config.yaml
- testbed/go.sum
- testbed/testbed/load_generator.go
- testbed/testbed/mock_backend.go
- testbed/testbed/test_case.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
- Added span_names filter condition.
- Implemented support for regexp patterns in span_names array.
- Added E2E test for attributes processor.
- Added ability to record and verify received data in E2E tests.
**Testing:** 
1. make e2e-test
2. Benchmarked `include` filter using regexp. It takes about 1 microsecond per span for simple regexes, which is virtually the same performance when strict equality is used instead of regex.
**Documentation:** processors README and config examples altered to show the new capability.
> Add span_names regexp-based filtering to attributes processor

- processor/README.md
- processor/spanprocessor/config.go
- processor/spanprocessor/config_test.go
- processor/spanprocessor/factory.go
- processor/spanprocessor/factory_test.go
- processor/spanprocessor/span.go
- processor/spanprocessor/span_test.go
- processor/spanprocessor/testdata/config.yaml
This adds "to_attributes" functionality that complements already
existing "from_attributes" functionality. This is very useful for
extracting attributes from span names and reducing cardinality of
span names.
For usage and examples see rocessor/spanprocessor/config.go and
processor/spanprocessor/testdata/config.yaml.
Testing: unit tests added.
Documentation: see readme.md, config.go and config.yaml
> Add support to extract attributes and rename span

- defaults/defaults.go
- defaults/defaults_test.go
- exporter/fileexporter/config.go
- exporter/fileexporter/config_test.go
- exporter/fileexporter/factory.go
- exporter/fileexporter/factory_test.go
- exporter/fileexporter/file_exporter.go
- exporter/fileexporter/file_exporter_test.go
- exporter/fileexporter/testdata/config.yaml
This exporter is very useful for debugging receivers and processors.
It allows to export the pipeline data to a JSON file and examine as needed.
The data is written in OpenCensus Protobuf JSON encoding
(https://developers.google.com/protocol-buffers/docs/proto3#json).
**Testing:** unit tests and tested manually.
> Add file exporter

- exporter/fileexporter/factory.go
Previously file exporter could write to existing file without truncating it.
Truncating is the desired behavior so that the file contains the new data only.
> Ensure file exporter truncates output file when starting

- exporter/zipkinexporter/zipkin.go
- exporter/zipkinexporter/zipkin_test.go
- translator/trace/jaeger/protospan_to_jaegerproto.go
- translator/trace/jaeger/protospan_to_jaegerthrift.go
- translator/trace/protospan_translation.go
- translator/trace/zipkin/protospan_to_zipkinv1.go
- translator/trace/zipkin/protospan_to_zipkinv1_test.go
- translator/trace/zipkin/zipkinv1_thrift_to_protospan.go
- translator/trace/zipkin/zipkinv1_to_protospan.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
Previously these span kinds were not supported because OpenCensus
does not have equivalent span kinds and they were translated as
"Unspecified" span kind when received by Zipkin receiver.
Now these span kinds are internally stored in a span attribute
named "span.kind" when received by Zipkin receiver. When exporting,
this attribute is used to perform a reverse translation in Zipkin
exporter. "span.kind" also matches the OpenTracing semantic
conventions so it should be correctly interpreted by any backend
that follows this convention.
The code that does translation from OC to Zipkin is moved from
exporter/zipkinexporter/zipkin.go to translator/trace/zipkin/protospan_to_zipkinv1.go. protospan_to_zipkinv1.go is not all
new code, only the code that deals with span kind is to be reviewed. …
> Add support for CONSUMER and PRODUCER span kinds

- exporter/jaeger/jaegergrpcexporter/exporter.go
- exporter/jaeger/jaegergrpcexporter/exporter_test.go
This change fixes an issue where the Jaeger gRPC exporter doesn't behave as expected. The Jaeger gRPC exporter accepts a `headers` configuration value (part of `configgrpc.GRPCSettings`) but doesn't add these headers to the gRPC request that is issued.
> Apply headers configuration to Jaeger gRPC exporter

- receiver/zipkinreceiver/proto_parse_test.go
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
Previously these span kinds were not supported because OpenCensus
does not have equivalent span kinds and they were translated as
"Unspecified" span kind when received by Zipkin receiver.
An earlier fix added this support for Zipkin V1 format. This fix
extends the support to Zipkin V2 format.
Testing done:
- Added a unit test to verify translations between ZipkinV2 and OC.
> Add support for CONSUMER and PRODUCER span kinds for Zipkin V2

- processor/README.md
- processor/attributesprocessor/attributes.go
- processor/attributesprocessor/attributes_test.go
- processor/attributesprocessor/config.go
- processor/attributesprocessor/config_test.go
- processor/attributesprocessor/factory.go
- processor/attributesprocessor/factory_test.go
- processor/attributesprocessor/testdata/config.yaml
- testbed/tests/trace_test.go
- Added regexp support to service name field in include/exclude
filters of attributes processor. This makes it consistent with
span name fields which already use regexp patterns.
- Added match_type to make service name and span name matching explicit.
Testing: added unit and E2E tests.
Documentation: README modified as appropriate.
> Add regexp support to service name include/exclude filters

- service/logger.go
Remove invalid `TRACE` level & add missing `DPANIC`, `PANIC` levels to logger level flag's (`--log-level`) usage string.
Fixes #531 
**Testing:**
N/A
N/A
> Fix usage string of logger level flag

- go.sum
- processor/metrics.go
- processor/queuedprocessor/queued_processor.go
- processor/queuedprocessor/queued_processor_test.go
Change "batches_dropped" to a .Sum(), and emit 0s for them on processor start.
Motivation:
Currently with batches_dropped being a .Count() we end up with a missing metric for bad_batches until one occurs.  This makes discovering the "error" metrics I want to watch kind of annoying as I can't just look in the default prom metric list and choose what I want to dashboard / alert on.
I also think that for things we KNOW are 0, we should be emitting a 0.  If we send 8000 batches, the bad_batches shouldn't be *absent* it should be 0.  I do think that view.Count()'s should be initialized to 0 as well ( but I may not know the whole story there. )
I can add these to the other processors if we think this is a good idea.  For now I just hoped the metric name is correct in my current production …
> Record dropped spans when zero

- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/metrics_receiver_test.go
**Description:** The Prometheus receiver currently drops the process start time metric when it is used to set the start time for scraped metrics but this is inconsistent with how other metrics are handled and prevents users from accessing the metric.
**Testing:** The associated metrics receiver unit test to verify that the metric is no longer dropped.
> Export start time metric, consistent with other metrics.

- examples/demo/.env
- examples/demo/README.md
- examples/demo/docker-compose.yaml
**Description:** Point the demo, by default, to a pre-built image. Devs can still run local builds by settings the env var OTELCOL_IMG.
**Link to tracking Issue:** Fix #536.
**Testing:** Manually launched the demo with new image and locally built.
**Documentation:** Updated demo doc.
> Do not require a local build to run the demo

- service/service.go
- service/service_test.go
This patch exposes service's `cobra.Command`. This is useful when service is embedded in other application which is adding other configuration properties.
I would like to use this feature in https://github.com/jaegertracing/jaeger-opentelemetry-collector to add Jaeger storage flags. The storage flags will be taken into account when creating a default exporter configuration. Storage flags will enable us a smoother migration from Jaeger collector to jaeger-otel-collector in jaeger-operator.
> Expose service command

- processor/README.md
- processor/attributesprocessor/attribute_hasher.go
- processor/attributesprocessor/attributes.go
- processor/attributesprocessor/attributes_test.go
- processor/attributesprocessor/config.go
- processor/attributesprocessor/config_test.go
- processor/attributesprocessor/factory.go
- processor/attributesprocessor/testdata/config.yaml
The new HASH action hashes existing attribute values (using SHA-1) and
replaces the original value with the hashed ones. This is useful when
users want to obfuscate some sensitive values but still want to drive
metrics in the backend based on those values.
**Testing:**: 
- Added test cases for functionality and config.
- Tested manually.
**Documentation:** Updated documentation.
> Add a new `HASH` action to attribute processor

- obsreport/doc.go
- obsreport/obsreport.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_test.go
This package is going to allow controlled transition/rename of metrics.
The initial implementation just prepares the way to remove the calls to
the observability package.
**Description:** In order to be able to rename and change the metrics generated by the Collector without breaking current usage the `obsreport` package is being introduced. After this is merged a command-line flag can be added to control the generation of the different sets of metrics - initially with the default as legacy only.
**Link to tracking Issue:** Needed for #141, see also the comments of PR #530
**Testing:** Besides the added tests I have a series of follow up PRs ready, I used these other PRs to manually validate the changes.
**Documentation:** Please refer to `doc.go` in the new package.
> Add the Observability Report Package

- go.sum
- receiver/README.md
- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/testdata/config.yaml
- receiver/jaegerreceiver/testdata/strategies.json
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
Added support for hosting a jaeger remote sampling file as requested in #500.  This was added to the core repo per discussion there.  
Fixes #500 
**Testing:**
Tests were added covering config, receiver creation and receiver functionality.
Added documentation on the new `strategy_file` config option.
> Add Support for Sampling JSON

- internal/collector/telemetry/process_telemetry.go
**Description:** These metrics had an outdated prefix, while at it renamed the metrics attempting to make their meaning more obvious.
**Link to tracking Issue:** Related to #141 
**Testing:** Manually validated generated metric names
> Rename Process Metrics

- examples/k8s.yaml
The binary path was moved so I was unable to run the latest image. This PR updates to the latest available image and uses the new path to avoid any confusion to future users.
All documentation
> Fix binary path and update to latest docker image

- consumer/consumer.go
- consumer/consumerdata/consumerdata.go
- exporter/exporter.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/factory.go
- internal/data/common.go
- internal/data/common_test.go
- internal/data/doc.go
- internal/data/resource.go
- internal/data/trace.go
- internal/data/trace_test.go
- receiver/factory.go
- translator/trace/oc_to_otlp.go
- translator/trace/oc_to_otlp_test.go
1. Introduced data structures that represent telemetry data in-memory.
2. Renamed OTLP* interfaces and types to *V2 types to denote that they are
Internal and not OTLP and are the new version of internal data.
Internal representation is somewhat different from OTLP.
Testing done: unit tests that cover non-trivial functions. Single-line
getters and setters are typically not covered.
Documentation: added doc.go to describe the implementation and usage.
Design doc and benchmarks: https://docs.google.com/document/d/1MSKjMVXQsP51lA6OwpfyLfZhWK-MkGo5vff43LhrqZU/edit#
> Introduce internal TraceData and other data structures

- exporter/README.md
- exporter/zipkinexporter/config.go
- exporter/zipkinexporter/config_test.go
- exporter/zipkinexporter/testdata/config.yaml
- exporter/zipkinexporter/zipkin.go
- translator/trace/spandata/protospan_to_spandata.go
- translator/trace/spandata/protospan_to_spandata_test.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
Resource data might include various labels that are currently missed when doing conversion. It seems to be a current limitation of the design: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/exporter-zipkin.md
This change adds this capability, simple merging resource labels with span attributes
**Testing:** Unit Tests + Manual tests on interoperability with K8S metadata tagging
**Documentation:** Relevant project documentation updated
> Include resource labels in Zipkin export

- examples/k8s.yaml
Signed-off-by: Irving Popovetsky <irving@honeycomb.io>
There's a few typos in the k8s example yaml file:
- In the `otel-collector-conf` configMap, the top-level key should be `service` not `services`
- misspelling of `opencensus`
- port definitions with underscores (`_`) cause a kubernetes DNS-1123 validation error
> Fix a few typos in the k8s example

- README.md
I found several of the examples in the README were incorrect:
* the opencensus and zipkin receivers take an `endpoint` key, not `address`
* Most users will want these to listen on `0.0.0.0` or a specific IP, not localhost 
* the jaeger_grpc exporter endpoint can't start with `http://`, it is simply `hostname:port`
* my editor auto-trimmed a few trailing whitespaces
**Testing:** 
These issues were discovered while attempting to integrate the otel collector into the [Google/OpenCensus microservices-demo project](https://github.com/irvingpop/microservices-demo/tree/full_jaeger)
> Fix several example typos in the README

- internal/data/metric.go
- internal/data/metric_test.go
Tests only for non trivial functions.
Consider next:
* add abstraction on top of the 4 point types similar with AttributeValue.
* add abstraction on top of the explicit bucket definition to support multiple types in the future (maybe similar with AttributeValue).
> Add internal representation for metrics

- Makefile
Change addlicense target to use the current year
> Change addlicense to use current year

- internal/data/trace.go
- internal/internal.go
- testbed/go.sum
- translator/conventions/opencensus.go
- translator/opencensus/oc_to_internal.go
- translator/opencensus/oc_to_internal_test.go
- translator/trace/oc_to_otlp.go
- translator/trace/otlp_to_oc.go
- translator/trace/otlp_to_oc_test.go
This implements translation from OpenCensus to internal representation.
This will be needed by OpenCensus receiver and can be also used
by compatibility shims.
Moved oc_const.go to conventions/opencensus.go and made the constants
exported so that we can reuse in the codebase.
> OpenCensus to internal data structure translation

- exporter/README.md
Small fix in Jaeger docs.
Signed-off-by: dgzlopes <danielgonzalezlopes@gmail.com>
> Fix link to Jaeger gRPC config

- internal/data/trace.go
- internal/internal.go
- translator/internal/internal_to_oc.go
- translator/internal/internal_to_oc_test.go
- translator/opencensus/oc_to_internal.go
- translator/trace/otlp_to_oc.go
- translator/trace/otlp_to_oc_test.go
This implements translation from internal data representation to OpenCensus format.
Needed as a temporary solution that allows new-styles receivers to send data to old-style processors.
> Add translator from internal data structure to Opencensus format

- internal/data/metric.go
- internal/data/metric_test.go
There are some important advantages to use pimpl:
* Consistency at the data API, all objects are simple wrappers to the underlying data, some may have an internal representation as well.
* Avoids implementations mistakes like `foo.getBar().setBaz()` it is guaranteed to be reflected in the `foo` instance - this can be achieved as well with pointers but mixing pointers vs non-pointers may cause bugs.
* We have the same amount of allocations, every time when we used an object by pointer we now have an internal pointer allocated.
* In the future we can optimize the structs to directly modify the marshaled proto, and in that case using struct values (like now) will avoid unnecessary allocations for every object pointer that we had before.
* Cleaner separation between the orig data and the …
> Change metric internal to use pimpl

- go.mod
- internal/processor/filterset/doc.go
- internal/processor/filterset/filterset.go
- internal/processor/filterset/filterset_test.go
- internal/processor/filterset/regexp/doc.go
- internal/processor/filterset/regexp/options.go
- internal/processor/filterset/regexp/regexpfilterset_test.go
- internal/processor/filterset/regexp/regexpfliterset.go
- internal/processor/filterset/strict/doc.go
- internal/processor/filterset/strict/options.go
- internal/processor/filterset/strict/strictfilterset.go
- internal/processor/filterset/strict/strictfilterset_test.go
Add filterset helper package to internal/processor that can be used by processors to filter metrics and spans by string properties.
`import "github.com/open-telemetry/opentelemetry-collector/internal/processor/filterset"`
This adds two types of filtersets
- regexp: filter strings using https://golang.org/pkg/regexp/ patterns
- strict: filter strings using exact string matches
**Link to tracking Issue:** First part of Filter Processor Proposal #560, though the package can be used by other processors too
This can be used for the [MatchSpan](https://github.com/open-telemetry/opentelemetry-collector/blob/05b7a5a073d5521225671b2e3d54e3644ec658e4/internal/processor/span/span.go#L37) implementation and the upcoming MatchMetric function. …
> Add filterset package that can be used to filter by string properties

- internal/data/common.go
This is to be consistent with other package names we use in data.
Split from https://github.com/open-telemetry/opentelemetry-collector/pull/630 to reduce size of that PR with unrelated changes.
> Rename import package in data/common.go

- CONTRIBUTING.md
- cmd/otelcol/main.go
- service/builder/exporters_builder.go
- service/builder/receivers_builder.go
- service/service.go
- service/telemetry.go
Fixes #619 - Replacing usages of `log.Fatal` with returning errors in `Application`, to be handled by the caller of `Application.Start()`.
**Link to tracking Issue:** #619
**Testing:** No tests failing
**Documentation:** Updated `CONTRIBUTING.md` to document the rules for process termination.
> Replace log.Fatal with returning errors to be handled by caller

- config/config.go
- consumer/consumer.go
- consumer/converter.go
- defaults/defaults_test.go
- receiver/factory.go
- receiver/factory_test.go
- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
- service/builder/testdata/new_style_receiver_factory.yaml
- translator/internaldata/internal_to_oc.go
- translator/internaldata/internal_to_oc_test.go
Once new receiver that uses internal data structure added into the pipeline it must be able to work with downstream components that still use old OC traces internally. This change makes it possible by using a compatibility shim. 
**Testing:** Unit test
> Add compatibility shim between internal and OC traces

- obsreport/obsreport.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus.go
- receiver/opencensusreceiver/octrace/opencensus.go
**Description:** Makes the handling of receive operations under long-lived contexts more straightforward for obsreport package users. See https://github.com/open-telemetry/opentelemetry-collector/pull/625/files/eab570775ccc5de671c7b60946a12541c4d72b27#r391766521
**Link to tracking Issue:** Related to #141 
**Testing:** Added a new test to exercise the new code.
**Documentation:** Added to public members of the package.
> Improve obsreport receiver operations under long lived contexts

- consumer/consumer.go
- exporter/exporter.go
- exporter/factory.go
- extension/factory.go
- processor/factory.go
- processor/processor.go
- receiver/factory.go
- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
- Added V2 metric factories and interfaces for receivers and exporters.
- Added V2 factories and interfaces for processors.
All changes are uniform with previously introduced initial batch of
V2 factories and interfaces.
Issue: https://github.com/open-telemetry/opentelemetry-collector/issues/478
> Add the rest of V2 factories and interfaces

- exporter/loggingexporter/logging_exporter.go
- service/service.go
**Description:** Two fit and finish issues on this change:
- With the improved shutdown merged recently the Collector started to show error messages on shutdown.
- Call to Sync on loggingexporter generates non-actionable error messages.
**Testing:** Manual validation
> Disable usage msg after Start and suppress errors from loggingexporter

- internal/data/metric_test.go
```
$go test -benchmem -bench=. -run=notests ./internal/data/...
goos: darwin
goarch: amd64
BenchmarkOtlpToFromInternal_PassThrough-16                              290311723                4.03 ns/op            0 B/op          0 allocs/op
BenchmarkOtlpToFromInternal_Int64Points_MutateOneLabel-16                1199534               970 ns/op            1216 B/op         18 allocs/op
BenchmarkOtlpToFromInternal_DoublePoints_MutateOneLabel-16               1233117               967 ns/op            1216 B/op         18 allocs/op
BenchmarkOtlpToFromInternal_HistogramPoints_MutateOneLabel-16            1000000              1223 ns/op            1392 B/op         20 allocs/op …
```
> Add initial set of benchmarks for MetricData v2 internal

- cmd/otelcol/main.go
- config/config.go
- config/test_helpers.go
- service/service.go
- service/service_test.go
Support programmatic API for passing config to the service.
This is needed for Jaeger-opentelemetry collector:
* it starts the service with Jaeger components when the configuration file is missing
* it configures components based on the additional flags added to the service
Not polished example of this PR used in Jaeger https://github.com/jaegertracing/jaeger-opentelemetry-collector/pull/32
Jaeger adds additional flags to the service's command. These flags are used to create default configuration objects, therefore the `ConfigFactory` has to be executed after `cmd.Execute` to populate flag values to viper.
Resolves #601
**Testing:** < Describe what testing was performed and which tests …
> Support programmatic API for passing config to the service

- config/configmodels/configmodels.go
- consumer/consumer.go
- consumer/converter.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/factory.go
- processor/factory.go
- receiver/factory.go
- receiver/prometheusreceiver/factory.go
- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
Certain functions had V2 suffixes where it was necessary to have one.
Even without a sufix they have different signature than equally-named
old functions and thus the compiler can clearly distinguish between
structs which implement the old of V2 interfaces.
Removing the suffixes results in cleaner and more readable code.
Some type names still have to use V2 suffix for now otherwise the
names would conflict with existing old type names.
Thanks, Jay for the hint.
> Eliminate unnecessary V2 suffixes from function names

- internal/data/metric.go
- internal/data/metric_test.go
Reduce the number of total allocations and the amount of allocate bytes:
1) Remove unnecessary Label object.
2) Remove unnecessary internal pimpl when only the labels internal is needed. This change reduces with 2 allocations.
3) Remove sliceChanged variable and directly change the `orig` pointer when updating a slice.
Before:
```
$go test -benchmem -bench=. -run=notests ./internal/data/...
goos: darwin
goarch: amd64
BenchmarkOtlpToFromInternal_PassThrough-16                              290311723                4.03 ns/op            0 B/op          0 allocs/op
BenchmarkOtlpToFromInternal_Int64Points_MutateOneLabel-16                1199534               970 ns/op            1216 B/op         18 allocs/op …
```
> Optimize MetricData for the case where labels are accessed

- consumer/converter.go
- internal/data/metric.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/resource_to_oc.go
- translator/internaldata/resource_to_oc_test.go
- translator/internaldata/traces_to_oc.go
- translator/internaldata/traces_to_oc_test.go
This will allow the new-styles metric receivers to send data to old-style processors during the period of transition to internal data structure, also will be reused by OC exporter
Translation is mostly based on OTLP to OC translation defined in translator/metrics/otlp_to_oc.go
> Metrics translation from internal data structure to OC format

- consumer/consumer.go
- consumer/converter.go
- service/builder/receivers_builder.go
This defines an internal data -> OC metrics converter that applied automatically between a new type component and a downstream component that can handle only OC metrics.
> Add compatibility shim between internal and OC metrics

- internal/data/common.go
- internal/data/common_test.go
- internal/data/metric.go
- internal/data/metric_test.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/metrics_to_oc_test.go
This PR plugs the new StringMap that is used in the Metrics, and we can see a very nice benefit from this in the metrics benchmarks:
Before:
```
go test -benchmem -bench=. -run=notests ./internal/data/...
goos: darwin
goarch: amd64
BenchmarkOtlpToFromInternal_PassThrough-16                              317034267                3.64 ns/op            0 B/op          0 allocs/op
BenchmarkOtlpToFromInternal_Int64Points_MutateOneLabel-16                1399080               849 ns/op            1088 B/op         16 allocs/op
BenchmarkOtlpToFromInternal_DoublePoints_MutateOneLabel-16               1414124               846 ns/op            1088 B/op         16 allocs/op …
```
> Add StringMap and use it instead of LablesMap

- exporter/exporterhelper/tracehelper_test.go
- internal/data/common.go
- internal/data/metric.go
- internal/data/resource.go
- internal/data/trace.go
- internal/data/trace_test.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/resource_to_oc.go
- translator/internaldata/resource_to_oc_test.go
- translator/internaldata/traces_to_oc_test.go
- translator/opencensus/oc_to_internal.go
- translator/opencensus/oc_to_internal_test.go
This PR plugs the new AttributeMap only into the Resource, but we can see a very nice benefit from this in the metrics benchmarks:
Before:
```
go test -benchmem -bench=. -run=notests ./internal/data/...
goos: darwin
goarch: amd64
BenchmarkOtlpToFromInternal_PassThrough-16                              318627304                3.66 ns/op            0 B/op          0 allocs/op
BenchmarkOtlpToFromInternal_Int64Points_MutateOneLabel-16                2147724               551 ns/op             688 B/op         13 allocs/op
BenchmarkOtlpToFromInternal_DoublePoints_MutateOneLabel-16               2170123               554 ns/op             688 B/op         13 allocs/op …
```
> Add AttributeMap and use it in the Resource

- .travis.yml
- CONTRIBUTING.md
- exporter/jaeger/jaegerthrifthttpexporter/factory_test.go
- go.mod
There are some runtime improvements like defer functions that we would like to benefit from. See  https://golang.org/doc/go1.14#runtime for more details.
There are some small code changes caused by a change in how go formats errors.
> Upgrade the project to use go 1.14

- Makefile
- go.mod
- go.sum
This will fail until https://github.com/open-telemetry/opentelemetry-collector/pull/663 is merged.
addlicense changed that without -check will not fail and just fix the license.
> Add check for copyright and run it always

- config/config.go
* Make DecodeTypeAndName public so it can be used by other receivers
that are loading receiver names dynamically.
* There was redundant validation being done on typeStr as well as use of err in a branch
that was not guaranteed where err was set. Removed check and added assumption to DecodeTypeAndName function doc.
**Testing:** Ran unit tests
**Documentation:** Inline code comments
> Export config.DecodeTypeAndName

- internal/data/generated_metrics.go
- internal/data/metric.go
- internal/data/metric_test.go
- internal/data_generator/internal/base_fields.go
- internal/data_generator/internal/base_structs.go
- internal/data_generator/internal/metrics_structs.go
- translator/internaldata/metrics_to_oc.go
Before (#660):
```
go test -benchmem -bench=. -run=notests ./internal/data/...
goos: darwin
goarch: amd64
BenchmarkOtlpToFromInternal_PassThrough-16                              1000000000               0.256 ns/op           0 B/op          0 allocs/op
BenchmarkOtlpToFromInternal_Int64Points_MutateOneLabel-16                4681989               252 ns/op             240 B/op          7 allocs/op
BenchmarkOtlpToFromInternal_DoublePoints_MutateOneLabel-16               4736796               249 ns/op             240 B/op          7 allocs/op
BenchmarkOtlpToFromInternal_HistogramPoints_MutateOneLabel-16            3651998               331 ns/op             320 B/op          8 allocs/op …
```
> Change all metric data points to be automatically generated

- obsreport/obsreport_exporter.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_test.go
- Fix export failed for metrics (changed the test to not use the metric itself, so the intended name is captured on the test).
- Fix creation of new processor metrics from legacy views.
**Testing:** 
- Hardcoded the desired metric names on the tests to avoid the tests ignoring mistakes on the metric definition. 
- Added a test to ensure that new metric views are handling views without explicit names.
> Fix some metric names in obsreport

- receiver/opencensusreceiver/ocmetrics/opencensus.go
- receiver/opencensusreceiver/octrace/opencensus.go
- receiver/opencensusreceiver/opencensus_test.go
- testbed/testbed/load_generator.go
- Per review [comment](https://github.com/open-telemetry/opentelemetry-collector/pull/577/files#r393999653) ensuring that observability is recorded if OC metrics receives empty data;
- Noticed that OC metrics were not returning errors to clients, changed it to be in line with OC trace and return an error (terminating the stream);
- Changed OC trace to capture client info from the context when the stream is started instead for each received message.
> Improve OC metrics observability and return errors to clients

- defaults/defaults.go
- defaults/defaults_test.go
- testbed/go.sum
- testbed/testbed/receivers.go
- testbed/testbed/senders.go
- testbed/tests/trace_test.go
- OTLP exporter is now a component enabled in the default build.
- Added OTLP E2E tests for traces.
TODO: Add OTLP E2E tests for metrics once metrics are supported
in OTLP exporter.
Resolves: https://github.com/open-telemetry/opentelemetry-collector/issues/668
> Enable OTLP exporter and add OTLP E2E tests

- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp.go
- translator/common/oc_to_otlp.go
- translator/common/oc_to_otlp_test.go
- translator/metrics/oc_to_otlp.go
- translator/metrics/oc_to_otlp_test.go
- translator/metrics/otlp_to_oc.go
- translator/trace/oc_to_otlp.go
- translator/trace/oc_to_otlp_test.go
**Description:** Used in OTLP Exporter to translate internal OC format to OTLP
`translator/common/oc_to_otlp.go` code was moved as is from `trace/oc_to_otlp.go` 
> Add OC -> OTLP metrics translation

- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/factory.go
- receiver/prometheusreceiver/testdata/invalid-config-prometheus-section.yaml
Using strict umarshalling ensures eliminates common mistakes
such as adding a key intended for the prometheus reciever itself
into the prometheus subconfiguration.
It's worth noting that this is a backwards-incompatible change, as anyone currently using the prometheus receiver with a configuration including unused keys will now fail to start. 
I believe this is ok, as the guideline is to fail fast: https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#startup-error-handling
Fixes #583
**Testing:**
reciever/prometheusreciever/TestLoadConfigFailsOnUnknownPrometheusSection
> Make prometheus reciever config loading strict (fixes #583)

- component/exporter.go
- component/processor.go
- consumer/consumer.go
- exporter/zipkinexporter/zipkin_test.go
- processor/cloningfanoutconnector.go
- processor/cloningfanoutconnector_test.go
- processor/fanoutconnector.go
- processor/fanoutconnector_test.go
- service/builder/exporters_builder.go
- service/builder/pipelines_builder.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder.go
In order to start migrating components from OC to internal data, all parts of the pipeline should be able to automatically convert back to OC if downstream component doesn't work with internal data structure yet
TODO: Support of mutating data processors will be added in a subsequent PR
> Add internal data -> OC compatibility shims to processors and exporters

- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
Fix this issue:
```
[/Users/lazy/github/opentelemetry-collector/testbed/tests/scenarios.go:134] - G307 (CWE-): Deferring unsafe method "*os.File" on type "Close" (Confidence: HIGH, Severity: MEDIUM)
> defer file.Close()
```
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/672
> Fix G307 errors in gosec evaluation

- exporter/fileexporter/factory.go
Fix this issue:
```
[/Users/lazy/github/opentelemetry-collector/exporter/fileexporter/factory.go:70] - G302 (CWE-276): Expect file permissions to be 0600 or less (Confidence: HIGH, Severity: MEDIUM)
> os.OpenFile(cfg.Path, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0755)
```
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/672
> Fix G302 errors in gosec evaluation

- config/test_helpers.go
Fix this issue:
```
[/Users/lazy/github/opentelemetry-collector/config/test_helpers.go:32] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
> os.Open(fileName)
```
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/672
> Fix G304 errors in gosec evaluation

- .circleci/config.yml
- testbed/tests/trace_test.go
Create a mock directory so CircleCI can persist "nothing" to the workspace if there's really nothing.
https://github.com/open-telemetry/opentelemetry-collector/pull/702
**Testing:**
Rerun CircleCI
n/a
> Fix CircleCI errors: ignore if cache missing

- internal/data/metric.go
- internal/data/testdata/metric.go
- internal/data/testdata/metric_test.go
- internal/data/testdata/trace.go
- internal/data/testdata/trace_test.go
- internal/data/trace.go
- processor/cloningfanoutconnector.go
- processor/cloningfanoutconnector_test.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/oc_to_traces_test.go
- translator/internaldata/traces_to_oc_test.go
**Description:** Cloning fanout connectors now able to work with new type of downstream consumers
Aslo added MetricData generators to `internal/data/testdata/metric.go` 
Code in `internal/data/testdata/common.go` moved from `internal/data/testdata/trace.go` as is
> Add support of new type consumers to cloning fanout connectors

- .circleci/config.yml
Publish to the newly created `otel` Docker Hub org instead of `omnition`. 
In addition to publishing released, we'll also be publishing a dev image on every commit to master.
**Testing:** 
Tested manually on CirceCI
> Publish to otel dockerhub account

- internal/data/testdata/trace.go
- internal/data/testdata/trace_test.go
- processor/cloningfanoutconnector_test.go
- translator/internaldata/oc_to_traces_test.go
- translator/internaldata/traces_to_oc_test.go
The main problem is that I used global variables so tests were not deterministic if one of the test changes the input. Decided to revert back to just having functions to generate a new input.
> Remove cleverness that defined tests cases

- go.mod
- go.sum
- service/service_test.go
- service/telemetry.go
This allows each instance of the collector to be uniquely identified in any deployment.
> Add service.instance.id to metrics generated by the Collector

- .golangci.yml
- config/test_helpers.go
- exporter/jaeger/jaegerthrifthttpexporter/exporter_test.go
- exporter/jaeger/jaegerthrifthttpexporter/factory.go
- exporter/otlpexporter/exporter.go
- exporter/zipkinexporter/zipkin.go
- processor/queuedprocessor/queued_processor.go
- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler.go
- processor/samplingprocessor/tailsamplingprocessor/processor.go
- receiver/end_to_end_test.go
- receiver/opencensusreceiver/opencensus.go
- receiver/otlpreceiver/otlp.go
- receiver/vmmetricsreceiver/vm_metrics_collector.go
- service/telemetry.go
- translator/trace/grpc_http_mapper.go
Shadows may be annoying but I think it can cover some very hidden bugs, and make code harder to understand.
Here a hidden bug/issue, err from `proc.Stat()` is never added to the errs:
https://github.com/open-telemetry/opentelemetry-collector/compare/master...bogdandrutu:govetbetter?expand=1#diff-7cf6f365929a0f9534bf47378832af52R173
Here this code worked because ":=" was used and the returned `code` did not actually overwrite the incoming `code` argument (very hard to guess and get it right):
https://github.com/open-telemetry/opentelemetry-collector/compare/master...bogdandrutu:govetbetter?expand=1#diff-ce6c181a493dd6999a951052d26248f5R59
> Enable default govet checks, enable and fix shadows

- .circleci/config.yml
- Makefile
- exporter/otlpexporter/connection.go
- extension/pprofextension/pprofextension.go
- go.sum
- processor/attributesprocessor/attribute_hasher.go
- testbed/testbed/child_process.go
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/737
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/736
Updates: https://github.com/open-telemetry/opentelemetry-collector/issues/735
Fixes: https://github.com/open-telemetry/opentelemetry-collector/issues/672
> Enable gosec in CI, takes ~50sec so make it separate job.

- .circleci/config.yml
publish-dev job needs to be in it's own workflow as it ignores all tags
and that conflicts with the publish-stable workflow. I'll re-enable
publish-dev in a separate PR later.
> Disbaled publish-dev job temporarily

- receiver/opencensusreceiver/octrace/opencensus_test.go
**Description:** Fix race in TestExportProtocolViolations_nodelessFirstMessage. The race is on the `t *testing.T` having one of its fields being read and write concurrently. I didn't investigate why this test needs this special timeout handling, just took the obvious fix to protect against the data race - will look at this again later.
**Link to tracking Issue:** Fixes #41
> Fix race in TestExportProtocolViolations_nodelessFirstMessage

- .circleci/config.yml
Circle was not running any builds for tags because the publish job had
other jobs as dependencies and they did not explicitly specify that they
should be run for tags. Looks like Circle will always run a job for any
branch unless the branch is ignored and never run a job for a tag unless
the tag is explicitly enabled.
> Enable tag publishing

- .circleci/config.yml
This PR enables publishing dev docker images from every commit to master. This was disabled earlier as I suspected it was causing issues with the job that publishes images from tags.
> Re-enable publishing dev docker images from master

- component/component.go
- component/mock_host.go
- config/example_factories.go
- extension/extensiontest/mock_host.go
- service/service.go
- service/service_test.go
- testbed/testbed/load_generator.go
- testbed/testbed/receivers.go
- testbed/tests/trace_test.go
Added GetFactory function to Host interface. This allows components
to fetch factories and create components dynamically. The functionality
will be used by receiver creator that creates and destroys other receivers
as it discovers relevant external endpoints from which these receivers
can get data.
> Allow getting factories from component Host

- internal/data/common.go
- internal/data/common_test.go
- internal/data/generated_metrics.go
- internal/data/generated_metrics_test.go
- internal/data/generated_resource.go
- internal/data/generated_resource_test.go
- internal/data/generated_trace.go
- internal/data/generated_trace_test.go
- internal/data/metric_test.go
- internal/data/testdata/common.go
- internal/data/testdata/metric.go
- internal/data/testdata/resource.go
- internal/data/testdata/trace.go
- internal/data_generator/internal/base_fields.go
- internal/data_generator/internal/common_structs.go
- internal/data_generator/internal/metrics_structs.go
- processor/fanoutconnector_test.go
- translator/internaldata/oc_to_traces.go
- translator/internaldata/oc_to_traces_test.go
- translator/internaldata/resource_to_oc_test.go
- translator/internaldata/traces_to_oc_test.go
The main focus for this PR is to remove all "Set" methods for maps. The current `InitFromMap` is not final but it was the easiest path forward at this moment. A bigger cleanup for maps will be done next, for the moment this allows to finalize all generated data except maps.
> Remove set for maps data

- translator/internaldata/oc_testdata.go
- translator/internaldata/oc_to_resource_test.go
- translator/internaldata/resource_to_oc_test.go
```
go test -benchmem -run=^$ github.com/open-telemetry/opentelemetry-collector/translator/internaldata -bench=.
goos: darwin
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector/translator/internaldata
BenchmarkMetricIntOCToInternal-16          	  529880	      1930 ns/op	    2232 B/op	      37 allocs/op
BenchmarkMetricDoubleOCToInternal-16       	  466656	      2466 ns/op	    2712 B/op	      49 allocs/op
BenchmarkMetricHistogramOCToInternal-16    	  343155	      3389 ns/op	    3672 B/op	      61 allocs/op
BenchmarkMetricSummaryOCToInternal-16      	  476601	      2307 ns/op	    2592 B/op	      43 allocs/op
BenchmarkOcNodeResourceToInternal-16       	  659343	      1837 ns/op	    2580 B/op	      15 allocs/op
BenchmarkInternalResourceToOC-16           	 1361719	       892 …
```
> Add benchmarks for resource translation

- translator/internaldata/oc_to_metrics_test.go
- translator/internaldata/oc_to_resource.go
- translator/internaldata/oc_to_resource_test.go
- translator/internaldata/oc_to_traces_test.go
- translator/internaldata/resource_to_oc_test.go
Before:
```
go test -benchmem -run=^$ github.com/open-telemetry/opentelemetry-collector/translator/internaldata -bench=.
goos: darwin
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector/translator/internaldata
BenchmarkMetricIntOCToInternal-16          	  521413	      1947 ns/op	    2232 B/op	      37 allocs/op
BenchmarkMetricDoubleOCToInternal-16       	  475279	      2430 ns/op	    2712 B/op	      49 allocs/op
BenchmarkMetricHistogramOCToInternal-16    	  344828	      3263 ns/op	    3672 B/op	      61 allocs/op
BenchmarkMetricSummaryOCToInternal-16      	  519634	      2270 ns/op	    2592 B/op	      43 allocs/op
BenchmarkOcNodeResourceToInternal-16       	  656428	      1823 ns/op	    2580 B/op	      15 allocs/op
BenchmarkInternalResourceToOC-16           	 1365171 …
```
> Improve OcNodeResourceToInternal and add benchmarks for mashal/unmarshal

- service/service.go
Validate factories on `service.Run`. `factory.CreateDefaultConfig` can use (default) values from viper, however viper can be initialized with flags from cobra only in `command.Run`.
We would like to use this in jaeger.
> Validate factories on service run

- component/component.go
- component/mock_host.go
- component/mock_host_test.go
- extension/extensiontest/mock_host.go
- processor/queuedprocessor/queued_processor.go
- receiver/prometheusreceiver/metrics_receiver.go
- service/service.go
- testbed/testbed/mock_backend.go
- testbed/testbed/receivers.go
It doesn't make sense to have this method on `component.Host`. Currently, the only usages are in `Start` methods, later we can add it to `Start` if we want to support timeout or cancellation. See https://github.com/open-telemetry/opentelemetry-collector/pull/748#discussion_r402690039
> Remove Context() from component.Host interface

- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
Right before switching OTLP exporter to internal data we want to capture the current OTLP pipeline performance with translation to OC. Once OTLP exporter switched to internal data we can measure improvement of using OTLP internally through the whole pipeline against the OC based pipeline.
This PR removes processors added by default to e2e  tests so we don't need to wait for processors to be switched to internal data in order to measure the performance improvement
> Remove default processors from e2e tests

- component/componenterror/errors.go
- component/componenterror/errors_test.go
- config/configcheck/configcheck.go
- defaults/defaults.go
- exporter/opencensusexporter/opencensus.go
- exporter/otlpexporter/otlp.go
- processor/attributesprocessor/attributes.go
- processor/cloningfanoutconnector.go
- processor/fanoutconnector.go
- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler.go
- processor/samplingprocessor/tailsamplingprocessor/processor.go
- processor/spanprocessor/span.go
- processor/spanprocessor/span_test.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/opencensusreceiver/ocmetrics/opencensus.go
- receiver/opencensusreceiver/octrace/opencensus.go
- receiver/opencensusreceiver/opencensus.go
- receiver/otlpreceiver/metrics/otlp.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/trace/otlp.go
- receiver/prometheusreceiver/internal/ocastore.go
- receiver/vmmetricsreceiver/metrics_receiver.go
- receiver/vmmetricsreceiver/vm_metrics_collector.go
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
- service/builder/exporters_builder.go
- service/builder/pipelines_builder.go
- service/builder/receivers_builder.go
- service/service.go
For consistency with `configerror` and `consumererror`
Question: Should `CombineErrors` be part of the `consumererror`?
> Rename componenterr to componenterror

- internal/data/common.go
- internal/data/common_test.go
- processor/cloningfanoutconnector_test.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/oc_to_resource.go
- translator/internaldata/oc_to_resource_test.go
- translator/internaldata/oc_to_traces.go
- translator/internaldata/resource_to_oc.go
- translator/internaldata/traces_to_oc.go
* Fix a bug in the setters for AttributeValue, the setter needs to overwrite the previous value with the default value.
> Remove AttributeKeyValue, make map insert/upsert safe by copying the given value

- internal/data/metric.go
- internal/data/metric_test.go
- internal/data/testdata/common.go
- internal/data/testdata/metric.go
- internal/data/testdata/metric_test.go
- internal/data/testdata/trace.go
- internal/data/testdata/trace_test.go
- internal/data/trace.go
- internal/data/trace_test.go
- processor/cloningfanoutconnector_test.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/oc_testdata_test.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_metrics_test.go
- translator/internaldata/oc_to_traces_test.go
- translator/internaldata/traces_to_oc.go
- translator/internaldata/traces_to_oc_test.go
Fixes in this PR:
* Handle correctly nil Resource[Spans|Metrics], InstrumentationLibrary[Spans|Metrics], Span|Metric, MetricDataPoints.
* Found a bug that the OTLP MetricDescriptor.Labels were ignored in Internal->OC
* Rename translator/internaldata/{oc_testdata.go => oc_testdata_test.go} to not count these lines in coverage.
Work left for slices:
* Tests and fixes for nil Events, Links, Buckets, ValueAtPercentile
Work left for maps:
* Define what should be the behavior if a nil entry in the "slice map representation".
* Add tests for these cases.
> Fix metric/spans count, add tests for nil entries in the slices

- processor/README.md
- processor/resourceprocessor/resource_processor.go
- processor/resourceprocessor/resource_processor_test.go
A minor tweak for Resource Processor to be able to add static labels without modifying resource type.
**Link to tracking Issue:** #773
**Testing:** Unit test added.
**Documentation:** Documentation updated.
> Don't mutate resource type if it wasn't specified in the Resource Processor config

- component/receiver.go
- config/config.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/prometheusreceiver/factory.go
Split from https://github.com/open-telemetry/opentelemetry-collector/pull/799.
> Update CustomUnmarshaler to not require top level config and the key.

- go.mod
This is no longer needed as the prometheus version used has go.mod with the
required client-go version. Before we were requiring client-go v12 which makes
go unhappy because it thinks if the version vN where N is > 1 then it should
have vN in the import path. Instead Kubernetes now tags what would be v12 as
v0.12 to work around this issue. Although it looks like prometheus just uses
the commit hash in their go.mod.
contrib will also be cleaned up to get rid of the warnings.
> Remove indirect client-go dependency

- internal/data/common.go
Before:
```
goos: darwin
goarch: amd64
BenchmarkSetIntVal
BenchmarkSetIntVal-16    	475874530	         2.53 ns/op
PASS
Process finished with exit code 0
```
After:
```
goos: darwin
goarch: amd64
BenchmarkSetIntVal
BenchmarkSetIntVal-16    	781448800	         1.50 ns/op
PASS
Process finished with exit code 0
```
> Small optimization for SetXVal in AttributeValue

- internal/data/common.go
- internal/processor/filterhelper/filterhelper.go
- internal/processor/filterhelper/filterhelper_test.go
- internal/processor/filterspan/filterspan.go
- internal/processor/filterspan/filterspan_test.go
The maps don't have an easy way to carry nil values, so if user needs a "nil" AttributeValue or StringValue they should use pointers to these data structures. See an example in filterspan where nil is used to signal that only key must exist.
> Disallow nil values in the custom data maps.

- processor/metrics.go
- processor/spanprocessor/config.go
- processor/spanprocessor/config_test.go
- processor/spanprocessor/factory.go
- processor/spanprocessor/factory_test.go
- processor/spanprocessor/span.go
- processor/spanprocessor/span_test.go
Founded problems:
* Maps don't handle nil entries in the underlying slice. What should we do?
* Current data API do not allow to construct slices with nil entries for test - it should probably not allow doing this for normal conversions/pipeline.
* Current protocol does not support undefined type for Attributes, should we support that, or we consider an empty entry as being type string with empty string value?
> Spanprocessor

- component/component.go
- component/componenttest/error_waiting_host.go
- component/componenttest/nop_host.go
- config/config_test.go
- config/example_factories.go
- service/service.go
- service/service_test.go
- testbed/testbed/receivers.go
Host.GetExtensions now allows components to discover extensions.
This will be used by upcoming receivers that need to cooperate
with extensions.
> Allow components to discover Extensions

- config/config.go
- receiver/prometheusreceiver/factory.go
This is an alternative to https://github.com/open-telemetry/opentelemetry-collector/pull/797 which kind of cleanups also the CustomUnmarshaler (which we should probably clean anyway).
* I still have to pass typeStr because some receivers do not set the type in the default config which is unexpected, I would look into that later.
> Polish config and custom unmarshaler

- testbed/testbed/load_generator.go
- testbed/tests/metric_test.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
Before:
```
Test                                    |Result|Duration|CPU Avg%|CPU Max%|RAM Avg MiB|RAM Max MiB|Sent Items|Received Items|
----------------------------------------|------|-------:|-------:|-------:|----------:|----------:|---------:|-------------:|
Metric10kDPS/OpenCensus                 |PASS  |     15s|    16.4|    17.3|         24|         30|    149900|        149900|
Metric10kDPS/OTLP                       |PASS  |     15s|    20.4|    23.9|         26|         32|    150000|        150000|
Trace10kSPS/JaegerGRPC                  |PASS  |     16s|    62.2|    64.7|         24|         29|    149960|        149960|
Trace10kSPS/OpenCensus                  |PASS  |     15s|    36.8|    38.8|         25|         30|    149970|        149970|
Trace10kSPS/OTLP …
```
> Change testbed to send 100 spans/metrics per message for 10K tests.

- internal/data/generated_metrics.go
- internal/data/generated_metrics_test.go
- internal/data/generated_trace.go
- internal/data/generated_trace_test.go
- internal/data_generator/internal/base_structs.go
Split Slice tests to allow parallelism and reduce the number of elements in the generated data for slices.
> Add MoveTo function to the Slice to allow optimal batching.

- internal/data/common.go
- internal/data/common_test.go
- internal/processor/filterspan/filterspan.go
- processor/spanprocessor/span.go
- testbed/tests/trace_test.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/oc_to_resource_test.go
- translator/internaldata/resource_to_oc.go
- translator/internaldata/traces_to_oc.go
**Open Questions**
1. Kind of don't like on the StringMap that I have to call `v.Value()`. Should we return just `string` from iterator? This makes things inconsistent with `AttributeMap`. 
**Benchmark results**
```
BenchmarkAttributeMap_ForEach-16                                 	26334198	        45.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkAttributeMap_RangeOverMap-16                            	 5635006	       214 ns/op	       0 B/op	       0 allocs/op
BenchmarkStringMap_ForEach-16                                    	26362994	        45.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkStringMap_RangeOverMap-16                               	 5518018	       220 ns/op	       0 B/op	       0 allocs/op
```
This was a huge surprise to me that range over maps is very inefficient. In …
> Add maps iterators similar Java's "ForEach"

- consumer/consumer.go
- consumer/converter/converter.go
- consumer/converter/converter_test.go
- consumer/pdata/metric.go
- consumer/pdatautil/empty_test.go
- consumer/pdatautil/pdatautil.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exportertest/nop_exporter.go
- exporter/exportertest/nop_exporter_test.go
- exporter/exportertest/sink_exporter.go
- exporter/exportertest/sink_exporter_test.go
- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
- exporter/otlpexporter/otlp.go
- processor/cloningfanoutconnector.go
- processor/cloningfanoutconnector_test.go
- processor/fanoutconnector.go
- processor/fanoutconnector_test.go
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
- receiver/otlpreceiver/metrics/otlp.go
- receiver/otlpreceiver/metrics/otlp_test.go
- testbed/testbed/mock_backend.go
- testbed/testbed/senders.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_metrics_test.go
The main idea is that currently even if the pdata.Traces is public still contrib cannot be changed to the new Components because there is no way in implementing the `ConsumeMetrics`.
To solve this problem we add a `pdata.Traces` with an opaque field that can carry `[]consumedata.MetricsData` or `data.MetricData` and make all the common consumers/components avoid conversion between the types if not necessary by proving util functions that work on both accepted formts.
With this change all contrib components can be easily change, it adds a very small overhead when carrying the old data because it forces to add an extra slice.
> Add pdata.Metrics with an opaque internal data.

- examples/k8s.yaml
**Description:** Instructions at https://opentelemetry.io/docs/collector/about/ were causing a formatting error, and correcting the formatting resulted in an error starting otel-collector related to naming in the opencensus configuration.
**Testing:** Verified that this change resulted in a successful deployment with `kubectl apply`.
> k8s example: Correct keepalive parameter naming

- translator/internaldata/oc_to_resource.go
Since we don't allocate attributes slice explicitly anymore, we don't need to count attributes
> Remove dead code from oc_to_resource

- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
* use default sampling strategy `{"strategyType":0,"probabilisticSampling":{"samplingRate":0.001}}` if no file is provided - this aligns with Jaeger behavior.
* use default values for fetch endpoint `fetch_endpoint`. If only `host_endpoint` is specified the collector will try to get the sampling strategies from grpc endpoint running on the localhost.
The following configuration would fail on `nil` pointer. The patch fixes it and uses the default value of `remote_endpoint` as `localhost:14250` so it would fail on `collector error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:14250: connect: connection refused"` 
```
receivers:
jaeger:
remote_sampling:
host_endpoint: localhost:5778
protocols:
thrift_compact:
thrift_binary:
``` …
> Use defaults in Jaeger remote sampling.

- receiver/prometheusreceiver/internal/internal_test.go
- receiver/prometheusreceiver/internal/metadata.go
- receiver/prometheusreceiver/internal/transaction_test.go
Fixing a bug - Match instance metadata via `instance` label (currently, `__address__` label is used, which may differ due to relabeling or explicit overridden value).
**Link to tracking Issue:** #709
**Testing:** Replaced mock with the actual implementation of the `MetadataService` interface to reproduce the issue and the fix in the unit test.
**Documentation:** -
> Use instance label for matching instance metadata

- receiver/README.md
- receiver/hostmetricsreceiver/README.md
- receiver/hostmetricsreceiver/config.go
- receiver/hostmetricsreceiver/config_test.go
- receiver/hostmetricsreceiver/example_config.yaml
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/factory_test.go
- receiver/hostmetricsreceiver/hostmetrics_receiver.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/empty_test.go
- receiver/hostmetricsreceiver/internal/scraper.go
- receiver/hostmetricsreceiver/testdata/config.yaml
- service/defaultcomponents/defaults.go
- service/defaultcomponents/defaults_test.go
[Issue 847](https://github.com/open-telemetry/opentelemetry-collector/issues/847)
Added initial scaffolding code for a new hostmetricsreceiver which will scrape Host Metrics (CPU, Memory, Disk, etc) based on the operating system.
This receiver supports configuration per metric type (or "Scraper"), e.g. to collect cpu, memory and disk metrics, config would look something like:
```
hostmetrics:
scrape_interval: 1s
scrapers:
cpu:
report_per_cpu: true
memory:
disk:
```
**Not included in this PR:**
- Scraping implementation: Will be added in follow-up PR
- End to end tests: Will be added in follow-up PR
- Windows build step: A lot of this code only runs against windows (see the `+build windows` flag). At some stage, we'll presumably need to add a …
> Add Host Metrics receiver scaffolding

- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/jaeger_agent_test.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
- testbed/testbed/receivers.go
- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerproto_to_traces_test.go
- translator/trace/jaeger/jaegerthrift_to_traces.go
- translator/trace/jaeger/jaegerthrift_to_traces_test.go
Conversion were replicated from existing jaeger -> OC -> internal.
One concern:
We are getting ParentSpanID from Jaeger span links and writing the link to internal Span.Links slice as well. I'm not sure if it's desired behavior. I'd remove parent span link from the translated internal span and keep that information only ParentSpanID field. Keeping the link copy in Span.Links makes it even more confusing because, with the links conversion, we lose RefType information (like Span_Link_PARENT_LINKED_SPAN or Span_Link_TYPE_UNSPECIFIED), OTLP doesn't have that field.
@tigrannajaryan @pjanotti what do you think about it ^
> Switch Jaeger receiver to internal data model

- processor/batchprocessor/batch_processor_test.go
Elapsed time measurement was set incorrectly. Timeout to compare elapsed time against is triggered with newBatchProcessor, move it below the timer start.
> Fix flaky test TestBatchProcessorSentByTimeout

- receiver/zipkinreceiver/trace_receiver.go
This patch splits zipkin receiver transport tag `http` into more specific types based on version and format. This helps us to understand what client instrumentations are deployed. 
Q: Is format tag going to be added to receivers? If so then this is not necessary as the format dimension would provide the same observability. 
These are the new metrics `--new-metrics=true`
```
otelcol_receiver_accepted_spans{receiver="zipkin",transport="http_v1_json"} 1
otelcol_receiver_accepted_spans{receiver="zipkin",transport="http_v1_thrift"} 1
otelcol_receiver_accepted_spans{receiver="zipkin",transport="http_v2_json"} 1
otelcol_receiver_accepted_spans{receiver="zipkin",transport="http_v2_proto"} 1
```
The …
> Make Zipkin transport metric tag more specific

- go.mod
- go.sum
Updated testify to v.1.5.1 to include https://github.com/stretchr/testify/pull/808, to prevent potential intermittent test failures when using `Eventually` functions
> Upgraded testify to v1.5.1

- examples/k8s.yaml
Support for extensions/v1beta1 was removed in v1.16.
Fix https://github.com/open-telemetry/opentelemetry-collector/issues/828
> Fix k8s example

- consumer/pdata/generated_metrics.go
- consumer/pdata/generated_metrics_test.go
- consumer/pdata/generated_trace.go
- consumer/pdata/generated_trace_test.go
- internal/data_generator/internal/base_structs.go
- processor/batchprocessor/batch_processor.go
- translator/internaldata/oc_to_metrics_test.go
The current `MoveTo` function does move and appends the data to the destination slice. A clear `MoveTo` should replace the data in the destination slice.
> Rename MoveTo to MoveAndAppendTo.

- receiver/jaegerreceiver/trace_receiver.go
Fixes Jaeger receiver's agent metrics. All metrics were reported as `transport=udp_thrift_binary`.
The issue was introduced in https://github.com/open-telemetry/opentelemetry-collector/pull/859 
> Fix Jaeger agent metrics

- Makefile
- internal/version/version.go
- service/logger.go
The [zap development logger](https://godoc.org/go.uber.org/zap#NewDevelopmentConfig) provides nicer console output as well as a few other different defaults for development.
To decide whether to use production or development it's checking if `Version`
has been set at build time. If not it assumes it's development. It may be
better not to conflate version number with build type in which case we could
add a separate build type. But first I wanted to see if the general idea
desirable.
---
Before
```
{"level":"info","ts":1588175559.4787421,"caller":"service/service.go:360","msg":"Starting OpenTelemetry Contrib Collector...","Version":"latest","GitHash":"<NOT PROPERLY GENERATED>","NumCPU":12}
{"level":"info","ts":1588175559.478791,"caller":"service/service.go:199","msg":"Setting up own …
```
> Use development logging when running a local build

- receiver/prometheusreceiver/internal/transaction_test.go
Minor cleanup, replacing `reflect.DeepEqual` with `proto.Equal` for comparing protobuf messages.
/cc @rghetia
> Use proto.Equal to compare protobuf messages

- examples/otel-local-config.yaml
The `health_check` extension does not have an endpoint property, it has a `port` property instead.
> Fix example otel local config

- receiver/hostmetricsreceiver/README.md
- receiver/hostmetricsreceiver/config_test.go
- receiver/hostmetricsreceiver/example_config.yaml
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/hostmetrics_receiver.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/metricutils.go
- receiver/hostmetricsreceiver/internal/scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_constants.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/testutils.go
- receiver/hostmetricsreceiver/testdata/config.yaml
Added cpu scraper to the hostmetricsreceiver which uses gopsutil to scrape CPU times. This can be configured to report on total cpu times, or provide a per cpu breakdown.
**Not included in this PR:**
The next PR will add cpu utilization metrics obtained via windows performance counters
> Added host metrics cpu scraper

- component/component.go
- component/componenttest/error_waiting_host.go
- component/componenttest/nop_host.go
- service/builder/exporters_builder.go
- service/builder/extensions_builder.go
- service/service.go
- service/service_test.go
- testbed/testbed/receivers.go
Host.GetExporters now allows components to discover exporters.
This will be used by upcoming receivers that need to cooperate
with exporters.
> Allow components to discover Exporters

- service/service.go
We would like to use this symbol in Jaeger. It also makes sense to make it public as it is the default factory.
> Make file config factory public

- config/config.go
- receiver/hostmetricsreceiver/factory.go
Export `ViperSub` so custom unmarshallers can use it (see https://github.com/spf13/viper/issues/871 for why we have this method at all)
> Change config.ViperSub to be exported so custom unmarshallers can use it

- config/configgrpc/configgrpc.go
- exporter/jaegerexporter/exporter.go
- exporter/jaegerexporter/exporter_test.go
- exporter/otlpexporter/exporter.go
gRPC can drop a couple of initial RPCs at the beginning of the connection. Wait for ready should prevent it.
Some resources:
* https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md
* https://github.com/grpc/grpc/tree/master/examples/python/wait_for_ready#use-cases-for-wait-for-ready
This feature is needed in Jaeger to make crossdock tests pass. Sometimes Jaeger exporter drops first batches that is causing test failures. I have tested this PR in https://github.com/jaegertracing/jaeger/pull/2211
> Set wait for ready in Jaeger gRPC exporter 

- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerproto_to_traces_test.go
- translator/trace/jaeger/jaegerthrift_to_traces.go
- translator/trace/jaeger/jaegerthrift_to_traces_test.go
Results of BenchmarkProtoBatchToInternalTraces:
Before:
```
BenchmarkProtoBatchToInternalTraces-12        329313          3346 ns/op        3352 B/op         43 allocs/op
```
After:
```
BenchmarkProtoBatchToInternalTraces-12        646017          1737 ns/op        2064 B/op         32 allocs/op
```
Roughly 80% of improvement was gained just by avoiding using intermediate map structure before creation of AttributeMap.
> Improve performance of jaeger to internal traces translation

- consumer/pdata/common.go
- testbed/testbed/load_generator.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_resource.go
- translator/internaldata/oc_to_traces.go
- translator/internaldata/oc_to_traces_test.go
- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerthrift_to_traces.go
Some benchmark runs *before*:
```
BenchmarkProtoBatchToInternalTraces-12        497078          2312 ns/op        2096 B/op         35 allocs/op
BenchmarkOcNodeResourceToInternal-12          698066          1889 ns/op        1304 B/op         17 allocs/op
BenchmarkSpansWithAttributesOCToInternal-12       282246          4596 ns/op        2328 B/op         30 allocs/op
BenchmarkMetricHistogramOCToInternal-12       363352          3540 ns/op        3544 B/op         59 allocs/op
```
Benchmark runs *after*:
```
BenchmarkProtoBatchToInternalTraces-12        646017          1737 ns/op        2064 B/op         32 allocs/op
BenchmarkOcNodeResourceToInternal-12         1075398          1126 ns/op        1152 B/op         13 allocs/op
BenchmarkSpansWithAttributesOCToInternal-12       305158 …
```
> Preset capacity for ApptibuteMap and StringMap to improve performance

- CODEOWNERS
- README.md
Dmitrii has been actively working on the Collector and has
already contributed 23 commits, most of them quite substantial.
I vouch for him.
> Add dmitryax as an approver

- README.md
I chatted with sjkaris and he is currently not going to actively
contribute to the Collector so he will not need the "approver" role.
Removing for now and will add back when he decides to contribute
to the Collector again.
Thanks, sjkaris!
> Remove sjkaris from README's Approvers list

- consumer/pdata/common.go
- consumer/pdata/common_test.go
- exporter/loggingexporter/logging_exporter.go
- internal/processor/filterspan/filterspan.go
- processor/spanprocessor/span.go
- testbed/tests/trace_test.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/resource_to_oc.go
- translator/internaldata/traces_to_oc.go
- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerthrift_to_traces.go
- translator/trace/jaeger/traces_to_jaegerproto.go
I found that `Cap` is very strange when used in practice, for example #906. I would propose to use `Len` and comment the caveat that when iterating fewer elements may be available.
> Rename Cap to Len for maps

- translator/trace/jaeger/traces_to_jaegerproto.go
- translator/trace/jaeger/traces_to_jaegerproto_test.go
Benchmark results:
Before:
```
BenchmarkInternalTracesToJaegerProto-12       611580          1696 ns/op        2952 B/op         17 allocs/op
```
After:
```
BenchmarkInternalTracesToJaegerProto-12       837252          1299 ns/op        2024 B/op         13 allocs/op
```
> Improve performance of internal traces to jaeger proto translation

- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/factory_test.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_constants.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_linux.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/factory_test.go
- Include all relevant cpu states for Linux when collecting cpu times data
- Remove windows only restriction from host metrics receiver
> Support any OS in host metrics receiver

- config/config.go
- config/config_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/888
> Allow config.Load to load partial config

- config/configgrpc/configgrpc_test.go
- receiver/securereceiverconfig_test.go
https://github.com/open-telemetry/opentelemetry-collector/issues/854
Updated a couple of tests that targeted `unix` specific code to use the `syscall` package instead so they work regardless of the platform. Note there are still a number of tests that fail on windows, but these two were particularly frustrating as they caused build failures (of the test code) which affected some linting commands. See the linked issue for more details.
> Remove code targeting Unix in tests

- receiver/hostmetricsreceiver/example_config.yaml
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/hostmetrics_receiver.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_constants.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_linux.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_test.go
- receiver/hostmetricsreceiver/internal/testutils.go
Added memory scraper to the hostmetricsreceiver which uses gopsutil to collect memory used metric.
**Exported Metric on Windows:**
> Initial commit of host metrics memory scraper

- receiver/hostmetricsreceiver/internal/scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_constants.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_linux.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/factory.go
Minor cleanup:
- Removed unused `Type()` function
- Const label values don't need to be exported anymore
> Minor cleanup to Host Metrics receiver

- extension/README.md
Signed-off-by: Kevin Earls <kearls@redhat.com>
**Description:** This fixes 2 broken links in the extension/README.md
**Testing:** 
> Fix broken links to configuration examples

- receiver/hostmetricsreceiver/example_config.yaml
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_constants.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/factory_test.go
Added disk scraper to the hostmetricsreceiver which uses gopsutil to collect disk related metrics
> Initial commit of host metrics disk scraper

- testbed/testbed/test_case.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
Signed-off-by: Kevin Earls <kearls@redhat.com>
**Description:** This is part of the fix for issue #266.  It updates tests in testbed to use stretchr/testify/require rather then checking err and calling t.Fatal
**Link to tracking Issue:** #266 
**Testing:** There are no new tests
> Update tests to use stretchr/testify/require

- receiver/hostmetricsreceiver/example_config.yaml
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_constants.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go
Added filesystem scraper to the hostmetricsreceiver which uses gopsutil to collect file system usage related metrics
**Metrics on Windows:** (Unix systems will additionally show inodes metrics)
> Initial commit of host metrics filesystem scraper

- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_constants.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
Renamed disk scraper receive/transmit labels to read/write (this was just a typo before - receive/transmit was meant to be for network metrics rather than disk)
> Rename host metrics disk scraper receive/transmit labels to read/write

- processor/memorylimiter/memorylimiter.go
- processor/queuedprocessor/queued_processor.go
The service builder adds by default log tags for:
* kind (receiver, exporter, processor)
* type
* name
See https://github.com/open-telemetry/opentelemetry-collector/blob/master/service/builder/pipelines_builder.go#L155
> Remove unnecessary log tags from processors

- receiver/hostmetricsreceiver/example_config.yaml
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_constants.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go
Added network scraper to the hostmetricsreceiver which uses gopsutil to collect metrics related to network usage & the number of active tcp connections
**Exported Metrics:**
> Initial commit of host metrics network scraper

- Makefile
- receiver/jaegerreceiver/errors.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
**Description:** This pulls in one more function from Jaeger collector that deals more
directly with the HTTP request object. We need reference to HTTP request
object and we need a way to pass the request context on to the next
consumer.
**Testing:** Tested manually and added a test case
> Add support for client IP detection to Jaeger Thrift HTTP receiver

- obsreport/obsreport.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_test.go
https://github.com/open-telemetry/opentelemetry-collector/issues/918
Made the "transport" parameter that's used to set a corresponding attribute value optional for obsreport receiver functions. This parameter doesn't make sense for all receivers.
Also added a comment regarding using the internal data structure with the CountMetricPoints function.
> Minor changes to Obsreport

- testbed/tests/trace_test.go
The limits are set too low and sporadically fail when CI runs a bit slower
than usual. We normally set limits to 1.3x of observed maximum.
> Increase limits for TestTrace10kSPS/OpenCensus

- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/jaeger_agent_test.go
- receiver/jaegerreceiver/testdata/config.yaml
- receiver/jaegerreceiver/trace_receiver.go
This PR adds support for secure connections for gRPC remote sampling receiver used in Jaeger agent or delegated collector.
There is a breaking code change but also the configuration -
`receivers.jaeger.remote_sampling.fetch_endpoint` changes to `receivers.jaeger.remote_sampling.endpoint`.
Resolves #461 
> Support secure connections in Jaeger remote sampling gRPC receiver

- component/exporter.go
- component/processor.go
- component/receiver.go
- config/config.go
- config/config_test.go
- config/configmodels/configmodels.go
- config/example_factories.go
- consumer/consumer.go
- internal/data/log.go
- processor/cloningfanoutconnector.go
- processor/fanoutconnector.go
- service/builder/exporters_builder.go
- service/builder/exporters_builder_test.go
- service/builder/pipelines_builder.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
- service/builder/testdata/pipelines_builder.yaml
- service/service.go
We are planning on experimenting with logs data type in the Collector.
This commit introduces factories and components types for logs and
implements pipeline building for logs.
The data.Log struct is for now empty. We need to wait for OTLP protocol
to define the log data format and we will use it in data.Log.
data.Log is in internal package since logs support is experimental
and is not intended for public usage.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/957
> Add factories and component types to support logs data type

- .golangci.yml
- Makefile
- receiver/hostmetricsreceiver/internal/third_party/telegraf/win_perf_counters/LICENSE
- receiver/hostmetricsreceiver/internal/third_party/telegraf/win_perf_counters/kernel32.go
- receiver/hostmetricsreceiver/internal/third_party/telegraf/win_perf_counters/pdh.go
- receiver/hostmetricsreceiver/internal/third_party/telegraf/win_perf_counters/pdh_386.go
- receiver/hostmetricsreceiver/internal/third_party/telegraf/win_perf_counters/pdh_amd64.go
- receiver/hostmetricsreceiver/internal/third_party/telegraf/win_perf_counters/performance_query.go
- receiver/hostmetricsreceiver/internal/third_party/telegraf/win_perf_counters/win_perf_counters_integration_test.go
- receiver/hostmetricsreceiver/internal/third_party/telegraf/win_perf_counters/win_perf_counters_notwindows.go
- receiver/hostmetricsreceiver/internal/windows/pdh/performance_counter.go
- receiver/hostmetricsreceiver/internal/windows/pdh/performance_counter_notwindows.go
- receiver/hostmetricsreceiver/internal/windows/pdh/performance_counter_test.go
- receiver/hostmetricsreceiver/internal/windows/pdh/performance_counter_utils.go
- receiver/hostmetricsreceiver/internal/windows/pdh/performance_counter_utils_test.go
Brings the [telegraf](https://github.com/influxdata/telegraf) [win_perf_counters](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/win_perf_counters) input plugin into a "third_party" folder. The code has been brought in as is (other than removing some code/files to avoid pulling in additional Telegraf dependencies) and includes a copy of Telegraf's MIT license. Also note that the code from Telegraf includes code copied from another repo (a predecessor of [win](https://github.com/lxn/win)), and so the source code references their license as well.
The reason for copying the code into the repo instead of referencing it directly is to avoid bringing in all of Telegraf and its many dependencies. See relevant previous discussion here: …
> Added third party code for accessing Windows performance counters

- translator/internaldata/oc_to_traces.go
- translator/internaldata/oc_to_traces_test.go
OpenCensus go instrumentation uses 8-bytes array internally https://github.com/census-instrumentation/opencensus-go/blob/master/trace/export.go#L76, and before exporting it in OC format the array is converted to slice https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/transform_spans.go#L44. As a result root spans are exported with ParentSpanID set to 8 byte slices with all zero values. 
This commit makes the OC->Internal trace convertor skip those values and align such spans with internal representation of a root span which supposed to have ParentSpanID set to nil instead.
> Do not pass zeroed parent span id from OC receiver

- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/opencensusexporter/factory.go
- receiver/opencensusreceiver/opencensus_test.go
- receiver/otlpreceiver/otlp_test.go
Fixes several unit tests that were failling on Windows:
1. `configgrpc`, `configgrpc_test` & `opencensusexporter.factory`: On Windows, calling `x509.SystemCertPool()` directly returns an error (see the discussion here https://github.com/golang/go/issues/16736), but as per the documentation, leaving `TLSConfig.RootCAs` as `nil` will still correctly validate certificates against the system cert pool. Fixing the failing tests on Windows required some minor code changes so that we never load the system cert pool, and just rely on `RootCAs` being `nil` instead. This made an existing test that checked if the call to `x509.SystemCertPool()` failed redundant.
2. `configgrpc_test`: Generalised a couple of checks against expected errors so they will pass on Windows (due to slightly …
> Fix unit tests on Windows

- receiver/hostmetricsreceiver/config_test.go
- receiver/hostmetricsreceiver/example_config.yaml
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_constants.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows_test.go
- receiver/hostmetricsreceiver/internal/windows/pdh/performance_counter.go
- receiver/hostmetricsreceiver/internal/windows/pdh/performance_counter_mock.go
- receiver/hostmetricsreceiver/testdata/config.yaml
Added load scraper to the hostmetricsreceiver which:
- On Unix-based systems, uses gopsutil to collect load metrics
- On Windows, samples the "Processor Queue Length" performance counter over 5s intervals and computes similar load averages (similar to what psutil does)
**Metrics:**
> Added cpu load scraper

- go.mod
Update go.mod as per `go mod tidy`. A direct reference to `golang.org/x/sys` was introduced in https://github.com/open-telemetry/opentelemetry-collector/pull/953
> Update go.mod 

- processor/README.md
**Description:** Fix incomplete sentence in the README of the `send_batch_size` configuration option (batch processor).
**Testing:** 
> Fix incomplete sentence on the batch processor

- processor/resourceprocessor/resource_processor.go
- processor/resourceprocessor/resource_processor_test.go
**Description:** The `resource` processor panics if the `Labels` field on a consumed resource is `nil`. Handled this gracefully by initializing the field if it is `nil`.
**Testing:** Added unit test.
> resourceprocessor: Don't panic when consumed resource has nil labels

- translator/trace/zipkin/status_code.go
- translator/trace/zipkin/status_code_test.go
Problem: 
If any zipkin span attribute that is used as source for setting OC status code (like `status.code`, `http.status_code` or `census.status_code`) received with a type other than int64, the underlying value will be taken as an integer. For example if http.status_code sent as "200" string attribute it's got converted to status code = 2. 
The problem wasn't that critical until we started setting error tag based on status code https://github.com/open-telemetry/opentelemetry-collector/commit/75ae9198a89eb9df1d14308c89c2a4c93b6ba9e1 
This commit adds support of string values in status.code, http.status_code or census.status_code attributes and reject values of other types.
> Fix zipkin receiver status code conversion

- testutils/testutils.go
On Windows, there is a significant wait when connecting to a local port that is not active. That causes the `testutils.GetAvailablePort` function, which has an assumption that a call to `net.Dial` will be very quick, to take much longer than the expected 5s (around 1 min).
See related discussion here: https://github.com/golang/go/issues/23366
Re-implemented using a ticker with timeout channel so the function will terminate after 5s regardless of the number of attempts that were able to be made in that period.
> Fix for testutils.GetAvailablePort on Windows

- examples/k8s.yaml
As is, the example k8s agent fails to deploy, going into a CrashLoopBackoff:
```
{"level":"info","ts":1589972770.1904275,"caller":"builder/exporters_builder.go:95","msg":"Exporter started.","component_kind":"exporter","component_type":"otlp","component_name":"otlp"}
Error: cannot setup pipelines: cannot build pipelines: error creating processor "memory_limiter" in pipeline "traces": checkInterval must be greater than zero
2020/05/20 11:06:10 Application run finished with error: cannot setup pipelines: cannot build pipelines: error creating processor "memory_limiter" in pipeline "traces": checkInterval must be greater than zero
```
**Testing:** 
I created a completely empty minikube and tried to apply k8s.yml from master. With this change, the agent becomes ready. …
> Add missing checkInterval to k8s deployment config

- receiver/hostmetricsreceiver/hostmetrics_receiver.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
Minor change to the host metrics receiver to not rely on the context provided in the Start method to determine when the host metrics ticker function should be terminated.
Addresses https://github.com/open-telemetry/opentelemetry-collector/pull/974#discussion_r426889598
> Change host metrics shutdown to use done channel

- .circleci/config.yml
Also moved the persist_to_workspace call out of restore_module_cache to not overwrite it from windows build.
> Enforce publish to wait for windows, use arch in cache key

- go.mod
This was removed before but found its way back in. I'm hoping keeping it
included with // indirect but changing it to pin to sha1 will prevent it from
getting clobbered again. Added note explaining why it's pinned the way it is.
> change k8s.io/client-go version to sha1

- service/builder/exporters_builder.go
- service/builder/receivers_builder.go
Resolves: https://github.com/jaegertracing/jaeger/issues/2252
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/294
Just fixing the log message. The warn level was printing stacktrace what was confusing for users.
> Unify log message when exporter or receiver is not registered

- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
- receiver/otlpreceiver/otlphttp.go
**Description:** This change adds application/x-protobuf support to the existing
grpc-gateway mux in the OTLP receiver.
(This change is a duplicate of #982 because CircleCI wasn't working.)
Protocol spec: https://github.com/open-telemetry/oteps/blob/master/text/0099-otlp-http.md
What currently works:
* The receiver will correctly process HTTP requests with the
Content-Type application/x-protobuf.
* The receiver will respond with Content-Type application/x-protobuf.
* The receiver will respond with status code HTTP 200 OK on success.
* The receiver can handle gzip-encoded requests (Content-Encoding
gzip) (http.Server natively supports gzip decoding).
What doesn't work yet:
* The receiver will not gzip-encode responses to requests with
Accept-Encoding: gzip.
**Link to tracking Issue:** #881 …
> Implement OTLP/HTTP X-Protobuf Receiver

- ADOPTERS.md
**Description:** The goal is to understand who is using the OpenTelemetry Collector in
production. Other CNCF projects have taken a similar approach to
highlight adoption.
**Documentation:** Create page and adding AppDirect pending their approval.
> Add AppDirect to adopters page

- service/service.go
- service/service_test.go
The client code that extends service should have access to the service's logger instance. 
> Expose service's logger

- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows_test.go
Added separate benchmark test for the load sampler which runs in the background on windows
> Added benchmark test for hostmetrics load sampler (windows)

- internal/processor/filterset/config.go
- internal/processor/filterspan/config.go
- internal/processor/filterspan/filterspan.go
- internal/processor/filterspan/filterspan_test.go
- processor/README.md
- processor/attributesprocessor/attributes_test.go
- processor/attributesprocessor/config_test.go
- processor/spanprocessor/config_test.go
- processor/spanprocessor/span_test.go
The MatchSpan interface is used by the attributes/span processor,
however this change does not change the yaml configuration or behavior,
just implementation.
FilterSet has the same filtering logic as MatchSpan previously had, but operates more
generically on just strings instead of spans and adds some additional
options, such as caching.
**Link to tracking Issue:** Side effect of #560 to help keep metrics and trace processors using matching configs the same.
**Testing:** unit tests updated, no new behavior, just implementation swapout
> Make MatchSpan implementation use FilterSet package

- service/service.go
- service/service_test.go
> Expose service's status channel

- exporter/README.md
Fix Jaeger exporter documentation: `insecure` instead of `secure`
**Link to tracking Issue:** #1049
**Testing:** try configuration with `exporters/jaeger/secure: false` then with exporters/jaeger/insecure: true`
**Documentation:** change documentation from `secure` to `insecure`.
> Fix #1049 Jaeger exporter docs: `insecure` instead of `secure`

- internal/data/testdata/metric.go
- internal/data/testdata/metric_test.go
- processor/README.md
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
- processor/batchprocessor/factory.go
- processor/batchprocessor/factory_test.go
**Description:** Add the ability to batch metrics as a processor.
**Testing:** Added test for batching of metrics
**Documentation:** Updated the docs.
> Add the ability to batch metrics as a processor.

- obsreport/obsreport_test.go
The goal is to prevent inadvertent changes of the labels. Using hard coded values requires manual changes of the tests.
Part of complete the switch to the new metrics, see #1082
**Link to tracking Issue:** #1082
> Hard code expected labels on obsreport tests

- processor/filterprocessor/factory.go
- processor/filterprocessor/factory_test.go
- service/defaultcomponents/defaults.go
- service/defaultcomponents/defaults_test.go
Add filter processor as a default processor.
Change trace processor to be old format so the filterprocessor correctly implements the old processor factory interface, otherwise there will be runtime errors.
**Link to tracking Issue:** part of #560
> Enable filter processor as a default processor

- examples/demo/otel-collector-config.yaml
**Description:** From the TLS refactor, connections are by default secure so they will fail in local scenarios. The docker compose example wasn't updated apart of the refactor. 
The k8s example is up to date and accurate.
**Link to tracking Issue:** Address issue seen in #1075 
**Testing:** Ran the docker compose environment locally and checked for metrics at localhost:8889/metrics
**Documentation:** N/aA
> Fix collector config to use insecure option in docker example

- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows_test.go
- receiver/hostmetricsreceiver/internal/windows/pdh/performance_counter_mock.go
There is a chance that the hostmetrics scrape ticker may run one last time after the receiver has been shutdown. On shutdown, don't set the load scraper instance to `nil`. This means stale values will be read on the last tick instead of raising an error. This also allows the tests to be improved somewhat.
> Prevent chance of panic on shutdown of load scraper

- exporter/loggingexporter/logging_exporter.go
Fixing a bug - enable metrics' debug logging in Logging Exporter
**Link to tracking Issue:** Fixes #1107
**Testing:**
Manual testing: simply run a collector with `--log-level=DEBUG` and the following config:
```yaml
receivers:
prometheus:
config:
scrape_configs:
- job_name: "test"
scrape_interval: 60s
static_configs:
- targets: ["localhost:8888"]
exporters:
logging:
loglevel: debug
service:
pipelines:
metrics:
receivers: [prometheus]
exporters: [logging]
```
The log now includes detailed information at the `DEBUG` level:
```
2020-06-11T14:13:08.697+1000	INFO	loggingexporter/logging_exporter.go:169	MetricsExporter	{"#metrics": 4}
2020-06-11T14:13:08.697+1000	DEBUG	loggingexporter/logging_exporter.go:213	ResourceMetrics #0
Resource labels:
-> port: STRING(8888)
-> scheme: …
```
> Add missing logging for metrics at 'debug' level

- processor/filterprocessor/config.go
- processor/filterprocessor/filter_processor.go
- processor/filterprocessor/filter_processor_test.go
It's mostly to see if CIrcleCI hooks will be triggered. It doesn't work for me in another PR: https://github.com/open-telemetry/opentelemetry-collector/pull/1105
> Remove year from copyright header

- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerproto_to_traces_test.go
Bug description: if "http.status_code" and "error" tags are both set in incoming a jaeger span, internal status code is incorrectly set to Unknown code ignoring value from http.status_code tag. This commit fixes the described bug, so http.status_code tag always has precedence over error tag during Jaeger -> Internal data model translation.
**Testing:** added more test cases to cover the bug.
> Fix setting internal status code in jaeger receivers

- exporter/zipkinexporter/zipkin.go
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
- translator/trace/zipkin/attributekeys.go
- translator/trace/zipkin/protospan_to_zipkinv1.go
- translator/trace/zipkin/zipkinv1_to_protospan.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/954
#954 is being caused from the conversion of OC -> Internal -> OC span types. 
OC technically allows nil times because its a pointer, but [docs state](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/trace/v1/trace.proto#L125-L135)
```go
// This field is semantically required. When not set on receive -
// receiver should set it to the value of end_time field if it was
// set. Or to the current time if neither was set. It is important to
// keep end_time > start_time for consistency.
//
// This field is required.
StartTime *timestamp.Timestamp
```
So this pr changes the zipkin receiver to set the start/end timestamps if they're not set on receive
> Zipkin Receiver: default timestamp

- testbed/testbed/test_case.go
If ResourceCheckPeriod is more than 1 second, reported resource values are not being changed during each ResourceCheckPeriod, so logging every second doens't provide much value, but makes it hard to read logs in long run running tests
> Use ResourceCheckPeriod as logging intervals in test bed

- exporter/exporterhelper/constants.go
- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/logshelper_test.go
- exporter/otlpexporter/README.md
- exporter/otlpexporter/exporter.go
- exporter/otlpexporter/factory.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- go.sum
- internal/data/testdata/log.go
- internal/data/testdata/log_test.go
- observability/observability.go
- observability/observabilitytest/observabilitytest.go
- obsreport/obsreport_exporter.go
The GRPC service was already defined in a previous PR.
This is still experimental.
> Add Log Support to OTLP Exporter

- config/config.go
- config/config_test.go
- config/testdata/simple-config-with-escaped-env.yaml
Adding a feature - Support escaping env var substitution in the collector config, e.g. `$$FOO_BAR` -> `$FOO_BAR`
Fixes #1112
Fixes #1077
**Testing:** Unit test added. No existing tests should be broken
**Documentation:** TODO: is there an existing documentation for env var substitution in the config?
> Add support for escaping env var substitution via $$

- exporter/prometheusexporter/prometheus.go
- exporter/prometheusexporter/prometheus_test.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/1076.
Signed-off-by: Liam White <liam@tetrate.io>
> Handle overlapping metrics from different jobs in prometheus exporter

- Makefile
These are useful targets for contrib. Adding them to this repo so we can have a unified release process. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/336
> Adds add-tag and delete-tag targets to have parity with the contrib repo

- testbed/tests/metric_test.go
- testbed/tests/trace_test.go
A few perf tests are recently failing once in a while on CircleCI.
I checked the commit history and was unable to identify a commit
that may have caused a regression. The failures are happening
randomly and the only conclusion I can make is that CircleCI is
a bit slower than usual and these tests have limits that are too
tight.
I am increasing the limits to avoid the intermittent CI failures.
> Increase resource limits for some perf tests

- exporter/otlpexporter/exporter.go
- exporter/otlpexporter/otlp_test.go
This change ensures the configured headers for the otlp exporter are sent in export requests to the backends.
Added a unit test to validate change works.
No documentation was added, the headers configuration option was already documented.
> otlpexporter: send configured headers in request

- examples/k8s.yaml
- examples/otel-local-config.yaml
Addresses #1019
Also add debug logging to local config YAML
> Fix k8s config

- testbed/tests/metric_test.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
**Description:** Adjusted scenario test function signatures so TestResultsSummary always gets passed in. This enables scenario functions currently reused in opentelemetry-collector-contrib to work correctly with TestResultsSummary instances created in that project.
**Testing:** All testbed tests are still passing.
> Adjusted test signatures to support tests in contrib project

- translator/internaldata/oc_to_traces.go
- translator/internaldata/oc_to_traces_test.go
- translator/internaldata/traces_to_oc.go
- translator/internaldata/traces_to_oc_test.go
- translator/trace/protospan_translation.go
Added setting of span attribute "span.kind" to "internal" when translating from OTLP to OC and translate back to SpanKindINTERNAL when translating from OC to OTLP.
**Link to tracking Issue:** #1136 #754
**Testing:** All tracing correctness tests involving only otlp and opencensus receivers and exporters now report a zero failure count.
> Fix handling of SpanKind INTERNAL in OTLP OC translation

- docs/monitoring.md
- internal/collector/telemetry/telemetry.go
- service/service_test.go
This change switches the defaults between "new-metrics" and "legacy-metrics".
Now the defaults are:
- "new-metrics" ON by default
- "legacy-metrics" OFF by default
- "add-instance-id" ON by default
**Link to tracking Issue:** Third item on https://github.com/open-telemetry/opentelemetry-collector/issues/1082
**Testing:** Added test to enforce the "service_instance_id" label ON by default.
**Documentation:** Updated `monitoring.md` to reflect that the "new-metrics" are on by default.
> Enable "new-metrics" by default

- go.mod
- testbed/testbed/child_process.go
- testbed/testbed/data_providers.go
- testbed/testbed/load_generator.go
- testbed/testbed/mock_backend.go
- testbed/testbed/mock_backend_test.go
- testbed/testbed/test_case.go
- testbed/tests/e2e_test.go
- testbed/tests/metric_test.go
- testbed/tests/scenarios.go
* Use atomic wrappers for readability and for preventing accidentally accessing atomic variables
non-atomically.
* Enhance readability of large numbers in testbed by formatting with thousands separator.
* Include rate per second in testbed output.
---
New output looks like:
```
2020/06/22 14:03:09 Starting load generator at 10000 items/sec.
2020/06/22 14:03:12 Agent RAM (RES):   1 MiB, CPU: 0.0% | Sent:   186,200 items | Received:   186,200 items (62,078/sec)
2020/06/22 14:03:15 Agent RAM (RES):  36 MiB, CPU:24.9% | Sent:   396,200 items | Received:   396,200 items (66,040/sec)
2020/06/22 14:03:18 Agent RAM (RES):  36 MiB, CPU:24.7% | Sent:   606,200 items | Received:   606,200 items (67,359/sec)
2020/06/22 14:03:21 Agent RAM (RES):  36 MiB, CPU:25.3% | Sent:   816,200 items | Received: …
```
> testbed improvements

- exporter/zipkinexporter/README.md
- exporter/zipkinexporter/config.go
- exporter/zipkinexporter/config_test.go
- exporter/zipkinexporter/testdata/config.yaml
- exporter/zipkinexporter/zipkin.go
> [BREAKING CHANGE] Remove `export_resource_labels` flag from Zipkin exporter

- .github/CODEOWNERS
@james-bebbington made a lot of contributions to the core collector and reviews see https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Ajames-bebbington+is%3Aclosed+
> Add james-bebbington as approver and remove songy23

- config/config_test.go
- config/configmodels/configmodels.go
- config/configprotocol/configprotocol.go
- config/configprotocol/empty_test.go
- config/configtls/configtls.go
- config/configtls/configtls_test.go
- config/example_factories.go
- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/opencensusreceiver/config.go
- receiver/opencensusreceiver/config_test.go
- receiver/opencensusreceiver/factory.go
- receiver/opencensusreceiver/factory_test.go
- receiver/otlpreceiver/config.go
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/factory_test.go
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/factory.go
- receiver/prometheusreceiver/testdata/config.yaml
- receiver/prometheusreceiver/testdata/config_env.yaml
- receiver/zipkinreceiver/config_test.go
- receiver/zipkinreceiver/factory.go
The configuration is backwards compatible except `Prometheus` receiver which defined an `Endpoint` but never used that.
TLSServerSetting was added in preparation to support proper mtls, and since this PR touches all the structs that use TLSSetting it was a good opportunity to avoid touching same files twice.
> Add protocol server settings and remove endpoint from ReceiverSettings

- processor/attributesprocessor/README.md
- processor/attributesprocessor/attributes.go
- processor/attributesprocessor/attributes_test.go
- processor/attributesprocessor/config.go
- processor/attributesprocessor/factory.go
- processor/attributesprocessor/factory_test.go
- processor/attributesprocessor/testdata/config.yaml
**Description:** Note: All of the cudos go to @dneray for the logic/testing/effort in https://github.com/open-telemetry/opentelemetry-collector/pull/981
This pr is based off of it with the following modifications
- The config looks like
```
- key : <key to use for applying the rule too>
pattern: <the regex pattern with named submatchers>
action: extract
```
I think that the original PR is going in the right way for what we can the internal logic to be but as the issue #979 and #1170 indicate we need to take a step back and redesign the attributes processor (or make it clear of its limitations).  This pr unblocks the required functionality. 
**Link to tracking Issue:** #979 
**Link to follow up issue:** #1170 
**Testing:** Added tests for extracting.
**Documentation:** Updated processor …
> Continue attribute regex support from PR 981

- config/confignet/confignet.go
- config/confignet/confignet_test.go
This target definition will be used for all the protocols except gRPC which has its own definition for target https://github.com/grpc/grpc/blob/master/doc/naming.md
Will change HttpClientSettings to use this definition after it gets merged.
> Add a NetAddr that can be used for HTTP or other protocols

- config/configgrpc/configgrpc.go
- config/configtls/configtls.go
- config/configtls/configtls_test.go
- exporter/jaegerexporter/exporter_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/opencensusreceiver/config.go
- receiver/otlpreceiver/config.go
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/1184
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/963
> mTLS: Add support to configure client CA and enforce ClientAuth

- component/componenttest/nop_host_test.go
- config/config_test.go
- exporter/prometheusexporter/prometheus_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/prometheusreceiver/internal/ocastore_test.go
- testutils/testutils.go
- translator/trace/jaeger/jaegerthrift_to_protospan_test.go
- translator/trace/zipkin/protospan_to_zipkinv1_test.go
- translator/trace/zipkin/zipkinv1_thrift_to_protospan_test.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
* Removes most of `t.Fatal` usages in tests in favor of `stretchr/testify/require`
* Additionally adds a `t.Run` for table tests in `config/config_test.go` for cleaner test output
**Link to tracking Issue:** #266 
> Use stretchr/testify/require instead of t.Fatal (#266)

- go.sum
- receiver/prometheusreceiver/DESIGN.md
- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
Made `textparse.MetricTypeUnknown` metrics convert to `gauge` by default to fix a Prometheus Receiver bug where `untyped` metrics were being dropped.
Issue link with much more details: https://github.com/open-telemetry/opentelemetry-collector/issues/1103
**Testing:**
Modified the tests for the new type the metrics are being converted to.
Added a small line in the design documentation stating that we default `untyped` metrics to `gauge`
Thanks @asuresh4 and @bogdandrutu
> Fixed untyped Prometheus receiver bug, updated tests and updated Design.md

- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
- exporter/zipkinexporter/config.go
- exporter/zipkinexporter/config_test.go
- exporter/zipkinexporter/factory.go
- exporter/zipkinexporter/factory_test.go
- exporter/zipkinexporter/testdata/config.yaml
- exporter/zipkinexporter/zipkin.go
- exporter/zipkinexporter/zipkin_test.go
- receiver/zipkinreceiver/trace_receiver_test.go
- testbed/testbed/receivers.go
- testbed/testbed/senders.go
Breaking change for Zipkin config "url" -> "endpoint", this makes it consistent with others.
Depends on #1184
Side effects:
* Zipkin exporter supports tls and mtls now.
* Allow to configure Client Timeout.
>  Add config settings for Http Client, change Zipkin to use it.

- cmd/otelcol/main.go
- cmd/otelcol/main_others.go
- cmd/otelcol/main_windows.go
- service/logger.go
- service/service.go
- service/service_test.go
- service/service_windows.go
- service/service_windows_test.go
- service/telemetry.go
- service/testdata/otelcol-config-minimal.yaml
https://github.com/open-telemetry/opentelemetry-collector/issues/1119
When running the Collector on Windows, users will generally want to run this as a Windows service. It's not possible to just run a .exe directly as a Windows service, so some minor modifications needed to be made to the startup/service code.
This PR adds a separate main method on Windows (using build flags) that checks if the app is running interactively (i.e. invoked directly via the command line) vs running as a Windows service (i.e. invoked from service control manager).
If the executable is invoked from the command line, there are no changes to how the app is run. If the executable has been invoked from Windows service control manager, we call …
> Enable Collector to be run as a Windows service

- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/jaegerexporter/exporter.go
- exporter/jaegerexporter/exporter_test.go
- exporter/opencensusexporter/config_test.go
- exporter/opencensusexporter/factory.go
- exporter/opencensusexporter/factory_test.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/exporter.go
- exporter/otlpexporter/factory_test.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/opencensusreceiver/config.go
- receiver/opencensusreceiver/config_test.go
- receiver/opencensusreceiver/factory.go
- receiver/opencensusreceiver/factory_test.go
- receiver/otlpreceiver/config.go
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/factory_test.go
Backwards compatible change for the configuration.
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/1172
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1014
> Add a generic grpc server settings config, cleanup client config

- exporter/opencensusexporter/factory_test.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp_test.go
- exporter/zipkinexporter/zipkin_test.go
- extension/healthcheckextension/factory_test.go
- extension/healthcheckextension/healthcheckextension_test.go
- extension/pprofextension/factory_test.go
- extension/pprofextension/pprofextension_test.go
- extension/zpagesextension/factory_test.go
- extension/zpagesextension/zpagesextension_test.go
- receiver/jaegerreceiver/jaeger_agent_test.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/opencensusreceiver/factory_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/opencensusreceiver/octrace/opencensus_test.go
- receiver/opencensusreceiver/opencensus_test.go
- receiver/otlpreceiver/factory_test.go
- receiver/otlpreceiver/metrics/otlp_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/otlpreceiver/trace/otlp_test.go
- receiver/prometheusreceiver/internal/metrics_adjuster_test.go
- receiver/zipkinreceiver/trace_receiver_test.go
- service/service_test.go
- testbed/testbed/utils.go
- testutil/metricstestutil/metricsutil.go
- testutil/metricstestutil/metricsutil_test.go
- testutil/testutil.go
- testutil/testutil_test.go
- translator/trace/jaeger/jaegerthrift_to_protospan_test.go
To keep the consistency with *util naming in the repo and in the larger Go ecosystem.
Similarly moved metricsutils to metricutil.
Also shorten some of the very long file names in the testutil packages.
> Rename testutils to testutil

- service/service.go
- service/service_test.go
- service/telemetry.go
appTelemetryExporter is not an exported type and there is no way
override the default telemetry. Unexport this variable until
we decide to export the type or provide different implementations.
> Don't export application telemetry

- component/componenttest/docs.go
- component/componenttest/docs_test.go
- service/defaultcomponents/docs_test.go
componentdocs is used for testing reasons, merging the docs validation code into the test package helps other developers to discover the existence of it.
Rename VerifyComponentDocumentation for CheckDocs to help verbosity and have consistency with the other checker functions in the module.
> Merge componentdocs into componenttest

- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- receiver/opencensusreceiver/config_test.go
- receiver/opencensusreceiver/factory.go
- receiver/opencensusreceiver/factory_test.go
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/factory_test.go
Adding `ProtocolServerSettings` was a bit of a rush. We determined that `endpoint` has different meaning based on protocol, also not all the protocols support TLS.
In this PR we revert embedding `ProtocolServerSettings` in the GRPCServerSettings and make it consistent with HttpServerSettings.
Work left: Consistent config name for TLS settings `tls_settings` or `tls_credentials`.
> Do not embed ProtocolServerSettings in gRPC

- receiver/jaegerreceiver/factory.go
Support was removed in https://github.com/open-telemetry/opentelemetry-collector/pull/636 and the error will still be returned because we return an error for every unknown protocol.
> Remove unnecessary constant and check

- processor/samplingprocessor/tailsamplingprocessor/sampling/numeric_tag_filter_test.go
- processor/samplingprocessor/tailsamplingprocessor/sampling/string_tag_filter_test.go
Add missing unit tests to the currently implemented attribute filters (`stringAttributeFilter` and `numericAttributeFilter`)
This can be considered part of #226
**Testing:** 
N/A
N/A
> Add unit tests to attribute filters (#226)

- testbed/testbed/receivers.go
This change plus https://github.com/open-telemetry/opentelemetry-collector/pull/1212 and sending 8 concurrent requests from the testbed data generator improved from 16 -> 10 cpu usage.
> Use default configs for testbed receivers

- .circleci/check-links/README.md
- .circleci/check-links/check-links.sh
- .circleci/check-links/markdown-link-check
- .circleci/config.yml
Add custom `markdown-link-check` to ignore 429 responses.
Diff with https://github.com/tcort/markdown-link-check/blob/v3.8.1/markdown-link-check:
```
< const markdownLinkCheck = require('markdown-link-check');
---
> const markdownLinkCheck = require('./');
134,138d133
<             // workaround to ignore 429 responses (too many requests)
<             if (result.statusCode === 429) {
<                 result.status = 'ignored'
<             }
<
```
**Testing:**
Tested locally with `circleci` command line tool.
Updated .circleci/check-links/README.md.
> Update check-links to ignore 429 errors

- receiver/jaegerreceiver/config.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/testdata/bad_typo_default_proto_config.yaml
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
- testbed/testbed/receivers.go
- testbed/testbed/senders.go
This change is backwards compatible for configuration.
Allows more configs for HTTP and gRPC protocols and ensure consistency with OTLP and OpenCensus.
> Refactor jaeger receiver config to allow different configs for different protocols

- cmd/pdatagen/internal/base_structs.go
- consumer/pdata/generated_log.go
- consumer/pdata/generated_log_test.go
- consumer/pdata/generated_metrics.go
- consumer/pdata/generated_metrics_test.go
- consumer/pdata/generated_trace.go
- consumer/pdata/generated_trace_test.go
This makes it a bit more convenient to assemble data structures.
It is also congruent with the existing Go slice functionality with
the same name.
> Add Append to Generated pdata Structs

- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
https://github.com/open-telemetry/opentelemetry-collector/issues/958
Surprisingly this test can intermittently time out after 1s, presumably implying scraping could not complete within that time. Increase the maximum wait time to make this more reliable.
> Increase maximum wait time for hostmetrics tests

- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
- internal/data/testdata/metric.go
Log metric data points in logging exporter.
Currently only resource labels are being logged.
**Link to tracking Issue:** -
**Testing:** Unit tests + tested manually:
```
ResourceMetrics #0
Resource labels:
-> resource-attr: STRING(resource-attr-val-1)
InstrumentationLibraryMetrics #0
Metric #0
Descriptor:
-> Name: counter-int
-> Description: 
-> Unit: 1
-> Type: MONOTONIC_INT64
Int64DataPoints #0
Data point labels:
-> label-1: label-value-1
StartTime: 1581452772000000321
Timestamp: 1581452773000000789
Value: 123
Int64DataPoints #1
Data point labels:
-> label-2: label-value-2
StartTime: 1581452772000000321
Timestamp: 1581452773000000789
Value: 456
Metric #1
Descriptor:
-> Name: counter-double
-> Description: 
-> Unit: 1
-> Type: MONOTONIC_DOUBLE
DoubleDataPoints #0
Data …
```
> Log metric data points in logging exporter

- exporter/jaegerexporter/exporter.go
- exporter/opencensusexporter/opencensus.go
- exporter/otlpexporter/otlp.go
- exporter/zipkinexporter/zipkin.go
- processor/batchprocessor/batch_processor.go
This PR changes the batch processor to not ignore the errors returned by the exporters. It also adds more context to the messages, to make it clear which exporter failed.
> Handle errors in exporters

- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_metadata.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_fallback.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_test.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/1240
**Description:** Added processes scraper to scrape stats on aggregate process counts (as opposed to the existing process scraper which scrapes per process metrics)
> Added processes scraper

- .circleci/config.yml
Publish-dev job depends on both build and cross-compile, and the following error happens:
```
Concurrent upstream jobs persisted the same file(s) into the workspace:
- project/bin/otelcol_linux_amd64
Error applying workspace layer for job ebcd1ff3-534d-473e-be90-0a741430a588: Concurrent upstream jobs persisted the same file(s)
```
> Fix circleCI publish job

- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
- processor/batchprocessor/metrics.go
Add batch size metric (units send in a batch). This metric helps us to tune batch processor size. 
Related to https://github.com/jaegertracing/jaeger/issues/2165#issuecomment-651179655
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/662
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/1139
> Add batch size metric 

- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_metadata.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_linux.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/847
**Description:** Added disk merged metric (Linux only) & updated tests
> Added disk merged metric & updated tests

- exporter/exportertest/nop_exporter.go
- exporter/exportertest/sink_exporter.go
- exporter/exportertest/sink_exporter_test.go
- obsreport/obsreport.go
- obsreport/obsreport_processor.go
- obsreport/obsreport_receiver.go
- obsreport/obsreport_test.go
- processor/memorylimiter/factory.go
- processor/memorylimiter/factory_test.go
- processor/memorylimiter/memorylimiter.go
- processor/memorylimiter/memorylimiter_test.go
- processor/metrics.go
This adds the ability to use the memorylimiter process in log pipelines.
> Log Support for memorylimiter Processor

- exporter/loggingexporter/factory.go
- exporter/loggingexporter/factory_test.go
- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
This makes the loggingexporter able to output in a log pipeline.
> loggingexporter: Add Log Support

- cmd/otelcol/Dockerfile
An attempted fix for #1317. It _shouldn't_ be necessary, but obviously the image is _somehow_ being built without an execute bit on the `otelcol` binary!
Also this bumps the base alpine to 3.12 (3.9 is pretty old). Pretty much a no-op though, since the `ca-certificates` package hasn't changed much.
**Link to tracking Issue:** #1317
**Testing:**
```
$ make docker-otelcol                                                      
COMPONENT=otelcol /Applications/Xcode.app/Contents/Developer/usr/bin/make docker-component
GOOS=linux /Applications/Xcode.app/Contents/Developer/usr/bin/make otelcol
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcol_linux_amd64 -ldflags "-X go.opentelemetry.io/collector/internal/version.GitHash=7c2ba895  -X …
```
> Force execute bit on otelcol binary in Docker image

- internal/processor/attraction/attraction.go
- processor/attributesprocessor/config.go
- processor/resourceprocessor/README.md
- processor/resourceprocessor/config.go
- processor/resourceprocessor/config_test.go
- processor/resourceprocessor/factory.go
- processor/resourceprocessor/factory_test.go
- processor/resourceprocessor/resource_processor.go
- processor/resourceprocessor/resource_processor_test.go
- processor/resourceprocessor/testdata/config.yaml
- testbed/tests/resource_processor_test.go
This PR migrates resource processor to internal data model. 
Existing processor configuration is relevant only to OpenCensus format, so the configuration schema has to be changed. Taking this opportunity, this commit adds existing logic for attributes manipulation from attributes processor to resource processor. 
New config uses "attributes" field which represents actions that can be made on resource attributes. Supported actions: INSERT, UPDATE, UPSERT, DELETE, HASH, EXTRACT.
In order to migrate existing resource processor config:
1. Move key/values from "labels" field to "attributes" with action="upsert".
2. Add value from "type" field to "attributes" with key="opencensus.resourcetype"  and action="upsert".
Resolves: …
> Migrate Resource Processor to internal data model

- testbed/tests/trace_test.go
TraceNoBackend10kSPS/JaegerGRPC/NoMemoryLimit load test is flaky and often goes over 60%.  Looking through the history wasn't able to identify if something might cause a regression.
Resolves: https://github.com/open-telemetry/opentelemetry-collector/issues/1281
> Bump CPU limit for a TraceNoBackend10kSPS/JaegerGRPC load test

- receiver/hostmetricsreceiver/config_test.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/testutils.go
- receiver/hostmetricsreceiver/testdata/config.yaml
Remove cpu scraper `report_per_cpu` option (this can be removed in metric transform processor instead). Also update tests & improve test coverage
> Remove report per cpu config option

- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go
Ensure tcp connection value is provided for all states, even when count is 0. Also update tests & improve test coverage.
> Ensure tcp connection value is provided for all states, even when count is 0

- .circleci/config.yml
- internal/buildscripts/packaging/fpm/common.sh
- internal/buildscripts/packaging/fpm/deb/Dockerfile.test
- internal/buildscripts/packaging/fpm/deb/README.md
- internal/buildscripts/packaging/fpm/deb/build.sh
- internal/buildscripts/packaging/fpm/otel-collector.service
- internal/buildscripts/packaging/fpm/postinstall.sh
- internal/buildscripts/packaging/fpm/preinstall.sh
- internal/buildscripts/packaging/fpm/preuninstall.sh
- internal/buildscripts/packaging/fpm/rpm/Dockerfile.test
- internal/buildscripts/packaging/fpm/rpm/README.md
- internal/buildscripts/packaging/fpm/rpm/build.sh
- internal/buildscripts/packaging/fpm/test.sh
- Install `otel-collector` systemd service and run as `otel:otel` user:group
- Fixed bug that packaged `amd64` binary in the `arm64` packages
**Testing:**
- Add simple installation test scripts using systemd-in-docker images
- Updated `deb/README.md` and `rpm/README.md`
> Add basic systemd service to deb and rpm

- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/factory_test.go
- receiver/jaegerreceiver/config_test.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/factory_test.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/factory_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/receiverhelper/factory.go
- receiver/receiverhelper/factory_test.go
- service/defaultcomponents/defaults.go
- service/defaultcomponents/defaults_test.go
- testbed/testbed/receivers.go
Alternative for https://github.com/open-telemetry/opentelemetry-collector/pull/1333
> Add helper receiver factory to reduce boilerplate

- processor/resourceprocessor/resource_processor.go
Resource processor misses a wrapper of the output result into pdata.Metrics structure. It causes the result of the processor work to be dropped if there is a component working with the old data model downstream in the pipeline. There are no tests catching this at the moment. Hopefully we will open the new data interface for metrics and remove this wrapper soon.
> Wrap metrics going from resource processor in pdata.Metrics structure

- processor/batchprocessor/README.md
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
- processor/batchprocessor/config.go
- processor/batchprocessor/config_test.go
- processor/batchprocessor/splittraces.go
- processor/batchprocessor/splittraces_test.go
- processor/batchprocessor/testdata/config.yaml
This PR adds configuration property `enfoce_batch_size` to batch processor that ensures that batch size does not overflow the configured `max_batch_size`. The default value is `false` hence it does not change the default behavior. 
If the incoming batch size is bigger than available space in cached traces then the incoming batch is split into reaming size and size of the maximum batch size. The spans that would overflow the buffer are sent again in trace data over the channel. 
Resolves #1140
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/1020
**Testing:** < Describe what testing was performed and which tests …
> Fix overflowing batch size

- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
A minor API refactor to use a single batch in Jaeger receiver. 
@pjanotti could you please review? 
Fixes #579 
> Minor API refactor to use a single batch in Jaeger

- testbed/tests/scenarios.go
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/436 which cannot pass the loadtest
> Partially revert #1336 to check the theory for carbon performance downgrade

- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_others_test.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_test.go
- receiver/hostmetricsreceiver/internal/testutils.go
**Fix:** Boot time is returned from gopsutil in seconds - we need to convert this to nano-seconds.
Added test cases to ensure this value is set correctly in the generated metrics and to cover the case where the call to get boot time fails.
> Set start / boot time to nano-second value

- .circleci/config.yml
Fixes `Concurrent upstream jobs persisted the same file(s)` error when attaching workspace during release.
> Filter package files when presisting to workspace

- config/configgrpc/bearer_token.go
- config/configgrpc/bearer_token_test.go
- config/configgrpc/configgrpc.go
- config/configgrpc/configgrpc_test.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/testdata/config.yaml
This PR adds support for including a per-RPC authentication to gRPC settings. Initially, only "bearer" token has been added, but can be easily extended in the future based on real-world needs. The token can be read directly from the configuration file or from an external token file, such as the ones injected by Kubernetes into pods.
**Testing:** this was successfully tested with a custom processor, reading the bearer token from the context via `metadata.FromIncomingContext(ctx)`. Additionally, unit tests were added to this PR.
**Documentation:** the `config.yaml` reference file has been updated to include this new option.
> Added PerRPCCredentials for gRPC settings

- .circleci/config.yml
- .gitignore
- internal/buildscripts/packaging/fpm/Dockerfile
- internal/buildscripts/packaging/fpm/deb/README.md
- internal/buildscripts/packaging/fpm/deb/build.sh
- internal/buildscripts/packaging/fpm/rpm/README.md
- internal/buildscripts/packaging/fpm/rpm/build.sh
- internal/buildscripts/packaging/msi/make.ps1
We were not able to release yesterday because the release CI job failed.
It failed because two sibling jobs persisted the same file(s) (bin/*) to the workspace.
- This commit fixes the issue by storing the packaged collector in `dist/` instead of `bin/`.
- In addition to that, the commit also adds job to catch any issues that
might make the publish job fail two weeks down the line. It doesn't add any significant overhead. It just makes sure the job can run (no conflicting persisted files in workspace) and that the files expected by the real publish job are generated.
> Fix publish CI job and add check to make sure publish doesn't break

- .circleci/config.yml
- internal/buildscripts/packaging/msi/make.ps1
Renames the MSI from `otel-collector.msi` to `otel-collector-<version>-amd64.msi` at build time.
> Add version and arch to MSI filename

- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/logshelper_test.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/opencensusexporter/factory_test.go
- exporter/otlpexporter/README.md
- exporter/otlpexporter/config.go
- exporter/otlpexporter/config_test.go
- exporter/otlpexporter/factory.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/testdata/config.yaml
- processor/queuedprocessor/config.go
Changed only the OTLP exporter for the moment to use the new settings.
Timeout is enabled for all the exporters. Fixes #1193
There are some missing features that will be added in a followup PR:
1. Enforcing errors. For the moment added the Throttle error as a hack to keep backwards compatibility with OTLP.
2. Enable queued and retry for all exporters.
3. Fix observability metrics for the case when requests are dropped because the queue is full.
> Add support for queued retry in the exporter helper.

- internal/goldendataset/metric_gen.go
- internal/goldendataset/metric_gen_test.go
This is in support of issue #652 and in response to a request by the team to break up my last commit into smaller chunks. This is the first of those chunks.
We will need to generate MetricData content both for feeding to the testbed sender and for testing MetricData diff functionality which will be used for validation checking in the testbed.
> Add support for generating metric data for testing

- internal/goldendataset/metric_gen.go
- internal/goldendataset/metric_gen_test.go
- testbed/testbed/metric_diff.go
- testbed/testbed/metric_diff_test.go
This is in support of issue #652 and in response to a request by the team to break a large PR into smaller chunks.
This change allows us to diff MetricData, which will be required by the validation step in the testbed when checking for metric correctness.
> Add support for diffs of MetricData

- processor/resourceprocessor/resource_processor.go
Need to wrap metric before sending out from resource processor, wrapping was lost during this change https://github.com/open-telemetry/opentelemetry-collector/commit/afc47961e03ef146922151a7006e9f9c4fbf8efc
> Fix resource processor for old metrics

- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_metadata.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go
On Linux:
- Physical usage = Resident set size
- Virtual usage = Virtual memory size
On Windows:
- Physical usage = Working set size
- Virtual usage = Commit size (private virtual memory), aka. Page File Usage
From what I can tell, there is one difference in that Virtual Usage on Windows does not include shared virtual memory whereas on Linux it does, but I think these concepts are similar enough to use the same metric. WDYT @jrcamp?
> Record process physical & virtual memory stats separately

- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_metadata.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others_linux.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows_test.go
Added "disk.time" cumulative metric for Windows. Since there is no direct performance counter for this we compute it from:
`disk.time += delta(# operations) * avg secs/operation`
Also changed the unit for this metric to seconds, and standardised this for other OSs (was previously reported in `ms`).
**Windows Metrics:**
> Scrape system.disk.time on Windows

- exporter/zipkinexporter/README.md
- receiver/zipkinreceiver/README.md
**Description:** zipkin.io was down for a short period of time but it is fixed now ([click here](https://zipkin.io)).
**Documentation:** Brought back the links to the documentation as they were removed just yesterday by https://github.com/open-telemetry/opentelemetry-collector/pull/1417
Ping @bogdandrutu
> docs(zipkin): bring back zipkin.io as it is back after a very short unavailability

- receiver/jaegerreceiver/trace_receiver.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/437
> JaegerReceiver: Do not try to stop if failed to start. Collector service will do that

- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_metadata.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows_test.go
Adds `disk.pending_operations` metric.
On Windows this is the "Current disk queue length", obtained via a [perf counter](http://www.appadmintools.com/documents/windows-performance-counters-explained/) whereas on Linux this is the "I/Os currently in progress" value returned by [procfs/disktats](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats).
> Add disk.pending_operations metric

- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/otlpexporter/otlp_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1354
Changes in otlp_test are required because the fix of InitialInterval (5 second) will timeout requests that are sent with 4seconds timeout, so decided to make calls blocking.
> Fix some race conditions in queued retry tests, fix initial interval initialization

- exporter/otlpexporter/otlp_test.go
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/2284/workflows/8b1d2b7b-71d1-4f28-a1d8-92246fc9471e/jobs/18340/parallel-runs/0/steps/0-103
> Give more time for otlp gRPC server to start

- extension/fluentbitextension/README.md
- extension/fluentbitextension/config.go
- extension/fluentbitextension/config_test.go
- extension/fluentbitextension/factory.go
- extension/fluentbitextension/factory_test.go
- extension/fluentbitextension/process.go
- extension/fluentbitextension/process_linux.go
- extension/fluentbitextension/process_linux_test.go
- extension/fluentbitextension/process_others.go
- extension/fluentbitextension/testdata/config.yaml
- go.mod
- service/defaultcomponents/defaults.go
- service/defaultcomponents/defaults_test.go
This extension runs FluentBit as a subprocess and does some standard
configuration to make it talk to a fluentforward receiver running in the
same collector.
You still have to pass through the FluentBit config text but it makes
running FluentBit with the collector a bit easier.
Only the second commit is relevant for the extension.
> FluentBit Subprocess Extension

- internal/goldendataset/span_generator.go
- internal/goldendataset/span_generator_test.go
- translator/conventions/opentelemetry.go
Updates to latest semantic conventions.
I also made the span generator a copy of the examples on the semantic conventions document for easier maintenance, hope this makes sense.
> Update DB conventions to latest and add exception conventions

- receiver/hostmetricsreceiver/README.md
- receiver/hostmetricsreceiver/config_test.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_metadata.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go
- receiver/hostmetricsreceiver/testdata/config.yaml
Add network interface label to network metrics & added config option to filter by interface name
> Add network interface label to network metrics

- .circleci/config.yml
- Makefile
It just runs the latest master contrib tests against the HEAD of the given 
build to make sure none of the changes are incompatible.
It should not be a required check, but is meant to be a heads up to
contributors to fix the contrib repo after their PR is merged.
> Add CircleCI check for contrib repo breakage

- Makefile
- consumer/pdata/generated_log_test.go
- consumer/pdata/generated_metrics_test.go
- consumer/pdata/generated_trace_test.go
- internal/data/opentelemetry-proto-gen/collector/logs/v1/logs_service.pb.go
- internal/data/opentelemetry-proto-gen/collector/metrics/v1/metrics_service.pb.go
- internal/data/opentelemetry-proto-gen/collector/trace/v1/trace_config.pb.go
- internal/data/opentelemetry-proto-gen/collector/trace/v1/trace_service.pb.go
- internal/data/opentelemetry-proto-gen/common/v1/common.pb.go
- internal/data/opentelemetry-proto-gen/logs/v1/logs.pb.go
- internal/data/opentelemetry-proto-gen/metrics/v1/metrics.pb.go
- internal/data/opentelemetry-proto-gen/resource/v1/resource.pb.go
- internal/data/opentelemetry-proto-gen/trace/v1/trace.pb.go
This ensures that you can run 'make fmt' and not have to manually
fix a bunch of stuff that shouldn't be in a PR.
> Format Generated protobufs Properly

- translator/internaldata/resource_to_oc.go
- translator/internaldata/resource_to_oc_test.go
**Disclaimer**: I have initially tried to fix this issue for Stackdriver exporter only (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/581), but it seems generic enough to be part of the core.
Reverse mapping from [OpenTelemetry's semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions) to OpenCensus resource type.
Since OpenTelemetry has switched to using semantic conventions over explicit resource types, the resource type may now be missing when converted to OpenCensus resource.
In that case we will try to infer the resource type based on documented conventions.
The issue has been originally discussed in …
> Infer OpenCensus resource type based on OpenTelemetry's semantic conventions

- receiver/prometheusreceiver/README.md
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/testdata/config_k8s.yaml
Added a test for Prometheus receiver configured to scrape metrics from Kubernetes Pods.
Also includes check for environment variable substitution with escaping support.
**Testing:** Unit test
**Documentation:** README is also update to include a basic K8s config
> Add example and test for scraping Pod metrics with Prometheus receiver

- exporter/zipkinexporter/config_test.go
- exporter/zipkinexporter/factory.go
- exporter/zipkinexporter/factory_test.go
- exporter/zipkinexporter/zipkin.go
- exporter/zipkinexporter/zipkin_test.go
- receiver/zipkinreceiver/config_test.go
- receiver/zipkinreceiver/factory.go
- receiver/zipkinreceiver/factory_test.go
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
- service/builder/receivers_builder_test.go
- service/defaultcomponents/defaults.go
- testbed/testbed/receivers.go
- testbed/testbed/senders.go
Extracted from https://github.com/open-telemetry/opentelemetry-collector/pull/1446
> Migrate zipkin receiver/exporter to the new interfaces

- component/component.go
- component/componenttest/example_factories.go
- component/receiver.go
- component/receiver_test.go
- config/config.go
- config/config_test.go
- exporter/exporterhelper/factory.go
- exporter/exporterhelper/factory_test.go
- processor/processorhelper/factory.go
- processor/processorhelper/factory_test.go
- receiver/jaegerreceiver/factory_test.go
- receiver/opencensusreceiver/factory.go
- receiver/prometheusreceiver/factory.go
- receiver/receiverhelper/factory.go
- receiver/receiverhelper/factory_test.go
- service/builder/receivers_builder_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/882 - need custom unmarshaler for the exporter to allow multi protocols support.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/292
> Add new FactoryUnmarshaler support to all components, deprecate old way

- receiver/prometheusreceiver/internal/logger.go
- receiver/prometheusreceiver/internal/logger_test.go
Fixing a bug:
- deduplicate the "level" field in log messages coming from Prometheus
- use appropriate zap log level rather than always using `Info`
**Link to tracking Issue:** Fixes #1486
**Testing:** Added unit tests
**Documentation:** -
> Fix log adapter in Prometheus receiver

- testbed/correctness/correctness_test.go
- testbed/correctness/utils.go
This change makes these functions/types available from the metrics package, where they will be needed to address issue #652.
> Move some content from correctness_test.go to utils.go

- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_linux.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others_fallback.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others_linux.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_linux.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_unix.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_windows.go
- receiver/hostmetricsreceiver/internal/testutils.go
- receiver/hostmetricsreceiver/internal/utils.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/1271
Updated all metrics that come from the same source to use the same timestamp, calculated when scraping the system.
Note there are a couple of places where we get data from different sources within the same scraper which possibly indicates that these should be separated (will consider this change for a future PR):
1. `network`: Network Interface info is obtained separately from Connection Counts
2. `swap`: Swap / Page File Usage is obtained separately from Paging IO
(have not done `process` scraper yet, will do in a separate PR)
> Host scrapers: Use same scrape time for all data points coming from same source

- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
The Windows CI sees this test fail very occasionally, presumably because system metric collection is slow (lots of processes running or sys calls blocked for some reason). Try increasing the max wait time before resorting to anything more drastic.
Resolves: https://github.com/open-telemetry/opentelemetry-collector/issues/1445#issuecomment-668315543
> Increase max wait time on host metrics test

- cmd/pdatagen/internal/base_structs.go
- cmd/pdatagen/internal/log_structs.go
- consumer/pdata/generated_log.go
- consumer/pdata/generated_log_test.go
- consumer/pdata/log.go
- internal/data/testdata/log.go
It was previously available in internal package only.
Now we have the public alias for it.
This is consistent with how we treat other enums, e.g. SpanKind.
> Make logs SeverityNumber publicly available

- receiver/prometheusreceiver/config.go
- receiver/prometheusreceiver/config_test.go
- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
- receiver/prometheusreceiver/internal/ocastore.go
- receiver/prometheusreceiver/internal/ocastore_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/internal/transaction_test.go
- receiver/prometheusreceiver/metrics_receiver.go
- receiver/prometheusreceiver/metrics_receiver_test.go
- receiver/prometheusreceiver/testdata/config.yaml
Previously the prometheus receiver only accepts
`process_start_time_metric` as the start time when UseStartTimeMetric is
set. For applications that export similar metrics but with a prefix,
e.g., via NewProcessCollector(namespace), the receiver would drop such
metrics.
By adding StartTimeMetricRegex, at least we will be able to cover such
use cases.
related: #969 
**Testing:** Adds new unit tests and end-to-end test case in prometheus receiver.
**Documentation:** none.
> Adds a new config StartTimeMetricRegex

- cmd/otelcol/main.go
Cleanup: The characters "%v" are extraneous in this case since errors.Wrap appends the two strings together instead. Additionally, errors.Wrapf is not used, which means the %v is added to the logs incorrectly.
**Testing:** Re-compiled with change and the error log was correct.
**Documentation:** n/a
> Remove extraneous %v from interactive CLI logs

- internal/collector/telemetry/process_telemetry_test.go
TestProcessTelemetry/"process/cpu_seconds" was failing
because this particular metric is not supported  on Darwin.
This commit skips the test on Darwin.
> Fix TestProcessTelemetry on Darwin

- processor/README.md
- processor/groupbytraceprocessor/README.md
- processor/groupbytraceprocessor/config.go
- processor/groupbytraceprocessor/doc.go
- processor/groupbytraceprocessor/event.go
- processor/groupbytraceprocessor/event_test.go
- processor/groupbytraceprocessor/factory.go
- processor/groupbytraceprocessor/factory_test.go
- processor/groupbytraceprocessor/processor.go
- processor/groupbytraceprocessor/processor_test.go
- processor/groupbytraceprocessor/ring_buffer.go
- processor/groupbytraceprocessor/ring_buffer_test.go
- processor/groupbytraceprocessor/storage.go
- processor/groupbytraceprocessor/storage_memory.go
- processor/groupbytraceprocessor/storage_memory_test.go
- processor/groupbytraceprocessor/testdata/config.yaml
- service/defaultcomponents/defaults.go
- service/defaultcomponents/defaults_test.go
**Description:** This change adds a new 'groupbytrace' processor, as defined on #1309. This addresses the first item in the action plan.
**Link to tracking Issue:** #1309
**Testing:** extensive unit tests have been added
**Documentation:** sample configuration + readme added
> Implemented a "group by trace" processor.

- translator/trace/zipkin/protospan_to_zipkinv1.go
- translator/trace/zipkin/protospan_to_zipkinv1_test.go
Fixes a bug with service name being skipped when span contains no attributes
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/1480
**Testing:** Added unit test and tested manually
**Documentation:** No extra documentation added
> Always include Zipkin's localEndpoint serviceName

- processor/README.md
- processor/filterprocessor/filter_processor.go
- processor/filterprocessor/filter_processor_test.go
- processor/processorhelper/processor.go
- processor/processorhelper/processor_test.go
Add a sentinel error to `processhelper` package that can be returned by other processors to indicate that the incoming batch of metrics data has been determined to be irrelevant and should be skipped for any further processing. If skipped, `processhelper` will nullify the sentinel error and return `nil`. 
Have the filterprocessor return the sentinel error if all metrics are filtered out by the filters. This prevents any further unnecessary processing and exporting of the empty metrics data.
**Link to tracking Issue:** #1491 
**Documentation:** N/A, no user-facing changes to fix big (though I did fix some typos in existing doc).
> If filterprocessor filters all data, stop further processing

- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_linux.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_windows.go
Link to tracking Issue: #1271
Updated all metrics related to the same process to use the same timestamp.
> Process scraper: Use same scrape time for all data points coming from same process

- internal/goldendataset/metric_gen.go
- internal/goldendataset/metric_gen_test.go
- internal/goldendataset/pict_metric_gen.go
- testbed/correctness/metrics/metric_diff.go
- testbed/correctness/metrics/metric_diff_test.go
- testbed/testbed/child_process.go
- testbed/testbed/mock_backend.go
- testbed/testbed/otelcol_runner.go
- testbed/testbed/receivers.go
- testbed/testbed/senders.go
- testbed/testbed/test_case.go
This is in support of issue #652.
This change:
- Adds support for setting a prefix on every metric name for metrics generated for testing. Doing so will be necessary to distinguish metric names for metrics generated from different rows in a PICT file.
- Exports some fields and functions in the `correctness` package so that they can be used from the `metrics` subdirectory/package.
- Replaces argument types that refer to the struct `MockTraceConsumer` and `MockMetricsConsumer` with the interfaces `MetricsDualConsumer` and `TraceDualConsumer`, both of which can consume old and new metrics/traces. This will be used in a forthcoming `TestHarness` type that implements `MetricsDualConsumer`.
- Adds a `PrometheusDataReceiver` and a `PrometheusDataSender` so that Prometheus correctness can be …
> Add misc changes for metrics correctness

- exporter/kafkaexporter/README.md
- exporter/kafkaexporter/config.go
- exporter/kafkaexporter/config_test.go
- exporter/kafkaexporter/factory.go
- exporter/kafkaexporter/kafka_exporter.go
- exporter/kafkaexporter/kafka_exporter_test.go
- exporter/kafkaexporter/testdata/config.yaml
> Enable queueing, retry, timeout for Kafka exporter

- cmd/otelcol/Dockerfile
**Description:** Removes the workaround for issue #587 since it is not necessary anymore. There is risk in this change since some may have taken a dependency on it existing but it will keep things clean and we will be alerted if some other component is logging to that path.
**Link to tracking Issue:** Fixes #608 (technically it is already fixed but this will detect any other component logging to `/tmp`)
**Testing:** Manual validation using minikube
> Remove /tmp from docker image

- service/builder/pipelines_builder.go
Fixing a bug
While using more than one exporter the panic runtime exception occured,
because the array allocated for exporters was as twice as big as it should
**Testing:**
Using more than one exporter results with panic runtime error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x510ca95]
goroutine 108 [running]:
go.opentelemetry.io/collector/processor.LogFanOutConnector.ConsumeLogs(0xc0002c0d40, 0x4, 0x4, 0x88ab900, 0xc0002c10c0, 0xc00082a000, 0xc000c19880, 0x2)
.../processor/fanoutconnector.go:171 +0xb5
```
Signed-off-by: Dominik Rosiek <drosiek@sumologic.com>
> Fix multiple exporters panic

- exporter/prometheusremotewriteexporter/config.go
- exporter/prometheusremotewriteexporter/config_test.go
- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/factory.go
- exporter/prometheusremotewriteexporter/factory_test.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
- exporter/prometheusremotewriteexporter/testutil_test.go
This PR is part of a series of PRs implementing a Prometheus remote write exporter supporting Cortex. 
**Description:** This PR adds helper methods used by the exporter, including functionalities such as sanitizing strings and creating Prometheus labels from OTLP labels.
* [Design](https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/prometheusremotewriteexporter/DESIGN.md)
cc: @huyan0 @alolita 
Request for review: @jmacd @bogdandrutu @annanay25 @gouthamve @open-telemetry/collector-approvers @open-telemetry/collector-maintainers
> Add Prometheus Remote Write Exporter supporting Cortex - helper

- consumer/pdatautil/pdatautil.go
- exporter/opencensusexporter/config_test.go
- exporter/opencensusexporter/factory.go
- exporter/opencensusexporter/factory_test.go
- exporter/opencensusexporter/opencensus.go
- exporter/opencensusexporter/opencensus_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/opencensusreceiver/octrace/opencensus_test.go
- service/builder/exporters_builder_test.go
- service/defaultcomponents/defaults.go
- testbed/testbed/senders.go
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/1570
> Convert ocexporter to the new interfaces

- .circleci/config.yml
- internal/buildscripts/packaging/msi/make.ps1
Something seems to have changed with the CircleCI Windows executor recently. .NET 3.5 was pre-installed before and is not now.
The `choco install wixtoolset` command has a dependency on the `dotnet3.5` module which doesn't work (if it detects .Net 3.5 is not already installed) when trying to install in some situations. See related discussion here: https://chocolatey.org/packages/DotNet3.5#comment-4490487735
Therefore, have updated the script to install .NET 3.5 explicitly (and restored the `windows-msi` build step)
> Add command to install .Net 3.5 explicitly

- Makefile
This causes some tests to not run:
```
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcol_linux_amd64 -ldflags "-X go.opentelemetry.io/collector/internal/version.GitHash=a8f3d716  -X go.opentelemetry.io/collector/internal/version.BuildType=release" ./cmd/otelcol
cd ./testbed/tests && ./runtests.sh
-test.run=TestTrace10kSPS|ok|go.opentelemetry.io/collector/testbed/tests|0.025s
=== RUN   TestTrace10kSPS
--- PASS: TestTrace10kSPS (0.00s)
testing: warning: no tests to run
```
> Fix make list test commands to not inlude the last line

- exporter/prometheusexporter/prometheus_test.go
- internal/internal.go
- internal/internal_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/opencensusreceiver/opencensus_test.go
- receiver/prometheusreceiver/internal/metricfamily.go
- receiver/prometheusreceiver/internal/metrics_adjuster.go
- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/metricsbuilder_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/metrics_receiver_test.go
- testutil/metricstestutil/metricsutil.go
- testutil/metricstestutil/metricsutil_test.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/metrics_to_oc_test.go
- translator/internaldata/oc_testdata_test.go
- translator/internaldata/oc_to_resource.go
- translator/internaldata/oc_to_traces_test.go
- translator/internaldata/resource_to_oc.go
- translator/internaldata/traces_to_oc_test.go
- translator/trace/zipkin/zipkinv1_thrift_to_protospan.go
- translator/trace/zipkin/zipkinv1_to_protospan.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
The module "github.com/golang/protobuf" was deprecated and replaced by the "google.golang.org/protobuf".
> Convert to the new proto library usage all the time

- exporter/prometheusremotewriteexporter/DESIGN.md
Looks like Cortex docs API link was changed. Existing one throws 404 which blocks CI
> Update Cortex docs API link

- exporter/opencensusexporter/README.md
- exporter/otlpexporter/README.md
"reconnection_delay" config was removed some time ago, but some mentions in docs and examples still exist
> Remove mentions of non-existent "reconnection_delay" config

- examples/k8s.yaml
Currently containers are failing with: "Error: cannot load configuration: error reading receivers configuration for otlp: empty config for OTLP receiver"
> Fix OTLP receiver configuration in examples

- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_test.go
This PR fixes a bug that produces duplicate "filesystem" metric data points for linux devices that have more than one data point. For example:
```
{"device":"/dev/vda1","mountpoint":"/etc/resolv.conf","fstype":"ext4","opts":"rw,relatime"}
{"device":"/dev/vda1","mountpoint":"/etc/hostname","fstype":"ext4","opts":"rw,relatime"}
{"device":"/dev/vda1","mountpoint":"/etc/hosts","fstype":"ext4","opts":"rw,relatime"}
```
**Resolves:** https://github.com/open-telemetry/opentelemetry-collector/issues/1615
**Testing:** Added a unit test.
> Do not duplicate filesystem metrics for devices with many mount points.

- docs/release.md
github was 503'ing on the URL (presumably because the diff is so large now). Don't bother checking the link.
> fix link check

- CHANGELOG.md
- component/componenttest/example_factories.go
- component/exporter.go
- component/processor.go
- component/processor_test.go
- component/receiver.go
- component/receiver_test.go
- exporter/exporterhelper/factory.go
- exporter/exporterhelper/factory_test.go
- exporter/loggingexporter/factory_test.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp_test.go
- processor/memorylimiter/factory_test.go
- processor/processorhelper/factory.go
- processor/processorhelper/factory_test.go
- receiver/fluentforwardreceiver/factory_test.go
- receiver/otlpreceiver/factory_test.go
- receiver/receiverhelper/factory_test.go
- service/builder/exporters_builder.go
- service/builder/pipelines_builder.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
> Remove logs factories and merge with normal factories

- cmd/otelcol/main.go
- component/component.go
- component/componenttest/application_start_info.go
- component/exporter.go
- component/extension.go
- component/processor.go
- component/receiver.go
- service/builder/exporters_builder.go
- service/builder/exporters_builder_test.go
- service/builder/extensions_builder.go
- service/builder/pipelines_builder.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder.go
- service/builder/receivers_builder_test.go
- service/service.go
- service/service_test.go
- service/service_windows_test.go
- testbed/testbed/otelcol_runner.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/1559
Update service pipeline to pass ApplicationInfo into all new components as part of the `CreateParams` structs.
**Example Usage:** https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/758
> Pass version (& other app info) into components in params struct

- .circleci/config.yml
- testbed/testbed/data_providers.go
- testbed/testbed/load_generator.go
- testbed/testbed/mock_backend.go
- testbed/testbed/receivers.go
- testbed/testbed/senders.go
- testbed/tests/log_test.go
- testbed/tests/metric_test.go
- testbed/tests/resource_processor_test.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
This adds a simple 10k logs per second performance test that currently
passes with a fairly low bar.
This also involves adding support for logs to the otlpreceiver since it
is used to receive the logs by the mock backend.
Also expanding the receiverhelper to supportlog receiver factories.
> Add Logs to Test Bed

- exporter/kafkaexporter/README.md
- exporter/kafkaexporter/config.go
- exporter/kafkaexporter/config_test.go
- exporter/kafkaexporter/factory.go
- exporter/kafkaexporter/factory_test.go
- exporter/kafkaexporter/jaeger_marshaller.go
- exporter/kafkaexporter/jaeger_marshaller_test.go
- exporter/kafkaexporter/kafka_exporter.go
- exporter/kafkaexporter/kafka_exporter_test.go
- exporter/kafkaexporter/marshaller.go
- exporter/kafkaexporter/marshaller_test.go
- exporter/kafkaexporter/otlp_marshaller.go
- exporter/kafkaexporter/otlp_marshaller_test.go
- go.sum
- receiver/kafkareceiver/README.md
- receiver/kafkareceiver/config.go
- receiver/kafkareceiver/config_test.go
- receiver/kafkareceiver/factory.go
- receiver/kafkareceiver/factory_test.go
- receiver/kafkareceiver/jaeger_unmarshaller.go
- receiver/kafkareceiver/jaeger_unmarshaller_test.go
- receiver/kafkareceiver/kafka_receiver.go
- receiver/kafkareceiver/kafka_receiver_test.go
- receiver/kafkareceiver/otlp_unmarshaller.go
- receiver/kafkareceiver/otlp_unmarshaller_test.go
- receiver/kafkareceiver/unmarshaller.go
- receiver/kafkareceiver/unmarshaller_test.go
- receiver/kafkareceiver/zipkin_unmarshaller.go
- receiver/kafkareceiver/zipkin_unmarshaller_test.go
- service/defaultcomponents/defaults.go
This PR makes configurable encoding of Kafka message payloads. I have added support for Jaeger proto and JSON for both receiver and exporter and also Zipkin JSON and thrift for receiver to cover the functionality we had in Jaeger. This will allow users to migrate to the OTEL collector and also Jaeger project to use this new implementation directly. 
In addition to that additional encodings can be programmatically added via a registry. 
Resolves #1580 
Added to readme
> Make Kafka payload encoding configurable

- cmd/pdatagen/internal/common_structs.go
- consumer/pdata/common.go
- consumer/pdata/common_test.go
- consumer/pdata/generated_common.go
- consumer/pdata/generated_common_test.go
- go.sum
- translator/internaldata/resource_to_oc.go
- translator/internaldata/resource_to_oc_test.go
Array value type was added to AnyValue Protobuf definition but corresponding
support in the Collector was missing.
This commit adds AnyValueArray internal data type which wraps an a slice of
AnyValue pointers.
AnyValueArray supports minimal set of functions for now. We will add more
functions if needed in the future.
> Add minimal support for array value type

- exporter/loggingexporter/logging_exporter.go
Resolves #1454
Output not very intuitive and readable, but I just tried to follow existing conventions. Looks like following:
```
2020-08-06T16:18:37.528+0300  INFO  TraceExporter  {"#spans": 3}
2020-08-06T16:18:37.528+0300  DEBUG  ResourceSpans #0
Resource labels:
-> resource-attr: STRING(resource-attr-val-1)
InstrumentationLibrarySpans #0
Span #0
Trace ID       :
Parent ID      :
ID             :
Name           : operationA
Kind           : SPAN_KIND_UNSPECIFIED
Start time     : 2020-02-11 23:26:12.000000321 +0300 MSK
End time       : 2020-02-11 23:26:13.000000789 +0300 MSK
Status code    : Cancelled
Status message : status-cancelled
Events:
SpanEvent #0
-> Name: event-with-attr
-> Timestamp: 1581452773000000123
-> DroppedAttributesCount: 2
-> Attributes:
-> span-event-attr: …
```
> LoggingExporter: Add logging of span events and links

- receiver/kafkareceiver/README.md
- receiver/kafkareceiver/unmarshaller.go
- receiver/kafkareceiver/unmarshaller_test.go
- receiver/kafkareceiver/zipkin_unmarshaller.go
- receiver/kafkareceiver/zipkin_unmarshaller_test.go
Add support for Zipkin proto in Kafka receiver. 
Created from https://github.com/open-telemetry/opentelemetry-collector/pull/1584#issuecomment-679187515
some unit tests
Added to readme
> Support zipkin proto in Kafka receiver

- consumer/pdata/metric.go
- consumer/pdata/metric_test.go
- internal/data/metrics.go
- internal/data/metrics_test.go
Currently the OTLP receiver/exporter still uses the old protos,
because the generated proto file was manually changed to import the v1old generated protos (in the previous PR, and not changed now).
Resolves the second action item from https://github.com/open-telemetry/opentelemetry-collector/issues/1657
internal/data/metrics.go and internal/data/metrics_test.go are the old internal/data/metric files moved in the previous PR, but changed to use the new generated structs.
> Generate the new internal metrics structures, not used

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/testutil_test.go
- go.mod
**Description:** This PR adds implementation for conversion from Int64, Monotonic Int64, Double, and Monotonic Double metrics to Prometheus TimeSeries, as well as the implementation for sending HTTP request to backend.
cc: @huyan0 @alolita  @jmacd @bogdandrutu @annanay25 @gouthamve @open-telemetry/collector-approvers @open-telemetry/collector-maintainers
> Add Prometheus Remote Write Exporter supporting Cortex - conversion and export for scalar OTLP metrics

- translator/internaldata/oc_to_old_metrics.go
- translator/internaldata/old_metrics_to_oc.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1657
> Rename some internal funcs to allow the oc to new structs to reuse the names

- internal/data/testdata/common.go
- internal/data/testdata/metric.go
- internal/data/testdata/metric_test.go
Not all the methods are used, but they will be soon when converting components.
Code mostly copied from testdataold and transformed to use the new structs.
> Add testdata for the new metrics structs

- go.mod
- internal/data/testdata/metric.go
- internal/data/testdata/metric_test.go
- internal/dataold/testdataold/metric.go
- translator/internaldata/oc_testdata_test.go
- translator/internaldata/oc_to_old_metrics_test.go
- translator/internaldata/old_metrics_to_oc_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1657
Split from #1666
> Tune testdata, and update testdataold to use same names

- translator/internaldata/oc_to_metrics_test.go
Use only one resource label to avoid ordering issues in the resource labels list.
> Fix flaky test TestOCToMetrics_ResourceInMetric

- consumer/pdata/metric.go
- internal/data/metrics.go
- internal/data/metrics_test.go
- internal/data/testdata/metric.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_metrics_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1674
> Rename getters for oneof and metricdata types

- cmd/pdatagen/internal/base_fields.go
- cmd/pdatagen/internal/metrics_structs.go
- consumer/pdata/generated_metrics.go
- consumer/pdata/generated_metrics_test.go
- consumer/pdata/metric.go
- consumer/pdata/metric_test.go
Updates #1674 
Depends on #1676
> Add initial draft of the oneof generator, fixes issue in contrib

- processor/resourceprocessor/resource_processor.go
- processor/resourceprocessor/resource_processor_test.go
- testbed/tests/resource_processor_test.go
> Change resource processor to use the new metrics internal structs

- exporter/exporterhelper/metricshelper_test.go
- processor/queuedprocessor/queued_processor_test.go
> Change queued processor/exporterhelper tests to use the new metrics internal structs

- exporter/opencensusexporter/opencensus_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
> Change opencensus recv/exp to use the new metrics internal structs

- processor/cloningfanoutconnector_test.go
- processor/fanoutconnector_test.go
> Change processor tests to use the new metrics internal structs

- consumer/pdata/metric.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1674
> Fix bug in copy data, the data were not deeply copied

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/testutil_test.go
- go.mod
- service/defaultcomponents/defaults.go
- service/defaultcomponents/defaults_test.go
This PR is part of a series of PRs implementing a Prometheus remote write exporter supporting Cortex. 
**See  related PR #1577**  
**Description:** This PR adds export support for histogram and summary metrics for Prometheus remote write [integrated backends](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage), such as Cortex. The exporter drops non-cumulative monotonic, histogram, and summary OTLP metrics.
Please note this metrics exporter does not support Prometheus default labels such as `job` or `instance` labels. An issue addressing Prometheus default labels will be filed later. Another related feature is to derive labels from a Resource. This functionality already exists in the Go SDK and will be implemented in another PR. This feature could allow users …
> Add Prometheus Remote Write Exporter supporting Cortex - conversion and export for Histogram OTLP metrics

- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
Updates #1657
Will slowdown the OTLP loadtest because of an extra conversion newOTLP -> OC -> oldOTLP until the PR to change OTLP will be merged.
> Change batch processor to use the new internal metrics structs

- CHANGELOG.md
- exporter/fileexporter/file_exporter.go
- exporter/fileexporter/file_exporter_test.go
- exporter/otlpexporter/otlp.go
- exporter/otlpexporter/otlp_test.go
- internal/data/opentelemetry-proto-gen/collector/metrics/v1/metrics_service.pb.go
- receiver/otlpreceiver/metrics/otlp.go
- receiver/otlpreceiver/metrics/otlp_test.go
> Change OTLP exporter/receiver and File exporter to use the new opentelemetry-proto v0.5.0

- exporter/otlpexporter/otlp_test.go
> Remove more old usages of metrics structs from otlp exporter

- exporter/prometheusremotewriteexporter/README.md
- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/factory.go
This PR changes the following methods in the Prometheus remote write exporter to public:
* `prometheusremotewriteexporter.prwExporter -> PrwExporter`
* `prometheusremotewriteexporter.newExporter -> NewExporter`
* `prometheusremotewriteexporter.pushMetrics -> PushMetric`
* `prometheusremotewriteexporter.shutdown    -> Shutdown`
These changes allows the creation of  a new exporter that use the Prometheus remote write exporter implementation. 
The new exporter can have a custom configuration and factory, and pass the Prometheus remote write exporter a different http.Client that does custom authentication.   
This PR also updates the link to the design PR in README.md to point to the merged DESIGN.md
Related PR: #1643
cc: @bogdandrutu @jmacd @alolita @huyan0
>  Change some Prometheus remote write exporter functions to public and update link to design in README.md

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
- exporter/prometheusremotewriteexporter/testutil_test.go
This PR removes dependency on dataold and the old v0.4.0 OTLP definitions. It refactors code for metric conversion to convert from OTLP v0.5.0. 
Changes in this PR includes: 
* Replace references:
*  dataold.MetricsData -> data.MetricsData
*  pdatautil.OldInternal -> pdatautil.Internal
* testdataold -> testdata (prefix was changed GenerateMetricData -> GenerateMetrics)
* Change helper methods to take in a pointer to a metric rather than a metric descriptor
* Create helper methods to get the type string from the metric
* Create helper methods for IntDataPoint, DoubleDataPoint, IntHistogramDataPoint , and DoubleHistogramDataPoint
* Replace OTLPv0.4.0 metrics with  v0.5.0 metrics as inputs for unit tests. This accounted for a lot of the changes
Linked Issue: resolves #1681
Related PR: #1643 …
> Refactor the Prometheus remote write exporter to use OTLP v0.5.0

- testbed/testbed/results.go
- testbed/testbed/validator.go
**Description:** This is in support of e2e metrics correctness testing.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/652
> Rename AssertionFailure to TraceAssertionFailure

- consumer/pdata/timestamp.go
- consumer/pdata/timestamp_test.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_old_metrics.go
- translator/internaldata/oc_to_traces.go
- translator/internaldata/old_metrics_to_oc.go
- translator/internaldata/traces_to_oc.go
- translator/trace/jaeger/traces_to_jaegerproto.go
- translator/trace/zipkin/traces_to_zipkinv2.go
This is necessary to prevent circular package dependency that
can arise when we need to hide certain pdata functions in the
internal package in a commit that is coming soon in
https://github.com/open-telemetry/opentelemetry-collector/pull/1703
> Move timestamp functions to pdata package

- testbed/tests/trace_test.go
Historically 70MB was very close to observed max. We typically used +15%
to observed max, so I bumped it to 82MB.
> Bump OpenCensus trace load test memory limit to avoid spurious failures

- consumer/pdata/trace.go
- internal/data/testdata/trace.go
- receiver/jaegerreceiver/trace_receiver_test.go
- translator/trace/jaeger/jaegerproto_to_traces.go
- translator/trace/jaeger/jaegerproto_to_traces_test.go
- translator/trace/jaeger/traces_to_jaegerproto.go
- translator/trace/jaeger/traces_to_jaegerproto_test.go
Will allow contrib to remove dependency on opentelemetry-proto which had the generated proto files.
> Add StatusCode enum values to avoid usage of the proto generated values

- consumer/pdata/metric.go
Avoid returning new objects which are not connected with the parent metric, this way if calling InitEmpty or changing anything we change the right metric.
> Fix oneof getters, avoid returning new objects.

- receiver/kafkareceiver/kafka_receiver.go
Avoid closing ready channel multiple times.
Fixes #1692 
> Fix Kafka receiver closing ready channel multiple times

- consumer/pdatautil/pdatautil.go
- consumer/pdatautil/pdatautil_test.go
- exporter/prometheusexporter/prometheus_test.go
- processor/filterprocessor/filter_processor_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/internal/transaction_test.go
- receiver/prometheusreceiver/metrics_receiver_test.go
Split from https://github.com/open-telemetry/opentelemetry-collector/pull/1720.
There are some changes that I had to do:
* Remove LabelKey.Description which we don't propagate from OC to OTLP;
* Some places where OC -> OTLP -> OC makes some empty slices to be nil (semantically no change, but when comparing protos this is a diff);
* Some places we did not have MetricDescriptor; metrics without descriptor in OC are dropped.
* Some node attributes are converted to Resource attributes (data are still present).
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/841
> Remove support to carry in the metrics pipeline for OC data

- processor/resourceprocessor/README.md
- processor/resourceprocessor/factory.go
- processor/resourceprocessor/resource_processor.go
- processor/resourceprocessor/resource_processor_test.go
- processor/resourceprocessor/testdata/config.yaml
Adds logs support to Resource Processor
**Link to tracking Issue:** #1650 
**Testing:** Unit test added as well as a simple manual test done (with fluentforward receiver and logging output)
**Documentation:** Added note on logs being supported
> Resource Processor: Logs Support (#1650)

- CHANGELOG.md
- receiver/zipkinreceiver/testdata/sample2.json
- receiver/zipkinreceiver/trace_receiver_test.go
- translator/trace/zipkin/zipkinv2_to_traces.go
Fix a panic issue while processing Zipkin spans with an empty service name.
**Testing:** 
`receiver/zipkinreceiver/TestConvertSpansToTraceSpans_JSONWithoutSerivceName`
> Fix panic while processing Zipkin spans with empty service name

- translator/trace/zipkin/zipkinv2_to_traces.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1749 allowing the zipkin span duration to be zero
> Zipkin Receiver: Always set the endtime

- receiver/prometheusreceiver/README.md
**Description:** Removing out of date documentation for prometheus reciever with regards to IncludeFilter.
**Link to tracking Issue:** N/A, [PR 416](https://github.com/open-telemetry/opentelemetry-collector/pull/416) removed code that this documentation is describing.
**Documentation:** Removal of incorrect documentation.
> Remove out of date Prometheus Include Filter docs

- testbed/tests/metric_test.go
OpenCensus appears to need more memory and randomly fails sometimes, e.g.:
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/3370/workflows/13f25fff-56dd-4df0-8c12-31a2432700f6/jobs/34450
> Increase OpenCensus perf test memory limit to avoid failures

- .github/workflows/stale-pr.yaml
To help reviewers and authors remember to make progress on PR
this action will mark PRs as stale after inactivity of 7 days
and will close the PR after 7 more days of inactivity.
> Enable stale PR action

- testbed/tests/trace_test.go
Zipkin appears to need more memory and randomly fails sometimes, e.g.:
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/3370/workflows/73f553df-16ba-40f4-aa04-8f01968b2728/jobs/34445
> Increase Zipkin perf test memory limit to avoid failures

- component/componenterror/errors.go
- component/componenterror/errors_test.go
This PR changes`componenterror.CombineErrors()` to return an error of type `consumererror.permanent` if any error passed to it is permanent. This PR also has some minor reformating of the testcases in `error_test.go` to make the "{}" align and more readable.
resolves #1736 
cc @bogdandrutu
> Return a consumererror.permanent from componenterror.CombineErrors() when necessary

- translator/internaldata/oc_to_traces.go
- translator/internaldata/oc_to_traces_test.go
Signed-off-by: Gary Brown <gary@brownuk.com>
Currently OpenCensus seems to allow span kind to be reported via a field (only `client` and `server` values) or an attribute (only `consumer` and `producer` values).
This PR extends support for handling `client` and `server` values via the attribute. This additional flexibility will enable Envoy (using the current C++ opencensus client with no span kind field support) to report the span kind value.
Fixes #1608 
**Testing:**
Unit test.
> Handle translation of OC span.kind attribute for client/server

- internal/empty.go
- internal/empty_test.go
empty.go file is needed to please `go list` which otherwise complains that tools.go is
only file in the internal package and that build constraints exclude it.
This results in empty list of tests when using `make test` command which then
silently skips all tests.
This fixes the problem and `make test` works properly.
> Fix `make test`

- .golangci.yml
- receiver/otlpreceiver/marshal_jsonpb.go
- receiver/otlpreceiver/marshal_jsonpb_test.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
This requires using custom data types with Gogoprotobuf library.
Gogoprotobuf does not have its own version of JSON Protobuf encoder/decoder,
so we first need to create one. JSONPb that we introduce here is a copy
of jsonpb.Marshaler from github.com/grpc-ecosystem/grpc-gateway project,
but modified to use Gogoproto library instead of golang/protobuf library.
After this PR is merged the next PR will introduce a custom data type
for trace_id field which will implement custom JSON serialization in hex
format as mandated by OTLP specification:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md#request
Note that code coverage is minimal, but marshal_jsonpb.go is a copy of well-tested file from grpc-gateway project.
There is no point in …
> Prepare custom JSON serialization

- consumer/pdata/log.go
- consumer/pdata/log_test.go
- exporter/fileexporter/file_exporter.go
- exporter/fileexporter/file_exporter_test.go
- exporter/otlpexporter/otlp.go
- internal/data/testdata/log.go
- internal/data/testdata/log_test.go
- internal/empty_test.go
- internal/otlp_wrapper.go
- receiver/otlpreceiver/logs/otlp.go
- receiver/otlpreceiver/logs/otlp_test.go
LogsToOtlp and LogsFromOtlp are intended to be used only by OTLP exporter (for which
OTLP is the native data format) and fileexporter (for which we do want to output internal
representation for debugging purposes).
All other code is supposed to use public member functions of pdata.Logs struct.
This changes makes it impossible to use LogsToOtlp and LogsFromOtlp outside this module
by hiding them behind an intermediary struct that is declared in an internal package.
This is necessary to prevent accidental use of LogsToOtlp and LogsFromOtlp and the OTLP
data structs, which we prohibit to do since the OTLP data structs may change in the
future.
> Make pdata.LogsToOtlp and pdata.LogsFromOtlp impossible to call from outside this module

- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler.go
Github appends trailing periods (.) when rendering a URL which means it doesn't go where intended, eg "[https://en.wikipedia.org/wiki/MurmurHash.](https://en.wikipedia.org/wiki/MurmurHash.)"
> Remove ending period in hash function description

- internal/data/testdata/metric.go
- processor/groupbytraceprocessor/processor.go
- processor/groupbytraceprocessor/processor_test.go
- processor/groupbytraceprocessor/storage_memory_test.go
- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler_test.go
This is a preparation to fix the `Append` func on the slices to not accept pointers.
> Avoid using Append when easy to use Resize

- config/confighttp/confighttp.go
- internal/middleware/compression.go
- internal/middleware/compression_test.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
- receiver/otlpreceiver/otlphttp.go
Fixing a bug - OTLP/HTTP receiver does not support gzip. Fixed this by wrapping the HTTP handler generated by grpc-gateway to decompress prior to processing the request, similar to how it's done in https://github.com/open-telemetry/opentelemetry-collector/blob/c4a38294b0f8cab47f63ed7819cb66199c7c53f8/receiver/zipkinreceiver/trace_receiver.go#L208
https://github.com/open-telemetry/opentelemetry-collector/issues/1344
**Testing:** 
Modified unit tests to cover cases where request body is compressed via gzip/zlib.
> Add support for gzip encoded payload in OTLP/HTTP receiver

- .circleci/config.yml
- Escape `.` to match dots only, not any character
- Remove redundant groups
> Correct tag regex in CircleCI config

- processor/resourceprocessor/factory.go
Make the comment and log message match the actual constant used in the deprecation logic.
> Fix Deprecation comment and log message

- internal/data/opentelemetry-proto-gen/common/v1/traceid.go
- internal/data/opentelemetry-proto-gen/common/v1/traceid_test.go
The TraceID type uses custom data type so that JSON serialization
is in hex format instead of base64 (which is the default Protobuf JSON
format). Hex format is required by OTLP spec:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md#request
SpanID must be also modified similarly. Will be done in a future PR
to avoid creating a huge PR.
TraceID data is not yet used in the codebase. This is just an introductory
commit that adds the type and tests but does not yet use them for actual
serialization of OTLP messages. It will be done in a future PR.
Contributes to https://github.com/open-telemetry/opentelemetry-collector/issues/1177
> Introduce TraceID custom data type

- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1357
> Return proto status for OTLP receiver when failed

- CHANGELOG.md
- cmd/otelcol/main.go
- service/service.go
- service/service_test.go
- service/service_windows.go
- testbed/testbed/otelcol_runner.go
Rename **Start()** to **Run()** to follow the naming pattern used in Go, e.g. see blocking [Cmd.Run](https://golang.org/pkg/os/exec/#Cmd.Run) vs non-blocking [Cmd.Start](https://golang.org/pkg/os/exec/#Cmd.Start).
Revisiting #615
@tigrannajaryan @bogdandrutu This is a trivial breaking one-line change compared to many other breaking changes introduced in the recent releases and affecting every single custom component, so I think it's worth reconsidering the [previous decision](https://github.com/open-telemetry/opentelemetry-collector/pull/615#issuecomment-597656638) before GA.
**Documentation:** Included into CHANGELOG as a breaking change
> Rename Start() to Run() since it's a blocking call

- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/opencensusreceiver/opencensus_test.go
**Link to tracking Issue:** #576 
This PR aims to close issue #576 
* `TestReceiver_endToEnd` has already been resolved in some other unrelated issue. Its vestigially mentioned in #576
* `TestAcceptAllGRPCProtoAffiliatedContentTypes`: Removing this test as it's been two years since its been inactive and there is still no way to flush all written traces. As per discussion [here](https://github.com/open-telemetry/opentelemetry-collector/issues/576#issuecomment-693106883) and in Sept Wed 16 2020's Collector SIG [meeting](https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE), there was agreement that this test could be removed since fixing it is costly enough to not be worth the effort.
* `TestExportProtocolConformation_metricsInFirstMessage`: …
> 576 Clean up skipped tests on OC receiver

- config/configtelemetry/configtelemetry.go
- config/configtelemetry/empty_test.go
- internal/collector/telemetry/telemetry.go
- processor/batchprocessor/batch_processor.go
- processor/batchprocessor/batch_processor_test.go
- processor/batchprocessor/metrics.go
- processor/batchprocessor/metrics_test.go
- processor/metrics.go
- processor/queuedprocessor/metrics.go
- processor/queuedprocessor/queued_processor_test.go
- processor/samplingprocessor/tailsamplingprocessor/metrics.go
- receiver/fluentforwardreceiver/observ/metrics.go
- service/telemetry.go
Next PR will add a config setting that can be embedded in every component config.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1663
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1413
> Expose telemetry level in the configtelemetry

- receiver/otlpreceiver/README.md
- add default port info for HTTP/JSON option
> OLTP receiver doc: fix typo

- receiver/kafkareceiver/README.md
Clarify that Zipkin Kafka payload is a list of spans.
Related to #1815
> Clarify that Zipkin Kafka payload is a list of spans

- config/configauth/README.md
- config/configauth/configauth.go
- config/configauth/empty_test.go
**Description:** Added a new configauth package, with the auth settings that can be used by receivers. Split from #1728
**Link to tracking Issue:** Part of the solution for #1424. 
**Testing:** unit tests.
**Documentation:** readme file.
> Authentication Helper 1/4 - Add configauth

- Makefile
- cmd/otelcol/config.yaml
- examples/otel-local-config.yaml
Add OTLP receiver and qretry processor to example and default config.
Updates #886 
Updates #1721 
* `make run`
* build and run docker image
> Add OTLP rec and remove qretry from example and default config

- examples/demo/docker-compose.yaml
- 55680 is the default port of otlp receiver. To avoid confusion,
it's better to use a different number.
> Demo docker-compose file: change the host port of collector

- receiver/prometheusreceiver/internal/metricsbuilder.go
- receiver/prometheusreceiver/internal/transaction.go
- Handle `0` separately from other (invalid) values and print informative log message.
- Delete unused OpenCensus metric
**Link to tracking Issue:** Fixes #1825
> Prometheus Receiver: Print a more informative message about 'up' metric value

- config/configauth/README.md
- config/configauth/configauth.go
- config/configauth/empty_test.go
- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
- internal/auth/context.go
- internal/auth/context_test.go
**Description:** Added a new internal/auth package with the interface that should be implemented by authenticators. Split from #1728.
This PR is based on top of #1807. 
**Link to tracking Issue:** Part of the solution for #1424. 
**Testing:** unit tests.
**Documentation:** none.
> Authentication processor 2/4 - Add auth context and interface

- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_metrics_test.go
**Description:** Getting rid of redundant nil `ResourceObject` when all metrics have resource specified.
After removal of `pdatautil` package in #1739, I've migrated our custom components from `pdatautil.MetricsFromMetricsData` to `internaldata.OCToMetrics` and found that some tests are failing due to converted metrics having an extra "empty" `ResourceMetrics` object in the slice.
**Testing:** Added unit test reproducing the issue
/cc @bogdandrutu
> Skip creation of redundant nil resource in translation from OC if there are no combined metrics

- consumer/consumerdata/consumerdata.go
- translator/internaldata/metrics_to_oc.go
- translator/internaldata/oc_to_metrics.go
- translator/internaldata/oc_to_traces.go
- translator/internaldata/traces_to_oc.go
All new code must use the new pdata.* structures.
TODO: move a few remaining functions that translate between
OpenCensus-data and pdata to OpenCensus packages.
> Deprecate OpenCensus-based internal data structures

- processor/samplingprocessor/tailsamplingprocessor/processor.go
- processor/samplingprocessor/tailsamplingprocessor/processor_test.go
Description:
Previously if multiple sampling policies chose to sample, the trace would be send to the next consumer multiple times. This fixes it to only send it once. 
Link to tracking Issue: #1514
Testing: 
Unit test added as well as a simple manual test using the reproduction case in the original issue.
Documentation: 
None. Do I need to add any?
> tailsampling: only send to next consumer once

- receiver/hostmetricsreceiver/internal/scraper/swapscraper/pagefile_windows.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_metadata.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_windows_test.go
The current code inconsistently reports pagefile usage in pages on Windows and swap usage in bytes on Unix systems.
Updated the code to convert from pages to bytes on Windows so this is consistent.
> Report Windows pagefile usage in bytes

- exporter/exporterhelper/queued_retry_test.go
The mock send is asynchronous so there is no guarantee that the request
count will be 1 at the point when it is asserted to be so in the test.
This has lead to flaky tests so do an Eventually to repeatedly check it for
a full second to make the test more robust.
Should fix one of the issues in #1711.
> Queued Retry Helper: Fix Flaky Test

- testbed/correctness/traces/correctness_test.go
This will hopefully fix #1671. The output of the failed tests indicates
that the received items eventually does equal the number of sent items
but several seconds after the condition timed out.
> Correctness Tests: Extend Timeout for Item Count Check

- go.mod
- go.sum
- receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_notwindows.go
- receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go
- receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper_mock.go
- receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper_test.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/973
**1. Add new perflib package**
2. Migrate host metrics scrapers to use new package
3. Remove third_party PDH code
See https://github.com/open-telemetry/opentelemetry-collector/pull/1836 for example of usage
> 1/3 Add new perfcounters package that uses perflib

- internal/data/opentelemetry-proto-gen/common/v1/bytesid.go
- internal/data/opentelemetry-proto-gen/common/v1/traceid.go
In preparation to SpanID type that is very similar to TraceID
I extracted bytesID as a separate that implements the common
functionality.
Contributes to https://github.com/open-telemetry/opentelemetry-collector/issues/1177
> Extract bytesID as a separate type

- go.mod
- go.sum
- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
- internal/auth/oidc_authenticator.go
- internal/auth/oidc_authenticator_test.go
- internal/auth/oidc_server_test.go
**Description:** Added the OIDC authenticator. Split from #1728.
This PR is based on top of #1808. 
**Link to tracking Issue:** Part of the solution for #1424. 
**Testing:** unit tests.
**Documentation:** none.
> Authentication processor 3/4 - Add implementation

- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows_test.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/973
&nbsp;1. Add new perflib package
&nbsp;**2. Migrate host metrics scrapers to use new package**
&nbsp;3. Remove third_party PDH code
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/1835
> 2a/3 Update hostmetrics disk scraper to use new perfcounters package

- receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper_mock.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows_test.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/973
&nbsp;1. Add new perflib package
&nbsp;**2. Migrate host metrics scrapers to use new package**
&nbsp;3. Remove third_party PDH code
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/1835
> 2b/3 Update hostmetrics load scraper to use new perfcounters package

- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_others_test.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_windows.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_windows_test.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/973
&nbsp;1. Add new perflib package
&nbsp;**2. Migrate host metrics scrapers to use new package**
&nbsp;3. Remove third_party PDH code
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/1835
> 2c/3 Update hostmetrics swap scraper to use new perfcounters package

- go.mod
- service/service.go
- service/service_test.go
- service/set_flag.go
- service/set_flag_test.go
- testbed/testbed/otelcol_runner.go
Creating as a draft to collect feedback. Once we agree I will clean it and add tests.
This patch adds support for configuring components (receivers, processors, exporters...) via `--set` flag. For example `--set=processors.batch.timeout=12s` or `--receivers.otlp.protocols.grpc.endpoint=123456`.
```
--set stringArray             Set arbitrary component config property. The flag has a higher precedence over config file. The arrays are overridden. Example --set=processors.batch.timeout=2s
```
- Flags have higher precedence than config file
- The component has to be defined in the config to apply the configuration otherwise the flag is noop e.g. `--set=processor.queued_retry.queue_size=15` is noop if the `queued_retry` is not …
> Support set flag for component configs

- translator/conventions/opentelemetry.go
See https://github.com/open-telemetry/opentelemetry-specification/pull/1018
> Add cloud.provider semantic conventions

- extension/fluentbitextension/process_linux_test.go
The failures reported in #1848 seem to be caused by the issue described
in https://github.com/golang/go/issues/22315 and the fact that we run
tests in parallel.
Fixes #1848.
> fluentbit Extension: Fix flaky test

- internal/data/opentelemetry-proto-gen/common/v1/spanid.go
- internal/data/opentelemetry-proto-gen/common/v1/spanid_test.go
This is step 2 in adding SpanID custom data type. This only introduces the
type but does not yet use it in Protobuf messages. It will added in a future PR.
Contributes to https://github.com/open-telemetry/opentelemetry-collector/issues/1177
> Add SpanID data type

- testbed/tests/metric_test.go
See https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/3751/workflows/00409594-d070-4f95-addb-928c6438426b/jobs/40533
> Bump memory requirements for TestMetric10kDPS/OpenCensus  to avoid sporadic failures

- receiver/otlpreceiver/otlp_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1851
> Fix flaky Test[HTTP|GRPC]InvalidTLSCredentials by using an available port

- internal/data/testdata/log.go
- internal/processor/filterconfig/config.go
- internal/processor/filterconfig/config_test.go
- internal/processor/filterlog/filterlog.go
- internal/processor/filterlog/filterlog_test.go
- processor/attributesprocessor/attributes_test.go
- processor/attributesprocessor/config.go
- processor/attributesprocessor/config_test.go
- processor/spanprocessor/config.go
- processor/spanprocessor/config_test.go
- processor/spanprocessor/span_test.go
This complements the trace span support already present.
It shares the same config struct to maintain backwards-compatibility with spans in the cleanest way possible.
> Log Support in Attribute Processor (1/2)

- receiver/hostmetricsreceiver/README.md
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/config.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/factory_test.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_test.go
**Description:** Add filters for mount points and filesystem types in addition to device filter.
**Testing:** Added tests.
> hostmetricsreceiver: (filesystems) Add filters for mount point and filesystem type

- cmd/otelcol/config.yaml
> Enable otlp trace by default in the released docker image

- processor/samplingprocessor/tailsamplingprocessor/processor.go
- processor/samplingprocessor/tailsamplingprocessor/processor_test.go
Adding feature https://github.com/open-telemetry/opentelemetry-collector/issues/1834
This changes the tail sampler to emit all spans for a single traces in a single batch. This allows downstream processors to easily perform operations on the entire trace.
**Testing:** 
Added test
> tailsampler: Combine batches of spans into a single batch

- processor/groupbytraceprocessor/README.md
- processor/groupbytraceprocessor/event.go
- processor/groupbytraceprocessor/event_test.go
- processor/groupbytraceprocessor/factory_test.go
- processor/groupbytraceprocessor/metrics.go
- processor/groupbytraceprocessor/metrics_test.go
- processor/groupbytraceprocessor/processor.go
- processor/groupbytraceprocessor/processor_test.go
- processor/groupbytraceprocessor/storage.go
- processor/groupbytraceprocessor/storage_memory.go
- service/telemetry.go
Fixed deadlock in groupbytrace processor.
* Drain the queue upon shutdown, with a time limit. Fixes #1465.
* Added metrics to the groupbyprocessor, making it easier to understand what's going on in case of problems. See #1811.
* Changes the in-memory storage to unlock its RLock when the method returns. Fixes #1811.
Link to tracking Issue: #1465 and #1811
Testing: unit + manual tests
Documentation: see README.md
> Add metrics to groupbytraceprocessor, wait for queue to be drained during shutdown.

- Makefile
After moving the default config, the configs make run is broken
> Fix "run" Makefile target

- internal/processor/filtermetric/filtermetric.go
- internal/processor/filtermetric/filtermetric_test.go
- processor/filterprocessor/filter_processor.go
- processor/filterprocessor/filter_processor_test.go
- processor/filterprocessor/metric_index.go
Updated filter processor to use pdata rather than OC. There's still some OC stuff in filter_processor_test.go, but am hoping that can be updated in a separate change.
Also replaced a benchmark test with a new one. (The previous benchmark test failed with a nil pointer.) The new benchmark test has the following results: 
4233112 ns/op before this change
837378 ns/op after this change
> Update filter processor to use pdata

- go.mod
- go.sum
Fixing a bug - Rolling back to a stable version of gopsutil.
The upgraded version introduced a race condition that should be resolved by
https://github.com/shirou/gopsutil/pull/951
> Rollback gopsutil v2.20.9 to v2.20.6

- exporter/exporterhelper/README.md
This can be referenced by exporter leveraging this helper instead of
duplicating the configuration parameters.
> Add a README to the exporter helper

- processor/groupbytraceprocessor/processor_test.go
This test is very unstable on windows.
Issue for proper fix is filed:
https://github.com/open-telemetry/opentelemetry-collector/issues/1923
> Temporarily skip test until it is fixed

- internal/processor/filterconfig/config.go
- internal/processor/filterhelper/attributematcher.go
- internal/processor/filterlog/filterlog.go
- internal/processor/filterlog/filterlog_test.go
- internal/processor/filtermatcher/.nocover
- internal/processor/filtermatcher/attributematcher.go
- internal/processor/filtermatcher/filtermatcher.go
- internal/processor/filterset/strict/strictfilterset.go
- internal/processor/filterspan/filterspan.go
- internal/processor/filterspan/filterspan_test.go
- processor/attributesprocessor/attributes.go
- processor/attributesprocessor/config_test.go
- processor/attributesprocessor/testdata/config.yaml
- processor/metrics.go
- processor/metrics_test.go
- processor/spanprocessor/span.go
This is how it works:
```
// version match
//  expected actual  match
//  nil      <blank> yes
//  nil      1       yes
//  <blank>  <blank> yes
//  <blank>  1       no
//  1        <blank> no
//  1        1       yes
```
You can decide to match against all versions (expected = `nil`), a specific version (e.g. expected = `1`), or against "version not provided" (expected = `<blank>`). 
Use case: drop attribute values (e.g. a password) for a certain version (`host.image.version`)
Regular expressions should only be prohibited if the expected value is not a string (because an implicit conversion to string would be unexpected).
If the expected value is a string, then a regular expression should be allowed.
> Match spans against the instrumentation library and resource attributes

- receiver/receiverhelper/receiver.go
- receiver/receiverhelper/receiver_test.go
- receiver/receiverhelper/scraper.go
- Added `receiverhelper` functions that follow a similar pattern to the other component helpers.
- Added options to configure `scrape` targets that make it easy to construct a receiver that scrapes sets of metrics at configured frequency(ies).
- Note: Currently only implemented this for Metrics as I don't believe the "scrape" model applies to Traces or Logs.
**Example Usages:**
1. Simple receiver with single scrape target:
```go
type Config struct {
configmodels.ReceiverSettings  `mapstructure:",squash"`
receiverhelper.ScraperSettings `mapstructure:",squash"`
}
...
scraper := newScraper(cfg)
return receiverhelper.NewMetricReceiver(
cfg,
consumer,
receiverhelper.AddScraper(cfg.ScraperSettings, scraper.scrape),
)
```
2. Receiver with multiple scrape targets with additional configuration: …
> 1/2 Add receiverhelper functions for creating flexible "scraper" metrics receiver

- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1813
> Do not inherit cancellation in the async sending queue

- receiver/receiverhelper/receiver.go
- receiver/receiverhelper/receiver_test.go
- receiver/receiverhelper/scraper.go
Allow users of this API to provide a scrape function that returns:
- A metrics slice; OR
- A resource metrics slice
(instead of having to return a fully constructed `pdata.Metrics` object)
Depends on: https://github.com/open-telemetry/opentelemetry-collector/pull/1886
> 2/2 Extend receiverhelper scraper functions to simplify the scrape function interface

- exporter/otlpexporter/otlp.go
> Remove unnecessary interface from otlp exporter, http exporter is different

- testbed/correctness/metrics/correctness_test_case.go
- testbed/correctness/metrics/metrics_test_harness.go
- testbed/correctness/traces/correctness_test.go
- testbed/testbed/child_process.go
- testbed/testbed/load_generator.go
- testbed/testbed/otelcol_runner.go
- testbed/testbed/otelcol_runner_test.go
- testbed/testbed/senders.go
- testbed/testbed/test_case.go
- testbed/tests/resource_processor_test.go
- testbed/tests/trace_test.go
> Use consumer for sender interface, remove unnecessary receiver address from runner

- CHANGELOG.md
- service/builder/exporters_builder.go
- service/builder/exporters_builder_test.go
- service/builder/pipelines_builder.go
- service/builder/pipelines_builder_test.go
- service/builder/receivers_builder_test.go
> Ensure that all exporters are started/shutdown

- exporter/jaegerexporter/README.md
- exporter/jaegerexporter/exporter_test.go
- exporter/jaegerexporter/factory.go
- exporter/kafkaexporter/README.md
- exporter/kafkaexporter/factory.go
- exporter/otlpexporter/README.md
- exporter/otlpexporter/factory.go
- exporter/otlpexporter/factory_test.go
- exporter/otlpexporter/otlp_test.go
- exporter/prometheusremotewriteexporter/factory.go
- testbed/testbed/otelcol_runner_test.go
- testbed/tests/scenarios.go
- testbed/tests/trace_test.go
> Enable sending queue by default in all exporters configured to use it

- receiver/receiverhelper/receiver.go
- receiver/receiverhelper/receiver_test.go
- receiver/receiverhelper/scraper.go
The main advantage is that entire functionality that can be added to the receiver can be encapsulated in one object,
which means some scrapers can be consumed from external packages.
> Refactor metrics scraper to use interface for Scrapers

- exporter/prometheusremotewriteexporter/exporter.go
> Use NewRequestWithContext, remove unnecessary code in PrometheusRemoteWrite exporter

- receiver/receiverhelper/scraper.go
- receiver/receiverhelper/scrapercontroller.go
- receiver/receiverhelper/scrapercontroller_test.go
Remove ability to configure collection interval per scraper and combine (batch) scrapers
> Remove ability to configure collection interval per scraper

- receiver/prometheusreceiver/internal/transaction.go
- receiver/prometheusreceiver/internal/transaction_test.go
~- Log a message when metrics are dropped by Prometheus receiver due to missing `process_start_time_seconds` metric.~
- Report error via `obsreport.EndMetricsReceiveOp` and return error in transaction `Commit()`
**Link to tracking Issue:** Fixes #969
> Log when dropping metrics due to missing process_start_time_seconds

- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/factory_test.go
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
Some TODOs left:
- Parse status and decide if can or not retry.
- Parse status and decide throttling.
- Add tests for both of these.
> Add initial implementation of the otlp HTTP exporter

- consumer/pdata/timestamp.go
- consumer/pdata/timestamp_test.go
- translator/trace/jaeger/jaegerproto_to_traces.go
Fixing a bug. When spans are converted from internal trace to jaeger trace the conversion is `zero timestamp -> time.Time{}` which is a reserved date.  When converted back, this date is interpreted as a usual one, so `ProtoBatchesToInternalTraces(InternalTracesToJaegerProto(traces)) != traces`. So I added a check on this one
> Fix trace jaeger conversion to internal traces zero time bug

- cmd/mdatagen/loader.go
- cmd/mdatagen/metrics.tmpl
- receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_test.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_test.go
This changes the Metrics fields to a struct that implements an interface
with the `New` and `Name` methods to create a new metric and get the
metric name, respectively.
It also adds some methods to Metrics:
- `Names()` that returns a slice of all the names of metrics
- `ByName(name string)` that looks up a metric by its name
- `FactoriesByName()` that returns a map of factories (`New` methods)
keyed by metric name.
This makes it possible to refer to metrics by name in an easily
comparable manner and between components without them having to
explicitly know about these metadata types.
It also removes the validation on the Unit field of metrics since there
are many metrics that have no standard units (e.g. connections).
It also adds an alias `M` that corresponds to `Metrics`, and `L` for …
> Metadata Generator Enhancements

- translator/trace/zipkin/traces_to_zipkinv2.go
- translator/trace/zipkin/traces_to_zipkinv2_test.go
Fixing a bug. There was a panic converting internal traces to zipkin, which occured if there were both a valid span and a nil span. With only nil span the error was about absence of trace id. No check for nil span was present - that is the bug.
**Link to tracking Issue:** might be connected to #1845 
**Testing:** added test with 2 spans
> Fix panic in otlp traces to zipkin

- consumer/pdata/trace.go
- consumer/pdata/trace_test.go
Adding a feature - allow to unmarshal pdata.Traces from protobuf
**Link to tracking Issue:** #1939 
**Testing:** unmarshal(marshal(trace)) = trace
> Add unmarshalling for pdata.Traces

- exporter/jaegerexporter/exporter.go
- exporter/jaegerexporter/exporter_test.go
- exporter/jaegerexporter/factory.go
When trying to get the OpenTelemetry Collector to work with Jaeger, it's currently not easy to determine whether a batch has failed to be sent to Jaeger, as there are no logs recorded anywhere.
This PR adds a debug-level message with the error. Users doing an initial setup, or having problems, can enable debug logging and will be able to identify what's wrong.
Example output:
```
2020-10-15T14:35:55.203+0200	DEBUG	jaegerexporter/exporter.go:95	failed to push trace data to Jaeger	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger/auth", "error": "rpc error: code = Unknown desc = authentication didn't succeed"}
```
**Testing:** manual test …
> Add debug-level message on error for Jaeger Exporter

- exporter/otlphttpexporter/README.md
- exporter/otlphttpexporter/config.go
- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/factory_test.go
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
See README for explanation of configuration changes. We need
this in order to be able to override destination URL per signal.
The OTLP specification defines the defaults for each signal.
This change allows the overrides per signal.
> Allow configuring URLs per signal in OTLP/HTTP exporter

- config/confighttp/confighttp.go
- exporter/otlphttpexporter/otlp_test.go
- internal/data/opentelemetry-proto-gen/collector/trace/v1/trace_service_gateway_aliases.go
- receiver/otlpreceiver/README.md
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
OTLP/HTTP receiver was incorrectly expecting traces on /v1/trace.
OTLP spec require the path to be /v1/traces. This change adds /v1/traces
as a supported alias in the receiver to match what spec requires.
We will keep both paths supported for a while and then will eventually
retire /v1/trace.
Note that the OTLP/HTTP exporter already correctly uses /v1/traces path.
Fixes: https://github.com/open-telemetry/opentelemetry-collector/issues/1968
> Fix OTLP/HTTP receiver's path to be /v1/traces

- consumer/consumertest/nop.go
- consumer/consumertest/nop_test.go
- exporter/exporterhelper/factory_test.go
- exporter/exportertest/nop_exporter.go
- exporter/exportertest/nop_exporter_test.go
- processor/attributesprocessor/attributes_test.go
- processor/attributesprocessor/factory_test.go
- processor/cloningfanoutconnector_test.go
- processor/fanoutconnector_test.go
- processor/filterprocessor/factory_test.go
- processor/memorylimiter/factory_test.go
- processor/memorylimiter/memorylimiter_test.go
- processor/processorhelper/processor_test.go
- processor/resourceprocessor/factory_test.go
- processor/samplingprocessor/probabilisticsamplerprocessor/factory_test.go
- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler_test.go
- processor/samplingprocessor/tailsamplingprocessor/factory_test.go
- processor/samplingprocessor/tailsamplingprocessor/processor_test.go
- processor/spanprocessor/factory_test.go
- processor/spanprocessor/span_test.go
- receiver/fluentforwardreceiver/factory_test.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/kafkareceiver/kafka_receiver_test.go
- receiver/opencensusreceiver/factory_test.go
- receiver/opencensusreceiver/octrace/observability_test.go
- receiver/opencensusreceiver/opencensus_test.go
- receiver/prometheusreceiver/internal/transaction_test.go
- receiver/zipkinreceiver/factory_test.go
- receiver/zipkinreceiver/trace_receiver_test.go
In few situations people complained about not having a nop consumer,
because of confusion that it was implemented as Exporter, even if only used as Consumer.
> Deprecate NopExporter, add NopConsumer

- consumer/pdata/log.go
- consumer/pdata/log_test.go
- consumer/pdata/metric.go
- consumer/pdata/metric_test.go
- consumer/pdata/trace.go
- consumer/pdata/trace_test.go
* Add FromOtlpProtoBytes to all signals;
* Remove deprecated unused function;
* Avoid creating new objects when possible;
> Small cleanups in pdata

- consumer/consumertest/nop_test.go
- consumer/consumertest/sink.go
- consumer/consumertest/sink_test.go
- exporter/exportertest/sink_exporter.go
- exporter/opencensusexporter/opencensus_test.go
- exporter/otlphttpexporter/otlp_test.go
- processor/batchprocessor/batch_processor_test.go
- processor/cloningfanoutconnector_test.go
- processor/fanoutconnector_test.go
- processor/memorylimiter/memorylimiter_test.go
- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler_test.go
- processor/samplingprocessor/tailsamplingprocessor/processor_test.go
- receiver/fluentforwardreceiver/receiver_test.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/jaegerreceiver/jaeger_agent_test.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/kafkareceiver/kafka_receiver_test.go
- receiver/opencensusreceiver/ocmetrics/opencensus_test.go
- receiver/opencensusreceiver/octrace/opencensus_test.go
- receiver/opencensusreceiver/opencensus_test.go
- receiver/otlpreceiver/factory_test.go
- receiver/otlpreceiver/logs/otlp_test.go
- receiver/otlpreceiver/metrics/otlp_test.go
- receiver/otlpreceiver/otlp_test.go
- receiver/otlpreceiver/trace/otlp_test.go
- receiver/prometheusreceiver/internal/transaction_test.go
- receiver/prometheusreceiver/metrics_receiver_test.go
- receiver/receiverhelper/scrapercontroller_test.go
- receiver/zipkinreceiver/trace_receiver_test.go
> Deprecate SinkExporter, add SinkConsumer

- README.md
I am nominating jrcamp as an Approver. Jay has been a reviewer
for many months and authored tens of PRs in this repo.
> Move jrcamp from Triager to Approver

- exporter/prometheusexporter/README.md
- exporter/prometheusexporter/config.go
- exporter/prometheusexporter/config_test.go
- exporter/prometheusexporter/factory.go
- exporter/prometheusexporter/prometheus_test.go
- exporter/prometheusexporter/testdata/config.yaml
Adds a `send_timestamps` option to the prometheus exporter to allow it to send scrape timestamps.
By default, when scraping, Prometheus records data assuming that the presented sample is at the instant of the scrape. For data sources that cache the underlying information and do not refresh on scrape, this can lead to metric samples being recorded at the wrong timestamp. For ex, cadvisor caches for many seconds (4-20 in our experience), and so a sample taken "now" may actually be a sample from 20s ago.
To handle this situation, the exposition format allows an exporter to advise the Prometheus server of the timestamp of the underlying scrape. OpenTelemetry is aware of the timestamp of the scrape.
This change adds an option to have OpenTelemetry send the timestamps of …
> Add send_timestamps option to Prometheus Exporter.

- internal/processor/filtermetric/config.go
- internal/processor/filtermetric/config_test.go
- internal/processor/filtermetric/filtermetric.go
- internal/processor/filtermetric/helpers_test.go
- processor/filterprocessor/config_test.go
- processor/filterprocessor/filter_processor_test.go
This is the first of two PRs to add support for filtering `pdata.Metric`s by arbitrary [expr](https://github.com/antonmedv/expr) expressions. The capabilities of the existing `filterprocessor`, which currently filters just metric _names_ by matching against regexes or strings, will be expanded to allow for filtering `pdata.Metric` _structs_ based on expressions such as `MetricName == "foo" && Label("mylabel") == "bar"`.
This change adds support for `match_type: expr` while maintaining backward compatibility with existing filterprocessor config yamls. Because the expr filter will be the first one that checks for matches against entire `pdata.Metric`s, rather than just their names, some minor changes are required to the structure of the configs that the filterprocessor uses.
For reference, …
> Add expr pdata.Metric filtering support to filterprocessor 1/2

- consumer/pdata/common.go
- consumer/pdata/log.go
- consumer/pdata/log_test.go
- consumer/pdata/metric.go
- consumer/pdata/metric_test.go
- consumer/pdata/trace.go
- consumer/pdata/trace_test.go
Before:
```
BenchmarkLogsClone-16    	    2022	    526826 ns/op
BenchmarkMetricsClone-16    	      92	  11530154 ns/op
BenchmarkTracesClone-16    	     237	   4822875 ns/op
```
After:
```
BenchmarkLogsClone-16    	   17643	     70484 ns/op
BenchmarkMetricsClone-16    	     516	   2226758 ns/op
BenchmarkTracesClone-16    	    1286	    853794 ns/op
```
> Improve Clone performance by 5-7x

- exporter/README.md
- receiver/README.md
Small thing, but I think it's better to have the bullets consistent with the heading.
> Fix alphabetic ordering in READMEs

- exporter/loggingexporter/logging_exporter.go
This PR was introduced to fix the logging exporter to increment the histogram bucket labels (when logging out metrics). Previously, the bucket count stayed at 0. However, bucket labels should increment to conform with the Explicit Bound labels.
Related issue: https://github.com/open-telemetry/opentelemetry-collector/issues/2008
> Logging Exporter: Add index for histogram buckets count

- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
**Description:** Bug fix - adds serialization of array attributes, including nested arrays, in the `logging_exporter`. This allows them to be printed like the primitive attribute types when debugging. AFAICT, there aren't any attributes with array values today, but they are permitted types in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/semantic_conventions/syntax.md#attributes), and I will be contributing a resource detector that uses array attributes in the future. 
**Testing:** Added unit test
> added array serialization to logging_exporter

- extension/fluentbitextension/process_linux_test.go
This should handle the cases where the Golang fork/exec 'text file busy'
error happens.  It should generally not happen twice in a row.
> fluentbit extension: Extend Test Timeout

- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/factory_test.go
- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/logshelper_test.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/queued_retry.go
- exporter/exporterhelper/queued_retry_test.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/jaegerexporter/exporter.go
- exporter/jaegerexporter/exporter_test.go
- exporter/kafkaexporter/factory.go
- exporter/kafkaexporter/factory_test.go
- exporter/kafkaexporter/kafka_exporter_test.go
- exporter/loggingexporter/logging_exporter.go
- exporter/opencensusexporter/factory.go
- exporter/opencensusexporter/opencensus.go
- exporter/otlpexporter/factory.go
- exporter/otlphttpexporter/factory.go
- exporter/otlphttpexporter/otlp.go
- exporter/otlphttpexporter/otlp_test.go
- exporter/prometheusremotewriteexporter/factory.go
- exporter/prometheusremotewriteexporter/factory_test.go
- exporter/zipkinexporter/factory.go
- exporter/zipkinexporter/zipkin_test.go
- service/builder/exporters_builder.go
This change introduces diagnostic debug, info and error logging in
queued_retry exporter helpers. The logging will be applied to all
exporters which use the helpers.
All logging is heavily sampled to avoid flooding the logs. We will
likely need to revise the contributing guide here to clarify that
such sampled logging is allowed:
https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#logging
We will likely also want to fix the logging for batch processor
which currently outputs not very user friendly messages on failures.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/2013
Sample output with otlphttp exporter and destination unavailable:
```
{"level":"info","ts":1603846135.431853,"caller":"service/service.go:252","msg":"Everything …
```
> Improve diagnostic logging for exporters

- consumer/pdata/common.go
- translator/trace/protospan_translation_test.go
Remove usages from non generated call. It is strange to have two new functions that do the same thing.
> Mark as deprecated NewAttributeValue

- go.mod
- go.sum
- internal/processor/filterexpr/matcher.go
- internal/processor/filterexpr/matcher_test.go
- internal/processor/filtermetric/config.go
- internal/processor/filtermetric/expr_matcher.go
- internal/processor/filtermetric/filtermetric.go
- internal/processor/filtermetric/filtermetric_test.go
- internal/processor/filtermetric/name_matcher.go
- processor/filterprocessor/README.md
- processor/filterprocessor/config_test.go
- processor/filterprocessor/expr_test.go
- processor/filterprocessor/factory.go
- processor/filterprocessor/filter_processor.go
- processor/filterprocessor/filter_processor_test.go
- processor/filterprocessor/testdata/config_expr.yaml
This is the second part of the expr metric filtering implementation.
The first PR is here (the description has some additional explanation): https://github.com/open-telemetry/opentelemetry-collector/pull/1940
There's also usage info in the [README](https://github.com/open-telemetry/opentelemetry-collector/pull/1996/files#diff-142d49d9de1b5c15f12404dce18ade26e9a8777110030d7f9d80281b96fa35b3).
> Add expr pdata.Metric filtering support to filterprocessor 2/2

- testbed/testbed/child_process.go
- testbed/testbed/test_bed.go
This is necessary because the file name in the contrib repo is
different from the file name in the core repo.
> Allow to configure the default executable file name in testbed

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
Added User-Agent header to Prometheus Remote Write Exporter's outgoing http request. This allows endpoints to identify whether an incoming metric has come from an OTel Collector instance.
**Testing:**
Unit tests added conforming with existing tests to check headers.
No documentation has been added as it is for internal usage rather than customer usage.
Note: I am assuming here that the `VERSION` variable in the makefile will be set when we reach GA, as currently it is not and the version in the version package is just the default value of "latest"
-- cc @alolita
> Add user agent header to outgoing prometheus remote write exporter http request

- consumer/pdata/common.go
- consumer/pdata/common_test.go
- exporter/loggingexporter/logging_exporter.go
- internal/goldendataset/metric_gen_test.go
- receiver/hostmetricsreceiver/internal/testutils.go
- translator/internaldata/metrics_to_oc.go
This is important since we changed to use slice of values instead of slice of pointers.
After that change we returned a pointer to the memory block to allow users to change the value
of the returned Get or when ForEach, this has a problem if the user keeps a reference to
the returned value by the Get call, then applies any mutation that may move the memory around
Delete, Insert/Upsert the returned pointer may point to other block of memory (different
value in the map) or to a block that is no longer part of the slice, if the slice has to be moved.
> Remove StringValue, do not return a pointer to the value in the map

- testbed/testbed/test_case.go
We only need to wait if the endpoint is not-empty, i.e. the sender does use network
(some senders like text log writers don't).
> Testbed: only wait for agent endpoint to be listening when endpoint is not empty

- consumer/consumererror/partialscrapeerror.go
- consumer/consumererror/partialscrapeerror_test.go
- obsreport/obsreport.go
- obsreport/obsreport_scraper.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- receiver/receiverhelper/errors.go
- receiver/receiverhelper/errors_test.go
- receiver/receiverhelper/scraper.go
- receiver/receiverhelper/scrapercontroller.go
- receiver/receiverhelper/scrapercontroller_test.go
Add obsreport to receiverhelper scraper library
- Added `consumererror.PartialScrapeError` for denoting that a scrape was partially successful and recording the number of metrics that failed to be scraped
- Add `receiverhelper.CombineScrapeErrors` to support combining partial scrape errors
- Updated `obsreport` with Trace & Metric observability support for Scrapers. Obsreport records the number of failed scrapes based on the partial scrape error count if relevant
- Call obsreport in the receiverhelper scraper library 🎉 
**Blocks #1949**
---
**Sample Output:** (see #1949)
_Note in these examples we see quite a lot of errors scraping process data due to not running the Collector in "Administrative mode" on Windows:_
**Traces (from http://localhost:55679/debug/tracez?zspanname=scraper%2fproce …
> Add obsreport to receiverhelper scrapers

- receiver/kafkareceiver/zipkin_unmarshaller.go
- receiver/zipkinreceiver/config.go
- receiver/zipkinreceiver/config_test.go
- receiver/zipkinreceiver/factory.go
- receiver/zipkinreceiver/proto_parse_test.go
- receiver/zipkinreceiver/testdata/config.yaml
- receiver/zipkinreceiver/trace_receiver.go
- receiver/zipkinreceiver/trace_receiver_test.go
- translator/trace/zipkin/status_code_test.go
- translator/trace/zipkin/testdata/zipkin_v1_multiple_batches.json
- translator/trace/zipkin/testdata/zipkin_v1_single_batch.json
- translator/trace/zipkin/testdata/zipkin_v1_thrift_single_batch.json
- translator/trace/zipkin/traces_to_zipkinv2_test.go
- translator/trace/zipkin/zipkinv1_to_protospan.go
- translator/trace/zipkin/zipkinv1_to_protospan_test.go
- translator/trace/zipkin/zipkinv1_to_traces.go
- translator/trace/zipkin/zipkinv1_to_traces_test.go
- translator/trace/zipkin/zipkinv2_to_traces.go
- translator/trace/zipkin/zipkinv2_to_traces_test.go
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1888
Previously the zipkin receiver parses string tags to other datatypes (int/bool/float), this adds the functionality back under a new configuration option `parse_string_tags` in the zipkin receiver.
To unify the behavior with the zipkin v1 I also disabled the parsing by default and check the same configuration option.
**Link to tracking Issue:** #1888 
**Testing:** 
Added test
> zipkin receiver: allow receiver to parse string tags

- consumer/pdata/common.go
> Remove InitFromAttributeMap, use CopyTo if needed.

- receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_test.go
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/2041
- The `disk.io_time` metric only reports a single value: the total time the disk was active. Unlike other disk metrics, it does not report read & write data points. Therefore, we would only expect one data point per disk.
- The test checked for a minimum of two data points. Therefore, if this test was run on a machine with a single disk drive, the test would fail.
Fixed the test to check for a minimum of one data point for this metric.
---
_Note to maintainers: please merge #1949 before this PR 😄_
> Fix host metrics disk tests

- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
Reworking of PR: https://github.com/open-telemetry/opentelemetry-collector/pull/1734
The requested functionality of modifying componenterror.CombineErrors() has since been done, all that is left is to actually return permanent errors in the exporter
**Link to tracking Issue:**  https://github.com/open-telemetry/opentelemetry-collector/issues/1733
> Return permanent errors in prometheus remote write exporter

- consumer/pdata/common.go
- consumer/pdata/common_test.go
- exporter/loggingexporter/logging_exporter_test.go
This makes things consistent with other generated code where we do not allow
to set non immutable fields.
User can get access to the Map/Array and change that in-place.
> Remove support to set map and array to attribute value

- processor/batchprocessor/batch_processor.go
The newItem channel cannot be closed ever since Shutdown is not
guaranteed to be called after all Consume* calls to the same processor.
Even after Shutdown is finished, there is not hard guarantee that
nothing will ever call Consume*, so we need to just leave the channel
open until GC will clean it up.
> batchprocessor: Fix shutdown race

- exporter/prometheusremotewriteexporter/README.md
- exporter/prometheusremotewriteexporter/config.go
- exporter/prometheusremotewriteexporter/config_test.go
- exporter/prometheusremotewriteexporter/exporter.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- exporter/prometheusremotewriteexporter/factory.go
- exporter/prometheusremotewriteexporter/factory_test.go
- exporter/prometheusremotewriteexporter/helper.go
- exporter/prometheusremotewriteexporter/helper_test.go
- exporter/prometheusremotewriteexporter/testdata/config.yaml
- exporter/prometheusremotewriteexporter/testutil_test.go
This PR adds the concept of Prometheus "external labels" to the Prometheus Remote Write Exporter. These labels must be kept isolated from OTLP metric data point labels because they do not undergo the same type of sanitization. The difference is external labels are allowed to start with "__". This satisfies the use case of Cortex HA deduplication and hence resolves the linked issue.
**Link to tracking Issue:** open-telemetry#1892
**Testing:**
Unit test cases have been added wherever changes were made and manual testing was done to verify Cortex HA deduplication and that nothing changed in metric graphs other than labels.
The example configuration in testdata/config.yaml demonstrates how to use the external label config'
README has been updated to include …
> Add external labels to prometheus remote write exporter

- consumer/consumererror/partialerror.go
- consumer/consumererror/partialerror_test.go
- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/logshelper_test.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
Add support of partial requests for logs and metrics to the exporterhelper
#2057 
**Testing:**
Unit Tests
> Add support of partial requests for logs and metrics to the exporterhelper

- consumer/pdata/metric.go
- consumer/pdata/metric_test.go
Add a guard for invalid metrics with no data points. The function `MetricAndDataPointCount` currently panics if the gauge, histogram or sum is nil.
**Testing:**
I added a unit test and reproduced the issue, making sure the issue is fixed with the test passing.
> Guard for nil data points

- consumer/pdata/common.go
Some method names in the method signatures and comments are different. This PR updates some misleading method names in comments.
> fix-typo: update method names in comments

- exporter/loggingexporter/logging_exporter.go
This issue adds logging for the summary datapoint in the logging exporter. This is primarily added for testing purposes.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/1638
**Resulting Logs**
```
Metric #38
Descriptor:
-> Name: rpc_durations_seconds
-> Description: RPC latency distributions.
-> Unit: s
-> DataType: DoubleSummary
SummaryDataPoints #0
Data point labels:
-> Namespace: rpc-app
-> Service: rpc-app-service
-> app: rpc-app
-> container_name: rpc-app-cont
-> service: exponential
StartTime: 1604691204093000000
Timestamp: 1604691234093000000
Count: 410
Sum: 0.000414
QuantileValue #0: Quantile 0.500000, Value 0.000001
QuantileValue #1: Quantile 0.900000, Value 0.000002
QuantileValue #2: Quantile 0.990000, Value 0.000005 …
```
> Add Logging for Summary Datapoint to Logging Exporter

- exporter/exporterhelper/README.md
- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/resource_to_label.go
- exporter/exporterhelper/resource_to_label_test.go
We need a common helper function which can convert resource attributes to metric labels and be utilized by every exporter. In the linked issue, @bogdandrutu suggested two possible ways- a consumer or a helper function. In this PR, we have both of the consumer and helper function ready. However, I was only able to utilize the helper function for end to end test modifying the `logging` exporter. Every exporter can call this helper function before exporting the metrics to destination. 
For the consumer setup, I cannot find a place to plug in this in between a processor and an exporter. I think I need more guidance on how we can make it a common utility for all exporters. Thanks in advance. 
Issue …
> [exporter-helper] [resource_to_label_conversion] add helper function and expose exporter settings

- config/confighttp/confighttp.go
- config/confighttp/confighttp_test.go
This is a fully backwards compatible change that allows optional configuration of a custom round tripper for components that use the confighttp package
An example use case can be seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1497
-- cc @bogdandrutu
> Add customroundtripper to httpclientconfig

- go.mod
- go.sum
> Upgrade zipkin-go to v0.2.5, run go mod tidy

- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_others.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_windows.go
For the tcp_connections metric, we want to always return a data point for each TCP state label. Unix uses slightly different TCP state labels than Windows:
- Linux: [gopsutil](https://github.com/shirou/gopsutil/blob/c4663018cc3b6dfb0ae893bf2ca5f861fe3de3c0/net/net_linux.go#L309) / [Linux src](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/net/tcp_states.h?id=HEAD) (this seems to match other Unix systems as well)
- Windows: [gopsutil](https://github.com/shirou/gopsutil/blob/c4663018cc3b6dfb0ae893bf2ca5f861fe3de3c0/net/net_windows.go#L563) / [MS docs](https://docs.microsoft.com/en-us/windows/win32/api/tcpmib/ns-tcpmib-mib_tcprow2)
This PR updates the code to set the tcp state labels based on OS. This also fixes a test that would fail intermittently on Linux …
> Host Metrics receiver: use correct TCP state labels on Unix systems

- service/logger.go
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/2106
Make logs more human-readable locally: switch from "json" to "console" encoding
even when "prod" logging configuration is selected (but keep Production zap
Logger configuration for "prod" mode). This is still fairly well-defined
format that can be unambiguously parse on the backend if needed.
> Use "console" encoding for own logs

- obsreport/obsreport_receiver.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest.go
- obsreport/obsreporttest/obsreporttest_test.go
- receiver/otlpreceiver/logs/otlp.go
Fix: otlp_log receiver wrong use of trace measurement
#2116
> fix otlp_log receiver wrong use of trace measurement

- obsreport/obsreport.go
- obsreport/obsreport_processor.go
This is part of a longer effort to move all the obsreport package to use structs for every component type,
that allow configuring the level at the component level (every component instance will have it's own
obsreport struct instance).
Exporter, Receiver and Scrapers will be changed later after the infrastructure is built for Processor.
> Add a struct for processor obs report instead of using package level funcs

- cmd/pdatagen/internal/base_structs.go
- consumer/pdata/common.go
- consumer/pdata/generated_common.go
- consumer/pdata/generated_common_test.go
- consumer/pdata/generated_log.go
- consumer/pdata/generated_log_test.go
- consumer/pdata/generated_metrics.go
- consumer/pdata/generated_metrics_test.go
- consumer/pdata/generated_trace.go
- consumer/pdata/generated_trace_test.go
- consumer/simple/metrics_test.go
Optimizations:
* For `CopyTo` ensures that if space enough in the slice (check for capacity not for length) a new slice is not allocated.
* For `Resize` if not enough capacity, allocate the right slice from the beginning instead of keep calling append which may do more allocations.
> Cleanup copyto/resize, ensure reuse of the old slice when possible.

- .golangci.yml
- exporter/exporterhelper/logshelper_test.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/tracehelper_test.go
- exporter/prometheusremotewriteexporter/exporter_test.go
- processor/samplingprocessor/probabilisticsamplerprocessor/probabilisticsampler.go
- receiver/jaegerreceiver/factory.go
- receiver/jaegerreceiver/jaeger_agent_test.go
- receiver/jaegerreceiver/trace_receiver.go
- receiver/jaegerreceiver/trace_receiver_test.go
- receiver/zipkinreceiver/trace_receiver.go
- testbed/tests/resource_processor_test.go
> Enable unparam linter, removes unused params from not exported funcs

- service/internal/telemetry/process_telemetry.go
This metric is in bytes, it was incorrectly marked as unitless.
> Fix "process/memory/rss" metric units

- service/internal/telemetry/process_telemetry.go
It was incorrectly declared as a unitless int64 metric. It needs to be a float64, and units are seconds.
> Fix "process/cpu_seconds" metrics

- service/logger.go
- service/service.go
- service/service_test.go
- service/service_windows.go
This is a Feature request.
It extends parameters passed to service so that more than hooks can be passed to the zap library.
Currently it removes the `LoggingHooks`, as this field can be represented as `zap.Option`
But if you prefer to leave it and possibly generate deprecation message let me know.
**Testing:** 
I changed the unit tests, considering the size of the change it should be enough.
> Allow for more logging options to be passed to service.

- translator/trace/jaeger/traces_to_jaegerproto.go
- translator/trace/jaeger/traces_to_jaegerproto_test.go
Maps the UNSET status code according to the spec.
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#set-status
**Testing:**
Unit test
N/A
> Map unset status code as per spec

- receiver/prometheusreceiver/internal/ocastore.go
- receiver/prometheusreceiver/metrics_receiver.go
- service/internal/resources.go
The receiver contains various unnecessary sections. Rewriting the
receiver's Start for better maintainability.
Related to #1909.
> Fix the scraper/discover manager coordination on the Prometheus receiver

- config/configtelemetry/configtelemetry.go
- config/configtelemetry/configtelemetry_test.go
- internal/collector/telemetry/telemetry.go
- processor/batchprocessor/factory.go
- processor/metrics.go
- service/service.go
- service/telemetry.go
Next steps will be to use the new settings in the processors.
> Add config settings for component telemetry, move the flag

- receiver/fluentforwardreceiver/README.md
Fixed fluentforwardreceiver example configuration. The example configuration specified `listenerAddress`; however, it should be `endpoint` based on the [Config struct](https://github.com/open-telemetry/opentelemetry-collector/blob/6ac579e9bc9b6a1bf06ffc07975d2c746ad1bdef/receiver/fluentforwardreceiver/config.go#L28).
**Testing:**
Configured fluentforwardreceiver and specified the correct configuration based on the Config struct. 
See commit.
> Fix fluentforwardreceiver config example

- processor/batchprocessor/batch_processor_test.go
- processor/batchprocessor/metrics.go
- processor/batchprocessor/metrics_test.go
- processor/metrics.go
- processor/queuedprocessor/metrics.go
- processor/queuedprocessor/queued_processor_test.go
- receiver/fluentforwardreceiver/observ/metrics.go
- receiver/fluentforwardreceiver/observ/metrics_test.go
- service/telemetry.go
This is a preparation for enabling per component telemetry level:
* Views are global and they must always be installed; they are no-op if nobody records data;
* Views are global and they must always contain all the labels; In case of measurements being recorded without one of the labels (for performance reasons)
the extra label defined does not have impact, because all the timeseries will have that label as "null" (missing).
> Remove level from all the MetricViews calls

- receiver/prometheusreceiver/internal/metrics_adjuster.go
Return after finding that two arrays differ in length.  Otherwise, the function will panic.
Fixes: https://github.com/open-telemetry/opentelemetry-collector/issues/2167
> Fix panic when adjusting buckets

- CHANGELOG.md
- service/logger.go
Contributes to https://github.com/open-telemetry/opentelemetry-collector/issues/2102
> Add --log-format command line option (default to "console")

- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/tracehelper.go
- obsreport/obsreport_exporter.go
- obsreport/obsreport_test.go
- obsreport/obsreporttest/obsreporttest_test.go
This is part of a longer effort to move all the obsreport package to use structs for every component type,
that allow configuring the level at the component level (every component instance will have it's own
obsreport struct instance).
> Add a struct for exporter obs report instead of using package level funcs

- CHANGELOG.md
- receiver/otlpreceiver/README.md
- receiver/otlpreceiver/config_test.go
- receiver/otlpreceiver/factory.go
- receiver/otlpreceiver/otlp.go
- receiver/otlpreceiver/otlp_test.go
This implements specification change https://github.com/open-telemetry/opentelemetry-specification/pull/1221
To make transition to new port numbers less painful OTLP receiver will
also accept data on the legacy port numbers when it is configured to
use the default endpoint. Users who use the default Collector config
can continue sending data to the legacy ports and have a graceful period
to update their senders to start sending to the new ports.
Note that OTLP/HTTP continues using a separate port number from OTLP/gRPC.
There is separate work in progress to use one port for both.
This must be merged after https://github.com/open-telemetry/opentelemetry-specification/pull/1221 is merged.
> Change default OTLP port number

- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/receiverhelper/scraper.go
- receiver/receiverhelper/scrapercontroller.go
In a followup PR, after #2186 is merged, use component helper.
> Use Component for start/shutdown of the Scraper

- receiver/hostmetricsreceiver/config.go
- receiver/hostmetricsreceiver/config_test.go
- receiver/hostmetricsreceiver/factory.go
- receiver/hostmetricsreceiver/hostmetrics_receiver_test.go
- receiver/hostmetricsreceiver/internal/scraper.go
- receiver/hostmetricsreceiver/internal/scraper/cpuscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/diskscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/loadscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/memoryscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/processesscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/factory.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_others.go
- receiver/hostmetricsreceiver/internal/scraper/swapscraper/swap_scraper_windows.go
- receiver/scraperhelper/errors.go
- receiver/scraperhelper/errors_test.go
- receiver/scraperhelper/scraper.go
- receiver/scraperhelper/scrapercontroller.go
- receiver/scraperhelper/scrapercontroller_test.go
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/2036
> Move scraper helpers to its own package scraperhelper

- component/componenthelper/component.go
- component/componenthelper/component_test.go
- exporter/exporterhelper/common.go
- exporter/exporterhelper/common_test.go
- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/tracehelper.go
- processor/processorhelper/processor.go
- processor/processorhelper/processor_test.go
Add `componenthelper` package to help building components like Processors, Exporters.
> Reduce duplicate code in components helper

- receiver/prometheusreceiver/internal/metricsbuilder.go
This is unncessarily a package level variable and at the same time, the name is confusing. It should be called "empty" instead of dummy. But no need to have it as a package-level variable, hence this change removes it.
> Remove the confusing package-level variable

- exporter/exporterhelper/constants.go
- exporter/exporterhelper/logshelper.go
- exporter/exporterhelper/logshelper_test.go
- exporter/exporterhelper/metricshelper.go
- exporter/exporterhelper/metricshelper_test.go
- exporter/exporterhelper/tracehelper.go
- exporter/exporterhelper/tracehelper_test.go
> Rename Push functions to be consistent across signals in exporterhelper

- config/configtls/README.md
- config/configtls/configtls.go
- config/configtls/configtls_test.go
Follow up from #933 where InsecureSkipVerify was discussed but not
implemented.
**Description:** Add support to set `InsecureSkipVerify` to `tls.Config`. This will use a secure connection which `Insecure` does not, however it will not verify the certificate.
**Link to tracking Issue:** No issue but followup on #933.
**Testing:** Added test for the configuration to ensure settings were properly set.
**Documentation:** Updated `configtls` README with example.
/cc @ccaraman
> Add support to skip TLS verification

- cmd/pdatagen/internal/base_slices.go
- consumer/pdata/common.go
- consumer/pdata/generated_common_test.go
- receiver/fluentforwardreceiver/conversion.go
> Remove calls to InitEmpty when not necessary, remove AttributeValue.InitEmpty

- Makefile.Common
When running `make` to run tests, the `misspell` target is run on the `internal/tools` directory (since https://github.com/open-telemetry/opentelemetry-collector/pull/2131).
As there are no `.md` nor `.yaml` files in this directory, the `ALL_DOC` variable (defined as `ALL_DOC := $(shell find . \( -name "*.md" -o -name "*.yaml" \) -type f | sort`) is empty.
Therefore, the `misspell` target runs `misspell -error` without any argument, causing `misspell` to read `stdin`, hanging. The only way to make `make` not hang is to send `EOF` (eg. with `echo -n | make`).
I suspect that this doesn't affect the CI as it automatically sends `EOF` to stdin.
This PR fixes makes the `misspell -error` by making the `misspell` command conditionally run, only if `ALL_DOC` is defined and not …
> Fix make misspell hanging on internal/tools

- config/config.go
- go.mod
- service/service.go
- service/service_test.go
- service/set_flag.go
- service/set_flag_test.go
- service/testdata/otelcol-config.yaml
- testbed/testbed/otelcol_runner.go
Re-adds the --set parameter in a way that works with `{}` being used in configs.
Fixes #1907 
**Testing:**
The original tests were added along with the addition of the following:
```
extensions:
health_check: {}
```
This failed the previous tests, but now passes.
> Fix --set flag

- processor/README.md
Documentation for processors states:
> Only match_type=strict is allowed if "attributes" are specified.
but this restriction was removed in https://github.com/open-telemetry/opentelemetry-collector/pull/928/files#diff-4548db28578c2ac90e2b277f24654cfa24fd0f99d854e0fcc4b50871c0b529caL166-R198, and so this doc appears to be outdated.
**Testing:**
I did not test this, but others (including @tigrannajaryan) have: https://github.com/open-telemetry/opentelemetry-collector/issues/1935#issuecomment-717259673
[btw, in case you're curious my interest in this, we are implementing a subset of this behavior at the java agent layer, as we aren't using otel collector. So far only in our vendor distro, though happy to move it to otel javaagent if/when others are interested.]
> Remove outdated line from documentation

- exporter/loggingexporter/logging_exporter.go
- exporter/loggingexporter/logging_exporter_test.go
Make `logLevel` ENV case-insensitive for **logging_exporter**
> make logLevel ENV case-insensitive

- testutil/testutil.go
- testutil/testutil_test.go
Signed-off-by: Kevin Earls <kearls@redhat.com>
**Description:** Add a retry mechanism when finding ports for tests on windows, as net.Listen will occasionally return a port that is actually not available.   Details are available here https://github.com/docker/for-win/issues/3171, but to summarize Hyper-V will reserve ranges of ports which do not show up under the "netstat -ano" command but can only be found by "netsh interface ipv4 show excludedportrange protocol=tcp"
This PR updates the testutil/GetAvailablePort function so when run on windows it will get the excludedportranges from the netsh command and retry if GetAvailableLocalAddress returns a port within those ranges
**Link to tracking Issue:** #2111 NOTE: there are several failures referred to in that issue which were not caused by …
> Add retry to getAvailablePort to avoid spordic CI failure on windows

- examples/demo/app/main.go
Stopping exporter before stopping pusher causes the pusher to flush
the buffered metrics to a stopped exporter, which basically means
sending metrics to /dev/null.
This has shown up for me, when I limited the number of metrics to a small number. So after shutdown the collector didn't receive any metrics (traces were fine). After the fix, metrics appeared as they should.
> Stop pusher after exporter in sample app

- exporter/prometheusremotewriteexporter/README.md
This PR is a documentation change addressing this [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/2268). We now specify that certain headers such as (`Content-Encoding`, `Content-Type`, `X-Prometheus-Remote-Write-Version`, and `User-Agent`) cannot be changed in the optional configuration.
**Link to tracking Issue:**  https://github.com/open-telemetry/opentelemetry-collector/issues/2268
The Prometheus Remote Write Exporter documentation was changed to reflect the behavior of the exporter.
> Fix the inaccurate mention of headers in prwe

- .circleci/config.yml
We want contribtest to run on PRs to make it clear when we are making
a breaking change. We also want to run it on release branches to prevent
making a core release when contrib is broken.
However, there is no point in running the contribtest on master branch, it does
not help and only pollutes the view with failures that are always ignored.
> Don't run contribtest on master. We only want to run it for PRs and releases

- translator/internaldata/resource_to_oc.go
> Remove duplicate code, same check exists in getLibraryInfo
