open-telemetry/opentelemetry-collector

.github/workflows/prepare-release.yml

After #8975 we decided to not do any more explicit release candidates so we can update the examples.
Note that due to #9676 this is not tested until we explicitly run the workflow on the next release, but the change is small enough to seem safe to merge.

[chore] Update prepare release examples

---

config/confighttp/README.md

This doc incorrectly uses the otlp exporter as an example of using confighttp. That exporter doesn't use confighttp

[chore] fix type in confighttp readme

---

cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_status.go
cmd/mdatagen/main_test.go
cmd/mdatagen/templates/status.go.tmpl
connector/forwardconnector/internal/metadata/generated_status.go
exporter/debugexporter/internal/metadata/generated_status.go
exporter/loggingexporter/internal/metadata/generated_status.go
exporter/otlpexporter/internal/metadata/generated_status.go
exporter/otlphttpexporter/internal/metadata/generated_status.go
extension/ballastextension/internal/metadata/generated_status.go
extension/memorylimiterextension/internal/metadata/generated_status.go
extension/zpagesextension/internal/metadata/generated_status.go
processor/batchprocessor/internal/metadata/generated_status.go
processor/memorylimiterprocessor/internal/metadata/generated_status.go
receiver/otlpreceiver/internal/metadata/generated_status.go

To produce the same output as mdatagen in contrib. It makes it easy to compare the diff for the mdatagen migration.

[chore] [cmd/mdatagen] Update status.go template

---

exporter/exporterhelper/common.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/request.go
exporter/exporterhelper/traces.go
exporter/exporterqueue/config.go
exporter/exporterqueue/queue.go

Addressing https://github.com/open-telemetry/opentelemetry-collector/pull/8685#discussion_r1514315859

[chore] [exporterhelper] Update notes for the experimental API

---

exporter/exporterhelper/README.md

- **[chore] [exporterhelper] Update docs to remove requeuing** as it was removed in #9090
- **Fix typo**
There is no functional change and should not require a changelog.

[chore] [exporterhelper] Update docs to remove requeuing

---

.chloggen/batch-exporter-helper.yaml
exporter/exporterbatcher/batch_func.go
exporter/exporterbatcher/config.go
exporter/exporterbatcher/config_test.go
exporter/exporterhelper/batch_sender.go
exporter/exporterhelper/batch_sender_test.go
exporter/exporterhelper/common.go
exporter/exporterhelper/queue_sender.go
exporter/exporterhelper/request_test.go

This change introduces new experimental batching functionality to the exporter helper. The batch sender is fully concurrent and synchronous. It's set after the queue sender, which, if enabled, introduces the asynchronous behavior and ensures no data loss with the permanent queue. 
Follow-up TODO list:
- Add pre-built merge funcs for pdata
- Handle partial errors
- A missing part compared to the batch processor is the ability to shard the batches by context value.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/8122

[exporterhelper] Introduce batching functionality

---

processor/batchprocessor/metrics.go

This follows #9556 and uses the Meter func instead of managing the scope in the batch processor manually. Replaces #9581

use generated meter

---

examples/k8s/otel-config.yaml

This PR fixes an incorrect automatic replace made in the `otel-config.yml` file in this [pull request](https://github.com/open-telemetry/opentelemetry-collector/pull/9680/files#diff-c7c8156618a7f8126b25ca1bdfde3e172a0d2cb75c533d63a71617ae2a5c54ae) by a bot. I've taken the previous value which seems right.

[chore] Fix an incorrect automatic replace made by a bot in `otel-config.yml`

---

cmd/mdatagen/loader_test.go
cmd/mdatagen/metricdata.go

Now that we support embedded structs unmarshaling, we can simplify the code handling metric data unmarshaling somewhat.

[chore] Refactor mdatagen unmarshaling to use less custom Unmarshalers

---

confmap/confmap.go
confmap/confmap_test.go

This is a split of #9750 that tries to work around mapstructure, which wraps an error around a decoding error.
In the case when an error is returned from a top level construct, we get a not so helpful message that says:
```
error decoding '': error running encode hook: marshaling error
```
With this change, the error is unwrapped, giving the following string representation:
```
error running encode hook: marshaling error
```
Because #9750 enforces going through mapstructure, it would change errors returned with this not-so-helpful preamble. Adding this removes the problem.

[chore] Remove the top level error if it indicates an empty name

---

cmd/mdatagen/internal/samplereceiver/generated_component_test.go
cmd/mdatagen/templates/component_test.go.tmpl
connector/forwardconnector/generated_component_test.go
exporter/debugexporter/generated_component_test.go
exporter/loggingexporter/generated_component_test.go
exporter/nopexporter/generated_component_test.go
exporter/otlpexporter/generated_component_test.go
exporter/otlphttpexporter/generated_component_test.go
extension/ballastextension/generated_component_test.go
extension/memorylimiterextension/generated_component_test.go
extension/zpagesextension/generated_component_test.go
processor/batchprocessor/generated_component_test.go
processor/memorylimiterprocessor/generated_component_test.go
receiver/nopreceiver/generated_component_test.go
receiver/otlpreceiver/generated_component_test.go

This change is required in preparation of #9750 
This removes the call to `component.UnmarshalConfig` in preparation of its deprecation, and instead has the `Conf` object unmarshal itself into the `Config` struct.

[chore] change the way we unmarshal the config in tests

---

exporter/exporterhelper/README.md

Removing the alpha status with the warning as discussed in the latest Collecor SIG meeting.
cc @swiatekm-sumo

[chore] Remove the development warning from readme for persistent queue

---

.chloggen/remove_stable_featuregate.yaml
internal/obsreportconfig/obsreportconfig.go

Remove the stable feature gate `telemetry.useOtelForInternalMetrics`. It was declared stable in 0.95.0.

[chore] Remove `telemetry.useOtelForInternalMetrics` stable feature gate

---

.chloggen/optimize-mdatagen-for-batchprocessor.yaml
cmd/mdatagen/templates/component_test.go.tmpl
exporter/debugexporter/generated_component_test.go
exporter/loggingexporter/generated_component_test.go
exporter/nopexporter/generated_component_test.go
exporter/otlpexporter/generated_component_test.go
exporter/otlphttpexporter/generated_component_test.go
processor/batchprocessor/generated_component_test.go
processor/batchprocessor/metadata.yaml
processor/memorylimiterprocessor/generated_component_test.go

fix #9688
The batchprocessor use a `batchProcessor` as a common struct which implements `consumer.Traces`, `consumer.Metrics`, `consumer.Logs` in the meantime.
As a result, the generated lifecycle test will fail, since when it create a metrics, traces processor object, it will still fall to the case `consumer.Logs` and panic. 
```
=== RUN   TestComponentLifecycle/metrics-shutdown
=== RUN   TestComponentLifecycle/metrics-lifecycle
panic: interface conversion: interface {} is plog.Logs, not pmetric.Metrics
goroutine 37 [running]:
go.opentelemetry.io/collector/processor/batchprocessor.(*batchMetrics).add(0x14000208120?, {0x10572aae0?, 0x1400029c3f0?})
/Users/zhaoziqi/Documents/go/src/go.opentelemetry.io/opentelemetry-collector/processor/batchprocessor/batch_processor.go:450 …
```

[cmd/mdatagen] optimize mdatagen for batchprocessor failed test

---

cmd/mdatagen/internal/samplereceiver/generated_component_test.go
cmd/mdatagen/templates/component_test.go.tmpl
connector/forwardconnector/generated_component_test.go
exporter/debugexporter/generated_component_test.go
exporter/loggingexporter/generated_component_test.go
exporter/nopexporter/generated_component_test.go
exporter/otlpexporter/generated_component_test.go
exporter/otlphttpexporter/generated_component_test.go
extension/ballastextension/generated_component_test.go
extension/memorylimiterextension/generated_component_test.go
extension/zpagesextension/generated_component_test.go
processor/batchprocessor/generated_component_test.go
processor/memorylimiterprocessor/generated_component_test.go
receiver/nopreceiver/generated_component_test.go
receiver/otlpreceiver/generated_component_test.go

Reverts open-telemetry/opentelemetry-collector#9765
We need to revert those changes as contrib has issues with them in isolation from #9750.

Revert "[chore] change the way we unmarshal the config in tests"

---

cmd/mdatagen/loader_test.go
cmd/mdatagen/metricdata.go

Reverts open-telemetry/opentelemetry-collector#9760
Trying to make contrib happy. We will be back with a unit test covering contrib's usage of mdatagen.

Revert "[chore] Refactor mdatagen unmarshaling to use less custom Unmarshalers"

---

component/telemetry.go

`ReportComponentStatus` is now deprecated, and `ReportStatus` is used instead.

[chore] use the new function name in comment

---

cmd/mdatagen/internal/samplereceiver/documentation.md
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_config.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_config_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/testdata/config.yaml
cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/loader_test.go

Making sure we can test input_type moving forward.
Fixes #9777

[chore] add new metric with input_type configuration

---

.chloggen/deprecate-SanatizedEndpoints.yaml
config/configgrpc/configgrpc.go
exporter/otlpexporter/config.go
exporter/otlpexporter/config_test.go
exporter/otlpexporter/testdata/invalid_configs.yaml

Deprecates `configgrpc.SanitizedEndpoint()`.
Works towards: https://github.com/open-telemetry/opentelemetry-collector/issues/9482

[configgrpc] Deprecate SanitizedEndpoint

---

processor/memorylimiterprocessor/internal/mock_exporter.go
processor/memorylimiterprocessor/memorylimiter_test.go

Peeling this set of changes from #9584 as a separate PR.
These changes allow a reduction of issues when working with ARM64, which seems to fail on some of the resource locking used in those tests.

[chore] rework memorylimiter test to avoid flaky tests

---

service/internal/status/status.go

Remove deprecated functions `ReportComponentStatus` and `ReportComponentOkIfStarting`
See #9148

[chore][status] Remove deprecated functions `ReportComponentStatus` and `ReportComponentOkIfStarting`

---

.chloggen/remove_deprecated_scrapercontrollersettings.yaml
receiver/scraperhelper/config.go

Remove deprecated `ScraperControllerSettings` and `NewDefaultScraperControllerSettings`
#6767

[receiver] Remove deprecated `ScraperControllerSettings` and `NewDefaultScraperControllerSettings`

---

.chloggen/remove_deprecated_interfaces_connector.yaml
connector/logs_router.go
connector/metrics_router.go
connector/traces_router.go

Remove deprecated interfaces LogsRouter, MetricsRouter and TracesRouter.
Follow up to #9095

[connector] Remove deprecated interfaces LogsRouter, MetricsRouter and TracesRouter

---

.chloggen/remove_deprecated_err.yaml
component/component.go

Remove deprecated error `ErrNilNextConsumer`
Fixes #9322

[component] Remove deprecated error `ErrNilNextConsumer`

---

.chloggen/configgrpc-remove-deprecated-func.yaml
.chloggen/configgrpc-remove-deprecated-func2.yaml
config/configgrpc/configgrpc.go
config/configgrpc/configgrpc_test.go

Removes deprecated `ToServer`.
Deprecate `ToServerContext`
Add new `ToServer` with `context.Context`.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/9490

[configgrpc] Remove deprecated func, add ToServer with context

---

.chloggen/fix-batch-processor-goroutine-leak.yaml
processor/batchprocessor/batch_processor.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/9739 
Replaces https://github.com/open-telemetry/opentelemetry-collector/pull/9814

Prevent starting unnecessary goroutines

---

.chloggen/configtls-fix-IncludeSystemCACertsPool-bug.yaml
config/configtls/configtls.go
config/configtls/configtls_test.go

Updates `ServerConfig` and `ClientConfig` to use `IncludeSystemCACertsPool` when doing `LoadTLSConfig`. Previously `IncludeSystemCACertsPool` was only used for `ServerConfig`'s `ClientCAs` via `newClientCAsReloader`.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9789
**Testing:** 
Added more tests

[configtls] Update IncludeSystemCACertsPool to be used in server and client RootCAs

---

.chloggen/validate-otlpexporter-port.yaml
exporter/otlpexporter/config.go
exporter/otlpexporter/config_test.go
exporter/otlpexporter/testdata/invalid_configs.yaml

**Description:** This PR updates the otlp exporter config validation to ensure that the "endpoint" specified for the exporter includes a port. The goal of this is to fail fast if the configuration is invalid instead of waiting for an error to arise. The PR adds a function to the ClientConfig defined in configgrpc that parses the port defined in the endpoint. The otlp exporter uses this port parsing to validate that 
**Link to tracking Issue:** [Issue 9505](https://github.com/open-telemetry/opentelemetry-collector/issues/9505)
**Testing:** 
configgrpc:
- Add unit tests to validate ports are correctly parsed in configrpc and that an error is returned if the port is omitted
otlpexporter:
- Add unit test for conifg validation function to ensure that the validation fails for missing endpoint …

[otlp exporter] Validate exporter endpoint has port

---

.chloggen/fix-validate-command.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
otelcol/go.mod
otelcol/internal/configunmarshaler/configs.go
otelcol/internal/configunmarshaler/configs_test.go

Fixes issue where validate command was not properly printing valid values.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9863
**Testing:**
Updated unit tests

Fix validate command

---

cmd/mdatagen/statusdata.go

Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30657
This removes all distributions linked to this repository maintained outside of OpenTelemetry.

[chore] Remove vendor distributions mentions in metadata.yaml

---

.chloggen/batch-exporter-helper.yaml
exporter/exporterhelper/batch_sender.go
exporter/exporterhelper/batch_sender_test.go
exporter/exporterhelper/common.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go

Introduce default batching functionality based on the internal data type (pdata). This makes the exporter batching capability available to the regular exporter helpers without using custom requests.
Updates #8122

[exporterhelper] Add default batching for OTLP data type

---

confmap/confmap_test.go

**Description:** Adds two tests to confmap to test some edge cases
**Link to tracking Issue:** Written while reviewing #9862

[chore] Adds two confmap tests

---

.chloggen/embedded_unmarshaler.yaml
confmap/confmap.go
confmap/confmap_test.go
confmap/doc_test.go

This is taking a small slice of #9750 to document the behavior of confmap and make sure we can unmarshal embedded structs.

[confmap] support unmarshaling for embedded structs with and without squashing

---

receiver/otlpreceiver/internal/errors/errors.go
receiver/otlpreceiver/internal/errors/errors_test.go
receiver/otlpreceiver/otlphttp.go

This PR slightly refactors the otlp receiver's HTTP error handling. The result is a few less calls to `status.FromError`, increased accuracy in the grpc code included in the body of the response, and centralizing http<->grpc mapping in the `internal/errors` package.
This PR intentionally changes how we map from HTTP status code to grpc `Status.code`. I don't consider this to be a breaking change, or even worthy of a changelog, since the specification states that `"The clients are not expected to alter their behavior based on Status.code field but MAY record it for troubleshooting purposes."` Honestly, I'd be ok if we chose to stop including the `Status.code` entirely as it leads to more confusion in the code and payload in my opinion.
Closes …

[receiver/otlp] Refactor http error handling

---

.github/workflows/build-and-test.yml

The `build-and-test` workflow has been failing consistently the last few days on the upload coverage step. The reason is outlined in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32259.
Contrib issue, but same underlying cause: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32259
None yet, the CI/CD tests on this PR should be successful if this works.

[chore][CI/CD] Fix failing codecov uploads

---

docs/platform-support.md

This is a documentation change reflecting the progress we have made in supporting Linux ARM64 type machines.
We now run both core and contrib builds on Ampere machines, supported by the CNCF, through Actuated github action runners.
This PR fixes #9731

Move arm64 to platform support tier 2

---

config/configtls/configtls.go
exporter/exporterhelper/request.go

Not prefixing the Deprecated godoc with a newline (or it being the only godoc) appears to cause intellisense/linters some pain.

[chore] fix deprecation godoc

---

.chloggen/codeboten_dep-context-methods.yaml
config/confighttp/compression_test.go
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
exporter/otlphttpexporter/otlp.go
receiver/otlpreceiver/otlp.go

Replaced by ToClient, ToServer, ToListener
Related to #9807

[confighttp] deprecate ToClientContext, ToServerContext, ToListenerContext

---

cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/testdata/config.yaml
cmd/mdatagen/templates/config.go.tmpl
cmd/mdatagen/templates/metrics.go.tmpl
cmd/mdatagen/templates/metrics_test.go.tmpl
cmd/mdatagen/templates/testdata/config.yaml.tmpl

- Make sure we always pass a string to the filter.Match even if the attribute value has a different type. Otherwise, it panics.
- Make sure we show the if_configured warning if the user sets include/exclude without enabled.
- Simplify generated tests
Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/9660

[cmd/mdatagen] [chore] Small fixes for new resource attributes filter

---

.chloggen/bnchmk-zstd.yaml
config/confighttp/compressor.go
config/confighttp/compressor_test.go

**Description:** zstd benchmark tests added
The goal of this PR is to disable concurrency in zstd compression to reduce its memory footprint and avoid a known issue with goroutine leaks. Please see - https://github.com/klauspost/compress/issues/264
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/8216
**Testing:** Benchmark test results below
```
BenchmarkCompression/zstdWithConcurrency/compress-10         	   21392	     55855 ns/op	187732.88 MB/s	 2329164 B/op	      28 allocs/op
BenchmarkCompression/zstdNoConcurrency/compress-10           	   29526	     39902 ns/op	262787.42 MB/s	 1758988 B/op	      15 allocs/op
input => 10.00 MB
```

Disable concurrency in zstd and add Benchmark tests for it

---

config/configgrpc/configgrpc.go
receiver/otlpreceiver/internal/logs/otlp_test.go
receiver/otlpreceiver/internal/metrics/otlp_test.go
receiver/otlpreceiver/internal/trace/otlp_test.go
receiver/otlpreceiver/otlp_test.go

DialContext was marked as deprecated https://github.com/grpc/grpc-go/releases/tag/v1.63.1

[chore] remove usage of deprecated funcs

---

.chloggen/codeboten_fix-sampler-typo.yaml
service/telemetry/otel_trace_sampler.go

The configuration for the recordSampler has multiple configurations for the RemoteParentSampler which doesn't appear to make any sense. I suspect the original intent was to configure both local and remote samplers with sampled and not sampled.

[service] fix bug in sampler

---

cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/testdata/config.yaml
cmd/mdatagen/templates/metrics_test.go.tmpl
cmd/mdatagen/templates/testdata/config.yaml.tmpl

Unblocking https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32394, again

[chore] [mdatagen] Fix generated tests for include/exclude capability

---

.chloggen/update-internal-metric-levels.yaml
config/configgrpc/configgrpc.go
config/configgrpc/go.mod
config/confighttp/confighttp.go
otelcol/unmarshaler.go
processor/batchprocessor/metrics.go

This change distributes the reported internal metrics across available levels and updates the level set by default:
1. The default level is changed from `basic` to `normal`, which can be overridden with `service::telmetry::metrics::level` configuration.
2. The following batch processor metrics are updated to be reported starting from `normal` level instead of `basic` level:
- `processor_batch_batch_send_size`
- `processor_batch_metadata_cardinality` 
- `processor_batch_timeout_trigger_send` 
- `processor_batch_size_trigger_send` 
3. The following GRPC/HTTP server and client metrics are updated to be reported starting from `detailed` level: 
- `http.client.*` metrics 
- `http.server.*` metrics 
- `rpc.server.*` metrics 
- `rpc.client.*` metrics …

Distribute internal metrics across different levels

---

cmd/mdatagen/templates/package_test.go.tmpl

Ensure setup/teardown are respected even when goleak is skipped.

[chore] update package test template

---

.github/workflows/build-and-test-windows.yaml
Makefile.Common

Bump the timeout for the Windows unit tests from 120s to 240s. The tests currently are brushing up very close to this limit and are becoming flaky as a result.
[Example run](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/8739137193/job/23984602883?pr=9516#step:5:19):
```
ok  	go.opentelemetry.io/collector/cmd/builder/internal/builder	116.086s
```

[chore] Double Windows unit tests timeout

---

cmd/builder/internal/builder/main_test.go

Improves `TestVersioning` added on #9897.
The configurations were not what one would usually find, since when running the builder we do some validation and setup.
This makes it closer to the real case.
In the process I removed the 'invalid' cases, since these error out today already

[cmd/builder] Improve TestVersioning

---

.github/workflows/build-and-test-windows.yaml
Makefile.Common
cmd/builder/internal/builder/main.go
cmd/builder/internal/builder/main_test.go

Partially reverts #9897. This was not documented on the original PR and is IMO too strict. 
We likely want to allow for some skew between versions.
Mentioned on https://github.com/open-telemetry/opentelemetry-collector/pull/9513#issuecomment-2065586307

[cmd/builder] Remove undocumented strictness check

---

.chloggen/metric-metadata.yaml
pdata/internal/cmd/pdatagen/internal/pmetric_package.go
pdata/pmetric/generated_metric.go
pdata/pmetric/generated_metric_test.go

After https://github.com/open-telemetry/opentelemetry-collector/pull/9985, add support for the new metric.metadata field in the pmetric package.
I plan to use the metric.metadata field to support additional prometheus types per https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#metric-metadata

Support metric.metadata in pdata/pmetric

---

.chloggen/builder-strict-versioning.yaml
cmd/builder/README.md
cmd/builder/internal/builder/main.go

When building from a commit hash, I got this error:
```
Error: mismatch in go.mod and builder configuration versions: core collector version calculated by component dependencies "v0.98.1-0.20240416174005-d0f15e2463f8" does not match configured version "v0.98.0". Use --skip-strict-versioning to temporarily disable this check. This flag will be removed in a future minor version
```
It may be more useful to only compare the major and minor versions
https://github.com/open-telemetry/opentelemetry-collector/issues/9896
Found in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32544
updated readme

[builder] only compare major and minor versions from gomod

---

.chloggen/builder-confmap-providers.yaml
cmd/builder/README.md
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go
cmd/builder/internal/builder/main.go
cmd/builder/internal/builder/main_test.go
cmd/builder/internal/builder/templates/go.mod.tmpl
cmd/builder/internal/builder/templates/main.go.tmpl
cmd/builder/internal/command.go
cmd/builder/internal/config/default.yaml
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/main.go

Allow configuring confmap providers in the builder's config. If the field isn't set, the default set of providers is used.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/4759.
**Testing:**
Extended unit tests.
Updated the readme to include the new options in the example manifest file.
cc @mx-psi

[cmd/builder] Allow configuring confmap providers

---

cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_config.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/testdata/config.yaml
cmd/mdatagen/templates/config.go.tmpl
cmd/mdatagen/templates/metrics.go.tmpl
cmd/mdatagen/templates/testdata/config.yaml.tmpl

The `include` and `exclude ` options in the resource attributes group sound confusing. It's easy to assume that matching filters will include or exclude resource attributes themselves while they control emitted resource metrics.
The proposal is to change the include/exclude options to `metrics_include`/`metrics_exclude` with detailed comments. These names make it cleaner that matching rules limit the emitted metrics, not resource attributes.
Updates https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25134

[mdatagen] Rename include/exclude config options

---

.chloggen/json-metric-metadata.yaml
pdata/pmetric/json.go
pdata/pmetric/json_test.go

Follow-up to https://github.com/open-telemetry/opentelemetry-collector/pull/10006, which added metric.metadata to pmetric.
I forgot to add support for parsing the field from JSON in that PR.  This PR adds the missing support.
Unit tests

Support parsing metric.metadata from OTLP JSON

---

CONTRIBUTING.md
Makefile
cmd/builder/Makefile
cmd/builder/README.md

This has been set to `on` by default since Go 1.16: https://go.dev/doc/go1.16#go-command.

[chore] Remove GO111MODULE references

---

renovate.json

This follows the monorepo preset pattern here: https://docs.renovatebot.com/presets-monorepo/#monorepoopentelemetry-go

[chore] group contrib packages

---

.github/workflows/check-links.yaml

this addresses a security concern around the version of the package installed

[chore] pin version of npm package

---

.chloggen/expose-err-queue-full.yaml
exporter/exporterqueue/queue.go

Marked as experimental as it is the Queue.

Allow receivers/processors to know when the queue is full

---

.chloggen/batch-sender-fix-enabled-config.yaml
exporter/exporterhelper/batch_sender_test.go
exporter/exporterhelper/common.go

`enabled` config option for batch sender was ignored. This PR fixes it.

[exporterhelper] Fix `enabled` config option for batch sender

---

cmd/mdatagen/go.mod
cmd/mdatagen/validate.go

[chore] remove multierr use in mdatagen

---

.chloggen/revert-validate-pipeline-types.yaml
otelcol/collector.go
otelcol/collector_test.go

This PR reverts the change made in https://github.com/open-telemetry/opentelemetry-collector/pull/9257 due to problems reported in https://github.com/open-telemetry/opentelemetry-collector/issues/10031.
Fixes #10031.

Revert pipeline type validation

---

docs/rfcs/logging-before-config-resolution.md

This is an RFC to help us decide how we want `otelcol` to provide a logger before the primary logger is created. As we discuss I will update the doc.  Before this is merged we should have decided on a solution and the Accepted Solution section must be updated.
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/10056
This unblocks:
- https://github.com/open-telemetry/opentelemetry-collector/issues/9162
- https://github.com/open-telemetry/opentelemetry-collector/issues/5615

[otelcol] rfc for how to log during startup

---

.github/workflows/build-and-test.yml

It's unclear why the retry action is failing to pass in the secret, trying to standard codecov action with a token as per codecov documentation.

[chore] try to fix coverage step

---

.chloggen/codeboten_mdatagen-for-batch-metrics.yaml
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/loader.go
cmd/mdatagen/loader_test.go
cmd/mdatagen/metadata-schema.yaml
cmd/mdatagen/metricdata.go
cmd/mdatagen/templates/telemetry.go.tmpl
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/batchprocessor/metadata.yaml
processor/batchprocessor/metrics.go

This updates mdatagen to generate internal telemetry for components based on metadata.yaml configuration.
Added tests to mdatagen and updated the batch processor to use this as well for synchronous counters and histogram

[mdatagen] use mdatagen to produce component internal telemetry

---

.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test.yml

This is the same as was done in contrib.

[chore] split arm builds into their own workflow

---

.chloggen/fix_skip_goleak.yaml
cmd/mdatagen/templates/package_test.go.tmpl

Tests are currently not being run when `goleak` checks are skipped. This is because `TestMain` is called in the generated file, and needs to call `m.Run()` to properly run the package's tests. This call was missing.
Fixes #10125
There aren't any `goleak` checks currently being skipped in core from the generated package tests, but there are quite a few in `contrib`. This will fix the skipped tests in `contrib`.

[mdatagen] Run tests when skipping goleak

---

exporter/exporterhelper/batch_sender_test.go
exporter/exporterhelper/common_test.go
exporter/exporterhelper/queue_sender_test.go
exporter/exporterhelper/retry_sender_test.go

`newBaseExporter` needs a `DataType` - up until now we've been passing in a `Type`.  In preparation of splitting `DataType` and `Type`, pass in a real `DataType`.
related to https://github.com/open-telemetry/opentelemetry-collector/issues/9429
In preparation for https://github.com/open-telemetry/opentelemetry-collector/pull/10069

ExporterHelper tests - switch to DataType instead of Type

---

processor/memorylimiterprocessor/memorylimiter_test.go

In an upcoming PR, I change Type to be an interface.  This means the zero value of Type will be nil - which will cause this test to fail.  Initializing ID instead of relying on the zero value fixes this
related to https://github.com/open-telemetry/opentelemetry-collector/issues/9429
In preparation for https://github.com/open-telemetry/opentelemetry-collector/pull/10069

MemoryLimiterProcessor - switch to  MustNewID instead of zero value ID

---

.chloggen/deprecate-confmap-new.yaml
confmap/converter/expandconverter/expand.go
confmap/provider/envprovider/provider.go
confmap/provider/envprovider/provider_test.go
confmap/provider/fileprovider/provider.go
confmap/provider/httpprovider/provider.go
confmap/provider/httpsprovider/provider.go
confmap/provider/yamlprovider/provider.go

Each of these was deprecated in v0.99.0, so I think removing them in v0.101.0 is a safe deprecation period for an API that is likely only used by vendor distros built without ocb.
If we would like to extend the deprecation period or break this change into PRs for each module, let me know and I'll make the necessary changes.

[confmap] Deprecate `NewWithSettings` and `New`

---

.chloggen/confmap-converter-logger.yaml
confmap/converter.go
confmap/converter/expandconverter/expand.go
confmap/converter/expandconverter/expand_test.go
confmap/resolver.go
confmap/resolver_test.go
otelcol/collector.go

Adds a Logger to ConverterSettings to enable logging from within converters. Also update the expand converter to log a warning if the env var is empty or missing.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9162
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/5615
Unit tests and local testing
```yaml
receivers:
nop:
exporters:
otlphttp:
endpoint: http://0.0.0.0:4317
headers:
x-test: $TEMP3
debug:
verbosity: $TEMP
service:
telemetry:
logs:
level: info
pipelines:
traces:
receivers:
- nop
exporters:
- otlphttp
- debug
```
Added godoc comments

[confmap] Add logger to ConverterSettings

---

pdata/internal/cmd/pdatagen/internal/base_fields.go

This adds an `originFieldName` option to `sliceField`, `messageValueField` and `primitiveField`.
This option already exists for `primitiveTypedField`, `oneOfField`, `oneOfPrimitiveValue` and `oneOfMessageValue`.
This is needed for #10109.
This is unit tested.
cc @mx-psi

Add origin field name option to base fields

---

.chloggen/string-encoding.yaml
confmap/internal/mapstructure/encoder.go
confmap/internal/mapstructure/encoder_test.go

Our check for determining whether a map key can be encoded as a string is too restrictive and doesn't into account types which are essentially aliases for the string type and don't implement `UnmarshalText`.
I encountered this while trying to call `(confmap.Conf).Marshal(*otelcol.Config)` when the config includes a Prometheus receiver, which includes the [LabelName type](https://github.com/prometheus/common/blob/main/model/labels.go#L98) that does not implement an unmarshaling method. We can't guarantee that all types will implement this, and [Go's print formatters check](https://github.com/golang/go/blob/master/src/fmt/print.go#L803) whether `(reflect.Value).Kind()` equals `reflect.String`, so I think this will be an overall more robust approach.
I added two test cases to demonstrate …

[confmap] Encode string-like map keys 

---

.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test.yml

as per dependabot security recommendations

[chore] appease versioning warnings

---

.chloggen/remove-confmap-instances.yaml
confmap/resolver.go
confmap/resolver_test.go

These fields were deprecated in v0.99.0 and aren't used in any upstream repositories.
These appear to still be used in downstream distributions. If we want to lengthen the deprecation period for these fields, I'll open a PR to instead set a timeline for their removal.

[confmap] Remove deprecated ResolverSettings fields

---

CONTRIBUTING.md
component/component.go
docs/internal-architecture.md
otelcol/collector.go
service/internal/graph/graph.go

Creates an internal architecture file.  In it is a diagram of the startup flow of the collector as well as links to key files / packages.  I also added package level comments to some key packages.
I wrote some other documentation in https://github.com/open-telemetry/opentelemetry-collector/pull/10029 but split the PRs up.

Documentation improvements  - Internal Architecture Doc + Package level comments

---

cmd/builder/internal/builder/main_test.go

Updates `TestReplaceStatementsAreComplete` to check the modules used in replace statements to ensure that their dependencies also have replace statements. This will catch the error that happened in #10188 before a release is started.
The one caveat here is that the test may need to be run multiple times if there are modules deep in the dependency tree that haven't been added to the list of replace statement modules. In essence, the user has to do a BFS walk of the dependency tree themselves by running the tests until all missing modules are caught. We could automate this process with additional code to report all missing modules at once regardless of depth, but I figure it's not worth the extra complexity in the test for such a small gain.
I tested this on the #10188 branch by removing …

[chore][cmd/builder] Improve missing replace statements test

---

cmd/mdatagen/main_test.go
cmd/mdatagen/metadata-schema.yaml
cmd/mdatagen/testdata/invalid_telemetry_missing_value_type_for_histogram.yaml
cmd/mdatagen/testdata/with_telemetry.yaml

This PR adds basic tests for the telemetry generation, and fixes the documentation about value type being required for histograms.

[mdatagen] Add basic telemetry test

---

.golangci.yml

This addresses some of the following warnings:
```
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`.
WARN [config_reader] The configuration option `run.skip-dirs-use-default` is deprecated, please use `issues.exclude-dirs-use-default`.
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats`
WARN [config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`.
WARN [config_reader] The configuration option `linters.errcheck.ignore` is deprecated, please use `linters.errcheck.exclude-functions`.
```

[chore] update lint configuration

---

pdata/plog/plogotlp/grpc_test.go
pdata/pmetric/pmetricotlp/grpc_test.go
pdata/ptrace/ptraceotlp/grpc_test.go
receiver/otlpreceiver/internal/logs/otlp_test.go
receiver/otlpreceiver/internal/metrics/otlp_test.go
receiver/otlpreceiver/internal/trace/otlp_test.go
receiver/otlpreceiver/otlp_test.go

Updating grpc.Dial -> grpc.NewClient, removing grpc.WithBlock as it's not recommended https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md#the-wrong-way-grpcdial. We may need to add code in the future to wait for state to be connected, but in my local tests, there was no flakiness introduced with this change.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10194

[chore] replace deprecated calls

---

.golangci.yml

Same as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33192

[chore] disable gosec checks that cause performance issues

---

cmd/mdatagen/metadata-schema.yaml

Apparently there's an error on the schema for the telemetry node: looking at a working example, I see this:
```
telemetry:
metrics:
processor_tail_sampling_sampling_decision_latency:
description: Latency (in microseconds) of a given sampling policy
unit: µs
enabled: true
histogram:
value_type: int
```
However, the current schema seems to indicate that the `metrics` node shouldn't be there. This PR brings the schema to be in-line with the code.

[chore] fix schema for telemetry/metrics/<metric-name>

---

.chloggen/codeboten_fix-batchprocessor-bug.yaml
processor/batchprocessor/metrics.go

[batchprocessor] fix broken processor_batch_metadata_cardinality metric

---

.github/workflows/generate-semantic-conventions-pr.yaml

The automation script that runs on a cron to auto-generate PRs for new semconv updates has been failing since it was created. This PR fixes a couple of issues w/ the workflow that were preventing it from working.

[chore]fix semconv script

---

exporter/exporterhelper/obsexporter_test.go
processor/batchprocessor/metrics_test.go
processor/processorhelper/obsreport_test.go
receiver/receiverhelper/obsreport_test.go
receiver/scraperhelper/obsreport_test.go

This is no longer needed since we're not testing WithOTel and WithOpenCensus.

[chore] remove WithOTel test wrapper

---

processor/batchprocessor/batch_processor_test.go
processor/batchprocessor/documentation.md
processor/batchprocessor/go.mod
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/batchprocessor/metadata.yaml
processor/batchprocessor/metrics.go

Follows https://github.com/open-telemetry/opentelemetry-collector/pull/10232, use mdatagen for async counter

[batchprocessor] use mdatagen for async metric

---

.chloggen/embedded_struct_unmarshaler.yaml
cmd/mdatagen/internal/samplereceiver/generated_component_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_config_test.go
cmd/mdatagen/templates/component_test.go.tmpl
cmd/mdatagen/templates/config_test.go.tmpl
component/config.go
component/config_test.go
connector/forwardconnector/generated_component_test.go
exporter/debugexporter/config_test.go
exporter/debugexporter/generated_component_test.go
exporter/loggingexporter/config_test.go
exporter/loggingexporter/generated_component_test.go
exporter/nopexporter/generated_component_test.go
exporter/otlpexporter/config_test.go
exporter/otlpexporter/generated_component_test.go
exporter/otlphttpexporter/config_test.go
exporter/otlphttpexporter/generated_component_test.go
extension/ballastextension/config_test.go
extension/ballastextension/generated_component_test.go
extension/memorylimiterextension/generated_component_test.go
extension/zpagesextension/config_test.go
extension/zpagesextension/generated_component_test.go
internal/memorylimiter/config_test.go
otelcol/internal/configunmarshaler/configs.go
processor/batchprocessor/config_test.go
processor/batchprocessor/generated_component_test.go
processor/memorylimiterprocessor/generated_component_test.go
receiver/nopreceiver/generated_component_test.go
receiver/otlpreceiver/config_test.go
receiver/otlpreceiver/generated_component_test.go

This PR removes the top level if/else in `component.UnmarshalConfig`, handling recursive state in the confmap.Conf object instead.
This PR deprecates `component.UnmarshalConfig` in favor of calling directly `Unmarshal` on the confmap.Conf object.
Fixes #7102
Fixes #7101

[config] Deprecate component.UnmarshalConfig

---

cmd/mdatagen/README.md

[chore] Fix link to generated tests

---

.chloggen/fix-batcher-sender-shutdown-deadlock.yaml
exporter/exporterhelper/batch_sender.go
exporter/exporterhelper/batch_sender_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10255

[exporterhelper] Fix potential deadlocks in BatcherSender shutdown

---

confmap/provider.go

Remove a TODO comment on confmap/provider.go related to ChangeEvent. This struct is used extensively in providers that rely on changes such as:
https://github.com/signalfx/splunk-otel-collector/blob/main/internal/configsource/etcd2configsource/source.go#L84

[chore] remove TODO from confmap code

---

.chloggen/otelcol-remove-deprecations.yaml
otelcol/collector.go
otelcol/collector_test.go
otelcol/command.go
otelcol/command_components_test.go

Removes the deprecated `ConfigProvider` field from `CollectorSettings`.

[otelcol] Removed deprecated `ConfigProvider` field from settings

---

.chloggen/jpkroehling_set-maxrequestbodysize-to-compressed.yaml
config/confighttp/compression.go
config/confighttp/compression_test.go
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go

This change applies a restriction on the size of the decompressed payload. Before this change, this is the result of the test added in this PR:
```
--- FAIL: TestServerWithDecompression (0.03s)
/home/jpkroehling/Projects/src/github.com/open-telemetry/opentelemetry-collector/config/confighttp/confighttp_test.go:1327: 
Error Trace:	/home/jpkroehling/Projects/src/github.com/open-telemetry/opentelemetry-collector/config/confighttp/confighttp_test.go:1327
/usr/lib/golang/src/net/http/server.go:2166
/home/jpkroehling/Projects/src/github.com/open-telemetry/opentelemetry-collector/config/confighttp/compression.go:163
/home/jpkroehling/Projects/src/github.com/open-telemetry/opentelemetry-collector/config/confighttp/confighttp.go:455
/usr/lib/golang/src/net/http/server.go:2166 …
```

[confighttp] Apply MaxRequestBodySize to the result of a decompressed body

---

.chloggen/fix_batch_sender_chaining.yaml
exporter/exporterhelper/batch_sender.go
exporter/exporterhelper/batch_sender_test.go

This change fixes a bug when the retry and timeout logic was not applied with enabled batching. The batch sender was ignoring the next senders in the chain.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10166

[exporterhelper] Fix batch sender ignoring next senders in the chain

---

.chloggen/fix_batch_sender_shutdown.yaml
exporter/exporterhelper/batch_sender.go
exporter/exporterhelper/batch_sender_test.go

Fix a bug where shutdown hangs if batch_sender exporter is not started. The bug causes generated component tests to fail as well.
Fixes #10306

[exporterhelper] Fix shutdown hang on unstarted exporter

---

cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/templates/telemetry.go.tmpl
exporter/exporterhelper/internal/metadata/generated_telemetry.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/processorhelper/internal/metadata/generated_telemetry.go
receiver/receiverhelper/internal/metadata/generated_telemetry.go
receiver/scraperhelper/internal/metadata/generated_telemetry.go

This will be used in a follow up PR that allows initialization of optional internal metrics which address the queue metric use-case.

[mdatagen] make meter a struct member of telemetryBuilder

---

.chloggen/confighttp-customroundtripper.yaml
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go

Deprecates the `CustomRoundTripper` field on `confighttp.ClientConfig`, which is unused outside tests in Contrib and causes errors because it cannot be unmarshaled or marshaled. Additionally, having a non-configurable field on a Config struct seems non-ideal.
Soft depends on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33371 so we're not using deprecated APIs.
Fixes #8627
Adapted tests to how the new way of doing this will look. It's slightly less ergonomic (you can't load up all the settings then just run `ToClient`), but we have no examples of this being used by any components, so I'm reluctant to add it to the API.

[confighttp] Deprecate `CustomRoundTripper`

---

.chloggen/jpkroehling-configgrpc-use-own-compressors-for-zstd.yaml
config/configgrpc/configgrpc.go
config/configgrpc/configgrpc_benchmark_test.go
config/configgrpc/go.mod
config/configgrpc/internal/zstd.go
config/configgrpc/internal/zstd_test.go
receiver/otlpreceiver/otlp_test.go

Uses our own version of the zstd compressor for gRPC servers. The code for it is based on the gzip compressor that comes built-in with gRPC. 
Benchmarks before this PR:
```
Running tool: /usr/bin/go test -benchmem -run=^$ -bench ^BenchmarkCompressors$ go.opentelemetry.io/collector/config/configgrpc
sm_log_requestgoos: linux
goarch: amd64
pkg: go.opentelemetry.io/collector/config/configgrpc
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
BenchmarkCompressors/sm_log_request/raw_bytes_160/compressed_bytes_162/compressor_gzip-16         	   71594	     19066 ns/op	     615 B/op	       4 allocs/op
sm_log_requestBenchmarkCompressors/sm_log_request/raw_bytes_160/compressed_bytes_159/compressor_zstd-16         	  151503	      8544 ns/op	     640 B/op	       6 allocs/op …
```

[configgrpc] Use own compressors for zstd

---

.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test.yml
.github/workflows/tidy-dependencies.yml
cmd/otelcorecol/go.mod
pdata/pprofile/go.mod

[chore] update go to 1.21.11/1.22.4 (#10321)

---

.chloggen/jpkroehling-configgrpc-use-own-compressors-for-zstd.yaml
config/configgrpc/configgrpc.go
config/configgrpc/configgrpc_benchmark_test.go
config/configgrpc/go.mod
config/configgrpc/internal/zstd.go
config/configgrpc/internal/zstd_test.go
receiver/otlpreceiver/otlp_test.go

[configgrpc] Use own compressors for zstd (#10323)

---

.chloggen/batchseder-fix-potential-deadlock.yaml
exporter/exporterhelper/batch_sender.go
exporter/exporterhelper/batch_sender_test.go

Concurrent handling of the flush timeouts can run into a deadlock when a batch is simultaneously sent by reaching the minimum size and flush timeout. The deadlock can happen on the following lines:
- https://github.com/open-telemetry/opentelemetry-collector/blob/115bc8e28e009ca93565dc4deb4cf6608fa63622/exporter/exporterhelper/batch_sender.go#L131
- https://github.com/open-telemetry/opentelemetry-collector/blob/115bc8e28e009ca93565dc4deb4cf6608fa63622/exporter/exporterhelper/batch_sender.go#L87

[exporterhelper] Fix potential deadlock in the batch sender

---

cmd/otelcorecol/README.md
cmd/otelcorecol/builder-config.yaml
go.mod

Documents the purpose of `cmd/otelcorecol` in a new README and in a comment on the builder manifest. Adds note to top-level go.mod.
This is a common point of confusion and was recently confusing for users on the aftermath of CVE-2024-36129
Counterpart to open-telemetry/opentelemetry-collector-contrib/pull/33409

[chore] Clarify that cmd/otelcorecol and top-level go.mod are not the source of the core distro

---

.chloggen/codeboten_create-settings-extension.yaml
cmd/mdatagen/templates/component_telemetry_test.go.tmpl
cmd/mdatagen/templates/component_test.go.tmpl
exporter/internal/queue/persistent_queue_test.go
extension/ballastextension/factory.go
extension/ballastextension/factory_test.go
extension/ballastextension/generated_component_test.go
extension/extension.go
extension/extension_test.go
extension/extensiontest/nop_extension.go
extension/extensiontest/nop_extension_test.go
extension/extensiontest/statuswatcher_extension.go
extension/memorylimiterextension/factory.go
extension/memorylimiterextension/factory_test.go
extension/memorylimiterextension/generated_component_test.go
extension/zpagesextension/factory.go
extension/zpagesextension/factory_test.go
extension/zpagesextension/generated_component_test.go
service/extensions/extensions.go
service/extensions/extensions_test.go
service/service_test.go

This deprecates CreateSettings in favour of Settings. NewNopCreateSettings is also being deprecated in favour of NewNopSettings
Part of #9428

[extension] deprecate CreateSettings -> Settings

---

.chloggen/filter.yaml
filter/config.go

Unexport CombinedFilter, it should not be exported as it implements Filter.

[filter] unexport CombinedFilter

---

.chloggen/codeboten_optional-internal-metric.yaml
cmd/mdatagen/internal/samplereceiver/documentation.md
cmd/mdatagen/internal/samplereceiver/factory.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/internal/samplereceiver/metrics_test.go
cmd/mdatagen/loader.go
cmd/mdatagen/loader_test.go
cmd/mdatagen/metadata-schema.yaml
cmd/mdatagen/templates/telemetry.go.tmpl

This allows metrics to be initialized at a later time as is the case for the queue metrics in exporterhelper which are only initialized if a queue is configured.

[mdatagen] add support for optional internal metrics

---

exporter/exporterhelper/common.go
exporter/exporterhelper/documentation.md
exporter/exporterhelper/internal/metadata/generated_telemetry.go
exporter/exporterhelper/metadata.yaml
exporter/exporterhelper/obsexporter.go
exporter/exporterhelper/queue_sender.go
exporter/exporterhelper/queue_sender_test.go

This uses mdatagen to generate the queue metrics. This will allow users to see the metric in the documentation for exporter helper

[exporterhelper] move queue metrics to mdatagen

---

.chloggen/confmap-fix-log.yaml
confmap/converter/expandconverter/expand.go

Fix a bug where we printed a warning log when we were not expanding a value
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10356
Tested manually

[confmap] Only log error in expandconverter if expansion actually happens

---

exporter/exporterhelper/obsexporter.go
exporter/exporterhelper/queue_sender.go
exporter/exporterhelper/queue_sender_test.go

This was introduced in go 1.21 and removes the need for a custom implementation of the context.
Fixes #9049

[chore] update code to use WithoutCancel

---

docs/release.md

In normal github issues etc, if you `@user`, it makes a link for you. So, it feels weird to see `@user` without a link. Feel free to reject this if it is a cure worse than the disease.

[chore] link release managers

---

.chloggen/jpkroehling_allow-compression-list-to-be-overridden.yaml
config/confighttp/README.md
config/confighttp/compression.go
config/confighttp/compression_test.go
config/confighttp/confighttp.go

- **[confighttp] Allow compression list for a server to be overridden**
- **changelog**

[confighttp] Allow compression list for a server to be overridden

---

confmap/expand.go

expandURI can always be viewed as changing the value as long as no error is returned.

[confmap] remove bool logic from expandURI

---

.golangci.yml

The upstream issue was fixed by https://github.com/golangci/golangci-lint/pull/4748, which was included in release [`v1.59.0`](https://github.com/golangci/golangci-lint/releases/tag/v1.59.0) of `golangci-lint`. From local testing, we're pulling version `v1.59.0` of `golangci-lint`, so the issue should be resolved.
Local runtime with excludes:
```
$ .tools/golangci-lint run -v --enable-only gosec
...
INFO Execution took 1.866075148s
INFO Execution took 1.218805785s
INFO Execution took 1.09527985s
```
Local runtime without excludes:
```
$ .tools/golangci-lint run -v --enable-only gosec
...
INFO Execution took 2.244716429s
INFO Execution took 1.539717296s
INFO Execution took 1.530163777s
```
Note: I ran `.tools/golangci-lint cache clean` between each test to clean the cache and keep results …

[chore][golangci-lint] Remove gosec excludes

---

service/telemetry/internal/factory.go
service/telemetry/telemetry.go

This only impacts internal code, no external impact.

[chore] more CreateSettings renames

---

.github/workflows/check-goreleaser.yaml
cmd/builder/.goreleaser.yml

https://github.com/open-telemetry/opentelemetry-collector/pull/10384 updated `goreleaser` to a new major version and this appears to have [broken the config](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/9565775767/job/26369463094). This problem only became apparent during the release process since the config is not used otherwise.
This PR adds a github action to run `goreleaser check` on all PRs, since changes to the config may not be caught until release is attempted.
I've also included what may be the only necessary change to the config, by [renaming `changelog.skip` to `changelog.disable`](https://github.com/goreleaser/goreleaser/commit/29f30b623ef8f0a19607afab22b3f3a2f9f68172). This passes `goreleaser check` when run locally.
The `monorepo` section of the …

Add goreleaser check and attempt update

---

.github/workflows/builder-release.yaml

This PR changes the trigger for releasing the builder to match the builder module tag. This allows us to release the builder separately by pushing a dedicated tag.

Change builder release trigger to module tag

---

.github/workflows/builder-release.yaml

This causes the goreleaser and gh release steps to conflict as the goreleaser will create a release for the builder tag, and gh release will try to create the same.
See https://github.com/open-telemetry/opentelemetry-collector/actions/runs/9568657405/job/26379389384 for more details

[chore] revert tag trigger change

---

.chloggen/processorhelper-inserted-api.yaml
.chloggen/processorhelper-inserted.yaml
component/componenttest/obsreporttest.go
component/componenttest/otelprometheuschecker.go
component/componenttest/otelprometheuschecker_test.go
component/componenttest/testdata/prometheus_response
processor/processorhelper/documentation.md
processor/processorhelper/internal/metadata/generated_telemetry.go
processor/processorhelper/metadata.yaml
processor/processorhelper/obsreport.go
processor/processorhelper/obsreport_test.go

Resolves #10353
Added equivalent testing to other processor metrics (accepted, refused, dropped).
Metric documentation is autogenerated.
My initial implementation includes a breaking change to `componenttest.TestTelemetry` which is public facing API. If we want to avoid an immediate breaking change in this test package, I would propose the following, which I can submit in a prerequisite PR:
1. Deprecate all `TestTelemetry.Check*` methods.
2. Replace with more granular `TestTelemetry.CheckOneSpecificMetric` methods.

Add "inserted" metrics to processors

---

.chloggen/print-tracestate.yaml
exporter/internal/otlptext/testdata/traces/two_spans.out
exporter/internal/otlptext/traces.go
pdata/testdata/trace.go

Span.TraceState() is not printed, but is a part of the OTel span data model.
Part of 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31918
✅ 
n/a

Print Span.TraceState() in debugexporter

---

docs/release.md

When I performed this step yesterday, I found that it was necessary to update the builder configs first, otherwise `make update-otel` would fail. This PR just updates the order of operations to match what worked for me.

Docs - Update contrib release step 1

---

.chloggen/cookie_support.yaml
config/confighttp/README.md
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go

Add support for cookies in HTTP clients with `cookies::enabled`.
Fixes #10175
Unit test
Added to README

[confighttp] Add support for cookies

---

README.md

Change the collector compatibility promise slightly by committing to building the collector with the latest Go minor version.

[chore] Commit to Building Collector with latest Go minor version

---

service/internal/graph/graph.go
service/internal/graph/graph_test.go
service/internal/servicetelemetry/telemetry_settings.go
service/internal/status/status.go
service/internal/status/statustest/statustest.go
service/internal/status/statustest/statustest_test.go
service/service.go

This PR refactors the service graph initialization so that the graph can be assembled without the intention to start it.
1. Do not save telemetry on the graph. The only use of this was for reporting component status. Instead, pass in a reporter when starting or stopping. Correspondingly, add an internal `statustest` package to make it easy to pass in a status reporter in tests.
2. Decouple graph building from extension building. There isn't any direct relationship so these things should be separated.

[chore] Remove telemetry from graph initialization

---

.chloggen/codeboten_remove-additional-slash.yaml
exporter/otlpexporter/config.go
exporter/otlpexporter/config_test.go

This allows users to continue using the recommended dns://authority/host:port notation when needing to specify a custom authority.
Fixes #10449

[otlpexporter] support validation for dns:// and dns:///

---

VERSIONING.md

We have recently discussed bumping the minimum TLS version to follow security best practices.
Since we are about to stabilize `configtls` (see #10344), I raised the question of whether this would be a breaking change that should be done before 1.0.
I argue that we should be allowed to do this after 1.0 because:
- The Go 1 version compatibility doc states
> Security. A security issue in the specification or implementation may come to light whose resolution requires breaking compatibility. We reserve the right to address such security issues.
- The Go team has made [similar changes](https://github.com/golang/go/issues/45428) in the past for Go as a whole
While this is not a security issue but a security best practice, the golang/go issue seems to indicate that changes like this would be in …

[chore][VERSIONING.md] Changing protocol support for security is allowed

---

.chloggen/localhostgate-info-log.yaml
internal/localhostgate/featuregate.go

Fixes log intended to be logged when the feature gate is enabled, not disabled.
Relates to #8510, updates #10352

[internal/localhostgate] Correctly log message about local host gate

---

cmd/mdatagen/templates/package_test.go.tmpl

When `tests.goleak.skip` flag is set to true, the generated_package_test.go file looks like the following image.
Since `import os` statement is missing, you fail to run the test. I added the missing import in this PR.
Compare the generated generated_package_test.go when tests.goleak.skip flag is toggle from false to true.
**before**
```diff
--- a/receiver/runnreceiver/generated_package_test.go
+++ b/receiver/runnreceiver/generated_package_test.go
@@ -3,10 +3,10 @@
package runnreceiver
import (
-       "go.uber.org/goleak"
"testing"
)
func TestMain(m *testing.M) {
-       goleak.VerifyTestMain(m)
+       // skipping goleak test as per metadata.yml configuration
+       os.Exit(m.Run())
}
```
**after**
```diff
--- a/receiver/runnreceiver/generated_package_test.go
+++ …
```

[mdatagen] bugfix: fix generated package test when skipping goleak, because os package import is forgotten

---

service/telemetry.go

Renames key to avoid conflict in JSON format.
Fixes #10537

[chore] Use different name for telemetry level key

---

cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/testdata/invalid_type_attr.yaml
cmd/mdatagen/testdata/no_type_attr.yaml
cmd/mdatagen/testdata/unused_attribute.yaml
exporter/exporterhelper/metadata.yaml
processor/batchprocessor/metadata.yaml
processor/processorhelper/metadata.yaml
receiver/receiverhelper/metadata.yaml
receiver/scraperhelper/metadata.yaml

Uses string type for `unit` field in mdatagen related files.
Needed for #10554

[chore] Use string for unit type

---

.chloggen/builder-empty-gomod-field.yaml
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go

improving an error message - a missing gomod field would be reported but without informing where in the config the field is missing.
Fixes #10474
Unit tests pass, added some tests for missing cases, manually tested
new error looks like:
```
../../bin/ocb_darwin_amd64 --config=./default.yaml
2024-06-27T11:39:10.316-0700	INFO	internal/command.go:125	OpenTelemetry Collector Builder	{"version": "", "date": "unknown"}
2024-06-27T11:39:10.319-0700	INFO	internal/command.go:161	Using config file	{"path": "./default.yaml"}
Error: invalid configuration: receiver module at index 0: missing gomod specification for module; provider module at index 2: missing gomod specification for module
```

[builder] more information for missing gomod error

---

CONTRIBUTING.md

Reworks 'Target audiences' section to:
1. Reflect the three audiences we have today, distinguishing between component developers and Collector library users
2. Reflect that we encourage end-users to use the OpenTelemetry Collector Builder and that builder compatibility should be a concern when thinking about binary end-users
Relates to #10004

[chore] Update the Collector target audiences

---

.chloggen/configauth-removed-deprecated-funcs.yaml
config/configauth/configauth.go
config/configauth/configauth_test.go
config/configgrpc/configgrpc.go
config/confighttp/confighttp.go

Deprecates GetClientAuthenticatorContext and GetServerAuthenticatorContext.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/9808

[configauth] Deprecate GetClientAuthenticatorContext and GetServerAuthenticatorContext

---

.chloggen/confmap-fix-escape-bug.yaml
confmap/expand.go
confmap/expand_test.go
confmap/go.sum
confmap/resolver.go
confmap/testdata/expand-escaped-env.yaml

When we promoted `confmap.unifyEnvVarExpansion` to beta, we found that the new expansion logic in `confmap` wasn't handling escaping of `$$` like it is supposed to.  This PR fixes that bug, but adding escaping logic for `$$`.
@azunna1 this fixes the bug you mentioned in https://github.com/open-telemetry/opentelemetry-collector/pull/10435 around the metricstransformprocessor:
```yaml
metricstransform:
transforms:
- include: '^k8s\.(.*)\.(.*)$$'
match_type: regexp
action: update
new_name: 'kubernetes.$${1}.$${2}'
- include: '^container_([0-9A-Za-z]+)_([0-9A-Za-z]+)_.*'
match_type: regexp
action: update
new_name: 'container.$${1}.$${2}'
```
Added new unit tests explicitly for escaping logic

[confmap] Fix bug where expand didn't honor escaping

---

.chloggen/exporterhelper-deprecate-obsreport-api.yaml
exporter/exporterhelper/obsexporter.go

Deprecate the obsreport API in the exporterhelper package. The top-level helpers `exporterhelper.New[Metrics|Traces|Logs]Exporter` are supposed to be used instead.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/10592

[exporterhelper] Deprecate the obsreport API

---

.chloggen/fix-http-grpc-error-code-mapping.yaml
receiver/otlpreceiver/internal/errors/errors.go
receiver/otlpreceiver/internal/errors/errors_test.go
receiver/otlpreceiver/otlp_test.go

Fixes a bug where the otlpreceiver was not translating grpc error codes to http status codes the same way that the otlp exporter was translating http status codes to grpc error codes.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10538
Added unit tests

Properly handle error code translation

---

.chloggen/jpkroehling_fix-servicename-own-telemetry.yaml
service/telemetry/factory.go
service/telemetry/tracer.go

This PR bridges the config that is exposed to Collector users to the internal format expected by the config helpers around the tracer provider.
Fixes #10489
Manual testing performed.
Config:
```yaml
receivers:
otlp:
protocols:
http:
grpc:
exporters:
debug:
service:
pipelines:
traces:
receivers: [otlp]
exporters: [debug]
metrics:
receivers: [otlp]
exporters: [debug]
logs:
receivers: [otlp]
exporters: [debug]
telemetry:
traces:
processors:
- batch:
schedule_delay: 1000
exporter:
otlp:
endpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/traces
protocol: http/protobuf
headers:
Authorization: "Basic ..."
metrics:
level: detailed
readers:
- periodic:
exporter:
otlp:
endpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/metrics
protocol: http/protobuf
headers: …
```

[telemetry] Add ability to set service.name for spans emitted by the Collector

---

.github/workflows/build-and-test-arm.yml
docs/platform-support.md

Similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33921

[chore] use macos-14 for arm testing

---

confmap/internal/e2e/types_test.go

Adds more e2e tests to match main's current behavior.  Some of these are weird, and could be used to justify https://github.com/open-telemetry/opentelemetry-collector/pull/10603
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/10603

[chore] Add more e2e tests

---

.chloggen/module-info-builder.yaml
.chloggen/module-info-components.yaml
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/templates/components.go.tmpl
otelcol/command_components.go
otelcol/factories.go
otelcol/factories_test.go
otelcol/testdata/components-output.yaml

Resolves #10570
Alternative to #10598
This implementation is more reliable that #10598 because it gets information directly from the builder manifest. It relies on additional structure in the `component.go` file, ultimately encoded in `otelcol.Factories`.
An alternative would be to push the enhancements deeper, into the `<kind>.Factories` implementations, so that the module information is available directly alongside the Factory.

Enhance builder to capture go module for each component type

---

.chloggen/mdatagen-remove-with-attributes-helper.yaml
cmd/mdatagen/go.mod
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/main.go
cmd/mdatagen/templates/telemetry.go.tmpl
exporter/exporterhelper/internal/metadata/generated_telemetry.go
exporter/exporterhelper/obsexporter.go
exporter/exporterhelper/queue_sender.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/batchprocessor/metrics.go
service/internal/metadata/generated_telemetry.go

Attribute sets for async instruments now can be set as options to callback setters and async instruments initializers. This allows each async instrument to have its own attribute set.
Unblocks https://github.com/open-telemetry/opentelemetry-collector/pull/10593

[mdatagen] Remove WithAttributes from the telemetry builder constructor

---

service/internal/graph/graph_test.go

I noticed that these loops are making the same assertion repeatedly, rather than checking each element.

[chore] Fix mutability assertion loops

---

.chloggen/codeboten_update-all-metrics-with-prefix.yaml
cmd/mdatagen/internal/samplereceiver/documentation.md
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/internal/samplereceiver/metrics_test.go
cmd/mdatagen/templates/documentation.md.tmpl
cmd/mdatagen/templates/telemetry.go.tmpl
component/componenttest/otelprometheuschecker.go
component/componenttest/testdata/prometheus_response
exporter/exporterhelper/documentation.md
exporter/exporterhelper/internal/metadata/generated_telemetry.go
exporter/exporterhelper/queue_sender_test.go
processor/batchprocessor/batch_processor_test.go
processor/batchprocessor/documentation.md
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/processorhelper/documentation.md
processor/processorhelper/internal/metadata/generated_telemetry.go
receiver/receiverhelper/documentation.md
receiver/receiverhelper/internal/metadata/generated_telemetry.go
receiver/scraperhelper/documentation.md
receiver/scraperhelper/internal/metadata/generated_telemetry.go
service/documentation.md
service/internal/metadata/generated_telemetry.go
service/internal/proctelemetry/config.go
service/internal/proctelemetry/process_telemetry_test.go
service/telemetry_test.go

This ensures the consistency for folks emitting metrics w/ OTLP until the OTEP to specify pipeline telemetry is completed.
Waiting on https://github.com/open-telemetry/opentelemetry-collector/pull/9775 before moving this forward
Fixes #9315

update all metrics to include otelcol_ prefix

---

.chloggen/codeboten_configauth-deprecated.yaml
config/configauth/configauth.go

Removes GetServerAuthenticatorContext and GetClientAuthenticatorContext

[configauth] remove deprecated methods

---

service/extensions/extensions.go
service/internal/graph/graph.go

Improved logging of component start errors, so the log lines appear where they chronologically happen, rather than at the end. They also use the component logger, which makes them look nicer.
Output before change:
```text
2024-06-19T14:15:30.822+0200    info    service@v0.103.0/service.go:115 Setting up own telemetry...
2024-06-19T14:15:30.822+0200    info    service@v0.103.0/telemetry.go:96        Serving metrics {"address": ":8888", "level": "Normal"}
2024-06-19T14:15:30.823+0200    info    service@v0.103.0/service.go:182 Starting otelcorecol... {"Version": "0.103.0-dev", "NumCPU": 32}
2024-06-19T14:15:30.823+0200    info    extensions/extensions.go:35     Starting extensions...
2024-06-19T14:15:30.823+0200    info    service@v0.103.0/service.go:245 Starting shutdown... …
```

Improve logging of component start errors

---

service/internal/graph/nodes.go

I noticed some inconsistency in the way we set up loggers for the different component kinds. This change just makes it uniform for all types and I think a little more readable.

[chore] Cleanup logger setup for component kinds

---

.chloggen/jpkroehling-add-query-params-to-authcontext-api.yaml
.chloggen/jpkroehling-add-query-params-to-authcontext.yaml
config/confighttp/README.md
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
extension/auth/server.go
extension/zpagesextension/zpagesextension_test.go

This PR adds a new option to the ServerConfig's Auth option, allowing users to specify a list of query parameters to add to the sources of auth data, in addition to HTTP headers. Instead of simply adding all parameters, which might be numeruous, we require users to specify which ones to include.
Auth extensions don't need to be changed, but should document which attributes they expect to find in the context and how to configure confighttp to accomplish that.
Fixes #4806

[confighttp] Add option to include query params in auth context

---

service/telemetry/tracer.go
service/telemetry/tracer_test.go

This isn't as good as emitting telemetry w/ the service but at least it ensures resource attributes are set.
Follow up to https://github.com/open-telemetry/opentelemetry-collector/pull/10490 and https://github.com/open-telemetry/opentelemetry-collector/pull/10645

[chore] adding minimal test for attributes

---

.chloggen/receiverhelper_metric_units.yaml
receiver/receiverhelper/documentation.md
receiver/receiverhelper/internal/metadata/generated_telemetry.go
receiver/receiverhelper/metadata.yaml

`1` isn't an informative unit for metrics, this should clarify their units.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10650

[receiverhelper] Update metric units

---

.chloggen/scraperhelper_metric_units.yaml
receiver/scraperhelper/documentation.md
receiver/scraperhelper/internal/metadata/generated_telemetry.go
receiver/scraperhelper/metadata.yaml

`1` isn't an informative unit for metrics, this clarifies the unit.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10649

[scraperhelper] Update metric units

---

processor/processorhelper/obsreport.go

This PR removes the `recordData` method, which I believe is an unhelpful abstraction for reporting internal processor metrics.
The drawbacks of the function are minor, but briefly:
1. Recording any metric requires passing in zeros for _all other metrics_. This is cumbersome to extend because any new metric requires updating the call to `recordData` for all metrics. It's also fragile because if we have more than a few metrics it is easy to position the intended metric incorrectly.
2. Every metric describes one data type, which is passed into `recordData` but then just used as a switch to get back to code that is specific to that data type. 
3. Every call to `recordData` instantiates N variables, where N is the number of metrics for each data type.
All of this seems unnecessary as we can …

[chore] Reduce complexity in processorhelper obsreport

---

.chloggen/experimental_include_metadata.yaml
config/configgrpc/configgrpc.go
config/confighttp/confighttp.go

Remove the experimental comment on `IncludeMetadata` in confighttp and configgrpc
Fixes #9381, Fixes #9642

[confighttp, configgrpc] Remove experimental note on IncludeMetadata

---

.chloggen/componenttest-extra-attributes.yaml
.chloggen/exporterhelper-report-data-type-in-queue-metrics.yaml
component/componenttest/obsreporttest.go
component/componenttest/otelprometheuschecker.go
exporter/exporterhelper/common.go
exporter/exporterhelper/obsexporter.go
exporter/exporterhelper/obsreport_test.go
exporter/exporterhelper/queue_sender.go
exporter/exporterhelper/queue_sender_test.go
internal/obsreportconfig/obsmetrics/obs_exporter.go

Add `data_type` attribute to the internal otelcol_exporter_queue_size metric to report the type of data being processed.
All other metrics have the data type reported as part of their names. We could've done the same for queue metrics, but that would introduce a significant breaking change. We want to avoid that until we have all the metrics standardized with OpenTelemetry semantic conventions.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/9943

[exporterhelper] Add data_type attribute to internal queue metrics

---

.chloggen/service-remove-ballast-deps-2.yaml
.chloggen/service-remove-ballast-deps-3.yaml
.chloggen/service-remove-ballast-deps.yaml
internal/memorylimiter/memorylimiter.go
internal/memorylimiter/memorylimiter_test.go
processor/memorylimiterprocessor/memorylimiter_test.go
service/internal/proctelemetry/process_telemetry.go
service/internal/proctelemetry/process_telemetry_linux_test.go
service/internal/proctelemetry/process_telemetry_test.go
service/service.go

This PR removes all ballast logic from service. This effectively deprecates the ballastextension as including the extension with this service would do nothing.
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/10671
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/8342
Unit tests.

[service] Remove getBallastSize from service

---

.chloggen/jpkroehling-grpc-statuscode.yaml
config/configgrpc/configgrpc.go
config/configgrpc/configgrpc_test.go

[configgrpc] Send UNAUTHENTICATED on auth failure

---

.chloggen/mx-psi_validate-uris.yaml
confmap/provider/internal/configurablehttpprovider/provider.go
confmap/provider/internal/configurablehttpprovider/provider_test.go

Validate URLs before fetching. 
Fixes #10468, Relates to #10121

[confmap/provider/http(s)provider] Validate URIs before fetching

---

component/host.go

Adds a note to the `component.Host` interface documenting that components may require additional interfaces.
I think this is the only sustainable pattern post 1.0, since we won't be able to add any new methods to the `component.Host` interface.
This pattern is also used today by:
- The zpages extension (https://github.com/open-telemetry/opentelemetry-collector/blob/91f13c309d00eef5b997a2e810effb2a4ccd95d4/extension/zpagesextension/zpagesextension.go#L58-L66)
- The receiver creator (after open-telemetry/opentelemetry-collector-contrib/pull/34234)
- Some contrib components (open-telemetry/opentelemetry-collector-contrib/pull/32498)
Fixes #10181

[chore][component] Document component.Host expectations

---

pdata/plog/fuzz_test.go
pdata/plog/plogotlp/fuzz_test.go
pdata/pmetric/fuzz_test.go
pdata/pmetric/pmetricotlp/fuzz_test.go
pdata/ptrace/fuzz_test.go
pdata/ptrace/ptraceotlp/fuzz_test.go

Adds fuzz tests for various unmarshaling routines.
This can be tested with `go test -fuzz=`
This is ongoing work for https://github.com/open-telemetry/sig-security/issues/55
Fixes #

Add fuzz tests for unmarshaling routines

---

.chloggen/delete_custom_roundtripper.yaml
config/confighttp/confighttp.go

Delete deprecated `ClientConfig.CustomRoundTripper`
Fixes #8627

[confighttp] delete `ClientConfig.CustomRoundTripper`

---

.chloggen/component-deprecate-GetFactory.yaml
component/componenttest/nop_host_test.go
component/host.go

This PR deprecates the `component.Host.GetFactory` interface. This has the benefit of keeping the `component.Host` interface as simple as possible.  Components that were relying on this method can instead check if the underlying `component.Host` implementation supports the interface.  An example of this pattern can be found here: https://github.com/open-telemetry/opentelemetry-collector/blob/91f13c309d00eef5b997a2e810effb2a4ccd95d4/extension/zpagesextension/zpagesextension.go#L58-L66
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/9511

Deprecate component.Host.GetFactory

---

.github/workflows/prepare-release.yml

From https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#releasing-opentelemetry-collector:
> If not intending to release stable modules, do not specify a version for Release candidate version stable.
`validate-versions` workflow fails on empty version right now, it should instead skip if stable module candidate version is empty.

[chore] skip stable module check if unset

---

.chloggen/mx-psi_fix-106-issue.yaml
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
extension/zpagesextension/zpagesextension_test.go
receiver/otlpreceiver/config_test.go
receiver/otlpreceiver/go.mod
receiver/otlpreceiver/testdata/config.yaml

- Uses `mapstructure:",squash"` instead of `mapstructure:"-"` for the Authenticator field
- Removes pointer (since pointers can't be squashed)
- Adds test in OTLP receiver for this reproducing the user's issue
Fixes #10750

[configauth] Fix unmarshaling of confighttp.AuthConfig

---

.chloggen/mx-psi_fix-106-issue.yaml
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
extension/zpagesextension/zpagesextension_test.go
receiver/otlpreceiver/config_test.go
receiver/otlpreceiver/go.mod
receiver/otlpreceiver/testdata/config.yaml

cherry-pick of https://github.com/open-telemetry/opentelemetry-collector/pull/10749

[configauth] Fix unmarshaling of confighttp.AuthConfig (#10749)

---

docs/ga-roadmap.md

Explicitly excludes service and otelcol from 1.0 efforts.
These modules are useful for distribution maintainers but not end-users, for which the 1.0 effort is targeted.

[chore] Explicitly note that service and otelcol are not part of 1.0

---

.chloggen/component-remove-deprecated-method.yaml
component/host.go

Removes the deprecated `GetFactory` method from the `component.Host` interface
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9511

[component] Remove deprecated `Host.GetFactory` method

---

docs/platform-support.md

I'm volunteering myself to own the tier 2 support for windows/amd64. This will put the windows/amd64 on par with the other tier 2 platforms by having a specific person owning it.
Some of Windows related things that I contribute(d):
* Codeowner of various Windows related components in contrib (pkg/winperfcounters, activedirectorydsreceiver, iisreceiver, windowseventlogreceiver, and windowsperfcountersreceiver)
* Fixing Windows related issues (e.g.: #9042, #9689, #9726, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30743)
* MSI on the collector releases repo (https://github.com/open-telemetry/opentelemetry-collector-releases/pull/560)

Make @pjanotti owner of windows/amd64

---

.chloggen/mx-psi_restrict-providers-scheme.yaml
confmap/expand_test.go
confmap/resolver.go
confmap/resolver_test.go

Validate providers schemes when building a Resolver.
I don't consider this a breaking change since the providers would be useless if they don't follow this pattern.

[confmap] Validate providers scheme when building a Resolver

---

.chloggen/mx-psi_fix-invalid-yaml-string.yaml
confmap/internal/e2e/types_test.go
confmap/provider.go
confmap/provider/envprovider/provider_test.go
confmap/provider/fileprovider/provider_test.go
confmap/provider/internal/configurablehttpprovider/provider_test.go
confmap/provider/yamlprovider/provider_test.go
confmap/provider_test.go

If YAML parsing fails, assume the user wanted to pass the value as a string.
This has the downside that the error messages are less informative: it will tell you it expected something other than a string instead of the YAML parser error.
A future improvement could be to pass these errors down as extra metadata up until the unmarshaling stage.
Fixes #10759
Added test case for this.

[confmap] Use values as string if YAML is invalid

---

.chloggen/mx-psi_remove-has-original.yaml
confmap/confmap.go
confmap/confmap_test.go
confmap/expand.go
confmap/internal/e2e/testdata/issue-10787-main.yaml
confmap/internal/e2e/testdata/issue-10787-snippet.yaml
confmap/internal/e2e/types_test.go

Removes original string representation if invalid.
Fixes #10787
Added e2e test cases

[confmap] Remove original representation if invalid

---

.chloggen/stabilize_client.yaml
versions.yaml

Mark module as stable.
Fixes #9795

[client] mark module as stable

---

.chloggen/mx-psi_add-string-representation-for-everything.yaml
confmap/expand_test.go
confmap/internal/e2e/types_test.go
confmap/provider.go

Allows any type to be used as a string if the target field is a string or the value is expanded in inline position. Inspired by #10794. This is not a breaking change (previously we would return an error for these).
Some things that you can do after this PR that you couldn't do before it:
1. Set `HOST` to `[2001:db8::8a2e:370:7334]` and use it in an endpoint:
```yaml
exporters:
otlp:
endpoint: http://${env:HOST}/api/v1/traces
```
2. Pass really big numbers as strings (e.g. `10000000000000000000`)
3. Pass `null` as a string.
<details>
<summary>Types that can be returned by our current YAML parser</summary>
Our current way of using the YAML parser has these types: `string`, `nil`, `int`, `uint64`, `float64`, `map[any]any`, `map[string]any`, `[]any`. 
There is no documentation for this, but …

[confmap] Allow using any type as a string

---

.chloggen/int-telemetry-otlp-options.yaml
service/internal/proctelemetry/config.go
service/internal/proctelemetry/config_test.go

adds temporality preference option for internal telemetry exported via OTLP
(partly) fixes #10745
unit tests
Feature is already documented, but not implemented yet.

[config] Implement temporality preference option

---

CHANGELOG.md

None of the changelog files have an entry for v0.106.1. Adding the content from the release notes to CHANGELOG.md.

Add missing CHANGELOG.md entry for v0.106.1

---

receiver/otlpreceiver/fuzz_test.go

Adds a fuzz test for the 3 exposed handlers of the receiver: `handleTraces`, `handleMetrics`, `handleLogs`. The fuzzer decides which content type header to set an also which of the handlers to invoke.

add fuzz test for receiver

---

connector/internal/factory.go

Fix an IDE warning about mixing receiver types.

[chore] avoid mixing pointer and non-pointer receiver on struct functions

---

.chloggen/obsexporter.yaml
exporter/exporterhelper/common.go
exporter/exporterhelper/common_test.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/obsexporter.go
exporter/exporterhelper/obsexporter_test.go
exporter/exporterhelper/obsreport_test.go
exporter/exporterhelper/queue_sender.go
exporter/exporterhelper/queue_sender_test.go
exporter/exporterhelper/retry_sender_test.go
exporter/exporterhelper/traces.go

Delete deprecated `exporterhelper.ObsReport` and `exporterhelper.NewObsReport`
Relates to https://github.com/open-telemetry/opentelemetry-collector/issues/10592

[exporterhelper] delete deprecated `exporterhelper.ObsReport`

---

.chloggen/codeboten_semconv-1.26.0.yaml
semconv/semconv_test.go
semconv/template.j2
semconv/v1.26.0/doc.go
semconv/v1.26.0/generated_attribute_group.go
semconv/v1.26.0/generated_event.go
semconv/v1.26.0/generated_resource.go
semconv/v1.26.0/generated_trace.go
semconv/v1.26.0/schema.go

This PR is updating the jinja template to ignore deprecated attributes as was done in https://github.com/open-telemetry/opentelemetry-go/pull/5476. Additonally, generate v1.26.0 semconv package
This replaces https://github.com/open-telemetry/opentelemetry-collector/pull/10249
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10813
NOTE: This leaves empty resource/trace/event files, but I'd rather not remove the methods they expose in this change

[semconv] update template to remove deprecated semconv attributes

---

.github/workflows/generate-semantic-conventions-pr.yaml

This prevents the workflow from trying to push to an existing branch which it doesn't have permissions to do.
An example of the failure can be found here: https://github.com/open-telemetry/opentelemetry-collector/actions/runs/10291429328/job/28483659786

[chore] update workflow to add changelog before pushing

---

exporter/exporterhelper/batch_sender_test.go

Those few ones seem particularly flaky on Windows:
https://github.com/open-telemetry/opentelemetry-collector/issues/10758
https://github.com/open-telemetry/opentelemetry-collector/issues/10802
https://github.com/open-telemetry/opentelemetry-collector/issues/10810

[chore] Skip a few flaky batch sender tests on Windows

---

.chloggen/new_cors_default_config.yaml
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go

Add `NewDefaultCORSConfig` function to initialize the default `confighttp.CORSConfig`
#9655

[confighttp] Add `NewDefaultCORSConfig` function

---

.chloggen/add_default_timeout.yaml
.golangci.yml
config/confighttp/confighttp.go
service/internal/proctelemetry/config.go

Add 10s read header timeout on the configtelemetry Prometheus HTTP server.
Fixes #5699

[configtelemetry] Add a read header timeout of 10s on the configtelemetry Prometheus HTTP server

---

cmd/builder/internal/builder/main_test.go

If the test is executed with the `root` user, the `TestGenerateInvalidOutputPath` test fails.
The behaviour was noticed with a GitLab runner that was executed with root rights.
An attempt is made to create the directory `/:invalid` during the test.
A user without root rights receives the message `cannot create directory '/:invalid': Permission denied`. 
In contrast, the `root` user can create the directory without any problems because this is a valid path.
To correct the behaviour of the test, the path to `:/invalid` was adjusted.
This is not a valid path under Windows or Linux.

[builder] fix the TestGenerateInvalidOutputPath

---

cmd/builder/internal/builder/main.go

Refine the warning message to make it useful for the end user.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10514
Locally tested.
```sh
2024-07-31T22:03:05.984+0900    INFO    internal/command.go:125 OpenTelemetry Collector Builder {"version": "(devel)"}
2024-07-31T22:03:05.984+0900    INFO    internal/command.go:136 Using default build configuration
2024-07-31T22:03:05.985+0900    INFO    builder/config.go:142   Using go        {"go-executable": "/usr/local/bin/go"}
2024-07-31T22:03:05.985+0900    INFO    builder/main.go:77      You're building a distribution with non-aligned version of the builder. The version mismatch may cause the compilation failure. It's recommended to use the same version.       {"collector-version": "0.104.0", "builder-version": …
```

[cmd/builder] clarify mismatched versions in the warning message

---

.github/workflows/build-and-test-windows.yaml
.github/workflows/scripts/win-required-ports.ps1

The default port used by `zpagesextension` is in a range that Windows machines can exclude by default. This change adds a PowerShell script to release the default `zpagesextension` port (55679) on the Windows GH workflows.
Fixes #10811

[chore] Release ports on the dynamic range on Windows runners

---

.github/workflows/generate-semantic-conventions-pr.yaml

This will reference the same issue instead of needing to create a PR and add it to the changelog. Creating a PR and then updating it is not allowed because of the branch protection permissions.

[chore] adding an issue number in the changelog

---

.chloggen/codeboten_mdatagen-expose-scope-name.yaml
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/main_test.go
cmd/mdatagen/templates/telemetry.go.tmpl
exporter/exporterhelper/internal/metadata/generated_telemetry.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/processorhelper/internal/metadata/generated_telemetry.go
receiver/receiverhelper/internal/metadata/generated_telemetry.go
receiver/scraperhelper/internal/metadata/generated_telemetry.go
service/internal/metadata/generated_telemetry.go

This can be used by components that need to set their scope name manually. Will save component owners from having to store a variable, which may diverge from the scope name used by the component for emitting its own telemetry. There are about a dozen components in contrib that could use this today.
Alternatively, I could just update the scope name strings in the components manually.

[mdatagen] export ScopeName in internal/metadata package

---

.chloggen/expose_host_tests.yaml
cmd/mdatagen/loader.go
cmd/mdatagen/loader_test.go
cmd/mdatagen/templates/component_test.go.tmpl

Expose a setting on tests::host to set up your own host initialization code
Some receivers require a host that has additional capabilities such as exposing exporters.
For those, we can expose a setting that allows them to place a different host in the generated code.

[mdatagen] expose host in generated test code by mdatagen

---

cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_status.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/main_test.go
cmd/mdatagen/templates/status.go.tmpl
cmd/mdatagen/templates/telemetry.go.tmpl
connector/forwardconnector/internal/metadata/generated_status.go
exporter/debugexporter/internal/metadata/generated_status.go
exporter/exporterhelper/internal/metadata/generated_telemetry.go
exporter/loggingexporter/internal/metadata/generated_status.go
exporter/nopexporter/internal/metadata/generated_status.go
exporter/otlpexporter/internal/metadata/generated_status.go
exporter/otlphttpexporter/internal/metadata/generated_status.go
extension/ballastextension/internal/metadata/generated_status.go
extension/memorylimiterextension/internal/metadata/generated_status.go
extension/zpagesextension/internal/metadata/generated_status.go
processor/batchprocessor/internal/metadata/generated_status.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/memorylimiterprocessor/internal/metadata/generated_status.go
processor/processorhelper/internal/metadata/generated_telemetry.go
receiver/nopreceiver/internal/metadata/generated_status.go
receiver/otlpreceiver/internal/metadata/generated_status.go
receiver/receiverhelper/internal/metadata/generated_telemetry.go
receiver/scraperhelper/internal/metadata/generated_telemetry.go
service/internal/metadata/generated_telemetry.go

This will make it available to most components, as the generated_telemetry is only generated for components that have internal telemetry configured. Arguably the scope name should be moved to its own file, but i'd rather not add yet another file if possible.

[mdatagen] move ScopeName to generated_status

---

.chloggen/fix-processor-metrics.yaml
processor/processorhelper/obsreport.go

This change reverts https://github.com/open-telemetry/opentelemetry-collector/pull/10693, which had an unintentional behavior change that made the processor helper report metrics only if they got values other than `0`.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10855

Fix processor metrics not being reported initially with 0 values

---

.chloggen/codeboten_disable-tracer-without-config.yaml
internal/globalgates/globalgates.go
service/go.mod
service/telemetry/config.go
service/telemetry/tracer.go
service/telemetry/tracer_test.go

Previously the service was returning an instance of a SDK tracer provider regardless of whether there were any processors configured causing resources to be consumed unnecessarily.
Fixes #10858

[service] Allow users to disable the tracer provider via the feature gate `service.noopTracerProvider`

---

.golangci.yml
exporter/exportertest/mock_consumer.go
receiver/receivertest/contract_checker.go

Migrated rand dependency to rand/v2. We only use rand in tests and mocks and the only two functions we use are float32 and float64 which still exist in the new v2 API so nothing very exciting going on here.
Fixes #10885
Ran `make test` successfully

chore (deps): migrate rand to rand/v2

---

.chloggen/mdatagen-usage.yaml
cmd/mdatagen/main.go

Updates mdatagen's output to show a complete example including the required metadata.yaml file.
- Closes #10886
Running `mdatagen -h` now shows `Usage: ./mdatagen metadata.yaml`
N/A

[mdatagen] Update usage output

---

.github/workflows/changelog.yml
.github/workflows/check-links.yaml
.gitignore
exporter/README.md
package.json

The repo uses markdown-link-check and not having a package.json file to pin the version causes dependabot security checks sadness. Following the same pattern as the specification repo for storing package.json in the root of the repo.

[chore] pin version for npm tooling

---

config/confighttp/confighttp_test.go

This is just splitting a change from #10912 to make it easier to review

[chore] adding test var for convenience

---

.chloggen/codeboten_leveled-meter-split-2.yaml
component/telemetry.go
processor/processorhelper/obsreport_test.go
service/internal/proctelemetry/process_telemetry_test.go
service/service.go

This func will MeterProvider and MetricsLevel in the near future. Split from https://github.com/open-telemetry/opentelemetry-collector/pull/10912

[component] add LeveledMeterProvider

---

.chloggen/builder-skip-go-mod.yaml
cmd/builder/Makefile
cmd/builder/README.md
cmd/builder/go.mod
cmd/builder/go.sum
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go
cmd/builder/internal/builder/main.go
cmd/builder/internal/builder/main_test.go
cmd/builder/internal/builder/modfiles_test.go
cmd/builder/internal/command.go
cmd/builder/internal/command_test.go

A continuation of https://github.com/open-telemetry/opentelemetry-collector/pull/9253 and https://github.com/open-telemetry/opentelemetry-collector/pull/9631
Description: Adds a `--skip-new-go-module` flag to the OTC builder. This enables users working in an existing go module environment (say, a "monorepo") to update the module they have, vs forcing the use of a new module.
With the new support inside an existing Go module, a collector main package can be generated using a go:generate directive. For example, in the directory where I want my collector built, the file generate.go has this line:
//go:generate builder --skip-new-go-module --skip-compilation --strict-versioning --config=./build-config.yaml
In the same directory, the build-config.yaml describes the collector to build. The …

[builder] Support for --skip-new-go-module

---

.chloggen/mdatagen-test-gen.yaml
cmd/mdatagen/templates/component_test.go.tmpl

When SkipLifecycle & SkipShutdown are set to true, the generated file will have an unused import `confmaptest`
The Metadata Generator had a bug described above, With this change, that issue has been addressed.
Fixes #10866

[cmd/mdatagen] Fixed bug in component_test.go.tmpl

---

exporter/exporterhelper/obsexporter.go
receiver/receiverhelper/obsreport.go
receiver/scraperhelper/obsreport.go

The MeterProvider used to generate the matric will make calls to recording the metric Noops. Removing the level check.

remove unnecessary level

---

exporter/exporterhelper/common.go
exporter/exporterhelper/obsexporter.go
exporter/exporterhelper/obsexporter_test.go
exporter/exporterhelper/obsreport_test.go
exporter/exporterhelper/queue_sender_test.go

This is leftover from the refactor to make that func private to the package. Removing it as all the callers can use newExporter directly.

[chore] newObsReport is no longer needed

---

confmap/confmaptest/configtest_test.go
confmap/confmaptest/testdata/empty-slice.yaml

Add a test on empty slices being sanitized to `nil` in `ToStringMap`

[confmaptest] Add a test on empty slice to nil

---

renovate.json

- Added a rule to ignore updates to the go toolchain. According to [this](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/gomod/update.ts#L51-L55), the toolchain update is a `depType` in the `gomod` manager. 
Fixes #10932
- Is there a way to test this aside from just waiting for the next renovate update?

fix(renovate): add package rule for disabling toolchain updates

---

.chloggen/codeboten_cleanup-unnecessary-func-2.yaml
receiver/scraperhelper/obsreport.go
receiver/scraperhelper/obsreport_test.go
receiver/scraperhelper/scrapercontroller.go

These functions and structs doesn't appear used in any of the components in either core or contrib. Deprecating to remove the surface area of the package.

[scraperhelper] deprecate NewObsReport, ObsReport, ObsReportSettings

---

.chloggen/codeboten_fix-10969.yaml
cmd/mdatagen/templates/component_telemetry_test.go.tmpl

[mdatagen] fix a missing import in a generated test file

---

extension/README.md

Removing references to the memory ballast extension

[chore] remove mentions of the `memory_ballast` extension

---

cmd/mdatagen/metadata-schema.yaml

The `async` option was recently added to telemetry metrics, and I believe this should be documented in the metadata schema. I've added a short description about what it means, and its purpose.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/10990

[chore][mdatagen] Update schema with information on async telemetry metrics

---

.chloggen/confmap-remove-unify-feature-gate.yaml
internal/globalgates/globalgates.go
otelcol/command.go
otelcol/go.mod

Removes stable `confmap.unifyEnvVarExpansion` feature gate.

[confmap] Remove stable confmap.unifyEnvVarExpansion feature gate

---

confmap/internal/e2e/testdata/issue-10787-main.yaml
confmap/internal/e2e/testdata/issue-10787-snippet.yaml
confmap/internal/e2e/types_test.go

These should have been updated to debug some time ago, but they're low priority as they're just tests

[chore] cleaning up references to logging exporter

---

README.md

This adds a badge to the oss-fuzz project that's running fuzzing tests against a build of the collector

[chore] add fuzzing badge

---

.chloggen/codeboten_level-internal-telemetry.yaml
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/loader.go
cmd/mdatagen/templates/telemetry.go.tmpl
component/componenttest/nop_telemetry.go
component/componenttest/obsreporttest.go
component/telemetry.go
config/configgrpc/configgrpc.go
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
config/confighttp/go.mod
exporter/exporterhelper/internal/metadata/generated_telemetry.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/batchprocessor/metadata.yaml
processor/batchprocessor/metrics.go
processor/processorhelper/internal/metadata/generated_telemetry.go
processor/processorhelper/obsreport.go
processor/processorhelper/obsreport_test.go
receiver/receiverhelper/internal/metadata/generated_telemetry.go
receiver/scraperhelper/internal/metadata/generated_telemetry.go
service/internal/metadata/generated_telemetry.go
service/internal/proctelemetry/process_telemetry_test.go

This is replaced by a LeveledMeterProvider method on the struct instead. This
reduces the complexity from the view of component authors, in that there's no need
to check the level before invoking the meter to record a metric.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9510

[service] deprecate TelemetrySettings.MeterProvider

---

component/component.go

Removes an incorrect comment from the `component.Factory interface`.
This comment was added via https://github.com/open-telemetry/opentelemetry-collector/pull/4338 when the extension/receiver/processor/exporter factory types all still [lived in](https://github.com/mx-psi/opentelemetry-collector/blob/b4be13e74923ebefb521f69a97288ce8d6f51ea9/component/exporter.go#L61) `component`. Since the factories have been moved to other modules, `component.Factory` needs to be implementable.
The specific extension/receiver/processor/exporter factory types are unimplementable since they are defined in internal packages. 
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/6506

[component] Remove incorrect comment on Factory interface

---

extension/zpagesextension/README.md
extension/zpagesextension/metadata.yaml

[extension/zpages] document unsupported none level

---

cmd/otelcorecol/go.mod
exporter/debugexporter/go.mod
exporter/go.mod
exporter/loggingexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
internal/e2e/go.mod

Follow up to #11020, needed for open-telemetry/opentelemetry-collector-contrib/pull/34956.
Updates all pseudoversions to point to cd1f762

[chore] Update references to experimental/storage

---

cmd/otelcorecol/go.mod
connector/forwardconnector/go.mod
connector/go.mod
internal/e2e/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
service/go.mod

Follows #10956, needed for open-telemetry/opentelemetry-collector-contrib#34956
Before #10956, the `connectorprofiles` main packages was named `connector`, so this was causing a conflict with the actual `connector` module. This is not a problem in core because of the `replace`s, but it is a problem in contrib.

[chore] Use updated connectorprofiles version

---

cmd/mdatagen/metadata-schema.yaml

The context can be found [here.](https://github.com/open-telemetry/opentelemetry-collector/issues/10801#issuecomment-2313541198) Only a subset of attribute types are supported for `telemetry` metrics vs. regular `metrics`. There's no instrumentation equivalent for attributes of the type `bytes`, `slice`, and `map`.

[chore][mdatagen] Add note about the supported types of telemetry metric attributes

---

exporter/loggingexporter/factory.go

Add warning to logging exporter on startup to remind users to switch to the debug exporter.
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/11037

[exporter/logging] Add warning to logging exporter

---

internal/obsreportconfig/obsmetrics/obs_exporter.go

This is apparently not used anywhere

[chore] removing unused internal variable

---

confmap/internal/e2e/types_test.go

This prevents the test from failing for users who set the variable locally

[chore] unset var used in test

---

.chloggen/codeboten_noop-providers.yaml
service/telemetry/tracer.go
service/telemetry/tracer_test.go

This is to address some of the memory concerns around the SDK's noop tracer provider. Instead of using the published noop tracer provider, we implement our own to avoid the cost of context propagation, which has been proven to be high enough to cause issues for end users.
Part of #10858

[service] implement a noop tracer provider

---

component/componenttest/obsreporttest.go

This is a documentation-only change, just cleaning up some wording of comments.

[chore][component/componenttest] Clarify wording in some comments

---

service/telemetry/attributes.go
service/telemetry/attributes_test.go
service/telemetry/tracer.go
service/telemetry/tracer_test.go

No functional change, just moving it into its own file to clean up the tracer config since the meter provider will also use attributes.

[chore] move attributes func into separate file

---

internal/e2e/status_test.go

Try adding wait group to ensure `StatusOk` is reported before the call to `Shutdown`.
Passed with `go test status_test.go --count 2000` 
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10927

[chore] Fix flaky Test_ComponentStatusReporting_SharedInstance test

---

.chloggen/fix-persistent-queue-deadlock.yaml
exporter/internal/queue/mock_storage.go
exporter/internal/queue/persistent_queue_test.go
exporter/internal/queue/sized_channel.go
exporter/internal/queue/sized_channel_test.go

This change fixes a potential deadlock bug for persistent queue.
There is a race condition in persistent queue that caused `used` in `sizedChannel` to become out of sync with `ch` len. This causes `Offer` to be deadlocked in specific race condition. For example:
1. Multiple consumers are calling Consume
2. Multiple producers are calling Offer to insert into the queue
a. All elements are taken from consumers. ch is empty
3. One consumer completes consume, calls onProcessingFinished
a. Inside sizedChannel, syncSize is invoked, used is reset to 0 when other consumers are still waiting for lock to consume
4. More Offer is called inserting elements -> used and ch len should equal
5. As step 3a consumers completes, used is decreased  -> used is lower than ch len
a. More Offer is called …

return queue is full error if sized_channel is full

---

.chloggen/refine-new-scraper.yaml
receiver/scraperhelper/scraper.go
receiver/scraperhelper/scrapercontroller_test.go

Create new function to  enable to pass `component.Type` to `scraperhelper.NewScraper`
Because many contrib scrapers name the scraper with the same name as the component itself, create a function to take `component.Type`.
For example, https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0e2bea5ac2763421e1a3943093f67184e109265f/receiver/activedirectorydsreceiver/factory_windows.go#L35 passes `metadata.Type.String()` as a name of scraper. With this change, you can pass `metadata.Type` instead 
Fixes #9473

Refine scraperhelper.NewScraper to take component.Type directly

---

.github/workflows/api-compatibility.yml
.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test-windows.yaml
.github/workflows/build-and-test.yml
.github/workflows/builder-integration-test.yaml
.github/workflows/changelog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/contrib-tests.yml
.github/workflows/perf.yml
.github/workflows/prepare-release.yml
.github/workflows/tidy-dependencies.yml
cmd/otelcorecol/go.mod
internal/tools/go.mod

[chore] bump go version

---

.chloggen/codeboten_beta-internal-telemetry-gate.yaml
internal/obsreportconfig/obsreportconfig.go
service/service.go

This configuration of the internal collector telemetry has been using the SDK configuration for some time. Moving this gate from alpha to beta.
Related to #6629

[service] move useOtelWithSDKConfigurationForInternalTelemetry gate to beta

---

.chloggen/confignet-mark-stable.yaml
versions.yaml

Reverts open-telemetry/opentelemetry-collector#11115
To be merged after the contrib release v0.109 is done.

Revert "Revert "[confignet] Mark as stable""

---

.golangci.yml
Makefile.Common
component/componentstatus/status_test.go
config/configtls/configtls_test.go
confmap/resolver_test.go
exporter/exporterhelper/batch_sender_test.go
exporter/exporterhelper/common_test.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces_batch_test.go
exporter/otlpexporter/factory_test.go
exporter/otlphttpexporter/factory_test.go
exporter/otlphttpexporter/otlp_test.go
pdata/pcommon/value_test.go
processor/processorhelper/logs_test.go
processor/processorhelper/metrics_test.go
processor/processorhelper/traces_test.go

Testifylint is a linter that provides best practices with the use of testify.
This PR enables [error-nil](https://github.com/Antonboom/testifylint?tab=readme-ov-file#error-nil) and  [nil-compare](https://github.com/Antonboom/testifylint?tab=readme-ov-file#nil-compare) rules from [testifylint](https://github.com/Antonboom/testifylint)

[chore]: enable error-nil and nil-compare rules from testifylint

---

.golangci.yml
Makefile.Common
exporter/exporterhelper/retry_sender_test.go
internal/fanoutconsumer/logs_test.go
internal/fanoutconsumer/metrics_test.go
internal/fanoutconsumer/profiles_test.go
internal/fanoutconsumer/traces_test.go
internal/iruntime/mem_info_test.go
internal/iruntime/total_memory_linux_test.go

Testifylint is a linter that provides best practices with the use of testify.
This PR enables [compares](https://github.com/Antonboom/testifylint?tab=readme-ov-file#compares) and  [negative-positive](https://github.com/Antonboom/testifylint?tab=readme-ov-file#negative-positive) rules from [testifylint](https://github.com/Antonboom/testifylint)

[chore]: enable compares and negative-positive rules from testifylint

---

.chloggen/6767-exporterhelper-rename-config.yaml
exporter/debugexporter/factory.go
exporter/exporterhelper/batch_sender_test.go
exporter/exporterhelper/common.go
exporter/exporterhelper/common_test.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/queue_sender.go
exporter/exporterhelper/queue_sender_test.go
exporter/exporterhelper/retry_sender_test.go
exporter/exporterhelper/timeout_sender.go
exporter/exporterhelper/timeout_sender_test.go
exporter/exporterhelper/traces_test.go
exporter/exporterqueue/config.go
exporter/internal/common/factory.go
exporter/otlpexporter/cfg-schema.yaml
exporter/otlpexporter/config.go
exporter/otlpexporter/config_test.go
exporter/otlpexporter/factory.go
exporter/otlpexporter/factory_test.go
exporter/otlphttpexporter/config.go
exporter/otlphttpexporter/config_test.go
exporter/otlphttpexporter/factory.go
exporter/otlphttpexporter/otlp_test.go
internal/e2e/consume_contract_test.go

This PR renames `TimeoutSettings` and `QueueSettings` (as well as the corresponding `NewDefault` functions) to `TimeoutConfig` and `QueueConfig`, for naming consistency reasons.
The previous struct/function names are kept as deprecated aliases of the new ones for now.
Updates #6767  (edit: reworded by @mx-psi)
No behavior changes were made, so no additional testing should be necessary.
The references to the aforementioned structs/functions in existing tests have been renamed as well. This means the deprecated function aliases are not tested, lowering the coverage a bit.
The new functions are documented identically to the previous ones.

[exporterhelper] Rename Timeout/QueueSettings to Config

---

.golangci.yml
Makefile.Common
cmd/builder/internal/builder/config_test.go
confmap/internal/mapstructure/encoder_test.go
consumer/consumererror/signalerrors_test.go

Testifylint is a linter that provides best practices with the use of testify.
This PR enables [error-is-as](https://github.com/Antonboom/testifylint?tab=readme-ov-file#error-is-as) rule from [testifylint](https://github.com/Antonboom/testifylint)

[chore]: enable error-is-as rule from testifylint

---

.chloggen/replace-new-scraper.yaml
receiver/scraperhelper/scraper.go
receiver/scraperhelper/scrapercontroller_test.go

As a step of https://github.com/open-telemetry/opentelemetry-collector/issues/9473, make the first argument of `scraperhelper.NewScraper` to take `component.Type`.
This PR deprecates `NewScraperWithComponentType` as the method is temporary and was created to change an argument of `NewScraper`

Make the first argument of NewScraper `component.Type`

---

.chloggen/mx-psi_fix-sub-config.yaml
confmap/confmap.go
confmap/confmap_test.go

Fixes `Sub` method to drop string representation if the requested sub-conf has it.
Fixes #11154
Added unit tests.

[confmap] Do not leak expanded values on Sub

---

.chloggen/mx-psi_disable-strict-versioning.yaml
cmd/builder/internal/command.go
cmd/builder/internal/command_test.go

Disable strict version check. The `--skip-strict-version-check` is kept but is now a no-op. 
This fixes #11152.
Fixes #11152

[cmd/builder] Disable strict version check

---

.chloggen/codeboten_consolidate-inout-items.yaml
processor/processorhelper/documentation.md
processor/processorhelper/internal/metadata/generated_telemetry.go
processor/processorhelper/logs.go
processor/processorhelper/logs_test.go
processor/processorhelper/metadata.yaml
processor/processorhelper/metrics.go
processor/processorhelper/metrics_test.go
processor/processorhelper/obsreport.go
processor/processorhelper/traces.go
processor/processorhelper/traces_test.go

This updating the existing metric points that were recently added to use signal as an attribute instead of separating the metric name. It follows the suggestions in [otep 259](https://github.com/open-telemetry/oteps/pull/259) for the metric and attribute names.
Putting this in draft to get some feedback from @djaglowski before moving forward with this change

[processorhelper] report signal as attribute on incoming/outgoing items

---

.chloggen/6767-embedded-field-rename.yaml

My PR #11132 introduced a small breaking change in the API of `otlpexporter`, which I failed to notice at the time. This PR adds a release note about this.
Specifically, the `TimeoutSettings` field in `otlpexporter.Config` was renamed to `TimeoutConfig` ([link to the new code](https://github.com/jade-guiton-dd/opentelemetry-collector/blob/543c4f510d3bbcd50e914f4e5d7f22c5fcbda92d/exporter/otlpexporter/config.go#L23)). As this is an embedded field, renaming the type of the field renamed the field itself.
(Another option would have been to de-embed the field, and keep the old name. This has less potential for breakage, but would also be a breaking change.)
Indirectly related to #6767

[otlpexporter] Document incidental breaking change on Config struct

---

.chloggen/fix-mdatagen-metrics-bool-attr.yaml
cmd/mdatagen/internal/samplereceiver/documentation.md
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics_test.go
cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/loader_test.go
cmd/mdatagen/templates/metrics_test.go.tmpl

Since commit 8f3ca8a, `mdatagen` improperly generates metric tests: boolean attributes are always expected to be `true` in the output, no matter what the injected test value was. For example, [this line in collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/19b01db307d984e62f81f1880b63327ba092cd81/receiver/apachesparkreceiver/internal/metadata/generated_metrics_test.go#L1250) is incorrectly changed to expect `true` instead of `false` after updating mdatagen and running it again.
The reason is [this line](https://github.com/open-telemetry/opentelemetry-collector/blob/8f3ca8aaf58539e5afab54d365f97624efe7cbc3/cmd/mdatagen/templates/metrics_test.go.tmpl#L182), which attempts to generate `assert.True` or `assert.False` based on the expected test value. …

[mdatagen] Fix metric tests on boolean attributes

---

cmd/otelcorecol/go.mod
config/configgrpc/go.mod
config/confighttp/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
extension/zpagesextension/go.mod
internal/e2e/go.mod
receiver/otlpreceiver/go.mod
service/go.mod

This is done to allow contrib dependencies to work. Otherwise, otelcoltest ends up picking up an old dependency that looks for localhostgate which has been removed.
Here's an example error:
```
go: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureeventhubreceiver tested by
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureeventhubreceiver.test imports
go.opentelemetry.io/collector/otelcol/otelcoltest imports
go.opentelemetry.io/collector/otelcol imports
go.opentelemetry.io/collector/service tested by
go.opentelemetry.io/collector/service.test imports
go.opentelemetry.io/collector/config/confighttp imports
go.opentelemetry.io/collector/config/internal imports
go.opentelemetry.io/collector/internal/localhostgate: package …
```

[chore] update internal dep

---

.chloggen/add-map-moveto.yaml
pdata/pcommon/map.go
pdata/pcommon/map_test.go

Can be used to remove unnecessary copies from places like https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c52a9a7ae1563127254530d416a8c569c54750bd/pkg/ottl/ottlfuncs/func_replace_all_patterns.go#L100

[pdata]: Add support to MoveTo for Map, allow avoiding copies

---

.golangci.yml
Makefile.Common
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics_test.go
cmd/mdatagen/internal/templates/metrics_test.go.tmpl
pdata/internal/cmd/pdatagen/internal/base_fields.go
pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
pdata/internal/json/number_test.go
pdata/pcommon/generated_float64slice_test.go
pdata/pcommon/map_test.go
pdata/pcommon/value_test.go
pdata/pmetric/generated_exemplar_test.go
pdata/pmetric/generated_exponentialhistogramdatapoint_test.go
pdata/pmetric/generated_histogramdatapoint_test.go
pdata/pmetric/generated_numberdatapoint_test.go
pdata/pmetric/generated_summarydatapoint_test.go
pdata/pmetric/generated_summarydatapointvalueatquantile_test.go
pdata/pmetric/metrics_test.go
service/telemetry/metrics_test.go

Testifylint is a linter that provides best practices with the use of testify.
This PR enables [float-compare](https://github.com/Antonboom/testifylint?tab=readme-ov-file#float-compare)  rule from [testifylint](https://github.com/Antonboom/testifylint)

[chore]: enable float-compare rule from testifylint

---

.chloggen/codeboten_deprecate-metrics.yaml
processor/memorylimiterprocessor/memorylimiter.go
processor/processorhelper/documentation.md
processor/processorhelper/internal/metadata/generated_telemetry.go
processor/processorhelper/metadata.yaml
processor/processorhelper/obsreport.go

These were only used by the memory limiter processor and were never automatically calculated by the processorhelper. It's better to move them to processor specific metrics that can be managed within the component itself.

[processorhelper] deprecated accepted/refused/dropped metrics

---

pdata/plog/fuzz_test.go
pdata/plog/plogotlp/fuzz_test.go
pdata/pprofile/fuzz_test.go
pdata/pprofile/pprofileotlp/fuzz_test.go
pdata/ptrace/fuzz_test.go
pdata/ptrace/ptraceotlp/fuzz_test.go

Fixes #
Adds both a marshal call and another unmarshal -> marshal round to the fuzzers to test for more potential bugs.

Add marshal calls to fuzzers

---

config/confighttp/compression_test.go
config/confighttp/confighttp_example_test.go
config/confighttp/confighttp_test.go

Minor life improvements when reviewing the tests,
- Using stdlib for error reading
- Using the config client from test server
- Moving examples into their own file for easy discovery/maintainability 
N/A

[chore] cleanup confighttp tests

---

exporter/otlphttpexporter/factory.go
exporter/otlphttpexporter/factory_test.go

Split off from #11131. Prepares OTLP HTTP exporter for supporting profiles (which uses `/v1development`)

[chore][exporter/otlphttpexporter] Generalize `composeSignalURL`

---

Makefile.Common
internal/tools/go.mod
internal/tools/tools.go

All Testifylint rules are now fixed and ensured to be applied with golangci-lint. 
This removes the helper configuration in Makefile and tools module.

[chore]: remove testifylint from Makefile

---

service/internal/proctelemetry/process_telemetry_linux_test.go

Fixes failing unit test TestProcessTelemetryWithHostProc under service/internal/proctelemetry/process_telemetry_linux_test.go due to incorrect metric name 
Fixes [#11221](https://github.com/open-telemetry/opentelemetry-collector/issues/11221)
unit tests
none

[chore] fix TestProcessTelemetryWithHostProc test

---

.chloggen/rename-getexporters.yaml
service/go.mod
service/internal/graph/host.go
service/service_test.go

As part of https://github.com/open-telemetry/opentelemetry-collector/pull/11204 I left `host`'s implementation of `GetExporters` alone, thinking I didn't need to change a deprecated interface implementation.
But `GetExporters` depends on `component.DataType`, so we won't be able to remove `component.DataType` unless `GetExporters` is updated to use `pipeline.Signal` instead.
This PR deprecates the deprecated `GetExporters` interface with `GetExportersWithSignal`, which uses `pipeline.Signal`. Then we'll follow the process to rename `GetExportersWithSignal` back to `GetExporters`.

[service] Start refactor of GetExporters

---

cmd/builder/README.md

- [Trailing spaces](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md009.md)
- [Dollar signs used before commands without showing output](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md014.md)
- [Fenced code blocks should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md031.md)

[chore] style: Fix markdown linter violations

---

.chloggen/exporterhelper-remove-deprecated.yaml
exporter/exporterhelper/common.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/queue_sender.go
exporter/exporterhelper/timeout_sender.go

Follow-up to #11132 now that 0.110 has been released.
Should be the final step for #6767.

[exporterhelper] Remove deprecated aliases for Queue/TimeoutSettings

---

.chloggen/json-decoded-flag.yaml
pdata/ptrace/json.go
pdata/ptrace/json_test.go

For both the `Span` and `SpanLink`, the current unmarshalJsoniter methods do not unmarshal the `flags` field. This updates the functionality to correctly decode these values into the destination.
Fix #11267
Signed-off-by: Tyler Yahn <codingalias@gmail.com>

Unmarshal span and link flags from JSON

---

exporter/exporterhelper/internal/base_exporter.go

This PR follows https://github.com/open-telemetry/opentelemetry-collector/pull/11041.
The previous PR changed the initialization of `batchSender` and `queueSender` to AFTER configuration, because that enables us to access `queueConfig` and `batcherConfig` in the same place.
I noticed since then that there is another API for queue configuration, and this PR takes care of that other API
Ran `opentelemetry-collector$ make` to make sure all tests still pass.

[exporter] [chore] Initialize batchSender and queueSender after configuration - #2

---

pdata/ptrace/json.go

Bug added in https://github.com/open-telemetry/opentelemetry-collector/pull/11275

[chore] Fix unreleased bug that JSON integers should support string or int

---

exporter/otlphttpexporter/factory.go

This PR makes usage of `NewDefaultClientConfig` instead of manually creating the `confighttp.ClientConfig` struct. The updates to defaults are maintained (Timeout, Compression, WriteBufferSize) whereas the fields that match the default are not manually set anymore (Endpoint, Headers).
It also sets to nil the fields that are set in default but weren't set previously (MaxIdleConns, MaxIdleConnsPerHost, MaxConnsPerHost, IdleConnTimeout) to retain the same behaviour. I am on the fence about this one, should we switch to using the defaults ?
#11274

[exporter/otlphttpexporter] Use NewDefaultClientConfig instead of manually creating struct

---

.chloggen/configgrpc-option-refactor.yaml
config/configgrpc/configgrpc.go
exporter/otlpexporter/otlp.go
receiver/otlpreceiver/otlp.go

`ClientConfig.ToClientConn` and `ServerConfig.ToServer` were deprecated in v0.110.0 in favor of `ClientConfig.ToClientConnWithOptions` and `ServerConfig.ToServerWithOptions` which use a more flexible option type (#11069). The original functions are now removed, and the new ones are renamed to the old names. The `WithOptions` names are kept as deprecated aliases for now.
Note: The "4 lines missing coverage" are from the `WithOptions` function aliases.
Updates #9480
- `collector-contrib` will need to be updated to rename uses of the `WithOptions` functions
- The newly deprecated aliases will then need to be removed in the next release

[configgrpc] Replace deprecated ToClientConn and ToServer with new API

---

.chloggen/remove-scraper-with-component-type.yaml
receiver/scraperhelper/scraper.go

Remove deprecated `scraperhelper.NewScraperWithComponentType`
This is the last change for #9473
Fixes #9473

Remove deprecated `scraperhelper.NewScraperWithComponentType`

---

.chloggen/service-continue-getexporters-rename.yaml
internal/e2e/status_test.go
otelcol/config.go
otelcol/config_test.go
otelcol/otelcoltest/config_test.go
otelcol/unmarshaler_test.go
service/config.go
service/config_test.go
service/go.mod
service/internal/graph/graph.go
service/internal/graph/graph_test.go
service/internal/graph/host.go
service/pipelines/config.go
service/service.go
service/service_test.go

Continues deprecation/rename processor for `Config.PipelinesWithPipelineID`, `pipelines.ConfigWithPipelineID` and `GetExportersWithSignal`.

[service] Remove deprecations and continue renames around DataType

---

.chloggen/exportertest-continue-deprecations-2.yaml
.chloggen/exportertest-continue-deprecations.yaml
exporter/exporterqueue/queue.go
exporter/exportertest/contract_checker.go
exporter/go.mod

Continues DataType deprecation/rename in exporter for `Settings.DataType` and `CheckConsumeContractParams.DataType`.

[exporter] Continue DataType rename in exporter

---

.chloggen/receivertest-continue-deprecation-2.yaml
.chloggen/receivertest-continue-deprecation.yaml
cmd/mdatagen/go.mod
exporter/debugexporter/go.mod
exporter/exporterprofiles/go.mod
exporter/go.mod
exporter/loggingexporter/go.mod
exporter/nopexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
otelcol/factories_test.go
receiver/go.mod
receiver/nopreceiver/go.mod
receiver/otlpreceiver/go.mod
receiver/receiverprofiles/go.mod
receiver/receivertest/contract_checker.go
receiver/receivertest/nop_receiver.go

Continues deprecation/rename processor for `NewNopFactoryForTypeWithSignal` and `CheckConsumeContractParams.DataType`.

[receivertest] Continue DataType deprecations in receivertest

---

processor/batchprocessor/batch_processor.go
processor/batchprocessor/batch_processor_test.go

Split the internal `batcher.export()` interface into three methods. This is a refactoring that was applied in https://github.com/open-telemetry/otel-arrow/tree/main/collector/processor/concurrentbatchprocessor and is being back-ported as part of #11308. The reason this refactoring is needed is that the parent context of the export() request will be manipulated in common code (vs signal-specific code) for tracing support.
Part of #11308
Existing tests cover this.

Refactor batch processor export method

---

processor/batchprocessor/batch_processor.go

There are two implementations of the `batcher` interface with several inconsistencies. Notably, the single-shard case would start a goroutine before `Start()` is called, which can be confusing when the goroutine leak checker notices it. This makes the single-shard batcher wait until Start() to create its single shard. A confusing field name `batcher` in this case becomes `single`, and a new field is added for use in start named `processor` to create the new shard.
For the multi-shard batcher, `start()` does nothing, but this structure confusingly embeds the batchProcessor. Rename the field `processor` for consistency with the single-shard case.
Part of #11308.

(batchprocessor): Multi/single-shard consistent start method and field names

---

.chloggen/deprecate-buildprocessormetricname.yaml
processor/processorhelper/obsreport.go

This helper is no longer needed since introduction of `mdatagen`.
Relates https://github.com/open-telemetry/opentelemetry-collector/issues/11302

[chore]: deprecate and remove BuildProcessorMetricName

---

receiver/otlpreceiver/fuzz_test.go

The fuzzer report a null-pointer dereference which is not true.  This fixes that.
Fixes https://issues.oss-fuzz.com/issues/42538213

Fix false fuzzer crash

---

service/internal/graph/connector.go

The primary goal here was to delegate from each switch case, rather than nest logic as deep as necessary.

[chore][graph] Decompose buildConnector

---

.chloggen/fix-ub-proc-helper.yaml
processor/processorhelper/logs.go
processor/processorhelper/logs_test.go
processor/processorhelper/metrics.go
processor/processorhelper/metrics_test.go
processor/processorhelper/traces.go
processor/processorhelper/traces_test.go

The main issue is that after https://github.com/open-telemetry/opentelemetry-collector/pull/10910 the err variable is shared between requests because it uses the same address as the err defined outside the func.
This is an UB because we are overwriting memory and will cause crashes like https://github.com/open-telemetry/opentelemetry-collector/pull/11335, where the check for not nil happens then gets overwrite with nil and crashes.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/11350

Fix data race condition, concurrent writes to the err variable, causes Undefined Behavior

---

.chloggen/mx-psi_update-default-builder-config.yaml
cmd/builder/internal/config/default.yaml

Update default configuration to use v1.17.0 for confmap providers.
This is what is making open-telemetry/opentelemetry-collector-contrib#35605 fail

[cmd/builder] Update default configuration to use v1.17.0

---

.chloggen/configgrpc-remove-deprecated.yaml
config/configgrpc/configgrpc.go

This PR removes `ClientConfig.ToClientConnWithOptions`/`ServerConfig.ToServerWithOptions`, deprecated aliases of `ClientConfig.ToClientConn`/`ServerConfig.ToServer`, which were introduced in v0.111.0. This was part of the three step process to change the option type used by these methods (introduce new methods using the new option type and deprecate the old ones / remove old methods, rename new methods to the old names, add deprecated aliases for the new names / remove aliases).
Fixes #9480

[configgrpc] Remove deprecated aliases

---

.chloggen/componentstatus-remove-deprecated-funcs.yaml
component/componentstatus/instance.go

[componentstatus] Remove deprecated functions

---

.chloggen/service-remove-deprecated-funcs.yaml
otelcol/config.go
service/config.go
service/pipelines/config.go
service/service.go

[service] remove deprecated types

---

.chloggen/processorhelper-in-out-fix.yaml
processor/processorhelper/logs.go
processor/processorhelper/logs_test.go
processor/processorhelper/metrics.go
processor/processorhelper/metrics_test.go
processor/processorhelper/traces.go
processor/processorhelper/traces_test.go

[processorhelper] Fix bug where record in/out metrics were skipped

---

.chloggen/retry_sender_fail_fast.yaml
exporter/exporterhelper/internal/retry_sender.go
exporter/exporterhelper/internal/retry_sender_test.go

The retry sender will delay until the context is canceled, where instead it could fail fast with a transient error and a clear message that no more retries are possible given the configuration.
Part of #11183 
One new test.

(exporterhelper) Retry sender: fail request if context timeout < next retry

---

cmd/builder/README.md
docs/release.md

Reverts open-telemetry/opentelemetry-collector#11234
The PR to publish container images for builder https://github.com/open-telemetry/opentelemetry-collector-releases/pull/671 has not been merged yet (neither has the one adding "Update version" workflow https://github.com/open-telemetry/opentelemetry-collector-releases/pull/684). We should only publish these docs after the images are published.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/11347

[chore] docs: Revert "update cmd/builder documentation for docker image"

---

.chloggen/msg_feature-include-lz4-compression.yaml
cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
config/configcompression/compressiontype.go
config/configcompression/compressiontype_test.go
config/confighttp/README.md
config/confighttp/compression.go
config/confighttp/compression_test.go
config/confighttp/compressor.go
config/confighttp/confighttp.go
config/confighttp/go.mod
config/confighttp/go.sum
exporter/otlphttpexporter/go.mod
exporter/otlphttpexporter/go.sum
extension/zpagesextension/go.mod
extension/zpagesextension/go.sum
internal/e2e/go.mod
internal/e2e/go.sum
otelcol/go.sum
otelcol/otelcoltest/go.sum
receiver/otlpreceiver/go.mod
receiver/otlpreceiver/go.sum
service/go.mod
service/go.sum

Adding in support for lz4 compression into the project, I have seen it perform amazing well in other projects that send a lot of traffic and were originally using `gzip` or `flate`. 
It would be really great to have for environments that are cpu, memory sensitive.
Fixes 9128
I've updated the existing test frameworks to include lz4 in their suite
I've updated the readmes to include lz4 but I suspect there might be more places to update.

confighttp: Including lz4 as supported compression encoding

---

config/confighttp/README.md

Documentation fix: The example for using attributesprocessor to add the value of an incoming HTTP header missed the `metadata.` prefix and the lowercasing of the header name.
Fix the example in config/confighttp/README.md.

docs: Fix metadata/headers example on confighttp README [chore]

---

service/internal/graph/connector.go
service/internal/graph/consumer.go
service/internal/graph/graph_test.go
service/internal/graph/util_test.go

Follows #11330
Currently, `connectorNode` contains separate `component.Component` and `baseConsumer` fields. These fields are essentially two representations of the same component, but `baseConsumer` may be wrapped in another consumer that inherits capabilities. Rather than maintain two separate handles, this PR switches to a unified field. I believe this change helps normalize the connector node with other types of consumer nodes and will enable further refactoring opportunities.

[chore][graph] Remove connectorNode's separate baseConsumer

---

exporter/internal/queue/bounded_memory_queue.go
exporter/internal/queue/bounded_memory_queue_test.go
exporter/internal/queue/consumers.go
exporter/internal/queue/persistent_queue.go
exporter/internal/queue/persistent_queue_test.go
exporter/internal/queue/queue.go
exporter/internal/queue/queue_test.go

This PR adds a public function `GetNextItem` to queue (both persistent queue and bounded memory queue)
Why this change?
Instead of blocking until consumption of the item is done, we would like to separate the API for reading and committing consumption.
Before:
`Consume(consumeFunc)`
After:
`idx, item = Read()`
`OnProcessingFinished(idx)`

[exporter] exporter queue Read()

---

.golangci.yml
component/config.go
config/confighttp/compress_readcloser_test.go
config/confighttp/compression_test.go
confmap/confmap_test.go
exporter/debugexporter/internal/otlptext/databuffer.go
exporter/exporterhelper/internal/batch_sender_test.go
exporter/exporterhelper/internal/request.go
exporter/internal/queue/persistent_queue.go
exporter/internal/queue/persistent_queue_test.go
exporter/otlpexporter/otlp_test.go
otelcol/collector.go
pdata/pcommon/timestamp.go
pdata/pcommon/timestamp_test.go
pdata/pcommon/value.go
processor/batchprocessor/batch_processor_test.go
processor/memorylimiterprocessor/memorylimiter_test.go
receiver/otlpreceiver/otlp_test.go
receiver/scraperhelper/config_test.go
service/internal/graph/node.go
service/internal/proctelemetry/process_telemetry.go
service/internal/status/status_test.go

Fix lots of tests, for non-tests add nolint annotations when fix not trivial.

Fix lint errors

---

README.md

Follows open-telemetry/community/pull/2391
See also open-telemetry/opentelemetry-collector-contrib/pull/35807

[chore][README.md] Remove company affiliation for emeritus

---

.chloggen/connectortest-own-module.yaml
Makefile
cmd/builder/internal/builder/main_test.go
cmd/builder/test/core.builder.yaml
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
connector/connectortest/Makefile
connector/connectortest/go.mod
connector/connectortest/go.sum
connector/go.mod
internal/e2e/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
service/go.mod
versions.yaml

This PR is putting the connectortest pkg in its own module as requested in https://github.com/open-telemetry/opentelemetry-collector/issues/11216

Put connectortest in its own module

---

service/service.go
service/telemetry/attributes.go

Came across these in the work to support v0.3.0 of the configuration schema, split them into a separate PR to reduce complexity of the review.

chore: minor code cleanup

---

.chloggen/profiles-featuregate.yaml
service/pipelines/config.go
service/pipelines/config_test.go

This hides profiles support behind a feature gate, so folks have to enable them explicitly to be able to use them.

Hide profiles behind a feature gate

---

docs/monitoring.md
docs/troubleshooting.md

Removes pages that were moved to opentelemetry.io. These pages now live at:
- https://opentelemetry.io/docs/collector/internal-telemetry/#use-internal-telemetry-to-monitor-the-collector
- https://opentelemetry.io/docs/collector/troubleshooting/
Neither of the md docs in opentelemetry-collector are among the top 10 most visited pages according to Github traffic stats (we don't have visibility into individual pages, only the top 10)

[chore] Remove deprecated documentation

---

.chloggen/configcompression-include-lz4-compression.yaml

`make check-changes PREVIOUS_VERSION=v1.17.0 MODSET=stable` returned that a v1.18.0 release is necessary due to changes in configcompression. This adds a missing changelog entry for the module since the other changelog entry only mentions confighttp.

[chore] Add missing API changelog for configcompression

---

.github/ISSUE_TEMPLATE/stabilization.md

[chore][.github/ISSUE_TEMPLATE] Update link to coding guidelines

---

README.md

Promotes @dmathieu to triager. His contributions have helped add support for the profiling signal and have placed him [among the top 5 (non-bot) committers in the last 6 months](https://github.com/open-telemetry/opentelemetry-collector/graphs/contributors?from=4%2F20%2F2024).
You can see a list of his contributions [here](https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+author%3Admathieu+).

[chore] Promote Damien Mathieu to triager role

---

.chloggen/stabilityunmarshal.yaml
cmd/mdatagen/internal/metadata_test.go
cmd/mdatagen/internal/status.go
component/component.go
component/component_test.go

This PR also starts using the fact that StabilityLevel implements UnmarshalText and cleans up the mdatagen stability structure.

Add UnmarshalText for StabilityLevel

---

service/telemetry/metrics_test.go

This test wasn't testing any new behaviour since similar config was used in both test cases. Removed the duplicate and updated `getMetricsFromPrometheus` to not require a handler anymore. This will be useful when updating the code with the new upstream config package.

[chore] clean up duplicated test

---

exporter/exporterhelper/internal/queue_sender.go
exporter/internal/queue/bounded_memory_queue_test.go
exporter/internal/queue/consumers.go
exporter/internal/queue/persistent_queue_test.go

This PR moves queue start and shutdown outside of queue consumer.
Consumer should be in charge of "consuming" the queue but not managing the life cycle.

[exporterqueue][chore] Moving queue start and shutdown out side of queue consumer

---

docs/release.md

* Minor formatting updates
* Remove notice about being an approver in all three repos, as the **release manager** section below says it is not necessary.
* Provide convenience commands for creating the release branch with Git.
* Put commands on separate lines to make them more obvious and easier to copy.
* Add a note about GPG errors if signing was not set up.
* Add a note about handling workflow fixes in opentelemetry-collector-releases

[chore] Update release procedure

---

exporter/internal/queue/batcher.go
exporter/internal/queue/batcher_test.go
exporter/internal/queue/disabled_batcher.go
exporter/internal/queue/disabled_batcher_test.go
exporter/internal/queue/fake_request.go

This PR is a bare minimum implementation of a component called queue batcher. On completion, this component will replace `consumers` in `queue_sender`, and thus moving queue-batch from a pulling model instead of pushing model.
Limitations of the current code
* This implements only the case where batching is disabled, which means no merge of splitting of requests + no timeout flushing.
* This implementation does not enforce an upper bound on concurrency
All these code paths are marked as panic currently, and they will be replaced with actual implementation in coming PRs. This PR is split from https://github.com/open-telemetry/opentelemetry-collector/pull/11507 for easier review.
Design doc:
https://docs.google.com/document/d/1y5jt7bQ6HWt04MntF8CjUwMBBeNiJs2gV4uUZfJjAsE/edit?usp=sharing …

[exporterqueue] Bare minimum frame of queue batcher + unit test.

---

.golangci.yml
config/confighttp/confighttp_test.go
exporter/otlphttpexporter/otlp_test.go
receiver/otlpreceiver/fuzz_test.go

[usestdlibvars](https://golangci-lint.run/usage/linters/#usestdlibvars) is a linter that detect the possibility to use variables/constants from the Go standard library.

[chore]: enable usestdlibvars linter

---

docs/coding-guidelines.md

Reflects existing practice in coding guidelines.
Relates to #6767, fixes #9428

[chore][docs] Reflect current practices about configuration structs in coding guidelines

---

README.md
docs/component-stability.md

The goal is to work towards #11553 in this new document. This only copies the contents of README.md verbatim.
Fixes #11560

[chore][docs] Move component stability to a separate document

---

exporter/internal/queue/batcher.go
exporter/internal/queue/default_batcher.go
exporter/internal/queue/default_batcher_test.go
exporter/internal/queue/disabled_batcher_test.go
exporter/internal/queue/fake_request.go

This PR follows https://github.com/open-telemetry/opentelemetry-collector/pull/11540 and implements support for item-count based batching for queue batcher.
Limitation: This PR supports merging request but not splitting request. In other words, it support specifying a minimum request size but not a maximum request size.
Design doc:
https://docs.google.com/document/d/1y5jt7bQ6HWt04MntF8CjUwMBBeNiJs2gV4uUZfJjAsE/edit?usp=sharing

[exporterqueue] Default Batcher that reads from the queue, batches and exports 

---

docs/scraping-receivers.md

Trying to reference docs on internal metrics and found the current link sends you to `404 - page not found` since the page seems to have moved from `opentelemetry-collector-contrib` to `opentelemetry-collector` repo
Fixes #

[docs] Fix link in scraping-receivers.md

---

cmd/builder/internal/command.go
cmd/builder/internal/command_test.go

This is a no-op, because the file config cannot set the "skip" properties since they have `mapstructure:"-"`

[chore] Remove unnecessary overwrites for flag only values

---

.chloggen/batch-processor-init-single-shard.yaml
processor/batchprocessor/batch_processor.go

The single-shard batcher is currently created and started in the start function. If the consume function is called before the start function, sb.single will be nil and it will panic. I'm not sure if that can happen in the Otel collector but it might happen in distributions that have a different runtime (such as Alloy - Grafana's distribution).
I think that conceptually, it's better to create the shard in the constructor and start it in the start function. 
PS: I did not create an entry in the changelog because the initial [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/11314) for this change didn't but let me know if I should add one.
Credits also to @thampiotr for this fix

(batchprocessor): Move single shard batcher creation to the constructor

---

cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/main.go
cmd/builder/internal/builder/main_test.go
cmd/builder/internal/command.go
cmd/builder/internal/command_test.go

Skip changelog since this is not visible to our users.

Apply default values before we unmarshal the config, allows not using pointers

---

package.json

To prevent it from using v3.13.x which is currently broken by https://github.com/tcort/markdown-link-check/issues/368.

[chore] fix: pin markdown-link-check to v3.12.2

---

.golangci.yml
cmd/mdatagen/internal/metadata.go
component/componenttest/otelchecker.go
component/identifiable.go
config/confighttp/compression_test.go
config/confighttp/compressor_test.go
config/confighttp/confighttp_test.go
config/configopaque/opaque_test.go
config/configtls/clientcasfilereloader.go
config/configtls/clientcasfilereloader_test.go
config/configtls/configtls.go
confmap/confmap.go
connector/internal/router.go
connector/logs_router.go
exporter/debugexporter/internal/normal/metrics.go
exporter/exporterhelper/internal/base_exporter.go
exporter/internal/queue/persistent_queue_test.go
exporter/otlphttpexporter/otlp_test.go
featuregate/registry.go
internal/e2e/otlphttp_test.go
internal/testutil/testutil.go
otelcol/buffered_core.go
pdata/pcommon/value.go
pipeline/internal/globalsignal/signal.go
processor/batchprocessor/batch_processor_test.go
receiver/otlpreceiver/internal/errors/errors_test.go
service/service_test.go
service/telemetry/config.go
service/telemetry/internal/otelinit/config.go

[perfsprint](https://golangci-lint.run/usage/linters/#perfsprint) checks that fmt.Sprintf can be replaced with a faster alternative.

[chore]: enable perfsprint linter

---

exporter/internal/queue/batcher.go
exporter/internal/queue/default_batcher.go
exporter/internal/queue/default_batcher_test.go
exporter/internal/queue/fake_request.go

This PR follows https://github.com/open-telemetry/opentelemetry-collector/pull/11546 and add support for splitting (i.e. support setting a maximum request size)
Design doc:
https://docs.google.com/document/d/1y5jt7bQ6HWt04MntF8CjUwMBBeNiJs2gV4uUZfJjAsE/edit?usp=sharing

[chore] [exporterqueue] Add splitting to the experimental pull-based batcher

---

exporter/internal/queue/batcher.go
exporter/internal/queue/default_batcher_test.go
exporter/internal/queue/disabled_batcher_test.go

This PR changes queue batcher to use `exportFunc` instead of `request.export()`. This makes testing easier and avoid passing unnecessary detail to the exporter batcher.

[exporter][chore] Change queue batcher to use exportFunc instead of request.export()

---

.chloggen/initial_delay_shutdown.yaml
receiver/scraperhelper/scrapercontroller.go
receiver/scraperhelper/scrapercontroller_test.go

exit before scraping if the receiver was shutdown, do not wait the initial delay.

[receiver/scraperhelper] exit before scraping if the receiver was shutdown

---

.chloggen/rm-scraper-id.yaml
receiver/scraperhelper/scraper.go
receiver/scraperhelper/scrapercontroller.go
receiver/scraperhelper/scrapercontroller_test.go

Changes interface to get closer to https://github.com/open-telemetry/opentelemetry-collector/pull/11657

Deprecate Scraper.ID func, pass type when register Scraper

---

cmd/mdatagen/internal/sampleprocessor/internal/metadata/generated_config_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_config_test.go
cmd/mdatagen/internal/templates/config_test.go.tmpl

Uses require.Emptyf on config diff instead of testing.Error with diff not empty

[mdatagen]: require.Emptyf on config diff

---

.chloggen/codeboten_3months.yaml
component/component.go
component/component_test.go
docs/component-stability.md

After reviewing the 6 month period, the period seems too long to get feedback on whether an unmaintained component should be removed. I'm proposing shortening it to 3 months.

update time period before removing an unmaintained component

---

service/telemetry/metrics_test.go

attempts to fix flaky `service/telemetry/metrics` test
Fixes #11654 
update to test helper function
n/a

[chore] add retry logic to flaky http test

---

.chloggen/add-local-module-replace-ocb-converter-provider.yaml
cmd/builder/internal/builder/templates/go.mod.tmpl
service/telemetry/metrics_test.go

Adds ability to replace Providers and Converters with local paths when building custom collector in ocb
Closes #11649
local build of ocb with locally downloaded converter and provider (can add this type of test to github actions if others think it is necessary)
.chloggen file

Add local module replacement to ocb template

---

.github/workflows/api-compatibility.yml
.github/workflows/build-and-test-windows.yaml
.github/workflows/build-and-test.yml
.github/workflows/builder-integration-test.yaml
.github/workflows/changelog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/contrib-tests.yml
.github/workflows/perf.yml
.github/workflows/prepare-release.yml
.github/workflows/tidy-dependencies.yml
cmd/otelcorecol/go.mod

The "build-and-test / checks" CI job specifies `go-version: ~1.22.8`. Today, this started resolving to `1.22.9`, causing [errors in CI](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/11839445874/job/32990922879?pr=11670) because of the `toolchain 1.22.8` directive in `otelcorecol/go.mod`. This PR just updates the directive to fix the error. A more long-term solution may be preferred, such as using exact versions instead of `~` versions in CI.

[chore] Run `make genotelcorecol` to fix "build-and-test / checks"

---

component/componenttest/configtest_test.go
pdata/internal/json/attribute_test.go
pdata/plog/json_test.go
pdata/pmetric/json_test.go
pdata/pprofile/json_test.go
pdata/ptrace/json_test.go

use ErrorContains with testify when possible

[chore]: use ErrorContains with testify

---

cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go
cmd/builder/internal/builder/main_test.go
cmd/builder/internal/builder/templates/go.mod.tmpl
cmd/builder/internal/builder/templates/main.go.tmpl

change name in templates and cmd/builder to refer to Providers and Converters as ConfmapProviders and ConfmapConverters
as requested here: https://github.com/open-telemetry/opentelemetry-collector/pull/11653#discussion_r1841202325
existing tests should cover this
none, internal change and no new code/api

[chore] rename confmap modules to ConfmapConverters and ConfmapProviders

---

cmd/otelcorecol/go.mod
exporter/go.mod
extension/memorylimiterextension/go.mod
extension/zpagesextension/go.mod
internal/e2e/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
service/go.mod

Now that the PR to split `extensiontest` into its own module (#11629) has landed, we can import the new module in an externally-resolvable way using the pseudo-version corresponding to the merge commit, similar to what I did for `componenttest` (#11668). After the next release (0.114.0), we will be able to use that version number instead for internal imports.

[chore] Use pseudo-versions to require `extensiontest`

---

Makefile

`make check-contrib` use `go mod edit` to allow running the `opentelemetry-collector-contrib` unit tests against the local version of the core libraries. It also removes the `replace` statements after tests have been run. At the moment, this is done with two long handwritten `go mod edit` commands. But this very easily gets out-of-date: for reference, we currently only `-replace` 70 modules out of the 73 in versions.yaml, and only `-dropreplace` 63 out of _those_.
This PR changes the `Makefile` to programatically generate the commands, to avoid needing to keep them up to date.
This was split off from PR #11670.
You can check the output in the `contrib-tests` CI job output.

[chore] Generate `replace` directives automatically in `check-contrib`

---

.chloggen/revert-10931.yaml
cmd/mdatagen/internal/command_test.go
cmd/mdatagen/internal/samplereceiver/generated_component_telemetry_test.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/internal/templates/component_telemetry_test.go.tmpl
cmd/mdatagen/internal/templates/telemetry.go.tmpl
component/componenttest/obsreporttest.go
component/telemetry.go
config/configgrpc/configgrpc.go
config/configgrpc/go.mod
config/confighttp/confighttp.go
exporter/exporterhelper/generated_component_telemetry_test.go
exporter/exporterhelper/internal/metadata/generated_telemetry.go
processor/batchprocessor/batch_processor_test.go
processor/batchprocessor/generated_component_telemetry_test.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/batchprocessor/metadata.yaml
processor/memorylimiterprocessor/generated_component_telemetry_test.go
processor/memorylimiterprocessor/internal/metadata/generated_telemetry.go
processor/memorylimiterprocessor/memorylimiter_test.go
processor/processorhelper/generated_component_telemetry_test.go
processor/processorhelper/internal/metadata/generated_telemetry.go
receiver/receiverhelper/generated_component_telemetry_test.go
receiver/receiverhelper/internal/metadata/generated_telemetry.go
receiver/scraperhelper/generated_component_telemetry_test.go
receiver/scraperhelper/internal/metadata/generated_telemetry.go
service/generated_component_telemetry_test.go
service/internal/metadata/generated_telemetry.go
service/internal/proctelemetry/process_telemetry_test.go

This PR removes APIs that expose `configtelemetry.Level`. Internal functionality still uses the Level, but will be soon changed to use the new Instrument.Enabled.

Revert public API changes in #10931, preserve logic

---

.chloggen/feature-gate-help-cmd-option.yaml
featuregate/flag.go
featuregate/flag_test.go

Make sure `flagValue.String()` can be called even when flagValue is created by `reflect.New`
```go
import (
"flag"
"log"
"go.opentelemetry.io/collector/featuregate"
)
func main() {
fs := new(flag.FlagSet)
featuregate.GlobalRegistry().RegisterFlags(fs)
if err := fs.Parse([]string{"--help"}); err != nil {
log.Fatalf("failed to parse flags: %v", err)
}
}
```
Before this PR
```
Usage:
-feature-gates value
Comma-delimited list of feature gate identifiers. Prefix with '-' to disable the feature. '+' or no prefix will enable the feature.
panic calling String method on zero featuregate.flagValue for flag feature-gates: runtime error: invalid memory address or nil pointer dereference
failed to parse flags: flag: help requested
```
Note that there is a panic in the message.
After this PR 
``` …
```

Make sure flagValue.String() can be called even when flagValue is created by reflect.New

---

.github/CODEOWNERS

I am going to start filing PRs to add codeowners, I want all maintainers to get notified about them.
I also want all maintainers to get notified about all RFCs.

[chore] Add all maintainers as codeowners of CODEOWNERS file and RFC folder

---

cmd/builder/README.md

This was removed as part of https://github.com/open-telemetry/opentelemetry-collector/commit/cd6bfbb121393e0ece575926d9056a32fd91576c but the documentation was not updated.

[chore] ocb name flag is no longer valid

---

package.json

This is pinned because of https://github.com/tcort/markdown-link-check/issues/369

[chore] pin markdown-link-check

---

config/configgrpc/go.mod
config/confighttp/go.mod

Now that #11705 has been merged, splitting the `extension/auth/authtest` package into a separate module, this PR updates imports of the new module to an externally resolvable pseudo-version based on the merge commit (f2e05b5). (See #11668 for context on why this two-step process is necessary.)
Resolves #11465

[chore] Use pseudo-versions to require `authtest`

---

exporter/debugexporter/go.mod
exporter/debugexporter/go.sum
exporter/exporterhelper/exporterhelperprofiles/go.mod
exporter/exporterhelper/exporterhelperprofiles/go.sum
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/base_exporter_test.go
exporter/exporterhelper/internal/batch_sender_test.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/retry_sender_test.go
exporter/exporterhelper/internal/test_util.go
exporter/exporterprofiles/go.mod
exporter/exportertest/go.mod
exporter/exportertest/go.sum
exporter/go.mod
exporter/go.sum
exporter/nopexporter/go.mod
exporter/nopexporter/go.sum
exporter/otlpexporter/go.mod
exporter/otlpexporter/go.sum
exporter/otlphttpexporter/go.mod
exporter/otlphttpexporter/go.sum

This PR proceeds https://github.com/open-telemetry/opentelemetry-collector/pull/11637. It 
* Introduces a noop feature gate that will be used for queue batcher.
* Updates exporter tests to run with both the feature gate on and off.

[exporter] Feature gate for queue batcher

---

.github/workflows/check-links.yaml

This PR will run the "markdown-link-check" tool if the package.json changes even if no markdown files were updated. This will help to confirm that "markdown-link-check" is still working as expected after a version update/pin. 
If 1+ *.md files gets changed AND the package.json gets updated, it will only check the updated files to keep the same behaviour as before. 
If only the package.json gets updated it will test all existing *.md files. 
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/11606 
I tested/reproduced this manually: 
1. *.md file changes, but package.json not: https://github.com/niwoerner/opentelemetry-collector/actions/runs/11959750938
2. *.md file and package.json changes: https://github.com/niwoerner/opentelemetry-collector/actions/runs/11959777300 …

[chore] Run markdown link check if package.json changes

---

.github/workflows/api-compatibility.yml
.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test-windows.yaml
.github/workflows/build-and-test.yml
.github/workflows/builder-integration-test.yaml
.github/workflows/changelog.yml
.github/workflows/check-links.yaml
.github/workflows/contrib-tests.yml
.github/workflows/shellcheck.yml

In preparation for the merge queue potentially being enabled,, this PR adds the `merge_group` trigger to CI workflows that run in `main` pull requests.
Updates #11707

[chore] Add `merge_group` trigger to required workflows

---

.github/workflows/check-merge-freeze.yml
.github/workflows/scripts/check-merge-freeze.sh
.github/workflows/scripts/release-prepare-release.sh

As stated in the [Release Procedure document](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#releasing-opentelemetry-collector), all merging in Core should be halted while the "Prepare release" PR is open. This PR adds a CI job checking the existence of such a PR, allowing us to enforce these freezes automatically.
To make things simple, I decided to distinguish the "Prepare release" PR from others by using a new `prepare:merge-freeze` label. I modified the "Prepare release" action to include that label on the automatically created PR, but in rare cases where maintainers might create the PR themselves, the label can be added manually. Triagers will need to be careful not to accidentally add this label to any random PR to avoid artificial freezes. …

[chore] Add CI check to enforce merge freezes

---

.chloggen/11637-exporter-queue-batcher.yaml
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/batch_sender_test.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/internal/queue/default_batcher.go
exporter/internal/queue/disabled_batcher.go

This PR solves https://github.com/open-telemetry/opentelemetry-collector/issues/10368.
Previously we use a pushing model between the queue and the batch, resulting the batch size to be constrained by the `sending_queue.num_consumers`, because the batch cannot accumulate more than `sending_queue.num_consumers` blocked goroutines provide.
This PR changes it to a pulling model. We read from the queue until threshold is met or timeout, then allocate a worker to asynchronously send out the request.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10368
This PR swaps out `batch_sender` directly and still passes all the existing tests.

[exporter] Flip on queue batcher

---

Makefile

This is a partial revert of https://github.com/open-telemetry/opentelemetry-collector/pull/11670 as it is currently blocking the release due to the need to run go mod tidy multiple times.
I'm still investigating why tidy is needed multiple times, but for now I'm disabling the generate step, which was not run before and is currently blocking the release process

[chore] disable generate for now

---

.github/workflows/api-compatibility.yml
.github/workflows/changelog.yml

This PR removes the `merge_group` trigger from the two CI checks that failed in merge queues (but not in PRs). See tracking issue for details.
The reasoning for simply disabling them instead of modifying them to work in merge queues is three-fold:
- For `changelog` to be meaningful, it needs to only run for PRs with no `[chore]` title tag or `Skip changelog` label, but it seems there is no simple way to access this data in merge queue workflows unfortunately. (A possible complicated way may be to parse the ref (PR branch) name and query the title and labels in a script with the `gh` command.)
- `api-compatibility` is never meaningful because it seems to have been broken for a long time (see #7443)
- Both `changelog` and `api-compatibility` are checks on the _set of changes_ made by a PR, …

Fix merge queue CI

---

.github/workflows/changelog.yml

In a previous PR (#11797), I removed the `merge_group` trigger from the `changelog` and `api-compatibility` CI checks, which don't work properly in merge queues. However, `changelog` is a required check for the `main` branch, which means Github will wait for the check status to be reported even though the job never started, eventually resulting in a timeout and rejection from the queue. ([see this note in the docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#status-checks-with-github-actions-and-a-merge-queue))
This PR adds the `merge_group` trigger back in `changelog`, but uses an `if` to skip it outside of pull requests (which should count as success for the …

Enable but skip `changelog` workflow in merge queue

---

docs/coding-guidelines.md

Adding guidelines for experimental module naming as a result of [the vote](https://github.com/open-telemetry/opentelemetry-collector/issues/11783).
Resolves #11783

[docs] Add guidelines for experimental modules naming

---

exporter/internal/queue/default_batcher_test.go

[chore] Skip TestDefaultBatcher_NoSplit_WithTimeout on Windows

---

receiver/otlpreceiver/config.go
receiver/otlpreceiver/internal/profiles/otlp_test.go
receiver/otlpreceiver/internal/trace/otlp_test.go
receiver/receiver_test.go
receiver/receiverprofiles/receiver_test.go
receiver/receivertest/contract_checker.go
receiver/scraperhelper/config.go
scraper/factory_test.go
semconv/semconv_test.go
service/config_test.go
service/internal/builders/connector_test.go
service/internal/builders/extension_test.go
service/internal/graph/graph.go
service/internal/graph/host.go
service/internal/testcomponents/example_connector.go
service/internal/testcomponents/example_exporter.go
service/pipelines/config_test.go
service/service.go
service/service_test.go
service/telemetry/config_test.go
service/telemetry/factory.go
service/telemetry/factory_test.go
service/telemetry/logger.go
service/telemetry/tracer.go

[gofumpt](https://golangci-lint.run/usage/linters/#gofumpt) is a stricter format than gofmt, while being backwards compatible.

[chore]: enable gofumpt linter in receiver, scraper, semconv and service

---

.github/workflows/prepare-release.yml
.github/workflows/scripts/release-prepare-release.sh

The "Prepare Release" action failed during the latest release process, as the OpenTelemetry Bot, which opens the release PR, does not have the permissions to add the new `release:merge-freeze` label. This PR fixes this by creating the PR with the bot token, then adding the label separately using the regular CI token.
Since we already use default CI tokens on -contrib to add labels, I assume they have the permission to do that on this repo as well. I deemed this simpler than the alternative solutions mentioned in the tracking issue, though I'm not certain it will work.
Note that the tracking issue is a release blocker.
Fixes #11808
I'm not sure how I could test this without getting it merged first unfortunately. Once merged, we could try running the action, then closing the resulting PR …

[chore] Fix "Prepare Release" action

---

cmd/otelcorecol/go.mod

If we run our CI with `go-version: ~1.22.9`, we would need to update the toolchain every time minor go version is released to make the `checks` CI job pass
We probably should do something else with this

[chore] Fix CI checks job

---

versions.yaml

They are deprecated but should not be excluded from the next release

[chore] Do not exclude deprecated profiles modules

---

.golangci.yml
Makefile.Common
internal/tools/go.mod
internal/tools/tools.go

[gofumpt](https://golangci-lint.run/usage/linters/#gofumpt) is a stricter format than gofmt, while being backwards compatible.

[chore]: enable gofumpt globally

---

README.md
docs/security-best-practices.md

Provide caption of a link in README
Fixes #

[README] links caption

---

cmd/builder/internal/command_test.go
cmd/mdatagen/internal/command_test.go
config/configgrpc/configgrpc_benchmark_test.go
config/confighttp/compressor_test.go
config/confighttp/confighttp_test.go
pdata/plog/fuzz_test.go
pdata/plog/plogotlp/fuzz_test.go
pdata/pprofile/fuzz_test.go
pdata/pprofile/pprofileotlp/fuzz_test.go
pdata/ptrace/fuzz_test.go
pdata/ptrace/ptraceotlp/fuzz_test.go

* uses testify instead of testing.Fatal or testing.Error in processor

[chore]: use testify instead of testing.Fatal or testing.Error

---

.golangci.yml
cmd/builder/internal/builder/main_test.go
config/confighttp/compression_test.go
confmap/confmap_test.go
confmap/internal/e2e/types_test.go
confmap/resolver_test.go
exporter/exporterhelper/internal/test_util.go
exporter/internal/queue/persistent_queue_test.go
internal/testutil/testutil.go
internal/testutil/testutil_test.go
otelcol/collector_test.go
service/internal/promtest/server_util.go

[Thelper](https://golangci-lint.run/usage/linters/#thelper) detects tests helpers which is not start with t.Helper() method.
This only enables rules for naming and paramter order

[chore]: enable partially thelper linter

---

.github/workflows/check-merge-freeze.yml
.github/workflows/prepare-release.yml
.github/workflows/scripts/check-merge-freeze.sh
.github/workflows/scripts/release-prepare-release.sh

The last attempt at making the Merge freeze check work in release PRs failed (#11906). This PR tries a different approach: it changes the criteria of the Merge freeze check, so that a freeze is enacted iff there is an open PR authored by @opentelemetrybot whose title contains "[chore] Prepare release" (note that if it weren't for the author, this PR would qualify).
This PR additionally reverts #11849, so no label is added to the release PR. I also added the `pull_request.enqueued` trigger, taking inspiration [from Merge Freeze](https://docs.mergefreeze.com/github-merge-queue#how-it-works), to see if it could help reject PRs earlier.
I tried to make sure the freeze check would be properly skipped for the release PR itself, both in PR checks and in the merge queue, but given the state of …

[chore] Merge freeze check uses title to find Release PRs

---

README.md

https://github.com/open-telemetry/opentelemetry-collector/blob/main/Makefile#L174 shows v1.4.0, so the readme got stale?

[chore] Update README.md to correctly reflect OTLP Protocol version

---

exporter/exporterhelper/internal/base_exporter_test.go
exporter/exporterhelper/internal/batch_sender_test.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/retry_sender_test.go

Before fix: `defer setFeatureGateForTest(t, usePullingBasedExporterQueueBatcher, enableQueueBatcher)`
This means run `setFeatureGateForTest` in the end.
After fix: `defer setFeatureGateForTest(t, usePullingBasedExporterQueueBatcher, enableQueueBatcher)()`
This means: run `setFeatureGateForTest` immediately but execute the function returned from `setFeatureGateForTest` in the end.
Fixes #

[chore][exporterhelper] Fix feature gate setting for unit tests.

---

.golangci.yml

[chore]: clean up misspell configuration

---

.github/workflows/changelog.yml
.github/workflows/check-links.yaml

This is as recommended to address a warning about pinning npm install documented in https://github.com/ossf/scorecard/discussions/4422

[chore] call npm with ci instead of install

---

.github/workflows/build-and-test.yml
Makefile
Makefile.Common

Creates a target to output junit files from testing.  This PR also starts to use it in CI - we don't consume the Junits yet but it would be easy to add on.  This will be useful for a number of CI/Devx initiatives in the future.
My company, Datadog, plans to use this information to track the build stability of our code in contrib, as well as the stability of code we depend on here in collector.

[chore] Create gotest-with-junit Makefile target

---

docs/release.md

If more PRs are merged after the release PR commit, make sure to checkout the release branch to the release PR commit rather than the mainline head.

[chore][release.md] checkout release branch to the correct commit & update release schedule

---

.golangci.yml
client/doc_test.go

By default revive enables a list of rules. 
When a list of rules are defined thay are the only one enabled.
This reenable this default list

[chore]: reenable default revive rules

---

.github/workflows/prepare-release.yml

This updates the prepare release workflow. It:
- adds a top level permission to read-all only
- breaks apart checking for blockers that doesn't need special permissions
- breaks apart the piece to create an issue that only needs issues: write
- adds contents: write  to the last piece that creates a commit and a PR

[chore] restrict workflow steps to necessary permissions

---

docs/release.md

updates documentation to include changes in https://github.com/open-telemetry/opentelemetry-collector-releases/pull/684
run locally and via workflows in jackgopack4 fork
updates to release.md in docs folder

[chore] add release docs for artifact version bump script

---

exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go

This PR fixes `logsRequest`, `tracesRequest` and `metricsRequest` to NOT modify the input if `MergeSplit()` returns an error. Copy-pasted the doc string of `MergeSplit()` for references:
// MergeSplit is a function that merge and/or splits this request with another one into multiple requests based on the
// configured limit provided in MaxSizeConfig.
// All the returned requests MUST have a number of items that does not exceed the maximum number of items.
// Size of the last returned request MUST be less or equal than the size of any other returned request.
// **The original request MUST not be mutated if error is returned after mutation** or if the exporter is
// marked as not mutable. The length of the returned slice MUST not be 0.
// Experimental: This API is at the early stage of …

[chore] Fix bug in exporter.Request.MergeSplit()

---

exporter/exporterhelper/internal/batch_sender.go
exporter/exporterhelper/internal/request.go
exporter/exporterhelper/internal/retry_sender_test.go
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go
exporter/exporterhelper/xexporterhelper/profiles_batch.go
exporter/exporterhelper/xexporterhelper/profiles_batch_test.go
exporter/internal/queue/default_batcher.go
exporter/internal/queue/fake_request_test.go
exporter/internal/request.go

This PR removes the interface `exporter.Request.Merge()` because `Merge()` is just a special case of `MergeSplit()`.
With just one interface, we no longer need an if-else loop in the batcher based on MaxConfigSize. `MergeSplit()` should be able to handle both the case where MaxConfigSize is specified or the case where it is not
Fixes #
All the existing cases should still pass.

[chore] Deprecate the interface exporter.Request.Merge()

---

exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/xexporterhelper/profiles_batch.go

This PR fixes how `capacityLimit` is updated in `exporter.request.MergeSplit()`.
Before
```
if srcReq.ld.LogRecordCount() <= capacityLeft {
if destReq == nil {
destReq = srcReq
} else {
srcReq.ld.ResourceLogs().MoveAndAppendTo(destReq.ld.ResourceLogs())
}
capacityLeft -= destReq.ld.LogRecordCount()
continue
}
```
After
```
srcCount := srcReq.ld.LogRecordCount()
if srcCount <= capacityLeft {
if destReq == nil {
destReq = srcReq
} else {
srcReq.ld.ResourceLogs().MoveAndAppendTo(destReq.ld.ResourceLogs())
}
capacityLeft -= srcCount
continue
}
```
With that said, the original implementation does not cause any bug because "the larger for loop" loops through only two items. In the first loop, `destReq` is guaranteed to be `nil`, so `capacityLeft` is updated properly. In the second loop, we jump …

[chore] Nit-fix exporter.request.MergeSplit()

---

cmd/mdatagen/internal/loader_test.go
cmd/mdatagen/internal/samplereceiver/documentation.md
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/internal/samplereceiver/internal/metadatatest/generated_telemetrytest_test.go
cmd/mdatagen/internal/samplereceiver/metadata.yaml
cmd/mdatagen/internal/templates/telemetrytest_test.go.tmpl

Unblocks https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37051

[chore] [mdatagen] Fix generated telemetry tests

---

.github/workflows/check-merge-freeze.yml

To unblock https://github.com/open-telemetry/opentelemetry-collector/pull/12043, which is always rejected on the queue.
Apparently, `github.event.merge_group.head_commit.author.name` is `OpenTelemetry Bot` not `opentelemetrybot`. See https://github.com/open-telemetry/opentelemetry-collector/actions/runs/12658978490/job/35277057933. 
Since `github.event.merge_group.head_commit.author` doesn't have `login` field, I've switched the condition to use the `name` field on both `github.event.pull_request.user` and  `github.event.merge_group.head_commit.author`

[chore] Fix check merge freeze job

---

.golangci.yml
processor/memorylimiterprocessor/internal/mock_exporter.go
service/extensions/graph.go

[early-return](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return): In Go it is idiomatic to minimize nesting statements, a typical example is to avoid if-then-else constructions.

[chore]: enable early-return from revive

---

processor/memorylimiterprocessor/README.md

Verified with this config:
```yaml
processors:
memory_limiter:
check_interval: 1s
limit_percentage: 50
```
Output:
```console
2025-01-10T10:55:58.072+0100    info    memorylimiter@v0.117.0/memorylimiter.go:151     Using percentage memory limiter {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "total_memory_mib": 31755, "limit_percentage": 50, "spike_limit_percentage": 0}
2025-01-10T10:55:58.072+0100    info    memorylimiter@v0.117.0/memorylimiter.go:75      Memory limiter configured       {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "limit_mib": 15877, "spike_limit_mib": 3175, "check_interval": 1}
```

[chore] [processor/memory_limiter] docs: fix default value of `spike_limit_percentage`

---

.chloggen/mx-psi_default-provider.yaml
otelcol/otelcoltest/config.go
otelcol/otelcoltest/config_test.go
otelcol/otelcoltest/testdata/config_default_scheme.yaml
otelcol/otelcoltest/testdata/config_env.yaml

Adds `DefaultScheme` to test `otelcol.ConfigProvider`, so that the test behavior is equivalent to the real thing.
Relates to open-telemetry/opentelemetry-collector-contrib/pull/37122
Added a test that failed before adding the DefaultScheme.

[otelcoltest] Add DefaultScheme to test ConfigProvider

---

processor/memorylimiterprocessor/README.md

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12063

[chore] [processor/memory_limiter] docs: improve examples

---

service/internal/testcomponents/example_exporter.go
service/internal/testcomponents/example_receiver.go

This PR just cleans up some naming in the `testcomponents` package, so that no component kind has a monopoly on the generic version of a variable or function name.
Subset of #12057

[chore] Clean up naming in testcomponent package

---

.github/workflows/check-links.yaml

Added the same thing in #12055 but for fixing check-links action.

[chore] Fix check-links action to allow empty links

---

.chloggen/add-blocking.yaml
exporter/exporterqueue/bounded_memory_queue.go
exporter/exporterqueue/bounded_memory_queue_test.go
exporter/exporterqueue/cond.go
exporter/exporterqueue/persistent_queue.go
exporter/exporterqueue/persistent_queue_test.go
exporter/exporterqueue/sized_queue.go
exporter/exporterqueue/sized_queue_test.go

This functionality is not yet exposed to the user because there is no config available. One option to consider is to add a "blocking" bool in the queue config.

Add capability for memory and persistent queue to block when add items

---

.gitignore

Contrib has this folder, and I find it helpful for stashing working files (e.g. config files) for testing running the Collector from a binary.
Happy to take another approach if someone is doing something else to store files used to test the Collector locally.

[chore] Add `local` folder to .gitignore

---

.chloggen/add-blocking-option.yaml
exporter/exporterhelper/README.md
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterqueue/config.go
exporter/exporterqueue/queue.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5456

Add blocking option to control queue behavior when full

---

.golangci.yml
service/telemetry/internal/otelinit/config.go

[unnecessary-stmt](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unnecessary-stmt): This rule suggests to remove redundant statements like a break at the end of a case block, for improving the code's readability.

[chore]: enable unnecessary-stmt from revive

---

.chloggen/revert-change-name.yaml
processor/processortest/go.mod
processor/processortest/nop_processor.go

Revert the `nop_processor.NewNopSettings` change, as it is no longer needed.
Fixes #11433

[chore] Revert the change in processortest setting creation

---

.chloggen/fieldalignment_generated.yaml
cmd/mdatagen/internal/templates/component_test.go.tmpl
exporter/debugexporter/generated_component_test.go
exporter/nopexporter/generated_component_test.go
exporter/otlpexporter/generated_component_test.go
exporter/otlphttpexporter/generated_component_test.go

Change the generated code so it doesn't get impacted if you run fieldalignment.

[mdatagen] apply fieldalignment to generated code

---

service/internal/graph/graph.go
service/internal/graph/graph_test.go
service/internal/graph/zpages.go

Subset of #12057
This PR adds a test to validate the expected number of instances of each component. This framework becomes more useful once singleton components are explicitly supported.

[chore] Add test to validate expected component instances

---

service/internal/attribute/attribute.go
service/internal/attribute/attribute_test.go

This PR creates a new internal package which defines the correct set of attributes for each kind of component. 
This is a subset of #12057 which is broken off in order to reduce the overall size of that PR. As such, this package will not actually be used until #12057 is merged.

[chore] Add internal attribute package

---

.github/workflows/scripts/release-prepare-release.sh

This following the workaround suggested in https://github.com/cli/cli/issues/6485
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12129

[chore] attempt to apply gh workaround

---

.golangci.yml
client/doc_test.go
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/main.go
cmd/builder/internal/builder/main_test.go
cmd/mdatagen/internal/command.go
cmd/mdatagen/internal/command_test.go
cmd/mdatagen/internal/lint.go
cmd/mdatagen/internal/metadata.go
config/confighttp/compression_test.go
confmap/internal/e2e/fuzz_test.go
exporter/exporterqueue/persistent_queue.go
internal/memorylimiter/iruntime/total_memory_linux.go
internal/tools/semconvkit/main.go
pdata/pcommon/timestamp.go
pdata/pcommon/timestamp_test.go
pdata/pcommon/value.go
processor/memorylimiterprocessor/memorylimiter_test.go
service/internal/graph/node.go
service/internal/proctelemetry/process_telemetry.go
service/service.go
service/service_test.go

[nolintlint](https://golangci-lint.run/usage/linters/#nolintlint): Reports ill-formed or insufficient nolint directives.

[chore]: enable nolintlint

---

cmd/builder/README.md
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go
cmd/builder/internal/builder/main.go
cmd/builder/internal/builder/main_test.go
cmd/builder/internal/command.go
cmd/builder/internal/command_test.go

The primary purpose of this PR is to provide greater flexibility in how OTEL binaries are built, enabling the inclusion of debugging symbols when needed, without always stripping them by default.
Currently, debugging symbols are only retained when debug_compilation=true. However, this approach also disables all compiler inlining and optimizations (gcflags=all=-N -l) to ensure an exact match between written and executed code, resulting in a significant increase in CPU consumption. There are scenarios where we want binaries with debugging symbols and DWARF information while still allowing the compiler to optimize and inline. This PR addresses that need by introducing configurable GCFlags. 
`ocb --ldflags="" --gcflags="" --config=builder-config.yaml`
Fixes …

[chore] Ability to provide custom ld and gc flags

---

exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go

As part of the effort to cache request size to improve merge splitting performance
(See https://github.com/open-telemetry/opentelemetry-collector/issues/12137 and https://github.com/open-telemetry/opentelemetry-collector/pull/12136),  we want to make sure requests are created from create function instead of getting initialized via struct directly.
* `newLogsRequest` instead of `&logsRequest{}`
* `newMetrcsRequest` instead of `&metricsRequest{}`
* `newTracesRequest` instead of `&tracesRequest{}`
https://github.com/open-telemetry/opentelemetry-collector/issues/12137

[chore][testonly][exporter] Use new{Logs,Metrics,Traces}Request instead of &{logs,metrics,traces}Request{}

---

docs/component-stability.md

This PR slightly changes the wording of the "Stability levels and versioning" doc (`docs/component-stability.md`), which I found a bit confusing, in order to:
- Emphasize the important fact that stability levels for a component are defined _per signal_. At the moment this is only alluded to at the beginning and assumed in the last section. Moreover, things like the "Unmaintained" level may give the impression that stability levels always apply to an entire component.
- More cleanly separate the part about behavior changes from the part about API changes in the "Versioning" section.
This should not change the content or interpretation of the document.

[chore] Reword component stability doc

---

exporter/exporterhelper/logs.go
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go

This PR improves item-based merge splitting by caching item count in `exporter.request`. Benchmarks shows benefits the case where many requests are merged in the same batch. We observed roughly 30 - 75% latency improvement.
| Event Type              | Before (ns/merge) | After (ns/merge) | Diff percentage |
| :---------------- | :------: | :----: | ----: |
| Logs       |   3643.971   | 2513.947 | -31% |
| Metrics  |   24550.572  | 5847.417 | -76% |
| Traces   |  5172.710 | 3233.694  | -37% |
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12137
This PR adds four benchmarks for each event type
1. 1000 requests are merged into the same batch.
2. every incoming request is slightly above the limit and will cause a split.
3. the incoming request is split into 10 batches …

[chore][exporter][batcher] Improve exporter.request merge splitting performance by caching items count

---

.chloggen/opbexp.yaml
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/obsexporter.go
exporter/exporterhelper/internal/obsexporter_test.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/retry_sender.go
exporter/exporterhelper/obsreport_test.go

Even though we change the Span attributes, this is ok since tracing is still not stable.

[chore] Move exporter id attribute to the span

---

.chloggen/fix-bug-histogram-aggregation.yaml
cmd/mdatagen/internal/metric.go
cmd/mdatagen/internal/metric_test.go

See https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L254

[mdatagen] Fix bug where Histograms were marked as not supporting temporaly aggregation

---

exporter/exporterhelper/xexporterhelper/profiles.go
exporter/exporterhelper/xexporterhelper/profiles_batch.go
exporter/exporterhelper/xexporterhelper/profiles_batch_test.go

No need for a changelog since the cache items was added this release.

[chore] Apply, items cache logic to profiles

---

exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/traces.go

During https://github.com/open-telemetry/opentelemetry-collector/pull/12136 discussion, it was noted that the count may not always be called, but that is not true since we always call it in the observability sender. This PR only simplifies the logic and ensure we always have the right number.

[chore] Always initialize cachedItemsCount, it is used in observability sender

---

.chloggen/fieldalignment_generated_others.yaml
cmd/mdatagen/internal/sampleprocessor/generated_component_test.go
cmd/mdatagen/internal/samplereceiver/generated_component_test.go
cmd/mdatagen/internal/samplescraper/generated_component_test.go
cmd/mdatagen/internal/templates/component_test.go.tmpl
connector/forwardconnector/generated_component_test.go
processor/batchprocessor/generated_component_test.go
processor/memorylimiterprocessor/generated_component_test.go
receiver/nopreceiver/generated_component_test.go
receiver/otlpreceiver/generated_component_test.go

update other lifecycle generated tests to not be impacted by fieldalignment
See #12121 for original PR.

[mdatagen] update other lifecycle generated tests to not be impacted by fieldalignment

---

docs/rfcs/component-universal-telemetry.md

This is a documentation-only change to fix some typos in the Pipeline Component Telemetry RFC doc.

[chore][docs] Fix typos in Pipeline Component Telemetry RFC

---

cmd/mdatagen/internal/samplereceiver/metrics_test.go
processor/batchprocessor/batch_processor_test.go
processor/memorylimiterprocessor/memorylimiter_test.go
processor/processorhelper/logs_test.go
processor/processorhelper/metrics_test.go
processor/processorhelper/traces_test.go
scraper/scraperhelper/controller_test.go
scraper/scraperhelper/obs_logs_test.go
service/internal/proctelemetry/process_telemetry_linux_test.go
service/internal/proctelemetry/process_telemetry_test.go

A follow-up PR of #12179 , cc @bogdandrutu 
Note: This PR also removes those metric assertions which is actually testing metrics that doesn't belong to the package. They might be added due to the limitation of the AssertMetrics function. e.g. changes in `processor/memorylimitprocessor/memorylimiter_test.go`
Relevant to #12179 
Updated
n/a

[chore] Replace AssertMetrics with AssertEqualMetric series functions

---

.chloggen/deprecate-checkexporterlogs.yaml
component/componenttest/obsreporttest.go
exporter/exporterhelper/internal/obs_report_test.go
exporter/exporterhelper/logs_test.go

Deprecate `CheckExporterLogs` functions, also verified `CheckExporterLogs` function is not being used in the contrib repo as well.
Updated
Added

[component/componenttest] Deprecate CheckExporterLogs functions

---

.chloggen/deprecate-checkreceiverlogs.yaml
component/componenttest/obsreporttest.go
receiver/receiverhelper/obsreport_test.go

Deprecate `CheckReceiverLogs` functions, also verified `CheckReceiverLogs` function is not being used in the contrib repo as well.
Updated
Added

[component/componenttest] Deprecate CheckReceiverLogs functions

---

.chloggen/deprecate-checkexporterenqueue-functions.yaml
component/componenttest/obsreporttest.go
exporter/exporterhelper/internal/obs_report_test.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/traces_test.go

Deprecate `CheckExporterEnqueue*` functions, also verified `CheckExporterEnqueue*` functions are not being used in the contrib repo as well.
Updated
Added

[component/componenttest] Deprecate `CheckExporterEnqueue*` functions

---

.github/workflows/api-compatibility.yml
.github/workflows/build-and-test-arm.yml
.github/workflows/build-and-test-windows.yaml
.github/workflows/build-and-test.yml
.github/workflows/builder-integration-test.yaml
.github/workflows/changelog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/contrib-tests.yml
.github/workflows/perf.yml
.github/workflows/prepare-release.yml
.github/workflows/tidy-dependencies.yml
cmd/otelcorecol/go.mod

Vulnerability #1: GO-2025-3373
Usage of IPv6 zone IDs can bypass URI name constraints in crypto/x50[9](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/13003405341/job/36266082673?pr=12193#step:6:10)
More info: https://pkg.go.dev/vuln/GO-2025-3373
Standard library
Found in: crypto/x509@go1.22.[10](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/13003405341/job/36266082673?pr=12193#step:6:11)
Fixed in: crypto/x509@go1.22.[11](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/13003405341/job/36266082673?pr=12193#step:6:12)

Fix govulncheck related to crypto/x509

---

confmap/README.md
confmap/provider.go
confmap/provider_test.go

I tried to improve the docs on watchers based on the issue below
Fixes #12115
Clarified some code comments that were incorrect (there's no Retrieved.Get method) and included a new code sample for a Provider that uses the watcher func

doc: add detail to confmap watcher

---

VERSIONING.md

Add wording that allows us to update struct field tags if changes to the tags doesn't change the values of fields in the struct during serialization/deserialization.
This will allow us to add `omitempty` to fields on structs in stable packages. Adding this tag will cause fields which have zero values to not be written when marshaling into YAML, but there is no functional difference since missing fields during unmarshaling simply leaves a struct field with a zero value.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/12191.

[chore] Clarify allowed changes to struct field tags in VERSIONING.md

---

.chloggen/deprecate-checkexportermetrics.yaml
component/componenttest/obsreporttest.go
exporter/exporterhelper/internal/obs_report_test.go
exporter/exporterhelper/metrics_test.go

Deprecate `CheckExporterMetrics` functions, also verified `CheckExporterMetrics` function is not being used in the contrib repo as well.
Updated
Added

[component/componenttest] Deprecate `CheckExporterMetrics` functions

---

cmd/builder/README.md

adds a caveat to ocb cmd/builder documentation about `go.mod` version.
Fixes #11844 
Replaces #11845 
none
README.md

[chore] [cmd/builder] add caveat for go version in go.mod

---

.chloggen/mx-psi_extension-interface.yaml
extension/extension.go
otelcol/collector_test.go

Changes `extension.Extension` to a proper interface that embeds `component.Component` instead of being an alias.
Fixes the second point mentioned in https://github.com/open-telemetry/opentelemetry-collector/issues/11443#issuecomment-2616396687

[extension] Change from interface alias to embedding alias

---

.chloggen/newsettings.yaml
cmd/mdatagen/internal/samplereceiver/internal/metadatatest/generated_telemetrytest.go
cmd/mdatagen/internal/samplereceiver/metrics_test.go
cmd/mdatagen/internal/templates/telemetrytest.go.tmpl
component/componenttest/obsreporttest.go
component/componenttest/otelchecker.go
component/componenttest/telemetry.go
exporter/exporterhelper/internal/metadatatest/generated_telemetrytest.go
processor/batchprocessor/batch_processor_test.go
processor/batchprocessor/internal/metadatatest/generated_telemetrytest.go
processor/memorylimiterprocessor/internal/metadatatest/generated_telemetrytest.go
processor/memorylimiterprocessor/memorylimiter_test.go
processor/processorhelper/internal/metadatatest/generated_telemetrytest.go
processor/processorhelper/logs_test.go
processor/processorhelper/metrics_test.go
processor/processorhelper/traces_test.go
receiver/receiverhelper/internal/metadatatest/generated_telemetrytest.go
scraper/scraperhelper/controller_test.go
scraper/scraperhelper/internal/metadatatest/generated_telemetrytest.go
scraper/scraperhelper/obs_logs_test.go
scraper/scraperhelper/obs_metrics_test.go
service/internal/metadatatest/generated_telemetrytest.go
service/internal/proctelemetry/process_telemetry_linux_test.go
service/internal/proctelemetry/process_telemetry_test.go

This is the last functionality needed to replace `metadatatest.Telemetry` with `componenttest.Telemetry`. 
The `metadatatest.Telemetry` will be deprecated next release to give time to change contrib since it is a large change.

[metadatatest] Generate NewSettings that accepts componenttest.Telemetry

---

.chloggen/deprecate-checkexportermetricgauge.yaml
component/componenttest/obsreporttest.go
exporter/exporterhelper/internal/queue_sender_test.go

Deprecate `CheckReceiverMetricGauge` functions, also verified `CheckReceiverMetricGauge` function is not being used in the contrib repo as well.
Updated
Added

[component/componenttest] Deprecate `CheckExporterMetricGauge` functions

---

.chloggen/mx-psi_component-kind-structify.yaml
component/component.go
component/component_test.go
service/service_test.go

Changes the underlying type of `component.Kind` to be closer to [`pipeline.Signal`](https://pkg.go.dev/go.opentelemetry.io/collector/pipeline#Signal). Right now the type is defined within `component`, but it could be moved to an internal module so that we could have a different module exposing other value on this enum.
This is already doable today, the only thing this PR gives us is 
1. slightly more flexibility on things like making the concept of kind more complex (e.g. adding an adjective to a kind).
2. restricting external consumers from implementing their own component kinds without our explicit approval (with some kind of API we design)
I am not convinced this is _necessary_ to do, but we may as well do it.
This is technically a breaking change since `component.Kind(42)` was a valid …

[component] Make component.Kind a struct

---

otelcol/collector.go
otelcol/config.go
otelcol/config_test.go
otelcol/otelcoltest/config.go
service/config.go
service/config_test.go
service/pipelines/config.go
service/pipelines/config_test.go

Follow-up to https://github.com/open-telemetry/opentelemetry-collector/pull/12108.
This calls `component.ValidateConfig` on `otelcol.Config`, which causes `Validate` to be recursively called on all eligible structs in the config.
This has the following benefits:
1. `Validate` will now automatically be called instead of config structs needing to call it on member structs.
2. Paths to the exact key that caused a validation error in the config are now consistently printed.
3. If there are multiple errors in the config, they are now all returned to the user instead of just the first error encountered.

[chore] Remove manual calls to `Validate`

---

.chloggen/done-callback.yaml
exporter/exporterqueue/bounded_memory_queue.go
exporter/exporterqueue/bounded_memory_queue_test.go
exporter/exporterqueue/persistent_queue.go
exporter/exporterqueue/persistent_queue_test.go
exporter/exporterqueue/queue.go
exporter/internal/queue/batcher.go
exporter/internal/queue/consumers.go
exporter/internal/queue/default_batcher.go
exporter/internal/queue/disabled_batcher.go

This change will allow to simplify significantly the implementation for when queue is disabled and caller must block until the batch is constructed and processed downstream
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/8122
It is ok to have this as a breaking change since Queue is still experimental.

Change Queue interface to return a callback instead of an index

---

.chloggen/disabled-batcher-context.yaml
exporter/internal/queue/disabled_batcher.go

Finishes the implementation started in https://github.com/open-telemetry/opentelemetry-collector/pull/12225

Fix context propagation for DisabledBatcher

---

exporter/internal/queue/batcher.go
exporter/internal/queue/default_batcher_test.go
exporter/internal/queue/disabled_batcher_test.go

It is impossible to configure infinite workers today, see https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterqueue/config.go#L41

[chore] Remove impossible infinite workers use-case for Batcher

---

.chloggen/clenup-initialization.yaml
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/base_exporter_test.go
exporter/exporterhelper/internal/batch_sender.go
exporter/exporterhelper/internal/obs_report_sender.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/request_sender.go
exporter/exporterhelper/internal/retry_sender.go
exporter/exporterhelper/internal/retry_sender_test.go
exporter/exporterhelper/internal/timeout_sender.go

Also, this PR fixes a concurrency data issue that only affects users that manually turned on `exporter.UsePullingBasedExporterQueueBatcher` featuregate.
`exporter.UsePullingBasedExporterQueueBatcher` is still alpha in the last release.

Cleanup initialization order for exporterhelper

---

.chloggen/fix-traces-split.yaml
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go
exporter/exporterhelper/xexporterhelper/profiles_batch.go
exporter/exporterhelper/xexporterhelper/profiles_batch_test.go

This PR simplifies the MergeSplit logic while fixing a bug (see `TestMergeSplitManySmall*` on how to replicate that). The performance is also slightly improved by reducing some allocations, see:
**Before:**
```
goos: darwin
goarch: arm64
pkg: go.opentelemetry.io/collector/exporter/exporterhelper
cpu: Apple M2 Max
BenchmarkSplittingBasedOnItemCountManySmallTraces
BenchmarkSplittingBasedOnItemCountManySmallTraces-12    	     390	   3029960 ns/op	 4850499 B/op	   81094 allocs/op
PASS
```
**After:**
```
goos: darwin
goarch: arm64
pkg: go.opentelemetry.io/collector/exporter/exporterhelper
cpu: Apple M2 Max
BenchmarkSplittingBasedOnItemCountManySmallTraces
BenchmarkSplittingBasedOnItemCountManySmallTraces-12    	     414	   2898061 ns/op	 4850453 B/op	   81092 allocs/op
```

Fix MergeSplit issue that ignores the initial message size

---

.chloggen/fix-default-batcher.yaml
exporter/exporterhelper/internal/batch_sender_test.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterqueue/bounded_memory_queue.go
exporter/exporterqueue/bounded_memory_queue_test.go
exporter/exporterqueue/persistent_queue.go
exporter/exporterqueue/persistent_queue_test.go
exporter/exporterqueue/queue.go
exporter/internal/queue/batcher.go
exporter/internal/queue/default_batcher.go
exporter/internal/queue/default_batcher_test.go
exporter/internal/queue/disabled_batcher.go
exporter/internal/requesttest/fake_request.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12247

Fix default batcher to correctly call all done callbacks exactly once

---

config/configgrpc/doc.go
config/confighttp/doc.go

Adds note discussed on 2025-02-03 Collector stability meeting.

[chore][configgrpc,confighttp] Clarify that config structs are to be used for a single protocol and receiver

---

README.md

Update jpkroehling's affiliation

---

.chloggen/fix-concurrent-issue.yaml
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/obs_queue.go
exporter/exporterhelper/internal/obs_report_sender.go
exporter/exporterhelper/internal/queue_sender.go

This can happen when items are added to the memory queue and processed by the batcher in the same time with reading the number of items from this code.
Though our queue does not return error and still add the item unless the Context is cancelled, but likely because of a bug that does not work as expected, see https://github.com/open-telemetry/opentelemetry-collector/issues/12282

Fix concurrent issues caused by accessing request after calling Send

---

.chloggen/disabled-queue.yaml
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/batch_sender_test.go
exporter/exporterqueue/disabled_queue.go
exporter/exporterqueue/disabled_queue_test.go
exporter/exporterqueue/queue.go
exporter/internal/queue/default_batcher.go

This PR implements a version of a queue that can be used when users want to not have an async behavior and want to block until the request is send by the exporter.
This implementation is only used when batching is enabled, otherwise if both batching and queueing are disabled no queue or batch is configured.
**Benchmark results:**
```
goos: darwin
goarch: arm64
pkg: go.opentelemetry.io/collector/exporter/exporterqueue
cpu: Apple M2 Max
BenchmarkDisabledQueueOffer
BenchmarkDisabledQueueOffer-12    	 5839711	       187.5 ns/op	      24 B/op	       1 allocs/op
```

Implement sync disabled queue

---

.chloggen/deprecate-checkreceivertraces.yaml
component/componenttest/obsreporttest.go
receiver/otlpreceiver/go.mod
receiver/otlpreceiver/otlp_test.go
receiver/receiverhelper/obsreport_test.go

Deprecate `CheckReceiverTraces` functions
Updated
Added

[component/componenttest] Deprecate `CheckReceiverTraces` functions

---

exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/queue_sender.go

This change will allow to change current separate queue and batch unit tests to be merged and only use the "queue_batch" part of the exporter.

[chore] Merge batch_sander into the queue_sander

---

.chloggen/mx-psi_move-moduleinfo-to-method.yaml
extension/extension.go
otelcol/collector.go
service/extensions/extensions.go
service/internal/graph/host.go
service/internal/moduleinfo/moduleinfo.go
service/service.go

Moves `extension.Settings.ModuleInfo` to a `service.Host.GetModuleInfo` method.
This field probably fits better on `extension.Settings` or even in `component.BuildInfo`, but since its contents are a bit in flux per discussions like #12283, I would like to move it here to not stabilize it alongside the rest of `extension`.
The field is not used in any public code on Github, so I think it won't have a huge impact to remove it in one go, happy to do this in two steps if preferred.
One relevant difference is that this information is no longer available at extension build time, but rather after the `Start` method is called. Another relevant difference is that this is now available for all component kinds, not just extensions. This could be worked around (we could pass a different host …

[extension] Remove Settings.ModuleInfo and move to service.Host hidden method

---

.chloggen/confignet-omitempty.yaml
config/confignet/confignet.go
internal/e2e/confignet_test.go
internal/e2e/go.mod

Adds `omitempty` to all struct fields that are not set with any of the `NewDefault[...]` functions. If we like the approach here, I'll open PRs for other config modules.
Works toward https://github.com/open-telemetry/opentelemetry-collector/issues/12191
I added tests to check that this works when structs are marshaled with confmap in a separate module so as not to create a direct dependency on confmap within confignet.

[confignet] Add `omitempty` tags to fields

---

.chloggen/codeboten_rm-deprecated-119.yaml
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/internal/samplereceiver/internal/metadatatest/generated_telemetrytest.go
cmd/mdatagen/internal/samplereceiver/internal/metadatatest/generated_telemetrytest_test.go
cmd/mdatagen/internal/templates/telemetry.go.tmpl
cmd/mdatagen/internal/templates/telemetrytest.go.tmpl
cmd/mdatagen/internal/templates/telemetrytest_test.go.tmpl
component/componenttest/obsreporttest.go
component/componenttest/otelchecker.go
exporter/exporterhelper/internal/metadata/generated_telemetry.go
exporter/exporterhelper/internal/metadatatest/generated_telemetrytest.go
exporter/exporterhelper/internal/metadatatest/generated_telemetrytest_test.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
processor/batchprocessor/internal/metadatatest/generated_telemetrytest.go
processor/batchprocessor/internal/metadatatest/generated_telemetrytest_test.go
processor/memorylimiterprocessor/internal/metadatatest/generated_telemetrytest.go
processor/memorylimiterprocessor/internal/metadatatest/generated_telemetrytest_test.go
processor/processorhelper/internal/metadatatest/generated_telemetrytest.go
processor/processorhelper/internal/metadatatest/generated_telemetrytest_test.go
receiver/receiverhelper/internal/metadatatest/generated_telemetrytest.go
receiver/receiverhelper/internal/metadatatest/generated_telemetrytest_test.go
scraper/scraperhelper/internal/metadatatest/generated_telemetrytest.go
scraper/scraperhelper/internal/metadatatest/generated_telemetrytest_test.go
service/internal/metadata/generated_telemetry.go
service/internal/metadatatest/generated_telemetrytest.go
service/internal/metadatatest/generated_telemetrytest_test.go

Removing all v0.119.0 deprecated funcs.

Remove deprecated funcs

---

config/configauth/README.md

- Adds headings so as to have anchor IDs that the docs can refer to.
- This is proposed, in part, to help address https://github.com/open-telemetry/opentelemetry.io/issues/6234
/cc @open-telemetry/docs-maintainers

[editorial] Add headings to configauth/README.md

---

.chloggen/consumer-message.yaml
consumer/logs.go
consumer/metrics.go
consumer/traces.go
consumer/xconsumer/profiles.go

The problem here is that we have components like batchprocessor or others which are keeping a reference of the data and eventually modifying them without any concurrent access protection. Hence, it is required for the callers to not access any data that were passed downstream.
This is not a backwards incompatible change, since pdata is not thread-safe this is a MUST to have here (consider a bug for not being documented) otherwise things will not work in the processing pipelines.

Clarify that data cannot be accessed after Consume* func is called

---

.chloggen/mx-psi_extensiontest-withtype.yaml
.chloggen/mx-psi_type-mismatch.yaml
cmd/mdatagen/internal/sampleprocessor/generated_component_test.go
cmd/mdatagen/internal/samplereceiver/generated_component_test.go
cmd/mdatagen/internal/samplescraper/generated_component_test.go
cmd/mdatagen/internal/templates/component_test.go.tmpl
connector/forwardconnector/generated_component_test.go
exporter/debugexporter/generated_component_test.go
exporter/nopexporter/generated_component_test.go
exporter/otlpexporter/generated_component_test.go
exporter/otlphttpexporter/generated_component_test.go
extension/extension.go
extension/extension_test.go
extension/extensiontest/nop_extension.go
extension/memorylimiterextension/factory_test.go
extension/memorylimiterextension/generated_component_test.go
extension/zpagesextension/factory_test.go
extension/zpagesextension/generated_component_test.go
processor/batchprocessor/generated_component_test.go
processor/memorylimiterprocessor/generated_component_test.go
receiver/nopreceiver/generated_component_test.go
receiver/otlpreceiver/generated_component_test.go

Explicitly error out if the passed `component.ID` does not have a matching `component.Type` 
Updates #12221

[extension] Error out if passed extension.Settings has incorrect type

---

.chloggen/configgrpc-omitempty.yaml
config/configgrpc/configgrpc.go
internal/e2e/configgrpc_test.go

I didn't add the tag to any fields that have defaults set, since setting these values to Go's zero value for that type would be a meaningful configuration option that should appear in the config.
I think we could consider updates to the marshaler in the future to make it possible to omit fields that have values matching the ones produced by the `NewDefault[...]` functions, but that will be a more involved effort we can tackle later.
Works toward https://github.com/open-telemetry/opentelemetry-collector/issues/12191

[configgrpc] Add `omitempty` tag to fields

---

.github/CODEOWNERS

This PR adds the releases-approvers user group as codeowners for all files related to the release.
Parf of https://github.com/open-telemetry/opentelemetry-collector/pull/11577
https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/rfcs/release-approvers.md

[chore] Update codeowners according to releases-approvers RFC

---

.chloggen/unique-aliases.yaml
cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go
cmd/builder/internal/builder/main_test.go

This PR ensures that unique aliases are used for modules with same suffix.
Fixes #12162

Ensure unique aliases

---

.chloggen/convert-configprovider-struct.yaml
otelcol/collector.go
otelcol/collector_test.go
otelcol/configprovider.go

The `ConfigProvider` interface is not very useful since it isn't used by `otelcol.Collector` anymore since we moved to creating it through `ConfigProviderSettings` inside `otelcol.Collector`. Therefore, we should just make `configProvider` the concrete implementation and remove the interface. We could consider entirely removing `ConfigProvider` from the API, but it is used by some downstream distributions, and there is no other way to marshal YAML into `otelcol.Config`, so we would need to make additional changes to provide an adequate replacement.
We could also follow our deprecation process for this change, but in my opinion that will only cause more churn for downstream consumers since they will need to update their code multiple times throughout the process instead of just once.

[otelcol] Make the `ConfigProvider` interface a struct

---

config/confighttp/confighttp.go

This PR deletes the TODO comment that sparked #9382. The original intent is a bit unclear, but it is probably addressed by #11769. See tracking issue for discussion and related PRs.
Resolves #9382

[chore] Remove resolved TODO about span name prefix

---

cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
cmd/mdatagen/internal/templates/telemetry.go.tmpl
exporter/exporterhelper/internal/metadata/generated_telemetry.go
processor/batchprocessor/internal/metadata/generated_telemetry.go
service/internal/metadata/generated_telemetry.go

Missed by https://github.com/open-telemetry/opentelemetry-collector/pull/12304, this variables can no longer be initialized so this becomes dead code.

[chore] Remove dead code from mdatagen.

---

cmd/mdatagen/internal/templates/component_test.go.tmpl

This PR makes `"go.opentelemetry.io/collector/component"` to be always present to create component type:
```
var typ = component.MustNewType("{{ .Type }}")
```
cc @mx-psi 
Relevant to #12305 
n/a
n/a

[chore] Fix component test template

---

.chloggen/mx-psi_deprecate-create-methods.yaml
connector/connector.go
connector/xconnector/connector.go
exporter/exporter.go
exporter/xexporter/exporter.go
processor/processor.go
processor/xprocessor/processor.go
receiver/receiver.go
receiver/xreceiver/profiles.go
scraper/factory.go

Deprecate `Create*` methods. This is a small part of #12305, but applied to all other component kinds
Updates #12221

Deprecate 'Create*' methods

---

exporter/exporterhelper/README.md

Fix `sending_queue` docs: the comment for `queue_size` was cut from the section by `blocking` item

[chore] Update exporterhelper README.md

---

exporter/otlpexporter/factory.go
receiver/otlpreceiver/config_test.go
receiver/otlpreceiver/factory.go
receiver/otlpreceiver/go.mod

According to [the coding guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/coding-guidelines.md#default-configuration), config structs should be initialized using the corresponding `NewDefaultX` function, and fields overwritten as necessary. This PR makes sure that the OTLP receiver and gRPC OTLP exporter follow this guideline.
Implemented naively, this would be a breaking change, as there are multiple default values provided by these functions that behave differently from the zero value. Notably, `confighttp.NewDefaultServerConfig` creates an HTTPS server which rejects insecure connections, whereas the current default (`ServerConfig.TLSSetting: nil`) accepts them.
I think deciding whether `confighttp` and `configgrpc`'s defaults are appropriate for …

[receiver/otlp, exporter/otlp] Use NewDefaultConfig

---

.chloggen/mx-psi_toclient-option.yaml
config/confighttp/confighttp.go

Adds `ToClientOption` option type to future-proof `ToClient` method. It has no current uses.
Skipping the deprecation process per [this exception](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/coding-guidelines.md#exceptions).
Fixes #12353

[confighttp] Add ToClientOption

---

.github/workflows/check-links.yaml

This was left behind when we moved to lychee

[chore] remove unused variable

---

Makefile

Not sure if anyone is actually using `make mdatagen-test`, but it is failing on main because of missing imports. This is because `mdatagen` does not work without a subsequent `goimports` pass. This PR adds a `make fmt` step to make it pass again.

[chore] Add fmt step to mdatagen-test

---

.chloggen/fix-otlp-http-exp.yaml
exporter/otlphttpexporter/otlp.go
exporter/otlphttpexporter/otlp_test.go

Small improvement to not create a throttled error when delay is 0, same behavior.

Fix otlphttpexporter parsing logic for Retry-After

---

Makefile

This PR enables the `make generate-contrib` step in `make check-contrib` originally introduced in #11670, which allows testing the latest version of the mdatagen against contrib. It had been disabled as initial remediation against #11795, which has since been resolved by making `make gotidy` on contrib tidy modules in topological order.
Fixes #11167
Modifying `mdatagen` locally to crash on startup causes `make check-contrib` to fail.

[chore] Enable `generate-contrib` step in `check-contrib`

---

.github/workflows/build-and-test-arm.yml

Switches Linux ARM64 runners to the public version.
Handles https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
CI
Already done in .NET, .NET Auto and rust. It will allow to remove private runners from otel org and execute whole pipeline on public forks.

[chore] Use public Linux ARM64 runners

---

.chloggen/ensure-queue-size-update.yaml
exporter/exporterhelper/internal/batch_sender_test.go
exporter/exporterqueue/async_queue_test.go
exporter/exporterqueue/disabled_queue.go
exporter/exporterqueue/memory_queue.go
exporter/exporterqueue/persistent_queue.go
exporter/exporterqueue/persistent_queue_test.go

This PR changes when the size of the queues is updated, previously the size was updated when the element was removed from the queue but before was fully consumed (done callback was called), after this PR the size is updated when done callback is called.
This change ensures that the queue size limit applies to the whole exporter and allows better memory control for the users.

Update queue size after the element is done exported

---

cmd/otelcorecol/go.mod
exporter/debugexporter/go.mod
exporter/otlpexporter/go.mod
exporter/otlphttpexporter/go.mod
internal/e2e/go.mod

Bumps `xexporterhelper` pseudoversion to work around this error in `make update-otel`:
```
go: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/oteltestbedcol imports
go.opentelemetry.io/collector/exporter/debugexporter imports
go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper tested by
go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper.test imports
go.opentelemetry.io/collector/exporter/internal/requesttest: package go.opentelemetry.io/collector/exporter/internal/requesttest provided by go.opentelemetry.io/collector/exporter at latest version v0.119.0 but not at required version v0.119.1-0.20250217142445-a567a0176541
```

[chore] More pseudoversions bumps

---

.github/workflows/ping-codeowners-on-new-issue.yml

Reduce the scope of permissions given to the github token.

[chore] update permissions for ping-codeowners-new-issues workflow

---

.chloggen/confighttp-remove-pointers.yaml
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
exporter/otlphttpexporter/config_test.go

I was looking through our defaults for a few `confighttp.ClientConfig` fields and found that `0` disables these fields in the underlying `http.Transport` object, which means we don't need them to be pointers.
Docs for the four fields we set in `http.Transport` here: https://pkg.go.dev/net/http#Transport.MaxIdleConns
I also stopped assigning defaults to any fields we take from `http.DefaultTransport` where setting them is a no-op since they aren't set in `http.DefaultTransport`.
Helps unblock confighttp 1.0 from depending on https://github.com/open-telemetry/opentelemetry-collector/issues/9478

[confighttp] Remove pointers from integer fields

---

.chloggen/codeboten_fix-12436.yaml
service/telemetry/internal/migration/testdata/v0.2.0_metrics.yaml
service/telemetry/internal/migration/testdata/v0.2.0_traces.yaml
service/telemetry/internal/migration/v0.2.0_test.go
service/telemetry/internal/migration/v0.3.0.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12436

[service] fix bug in parsing `service::telemetry` configuration

---

.chloggen/codeboten_bump-config-pkg.yaml
otelcol/collector_test.go
otelcol/testdata/otelcol-multipleheaders.yaml
service/telemetry/internal/migration/testdata/v0.2.0_metrics.yaml
service/telemetry/internal/migration/v0.2.0.go
service/telemetry/internal/migration/v0.2.0_test.go

Converting headers from config schema v0.2.0 to v0.3.0 was causing a nil dereferencing issue by incorrectly setting the name/value pair to a nil pointer. Added a test in both the loading of the config in otelcol, as well as the migration code unit test.
Fixes #12439

[service] fix v0.2.0 to v0.3.0 conversion bug

---

.chloggen/mdatagen-fix.yaml
cmd/mdatagen/internal/templates/metrics.go.tmpl

Re-adds the missing import for the `ResourceAttributes` for metrics generation. This impacts receivers that emit resource attributes. Filter is still within the template code for resource attributes, but not imported.
Fixes #12455

[mdatagen] fix missing resource attributes import in metrics template

---

.chloggen/mx-psi_component-1.0.yaml
versions.yaml

Marks module as stable.
Note that this does **not** mark `componenttest` or `componentstatus` as stable.
Fixes #9376

[component] Mark module as stable

---

docs/coding-guidelines.md

Add guidelines for naming Go modules

[chore] Add naming guidance for modules prefix

---

.chloggen/finishsize.yaml
.chloggen/finishsize_breaking.yaml
.chloggen/finishsize_deprecation.yaml
exporter/exporterbatcher/config.go
exporter/exporterbatcher/config_test.go
exporter/exporterbatcher/sizer_type.go
exporter/exporterbatcher/sizer_type_test.go
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/batcher/default_batcher.go
exporter/exporterhelper/internal/batcher/default_batcher_test.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/request/request.go
exporter/exporterhelper/internal/requesttest/fake_request.go
exporter/exporterhelper/internal/retry_sender_test.go
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go
exporter/exporterhelper/xexporterhelper/go.mod
exporter/exporterhelper/xexporterhelper/profiles_batch.go
exporter/exporterhelper/xexporterhelper/profiles_batch_test.go
exporter/exportertest/go.mod
exporter/otlpexporter/config_test.go
exporter/otlpexporter/testdata/config.yaml

This PR also temporary removes "bytes" as supported sizer type since it is not yet implemented.

Start using the new SizeConfig

---

.github/workflows/contrib-tests.yml

Fix the build as cmd-1 is no longer used as a group for contrib tests.

[chore] remove cmd-1 contrib test group

---

cmd/mdatagen/metadata-schema.yaml

The `telemetry::level` key in `metadata.yaml` wasn't used for anything, and support for it was dropped in #12144. However, it was never removed from the schema file. This PR fixes that.

[chore][mdatagen] Remove telemetry::level from schema file

---

exporter/exporterbatcher/config.go
exporter/exporterbatcher/config_test.go

In the batcher config, ignore deprecated `min_size_items` and `max_size_items` fields if new `min_size` and `max_size` are set.
A follow-up to https://github.com/open-telemetry/opentelemetry-collector/pull/12486.

[chore] [exporterhelper/batcher] Ignore deprecated fields if new set

---

cmd/builder/internal/builder/templates/main.go.tmpl
cmd/otelcorecol/main.go

Puts the keys in `ConfigProviderSettings` to all be on their own lines like the other keys in the struct.

[chore][cmd/builder] Improve main.go template formatting

---

exporter/exporterbatcher/sizer_type.go
exporter/exporterhelper/internal/sizer/logs_sizer.go
exporter/exporterhelper/internal/sizer/logs_sizer_test.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
pdata/plog/pb.go

This PR implements serialized bytes based batching.
https://github.com/open-telemetry/opentelemetry-collector/issues/3262
```
BenchmarkSplittingBasedOnItemCountManySmallLogs-10                    	     409	   2822478 ns/op	 3148718 B/op	   71082 allocs/op
BenchmarkSplittingBasedOnByteSizeManySmallLogs-10                     	     412	   2890594 ns/op	 3156103 B/op	   71242 allocs/op
BenchmarkSplittingBasedOnItemCountManyLogsSlightlyAboveLimit-10       	      38	  27579702 ns/op	43531582 B/op	  700471 allocs/op
BenchmarkSplittingBasedOnByteSizeManyLogsSlightlyAboveLimit-10        	      24	  43067219 ns/op	43639889 B/op	  702927 allocs/op
BenchmarkSplittingBasedOnItemCountHugeLogs-10                         	      40	  29722710 ns/op	41922925 B/op	  690300 allocs/op …
```

[exporter][batching] Serialized bytes based batching for logs

---

.chloggen/fix-wrong-error-log.yaml
exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/xexporterhelper/profiles.go

The problem was that in the logging statement (in all signals) we log `err` instead of `cErr`. The good part is that this is not a UB, because if we get to the point where that function is called, the `err` was nil otherwise and never modified again so not race condition in accessing it.
Separate the lambda function in a different function so we don't repeat the same mistake of capturing other params by mistake.

Fix bug where the error logged when conversion of data fails is always nil

---

.chloggen/mx-psi_deprecate-func-methods.yaml
extension/extensionauth/client.go
extension/extensionauth/server.go

Depends on #12478, deprecates methods that are unnecessary

[extension/extensionauth] Deprecate methods on Func types

---

config/configauth/configauth_test.go
config/configgrpc/configgrpc_test.go
config/confighttp/confighttp_test.go
extension/auth/client.go
extension/auth/server.go
extension/extensionauth/client.go
extension/extensionauth/client_test.go
extension/extensionauth/server.go
extension/extensionauth/server_test.go

Adds errors in return type to `extensionauth.New*` functions. This is not a breaking change since `extensionauth` is an unreleased module.

[chore][extensionauth] Return error on NewClient and NewServer constructors

---

.chloggen/service-omitempty.yaml
service/config.go
service/config_test.go
service/telemetry/config.go
service/telemetry/internal/migration/v0.3.0.go

Update config structs in the service module to include `omitempty` tags.
Works toward https://github.com/open-telemetry/opentelemetry-collector/issues/12191

[service] Add `omitempty` tag to config fields

---

exporter/exporterhelper/logs.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/xexporterhelper/profiles.go

Follow-up from https://github.com/open-telemetry/opentelemetry-collector/pull/12510 cc @bogdandrutu

[chore] fix typos in error messages "Failed to convert metrics"

---

.chloggen/break-exporterqueue-factory.yaml
.chloggen/new-queue-factory.yaml
exporter/exporterhelper/common.go
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/base_exporter_test.go
exporter/exporterhelper/internal/batcher/disabled_batcher_test.go
exporter/exporterhelper/internal/obs_queue.go
exporter/exporterhelper/internal/obs_queue_test.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/retry_sender_test.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/queue_sender.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/xexporterhelper/profiles.go
exporter/exporterqueue/config.go
exporter/exporterqueue/persistent_queue.go
exporter/exporterqueue/persistent_queue_test.go
exporter/exporterqueue/queue.go

Remove exporterqueue.Factory and simplify exportehelper.WithQueueRequest

---

.chloggen/mx-psi_remove-withtype.yaml
connector/connectortest/connector.go
exporter/exportertest/nop_exporter.go
extension/extensiontest/nop_extension.go
processor/processortest/nop_processor.go
receiver/receivertest/nop_receiver.go
scraper/scrapertest/settings.go

Removes deprecated `NewNopSettingsWithType` functions
Updates #12221, follows #12452

Remove WithType functions

---

exporter/exporterhelper/internal/sizer/logs_sizer.go
exporter/exporterhelper/internal/sizer/logs_sizer_test.go

This is not used because the bytes sizer is not enabled yet.

[chore] Fix logs bytes delta size

---

Makefile.Common
cmd/builder/internal/builder/main.go

This was missed in the upgrade of go1.24

[chore] update min version in tidy

---

exporter/exporterhelper/internal/sizer/logs_sizer.go
exporter/exporterhelper/internal/sizer/logs_sizer_test.go
exporter/exporterhelper/internal/sizer/metrics_sizer.go
exporter/exporterhelper/internal/sizer/metrics_sizer_test.go
exporter/exporterhelper/internal/sizer/proto_delta_sizer.go
exporter/exporterhelper/internal/sizer/proto_delta_sizer_test.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
pdata/pmetric/pb.go

This PR implements serialized bytes based batching for metrics.
https://github.com/open-telemetry/opentelemetry-collector/issues/3262
Continuation of #12299 made by @sfc-gh-sili.

Bytes based batching for metrics

---

service/service_test.go

I noticed the service tests were a little flaky due to using the default Prometheus port. This should at least reduce the frequency where this happens if not eliminate it.
I did two things to help elimination contention for the port:
1. Disable the Prometheus server in tests where it isn't needed.
2. Ensure the port is randomized in tests where it is needed.

[chore] Reduce port contention in service tests

---

consumer/consumererror/doc.go
receiver/doc.go

Reorganizes receiver docs to remove mentions to consumererror specifics in the receiver package

[chore] Reorganize documentation regarding consumer errors for receiver

---

pdata/pprofile/attributes.go
pdata/pprofile/attributes_test.go

As discussed in https://github.com/open-telemetry/opentelemetry-collector/issues/12561, this switches the `pprofile.AddAttribute` method to use `pcommon.Value` rather than raw data.
I didn't add a changelog entry, because this method has not been released yet. So the [introduction changelog entry](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.chloggen/pprofile-add-attribute.yaml) should be enough.
Benchmark tests:
```
goos: darwin
goarch: arm64
pkg: go.opentelemetry.io/collector/pdata/pprofile
cpu: Apple M1 Max
BenchmarkAddAttribute/with_a_new_string_attribute-10            47255384                25.08 ns/op           16 B/op          1 allocs/op
BenchmarkAddAttribute/with_an_existing_attribute-10             46872556                25.16 ns/op           16 B/op …
```

Switch the pprofile.AddAttribute to use pcommon.Value rather than raw data

---

.chloggen/fix_process_metrics_disable.yaml
service/service.go

Process registration protection for telemetry level being set to "None"
Fixes #12098
Manual testing on an AIX 7.3 system rented from SiteOx:
```
-bash-5.2# ./otelcorecol_aix_ppc64 --config ./example.yaml 
2025-03-11T16:52:04.318-0500    info    service@v0.121.0/service.go:193 Setting up own telemetry...
2025-03-11T16:52:04.318-0500    info    service@v0.121.0/service.go:238 Skipped telemetry setup.
2025-03-11T16:52:04.318-0500    info    service@v0.121.0/service.go:260 Starting otelcorecol... {"Version": "0.121.0-dev", "NumCPU": 8}
2025-03-11T16:52:04.319-0500    info    extensions/extensions.go:40     Starting extensions...
2025-03-11T16:52:04.319-0500    info    service@v0.121.0/service.go:283 Everything is ready. Begin running and processing data.
2025-03-11T16:52:13.786-0500  info …
```

Fix process metrics disable

---

.github/workflows/builder-snapshot.yaml
cmd/builder/README.md

This PR fixes a few minor things in the OCB release test workflow:
- fix triggers on OCB changes
- remove non-existent log output inside the GH issue generation step
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12624

[chore] Fix OCB snapshot workflow

---

.chloggen/delete_old_status.yaml
cmd/mdatagen/internal/command.go
cmd/mdatagen/internal/command_test.go
cmd/mdatagen/internal/testdata/basic_pkg.yaml

Delete generated_status.go if the component type doesn't require it.
Fixes #12346

[mdatagen] delete generated_status.go in case it is not required

---

docs/release.md

Once [contrib#38534](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38534) is merged, the manual changes that were necessary in step 1 of releasing contrib should now be included in step 2 (the Prepare Release CI workflow). This PR updates the release doc to remove step 1.
Updates #12294

[chore] Update release doc to remove step 1 of releasing contrib

---

.chloggen/add-supports-signal-func.yaml
cmd/mdatagen/internal/command.go
cmd/mdatagen/internal/metadata.go

This PR added `supportsSignal` func to `Metadata` type to reduce duplicated code blocks for checking supported signals.
n/a
Already covered
Added

[mdatagen] Add supportsSignal func

---

.chloggen/rm-request-export.yaml
exporter/exporterhelper/constants.go
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/base_exporter_test.go
exporter/exporterhelper/internal/batcher/default_batcher_test.go
exporter/exporterhelper/internal/batcher/disabled_batcher_test.go
exporter/exporterhelper/internal/obs_report_sender_test.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/request/request.go
exporter/exporterhelper/internal/requesttest/request.go
exporter/exporterhelper/internal/requesttest/sink.go
exporter/exporterhelper/internal/retry_sender_test.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/request.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go
exporter/exporterhelper/traces_test.go
exporter/exporterhelper/xexporterhelper/constants.go
exporter/exporterhelper/xexporterhelper/profiles.go
exporter/exporterhelper/xexporterhelper/profiles_batch.go
exporter/exporterhelper/xexporterhelper/profiles_batch_test.go
exporter/exporterhelper/xexporterhelper/profiles_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/8950
The logic behind this, is that during merging and splitting we should not care about the export func (see complicated logic removed in FakeRequest of in the pdata requests implementations).
Also, this simplify what user should carry with the request.

Replace exporterhelper Request.Export with passing a ConsumeRequest func

---

pdata/pcommon/map.go

Remove the deprecation notice until the v0.122.0 release is complete.
After trying to migrate from `Range` to `All` in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38676, I think the changes required for this will be sufficiently large that we should avoid doing them during a release.

[chore] Remove deprecation notice for `(pcommon.Map).Range`

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
extension/memorylimiterextension/go.mod
extension/memorylimiterextension/go.sum
internal/e2e/go.mod
internal/e2e/go.sum
internal/memorylimiter/go.mod
internal/memorylimiter/go.sum
otelcol/go.mod
otelcol/go.sum
otelcol/otelcoltest/go.mod
otelcol/otelcoltest/go.sum
processor/memorylimiterprocessor/go.mod
processor/memorylimiterprocessor/go.sum
service/go.mod
service/go.sum

The cross-build test for the AIX platform (a tier 3 platform) is failing on main after the upgrade #12654. This is due to a bug in that patch release that was reported [here](https://github.com/shirou/gopsutil/issues/1806), but the fix hasn't been released yet. For that reason, I suggest reverting the upgrade until the next release.

Revert "fix(deps): update module github.com/shirou/gopsutil/v4 to v4.25.2 (#12654)"

---

cmd/otelcorecol/go.mod
cmd/otelcorecol/go.sum
internal/e2e/go.mod
internal/e2e/go.sum
otelcol/go.mod
otelcol/go.sum
otelcol/otelcoltest/go.mod
otelcol/otelcoltest/go.sum
service/go.mod
service/go.sum

Contrib tests are currently failing on main with the following build error:
```
Error: /home/runner/go/pkg/mod/github.com/prometheus/prometheus@v0.300.1/util/logging/file.go:42:23: undefined: promslog.AllowedFormat
```
I believe this is because of the update in #12656: there is [a breaking change in `github.com/prometheus/common` 0.63.0](https://github.com/prometheus/common/pull/754) that is incompatible with the version of `github.com/prometheus` used in some contrib modules. While the latter package [has been updated](https://github.com/prometheus/prometheus/pull/16210) on main, the updated version hasn't been released yet, so I this the only solution is to revert this PR until then.

Revert "fix(deps): update module github.com/prometheus/common to v0.63.0 (#12656)"

---

exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/obs_queue.go
exporter/exporterhelper/internal/obs_queue_test.go
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queue_sender_test.go
exporter/exporterhelper/internal/queuebatch/disabled_batcher_test.go
exporter/exporterhelper/internal/queuebatch/disabled_queue.go
exporter/exporterhelper/internal/queuebatch/memory_queue.go
exporter/exporterhelper/internal/queuebatch/persistent_queue.go
exporter/exporterhelper/internal/queuebatch/persistent_queue_test.go
exporter/exporterhelper/internal/queuebatch/queue.go
exporter/exporterhelper/internal/queuebatch/queue_batch.go
exporter/exporterhelper/internal/queuebatch/sizer.go
exporter/exporterhelper/internal/queuebatch/sizer_test.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/request.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/xexporterhelper/profiles.go

Users cannot yet configure which sizer to use, so not yet a changelog entry for this.

[chore] Allow to configure available sizers in the queuebatch Settings

---

.chloggen/avoid-embedings-in-conifg.yaml
exporter/otlpexporter/config.go
exporter/otlpexporter/config_test.go
exporter/otlpexporter/factory_test.go
exporter/otlphttpexporter/config.go
exporter/otlphttpexporter/factory.go
exporter/otlphttpexporter/factory_test.go
exporter/otlphttpexporter/otlp.go
internal/e2e/otlphttp_test.go
receiver/otlpreceiver/config.go
receiver/otlpreceiver/config_test.go
receiver/otlpreceiver/factory.go
receiver/otlpreceiver/factory_test.go
receiver/otlpreceiver/otlp.go
receiver/otlpreceiver/otlp_test.go

This PR:
* Helps with https://github.com/open-telemetry/opentelemetry-collector/issues/12709, to avoid the situation where we need to add Unmarshal for a struct and if used as embedded will not work.
* Helps with avoiding name conflicts between variables. Will allow for example to have a "Timeout" member in both QueueConfig and ClientConfig, even though that was a valid YAML config since `QueueConfig` is under "seding_queue".
* This is a breaking change only if devs are created manually the OTLP configs which should be very rare, and unfortunately this is hard to do using deprecation steps.

Avoid using go embedded messages in Config

---

.chloggen/allow-sizer.yaml
exporter/exporterhelper/internal/queue_sender.go
exporter/exporterhelper/internal/queuebatch/queue_batch.go
exporter/exporterhelper/internal/queuebatch/queue_batch_test.go
exporter/exporterhelper/queue_batch.go
exporter/exporterqueue/config.go
exporter/otlpexporter/config_test.go
exporter/otlphttpexporter/config_test.go

Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/12706

Allow users to configure different sizers for memory queue 

---

.github/workflows/prepare-release.yml
docs/release.md

This PR updated the prepare-release workflow so that the version bump just needs to be selected in a dropdown menu instead of putting in the version numbers by hand. Additionally, "no bump" can be selected to not bump specific component sets (beta or stable).
Fixes #12565
Only bumping beta to next minor: [workflow run](https://github.com/mowies/opentelemetry-collector/actions/runs/14059792536) - [release tracker issue](https://github.com/mowies/opentelemetry-collector/issues/17)
Bumping beta and stable to next minor: [workflow run](https://github.com/mowies/opentelemetry-collector/actions/runs/14058979304/job/39364990356) - [release tracker issue](https://github.com/mowies/opentelemetry-collector/issues/16)
Bumping beta and stable to next patch: [workflow …

[chore] Auto-populate versions during release preparation

---

.github/workflows/spell-check.yaml
.github/workflows/utils/cspell.json

Attempting to fix the following failure in CI due to cspell.
> Warning: Unknown word (queuebatch)
> exporter/exporterhelper/internal/queuebatch/metadata.yaml:1:7 Unknown word (queuebatch)
> Files checked: 289, Issues found: 1 in 1 files.
> Error: 1 spelling issue found in 1 of the 289 files checked.

[chore]: Fix cspell

---

.gitignore

Running `make gobenchmark` locally creates individual benchmarks files. This PR adds them to git-ignore list. The combined benchmarks.txt was already ignored.

[chore]: Add benchmark.txt to gitignore

---

.github/workflows/scripts/ping-codeowners-on-new-issue.sh

Code owners should be pinged even if a code owner filed an issue. This helps other code owners, in the case of more than one for a single component, be notified of relevant issues being filed.
This is the same change as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38841, as [requested](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38841#issuecomment-2747326094).

[chore][ping-codeowners-on-new-issue] Ping even if owner filed

---

component/component_test.go
exporter/otlphttpexporter/factory_test.go
internal/memorylimiter/cgroups/mountpoint_test.go
pdata/pcommon/spanid_test.go
pdata/pcommon/trace_state_test.go
pdata/pcommon/traceid_test.go
pdata/pcommon/value_test.go
pdata/pmetric/aggregation_temporality_test.go
pdata/pmetric/exemplar_value_type_test.go
pdata/pmetric/metric_type_test.go
pdata/pmetric/number_data_point_value_type_test.go
pdata/pprofile/aggregation_temporality_test.go
pdata/pprofile/profileid_test.go

This change was caught by the linter in the update of golangci-lint to v2 (see https://github.com/open-telemetry/opentelemetry-collector/pull/12731)

[chore] update tests to use Empty

---

cmd/otelcorecol/go.mod
processor/memorylimiterprocessor/go.mod
processor/processorhelper/xprocessorhelper/go.mod

Update processorhelper to unblock contrib
n/a
n/a
n/a

[chore] Update processorhelper version

---

cmd/builder/internal/builder/config.go
cmd/builder/internal/builder/config_test.go

As titled said, this is not a breaking change, since we only are going to return a different error.

[builder] Remove deprecated OtelColVersion, already an error if used

---

exporter/exporterhelper/README.md

This PR adds the already existing/supported `multiplier` config option to the exporterhelper's readme.

[chore] add missing multiplier option to exporterhelper readme

---

.github/actionlint.yaml
.github/workflows/generate-semantic-conventions-pr.yaml
.github/workflows/lint-workflow-files.yml
Makefile
internal/tools/go.mod
internal/tools/go.sum
internal/tools/tools.go

This pull request builds on the work done in #11493 
This PR introduces Actionlint as part of the project to enable linting of GitHub Workflow files. The changes ensure that Actionlint is installed locally within the project and is automatically run during pull requests to enforce consistency and best practices for workflow files.
- Added a `actionlint` target to the Makefile for running Actionlint on workflow files.
- Added actionlint configuration to `.github/actionlint.yaml`
- update `internal/tools/go.mod` and `internal/tools/go.sum`
- Ignored some shellcheck errors (with comments) since shellcheck isn't always right.
https://github.com/open-telemetry/opentelemetry-collector/issues/9676
- Addresses potential linting errors in workflow files after changes are made.
- The workflow has …

[chore] Added a workflow to lint YAML files using actionlint

---

.chloggen/enhance_config-validation.yaml
otelcol/collector.go
otelcol/collector_test.go
otelcol/testdata/otelcol-cyclic-connector.yaml
otelcol/testdata/otelcol-invalid-connector-unused-exp.yaml
otelcol/testdata/otelcol-invalid-connector-unused-rec.yaml
otelcol/testdata/otelcol-valid-connector-use.yaml
otelcol/unmarshal_dry_run_test.go
service/service.go
service/service_test.go

As described in [#8721](https://github.com/open-telemetry/opentelemetry-collector/issues/8721), the current `validate` command cannot capture improper connector usage errors during a dry run. 
One proposed solution _(as mentioned in [this comment](https://github.com/open-telemetry/opentelemetry-collector/issues/8721#issuecomment-1775393905))_ is to surface configuration errors by instantiating the service during the dry run. However, reviewers preferred statically verifying the errors over instantiating the service (see the [PR #12488 comments](https://github.com/open-telemetry/opentelemetry-collector/pull/12488)).
The validation logic for connectors is located in the [`service/internal/graph`](https://github.com/open-telemetry/opentelemetry-collector/blob/1daa315455d02bac90185027878d858ba …

Statically validate connector config during dry-run.

---

.chloggen/client-metadata-keys.yaml
client/client.go
client/client_test.go

Add support for iterating over the client metadata keys.
At the moment it is only possible to get the values for a known key, which makes it impossible to inspect metadata keys without prior knowledge of all possible keys, e.g. as described in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39157.
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/12804
Trivial addition, added unit tests.
N/A

client: add Metadata.Keys method

---

.chloggen/document_get_factory_interface.yaml
service/hostcapabilities/interfaces.go
service/internal/graph/host.go

The GetFactory method is used by a few receivers in the contrib package (e.g. receiver_creator). This PR adds a new interface to the hostcapabilities package so it can be cast correctly from other packages/components.  
Fixes #

add GetFactory interface to hostcapabilities package

---

renovate.json

As part of the security slam, we've been working to pin digests in GitHub actions. There's some tools that can run through and pin everything, but without the notes and comments of every versioned, it can be difficult to understand what is actually being pinned. Thus, I'm opting to add the [renovate helper](https://docs.renovatebot.com/modules/manager/github-actions/#digest-pinning-and-updating) for this in GitHub actions which should automatically manage version pinning.
Related to [#86](https://github.com/open-telemetry/sig-security/issues/87#issuecomment-2776660785)
Ran `npx --yes --package renovate -- renovate-config-validator renovate.json` after updating the config.

[chore] enable github action pin digest helper in renovatebot

---

README.md
docs/release.md

A few weeks ago, I mentioned to the Collector leads about my intention to resign as maintainer/approver. My current focus on building OllyGarden isn't leaving much room to be an approver or maintainer.
The plan right now is to ramp up again as approver/maintainer in the future once time allows.

[chore] Move jpkrohling to emeritus

---

docs/rfcs/component-universal-telemetry.md

Without this attribute, it's not possible to accurately understand how data flows out of connectors.

[chore] Propose additional attribute for 'otelcol.connector.produced.*' metrics

---

renovate.json

This will avoid future merge conflicts with the packages.

[chore] group github.com/knadh/koanf packages

---

.golangci.yml

Remove exclusion of useless-assert rule from testifylint. 
Also removes golangci-lint config that does not apply

[chore]: clean up golangci-lint

---

.chloggen/fix-attribute-cap.yaml
service/internal/attribute/attribute.go
service/internal/attribute/attribute_test.go
service/internal/graph/graph_test.go

This brings capitalization in line with the attributes defined in the [Pipeline Component Telemetry](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/rfcs/component-universal-telemetry.md#attributes) RFC.

Fix 'otelcol.component.kind' value capitalization

---

.chloggen/fix-too-large-size.yaml
exporter/exporterhelper/internal/queuebatch/memory_queue.go
exporter/exporterhelper/internal/queuebatch/memory_queue_test.go

Without this change, the requests without deadline will block forever until the space is available which will never be.

Reject too large elements to the queue

---

confmap/confmap_test.go
faulty_config.yaml

Adds a test for #12661 and another test present on #11882.
I verified that the first test fails in v0.123.0: on this version the slice has `[]S{A: "A", B: "B"}` instead.

[chore][confmap] Add tests for handling of slices

---

exporter/debugexporter/README.md

Updates example output from the exporter after changes to collector telemetry made in `v0.120.0` via https://github.com/open-telemetry/opentelemetry-collector/pull/12259.

[chore] [exporter/debug] docs: update example output after changes in telemetry

---

.chloggen/use-err.yaml
config/confighttp/confighttp_test.go
extension/extensionauth/extensionauthtest/err.go
extension/extensionauth/extensionauthtest/err_test.go

Make this package consistent with a way more used package https://github.com/open-telemetry/opentelemetry-collector/blob/main/consumer/consumertest/err.go#L15

Use Err prefix for always return error implementation

---

.chloggen/mx-psi_nil-empty-slices.yaml
confmap/confmap.go
confmap/confmap_test.go
confmap/confmaptest/configtest_test.go
confmap/internal/mapstructure/encoder.go
service/config_test.go

A second attempt at #11882.
Note that I added some tests in #12871 to prevent something like #12661 from happening again.
Fixes #11749
See tests from #12871 as well as the new tests added here.

[confmap] Correctly distinguish between empty and nil slices

---

exporter/otlphttpexporter/README.md

Corrected a missing "for" in the extended description to improve readability and grammar.

Fix typo in README.md

---

.chloggen/codeboten_add-attributes-support-telemetry.yaml
cmd/mdatagen/internal/command_test.go
cmd/mdatagen/internal/templates/documentation.md.tmpl
cmd/mdatagen/internal/testdata/with_telemetry.yaml

This adds the ability to generate documentation for the internal metrics attributes.

[mdatagen] support producing docs for internal telemetry attributes

---

.chloggen/exporterhelper-remove-hardcoded-one-worker.yaml
exporter/exporterhelper/internal/queuebatch/queue_batch.go

Remove hardcoding the number of queue workers to one if batching is enabled. The bug described in https://github.com/open-telemetry/opentelemetry-collector/issues/12244 isn't relevant anymore.

[exporterhelper] Do not ignore the `num_consumers` setting when batching is enabled

---

.chloggen/lock-attributes-gate.yaml
internal/telemetry/telemetry.go

PR #12617 introduced logic to inject new instrumentation scope attributes in all internal telemetry to identify which Collector component it came from. These attributes had already been added to internal logs as regular log attributes, and this PR switched them to scope attributes for consistency. The new logic was placed behind an Alpha stage feature gate, `telemetry.newPipelineTelemetry`.
Unfortunately, the default "off" state of the feature gate disabled the injection of component-identifying attributes entirely, which was a regression since they had been present in internal logs in previous releases. See issue #12870 for an in-depth discussion of this issue.
To correct this, PR #12856 was filed, which stabilized the feature gate, making it on by default, with no way to disable it, and …

Put component-identifying scope attributes for internal metrics back behind feature gate

---

.chloggen/storage-full-error.yaml
extension/xextension/storage/storage.go

This adds an error for when the storage extension runs out of space. Extensions can return this error when it's not possible to store data because the maximum allowable/possible space has been reached.
Fixes #12634
I have been working on the filestorage extension and have a draft PR that uses this error: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39667

add storage full error to xextension/storage

---

Makefile

golangci-lint is now able to apply suggested fixes from testifylint with golangci-lint --fix .
This PR removes testifylint-fix target from Makefile.

[chore]: remove testifylint-fix target

---

.chloggen/mx-psi_naming-configauth.yaml
config/configauth/configauth.go
config/configauth/configauth_test.go
config/configgrpc/configgrpc.go
config/configgrpc/configgrpc_test.go
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
exporter/otlpexporter/config_test.go
extension/extensionauth/client.go
extension/extensionauth/server.go
extension/zpagesextension/zpagesextension_test.go
internal/e2e/configauth_test.go
receiver/otlpreceiver/config_test.go

Deprecates `configauth.Authentication` in favor of `configauth.AuthenticationConfig`.
Fixes #12875

[configauth] Deprecate Authentication in favor of authentication.Config

---

.chloggen/12948.yaml
exporter/exporterhelper/internal/queuebatch/config.go
exporter/exporterhelper/internal/queuebatch/config_test.go

Add validation error when queue_size smaller than batch.min_size

---

.github/workflows/scripts/check-merge-freeze.sh

Extend the merge freeze logic in `.github/workflows/scripts/check-merge-freeze.sh` to include open PRs titled "[chore] Update core dependencies" in the `opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib` repository, in addition to the existing check for "[chore] Prepare release" PRs in the core repo.
This ensures that no PRs can be merged into `main` while a core update PR is pending in contrib, helping us avoid version drift and keep dependencies aligned between core and contrib.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12830
Tested locally by:
- Opening a dummy "[chore] Update core dependencies" PR on `opentelemetry-collector-contrib`
- Running the updated `check-merge-freeze.sh` script to confirm it …

Implement a merge freeze when an "[chore] Update core dependencies" PR on opentelemetry-collector-contrib is present

---

service/internal/obsconsumer/logs_test.go
service/internal/obsconsumer/metrics_test.go
service/internal/obsconsumer/option.go
service/internal/obsconsumer/profiles_test.go
service/internal/obsconsumer/traces_test.go

Implements new name for attribute as documented in #12951.
Note: The obsconsumer package is unused until #12812 is merged so this is not a breaking change.

[chore] Update obsconsumer to use new attribute name

---

.chloggen/fix-resource-attributes-internal-console-logger.yaml
service/telemetry/logger.go
service/telemetry/logger_test.go

Propagate `telemetry.resource` to the internal logs.
Fixes #12582

Propagate telemetry.resource to the internal logs

---

docs/component-stability.md

Adds wording regarding testing requirements for stable components. The intent is for the lifecycle tests to be handled via mdatagen.
This follows the work done on open-telemetry/opentelemetry-collector-contrib/issues/39543, with which now we have component coverage per component.
Fixes #11867

[chore] Add testing requirements for stable components

---

.chloggen/codeboten_remove-deprecated-funcs.yaml
config/configauth/configauth.go
extension/extensionauth/extensionauthtest/err.go

Removes:
- configauth.Authentication use configauth.Config instead
- extensionauthtest.NewErrorClient use extensionauthtest.NewErr instead

remove deprecated aliases

---

docs/release.md

This updates the bugfix guidelines to make them less strict. In particular, after this change, we would start releasing bugfix releases under the following cases:
1. Lack of consensus of SIG leads on whether to release a bugfix version within one working day after a report has been made
2. Issues that have not been reported by multiple people, but that are known to be used in production
This also:
- Explicitly lists difficulties with debugging and troubleshooting as 'severe enough'
- Explicitly states that the release manager is responsible for bugfix releases

[chore] Update bugfix release guidelines

---

cmd/mdatagen/internal/loader_test.go
cmd/mdatagen/internal/testdata/empty_test_config.yaml
confmap/confmap_test.go

While working on #12981, I would have found it useful to have these tests, since they surfaced a bug when enabling `DecodeNil`.

[chore] Add tests loading nil to any

---

confmap/confmap.go
confmap/internal/compose_hook.go
confmap/internal/third_party/composehook/compose_hook.go

If we enable `DecodeNil` as true, we may have [untyped nils](https://go.dev/doc/faq#nil_error) being passed. Unfortunately, these are not valid values for `reflect`, which leads to surprising behavior such as golang/go/issues/51649.
Unfortunately, the default hooks from mapstructure do not deal with this properly. To account for this, we:
- Vendor and change the `ComposeDecodeHookFunc` function so that this case is accounted for the kinds of hooks that just won't work with untyped nils
- Create a safe wrapper for the hooks that do work with untyped nils. This wrapper is used in all hooks, but in the interest of keeping as close to what I would imagine upstream will accept, I did not add this to the compose function.
This should not have any end-user observable behavior.
Attempt to work …

[chore] Make mapstructure hooks safe against untyped nils

---

.chloggen/codeboten_remove-internal-semconv-dep.yaml
cmd/builder/internal/builder/main_test.go
cmd/mdatagen/go.mod
cmd/mdatagen/internal/sampleconnector/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_logs.go
cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/samplescraper/internal/metadata/generated_logs.go
cmd/mdatagen/internal/samplescraper/internal/metadata/generated_metrics.go
cmd/mdatagen/internal/templates/logs.go.tmpl
cmd/mdatagen/internal/templates/metrics.go.tmpl
cmd/otelcorecol/builder-config.yaml
cmd/otelcorecol/go.mod
internal/e2e/go.mod
otelcol/go.mod
otelcol/otelcoltest/go.mod
service/go.mod
service/hostcapabilities/go.mod
service/internal/resource/config.go
service/internal/resource/config_test.go
service/service.go
service/telemetry/logger_test.go
service/telemetry/metrics_test.go

This updates the calls to the collector's internal semconv package with otelgo's instead. The main difference is how the keys can be used, they will need to be cast as strings where they key name is needed, otherwise it's not a huge change. This would allow us to stop producing our own semconv package once contrib is moved as well.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/10346, https://github.com/open-telemetry/opentelemetry-collector/issues/11828, https://github.com/open-telemetry/opentelemetry-collector/issues/11807

update semconv dependency to otelgo's semconv package

---

.chloggen/fix-13014.yaml
internal/telemetry/componentattribute/logger_test.go
internal/telemetry/componentattribute/logger_zap.go
service/telemetry/logger.go
service/telemetry/logger_test.go

Avoid re-creating sampler counters every time we wrap with attributes.
Updates #13014

Avoid allocating too much memory, sampling logic is not re-applied

---

.chloggen/mx-psi_decodenil.yaml
confmap/confmap.go
confmap/confmap_test.go

Enables `DecoderConfig.DecodeNil` 
Taken from #10260
Updates #12981

[confmap] Enable `DecodeNil` option

---

exporter/exporterhelper/README.md

The warning does not appear to be relevant any more. It comes from a time when the package provided a factory, and I assume it was warning against using that factory directly within the service pipeline, as opposed to indirectly from another exporter.
N/A
N/A
N/A

[chore] exporter/exporterhelper: remove outdated warning

---

confmap/confmap.go

Clarifies usage of `confmap.Unmarshaler`. This is a limitation that currently exists since mapstructure will fail to map between the types.

[chore] Clarify that Unmarshaler only supports structs

---

.chloggen/context-in-sinks.yaml
consumer/consumertest/sink.go
consumer/consumertest/sink_test.go

This PR enhances the `consumertest.Sink` types (TracesSink, MetricsSink, LogsSink, ProfilesSink) to store and expose request contexts during consumption
Changes include:
- Added context storage to all sink types
- Added `AllContexts()` method to retrieve stored contexts
- Updated `Reset()` to clear stored contexts
- Added comprehensive tests for context transformation verification
Fixes [#13039](https://github.com/open-telemetry/opentelemetry-collector/issues/13039)
Added new test cases to verify context handling:
- `TestSinkContextTransformation`: Verifies context preservation across all sink types
- `TestContextTransformationChain`: Tests complex chains of context transformations
- `TestConcurrentContextTransformations`: Ensures thread-safe context handling
- Added context verification …

Add context handling to sinks in consumertest

---

confmap/confmap.go

Documents the behavior of `ToStringMap` when there are multiple representations available

[chore] Document ToStringMap behavior on values with multiple representations

---

.chloggen/mx-psi_confmap-delete.yaml
confmap/confmap.go
confmap/confmap_test.go

Adds a method to delete a path from a `Conf` object.
I needed this for #13060

[confmap] Add Conf.Delete method

---

.chloggen/pdata-primitive-slices-moveappendto.yaml
pdata/internal/cmd/pdatagen/internal/templates/primitive_slice.go.tmpl
pdata/internal/cmd/pdatagen/internal/templates/primitive_slice_test.go.tmpl
pdata/pcommon/generated_byteslice.go
pdata/pcommon/generated_byteslice_test.go
pdata/pcommon/generated_float64slice.go
pdata/pcommon/generated_float64slice_test.go
pdata/pcommon/generated_int32slice.go
pdata/pcommon/generated_int32slice_test.go
pdata/pcommon/generated_int64slice.go
pdata/pcommon/generated_int64slice_test.go
pdata/pcommon/generated_stringslice.go
pdata/pcommon/generated_stringslice_test.go
pdata/pcommon/generated_uint64slice.go
pdata/pcommon/generated_uint64slice_test.go

pdata primitive slices are missing `MoveAndAppendTo`, and we're going to start needing it with the profiles proto upgrade (which has a dictionary object with primitive type slices that we will need to merge at some point)

Add MoveAndAppendTo to pdata primitive slices

---

processor/README.md
processor/processorhelper/example_test.go

This PR introduces a testable example to the package [processor](/processor).  it's a similar example to the documentation one on https://opentelemetry.io/docs/collector/building/receiver/#designing-and-validating-receiver-settings
the testable example was executed successfully:
this testable example follows https://go.dev/blog/examples#larger-examples format and should be automatically added to `processor` package documentation

Add documentation example for processor package (#5675)

---

.chloggen/ip_fix-event-name-unmarshal-json.yaml
pdata/plog/json.go
pdata/plog/json_test.go

This PR adds missing logic to process `event_name` field when unmarshaling LogRecords from JSON.
Added `eventName` to json (un)marshal tests.
Fixes #13127

fix(pdata/plog): unmarshal event_name from json

---

.chloggen/13110.yaml
service/service.go
service/telemetry/factory.go
service/telemetry/logger.go
service/telemetry/logger_test.go

Fixes #13110
- Improved the unit tests.

Print generated resource attributes for internal logs

---

.chloggen/mx-psi_newdefault-nopointer.yaml
config/configgrpc/configgrpc.go
config/configgrpc/configgrpc_test.go
config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
exporter/otlpexporter/factory.go
receiver/otlpreceiver/config_test.go
receiver/otlpreceiver/factory.go

Some `NewDefault*Config` functions return `*Config`, while others return `Config`. As far as I can tell, this is solely because it was easier to write the code for existing usages of the configs. I think that's not the right approach: in my opinion, we should return either always `Config` or always `*Config`, and the former seems to be more natural to me (since the pointer should never be nil)

Make all NewDefault* functions return structs instead of pointers

---

.chloggen/mapping-equal.yaml
.chloggen/set-mapping.yaml
pdata/pprofile/mapping.go
pdata/pprofile/mapping_test.go
pdata/pprofile/mappings.go
pdata/pprofile/mappings_test.go

This is part of https://github.com/open-telemetry/opentelemetry-collector/issues/13106
It introduces a new `SetMapping` method, which allows setting a location's mapping based on a specific dictionary.
I named the method `SetMapping` and not `PutMapping`, as it overrides the `MappingIndex` value, it doesn't append to a slice.
Contrarily to Locations or Attributes, as location has a single mapping. So we don't need a `FromMappingIndices` method, we can use `MappingSlice.At()` directly.

Introduce SetMapping for profiles

---

.chloggen/internal-trace-sampling.yaml
service/service.go
service/telemetry/internal/migration/testdata/v0.3.0_traces.yaml
service/telemetry/internal/migration/v0.3.0.go

This PR changes the config struct corresponding to `service::telemetry::traces` to embed the full `TracerProvider` config struct from `otelconf`, instead of including only its `Processors` field.
Something similar was previously done for the `MeterProvider` struct in #12433.
This has the effect of letting users enable sampling on internal Collector traces using [the `sampler` section of the declarative config](https://github.com/open-telemetry/opentelemetry-configuration/blob/9c8ff31553a6a48c09fe99a288596e28b63c4cdb/examples/kitchen-sink.yaml#L294).
I couldn't find any relevant issue.
I added a basic example of using the `sampler` to `service/telemetry/internal/migration/testdata/v0.3.0_traces.yaml` to test that we can unmarshal this section properly.
Just a changelog.

Use full TracerProvider config from otelconf

---

pdata/xpdata/go.mod
pdata/xpdata/request/context.go
pdata/xpdata/request/internal/request.pb.go
pdata/xpdata/request/internal/request.proto
pdata/xpdata/request/requesttest.go

Resolves https://github.com/open-telemetry/opentelemetry-collector/pull/13220#discussion_r2153174157
Benchmarks:
```
goos: darwin
goarch: arm64
pkg: go.opentelemetry.io/collector/pdata/xpdata/request
cpu: Apple M1 Max
before:
BenchmarkEncodeDecodeContext-10    	  528876	      2331 ns/op	    1200 B/op	      28 allocs/op
after:
BenchmarkEncodeDecodeContext-10    	  559353	      1832 ns/op	     864 B/op	      16 allocs/op
```

[chore] [exporterhelper] Move to span context marshaling as a message

---

.chloggen/persist-request-context.yaml
pdata/xpdata/request/context.go
pdata/xpdata/request/context_test.go
pdata/xpdata/request/internal/request.pb.go
pdata/xpdata/request/internal/request.proto

Preserve client address in persistent queue as part of the request context 
A follow-up to https://github.com/open-telemetry/opentelemetry-collector/pull/13220

[exporterhelper] Preserve client address in persistent queue

---

.chloggen/pdata-fix-copy-optional-field.yaml
pdata/internal/cmd/pdatagen/internal/base_fields.go
pdata/pmetric/generated_exponentialhistogramdatapoint.go
pdata/pmetric/generated_exponentialhistogramdatapoint_test.go
pdata/pmetric/generated_histogramdatapoint.go
pdata/pmetric/generated_histogramdatapoint_test.go
pdata/pprofile/generated_location.go
pdata/pprofile/generated_location_test.go
pdata/pprofile/generated_sample.go
pdata/pprofile/generated_sample_test.go

If destination has an optional field set to some value but source has it unset, we need to unset the field on the destination instead of keeping the old value.
Found this bug while working on https://github.com/open-telemetry/opentelemetry-collector/pull/13267

[pdata] Fix copying of optional fields when the source is unset

---

pdata/pcommon/slice.go

This was missed in https://github.com/open-telemetry/opentelemetry-collector/pull/13267

[chore] [pdata] Use internal.CopyOrigSlice for pcommon.Slice

---

.github/workflows/sourcecode-release.yaml

During the v0.129.0 release process, the sourcecode-release.yaml workflow [failed](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/15973270037/job/45049168039), during the step that [updates the "next release" milestone](https://github.com/open-telemetry/opentelemetry-collector/blob/8c7e0b7708eeb02f012282f74c6723a58f9cbf2a/.github/workflows/sourcecode-release.yaml#L56). I believe this was because of [this change](https://github.com/open-telemetry/opentelemetry-collector/pull/13240/files#diff-ac51d4c0a4ced767627f2ed87af1fe93f5eba40f8de1d0a4dd5b1b99914e1d88), which accidentally removed the workflow's permission to modify issue milestones.
This PR adds back the appropriate permission explicitly.
([→ Doc page showing that "issues" is the appropriate scope for modifying …

[chore] Fix sourcecode-release workflow permissions

---

pdata/internal/cmd/pdatagen/internal/base_fields.go
pdata/pmetric/generated_exponentialhistogramdatapoint.go
pdata/pmetric/generated_histogramdatapoint.go
pdata/pprofile/generated_location.go
pdata/pprofile/generated_sample.go

Addresses https://github.com/open-telemetry/opentelemetry-collector/pull/13267#discussion_r2168550011

[chore] [pdata] Avoid an allocation when copy an optional field

---

docs/release.md

A few changes:
- Update the section about releasing `collector-contrib` to reflect the fact that the Github release is now automatically populated with the changelog (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38730)
- Update recommendations for dealing with https://github.com/open-telemetry/opentelemetry-go-build-tools/issues/47 with a new workaround (commenting out the unrecognized "merge" entries in `.git/config`)
- Remove what looks like a second reference to the same issue?
- Put myself and Bogdan back at the end of the release rotation
- Correct the date for the release of v0.137.0, which is only one week after v0.136.0. Feel free to tell me if this wasn't a mistake.

Update release procedure document

---

.chloggen/persistent-metadata-data.yaml
exporter/exporterhelper/internal/queue/persistent_queue.go
exporter/exporterhelper/internal/queue/persistent_queue_test.go

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12890

Switch to use the new metadata structure for persistent queue

---

docs/release.md

This PR updates the release procedure doc to reflect the fact that updating tags is no longer possible with "only" write access, you need maintainer-level bypass permissions: see https://github.com/open-telemetry/opentelemetry-collector-releases/issues/998

[chore] Update release troubleshooting guidelines

---

README.md

The badges currently in main branch:
The badges after the fix:
Now the smaller ones are at the same line, makes it looks a little bit better.
Sorry this may looks like a spam PR. I created it as I previously can not make my PR go through the merge queue in this repo, as I am still interested in some work in this repo, I raised this pr to test if my commits / CLA can pass the merge queue now. 
Fixes #

[chore] update readme badges to align the sizes

---

.chloggen/prom_enable_scope_info.yaml
cmd/otelcorecol/go.mod
service/config_test.go
service/internal/promtest/server_util.go
service/telemetry/factory.go
service/telemetry/metrics_test.go

This changes the config for the default Prometheus exporter to remove `disable_scope_info: true`. This prevent errors in the exporter caused by metrics only differentiated by their scope being considered aliasing, which will become more common when the `telemetry.newPipelineTelemetry` feature gate graduates (see tracking issue for details).
I marked this as a "breaking change", but I'm not sure if we make guarantees about the format of the Prometheus metrics we emit?
Fixes #12939
I updated some tests to reflect the additional labels added to Prometheus metrics.
I performed manual testing and confirmed that the reproduction case in the tracking issue no longer emits an error when the feature gate is enabled.

[service] Enable scope information in default Prometheus exporter

---

.chloggen/fix_exporter-PersistRequestContext-fg.yaml
exporter/exporterhelper/internal/queue/fg.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/traces_test.go
exporter/exporterhelper/xexporterhelper/profiles.go
exporter/exporterhelper/xexporterhelper/profiles_test.go

It was ignored before because the PersistRequestContextOnRead and PersistRequestContextOnWrite variables were initialized before the feature gate was set from the command line arguments.
Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/13342

[exporterhelper] Fix exporter.PersistRequestContext feature gate

---

.chloggen/fix-todo-optional.yaml
exporter/exporterhelper/internal/base_exporter.go
exporter/exporterhelper/internal/base_exporter_test.go
exporter/exporterhelper/internal/queue/persistent_queue.go
exporter/exporterhelper/internal/queue/persistent_queue_test.go
exporter/exporterhelper/internal/queue/queue.go
exporter/exporterhelper/internal/queuebatch/config.go
exporter/exporterhelper/internal/queuebatch/config_test.go
exporter/exporterhelper/internal/queuebatch/queue_batch_test.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/traces_test.go
exporter/exporterhelper/xexporterhelper/go.mod
exporter/exporterhelper/xexporterhelper/profiles_test.go

Partially reverts https://github.com/open-telemetry/opentelemetry-collector/pull/13345
`configoptional` cannot unmarshal a scalar preset value yet. See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/16199280314/job/45733970146?pr=41234

[chore] [exporterhelper] Revert moving StorageID to configpoptional

---

CHANGELOG-API.md
CHANGELOG.md

Fixes spelling on release notes

Fix spelling

---

.chloggen/remove-newprofilesexporter.yaml
exporter/exporterhelper/xexporterhelper/profiles.go

This method was deprecated in 0.130.0. Since that release has happened, we can now remove it.
See https://github.com/open-telemetry/opentelemetry-collector/pull/13372

Remove deprecated NewProfilesExporter

---

.github/workflows/add-labels-and-owners.yml
.github/workflows/ping-codeowners-prs.yml

A draft PR is by definition not yet ready for review, and may have further changes that add or remove pings (and we never remove labels and review requests).
So this changes the labels assignement and review requests to only happen for PRs that are ready to be reviewed.
See https://cloud-native.slack.com/archives/C07CCCMRXBK/p1752690459792339

[chore] Only label issues and ping code owners for PRs that are ready to review

---

exporter/exporterhelper/internal/queuebatch/partition_batcher.go
exporter/exporterhelper/internal/queuebatch/partition_batcher_test.go
exporter/exporterhelper/internal/requesttest/request.go
exporter/exporterhelper/logs_batch.go
exporter/exporterhelper/logs_batch_test.go
exporter/exporterhelper/metrics_batch.go
exporter/exporterhelper/metrics_batch_test.go
exporter/exporterhelper/traces_batch.go
exporter/exporterhelper/traces_batch_test.go
exporter/exporterhelper/xexporterhelper/profiles_batch.go
exporter/exporterhelper/xexporterhelper/profiles_batch_test.go

No changelog because if fixes logic added in current release.
Depends on https://github.com/open-telemetry/opentelemetry-collector/pull/13418

[chore] Fix the fix of OOM when size of one item larger than max size 

---

cmd/builder/README.md

Makes it less confusing, especially with provider versions now all aligned on v1.x.

[chore] docs(builder): use more recent version in builder docs

---

docs/release.md

Moves contrib release process to opentelemetry-collector-contrib repository.
Depends on open-telemetry/opentelemetry-collector-contrib/pull/41509.
See also #13464 and open-telemetry/opentelemetry-collector-releases/pull/1034

[chore][docs] Remove release process for contrib and replace with link

---

docs/release.md

Moves 'releases' release process to opentelemetry-collector-contrib repository.
Depends on open-telemetry/opentelemetry-collector-releases/pull/1034.
See also #13463 and open-telemetry/opentelemetry-collector-contrib/pull/41509.

[chore][docs] Remove release process for 'releases' and replace with link

---

.golangci.yml
config/configgrpc/configgrpc_test.go

Enable and fixes [fatcontext](https://golangci-lint.run/usage/linters/#fatcontext) linter

[chore]: enable fatcontext linter

---

.chloggen/fix-unmarshal-json.yaml
pdata/internal/wrapper_entityref.go
pdata/internal/wrapper_entityrefslice.go
pdata/internal/wrapper_map.go
pdata/internal/wrapper_resource.go
pdata/internal/wrapper_stringslice.go
pdata/pcommon/map_test.go
pdata/plog/json_test.go
pdata/pmetric/json_test.go
pdata/pprofile/json_test.go
pdata/ptrace/json_test.go

When Entity was added, we forgot to update the unmarshal logic. Add e2e tests so that this cannot happened in the future.

Fix JSON unmarshal and add e2e tests

---

receiver/otlpreceiver/config.go

Config struct does not prevent unkeyed literal initialization.
#12360

[chore] prevent unkeyed literal initialization

---

.github/workflows/check-merge-freeze.yml

This should fix the recent failure in https://github.com/open-telemetry/opentelemetry-collector/pull/13507

Fix merge queue check

---

pdata/plog/encoding.go
pdata/plog/json.go
pdata/pmetric/json.go
pdata/ptrace/encoding.go
pdata/ptrace/json.go

We used to have Logs/Traces/Metrics in pdata package, not anymore.

[chore] Update comments to remove reference to old pdata package

---

.chloggen/mark_noopTraceProvider_deprecated.yaml
service/telemetry/tracer.go
service/telemetry/tracer_test.go

move service.noopTraceProvider feature gate to deprecated stage
Fixes #13492

[service] move service.noopTraceProvider feature gate to deprecated stage

---

pdata/internal/wrapper_map.go
pdata/internal/wrapper_slice.go
pdata/pcommon/map.go
pdata/pcommon/map_test.go
pdata/pcommon/slice.go
pdata/pcommon/slice_test.go

Applies fixes from https://github.com/open-telemetry/opentelemetry-collector/pull/13522 and https://github.com/open-telemetry/opentelemetry-collector/pull/13523

[chore] Apply improvements and fixes for RemoveIf and CopyOrig to manually writen structs

---

service/service.go
service/telemetry/factory.go

Cleanup - the field is unused, so remove it.
Preparation work for https://github.com/open-telemetry/opentelemetry-collector/issues/4970
N/A, non-functional change.
N/A

[chore] service/telemetry: remove Settings.AsyncErrorChannel

---

confmap/provider/yamlprovider/provider_test.go
connector/forwardconnector/README.md
docs/rfcs/component-universal-telemetry.md
docs/rfcs/processing.md
otelcol/command_print_test.go
pdata/ptrace/doc_test.go
processor/README.md

Non functional change, just updating more documentation to remove references to the batch processor.

[chore] remove more references to the batch processor

---

service/telemetry/tracer.go

The `service.noopTracerProvider` feature gate is now deprecated, and cannot be enabled, therefore we can remove any code that references it.
Relates to https://github.com/open-telemetry/opentelemetry-collector/issues/13492
Manually verified the feature gate cannot be enabled.
None

[chore] service/telemetry: remove deprecated feature gate check

---

renovate.json

Fix syntax following http://docs.renovatebot.com/configuration-options/#ignore-versions-with-negated-regex-syntax
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/13542

[chore] Update renovate.json

---

.github/workflows/spell-check.yaml
.github/workflows/utils/cspell.json

Fixes cspell workflow to:
1. Run only once on PRs instead of one because of the push and one because of the PR
2. Run on all files to avoid issues with the incremental mode
3. Use `globRoot` option to make sure that we ignore the right files (thanks @jade-guiton-dd!)

[chore] Fix ignored paths in cspell CI

---

config/confighttp/confighttp.go
config/confighttp/confighttp_test.go
config/confighttp/xconfighttp/options_test.go
docs/rfcs/optional-config-type.md

I was puzzling over what "hss" meant when looking at confighttp earlier, and realized it's a holdover from when the struct was named `HTTPServerSettings`. This renames the receiver variables for both `ClientConfig` and `ServerConfig` to be initialisms of these two types.

[chore][confighttp] Rename receiver variables

---

.chloggen/optimize-context.yaml
pdata/xpdata/request/context.go

This is a backwards compatible change because on the decoding side we support both single value string as well as slice.

Optimize xpdata/context for persistent queue when only one value for key

---

.chloggen/dep-profiles-dict.yaml
exporter/debugexporter/internal/normal/profiles.go
exporter/debugexporter/internal/normal/profiles_test.go
exporter/debugexporter/internal/otlptext/profiles.go
exporter/debugexporter/internal/otlptext/profiles_test.go
internal/cmd/pdatagen/internal/message_field.go
internal/cmd/pdatagen/internal/pprofile_package.go
pdata/pprofile/generated_profiles.go
pdata/pprofile/generated_profiles_test.go
pdata/pprofile/pb_test.go
pdata/pprofile/profiles.go
pdata/testdata/profile.go

This removes unnecessary duplication of "Profiles" prefix when the struct/package has already profile in it, also brings consistency with proto definition.

Deprecate Profiles.ProfilesDictionary in favor of Profiles.Dictionary.

---

.chloggen/batcher-bug-workers.yaml
exporter/exporterhelper/internal/queuebatch/partition_batcher.go

While working on an unrelated tasks, I observed unrestricted number of `partitionBatcher.flush(..)` being spinned. This resulted in `ConsumeLogs` being called excessively.  
If I understand correctly, we're supposed to return the worker to `qb.workerPool` only when the `consumeFunc` has returned. Right now, we're calling the `consumeFunc` in a background goroutine and returning the worker immediately in the main goroutine. 
Here's the previous behaviour for comparision: https://github.com/open-telemetry/opentelemetry-collector/pull/13164/files#diff-e3328327e734297f98f035f3eb463dc25c06843b82e6d48053020a94df0b9e94L189-L198
Did manual testing and verified the number of goroutines via profiling.

[exporterhelper][batcher] - Fix the bug related to worker pool

---

.chloggen/add-custom-encoder.yaml
pdata/internal/grpcencoding/encoding.go
pdata/plog/plogotlp/grpc.go
pdata/pmetric/pmetricotlp/grpc.go
pdata/pprofile/pprofileotlp/grpc.go
pdata/ptrace/ptraceotlp/grpc.go

This change should not affect other gRPC calls since it fallbacks to the default grpc/proto encoding if requests are not pdata/otlp requests.

Add custom grpc/encoding that replaces proto and calls into our formats first

---

pdata/plog/plogotlp/request.go
pdata/pmetric/pmetricotlp/request.go
pdata/pprofile/pprofileotlp/request.go
pdata/ptrace/ptraceotlp/request.go

The main idea is that the [*]otlp/Request is for http/grpc OTLP communication, but the Marshaler is only marshaling non-protocol specific data.

[chore] Small nits, consistent JSON and Proto logic to call into internal

---

.chloggen/fix-map-copy.yaml
pdata/pcommon/map.go
pdata/pcommon/map_test.go

Updates https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/42350

Avoid copying the pcommon.Map when same origin

---

.chloggen/profiles-remove-add-attribute.yaml
pdata/pprofile/attributes.go
pdata/pprofile/attributes_test.go

This method has been deprecated since 0.126.0.

Remove deprecated AddAttribute method pprofile

---

.chloggen/profiles-otlp-1-8-0.yaml
internal/cmd/pdatagen/internal/pdata/pprofile_package.go
pdata/internal/generated_wrapper_profile.go
pdata/internal/generated_wrapper_profile_test.go
service/internal/graph/obs_test.go

This was missed in my previous PR. The `timestamp_unix_nano` field has changed to be a fixed rather than uint.
See https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/profiles/v1development/profiles.proto#L257

Fix pprofile timestamp unix nano to be a fixed64

---

.github/workflows/check-merge-freeze.yml

This PR changes the criterion which excludes otelbot's "Prepare release" PRs from the merge freeze they cause, so that we check the email address instead of the name of the committer. The address was taken from [otelbot's last commit on its latest PR](https://github.com/open-telemetry/opentelemetry-collector/commit/8e24523e66c3acfeb18dd3086f7f198f3953bae5.patch).
Updates #13789
Hopefully fixes it, but let's wait until next release to see if it worked.

Use email to exclude otelbot from merge freeze

---

.chloggen/remove-profiles-dictionary.yaml
pdata/pprofile/profiles.go

This method has been deprecated for 2 releases already.

Remove deprecated ProfilesDictionary method

---

exporter/exporterhelper/internal/queuebatch/encoding.go
exporter/exporterhelper/internal/queuebatch/logs.go
exporter/exporterhelper/internal/queuebatch/logs_batch.go
exporter/exporterhelper/internal/queuebatch/logs_batch_test.go
exporter/exporterhelper/internal/queuebatch/logs_test.go
exporter/exporterhelper/internal/queuebatch/metrics.go
exporter/exporterhelper/internal/queuebatch/metrics_batch.go
exporter/exporterhelper/internal/queuebatch/metrics_batch_test.go
exporter/exporterhelper/internal/queuebatch/metrics_test.go
exporter/exporterhelper/internal/queuebatch/traces.go
exporter/exporterhelper/internal/queuebatch/traces_batch.go
exporter/exporterhelper/internal/queuebatch/traces_batch_test.go
exporter/exporterhelper/internal/queuebatch/traces_test.go
exporter/exporterhelper/logs.go
exporter/exporterhelper/logs_test.go
exporter/exporterhelper/metrics.go
exporter/exporterhelper/metrics_test.go
exporter/exporterhelper/traces.go
exporter/exporterhelper/traces_test.go
exporter/exporterhelper/xexporterhelper/new_request.go

I forgot to move these symbols in #13821.
Relates to open-telemetry/opentelemetry-collector-contrib/pull/42782, which is how I noticed.
Follows #13821
Updates #11143

[chore] Move missing experimental symbols to xexporterhelper

---

.chloggen/telemetry-tracesconfig-deprecated.yaml
.github/workflows/utils/cspell.json
service/telemetry/telemetry.go

service/telemetry.TracesConfig is deprecated. This type alias has been added to otelconftelemetry.TracesConfig as part of #4970, which is where the otelconf-based telemetry implementation now lives.
Relates to #4970
N/A
N/A

service/telemetry: deprecate TracesConfig

---

.chloggen/README.md
.chloggen/config.yaml
.chloggen/control-attribute-enabled.yaml
.chloggen/fix_cmd_mdata-gen-metrics.yml
.chloggen/mowies-standardize-chloggen-components.yaml
.chloggen/mx-psi_configoptional-1.0.yaml
.chloggen/mx-psi_mark-configauth-as-1.0.yaml
.chloggen/mx-psi_remove-deprecated-symbols-exporterhelper.yaml
.chloggen/stable-use-custom-proto.yaml
.chloggen/telemetry-tracesconfig-deprecated.yaml
.github/workflows/changelog.yml
Makefile

This PR adds some code to generate the list of allowed components for `chloggen`.
All tooling was already prepared previously so we just need to make use of the features.
The PR also adds a CI check to validate the component label in all changelog entries.
Fixes #13923
I added a readme file as a replacement for the code comments in `.chloggen/config.yaml` since those are removed during auto generation of the file.

Standardize changelog component list
